// Perform: scenes, dials and cues over a piece as it plays, for a hand, a
// controller or a game. `set.ts` is the data and its pure helpers;
// `Performer` plays a set on an engine without writing to the score.

export {
  DEFAULT_MORPH_BARS,
  MAX_MORPH_BARS,
  MAX_RIDE,
  PERFORM_FOLLOW_KINDS,
  PERFORM_META_KEY,
  PERFORM_SET_VERSION,
  describePerformFollow,
  drawPerformFollow,
  emptyPerformSet,
  freeId,
  isEmptyPerformSet,
  ladderTargets,
  moveScene,
  normalisePerformSet,
  performSetOf,
  resolvePerformFollow,
  sceneTracksIn,
  shapeDial,
  withCue,
  withDial,
  withScene,
  withoutCue,
  withoutDial,
  withoutScene,
  withoutTrack,
  type PerformCue,
  type PerformDial,
  type PerformDialTarget,
  type PerformFollow,
  type PerformFollowKind,
  type PerformFollowTarget,
  type PerformRange,
  type PerformScene,
  type PerformSet,
} from './set'
export {
  DEFAULT_DIAL_GLIDE_SECONDS,
  DEFAULT_PERFORM_LOOKAHEAD_SECONDS,
  DEFAULT_RESET_SECONDS,
  DIAL_RIDE_LAYER,
  MORPH_TIME_CONSTANTS,
  Performer,
  SCENE_RIDE_LAYER,
  engineStrip,
  type DialOptions,
  type MoveOptions,
  type PerformEvent,
  type PerformEventType,
  type PerformGlide,
  type PerformListener,
  type PerformState,
  type PerformerOptions,
} from './Performer'
