// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Cascade, shared with
// src/dsp/devices/cascade.gen.ts:
//    0  pattern: 0 Mosaic, 1 Strum, 2 Tunnel, 3 Steps, default 0
//    1  time: 60..2000 ms, default 400
//    2  repeats: 1..16, default 5
//    3  decay: 0..1, default 0.4
//    4  high: 0..1, default 0.6
//    5  low: 0..1, default 0
//    6  interval: 0 Octaves, 1 Octaves and fifths, default 0
//    7  shape: 0..1, default 0.5
//    8  reverse: 0..1, default 0
//    9  spread: 0..1, default 0.6
//   10  tone: 800..18000 Hz, default 9000
//   11  mix: 0..1, default 0.5

#pragma once

namespace livemix {
namespace cascade {

enum Param : int {
  kPattern = 0,
  kTime = 1,
  kRepeats = 2,
  kDecay = 3,
  kHigh = 4,
  kLow = 5,
  kInterval = 6,
  kShape = 7,
  kReverse = 8,
  kSpread = 9,
  kTone = 10,
  kMix = 11,
  kNumParams = 12,
};

inline constexpr float kParamMin[kNumParams] = {0.0f, 60.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 800.0f, 0.0f};
inline constexpr float kParamMax[kNumParams] = {3.0f, 2000.0f, 16.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 18000.0f, 1.0f};
inline constexpr float kParamDefault[kNumParams] = {0.0f, 400.0f, 5.0f, 0.4f, 0.6f, 0.0f, 0.0f, 0.5f, 0.0f, 0.6f, 9000.0f, 0.5f};

}  // namespace cascade
}  // namespace livemix
