// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Thesis, shared with
// src/dsp/devices/thesis.gen.ts:
//    0  center: 48..71 note, default 62
//    1  resonance: 5..100, default 40
//    2  width: 0..100 %, default 50
//    3  attack: 0.01..5 s, default 0.5
//    4  release: 0.1..10 s, default 2
//    5  mode: 0 Fixed, 1 Breathe, 2 Drift, 3 Gravity, default 1
//    6  breatheRate: 0.1..2 Hz, default 0.3
//    7  strum: 0..100 ms, default 0
//    8  mirrorEnabled: 0 Off, 1 On, default 1
//    9  octaflipEnabled: 0 Off, 1 On, default 1
//   10  middleEnabled: 0 Off, 1 On, default 0
//   11  mirrorMiddleEnabled: 0 Off, 1 On, default 0
//   12  centerEnabled: 0 Off, 1 On, default 0
//   13  scale: 0 Major, 1 Natural Minor, 2 Harmonic Minor, 3 Melodic Minor, 4 Dorian, 5 Phrygian, 6 Lydian, 7 Mixolydian, 8 Locrian, 9 Pentatonic, 10 Blues, 11 Whole Tone, 12 Chromatic, default 0
//   14  root: 0 C, 1 C#, 2 D, 3 D#, 4 E, 5 F, 6 F#, 7 G, 8 G#, 9 A, 10 A#, 11 B, default 0

#pragma once

namespace livemix {
namespace thesis {

enum Param : int {
  kCenter = 0,
  kResonance = 1,
  kWidth = 2,
  kAttack = 3,
  kRelease = 4,
  kMode = 5,
  kBreatheRate = 6,
  kStrum = 7,
  kMirrorEnabled = 8,
  kOctaflipEnabled = 9,
  kMiddleEnabled = 10,
  kMirrorMiddleEnabled = 11,
  kCenterEnabled = 12,
  kScale = 13,
  kRoot = 14,
  kNumParams = 15,
};

inline constexpr float kParamMin[kNumParams] = {48.0f, 5.0f, 0.0f, 0.01f, 0.1f, 0.0f, 0.1f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
inline constexpr float kParamMax[kNumParams] = {71.0f, 100.0f, 100.0f, 5.0f, 10.0f, 3.0f, 2.0f, 100.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 12.0f, 11.0f};
inline constexpr float kParamDefault[kNumParams] = {62.0f, 40.0f, 50.0f, 0.5f, 2.0f, 1.0f, 0.3f, 0.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};

}  // namespace thesis
}  // namespace livemix
