// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Analog Drive, shared with
// src/dsp/devices/analog-drive.gen.ts:
//    0  drive: 0..1, default 0.3
//    1  circuit: 0 Tape preamp, 1 Console, 2 Transformer, 3 Triode, 4 Pentode, default 0
//    2  push: 0 Off, 1 On, default 0
//    3  lowCut: 20..1000 Hz, default 20
//    4  thump: 0..1, default 0
//    5  tone: -1..1, default 0
//    6  highCut: 1000..20000 Hz, default 20000
//    7  autoGain: 0 Off, 1 On, default 1
//    8  output: -24..12 dB, default 0
//    9  mix: 0..1, default 1

#pragma once

namespace livemix {
namespace analog_drive {

enum Param : int {
  kDrive = 0,
  kCircuit = 1,
  kPush = 2,
  kLowCut = 3,
  kThump = 4,
  kTone = 5,
  kHighCut = 6,
  kAutoGain = 7,
  kOutput = 8,
  kMix = 9,
  kNumParams = 10,
};

inline constexpr float kParamMin[kNumParams] = {0.0f, 0.0f, 0.0f, 20.0f, 0.0f, -1.0f, 1000.0f, 0.0f, -24.0f, 0.0f};
inline constexpr float kParamMax[kNumParams] = {1.0f, 4.0f, 1.0f, 1000.0f, 1.0f, 1.0f, 20000.0f, 1.0f, 12.0f, 1.0f};
inline constexpr float kParamDefault[kNumParams] = {0.3f, 0.0f, 0.0f, 20.0f, 0.0f, 0.0f, 20000.0f, 1.0f, 0.0f, 1.0f};

}  // namespace analog_drive
}  // namespace livemix
