// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Grain, shared with
// src/dsp/devices/grain-synth.gen.ts:
//    0  position: 0..1, default 0.2
//    1  scan: -2..2, default 0.1
//    2  size: 10..2000 ms, default 280
//    3  density: 1..16, default 6
//    4  spray: 0..1, default 0.2
//    5  detune: 0..100 ct, default 6
//    6  octaves: 0..1, default 0.08
//    7  shape: 0..1, default 0
//    8  reverse: 0..1, default 0.15
//    9  attack: 0.005..8 s, default 0.5
//   10  release: 0.05..12 s, default 2
//   11  spread: 0..1, default 0.7
//   12  tone: 200..18000 Hz, default 9000
//   13  volume: -48..6 dB, default -9

#pragma once

namespace livemix {
namespace grain_synth {

enum Param : int {
  kPosition = 0,
  kScan = 1,
  kSize = 2,
  kDensity = 3,
  kSpray = 4,
  kDetune = 5,
  kOctaves = 6,
  kShape = 7,
  kReverse = 8,
  kAttack = 9,
  kRelease = 10,
  kSpread = 11,
  kTone = 12,
  kVolume = 13,
  kNumParams = 14,
};

inline constexpr float kParamMin[kNumParams] = {0.0f, -2.0f, 10.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.005f, 0.05f, 0.0f, 200.0f, -48.0f};
inline constexpr float kParamMax[kNumParams] = {1.0f, 2.0f, 2000.0f, 16.0f, 1.0f, 100.0f, 1.0f, 1.0f, 1.0f, 8.0f, 12.0f, 1.0f, 18000.0f, 6.0f};
inline constexpr float kParamDefault[kNumParams] = {0.2f, 0.1f, 280.0f, 6.0f, 0.2f, 6.0f, 0.08f, 0.0f, 0.15f, 0.5f, 2.0f, 0.7f, 9000.0f, -9.0f};

}  // namespace grain_synth
}  // namespace livemix
