// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Constellation, shared with
// src/dsp/devices/constellation.gen.ts:
//    0  span: 100..8000 ms, default 2400
//    1  stars: 1..12, default 7
//    2  pattern: 0 Spiral, 1 Cluster, 2 Scatter, 3 Ladder, 4 Gather, default 0
//    3  shuffle: 1..16, default 1
//    4  fade: 0..1, default 0.4
//    5  again: 0..1, default 0.35
//    6  tone: 500..16000 Hz, default 7000
//    7  drift: 0..1, default 0.3
//    8  width: 0..1, default 0.8
//    9  mix: 0..1, default 0.4

#pragma once

namespace livemix {
namespace constellation {

enum Param : int {
  kSpan = 0,
  kStars = 1,
  kPattern = 2,
  kShuffle = 3,
  kFade = 4,
  kAgain = 5,
  kTone = 6,
  kDrift = 7,
  kWidth = 8,
  kMix = 9,
  kNumParams = 10,
};

inline constexpr float kParamMin[kNumParams] = {100.0f, 1.0f, 0.0f, 1.0f, 0.0f, 0.0f, 500.0f, 0.0f, 0.0f, 0.0f};
inline constexpr float kParamMax[kNumParams] = {8000.0f, 12.0f, 4.0f, 16.0f, 1.0f, 1.0f, 16000.0f, 1.0f, 1.0f, 1.0f};
inline constexpr float kParamDefault[kNumParams] = {2400.0f, 7.0f, 0.0f, 1.0f, 0.4f, 0.35f, 7000.0f, 0.3f, 0.8f, 0.4f};

}  // namespace constellation
}  // namespace livemix
