// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Tanpura, shared with
// src/dsp/devices/tanpura.gen.ts:
//    0  tuning: 0 Pa, 1 Ma, 2 Ni, default 0
//    1  jawari: 0..1, default 0.6
//    2  speed: 2..12 s, default 5
//    3  decay: 3..30 s, default 12
//    4  detune: 0..8 ct, default 2
//    5  body: 0..1, default 0.4
//    6  spread: 0..1, default 0.5
//    7  volume: -48..6 dB, default -8

#pragma once

namespace livemix {
namespace tanpura {

enum Param : int {
  kTuning = 0,
  kJawari = 1,
  kSpeed = 2,
  kDecay = 3,
  kDetune = 4,
  kBody = 5,
  kSpread = 6,
  kVolume = 7,
  kNumParams = 8,
};

inline constexpr float kParamMin[kNumParams] = {0.0f, 0.0f, 2.0f, 3.0f, 0.0f, 0.0f, 0.0f, -48.0f};
inline constexpr float kParamMax[kNumParams] = {2.0f, 1.0f, 12.0f, 30.0f, 8.0f, 1.0f, 1.0f, 6.0f};
inline constexpr float kParamDefault[kNumParams] = {0.0f, 0.6f, 5.0f, 12.0f, 2.0f, 0.4f, 0.5f, -8.0f};

}  // namespace tanpura
}  // namespace livemix
