// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Skipping Stone, shared with
// src/dsp/devices/skipping-stone.gen.ts:
//    0  first: 20..2000 ms, default 320
//    1  bounce: 0.5..1.5, default 0.8
//    2  skips: 2..16, default 8
//    3  loss: 0..12 dB, default 2.5
//    4  sink: 0..1, default 0.3
//    5  drop: 0..200 ct, default 0
//    6  throw: -1..1, default 0.6
//    7  ripple: 0..1, default 0.35
//    8  again: 0..0.95, default 0
//    9  mix: 0..1, default 0.35

#pragma once

namespace livemix {
namespace skipping_stone {

enum Param : int {
  kFirst = 0,
  kBounce = 1,
  kSkips = 2,
  kLoss = 3,
  kSink = 4,
  kDrop = 5,
  kThrow = 6,
  kRipple = 7,
  kAgain = 8,
  kMix = 9,
  kNumParams = 10,
};

inline constexpr float kParamMin[kNumParams] = {20.0f, 0.5f, 2.0f, 0.0f, 0.0f, 0.0f, -1.0f, 0.0f, 0.0f, 0.0f};
inline constexpr float kParamMax[kNumParams] = {2000.0f, 1.5f, 16.0f, 12.0f, 1.0f, 200.0f, 1.0f, 1.0f, 0.95f, 1.0f};
inline constexpr float kParamDefault[kNumParams] = {320.0f, 0.8f, 8.0f, 2.5f, 0.3f, 0.0f, 0.6f, 0.35f, 0.0f, 0.35f};

}  // namespace skipping_stone
}  // namespace livemix
