// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Generations, shared with
// src/dsp/devices/generations.gen.ts:
//    0  length: 0.5..12 s, default 1.6
//    1  room: 0..1, default 0.5
//    2  resonance: 0..1, default 0.35
//    3  keep: 0..1, default 0.8
//    4  damping: 0..1, default 0.3
//    5  hiss: 0..1, default 0.15
//    6  width: 0..1, default 0.5
//    7  listen: 0 On, 1 Off, default 0
//    8  mix: 0..1, default 0.5

#pragma once

namespace livemix {
namespace generations {

enum Param : int {
  kLength = 0,
  kRoom = 1,
  kResonance = 2,
  kKeep = 3,
  kDamping = 4,
  kHiss = 5,
  kWidth = 6,
  kListen = 7,
  kMix = 8,
  kNumParams = 9,
};

inline constexpr float kParamMin[kNumParams] = {0.5f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
inline constexpr float kParamMax[kNumParams] = {12.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f};
inline constexpr float kParamDefault[kNumParams] = {1.6f, 0.5f, 0.35f, 0.8f, 0.3f, 0.15f, 0.5f, 0.0f, 0.5f};

}  // namespace generations
}  // namespace livemix
