// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Glitch, shared with
// src/dsp/devices/glitch.gen.ts:
//    0  time: 20..2000 ms, default 250
//    1  chance: 0..1, default 0.25
//    2  repeat: 0..1, default 0.7
//    3  skip: 0..1, default 0.4
//    4  reverse: 0..1, default 0.3
//    5  slow: 0..1, default 0.25
//    6  calm: 0..1, default 0.6
//    7  decay: 0..1, default 0.3
//    8  bounce: 0..1, default 0
//    9  octaves: 0..1, default 0
//   10  spread: 0..1, default 0.3
//   11  mix: 0..1, default 1

#pragma once

namespace livemix {
namespace glitch {

enum Param : int {
  kTime = 0,
  kChance = 1,
  kRepeat = 2,
  kSkip = 3,
  kReverse = 4,
  kSlow = 5,
  kCalm = 6,
  kDecay = 7,
  kBounce = 8,
  kOctaves = 9,
  kSpread = 10,
  kMix = 11,
  kNumParams = 12,
};

inline constexpr float kParamMin[kNumParams] = {20.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
inline constexpr float kParamMax[kNumParams] = {2000.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f};
inline constexpr float kParamDefault[kNumParams] = {250.0f, 0.25f, 0.7f, 0.4f, 0.3f, 0.25f, 0.6f, 0.3f, 0.0f, 0.0f, 0.3f, 1.0f};

}  // namespace glitch
}  // namespace livemix
