// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Sympathetic, shared with
// src/dsp/devices/sympathetic.gen.ts:
//    0  root: 0 C, 1 C#, 2 D, 3 D#, 4 E, 5 F, 6 F#, 7 G, 8 G#, 9 A, 10 A#, 11 B, default 0
//    1  mode: 0 Major, 1 Minor, 2 Learn, default 0
//    2  sympathy: 0..1, default 0.5
//    3  strings: 0 4, 1 5, 2 6, 3 7, 4 8, 5 9, 6 10, 7 11, 8 12, 9 13, 10 14, 11 15, 12 16, default 4
//    4  decay: 0.5..10 s, default 3
//    5  mix: 0..1, default 0.5
//    6  width: 0..1, default 0.5

#pragma once

namespace livemix {
namespace sympathetic {

enum Param : int {
  kRoot = 0,
  kMode = 1,
  kSympathy = 2,
  kStrings = 3,
  kDecay = 4,
  kMix = 5,
  kWidth = 6,
  kNumParams = 7,
};

inline constexpr float kParamMin[kNumParams] = {0.0f, 0.0f, 0.0f, 0.0f, 0.5f, 0.0f, 0.0f};
inline constexpr float kParamMax[kNumParams] = {11.0f, 2.0f, 1.0f, 12.0f, 10.0f, 1.0f, 1.0f};
inline constexpr float kParamDefault[kNumParams] = {0.0f, 0.0f, 0.5f, 4.0f, 3.0f, 0.5f, 0.5f};

}  // namespace sympathetic
}  // namespace livemix
