// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Analog Delay, shared with
// src/dsp/devices/analog-delay.gen.ts:
//    0  time: 20..1200 ms, default 380
//    1  feedback: 0..1.1, default 0.45
//    2  modDepth: 0..1, default 0.3
//    3  modRate: 0.05..8 Hz, default 0.6
//    4  tone: 800..8000 Hz, default 3200
//    5  age: 0..1, default 0.3
//    6  intervalA: 0 Off, 1 Octave down, 2 Fifth down, 3 Fourth down, 4 Fourth up, 5 Fifth up, 6 Octave up, default 0
//    7  intervalB: 0 Off, 1 Octave down, 2 Fifth down, 3 Fourth down, 4 Fourth up, 5 Fifth up, 6 Octave up, default 0
//    8  step: 0 1, 1 2, 2 4, 3 8, default 1
//    9  glide: 0..1, default 0
//   10  spread: 0..1, default 0.5
//   11  mix: 0..1, default 0.35

#pragma once

namespace livemix {
namespace analog_delay {

enum Param : int {
  kTime = 0,
  kFeedback = 1,
  kModDepth = 2,
  kModRate = 3,
  kTone = 4,
  kAge = 5,
  kIntervalA = 6,
  kIntervalB = 7,
  kStep = 8,
  kGlide = 9,
  kSpread = 10,
  kMix = 11,
  kNumParams = 12,
};

inline constexpr float kParamMin[kNumParams] = {20.0f, 0.0f, 0.0f, 0.05f, 800.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
inline constexpr float kParamMax[kNumParams] = {1200.0f, 1.1f, 1.0f, 8.0f, 8000.0f, 1.0f, 6.0f, 6.0f, 3.0f, 1.0f, 1.0f, 1.0f};
inline constexpr float kParamDefault[kNumParams] = {380.0f, 0.45f, 0.3f, 0.6f, 3200.0f, 0.3f, 0.0f, 0.0f, 1.0f, 0.0f, 0.5f, 0.35f};

}  // namespace analog_delay
}  // namespace livemix
