// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Guitar, shared with
// src/dsp/devices/guitar.gen.ts:
//    0  pickup: 0..1, default 0.85
//    1  position: 0.05..0.35, default 0.14
//    2  hardness: 0..1, default 0.55
//    3  sustain: 1..30 s, default 9
//    4  tone: 1500..5500 Hz, default 3600
//    5  swell: 0..3 s, default 0
//    6  strum: 0..80 ms, default 18
//    7  shimmer: 0..1.5 Hz, default 0.3
//    8  warmth: 0..1, default 0.3
//    9  volume: -48..6 dB, default -6

#pragma once

namespace livemix {
namespace guitar {

enum Param : int {
  kPickup = 0,
  kPosition = 1,
  kHardness = 2,
  kSustain = 3,
  kTone = 4,
  kSwell = 5,
  kStrum = 6,
  kShimmer = 7,
  kWarmth = 8,
  kVolume = 9,
  kNumParams = 10,
};

inline constexpr float kParamMin[kNumParams] = {0.0f, 0.05f, 0.0f, 1.0f, 1500.0f, 0.0f, 0.0f, 0.0f, 0.0f, -48.0f};
inline constexpr float kParamMax[kNumParams] = {1.0f, 0.35f, 1.0f, 30.0f, 5500.0f, 3.0f, 80.0f, 1.5f, 1.0f, 6.0f};
inline constexpr float kParamDefault[kNumParams] = {0.85f, 0.14f, 0.55f, 9.0f, 3600.0f, 0.0f, 18.0f, 0.3f, 0.3f, -6.0f};

}  // namespace guitar
}  // namespace livemix
