// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Tape Echo, shared with
// src/dsp/devices/tape-echo.gen.ts:
//    0  time: 30..2000 ms, default 380
//    1  feedback: 0..1.1, default 0.45
//    2  heads: 0 One, 1 Two, 2 Three, 3 Dotted, default 0
//    3  wow: 0..1, default 0.25
//    4  flutter: 0..1, default 0.15
//    5  drive: 0..1, default 0.3
//    6  lowCut: 20..800 Hz, default 120
//    7  highCut: 800..16000 Hz, default 4500
//    8  spread: 0..1, default 0.3
//    9  mix: 0..1, default 0.35

#pragma once

namespace livemix {
namespace tape_echo {

enum Param : int {
  kTime = 0,
  kFeedback = 1,
  kHeads = 2,
  kWow = 3,
  kFlutter = 4,
  kDrive = 5,
  kLowCut = 6,
  kHighCut = 7,
  kSpread = 8,
  kMix = 9,
  kNumParams = 10,
};

inline constexpr float kParamMin[kNumParams] = {30.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 20.0f, 800.0f, 0.0f, 0.0f};
inline constexpr float kParamMax[kNumParams] = {2000.0f, 1.1f, 3.0f, 1.0f, 1.0f, 1.0f, 800.0f, 16000.0f, 1.0f, 1.0f};
inline constexpr float kParamDefault[kNumParams] = {380.0f, 0.45f, 0.0f, 0.25f, 0.15f, 0.3f, 120.0f, 4500.0f, 0.3f, 0.35f};

}  // namespace tape_echo
}  // namespace livemix
