import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'ambient-comp',
  jitter: ['attack', 'release'],
  trim: [
    { param: 'makeup', kind: 'db' },
    { param: 'mix', kind: 'mix' },
  ],
  voices: {
    Level: {
      says: 'a slow compressor that evens out swells over seconds',
      brief: 'a slow levelling compressor',
      nouns: ['fader', 'glue'],
      roles: ['glue', 'swell'],
      traits: ['slow', 'clean', 'faint'],
    },
    Glue: {
      says: 'a very gentle compressor that leans on the loudest swells',
      brief: 'a very gentle compressor',
      nouns: ['glue'],
      roles: ['glue'],
      traits: ['slow', 'clean', 'faint'],
    },
    'Hold swells': {
      says: 'a firm, slow compressor that keeps long swells held down',
      brief: 'a swell-holding compressor',
      nouns: ['grip', 'glue'],
      roles: ['glue', 'swell'],
      traits: ['slow', 'clean', 'faint'],
    },
    Lift: {
      says: 'a parallel compressor that lifts quiet playing and tails',
      brief: 'a parallel compressor',
      nouns: ['lift', 'glue'],
      roles: ['glue'],
      traits: ['slow', 'faint'],
    },
    Keys: {
      says: 'a compressor that lets each attack through before it levels',
      brief: 'an even-handed compressor',
      nouns: ['glue'],
      roles: ['glue'],
      traits: ['clean', 'faint'],
    },
    Mic: {
      says: 'a quicker compressor that takes no notice of low rumble',
      brief: 'a quicker compressor',
      nouns: ['glue', 'grip'],
      roles: ['glue'],
      traits: ['clean', 'faint'],
    },
    'Drone bed': {
      says: 'a deep, slow compressor that lifts a quiet bed and holds it',
      brief: 'a deep, slow compressor',
      nouns: ['bed', 'glue'],
      roles: ['glue', 'swell'],
      traits: ['slow'],
    },
    'Slow fader': {
      says: 'a compressor as slow as a hand on a fader',
      brief: 'a fader-slow compressor',
      nouns: ['fader', 'tide'],
      roles: ['swell', 'glue'],
      traits: ['slow', 'clean', 'faint'],
    },
    'Dense pad': {
      says: 'a hard, fast-acting compressor that packs the sound dense',
      brief: 'a dense, hard compressor',
      nouns: ['press', 'grip'],
      roles: ['glue'],
      traits: [],
    },
    'Pluck tamer': {
      says: 'a fast compressor that takes the spike off plucked notes',
      brief: 'a pluck-taming compressor',
      nouns: ['glue', 'grip'],
      roles: ['glue'],
      traits: ['clean', 'faint'],
    },
    Pump: {
      says: 'a hard compressor that ducks each note and surges back up',
      brief: 'a pumping compressor',
      nouns: ['pump', 'surge'],
      roles: ['glue'],
      traits: ['fast'],
    },
    'Long sustain': {
      says: 'a compressor that pulls the tail of every note back up',
      brief: 'a tail-lifting compressor',
      nouns: ['sustain', 'glue'],
      roles: ['glue'],
      traits: [],
    },
    'Peak stop': {
      says: 'a fast, firm compressor that stops only the peaks',
      brief: 'a peak-stopping compressor',
      nouns: ['grip', 'glue'],
      roles: ['glue'],
      traits: ['clean', 'faint'],
    },
    'Raise the quiet': {
      says: 'a low, gentle compressor that brings up everything quiet',
      brief: 'a quiet-raising compressor',
      nouns: ['lift', 'glue'],
      roles: ['glue'],
      traits: [],
    },
    'Ride the mids': {
      says: 'a firm compressor that listens only above the low end',
      brief: 'a mid-listening compressor',
      nouns: ['grip', 'glue'],
      roles: ['glue'],
      traits: [],
    },
    'Sit back': {
      says: 'a gentle compressor that sets the sound a little way back',
      brief: 'a gentle compressor',
      nouns: ['glue'],
      roles: ['glue'],
      traits: ['clean', 'faint'],
    },
  },
}
