import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'ambient-comp',
  jitter: ['attack', 'release'],
  trim: [
    { param: 'makeup', kind: 'db' },
    { param: 'mix', kind: 'mix' },
  ],
  voices: {
    Level: {
      says: 'a slow compressor that evens out swells over seconds',
      brief: 'a slow levelling compressor',
      nouns: ['leveller', 'tide'],
      roles: ['glue'],
      traits: ['slow', 'clean', 'faint', 'whole'],
    },
    Glue: {
      says: 'a very gentle compressor that leans on the loudest swells',
      brief: 'a very gentle compressor',
      nouns: ['leveller', 'tide'],
      roles: ['glue'],
      traits: ['slow', 'clean', 'faint', 'whole'],
    },
    'Hold swells': {
      says: 'a firm, slow compressor that keeps long swells held down',
      brief: 'a swell-holding compressor',
      nouns: ['leveller', 'tide'],
      roles: ['glue'],
      traits: ['slow', 'clean'],
    },
    Lift: {
      says: 'a parallel compressor that lifts quiet playing and tails',
      brief: 'a parallel compressor',
      nouns: ['sustain', 'leveller'],
      roles: ['glue'],
      traits: ['slow', 'faint', 'whole'],
    },
    Keys: {
      says: 'a compressor that lets each attack through before it levels',
      brief: 'an even-handed compressor',
      nouns: ['leveller'],
      roles: ['glue'],
      traits: ['clean', 'faint', 'whole'],
    },
    Mic: {
      says: 'a quick, firm compressor that takes no notice of low rumble',
      brief: 'a quick, firm compressor',
      nouns: ['leveller'],
      roles: ['glue'],
      traits: ['clean'],
    },
    'Drone bed': {
      says: 'a deep, slow compressor that lifts the quiet and holds it',
      brief: 'a deep, slow compressor',
      nouns: ['sustain', 'leveller'],
      roles: ['glue'],
      traits: ['slow'],
    },
    'Slow fader': {
      says: 'a compressor so slow it rides the level over many seconds',
      brief: 'a very slow compressor',
      nouns: ['tide', 'leveller'],
      roles: ['glue'],
      traits: ['slow', 'clean', 'faint'],
    },
    'Dense pad': {
      says: 'a hard, fast-acting compressor that packs the sound dense',
      brief: 'a dense, hard compressor',
      nouns: ['sustain', 'leveller'],
      roles: ['glue'],
      traits: [],
    },
    'Pluck tamer': {
      says: 'a fast compressor that takes the spike off every attack',
      brief: 'a spike-taming compressor',
      nouns: ['leveller'],
      roles: ['glue'],
      traits: ['fast', 'clean'],
    },
    Pump: {
      says: 'a hard compressor that ducks each note and surges back up',
      brief: 'a pumping compressor',
      nouns: ['leveller'],
      roles: ['glue'],
      traits: ['fast'],
    },
    'Long sustain': {
      says: 'a compressor that pulls the tail of every note back up',
      brief: 'a tail-lifting compressor',
      nouns: ['sustain', 'leveller'],
      roles: ['glue'],
      traits: [],
    },
    'Peak stop': {
      says: 'a fast, firm compressor that stops only the peaks',
      brief: 'a peak-stopping compressor',
      nouns: ['leveller'],
      roles: ['glue'],
      traits: ['fast', 'clean'],
    },
    'Raise the quiet': {
      says: 'a low, gentle compressor that brings up everything quiet',
      brief: 'a quiet-raising compressor',
      nouns: ['sustain', 'leveller'],
      roles: ['glue'],
      traits: [],
    },
    'Ride the mids': {
      says: 'a firm compressor driven by the mids, not by the bass',
      brief: 'a mid-driven compressor',
      nouns: ['leveller'],
      roles: ['glue'],
      traits: [],
    },
    'Sit back': {
      says: 'a gentle compressor that draws loud and quiet together',
      brief: 'a gentle compressor',
      nouns: ['leveller'],
      roles: ['glue'],
      traits: ['clean', 'faint', 'whole'],
    },
  },
}
