import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'ambient-eq',
  jitter: ['clearTime'],
  trim: [],
  voices: {
    Open: {
      says: 'a flat equaliser with nothing cut or lifted',
      brief: 'a flat equaliser',
      nouns: ['tone'],
      roles: [],
      traits: ['clean', 'faint'],
      skip: 'Every band is flat and both cuts are out of the path: it is the device at rest and changes nothing.',
    },
    Layer: {
      says: 'a low cut that clears the bottom and dips the low mids',
      brief: 'a low cut and a low-mid dip',
      nouns: ['tone', 'filter'],
      roles: ['tone'],
      traits: ['clean', 'faint'],
    },
    Drone: {
      says: 'a subsonic cut with the low mids and the presence eased',
      brief: 'a small dip in the low mids',
      nouns: ['tone'],
      roles: ['tone'],
      traits: ['clean', 'faint', 'whole'],
    },
    Texture: {
      says: 'a low cut that thins the bass, with a little air on top',
      brief: 'a cut that thins the bass',
      nouns: ['tone', 'filter', 'air'],
      roles: ['tone'],
      traits: ['clean', 'cold'],
    },
    Keys: {
      says: 'a rumble cut and a small lift of presence',
      brief: 'a small lift of presence',
      nouns: ['tone'],
      roles: ['tone'],
      traits: ['clean', 'faint', 'whole'],
    },
    Voice: {
      says: 'a low cut with the low mids dipped and the presence lifted',
      brief: 'a low cut and some presence',
      nouns: ['tone', 'filter'],
      roles: ['tone'],
      traits: ['clean', 'faint'],
    },
    Master: {
      says: 'a subsonic cut and a slow easing of any note that rings on',
      brief: 'a subsonic cut',
      nouns: ['tone', 'filter'],
      roles: ['tone'],
      traits: ['clean', 'faint', 'whole'],
    },
    Shaded: {
      says: 'a gentle high cut that shades the top end',
      brief: 'a shaded top end',
      nouns: ['filter', 'tone'],
      roles: ['tone'],
      traits: ['dark'],
    },
    Warm: {
      says: 'an equaliser that adds lows and body and eases the top',
      brief: 'a bass lift and an eased top',
      nouns: ['tone'],
      roles: ['tone'],
      traits: ['warm', 'dark'],
    },
    Bright: {
      says: 'a big lift of presence and air',
      brief: 'a lift of presence and air',
      nouns: ['tone', 'air'],
      roles: ['tone'],
      traits: ['bright'],
    },
    Thin: {
      says: 'a thin band of tone with the lows cut and the top rolled off',
      brief: 'a thin band of tone',
      nouns: ['filter', 'tone'],
      roles: ['tone'],
      traits: ['cold'],
    },
    Deep: {
      says: 'a big lift of the low end that puts weight under the sound',
      brief: 'a big lift of the low end',
      nouns: ['tone', 'weight'],
      roles: ['tone'],
      traits: ['warm', 'dark'],
    },
    Distant: {
      says: 'an equaliser that takes presence, air and lows away',
      brief: 'a dulled, thinned tone',
      nouns: ['tone', 'filter'],
      roles: ['tone'],
      traits: ['far', 'dark'],
    },
    Muffled: {
      says: 'a high cut set low enough to muffle everything',
      brief: 'a muffling high cut',
      nouns: ['filter', 'tone'],
      roles: ['tone'],
      traits: ['dark', 'warm'],
    },
    Hollow: {
      says: 'a scooped tone with lows and highs up and the body down',
      brief: 'a scooped, hollow tone',
      nouns: ['tone'],
      roles: ['tone'],
      traits: ['bright'],
    },
    Forward: {
      says: 'a mid-forward tone with the lows and the top trimmed',
      brief: 'a mid-forward tone',
      nouns: ['tone'],
      roles: ['tone'],
      traits: ['warm', 'dark'],
    },
  },
}
