import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'ambient-eq',
  jitter: ['clearTime'],
  trim: [],
  voices: {
    Open: {
      says: 'a flat equaliser with nothing cut or lifted',
      brief: 'a flat equaliser',
      nouns: ['tone'],
      roles: [],
      traits: ['clean', 'faint'],
      skip: 'Every band is flat and both cuts are out of the path: it is the device at rest and changes nothing.',
    },
    Layer: {
      says: 'a low cut and a small dip in the low mids, to make room',
      brief: 'a low cut and a low-mid dip',
      nouns: ['tone', 'filter'],
      roles: ['tone'],
      traits: ['clean', 'faint'],
    },
    Drone: {
      says: 'a subsonic cut with the low mids and presence eased a touch',
      brief: 'a slightly eased equaliser',
      nouns: ['tone', 'curve'],
      roles: ['tone'],
      traits: ['clean', 'faint'],
    },
    Texture: {
      says: 'a low cut that thins the bass, with a little air on top',
      brief: 'a low cut with some air',
      nouns: ['tone', 'filter', 'air'],
      roles: ['tone'],
      traits: ['clean', 'faint'],
    },
    Keys: {
      says: 'a rumble cut and a single decibel of presence',
      brief: 'a touch of presence',
      nouns: ['tone', 'curve'],
      roles: ['tone'],
      traits: ['clean', 'faint'],
    },
    Voice: {
      says: 'a low cut with the low mids dipped and the presence lifted',
      brief: 'a low cut and some presence',
      nouns: ['tone', 'filter'],
      roles: ['tone'],
      traits: ['clean', 'faint'],
    },
    Master: {
      says: 'a subsonic cut and a slow ear that eases whatever rings on',
      brief: 'a ring-easing equaliser',
      nouns: ['tone', 'filter'],
      roles: ['tone'],
      traits: ['clean', 'faint'],
    },
    Shaded: {
      says: 'a gentle high cut that shades the top end',
      brief: 'a shaded top end',
      nouns: ['shade', 'tone', 'filter'],
      roles: ['tone'],
      traits: ['dark', 'faint'],
    },
    Warm: {
      says: 'an equaliser that adds lows and body and eases the top',
      brief: 'a warm, full equaliser',
      nouns: ['tone', 'curve'],
      roles: ['tone'],
      traits: ['warm', 'dark', 'faint'],
    },
    Bright: {
      says: 'a big lift of presence and air, with ringing held in check',
      brief: 'a lift of presence and air',
      nouns: ['air', 'tone', 'shelf'],
      roles: ['tone'],
      traits: ['bright'],
    },
    Thin: {
      says: 'a thin band of tone with the lows cut and the top rolled off',
      brief: 'a thin band of tone',
      nouns: ['band', 'filter', 'tone'],
      roles: ['tone'],
      traits: ['cold'],
    },
    Deep: {
      says: 'a heavy low shelf that puts weight under the sound',
      brief: 'a heavy low shelf',
      nouns: ['shelf', 'weight', 'tone'],
      roles: ['tone'],
      traits: ['warm', 'dark', 'faint'],
    },
    Distant: {
      says: 'an equaliser that takes presence, air and lows away',
      brief: 'a far-off, dulled tone',
      nouns: ['tone', 'filter'],
      roles: ['tone'],
      traits: ['far', 'dark', 'faint'],
    },
    Muffled: {
      says: 'a high cut set low enough to muffle everything',
      brief: 'a muffling high cut',
      nouns: ['filter', 'blanket', 'tone'],
      roles: ['tone'],
      traits: ['dark', 'warm'],
    },
    Hollow: {
      says: 'a scooped tone with lows and highs up and the body down',
      brief: 'a scooped, hollow tone',
      nouns: ['scoop', 'tone', 'curve'],
      roles: ['tone'],
      traits: ['bright', 'faint'],
    },
    Forward: {
      says: 'a mid-forward tone with the lows and the top trimmed',
      brief: 'a mid-forward tone',
      nouns: ['tone', 'curve'],
      roles: ['tone'],
      traits: ['warm', 'faint'],
    },
  },
}
