import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'analog-drive',
  jitter: [],
  trim: [
    { param: 'output', kind: 'db' },
    { param: 'mix', kind: 'mix' },
  ],
  voices: {
    'Warm glue': {
      says: 'a tape preamp pushed just enough to add weight',
      brief: 'a warm tape preamp',
      nouns: ['preamp', 'tape', 'glue'],
      roles: ['drive', 'glue'],
      traits: ['warm', 'faint'],
    },
    'Tape weight': {
      says: 'a tape preamp driven for thick lows and a dull top',
      brief: 'a thick, dull tape preamp',
      nouns: ['tape', 'weight', 'preamp'],
      roles: ['drive'],
      traits: ['warm', 'dark'],
    },
    Console: {
      says: 'a console channel driven until it is firm in the mids',
      brief: 'a driven console channel',
      nouns: ['console', 'desk', 'channel'],
      roles: ['drive'],
      traits: ['bright', 'faint'],
    },
    'Iron lows': {
      says: 'a transformer driven so the low end thickens and loosens',
      brief: 'a low-heavy transformer',
      nouns: ['iron', 'coil'],
      roles: ['drive'],
      traits: ['warm', 'faint'],
    },
    'Triode glow': {
      says: 'a triode valve stage, smoothly overdriven',
      brief: 'a smooth triode stage',
      nouns: ['valve', 'triode', 'glow'],
      roles: ['drive'],
      traits: ['warm'],
    },
    Bite: {
      says: 'a lean pentode valve stage with a bite on every attack',
      brief: 'a biting pentode stage',
      nouns: ['valve', 'pentode', 'bite'],
      roles: ['drive'],
      traits: ['bright', 'cold'],
    },
    Crushed: {
      says: 'an overloaded console channel, half under the clean sound',
      brief: 'an overloaded console',
      nouns: ['console', 'fuzz', 'desk'],
      roles: ['drive'],
      traits: ['worn'],
    },
    'Dark fuzz': {
      says: 'a dark fuzz from a triode pushed far past its limit',
      brief: 'a dark valve fuzz',
      nouns: ['fuzz', 'valve'],
      roles: ['drive'],
      traits: ['dark', 'warm'],
    },
    'Parallel grit': {
      says: 'thin pentode grit mixed in under the clean sound',
      brief: 'thin grit under the clean',
      nouns: ['grit', 'valve', 'edge'],
      roles: ['drive'],
      traits: ['bright', 'cold'],
    },
    'First hint': {
      says: 'the first hint of weight from a tape preamp',
      brief: 'a hint of tape preamp',
      nouns: ['preamp', 'tape'],
      roles: ['drive'],
      traits: ['warm', 'faint'],
    },
    'Low warmth': {
      says: 'a transformer that fills out the lows and dulls the top',
      brief: 'a low, warm transformer',
      nouns: ['iron', 'weight', 'coil'],
      roles: ['drive'],
      traits: ['warm', 'dark', 'faint'],
    },
    Sheen: {
      says: 'a bright, lean console channel driven for an edge on top',
      brief: 'a bright driven console',
      nouns: ['sheen', 'console', 'desk'],
      roles: ['drive'],
      traits: ['bright', 'cold'],
    },
    'Worn tape': {
      says: 'a tape preamp overloaded until it breaks up, dull and thick',
      brief: 'an overloaded tape preamp',
      nouns: ['tape', 'reel', 'fuzz'],
      roles: ['drive', 'wear'],
      traits: ['worn', 'dark', 'warm'],
    },
    'Iron melt': {
      says: 'a transformer overloaded into a thick, loose fuzz',
      brief: 'an overloaded transformer',
      nouns: ['iron', 'fuzz', 'coil'],
      roles: ['drive'],
      traits: ['worn', 'warm'],
    },
    'Torn cone': {
      says: 'a pentode pushed into a folded-over fuzz, thin and torn',
      brief: 'a torn, folded-over fuzz',
      nouns: ['fuzz', 'cone', 'rasp'],
      roles: ['drive'],
      traits: ['worn', 'strange'],
    },
    'Hot channel': {
      says: 'a console channel run hot with its level pulled back down',
      brief: 'a hot console channel',
      nouns: ['channel', 'console', 'desk'],
      roles: ['drive'],
      traits: ['faint'],
    },
  },
}
