import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'analog-delay',
  jitter: ['time', 'modRate'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    'Dark echo': {
      says: 'a bucket-brigade echo whose soft repeats dull as they fade',
      brief: 'a soft bucket-brigade echo',
      nouns: ['echo', 'repeats'],
      roles: ['echo'],
      traits: ['warm', 'dark'],
    },
    Chorused: {
      says: 'a bucket-brigade echo with a slow chorus on its repeats',
      brief: 'a chorused echo',
      nouns: ['echo'],
      roles: ['echo'],
      traits: ['wide', 'warm'],
    },
    Seasick: {
      says: 'a short echo whose pitch sways like a seasick vibrato',
      brief: 'a seasick short echo',
      nouns: ['wobble', 'echo', 'sway'],
      roles: ['echo'],
      traits: ['unsteady', 'wide', 'fast'],
    },
    Murky: {
      says: 'a slow murky bucket-brigade echo with dull, worn repeats',
      brief: 'a murky slow echo',
      nouns: ['echo', 'murk', 'repeats'],
      roles: ['echo'],
      traits: ['dark', 'worn', 'warm'],
    },
    Slapback: {
      says: 'a soft slapback echo close behind each note',
      brief: 'a soft slapback echo',
      nouns: ['echo'],
      roles: ['room', 'echo'],
      traits: ['short', 'faint'],
    },
    'Octave hop': {
      says: 'an echo whose repeats jump up an octave and back',
      brief: 'an octave-hopping echo',
      nouns: ['echo', 'octave', 'steps'],
      roles: ['echo', 'pitch'],
      traits: ['warm', 'high'],
    },
    'Fifth hop': {
      says: 'an echo whose repeats hop up a fifth and down a fourth',
      brief: 'a fifth-hopping echo',
      nouns: ['echo', 'fifths', 'steps'],
      roles: ['echo', 'pitch'],
      traits: ['warm'],
    },
    'Falling tape': {
      says: 'an echo that slides down an octave like tape slowed by hand',
      brief: 'a sinking octave echo',
      nouns: ['echo', 'octave'],
      roles: ['echo', 'pitch'],
      traits: ['low', 'unsteady', 'worn', 'wide'],
    },
    Runaway: {
      says: 'a bucket-brigade echo fed back until it becomes a drone',
      brief: 'a runaway echo',
      nouns: ['drone', 'echo'],
      roles: [],
      traits: ['long', 'heavy', 'wide'],
      skip: 'Its feedback is above one, so the repeats never die away: half a minute on it is still at its loudest.',
    },
    'Faint halo': {
      says: 'a faint, dull echo with a slow chorus on it',
      brief: 'a faint chorused echo',
      nouns: ['trace', 'echo'],
      roles: ['echo'],
      traits: ['faint', 'dark'],
    },
    'Clean echo': {
      says: 'a clean, steady echo with no wobble and little dulling',
      brief: 'a clean steady echo',
      nouns: ['echo', 'repeats'],
      roles: ['echo'],
      traits: ['clean'],
    },
    Doubler: {
      says: 'a wavering double of the sound spread wide to both sides',
      brief: 'a wide wavering double',
      nouns: ['wobble', 'chorus'],
      roles: ['width'],
      traits: ['wide', 'short', 'unsteady'],
    },
    'Slow drift': {
      says: 'a wide echo whose repeats drift slowly in pitch',
      brief: 'a slowly drifting echo',
      nouns: ['drift', 'echo'],
      roles: ['echo'],
      traits: ['wide', 'slow', 'unsteady'],
    },
    'Noisy clock': {
      says: 'a slow, dull, worn-out echo with hiss riding on its repeats',
      brief: 'a worn-out, hissing echo',
      nouns: ['echo'],
      roles: ['echo'],
      traits: ['dark', 'worn', 'noisy'],
    },
    'Slow lurch': {
      says: 'an echo that now and then lurches down a fifth and back',
      brief: 'a lurching echo',
      nouns: ['echo'],
      roles: ['echo', 'pitch'],
      traits: ['unsteady', 'strange'],
    },
    Fluttering: {
      says: 'an echo with a fast flutter in the pitch of its repeats',
      brief: 'a fluttering echo',
      nouns: ['flutter', 'echo'],
      roles: ['echo'],
      traits: ['unsteady', 'fast'],
    },
  },
}
