import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'analog-drive',
  jitter: [],
  trim: [
    { param: 'output', kind: 'db' },
    { param: 'mix', kind: 'mix' },
  ],
  voices: {
    'Warm glue': {
      says: 'a tape preamp pushed just enough to add weight',
      brief: 'a warm tape preamp',
      nouns: ['preamp', 'tape'],
      roles: ['drive', 'glue'],
      traits: ['warm', 'faint'],
    },
    'Tape weight': {
      says: 'a tape preamp driven for thick lows and a dull top',
      brief: 'a thick, dull tape preamp',
      nouns: ['preamp', 'tape'],
      roles: ['drive'],
      traits: ['warm', 'dark'],
    },
    Console: {
      says: 'a console channel driven until it is firm in the mids',
      brief: 'a driven console channel',
      nouns: ['preamp'],
      roles: ['drive'],
      traits: ['bright', 'faint'],
    },
    'Iron lows': {
      says: 'a transformer driven so the low end thickens and loosens',
      brief: 'a low-heavy transformer',
      nouns: ['warmth'],
      roles: ['drive'],
      traits: ['warm'],
    },
    'Triode glow': {
      says: 'a triode valve stage, smoothly overdriven',
      brief: 'a smooth triode stage',
      nouns: ['valves', 'glow'],
      roles: ['drive'],
      traits: ['warm'],
    },
    Bite: {
      says: 'a lean pentode valve stage with a bite on every attack',
      brief: 'a biting pentode stage',
      nouns: ['valves', 'grit'],
      roles: ['drive'],
      traits: ['bright', 'cold'],
    },
    Crushed: {
      says: 'an overloaded console channel under the clean sound',
      brief: 'an overloaded console',
      nouns: ['grit'],
      roles: ['drive'],
      traits: ['worn'],
    },
    'Dark fuzz': {
      says: 'a dark fuzz from a valve pushed far past its limit',
      brief: 'a dark valve fuzz',
      nouns: ['fuzz', 'valves'],
      roles: ['drive'],
      traits: ['dark', 'warm'],
    },
    'Parallel grit': {
      says: 'thin valve grit mixed in under the clean sound',
      brief: 'a thin layer of valve grit',
      nouns: ['grit', 'valves'],
      roles: ['drive'],
      traits: ['bright', 'cold'],
    },
    'First hint': {
      says: 'the first hint of weight from a tape preamp',
      brief: 'a hint of tape preamp',
      nouns: ['preamp', 'tape'],
      roles: ['drive'],
      traits: ['warm', 'faint', 'whole'],
    },
    'Low warmth': {
      says: 'a transformer that fills out the lows and dulls the top',
      brief: 'a low-thickening transformer',
      nouns: ['warmth'],
      roles: ['drive'],
      traits: ['warm', 'dark'],
    },
    Sheen: {
      says: 'a bright, lean console channel driven for an edge on top',
      brief: 'a bright driven console',
      nouns: ['sheen'],
      roles: ['drive'],
      traits: ['bright', 'cold'],
    },
    'Worn tape': {
      says: 'a tape preamp overloaded until it breaks up, dull and thick',
      brief: 'an overloaded tape preamp',
      nouns: ['tape'],
      roles: ['drive'],
      traits: ['worn', 'dark', 'warm'],
    },
    'Iron melt': {
      says: 'a thick, loose fuzz from an overloaded transformer',
      brief: 'an overloaded transformer',
      nouns: ['fuzz'],
      roles: ['drive'],
      traits: ['worn', 'warm'],
    },
    'Torn cone': {
      says: 'a thin, torn fuzz from a valve pushed until it folds over',
      brief: 'a torn, folded-over fuzz',
      nouns: ['fuzz', 'grit'],
      roles: ['drive'],
      traits: ['worn', 'strange'],
    },
    'Hot channel': {
      says: 'a hot console channel, forward in the upper mids',
      brief: 'a hot console channel',
      nouns: ['preamp'],
      roles: ['drive'],
      traits: ['faint'],
    },
  },
}
