import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'auto-filter',
  jitter: ['lfoRateHz', 'envAttackMs', 'envReleaseMs'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    Init: {
      says: 'a gentle low-pass at a kilohertz',
      brief: 'a gentle low-pass',
      nouns: ['filter'],
      roles: [],
      traits: ['dark', 'faint'],
      skip: "The device's blank default patch: a plain low-pass at a kilohertz with nothing moving, which only muffles what stands before it.",
    },
    'Low-pass gate': {
      says: 'a steep low-pass that removes all above four hundred hertz',
      brief: 'a steep dark low-pass',
      nouns: ['filter'],
      roles: ['tone'],
      traits: ['dark'],
    },
    'Touch wah': {
      says: 'a band-pass wah over the dry sound, opening with each note',
      brief: 'a touch wah',
      nouns: ['wah', 'filter'],
      roles: ['motion'],
      traits: ['fast'],
    },
    'Dub sweep': {
      says: 'a resonant low-pass that swings open about every two seconds',
      brief: 'a swinging resonant low-pass',
      nouns: ['sweep', 'filter'],
      roles: ['motion'],
      traits: ['strange'],
    },
    Squelch: {
      says: 'a squelching low-pass ramping open about four times a second',
      brief: 'a squelching low-pass',
      nouns: ['filter'],
      roles: ['pulse'],
      traits: ['fast', 'strange'],
    },
    Stepped: {
      says: 'a narrow band-pass that jumps about eight times a second',
      brief: 'a randomly stepping filter',
      nouns: ['filter'],
      roles: ['pulse'],
      traits: ['fast', 'strange'],
    },
    'Rumble cut': {
      says: 'a steep high-pass at eighty hertz',
      brief: 'a rumble cut',
      nouns: ['filter'],
      roles: [],
      traits: ['faint', 'clean'],
      skip: 'A high-pass at eighty hertz with nothing on the bench for it to cut: 0.2 dB off the dry sound and no change in level.',
    },
    'Phone line': {
      says: 'a gritty band-pass as narrow as the sound of a telephone',
      brief: 'a telephone band-pass',
      nouns: ['filter'],
      roles: ['wear', 'drive'],
      traits: ['cold', 'worn'],
    },
    'Slow notch': {
      says: 'a single notch drifting slowly up and down the spectrum',
      brief: 'a slowly drifting notch',
      nouns: ['filter', 'sweep'],
      roles: ['motion'],
      traits: ['faint', 'slow'],
    },
    'Resonant peak': {
      says: 'a resonant upper-mid peak that rises when played hard',
      brief: 'a resonant peak up high',
      nouns: ['filter'],
      roles: ['motion'],
      traits: ['bright'],
    },
    Screaming: {
      says: 'an overdriven low-pass at full resonance with a fast wobble',
      brief: 'a screaming driven filter',
      nouns: ['filter'],
      roles: ['drive', 'pulse'],
      traits: ['dark', 'strange', 'fast'],
    },
    'Tremolo filter': {
      says: 'a low-pass snapping shut and open about eight times a second',
      brief: 'a fast chopping low-pass',
      nouns: ['filter'],
      roles: ['pulse'],
      traits: ['fast'],
    },
    'Glacial low-pass': {
      says: 'a low-pass that opens and closes over about half a minute',
      brief: 'a half-minute low-pass sweep',
      nouns: ['filter', 'tide'],
      roles: ['motion'],
      traits: ['slow', 'dark'],
    },
    'Falling high-pass': {
      says: 'a resonant high-pass falling for about two seconds at a time',
      brief: 'a falling high-pass',
      nouns: ['filter', 'sweep'],
      roles: ['motion'],
      traits: ['fast'],
    },
    'Soft bloom': {
      says: 'a dark low-pass that each note nudges open a moment late',
      brief: 'a dark low-pass that blooms',
      nouns: ['bloom', 'filter'],
      roles: ['swell'],
      traits: ['dark', 'warm'],
    },
    'Loud goes dark': {
      says: 'a low-pass that closes as the playing gets louder',
      brief: 'a low-pass shut by loudness',
      nouns: ['filter'],
      roles: [],
      traits: ['faint', 'dark'],
      skip: 'At the level the bench plays, its filter never closes far enough to hear: 0.0 to 0.3 dB off the dry sound and no change in level.',
    },
  },
}
