import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'bloom-reverb',
  jitter: ['decay'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    Bloom: {
      says: 'a reverb whose tail drifts up towards the octave as it rings',
      brief: 'a tail that drifts upwards',
      nouns: ['bloom', 'halo', 'drift'],
      roles: ['halo'],
      traits: ['high'],
    },
    'Rising fifths': {
      says: 'a reverb whose tail drifts up towards the fifth as it rings',
      brief: 'a tail that rises a fifth',
      nouns: ['fifths', 'halo', 'bloom'],
      roles: ['halo'],
      traits: ['slow'],
    },
    'Winter drift': {
      says: 'a dark reverb whose tail sags slowly out of tune',
      brief: 'a dark sagging tail',
      nouns: ['drift', 'frost', 'halo'],
      roles: ['halo'],
      traits: ['dark', 'unsteady', 'slow', 'strange'],
    },
    'Octave halo': {
      says: 'a reverb whose tail climbs nearly an octave as it rings',
      brief: 'a tail climbing an octave',
      nouns: ['halo', 'octave', 'bloom'],
      roles: ['halo'],
      traits: ['high'],
    },
    Scatter: {
      says: 'a mellow reverb whose tail splits upwards and downwards',
      brief: 'a tail that splits both ways',
      nouns: ['scatter', 'halo', 'spray'],
      roles: ['halo'],
      traits: ['dark', 'slow'],
    },
    'Long dark': {
      says: 'a long dark reverb whose tail sinks slowly in pitch',
      brief: 'a long dark sinking tail',
      nouns: ['night', 'depths', 'halo'],
      roles: ['halo', 'hall'],
      traits: ['dark', 'long', 'slow', 'low'],
    },
    'Still room': {
      says: 'a plain short room whose tail stays at pitch',
      brief: 'a plain still room',
      nouns: ['room', 'chamber'],
      roles: ['room'],
      traits: ['clean'],
    },
    'Falling fifths': {
      says: 'a mellow reverb whose tail drifts down towards the fifth',
      brief: 'a tail that falls a fifth',
      nouns: ['fifths', 'halo', 'autumn'],
      roles: ['halo'],
      traits: ['dark', 'slow'],
    },
    'Glass scatter': {
      says: 'a reverb whose tail scatters to pitches out of tune',
      brief: 'a tail scattered out of tune',
      nouns: ['shards', 'glass', 'scatter'],
      roles: ['halo', 'grain'],
      traits: ['strange', 'unsteady'],
    },
    'Tail alone': {
      says: 'the drifting tail of a long reverb with no dry sound',
      brief: 'a drifting tail alone',
      nouns: ['tail', 'halo', 'wash'],
      roles: ['halo', 'hall'],
      traits: ['heavy', 'far', 'wide', 'dark', 'slow'],
    },
    'Narrow cellar': {
      says: 'a dark cellar of a room that folds the sound to mono',
      brief: 'a dark mono cellar',
      nouns: ['cellar', 'room', 'vault'],
      roles: ['room'],
      traits: ['narrow', 'dark'],
    },
    'Wide summer': {
      says: 'a full reverb with the whole sound pushed extra wide',
      brief: 'an extra-wide reverb',
      nouns: ['summer', 'span', 'halo'],
      roles: ['halo', 'width'],
      traits: ['wide', 'bright'],
    },
    'Faint glow': {
      says: 'a faint short reverb with a slight upward drift',
      brief: 'a faint glow of reverb',
      nouns: ['glow', 'halo', 'trace'],
      roles: ['halo', 'room'],
      traits: ['faint'],
    },
    'Endless rise': {
      says: 'a very long reverb whose tail keeps climbing by octaves',
      brief: 'a long climbing tail',
      nouns: ['rise', 'ascent', 'halo'],
      roles: ['halo', 'hall'],
      traits: ['long', 'heavy', 'wide', 'high', 'slow'],
    },
    'Quick sparkle': {
      says: 'a short room whose tail splits towards a fifth up and down',
      brief: 'a short scattering room',
      nouns: ['sparkle', 'room', 'glint'],
      roles: ['room', 'halo'],
      traits: ['short'],
    },
    'Smooth climb': {
      says: 'a reverb whose tail slides smoothly upwards out of key',
      brief: 'a tail that slides upwards',
      nouns: ['climb', 'glide', 'halo'],
      roles: ['halo'],
      traits: ['unsteady', 'strange', 'slow'],
    },
  },
}
