import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'bloom-reverb',
  jitter: ['decay'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    Bloom: {
      says: 'a reverb whose tail drifts up towards the octave as it rings',
      brief: 'a reverb that drifts upwards',
      nouns: ['bloom', 'halo', 'drift'],
      roles: ['halo'],
      traits: ['high'],
    },
    'Rising fifths': {
      says: 'a reverb whose tail drifts up towards the fifth as it rings',
      brief: 'a reverb that rises a fifth',
      nouns: ['fifths', 'halo', 'bloom'],
      roles: ['halo'],
      traits: ['high', 'slow'],
    },
    'Winter drift': {
      says: 'a dark reverb whose tail sags slowly out of tune',
      brief: 'a dark sagging reverb',
      nouns: ['drift', 'frost', 'halo'],
      roles: ['halo'],
      traits: ['dark', 'low', 'unsteady', 'slow', 'strange'],
    },
    'Octave halo': {
      says: 'a reverb whose tail climbs nearly an octave as it rings',
      brief: 'a reverb climbing an octave',
      nouns: ['halo', 'octave', 'bloom'],
      roles: ['halo'],
      traits: ['high'],
    },
    Scatter: {
      says: 'a mellow reverb whose tail splits up and down in pitch',
      brief: 'a reverb splitting in pitch',
      nouns: ['halo', 'bloom', 'drift'],
      roles: ['halo'],
      traits: ['dark', 'slow'],
    },
    'Long dark': {
      says: 'a long dark reverb whose tail sinks slowly in pitch',
      brief: 'a long dark sinking reverb',
      nouns: ['depths', 'halo'],
      roles: ['halo', 'hall'],
      traits: ['dark', 'long', 'slow', 'low'],
    },
    'Still room': {
      says: 'a plain room that is gone in a couple of seconds',
      brief: 'a plain short room',
      nouns: ['room', 'chamber'],
      roles: ['room'],
      traits: ['clean'],
    },
    'Falling fifths': {
      says: 'a mellow reverb whose tail drifts down towards the fifth',
      brief: 'a reverb that falls a fifth',
      nouns: ['fifths', 'halo'],
      roles: ['halo'],
      traits: ['dark', 'low', 'slow'],
    },
    'Glass scatter': {
      says: 'a reverb whose tail scatters to pitches out of tune',
      brief: 'a reverb scattered off pitch',
      nouns: ['grains', 'halo'],
      roles: ['halo', 'grain'],
      traits: ['strange', 'unsteady'],
    },
    'Tail alone': {
      says: 'the drifting tail of a long reverb with no dry sound',
      brief: 'a drifting reverb tail alone',
      nouns: ['halo', 'wash'],
      roles: ['halo', 'hall'],
      traits: ['heavy', 'far', 'long', 'wide', 'dark', 'slow'],
    },
    'Narrow cellar': {
      says: 'a dark cellar of a room that folds the sound to mono',
      brief: 'a dark mono cellar',
      nouns: ['cellar', 'room'],
      roles: ['room'],
      traits: ['narrow', 'dark'],
    },
    'Wide summer': {
      says: 'a gently rising reverb with the whole sound made extra wide',
      brief: 'an extra-wide reverb',
      nouns: ['halo', 'bloom'],
      roles: ['halo'],
      traits: ['wide', 'bright', 'high'],
    },
    'Faint glow': {
      says: 'a faint short reverb with a slight upward drift',
      brief: 'a faint glow of reverb',
      nouns: ['glow', 'halo', 'trace'],
      roles: ['halo', 'room'],
      traits: ['faint'],
    },
    'Endless rise': {
      says: 'a very long reverb whose tail keeps climbing by octaves',
      brief: 'a long climbing reverb',
      nouns: ['ascent', 'halo'],
      roles: ['halo', 'hall'],
      traits: ['long', 'heavy', 'wide', 'high', 'slow'],
    },
    'Quick sparkle': {
      says: 'a short bright room whose tail splits a fifth up and down',
      brief: 'a short bright room',
      nouns: ['sparkle', 'room', 'glint'],
      roles: ['room', 'halo'],
      traits: ['short', 'bright'],
    },
    'Smooth climb': {
      says: 'a reverb whose tail slides smoothly upwards out of key',
      brief: 'a reverb that slides upwards',
      nouns: ['halo', 'drift', 'ascent'],
      roles: ['halo'],
      traits: ['high', 'unsteady', 'strange', 'slow'],
    },
  },
}
