import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'cascade',
  jitter: ['time'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    'Octave stack': {
      says: 'little loops of each note stacked one and two octaves up',
      brief: 'a stack of octave loops',
      nouns: ['cascade', 'stack', 'octaves'],
      roles: ['grain', 'pitch'],
      traits: ['bright', 'high'],
    },
    'Glass rain': {
      says: 'a fast glittering stutter of plucked octaves over each note',
      brief: 'a glittering octave stutter',
      nouns: ['rain', 'glass', 'glitter'],
      roles: ['grain', 'pitch'],
      traits: ['bright', 'high', 'fast', 'cold'],
    },
    'Slow tiles': {
      says: 'slow loops of each phrase that swell in at several octaves',
      brief: 'slow swelling octave loops',
      nouns: ['tiles', 'cascade', 'wash'],
      roles: ['grain', 'pitch'],
      traits: ['slow', 'long'],
    },
    Restruck: {
      says: 'the start of each note struck again in a bouncing run',
      brief: 'a run of restruck attacks',
      nouns: ['strikes', 'strum', 'volley'],
      roles: ['grain', 'echo'],
      traits: ['fast'],
    },
    'Long drone': {
      says: 'a piece of each note looped into a long, swelling drone',
      brief: 'a long looped drone',
      nouns: ['drone', 'tunnel', 'loop'],
      roles: ['grain', 'hold'],
      traits: ['long', 'slow'],
    },
    'Rising steps': {
      says: 'each note replayed as an arpeggio of octaves and fifths',
      brief: 'an arpeggio of replays',
      nouns: ['steps', 'arpeggio', 'ladder'],
      roles: ['grain', 'pitch', 'echo'],
      traits: ['high', 'bright', 'fast'],
    },
    Undertow: {
      says: 'dark backwards loops of each note and its octave below',
      brief: 'a dark backwards undertow',
      nouns: ['undertow', 'tide', 'loops'],
      roles: ['grain', 'pitch'],
      traits: ['dark', 'low', 'backwards', 'warm'],
    },
    'Sparkle bed': {
      says: 'a soft wash of octave and fifth loops over each note',
      brief: 'a wash of octaves and fifths',
      nouns: ['sparkle', 'bed', 'wash'],
      roles: ['grain', 'pitch', 'halo'],
      traits: ['high', 'bright'],
    },
    'Dropped marbles': {
      says: "a quick rattle of each note's start, like dropped marbles",
      brief: 'a rattle of restruck notes',
      nouns: ['marbles', 'rattle', 'clatter'],
      roles: ['grain'],
      traits: ['fast', 'short'],
    },
    'Deep drone': {
      says: 'a dark drone looped from each note with the octave below',
      brief: 'a deep dark looped drone',
      nouns: ['drone', 'depths', 'tunnel'],
      roles: ['grain', 'hold', 'pitch'],
      traits: ['dark', 'low', 'long', 'slow', 'heavy'],
    },
    'Drone of fifths': {
      says: 'a drone looped from each note with the fifth above it',
      brief: 'a looped drone in fifths',
      nouns: ['drone', 'fifths'],
      roles: ['grain', 'pitch', 'hold'],
      traits: [],
    },
    'Slow staircase': {
      says: 'each phrase climbing in slow soft steps, an octave at a time',
      brief: 'a slow staircase of octaves',
      nouns: ['staircase', 'steps', 'stairs'],
      roles: ['grain', 'pitch', 'echo'],
      traits: ['slow'],
    },
    'Phrase returns': {
      says: 'whole phrases coming back three times, each one duller',
      brief: 'a phrase that comes back',
      nouns: ['returns', 'phrase', 'echo'],
      roles: ['echo', 'grain'],
      traits: ['slow'],
    },
    'Faint halo': {
      says: 'a faint swell of octave loops behind each note',
      brief: 'a faint halo of octaves',
      nouns: ['halo', 'trace', 'glow'],
      roles: ['grain', 'halo'],
      traits: ['faint'],
    },
    'Backwards stack': {
      says: 'loops of each note played backwards at stacked octaves',
      brief: 'a backwards octave stack',
      nouns: ['stack', 'cascade', 'mirror'],
      roles: ['grain', 'pitch'],
      traits: ['backwards', 'bright', 'high'],
    },
    'Only the echoes': {
      says: 'a wide wash of octave loops with no dry sound left in it',
      brief: 'a wide wash of loops alone',
      nouns: ['echoes', 'wash', 'cascade'],
      roles: ['grain', 'pitch', 'halo'],
      traits: ['heavy', 'far', 'wide', 'long', 'bright', 'high'],
    },
  },
}
