import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'chorus',
  jitter: ['rate', 'delayMs'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    'Wide chorus': {
      says: 'a three-voice chorus spread wide across the sides',
      brief: 'a wide three-voice chorus',
      nouns: ['chorus', 'voices'],
      roles: ['motion', 'width'],
      traits: ['wide'],
    },
    'Classic chorus': {
      says: 'a plain two-voice chorus with a voice towards each side',
      brief: 'a plain two-voice chorus',
      nouns: ['chorus', 'pair'],
      roles: ['motion', 'width'],
      traits: ['wide'],
    },
    'Lush ensemble': {
      says: 'a thick three-voice ensemble chorus that turns slowly',
      brief: 'a slow ensemble chorus',
      nouns: ['ensemble', 'chorus'],
      roles: ['motion', 'width'],
      traits: ['wide', 'slow'],
    },
    'Subtle widener': {
      says: 'a light two-voice chorus that widens more than it moves',
      brief: 'a light widening chorus',
      nouns: ['chorus', 'width'],
      roles: ['width', 'motion'],
      traits: ['faint', 'slow'],
    },
    Vibrato: {
      says: 'a fast warble of two voices pulling against each other',
      brief: 'a fast two-voice warble',
      nouns: ['warble', 'flutter'],
      roles: ['pulse'],
      traits: ['fast', 'unsteady'],
    },
    'Guitar shimmer': {
      says: 'a three-voice chorus that leaves the lows dry and steady',
      brief: 'a chorus above the lows',
      nouns: ['chorus', 'ripple'],
      roles: ['motion', 'width'],
      traits: ['wide'],
    },
    'Deep sea': {
      says: 'a deep slow chorus on a long delay, swaying over seconds',
      brief: 'a deep slow chorus',
      nouns: ['chorus', 'sway', 'tide'],
      roles: ['motion', 'width'],
      traits: ['slow', 'wide'],
    },
    'Vocal thickener': {
      says: 'a shallow three-voice chorus that thickens above the lows',
      brief: 'a shallow thickening chorus',
      nouns: ['chorus', 'double'],
      roles: ['width', 'motion'],
      traits: ['faint', 'slow'],
    },
    'Metallic comb': {
      says: 'a short chorus with heavy feedback that rings like metal',
      brief: 'a ringing metallic chorus',
      nouns: ['comb', 'metal', 'chorus'],
      roles: ['motion'],
      traits: ['cold', 'wide', 'strange'],
    },
    'Slow drift': {
      says: 'three voices drifting over a cycle of about twelve seconds',
      brief: 'three slowly drifting voices',
      nouns: ['drift', 'chorus', 'voices'],
      roles: ['motion', 'width'],
      traits: ['slow', 'wide'],
    },
    'Faint air': {
      says: 'a trace of chorus on the top of the sound only',
      brief: 'a trace of chorus on top',
      nouns: ['air', 'chorus'],
      roles: ['width', 'motion'],
      traits: ['faint', 'slow'],
    },
    'Loose double': {
      says: 'two late copies either side, like loose double-tracking',
      brief: 'two loose late copies',
      nouns: ['double', 'takes', 'chorus'],
      roles: ['width', 'motion'],
      traits: ['wide', 'slow'],
    },
    'Hollow swell': {
      says: 'a hollow three-voice chorus swelling over about ten seconds',
      brief: 'a hollow swelling chorus',
      nouns: ['swell', 'chorus', 'hollow'],
      roles: ['motion'],
      traits: ['slow', 'wide'],
    },
    'Fast flutter': {
      says: 'a quick flutter of three voices over the dry sound',
      brief: 'a quick three-voice flutter',
      nouns: ['flutter', 'chorus'],
      roles: ['pulse'],
      traits: ['fast', 'unsteady'],
    },
    'Voices only': {
      says: 'three detuned voices spread hard apart with no dry sound',
      brief: 'three voices, no dry sound',
      nouns: ['voices', 'chorus'],
      roles: ['width', 'motion'],
      traits: ['wide', 'slow', 'unsteady'],
    },
    'Warped tape': {
      says: 'a deep pitch wobble in the centre, like a warped tape',
      brief: 'a warped-tape wobble',
      nouns: ['wobble', 'warp', 'tape'],
      roles: ['motion', 'wear'],
      traits: ['unsteady', 'worn'],
    },
  },
}
