import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'chorus',
  jitter: ['rate', 'delayMs'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    'Wide chorus': {
      says: 'a full chorus spread wide to left and right',
      brief: 'a wide full chorus',
      nouns: ['chorus'],
      roles: ['motion', 'width'],
      traits: ['wide'],
    },
    'Classic chorus': {
      says: 'a plain chorus with a detuned copy towards each side',
      brief: 'a plain chorus',
      nouns: ['chorus'],
      roles: ['motion', 'width'],
      traits: ['wide'],
    },
    'Lush ensemble': {
      says: 'a thick ensemble chorus turning about every two seconds',
      brief: 'a thick ensemble chorus',
      nouns: ['chorus'],
      roles: ['motion', 'width'],
      traits: ['wide'],
    },
    'Subtle widener': {
      says: 'a light chorus that widens more than it moves',
      brief: 'a light widening chorus',
      nouns: ['chorus'],
      roles: ['width', 'motion'],
      traits: ['faint', 'slow'],
    },
    Vibrato: {
      says: 'a fast vibrato that warbles the whole sound in pitch',
      brief: 'a fast pitch warble',
      nouns: ['vibrato', 'warble', 'flutter'],
      roles: ['pulse'],
      traits: ['fast', 'unsteady'],
    },
    'Guitar shimmer': {
      says: 'a chorus on the upper range that leaves the lows steady',
      brief: 'a chorus above the lows',
      nouns: ['chorus', 'ripple'],
      roles: ['motion', 'width'],
      traits: ['wide'],
    },
    'Deep sea': {
      says: 'a deep slow chorus on a long delay, swaying over seconds',
      brief: 'a deep slow chorus',
      nouns: ['chorus', 'sway', 'tide'],
      roles: ['motion', 'width'],
      traits: ['slow', 'wide'],
    },
    'Vocal thickener': {
      says: 'a shallow chorus that thickens the sound above its lows',
      brief: 'a shallow thickening chorus',
      nouns: ['chorus'],
      roles: ['width', 'motion'],
      traits: ['faint'],
    },
    'Metallic comb': {
      says: 'a short chorus with heavy feedback that rings like metal',
      brief: 'a ringing metallic chorus',
      nouns: ['chorus'],
      roles: ['motion'],
      traits: ['cold', 'wide', 'strange'],
    },
    'Slow drift': {
      says: 'a wide chorus drifting over a cycle of about twelve seconds',
      brief: 'a slowly drifting chorus',
      nouns: ['drift', 'chorus'],
      roles: ['motion', 'width'],
      traits: ['slow', 'wide'],
    },
    'Faint air': {
      says: 'a trace of chorus on the top of the sound only',
      brief: 'a trace of chorus on top',
      nouns: ['chorus', 'air'],
      roles: ['width', 'motion'],
      traits: ['faint', 'slow'],
    },
    'Loose double': {
      says: 'a late copy on each side, like the same part played twice',
      brief: 'a loose late copy each side',
      nouns: ['chorus'],
      roles: ['width', 'motion'],
      traits: ['wide', 'slow'],
    },
    'Hollow swell': {
      says: 'a hollow chorus that swells over about ten seconds',
      brief: 'a hollow swelling chorus',
      nouns: ['swell', 'chorus'],
      roles: ['motion'],
      traits: ['slow', 'wide'],
    },
    'Fast flutter': {
      says: 'a quick shallow chorus flutter over the dry sound',
      brief: 'a quick chorus flutter',
      nouns: ['flutter', 'chorus'],
      roles: ['pulse'],
      traits: ['fast', 'unsteady'],
    },
    'Voices only': {
      says: 'a chorus heard alone, its detuned copies spread hard apart',
      brief: 'a chorus with no dry sound',
      nouns: ['chorus'],
      roles: ['width', 'motion'],
      traits: ['wide', 'slow', 'unsteady'],
    },
    'Warped tape': {
      says: 'a deep pitch wobble in the centre, like a warped tape',
      brief: 'a warped-tape wobble',
      nouns: ['wobble'],
      roles: ['motion'],
      traits: ['unsteady', 'worn'],
    },
  },
}
