import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'echo-memory',
  jitter: ['time', 'reach', 'size'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    Recalling: {
      says: 'a soft echo while earlier phrases drift back under it',
      brief: 'an echo that recalls phrases',
      nouns: ['memory', 'echo'],
      roles: ['loop', 'echo'],
      traits: ['long'],
    },
    'Far back': {
      says: 'whole phrases from up to about a minute ago, drifting back',
      brief: 'phrases from a minute back',
      nouns: ['memory', 'past'],
      roles: [],
      traits: ['long', 'slow'],
      skip: 'It goes on recalling for about a minute, so half a minute after the playing stops it is louder than at ten seconds: the bench reads it as growing.',
    },
    Flickers: {
      says: 'quick glimpses of notes just played that flicker about',
      brief: 'flickers of recent notes',
      nouns: ['flickers', 'memory'],
      roles: ['grain', 'loop'],
      traits: ['fast', 'long'],
    },
    Backwards: {
      says: 'recalled moments that mostly come back reversed or slowed',
      brief: 'reversed recollections',
      nouns: ['memory', 'echo'],
      roles: ['loop', 'echo'],
      traits: ['backwards', 'low', 'long'],
    },
    'Hazy past': {
      says: 'dull memories of earlier phrases, many reversed or slowed',
      brief: 'dull hazy recollections',
      nouns: ['haze', 'memory', 'past'],
      roles: ['loop'],
      traits: ['dark', 'far', 'backwards', 'low', 'long'],
    },
    'Plain echo': {
      says: 'a plain echo that is a little darker on each repeat',
      brief: 'a plain darkening echo',
      nouns: ['echo', 'repeats'],
      roles: ['echo'],
      traits: ['clean'],
    },
    Gathering: {
      says: 'earlier phrases that return over and over and slowly gather',
      brief: 'gathering recollections',
      nouns: ['memory', 'layers'],
      roles: ['loop', 'hold'],
      traits: ['long', 'slow'],
    },
    'Minute ago': {
      says: 'a slow dark echo with a whole phrase recalled now and then',
      brief: 'a slow echo and late recalls',
      nouns: ['memory', 'past'],
      roles: [],
      traits: ['long', 'slow', 'dark'],
      skip: 'It recalls a phrase only every several seconds from up to a minute back, so it is louder half a minute on than at ten seconds: the bench reads it as growing.',
    },
    'No echo': {
      says: 'earlier moments of the playing that keep drifting back',
      brief: 'moments drifting back',
      nouns: ['memory'],
      roles: ['loop'],
      traits: ['long'],
    },
    'Faint recall': {
      says: 'a faint echo and faint recollections behind the playing',
      brief: 'faint recollections',
      nouns: ['trace', 'memory'],
      roles: ['loop', 'echo'],
      traits: ['faint', 'long'],
    },
    'Dark trail': {
      says: 'a slow echo with a long dark trail and a few recollections',
      brief: 'a slow dark-trailing echo',
      nouns: ['trail', 'echo'],
      roles: ['echo', 'loop'],
      traits: ['dark', 'long', 'slow'],
    },
    'Side to side': {
      says: 'a plain echo whose repeats bounce from side to side',
      brief: 'a side-to-side echo',
      nouns: ['echo'],
      roles: ['echo'],
      traits: ['wide', 'clean'],
    },
    Swarm: {
      says: 'short glimpses of the last seconds that swarm and pile up',
      brief: 'a swarm of short glimpses',
      nouns: ['flickers', 'cloud'],
      roles: ['grain', 'loop'],
      traits: ['heavy', 'long', 'fast', 'strange'],
    },
    'Late return': {
      says: 'an echo about four seconds late over older recalled phrases',
      brief: 'a very late echo and recalls',
      nouns: ['echo', 'memory'],
      roles: ['echo', 'loop'],
      traits: ['long', 'slow'],
    },
    'Just now': {
      says: 'short moments of the last few seconds replayed as they were',
      brief: 'replays of the last seconds',
      nouns: ['memory', 'replay'],
      roles: ['loop', 'echo'],
      traits: ['clean'],
    },
    Glimpses: {
      says: 'a quick slapback echo over short glimpses of earlier notes',
      brief: 'a close echo and glimpses',
      nouns: ['glimpses', 'memory'],
      roles: ['loop', 'grain'],
      traits: [],
    },
  },
}
