import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'ether-reverb',
  jitter: ['predelayMs'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    Ether: {
      says: 'a bright wide room that rings for a second or two',
      brief: 'a bright wide room',
      nouns: ['room', 'chamber'],
      roles: ['room'],
      traits: ['bright', 'wide'],
    },
    Room: {
      says: 'a small damped room that is over within a second',
      brief: 'a small damped room',
      nouns: ['room'],
      roles: ['room'],
      traits: ['short'],
    },
    Cathedral: {
      says: 'a huge bright space with a wide and very long tail',
      brief: 'a huge bright cathedral',
      nouns: ['cathedral', 'vault', 'wash'],
      roles: ['hall'],
      traits: ['long', 'bright', 'wide'],
    },
    Frozen: {
      says: 'a huge room frozen on the first sound that enters it',
      brief: 'a frozen huge room',
      nouns: ['freeze', 'room'],
      roles: [],
      traits: ['frozen', 'heavy', 'wide', 'long'],
      skip: 'Its freeze holds the first sound for good and mutes all that is played after, until the switch is turned off by hand.',
    },
    'Small booth': {
      says: 'a small dead booth that is gone almost at once',
      brief: 'a small dead booth',
      nouns: ['booth', 'room'],
      roles: ['room'],
      traits: ['short', 'faint'],
    },
    'Faint air': {
      says: 'a trace of room around the sound',
      brief: 'a trace of room',
      nouns: ['air', 'room'],
      roles: ['room'],
      traits: ['faint'],
    },
    'Bright chamber': {
      says: 'a bright wide chamber that is over in about a second',
      brief: 'a bright chamber',
      nouns: ['chamber', 'room'],
      roles: ['room'],
      traits: ['short', 'bright', 'wide'],
    },
    'Dark hall': {
      says: 'a fully damped hall with a few seconds of tail',
      brief: 'a damped hall',
      nouns: ['hall'],
      roles: ['hall'],
      traits: ['dark', 'wide'],
    },
    'Slap room': {
      says: 'a small room that answers about an eighth of a second late',
      brief: 'a late small room',
      nouns: ['slap', 'room'],
      roles: ['room'],
      traits: ['short'],
    },
    'Late hall': {
      says: 'a wide hall that answers about a fifth of a second late',
      brief: 'a late-arriving hall',
      nouns: ['hall', 'answer'],
      roles: ['hall'],
      traits: ['wide'],
    },
    'Shining tail': {
      says: 'a long undamped tail kept low behind the sound',
      brief: 'a long undamped tail',
      nouns: ['tail', 'hall', 'wash'],
      roles: ['hall'],
      traits: ['long', 'wide', 'bright'],
    },
    'Dark infinite': {
      says: 'a damped hall whose tail lasts ten seconds and more',
      brief: 'a very long damped hall',
      nouns: ['hall', 'wash', 'depths'],
      roles: ['hall'],
      traits: ['long', 'dark', 'wide'],
    },
    Distant: {
      says: 'a room heard from its far end with little dry sound left',
      brief: 'a far-off room',
      nouns: ['room', 'distance'],
      roles: ['room'],
      traits: ['far', 'wide', 'bright'],
    },
    'Soft freeze': {
      says: 'a small dark room frozen on the first sound that enters it',
      brief: 'a frozen small room',
      nouns: ['freeze', 'room'],
      roles: [],
      traits: ['frozen', 'heavy', 'wide', 'long'],
      skip: 'Its freeze holds the first sound for good and mutes all that is played after, until the switch is turned off by hand.',
    },
  },
}
