import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'expanse',
  jitter: ['decay', 'modRate'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    'Open space': {
      says: 'a wide open space with a slowly wavering tail',
      brief: 'a wide open space',
      nouns: ['space', 'hall', 'sky'],
      roles: ['hall'],
      traits: ['long', 'wide'],
    },
    Bloom: {
      says: 'a large space whose tail swells in behind each note',
      brief: 'a space that swells in',
      nouns: ['bloom', 'swell', 'space'],
      roles: ['hall'],
      traits: ['long', 'slow', 'wide'],
    },
    'Small dark room': {
      says: 'a small dark room that is gone in about a second',
      brief: 'a small dark room',
      nouns: ['room', 'cell', 'booth'],
      roles: ['room'],
      traits: ['dark', 'short'],
    },
    'Event horizon': {
      says: 'a vast space whose tail swells in and hangs a minute or more',
      brief: 'a vast space that hangs on',
      nouns: ['horizon', 'void', 'space'],
      roles: ['hall', 'hold'],
      traits: ['long', 'heavy', 'wide', 'slow'],
    },
    'Far echoes': {
      says: 'a huge space that answers in separate far-off echoes',
      brief: 'far-off separate echoes',
      nouns: ['echoes', 'canyon'],
      roles: ['hall'],
      traits: ['long', 'far'],
    },
    'Seasick choir': {
      says: 'a long reverb whose tail wavers queasily in pitch',
      brief: 'a long seasick reverb',
      nouns: ['sway', 'wobble', 'swell'],
      roles: ['hall'],
      traits: ['long', 'unsteady', 'wide'],
    },
    'Bright chamber': {
      says: 'a bright chamber that rings for a couple of seconds',
      brief: 'a bright chamber',
      nouns: ['chamber', 'room'],
      roles: ['room'],
      traits: ['bright'],
    },
    'Hard echoes': {
      says: 'a space that answers in hard separate echoes',
      brief: 'hard separate echoes',
      nouns: ['echoes'],
      roles: ['echo'],
      traits: ['clean'],
    },
    'Narrow tunnel': {
      says: 'a dull mono tunnel with a tail of several seconds',
      brief: 'a dull mono tunnel',
      nouns: ['tunnel'],
      roles: ['hall'],
      traits: ['narrow', 'dark'],
    },
    'Thin air': {
      says: 'a thin bright reverb with all its lows cut away',
      brief: 'a thin bright reverb',
      nouns: ['haze', 'mist', 'air'],
      roles: ['hall'],
      traits: ['bright', 'cold', 'long'],
    },
    'Low cathedral': {
      says: 'a huge dark cathedral with only the lows left ringing',
      brief: 'a huge dark cathedral',
      nouns: ['cathedral', 'crypt'],
      roles: ['hall'],
      traits: ['dark', 'long', 'wide', 'warm'],
    },
    'Fast flutter': {
      says: 'a space whose tail flutters quickly in pitch',
      brief: 'a fluttering reverb',
      nouns: ['flutter', 'tremor', 'space'],
      roles: ['hall'],
      traits: ['unsteady', 'fast', 'wide'],
    },
    'Faint air': {
      says: 'a hint of open space behind the sound',
      brief: 'a hint of space',
      nouns: ['space', 'air'],
      roles: ['hall'],
      traits: ['faint'],
    },
    'Quick swell': {
      says: 'a short reverb that swells in just after each note',
      brief: 'a quick swell of reverb',
      nouns: ['swell', 'bloom', 'room'],
      roles: ['room'],
      traits: ['wide', 'bright'],
    },
    'Wash alone': {
      says: 'a huge slow wash that swells in and hangs with no dry sound',
      brief: 'a huge wash heard alone',
      nouns: ['wash', 'fog', 'tide'],
      roles: ['hall'],
      traits: ['heavy', 'far', 'long', 'wide', 'slow'],
    },
    'Small box': {
      says: 'a tiny boxy room that is gone almost at once',
      brief: 'a tiny boxy room',
      nouns: ['room', 'booth'],
      roles: ['room'],
      traits: ['short'],
    },
  },
}
