import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'fdn-reverb',
  jitter: ['decay', 'predelayMs', 'breathRate'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    Room: {
      says: 'a small plain room that is over in about a second',
      brief: 'a small plain room',
      nouns: ['room'],
      roles: ['room'],
      traits: ['short', 'faint', 'clean'],
    },
    Hall: {
      says: 'a plain hall with about four seconds of tail',
      brief: 'a plain mid-sized hall',
      nouns: ['hall'],
      roles: ['hall'],
      traits: ['clean'],
    },
    Breathing: {
      says: 'a large hall whose tail rises and falls every few seconds',
      brief: 'a slowly breathing hall',
      nouns: ['hall', 'tide'],
      roles: ['hall'],
      traits: ['long', 'slow'],
    },
    'Short ambience': {
      says: 'the close reflections of a very small room',
      brief: 'close early reflections',
      nouns: ['room', 'booth'],
      roles: ['room'],
      traits: ['short', 'faint'],
    },
    'Thin veil': {
      says: 'a thin veil of reverb kept low under the sound',
      brief: 'a thin veil of reverb',
      nouns: ['trace', 'room'],
      roles: ['room'],
      traits: ['faint', 'clean'],
    },
    'Bright air': {
      says: 'an undamped hall with about three seconds of tail',
      brief: 'an undamped hall',
      nouns: ['hall', 'air'],
      roles: ['hall'],
      traits: ['clean', 'bright'],
    },
    'Dark cave': {
      says: 'a big muffled cave that rings for about six seconds',
      brief: 'a big muffled cave',
      nouns: ['cave', 'cavern'],
      roles: ['hall'],
      traits: ['dark'],
    },
    'Small bright tank': {
      says: 'a small bright chamber that goes on ringing for seconds',
      brief: 'a small ringing chamber',
      nouns: ['chamber'],
      roles: ['hall'],
      traits: ['bright'],
    },
    'Open valley': {
      says: 'a huge dark open space that answers late and rings on',
      brief: 'a huge open valley',
      nouns: ['valley', 'hall'],
      roles: ['hall'],
      traits: ['long', 'dark'],
    },
    'Late arrival': {
      says: 'a hall that answers about a quarter of a second late',
      brief: 'a late-arriving hall',
      nouns: ['hall'],
      roles: ['hall'],
      traits: [],
    },
    'Slow swell': {
      says: 'a vast hall that opens to the sound in very slow waves',
      brief: 'a vast, slowly opening hall',
      nouns: ['hall', 'swell', 'tide'],
      roles: ['hall'],
      traits: ['long', 'slow', 'wide'],
    },
    'Pulsing gate': {
      says: 'a short room fed in pulses about twice a second',
      brief: 'a short pulsing room',
      nouns: ['room', 'pulse'],
      roles: ['room'],
      traits: ['short', 'faint', 'fast'],
    },
    'Endless tail': {
      says: 'a dark hall that takes about twenty seconds to die away',
      brief: 'a dark, very long hall',
      nouns: ['hall', 'wash'],
      roles: ['hall'],
      traits: ['long', 'dark', 'wide'],
    },
    'Full wet send': {
      says: 'a large hall heard alone with none of the dry sound left',
      brief: 'a hall with no dry sound',
      nouns: ['hall'],
      roles: ['hall'],
      traits: ['heavy', 'far', 'wide', 'long'],
    },
  },
}
