import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'flanger',
  jitter: ['rate', 'delayMs'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    'Gentle sweep': {
      says: 'a gentle flanger sweep about four seconds round',
      brief: 'a gentle flanger sweep',
      nouns: ['flanger', 'sweep'],
      roles: ['motion'],
      traits: ['slow', 'wide'],
    },
    'Classic jet': {
      says: 'a jet-plane flanger sweep with a sharper comb',
      brief: 'a jet flanger sweep',
      nouns: ['jet', 'flanger', 'sweep'],
      roles: ['motion'],
      traits: ['slow', 'wide'],
    },
    'Slow sweep': {
      says: 'a flanger that takes about twelve seconds over each sweep',
      brief: 'a very slow flanger sweep',
      nouns: ['sweep', 'flanger'],
      roles: ['motion'],
      traits: ['slow', 'wide'],
    },
    'Negative hollow': {
      says: 'a short hollow flanger on negative feedback',
      brief: 'a hollow flanger',
      nouns: ['hollow', 'flanger', 'comb'],
      roles: ['motion'],
      traits: ['slow', 'wide'],
    },
    'Through-zero feel': {
      says: 'a very short flanger swept nearly down to nothing',
      brief: 'a very short deep flanger',
      nouns: ['flanger', 'sweep'],
      roles: ['motion'],
      traits: ['slow', 'wide'],
    },
    'Tremolo saw': {
      says: 'a shallow flanger that ramps and snaps back in a steady beat',
      brief: 'a ramping flanger',
      nouns: ['ramp', 'flanger', 'saw'],
      roles: ['pulse', 'motion'],
      traits: ['faint'],
    },
    'Stepped random': {
      says: 'a flanger jumping to a new place about four times a second',
      brief: 'a randomly stepping flanger',
      nouns: ['steps', 'flanger'],
      roles: ['pulse'],
      traits: ['fast', 'strange'],
    },
    'Metal resonator': {
      says: 'a comb driven close to ringing, a pipe that sings along',
      brief: 'a ringing comb like a pipe',
      nouns: ['pipe', 'comb', 'resonator'],
      roles: ['motion'],
      traits: ['cold', 'bright', 'slow', 'strange'],
    },
    'Wide wash': {
      says: 'a long slow flanger, nearly a chorus, opposite on each side',
      brief: 'a long slow flanger wash',
      nouns: ['wash', 'flanger'],
      roles: ['motion', 'width'],
      traits: ['slow', 'wide'],
    },
    'Square chop': {
      says: 'a flanger that flips between two combs about once a second',
      brief: 'a two-comb flanger flip',
      nouns: ['flip', 'flanger', 'comb'],
      roles: ['pulse'],
      traits: [],
    },
    'Faint air': {
      says: 'a trace of short flanger, opposite on the two sides',
      brief: 'a trace of flanger',
      nouns: ['air', 'flanger'],
      roles: ['motion', 'width'],
      traits: ['faint', 'slow'],
    },
    'Glacial drift': {
      says: 'a deep flanger that takes most of a minute to cross',
      brief: 'a glacial flanger drift',
      nouns: ['drift', 'flanger', 'glacier'],
      roles: ['motion'],
      traits: ['slow', 'wide'],
    },
    'Rising comb': {
      says: 'a comb that climbs for about five seconds and starts again',
      brief: 'a climbing comb',
      nouns: ['comb', 'riser', 'flanger'],
      roles: ['motion'],
      traits: ['slow', 'wide'],
    },
    'Standing comb': {
      says: 'a flanger held still, its comb all but cancelled',
      brief: 'a flanger held still',
      nouns: ['comb'],
      roles: [],
      traits: ['faint'],
      skip: 'With the sweep at zero its negative feedback all but cancels the comb: what comes out is the dry sound two decibels quieter and nothing more.',
    },
    'Fast warble': {
      says: 'a quick shallow warble from a longer flanger',
      brief: 'a quick shallow warble',
      nouns: ['warble', 'flanger'],
      roles: ['pulse'],
      traits: ['fast', 'unsteady'],
    },
    'Deep dive': {
      says: 'a long flanger with strong feedback, diving slowly',
      brief: 'a slow deep flanger dive',
      nouns: ['dive', 'flanger', 'comb'],
      roles: ['motion'],
      traits: ['slow', 'cold'],
    },
  },
}
