import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'flanger',
  jitter: ['rate', 'delayMs'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    'Gentle sweep': {
      says: 'a gentle flanger sweeping about every four seconds',
      brief: 'a gentle flanger sweep',
      nouns: ['flanger', 'sweep'],
      roles: ['motion'],
      traits: ['slow', 'wide'],
    },
    'Classic jet': {
      says: 'a flanger sweep with the whoosh of a passing jet plane',
      brief: 'a jet flanger sweep',
      nouns: ['flanger', 'sweep'],
      roles: ['motion'],
      traits: ['slow', 'wide', 'bright'],
    },
    'Slow sweep': {
      says: 'a flanger that takes about twelve seconds over each sweep',
      brief: 'a very slow flanger sweep',
      nouns: ['sweep', 'flanger'],
      roles: ['motion'],
      traits: ['slow', 'wide'],
    },
    'Negative hollow': {
      says: 'a hollow flanger that sweeps every two or three seconds',
      brief: 'a hollow flanger',
      nouns: ['flanger'],
      roles: ['motion'],
      traits: ['wide'],
    },
    'Through-zero feel': {
      says: 'a deep flanger that sweeps right up through the top',
      brief: 'a deep high flanger sweep',
      nouns: ['flanger', 'sweep'],
      roles: ['motion'],
      traits: ['slow', 'wide'],
    },
    'Tremolo saw': {
      says: 'a shallow flanger that ramps and snaps back in a steady beat',
      brief: 'a ramping flanger',
      nouns: ['flanger'],
      roles: ['motion'],
      traits: ['fast'],
    },
    'Stepped random': {
      says: 'a flanger jumping to a new place about four times a second',
      brief: 'a randomly stepping flanger',
      nouns: ['flanger'],
      roles: ['pulse'],
      traits: ['fast', 'strange'],
    },
    'Metal resonator': {
      says: 'a flanger so resonant that it rings like a metal pipe',
      brief: 'a ringing pipe-like flanger',
      nouns: ['flanger'],
      roles: ['motion'],
      traits: ['cold', 'bright', 'slow', 'strange'],
    },
    'Wide wash': {
      says: 'a long slow flanger, nearly a chorus, opposite on each side',
      brief: 'a long slow flanger wash',
      nouns: ['wash', 'flanger'],
      roles: ['motion', 'width'],
      traits: ['slow', 'wide'],
    },
    'Square chop': {
      says: 'a flanger that flips between two tones about twice a second',
      brief: 'a two-tone flanger flip',
      nouns: ['flanger'],
      roles: ['pulse'],
      traits: ['fast'],
    },
    'Faint air': {
      says: 'a trace of short flanger, opposite on the two sides',
      brief: 'a trace of flanger',
      nouns: ['flanger', 'air'],
      roles: ['motion', 'width'],
      traits: ['faint', 'slow'],
    },
    'Glacial drift': {
      says: 'a deep flanger that takes most of a minute to sweep',
      brief: 'a glacial flanger drift',
      nouns: ['drift', 'flanger'],
      roles: ['motion'],
      traits: ['slow', 'wide'],
    },
    'Rising comb': {
      says: 'a flanger that climbs for about five seconds and snaps back',
      brief: 'a climbing flanger',
      nouns: ['flanger'],
      roles: ['motion'],
      traits: ['fast', 'wide'],
    },
    'Standing comb': {
      says: 'a flanger held still, its comb all but cancelled',
      brief: 'a flanger held still',
      nouns: ['flanger'],
      roles: [],
      traits: ['faint'],
      skip: 'With the sweep at zero its negative feedback all but cancels the comb: what comes out is the dry sound two decibels quieter and nothing more.',
    },
    'Fast warble': {
      says: 'a shallow flanger warbling about six times a second',
      brief: 'a quick shallow warble',
      nouns: ['warble', 'flanger'],
      roles: ['pulse'],
      traits: ['fast', 'unsteady'],
    },
    'Deep dive': {
      says: 'a low, resonant flanger diving over about ten seconds',
      brief: 'a slow deep flanger dive',
      nouns: ['flanger'],
      roles: ['motion'],
      traits: ['slow', 'cold'],
    },
  },
}
