import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'freq-shifter',
  jitter: ['delay', 'lfoRate'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    'Slow drift': {
      says: 'a slow phasing drift that turns over every few seconds',
      brief: 'a slow phasing drift',
      nouns: ['drift', 'tide'],
      roles: ['motion'],
      traits: ['slow', 'wide'],
    },
    'Barber pole': {
      says: 'a ringing sweep that seems to climb without end',
      brief: 'an endlessly rising sweep',
      nouns: ['spiral', 'sweep'],
      roles: ['motion'],
      traits: ['wide'],
    },
    'Falling spiral': {
      says: 'echoes that sink a few hertz flatter on every repeat',
      brief: 'echoes that spiral down',
      nouns: ['descent', 'echoes', 'spiral'],
      roles: ['echo', 'pitch'],
      traits: ['strange', 'unsteady', 'wide'],
    },
    'Bell metal': {
      says: 'a large upward shift that turns notes to clanging metal',
      brief: 'a clanging bell-metal shift',
      nouns: ['bell', 'clang'],
      roles: ['pitch'],
      traits: ['strange', 'bright', 'cold'],
    },
    'Split sky': {
      says: 'echoes that creep sharp on the left and flat on the right',
      brief: 'echoes drifting apart',
      nouns: ['echoes', 'drift'],
      roles: ['echo', 'width'],
      traits: ['wide', 'unsteady'],
    },
    'Radio ring': {
      says: 'a slowly swaying ring modulator, sour as a mistuned radio',
      brief: 'a swaying ring modulator',
      nouns: ['signal', 'clang'],
      roles: ['pitch'],
      traits: ['strange', 'cold'],
    },
    Seasick: {
      says: 'the whole sound swaying sharp and flat every few seconds',
      brief: 'a slow seasick pitch sway',
      nouns: ['sway', 'drift'],
      roles: ['motion'],
      traits: ['unsteady', 'slow', 'wide'],
    },
    'Still water': {
      says: 'a faint phasing that turns over about every twelve seconds',
      brief: 'a faint, very slow phasing',
      nouns: ['ripple'],
      roles: ['motion'],
      traits: ['faint', 'slow', 'clean'],
    },
    'Moving beat': {
      says: 'a steady pulse about twice a second, crossing side to side',
      brief: 'a pulse from side to side',
      nouns: ['pulse', 'tremolo'],
      roles: ['pulse'],
      traits: ['wide', 'fast'],
    },
    'Rising echo': {
      says: 'slow echoes that climb further out of tune on each repeat',
      brief: 'echoes that climb sharp',
      nouns: ['echoes', 'ascent'],
      roles: ['echo', 'pitch'],
      traits: ['strange', 'unsteady', 'wide'],
    },
    'Parting echo': {
      says: 'echoes that go sour fast, up on the left, down on the right',
      brief: 'echoes souring apart',
      nouns: ['echoes'],
      roles: ['echo', 'pitch'],
      traits: ['strange', 'wide'],
    },
    Detuned: {
      says: 'a wide detune, sharp on the left and flat on the right',
      brief: 'a wide left-right detune',
      nouns: ['detune', 'split'],
      roles: ['width'],
      traits: ['wide'],
    },
    'Low growl': {
      says: 'a low ring modulator that roughens every note to a growl',
      brief: 'a growling ring modulator',
      nouns: ['buzz', 'grit'],
      roles: ['pitch'],
      traits: ['strange', 'heavy', 'wide'],
    },
    'High chime': {
      says: 'inharmonic chimes far above the notes, echoing higher still',
      brief: 'high inharmonic chimes',
      nouns: ['chime', 'bells'],
      roles: ['pitch', 'echo'],
      traits: ['strange', 'bright', 'cold'],
    },
    'Sunken bell': {
      says: 'a dark downward shift that turns notes to dull, sunken bells',
      brief: 'dull, sunken bell tones',
      nouns: ['bell', 'depths'],
      roles: ['pitch'],
      traits: ['strange', 'dark', 'low', 'wide'],
    },
    'Fast warble': {
      says: 'a fast warble of the whole sound, sharp and flat by turns',
      brief: 'a fast pitch warble',
      nouns: ['warble', 'flutter'],
      roles: ['motion'],
      traits: ['unsteady', 'fast', 'strange'],
    },
  },
}
