import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'glitch',
  jitter: ['time'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    'Gentle stumble': {
      says: 'soft stumbles where a slice repeats, sticks or turns back',
      brief: 'soft stumbles and repeats',
      nouns: ['stutter', 'glitch'],
      roles: ['grain'],
      traits: [],
    },
    'Skipping disc': {
      says: 'the skips of a scratched disc, stuck on tiny fragments',
      brief: 'a skipping scratched disc',
      nouns: ['disc', 'scratch'],
      roles: ['grain', 'wear'],
      traits: ['strange', 'fast'],
    },
    Stuck: {
      says: 'a sound that keeps getting stuck and repeating a slice',
      brief: 'a sound that gets stuck',
      nouns: ['stutter', 'loop'],
      roles: ['grain'],
      traits: ['strange', 'fast'],
    },
    'Backwards glances': {
      says: 'phrases that sometimes turn round and play backwards',
      brief: 'phrases that turn backwards',
      nouns: ['reversal', 'glances'],
      roles: ['grain'],
      traits: ['backwards'],
    },
    'Winding down': {
      says: 'moments that drop to half speed or wind down to a stop',
      brief: 'a sound that winds down',
      nouns: ['slowdown', 'drift'],
      roles: ['grain', 'wear'],
      traits: ['unsteady', 'worn', 'dark', 'low'],
    },
    Bouncing: {
      says: 'slices that repeat faster and faster like a dropped ball',
      brief: 'repeats like a bouncing ball',
      nouns: ['echo', 'stutter'],
      roles: ['grain'],
      traits: ['fast'],
    },
    Shards: {
      says: 'hard-cut splinters of sound, some an octave off, flung wide',
      brief: 'hard-cut shards of sound',
      nouns: ['clicks', 'glitch'],
      roles: ['grain'],
      traits: ['strange', 'fast', 'cold'],
    },
    'Rare slips': {
      says: 'rare soft slips where a slice repeats, reverses or slows',
      brief: 'rare soft slips in the sound',
      nouns: ['glitch', 'trace'],
      roles: ['grain'],
      traits: ['faint'],
    },
    'Octave ghosts': {
      says: 'soft repeats an octave up or down, under the dry sound',
      brief: 'soft ghosts at the octave',
      nouns: ['octaves', 'echoes'],
      roles: ['grain', 'pitch'],
      traits: ['dark'],
    },
    'Barely broken': {
      says: 'a few soft stutters and skips under the dry sound',
      brief: 'a few soft stutters',
      nouns: ['stutter', 'trace'],
      roles: ['grain'],
      traits: ['faint'],
    },
    'Smears underneath': {
      says: 'soft smeared repeats and reversals under the dry sound',
      brief: 'soft smeared repeats',
      nouns: ['blur', 'undertow'],
      roles: ['grain'],
      traits: ['dark'],
    },
    'Phrase repeats': {
      says: 'whole phrases that repeat by chance, each time quieter',
      brief: 'phrases repeated by chance',
      nouns: ['repeats', 'refrain', 'loop'],
      roles: ['grain', 'loop'],
      traits: ['slow'],
    },
    'All backwards': {
      says: 'every slice of the sound turned round and played backwards',
      brief: 'a sound in backwards slices',
      nouns: ['reversal', 'glitch'],
      roles: ['grain'],
      traits: ['backwards', 'strange', 'heavy'],
    },
    'Flickering octaves': {
      says: 'stuttered fragments that flicker an octave up and down',
      brief: 'flickering octave stutters',
      nouns: ['flicker', 'octaves', 'sparks'],
      roles: ['grain', 'pitch'],
      traits: ['fast', 'wide', 'strange'],
    },
    'Buzzing stutter': {
      says: 'tiny slices repeated so fast that they buzz',
      brief: 'a buzzing stutter',
      nouns: ['buzz', 'stutter'],
      roles: ['grain'],
      traits: ['fast', 'strange'],
    },
    'Total collapse': {
      says: 'a sound stuck, reversed or slowed at every single slice',
      brief: 'a sound in broken slices',
      nouns: ['glitch', 'stutter'],
      roles: ['grain'],
      traits: ['strange', 'heavy', 'unsteady', 'fast'],
    },
  },
}
