import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'grain-delay',
  jitter: ['time', 'size'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    Crystals: {
      says: 'grain repeats that climb an octave on every pass',
      brief: 'octave-climbing grain echoes',
      nouns: ['echo', 'octaves'],
      roles: ['echo', 'pitch', 'grain'],
      traits: ['high', 'bright'],
    },
    'Falling embers': {
      says: 'grain repeats that fall an octave and darken each time',
      brief: 'octave-falling grain echoes',
      nouns: ['embers', 'echo'],
      roles: ['echo', 'pitch', 'grain'],
      traits: ['low', 'dark'],
    },
    'Rising fifths': {
      says: 'grain repeats that climb by fifths on every pass',
      brief: 'grain echoes up in fifths',
      nouns: ['fifths', 'steps', 'echo'],
      roles: ['echo', 'pitch'],
      traits: ['bright', 'high'],
    },
    'Grain cloud': {
      says: 'a scattered cloud of short grains behind the playing',
      brief: 'a scattered grain cloud',
      nouns: ['cloud', 'grains'],
      roles: ['grain'],
      traits: [],
    },
    'Backwards shards': {
      says: 'backwards grains of each phrase, repeating as they fade',
      brief: 'backwards grain repeats',
      nouns: ['echo', 'grains'],
      roles: ['echo', 'grain'],
      traits: ['backwards'],
    },
    'Frozen haze': {
      says: 'a wide haze of grains that hangs on long after the playing',
      brief: 'a wide hanging grain haze',
      nouns: ['haze', 'cloud'],
      roles: ['grain', 'hold', 'hall'],
      traits: ['long', 'wide', 'heavy'],
    },
    'Plain repeat': {
      says: 'a plain, centred echo rebuilt from grains',
      brief: 'a plain grain echo',
      nouns: ['repeat', 'echo'],
      roles: ['echo'],
      traits: ['clean'],
    },
    'Sub shadow': {
      says: 'a dull copy an octave below, close behind each note',
      brief: 'a dull octave-down shadow',
      nouns: ['shadow', 'octave'],
      roles: ['pitch'],
      traits: ['low', 'dark', 'faint'],
    },
    'Shimmer wash': {
      says: 'a smeared wash of grains that climbs by octaves',
      brief: 'an octave-climbing wash',
      nouns: ['shimmer', 'wash'],
      roles: ['halo', 'grain', 'pitch'],
      traits: ['high', 'bright'],
    },
    'Thick double': {
      says: 'a thick double made of slightly detuned grains',
      brief: 'a thick detuned double',
      nouns: ['chorus', 'grains'],
      roles: ['width'],
      traits: ['faint', 'short'],
    },
    'High glitter': {
      says: 'sparse short grains two octaves up, after each note',
      brief: 'grains two octaves up',
      nouns: ['glitter', 'sparks'],
      roles: ['pitch', 'grain'],
      traits: ['high', 'bright', 'cold'],
    },
    'Pulsing repeat': {
      says: 'an echo whose repeats come in quick, separate pulses',
      brief: 'a pulsing grain echo',
      nouns: ['echo', 'pulse'],
      roles: ['echo'],
      traits: ['fast'],
    },
    'Scattered pitches': {
      says: 'grains thrown up to an octave out of tune either way',
      brief: 'out-of-tune scattered grains',
      nouns: ['grains', 'cloud'],
      roles: ['grain'],
      traits: ['strange', 'unsteady'],
    },
    'Faint glints': {
      says: 'faint grains an octave and a fifth up, behind the playing',
      brief: 'faint high grains',
      nouns: ['glints', 'sparks'],
      roles: ['pitch', 'grain'],
      traits: ['high', 'bright', 'faint'],
    },
    'Dark slow smear': {
      says: 'a dark smear of long grains that trails for many seconds',
      brief: 'a dark smear of long grains',
      nouns: ['haze', 'cloud'],
      roles: ['grain', 'hall'],
      traits: ['dark', 'long', 'slow', 'far'],
    },
    'Falling fourths': {
      says: 'grain repeats that sink by fourths on every pass',
      brief: 'grain echoes down in fourths',
      nouns: ['fourths', 'steps', 'echo'],
      roles: ['echo', 'pitch'],
      traits: ['dark', 'low'],
    },
  },
}
