import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'grain-cloud',
  jitter: ['size', 'density'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    'Soft cloud': {
      says: 'a soft cloud of grains made from what was just played',
      brief: 'a soft cloud of grains',
      nouns: ['cloud', 'grains', 'haze'],
      roles: ['grain'],
      traits: [],
    },
    'Octave rain': {
      says: 'scattered short grains an octave up, falling like rain',
      brief: 'a rain of octave-up grains',
      nouns: ['rain', 'drops', 'grains'],
      roles: ['grain', 'pitch'],
      traits: ['high', 'fast'],
    },
    'Slow smear': {
      says: 'a smear of long overlapping grains, half of them reversed',
      brief: 'a slow smear of long grains',
      nouns: ['smear', 'cloud', 'wash'],
      roles: ['grain'],
      traits: ['long', 'slow', 'wide', 'heavy'],
    },
    'Choir of fifths': {
      says: 'a wide cloud whose grains jump by fifths and octaves',
      brief: 'a cloud that jumps by fifths',
      nouns: ['choir', 'cloud', 'fifths'],
      roles: ['grain', 'pitch', 'halo'],
      traits: ['wide', 'heavy', 'bright', 'unsteady'],
    },
    'Low tide': {
      says: 'long slow grains an octave down, most of them reversed',
      brief: 'a low tide of slow grains',
      nouns: ['tide', 'undertow', 'swell'],
      roles: ['grain', 'pitch'],
      traits: ['low', 'dark', 'long', 'slow', 'heavy'],
    },
    'Glass shards': {
      says: 'tiny hard-edged grains an octave up, scattered in pitch',
      brief: 'sharp shards of high grains',
      nouns: ['shards', 'glass', 'splinters'],
      roles: ['grain', 'pitch'],
      traits: ['high', 'cold', 'strange', 'fast'],
    },
    'Backwards room': {
      says: 'a cloud of backwards grains close behind the playing',
      brief: 'a cloud of backwards grains',
      nouns: ['cloud', 'mirror'],
      roles: ['grain'],
      traits: ['backwards'],
    },
    'Thin veil': {
      says: 'a thin veil of grains just behind the dry sound',
      brief: 'a thin veil of grains',
      nouns: ['veil', 'haze', 'gauze'],
      roles: ['grain'],
      traits: ['faint', 'short'],
    },
    'Detuned double': {
      says: 'a detuned double made of grains, spread to the sides',
      brief: 'a detuned grain double',
      nouns: ['double', 'twin', 'chorus'],
      roles: ['width', 'grain'],
      traits: ['faint', 'short'],
    },
    'Two octaves under': {
      says: 'long sparse grains two octaves down, a slow bass shadow',
      brief: 'grains two octaves down',
      nouns: ['depths', 'shadow', 'undertow'],
      roles: ['grain', 'pitch'],
      traits: ['low', 'dark', 'slow'],
    },
    'Rising shimmer': {
      says: 'grains fed back an octave up, climbing higher each pass',
      brief: 'a climbing octave shimmer',
      nouns: ['shimmer', 'spiral', 'ladder'],
      roles: ['grain', 'pitch', 'halo'],
      traits: ['high', 'bright', 'heavy', 'long', 'wide'],
    },
    'Sinking spiral': {
      says: 'grains fed back a fourth down, sinking lower each pass',
      brief: 'a sinking spiral of grains',
      nouns: ['spiral', 'descent', 'eddy'],
      roles: ['grain', 'pitch'],
      traits: ['dark', 'low', 'heavy', 'long', 'wide', 'strange'],
    },
    'Thick fog': {
      says: 'a dense, wide fog of grains that buries the dry sound',
      brief: 'a thick fog of grains',
      nouns: ['fog', 'cloud', 'murk'],
      roles: ['grain'],
      traits: ['heavy', 'long', 'wide', 'far'],
    },
    'Stray memories': {
      says: 'sparse stray grains of things played seconds earlier',
      brief: 'stray grains of the past',
      nouns: ['memories', 'strays', 'echoes'],
      roles: ['grain'],
      traits: [],
    },
    'Long memory': {
      says: 'long grains of what was played about four seconds ago',
      brief: 'grains from seconds ago',
      nouns: ['memory', 'cloud', 'trace'],
      roles: ['grain', 'loop'],
      traits: ['long', 'slow'],
    },
    'Grain buzz': {
      says: 'tiny hard grains so close together that the sound buzzes',
      brief: 'a buzz of tiny grains',
      nouns: ['buzz', 'rasp', 'grit'],
      roles: ['grain'],
      traits: ['short', 'strange'],
    },
  },
}
