import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'half-speed',
  jitter: ['length'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    'Half speed': {
      says: 'a half-speed replay an octave down, with no dry sound',
      brief: 'a half-speed replay',
      nouns: ['octave', 'replay'],
      roles: ['pitch'],
      traits: ['low', 'dark', 'slow', 'heavy'],
    },
    'Slow chops': {
      says: 'a half-speed octave below, cut hard about twice a second',
      brief: 'a chopped half-speed octave',
      nouns: ['octave', 'pulse'],
      roles: ['pitch', 'pulse'],
      traits: ['low', 'dark', 'fast', 'heavy'],
    },
    'Smooth octave': {
      says: 'an unbroken half-speed bed an octave down, with no dry sound',
      brief: 'a smooth octave-down bed',
      nouns: ['octave'],
      roles: ['pitch'],
      traits: ['low', 'dark', 'slow', 'heavy'],
    },
    'Fifth down bed': {
      says: 'a slowed copy a fifth below, running on beside the dry sound',
      brief: 'a slowed fifth below',
      nouns: ['fifth', 'harmony'],
      roles: ['pitch'],
      traits: ['low', 'slow'],
    },
    'Two octaves': {
      says: 'a quarter-speed copy two octaves down under the dry sound',
      brief: 'a copy two octaves down',
      nouns: ['depths', 'octaves'],
      roles: ['pitch'],
      traits: ['low', 'dark', 'slow'],
    },
    'Long drag': {
      says: 'whole phrases dragged out at half speed, an octave down',
      brief: 'a long half-speed replay',
      nouns: ['undertow', 'octave'],
      roles: ['pitch'],
      traits: ['low', 'dark', 'slow', 'heavy'],
    },
    'Blurred half': {
      says: 'a blurred half-speed wash an octave down, dull on top',
      brief: 'a blurred half-speed wash',
      nouns: ['blur', 'wash'],
      roles: ['pitch'],
      traits: ['low', 'dark', 'slow', 'heavy'],
    },
    'Under the mix': {
      says: 'a dark, smooth half-speed octave under the dry sound',
      brief: 'a dark octave underneath',
      nouns: ['undertow', 'octave'],
      roles: ['pitch'],
      traits: ['low', 'dark', 'slow'],
    },
    'Short stutter': {
      says: 'a stutter of tiny half-speed pieces, an octave down',
      brief: 'a half-speed stutter',
      nouns: ['stutter', 'octave'],
      roles: ['pulse', 'pitch'],
      traits: ['low', 'dark', 'fast', 'heavy', 'strange'],
    },
    'Fourth down drift': {
      says: 'a wide, slowed copy a fourth below that drifts behind',
      brief: 'a drifting fourth below',
      nouns: ['drift', 'fourth'],
      roles: ['pitch'],
      traits: ['low', 'slow', 'wide'],
    },
    'Quarter speed': {
      says: 'a quarter-speed crawl two octaves down, smooth and unbroken',
      brief: 'a quarter-speed crawl',
      nouns: ['depths', 'octaves'],
      roles: ['pitch'],
      traits: ['low', 'dark', 'slow'],
    },
    'Thin shadow': {
      says: 'a thin half-speed shadow an octave down, its lows cut away',
      brief: 'a thin half-speed shadow',
      nouns: ['shadow', 'trace'],
      roles: ['pitch'],
      traits: ['faint', 'low', 'slow', 'cold'],
    },
    'Fourth below': {
      says: 'a close harmony a fourth below, made of short slowed pieces',
      brief: 'a harmony a fourth below',
      nouns: ['fourth', 'harmony'],
      roles: ['pitch'],
      traits: ['low'],
    },
    'Muffled floor': {
      says: 'a muffled half-speed octave below, kept in the centre',
      brief: 'a muffled octave below',
      nouns: ['octave', 'bass'],
      roles: ['pitch'],
      traits: ['low', 'dark', 'warm', 'slow'],
    },
    'Fifth down grains': {
      says: 'scattered grains a fifth down, spread across both sides',
      brief: 'grains a fifth down',
      nouns: ['grains', 'fifth'],
      roles: ['pitch', 'grain'],
      traits: ['low', 'wide'],
    },
    'Tape slip': {
      says: 'uneven pieces a fourth down, like tape slipping and catching',
      brief: 'a lurching fourth below',
      nouns: ['fourth'],
      roles: ['pitch'],
      traits: ['low', 'worn', 'fast', 'heavy', 'strange'],
    },
  },
}
