import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'lattice',
  jitter: ['v1Delay', 'v2Delay', 'v3Delay', 'v4Delay'],
  trim: [
    { param: 'output', kind: 'db' },
    { param: 'mix', kind: 'mix' },
  ],
  voices: {
    'Thesis voicing': {
      says: 'a line mirrored around a centre note, with a third above it',
      brief: 'a mirror and a third above',
      nouns: ['mirror', 'voicing', 'harmony'],
      roles: ['pitch'],
      traits: [],
    },
    Octaves: {
      says: 'an octave above and an octave below a single line',
      brief: 'octaves above and below',
      nouns: ['octaves', 'pair'],
      roles: ['pitch'],
      traits: ['low', 'high'],
    },
    'Fifths up': {
      says: 'a fifth and a ninth above a single line, as stacked fifths',
      brief: 'stacked fifths above',
      nouns: ['fifths', 'stack'],
      roles: ['pitch'],
      traits: ['high'],
    },
    'Diatonic thirds': {
      says: 'a third above and a sixth below a single line, in C major',
      brief: 'a third above, a sixth below',
      nouns: ['thirds', 'duet', 'harmony'],
      roles: ['pitch'],
      traits: [],
    },
    'Seventh chord stack': {
      says: 'a third, fifth and seventh above each note, in C major',
      brief: 'a stacked seventh chord',
      nouns: ['chord', 'sevenths', 'stack'],
      roles: ['pitch'],
      traits: ['high'],
    },
    'Crystal cascade': {
      says: 'echoes that jump an octave on every repeat, left and right',
      brief: 'octave-climbing echoes',
      nouns: ['cascade', 'crystals', 'echoes'],
      roles: ['echo', 'pitch'],
      traits: ['high'],
    },
    'Sub octave': {
      says: 'one voice an octave below a single line, as loud as the line',
      brief: 'an octave below the line',
      nouns: ['bass', 'octave'],
      roles: ['pitch'],
      traits: ['low', 'warm'],
    },
    'Minor mirror and drone': {
      says: 'mirrored harmonies in A minor around a fixed low A',
      brief: 'an A minor mirror and drone',
      nouns: ['mirror', 'drone'],
      roles: ['pitch'],
      traits: ['strange', 'bright'],
    },
    'Pentatonic harp': {
      says: 'each note answered by a rising pentatonic run of echoes',
      brief: 'a rising pentatonic run',
      nouns: ['harp', 'arpeggio', 'run'],
      roles: ['pitch', 'echo'],
      traits: ['high'],
    },
    'Just intonation triad': {
      says: 'a pure-tuned third and fifth above, with an octave below',
      brief: 'a pure-tuned triad',
      nouns: ['triad', 'chord'],
      roles: ['pitch'],
      traits: ['clean'],
    },
    'Tuned double': {
      says: 'two unison doubles snapped to pitch, hard left and right',
      brief: 'a pitch-snapped double',
      nouns: ['double', 'pair'],
      roles: ['width'],
      traits: [],
    },
    'Sinking cascade': {
      says: 'echoes falling an octave on one side, a fourth on the other',
      brief: 'echoes that sink in pitch',
      nouns: ['cascade', 'descent', 'echoes'],
      roles: ['echo', 'pitch'],
      traits: ['low'],
    },
    'Whole tone haze': {
      says: 'slurred whole-tone harmonies trailing off in echoes',
      brief: 'a whole-tone echo haze',
      nouns: ['haze', 'echoes'],
      roles: ['echo', 'pitch'],
      traits: ['strange'],
    },
    'Two note drone': {
      says: 'copies of each note re-pitched to a fixed C and the G below',
      brief: 'a fixed drone on C and G',
      nouns: ['drone', 'pedal'],
      roles: ['pitch'],
      traits: [],
    },
    'Rough high splinters': {
      says: 'rough splinters one and two octaves up, in quick echoes',
      brief: 'rough shards two octaves up',
      nouns: ['splinters', 'shards'],
      roles: ['pitch', 'grain'],
      traits: ['high', 'strange'],
    },
    'Quiet fifth halo': {
      says: 'a quiet fifth and octave above the line, a touch late',
      brief: 'a quiet fifth and octave',
      nouns: ['halo', 'fifth'],
      roles: ['pitch'],
      traits: ['faint', 'high'],
    },
  },
}
