import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'low-bitrate',
  jitter: [],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    'Behind glass': {
      says: 'a thin audio stream that swirls and warbles a little',
      brief: 'a thin audio stream',
      nouns: ['signal', 'warble'],
      roles: ['wear'],
      traits: ['faint', 'cold'],
    },
    Underwater: {
      says: 'a starved audio stream, watery and smeared, its top cut away',
      brief: 'a watery, dull audio stream',
      nouns: ['warble', 'signal'],
      roles: ['wear'],
      traits: ['dark', 'cold'],
    },
    'Dial-up': {
      says: 'a telephone-grade audio stream, mono, gritty and dull on top',
      brief: 'a gritty mono audio stream',
      nouns: ['signal', 'grit'],
      roles: ['wear'],
      traits: ['narrow', 'dark', 'cold'],
    },
    Ghost: {
      says: 'only the thin, bright part that an audio stream throws away',
      brief: 'a thin, bright digital trace',
      nouns: ['trace'],
      roles: ['wear'],
      traits: ['bright', 'cold', 'strange'],
    },
    'Smeared haze': {
      says: 'a scrambled audio stream that smears every attack into haze',
      brief: 'a haze of scrambled audio',
      nouns: ['haze', 'signal'],
      roles: ['wear', 'grain'],
      traits: ['strange'],
    },
    'Bad connection': {
      says: 'a bad connection that drops out and sticks in buzzing loops',
      brief: 'a bad, sticking connection',
      nouns: ['signal', 'buzz'],
      roles: ['wear', 'grain'],
      traits: ['cold', 'strange', 'fast'],
    },
    'Stuck stream': {
      says: 'an audio stream that keeps sticking in long, buzzing loops',
      brief: 'an audio stream that sticks',
      nouns: ['buzz', 'signal'],
      roles: ['wear', 'grain'],
      traits: ['cold', 'strange'],
    },
    'Frozen stream': {
      says: 'a watery audio stream whose notes hang on as a grainy wash',
      brief: 'a watery, grainy wash',
      nouns: ['wash', 'haze'],
      roles: ['grain', 'wear'],
      traits: ['heavy', 'long'],
    },
    'Thin air': {
      says: 'the discarded part of an audio stream, thin, in a short wash',
      brief: 'a smeared digital trace',
      nouns: ['trace', 'air'],
      roles: ['wear', 'grain'],
      traits: ['bright', 'cold', 'strange'],
    },
    'Few partials': {
      says: 'an audio stream starved down to a few warbling tones',
      brief: 'a few warbling tones',
      nouns: ['warble', 'signal'],
      roles: ['wear', 'grain'],
      traits: ['cold', 'strange'],
    },
    'Watery trace': {
      says: 'a watery, warbling copy laid under the clean sound',
      brief: 'a watery copy underneath',
      nouns: ['trace', 'warble'],
      roles: ['wear'],
      traits: ['faint', 'cold'],
    },
    'Gritty attacks': {
      says: 'a starved audio stream, gritty and rough around each attack',
      brief: 'a gritty audio stream',
      nouns: ['grit', 'signal'],
      roles: ['wear'],
      traits: ['cold'],
    },
    'Fizzing phases': {
      says: 'an audio stream starved and scrambled until each note fizzes',
      brief: 'a fizzing, scrambled signal',
      nouns: ['fizz', 'signal'],
      roles: ['wear', 'grain'],
      traits: ['cold', 'strange'],
    },
    Dropouts: {
      says: 'an audio stream that drops out in soft-edged gaps of silence',
      brief: 'an audio stream full of gaps',
      nouns: ['gaps', 'holes', 'signal'],
      roles: ['wear'],
      traits: ['cold', 'strange'],
    },
    'Through a wall': {
      says: 'an audio stream cut off above the mids, as if through a wall',
      brief: 'a muffled audio stream',
      nouns: ['signal'],
      roles: ['wear'],
      traits: ['dark', 'far'],
    },
    'Endless wash': {
      says: 'a grainy wash that never fades, gathering all that is played',
      brief: 'a wash that never fades',
      nouns: ['wash', 'haze'],
      roles: ['hold', 'grain'],
      traits: ['frozen', 'heavy', 'long', 'strange'],
    },
  },
}
