import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'low-bitrate',
  jitter: [],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    'Behind glass': {
      says: 'a thin audio stream that swirls and warbles a little',
      brief: 'a thin audio stream',
      nouns: ['stream', 'glass'],
      roles: ['wear'],
      traits: ['faint', 'cold', 'worn'],
    },
    Underwater: {
      says: 'a starved stream in long frames, watery, its top cut away',
      brief: 'a watery, dulled stream',
      nouns: ['water', 'stream'],
      roles: ['wear'],
      traits: ['faint', 'dark', 'worn'],
    },
    'Dial-up': {
      says: 'a telephone-grade stream, mono, gritty and cut off on top',
      brief: 'a gritty mono stream',
      nouns: ['modem', 'line', 'stream'],
      roles: ['wear'],
      traits: ['narrow', 'cold', 'worn'],
    },
    Ghost: {
      says: 'only what a starved stream threw away, a thin bright husk',
      brief: 'the leavings of a stream',
      nouns: ['ghost', 'husk', 'trace'],
      roles: ['wear'],
      traits: ['bright', 'cold', 'strange', 'worn'],
    },
    'Smeared haze': {
      says: 'a stream with its timing scrambled, attacks smeared to haze',
      brief: 'a stream smeared to haze',
      nouns: ['haze', 'stream', 'smear'],
      roles: ['wear', 'grain'],
      traits: ['worn', 'strange'],
    },
    'Bad connection': {
      says: 'a bad connection that drops out and sticks in buzzing loops',
      brief: 'a dropping, sticking stream',
      nouns: ['stream', 'signal', 'packets'],
      roles: ['wear', 'grain'],
      traits: ['worn', 'strange'],
    },
    'Stuck stream': {
      says: 'a stream that keeps sticking on long, buzzing held loops',
      brief: 'a stream that keeps sticking',
      nouns: ['stutter', 'stream', 'buzz'],
      roles: ['wear', 'grain'],
      traits: ['worn', 'strange'],
    },
    'Frozen stream': {
      says: 'a watery stream whose every note hangs on as a grainy wash',
      brief: 'a stream with a grainy wash',
      nouns: ['wash', 'stream', 'haze'],
      roles: ['grain', 'wear'],
      traits: ['heavy', 'long', 'worn'],
    },
    'Thin air': {
      says: 'the thrown-away part of a stream, thin, with a short wash',
      brief: 'a thin smeared remainder',
      nouns: ['air', 'residue', 'trace'],
      roles: ['wear', 'grain'],
      traits: ['bright', 'cold', 'strange', 'worn'],
    },
    'Few partials': {
      says: 'a stream starved down to a few warbling partials',
      brief: 'a few warbling partials',
      nouns: ['partials', 'stream', 'warble'],
      roles: ['wear', 'grain'],
      traits: ['cold', 'strange', 'worn'],
    },
    'Watery trace': {
      says: 'a watery, warbling copy mixed low under the clean sound',
      brief: 'a watery copy mixed low',
      nouns: ['trace', 'water', 'stream'],
      roles: ['wear'],
      traits: ['faint', 'cold'],
    },
    'Gritty attacks': {
      says: 'a starved stream in short frames, rough around each attack',
      brief: 'a gritty short-frame stream',
      nouns: ['grit', 'stream'],
      roles: ['wear'],
      traits: ['faint', 'cold', 'worn'],
    },
    'Fizzing phases': {
      says: 'a stream starved and scrambled until every note fizzes',
      brief: 'a fizzing, scrambled stream',
      nouns: ['fizz', 'stream'],
      roles: ['wear', 'grain'],
      traits: ['cold', 'strange', 'worn'],
    },
    Dropouts: {
      says: 'a stream losing packets, soft holes of silence in the sound',
      brief: 'a stream full of holes',
      nouns: ['gaps', 'holes', 'stream'],
      roles: ['wear'],
      traits: ['worn', 'strange'],
    },
    'Through a wall': {
      says: 'a stream cut off above the mids, as if through a wall',
      brief: 'a muffled, walled-off stream',
      nouns: ['wall', 'stream'],
      roles: ['wear'],
      traits: ['dark', 'far', 'worn'],
    },
    'Endless wash': {
      says: 'a grainy wash that never fades, gathering all that is played',
      brief: 'a wash that never fades',
      nouns: ['wash', 'haze'],
      roles: ['hold', 'grain'],
      traits: ['frozen', 'heavy', 'long', 'strange'],
    },
  },
}
