import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'micro-looper',
  jitter: ['length'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    'Soft bed': {
      says: 'a soft loop of whatever was just played',
      brief: 'a soft renewing loop',
      nouns: ['bed', 'loop'],
      roles: ['loop'],
      traits: ['clean'],
    },
    'Half speed': {
      says: 'a loop of the last phrase at half speed, an octave down',
      brief: 'a half-speed loop',
      nouns: ['loop', 'bed'],
      roles: ['loop', 'pitch'],
      traits: ['low', 'dark', 'slow', 'long'],
    },
    'Lo-fi quarter': {
      says: 'a short loop at a quarter of the sample rate, with less top',
      brief: 'a dull quarter-rate loop',
      nouns: ['loop', 'sampler'],
      roles: ['loop', 'wear'],
      traits: ['worn', 'dark', 'long'],
    },
    'Reverse bed': {
      says: 'a loop of the last phrase played backwards as a bed',
      brief: 'a backwards loop',
      nouns: ['bed', 'loop'],
      roles: ['loop'],
      traits: ['backwards', 'long'],
    },
    'Stutter held': {
      says: 'the first fragment played, held as an endless stutter',
      brief: 'an endless held stutter',
      nouns: ['stutter', 'loop'],
      roles: ['loop', 'pulse'],
      traits: ['frozen', 'long', 'fast', 'strange'],
    },
    'Octave up': {
      says: 'a short loop at double speed, an octave up and soon gone',
      brief: 'an octave-up short loop',
      nouns: ['loop', 'sparkle'],
      roles: ['loop', 'pitch'],
      traits: ['high', 'bright'],
    },
    Drifting: {
      says: 'a blurred loop that never comes round quite the same',
      brief: 'a blurred drifting loop',
      nouns: ['drift', 'loop', 'bed'],
      roles: ['loop', 'hold'],
      traits: ['long', 'slow', 'unsteady'],
    },
    'Clean hold': {
      says: 'the first phrase played, looped clean and never fading',
      brief: 'a clean unfading loop',
      nouns: ['loop', 'hold'],
      roles: ['loop', 'hold'],
      traits: ['frozen', 'long', 'clean', 'heavy'],
    },
    'Faint bed': {
      says: 'a faint, soft loop of the last phrase, gone in a few passes',
      brief: 'a faint short-lived loop',
      nouns: ['trace', 'loop', 'bed'],
      roles: ['loop'],
      traits: ['faint'],
    },
    Underwater: {
      says: 'a wide, muffled loop of the last phrase, as if under water',
      brief: 'a wide muffled loop',
      nouns: ['pool', 'loop', 'bed'],
      roles: ['loop', 'hold'],
      traits: ['dark', 'wide', 'long', 'far'],
    },
    'Frozen pad': {
      says: 'the first notes played, held as a wide smeared pad',
      brief: 'a wide held pad',
      nouns: ['pad', 'hold'],
      roles: ['hold', 'loop'],
      traits: ['frozen', 'long', 'wide'],
    },
    'Deep drone': {
      says: 'the first phrase played, held an octave down as a dark drone',
      brief: 'a dark held drone',
      nouns: ['drone', 'hold'],
      roles: ['hold', 'loop', 'pitch'],
      traits: ['frozen', 'long', 'low', 'dark', 'heavy', 'slow'],
    },
    'Slow reverse': {
      says: 'a smeared loop run backwards at half speed, an octave down',
      brief: 'a slow backwards loop',
      nouns: ['loop', 'haze'],
      roles: ['loop', 'pitch', 'hold'],
      traits: ['backwards', 'low', 'dark', 'slow', 'long'],
    },
    'Fast reverse': {
      says: 'a short loop run backwards at double speed, an octave up',
      brief: 'a fast backwards loop',
      nouns: ['chirps', 'loop'],
      roles: ['loop', 'pitch'],
      traits: ['backwards', 'high', 'bright', 'fast'],
    },
    'Sampler grit': {
      says: 'a short loop at an eighth of the sample rate, dull and plain',
      brief: 'a dull eighth-rate loop',
      nouns: ['sampler', 'loop'],
      roles: ['loop', 'wear'],
      traits: ['worn', 'dark', 'long'],
    },
    'Quick loop': {
      says: 'a quick loop of about the last half second, soon faded',
      brief: 'a quick fading loop',
      nouns: ['loop', 'repeats'],
      roles: ['loop', 'echo'],
      traits: ['clean'],
    },
  },
}
