import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'micro-looper',
  jitter: ['length'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    'Soft bed': {
      says: 'a soft loop of whatever was just played',
      brief: 'a soft renewing loop',
      nouns: ['loop'],
      roles: ['loop'],
      traits: ['clean'],
    },
    'Half speed': {
      says: 'a half-speed loop that plays the last phrase an octave down',
      brief: 'a half-speed loop',
      nouns: ['loop'],
      roles: ['loop', 'pitch'],
      traits: ['low', 'dark', 'slow', 'long'],
    },
    'Lo-fi quarter': {
      says: 'a short, dull loop at a quarter of the sample rate',
      brief: 'a dull early-sampler loop',
      nouns: ['loop', 'sampler'],
      roles: ['loop', 'wear'],
      traits: ['worn', 'dark', 'long'],
    },
    'Reverse bed': {
      says: 'a loop of the last phrase played backwards as a bed',
      brief: 'a backwards loop',
      nouns: ['loop'],
      roles: ['loop'],
      traits: ['backwards', 'long'],
    },
    'Stutter held': {
      says: 'an endless stutter made of the first fragment played',
      brief: 'an endless held stutter',
      nouns: ['stutter', 'loop'],
      roles: ['loop', 'hold'],
      traits: ['frozen', 'long', 'fast', 'strange'],
    },
    'Octave up': {
      says: 'a short double-speed loop an octave up that soon dies away',
      brief: 'an octave-up short loop',
      nouns: ['loop', 'sparkle'],
      roles: ['loop', 'pitch'],
      traits: ['high', 'bright', 'fast'],
    },
    Drifting: {
      says: 'a blurred loop that never comes round quite the same',
      brief: 'a blurred drifting loop',
      nouns: ['drift', 'loop'],
      roles: ['loop', 'hold'],
      traits: ['long', 'slow', 'unsteady'],
    },
    'Clean hold': {
      says: 'a clean, unfading loop of the first phrase played',
      brief: 'a clean unfading loop',
      nouns: ['loop'],
      roles: ['loop', 'hold'],
      traits: ['frozen', 'long', 'clean', 'heavy'],
    },
    'Faint bed': {
      says: 'a faint, soft loop of the last phrase that soon dies away',
      brief: 'a faint short-lived loop',
      nouns: ['trace', 'loop'],
      roles: ['loop'],
      traits: ['faint'],
    },
    Underwater: {
      says: 'a wide, muffled loop of the last phrase, as if under water',
      brief: 'a wide muffled loop',
      nouns: ['loop', 'haze'],
      roles: ['loop', 'hold'],
      traits: ['dark', 'wide', 'long', 'far'],
    },
    'Frozen pad': {
      says: 'a wide smeared pad held from the first notes played',
      brief: 'a wide held pad',
      nouns: ['pad'],
      roles: ['hold', 'loop'],
      traits: ['frozen', 'long', 'wide'],
    },
    'Deep drone': {
      says: 'a dark drone made by holding the first phrase an octave down',
      brief: 'a dark held drone',
      nouns: ['drone'],
      roles: ['hold', 'loop', 'pitch'],
      traits: ['frozen', 'long', 'low', 'dark', 'heavy', 'slow'],
    },
    'Slow reverse': {
      says: 'a smeared backwards loop at half speed and an octave down',
      brief: 'a slow backwards loop',
      nouns: ['loop', 'haze'],
      roles: ['loop', 'pitch', 'hold'],
      traits: ['backwards', 'low', 'dark', 'slow', 'long'],
    },
    'Fast reverse': {
      says: 'a short loop run backwards at double speed and an octave up',
      brief: 'a fast backwards loop',
      nouns: ['chirps', 'loop'],
      roles: ['loop', 'pitch'],
      traits: ['backwards', 'high', 'bright', 'fast'],
    },
    'Sampler grit': {
      says: 'a short, muffled loop at an eighth of the sample rate',
      brief: 'a muffled early-sampler loop',
      nouns: ['sampler', 'loop'],
      roles: ['loop', 'wear'],
      traits: ['worn', 'dark', 'long'],
    },
    'Quick loop': {
      says: 'a quick loop of about the last half second that soon fades',
      brief: 'a quick fading loop',
      nouns: ['loop', 'repeats'],
      roles: ['loop', 'echo'],
      traits: ['clean', 'fast'],
    },
  },
}
