import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'noise-floor',
  jitter: ['response', 'hold'],
  // Level sets the noise alone and the sound passes untouched, so nothing here sets the chain's level.
  trim: [],
  voices: {
    'Tape floor': {
      says: 'steady tape hiss that lingers after the last note',
      brief: 'steady tape hiss',
      nouns: ['hiss', 'tape', 'floor'],
      roles: ['hiss'],
      traits: ['noisy', 'bright', 'long'],
    },
    'Old record': {
      says: 'the surface noise and crackle of an old record',
      brief: 'old record crackle',
      nouns: ['crackle', 'record', 'dust'],
      roles: ['hiss'],
      traits: ['noisy', 'worn', 'long'],
    },
    'Empty room': {
      says: 'the low rumble of an empty room, left running',
      brief: 'the rumble of an empty room',
      nouns: ['rumble', 'floor'],
      roles: ['hiss'],
      traits: ['noisy', 'dark', 'heavy', 'long'],
    },
    'Amp left on': {
      says: 'the low mains hum of an amplifier left switched on',
      brief: 'the hum of an amplifier',
      nouns: ['hum', 'amp', 'mains'],
      roles: ['hiss'],
      traits: ['noisy', 'long'],
    },
    'Radio static': {
      says: 'radio static that drifts and crackles under the sound',
      brief: 'drifting radio static',
      nouns: ['static', 'radio'],
      roles: ['hiss'],
      traits: ['noisy', 'worn', 'long'],
    },
    'Breathing tape': {
      says: 'tape hiss that sinks under each note and swells in the gaps',
      brief: 'hiss that swells in the gaps',
      nouns: ['hiss', 'breath', 'tape'],
      roles: ['hiss'],
      traits: ['noisy', 'bright', 'heavy', 'slow', 'long'],
    },
    'Riding hiss': {
      says: 'tape hiss that rises with each note and dies with it',
      brief: 'hiss that rides the notes',
      nouns: ['hiss', 'tape'],
      roles: ['hiss'],
      traits: ['noisy', 'bright', 'short'],
    },
    'Close mic': {
      says: 'the soft air of an open microphone under the sound',
      brief: 'open microphone air',
      nouns: ['air', 'mic'],
      roles: ['hiss'],
      traits: ['noisy', 'long'],
    },
    'Faint hiss': {
      says: 'a trace of tape hiss, even and barely there',
      brief: 'a trace of tape hiss',
      nouns: ['hiss', 'trace', 'tape'],
      roles: ['hiss'],
      traits: ['faint', 'noisy'],
    },
    'Muffled hiss': {
      says: 'muffled tape hiss with its top taken off, steady and thick',
      brief: 'dull, thick tape hiss',
      nouns: ['hiss', 'tape', 'floor'],
      roles: ['hiss'],
      traits: ['noisy', 'heavy', 'long'],
    },
    'Wall of hiss': {
      says: 'loud, wide tape hiss that stands over the sound',
      brief: 'loud, wide tape hiss',
      nouns: ['hiss', 'wall', 'tape'],
      roles: ['hiss'],
      traits: ['noisy', 'heavy', 'wide', 'bright', 'long'],
    },
    'Mains hum': {
      says: 'a pure low mains hum in the middle of the sound',
      brief: 'a pure low mains hum',
      nouns: ['hum', 'mains'],
      roles: ['hiss'],
      traits: ['noisy', 'dark', 'long'],
    },
    'Gap crackle': {
      says: 'record crackle that ducks under notes and fills the gaps',
      brief: 'crackle between the notes',
      nouns: ['crackle', 'dust', 'record'],
      roles: ['hiss'],
      traits: ['noisy', 'worn', 'heavy', 'slow', 'long'],
    },
    'Static notes': {
      says: 'radio static that sounds only with each note played',
      brief: 'static riding each note',
      nouns: ['static', 'radio'],
      roles: ['hiss'],
      traits: ['noisy', 'worn', 'short'],
    },
    'Distant rumble': {
      says: 'deep, wide rumble that wanders slowly and lingers',
      brief: 'deep, wandering rumble',
      nouns: ['rumble', 'depths'],
      roles: ['hiss'],
      traits: ['noisy', 'dark', 'wide', 'heavy', 'slow', 'long'],
    },
    'Thin bright air': {
      says: 'thin bright air from a microphone, hardly moving',
      brief: 'thin, bright air noise',
      nouns: ['air', 'hiss'],
      roles: ['hiss'],
      traits: ['noisy', 'bright', 'long'],
    },
  },
}
