import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'noise-floor',
  jitter: ['response', 'hold'],
  // Level sets the noise alone and the sound passes untouched, so nothing here sets the chain's level.
  trim: [],
  voices: {
    'Tape floor': {
      says: 'steady tape hiss that lingers after the last note',
      brief: 'steady tape hiss',
      nouns: ['hiss'],
      roles: ['hiss'],
      traits: ['noisy', 'bright'],
    },
    'Old record': {
      says: 'the surface noise and crackle of an old record',
      brief: 'old record crackle',
      nouns: ['crackle', 'dust'],
      roles: ['hiss'],
      traits: ['noisy', 'worn'],
    },
    'Empty room': {
      says: 'the low, wide rumble of an empty room',
      brief: 'the rumble of an empty room',
      nouns: ['noise'],
      roles: ['hiss'],
      traits: ['noisy', 'dark', 'heavy'],
    },
    'Amp left on': {
      says: 'the low hum of an amplifier left switched on',
      brief: 'the hum of an amplifier',
      nouns: ['hum', 'amp'],
      roles: ['hiss'],
      traits: ['noisy', 'dark'],
    },
    'Radio static': {
      says: 'radio static that drifts and crackles under the sound',
      brief: 'drifting radio static',
      nouns: ['static'],
      roles: ['hiss'],
      traits: ['noisy', 'worn'],
    },
    'Breathing tape': {
      says: 'tape hiss that sinks under each note and swells in the gaps',
      brief: 'hiss that swells in the gaps',
      nouns: ['hiss'],
      roles: ['hiss'],
      traits: ['noisy', 'bright', 'heavy', 'slow'],
    },
    'Riding hiss': {
      says: 'tape hiss that rises with each note and dies with it',
      brief: 'hiss that rides the notes',
      nouns: ['hiss'],
      roles: ['hiss'],
      traits: ['noisy', 'bright', 'short'],
    },
    'Close mic': {
      says: 'the soft air of an open microphone under the sound',
      brief: 'open microphone air',
      nouns: ['hiss', 'air'],
      roles: ['hiss'],
      traits: ['noisy'],
    },
    'Faint hiss': {
      says: 'a thin, even trace of tape hiss, heard in the pauses',
      brief: 'a trace of tape hiss',
      nouns: ['hiss', 'trace'],
      roles: ['hiss'],
      traits: ['faint', 'noisy'],
    },
    'Muffled hiss': {
      says: 'muffled tape hiss with its top taken off, steady and thick',
      brief: 'dull, thick tape hiss',
      nouns: ['hiss'],
      roles: ['hiss'],
      traits: ['noisy', 'heavy', 'dark'],
    },
    'Wall of hiss': {
      says: 'a wide wall of tape hiss that stands over the sound',
      brief: 'a wide wall of tape hiss',
      nouns: ['hiss'],
      roles: ['hiss'],
      traits: ['noisy', 'heavy', 'wide', 'bright'],
    },
    'Mains hum': {
      says: 'a pure, low electrical hum that sits in the centre',
      brief: 'a pure, low electrical hum',
      nouns: ['hum'],
      roles: ['hiss'],
      traits: ['noisy', 'dark'],
    },
    'Gap crackle': {
      says: 'record crackle that ducks under notes and fills the gaps',
      brief: 'crackle between the notes',
      nouns: ['crackle', 'dust'],
      roles: ['hiss'],
      traits: ['noisy', 'worn', 'heavy', 'slow'],
    },
    'Static notes': {
      says: 'radio static that sounds only with each note played',
      brief: 'static riding each note',
      nouns: ['static'],
      roles: ['hiss'],
      traits: ['noisy', 'worn', 'short'],
    },
    'Distant rumble': {
      says: 'deep, wide rumble that wanders slowly and lingers',
      brief: 'deep, wandering rumble',
      nouns: ['noise'],
      roles: ['hiss'],
      traits: ['noisy', 'dark', 'wide', 'heavy', 'slow'],
    },
    'Thin bright air': {
      says: 'thin bright air from a microphone, hardly moving',
      brief: 'thin, bright air noise',
      nouns: ['hiss', 'air'],
      roles: ['hiss'],
      traits: ['noisy', 'bright'],
    },
  },
}
