import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'octaves',
  jitter: ['attack'],
  trim: [],
  voices: {
    Organ: {
      says: 'every note doubled one and two octaves below and above',
      brief: 'a full stack of octaves',
      nouns: ['octaves'],
      roles: ['pitch'],
      traits: ['low', 'high'],
    },
    'Sub octave': {
      says: 'a rounded octave below every note of a chord',
      brief: 'a rounded octave below',
      nouns: ['bass', 'octave'],
      roles: ['pitch'],
      traits: ['low', 'dark', 'warm'],
    },
    'Twelve string': {
      says: 'a detuned octave above each note, like doubled strings',
      brief: 'a detuned octave above',
      nouns: ['octave', 'jangle'],
      roles: ['pitch'],
      traits: ['high', 'bright'],
    },
    'Glass octaves': {
      says: 'one and two octaves above each note, thin and glassy',
      brief: 'glassy upper octaves',
      nouns: ['octaves', 'sheen'],
      roles: ['pitch'],
      traits: ['high', 'bright', 'cold'],
    },
    Cathedral: {
      says: 'four octaves that swell in on each note, like a pipe organ',
      brief: 'a swelling stack of octaves',
      nouns: ['octaves'],
      roles: ['pitch'],
      traits: ['low', 'high', 'warm'],
    },
    Deep: {
      says: 'a soft, deep bass one and two octaves below each note',
      brief: 'a soft bass two octaves down',
      nouns: ['depths', 'bass'],
      roles: ['pitch'],
      traits: ['low', 'dark', 'warm'],
    },
    'Swell pad': {
      says: 'octaves below and above that swell in, with no dry sound',
      brief: 'a slow swell of octaves',
      nouns: ['swell', 'pad'],
      roles: ['pitch', 'swell'],
      traits: ['heavy', 'slow', 'low', 'high'],
    },
    'Faint octave': {
      says: 'a faint octave above each note, slightly detuned',
      brief: 'a faint octave above',
      nouns: ['octave', 'glint'],
      roles: ['pitch'],
      traits: ['faint', 'high'],
    },
    'High voice alone': {
      says: 'the octave above alone, every note of a chord moved up',
      brief: 'the octave above alone',
      nouns: ['treble', 'octave'],
      roles: ['pitch'],
      traits: ['high', 'bright', 'heavy'],
    },
    'Bass alone': {
      says: 'the octave below alone, rounded off like a bass',
      brief: 'the octave below alone',
      nouns: ['bass', 'octave'],
      roles: ['pitch'],
      traits: ['low', 'dark', 'heavy', 'narrow'],
    },
    'Slow halo': {
      says: 'high octaves that fade in late above each note',
      brief: 'a late halo of high octaves',
      nouns: ['halo', 'glow'],
      roles: ['pitch'],
      traits: ['high', 'bright', 'slow'],
    },
    'Nasal reed': {
      says: 'octaves below and above through a nasal, peaked filter',
      brief: 'a nasal reed of octaves',
      nouns: ['octaves', 'reed'],
      roles: ['pitch'],
      traits: ['high', 'cold', 'narrow'],
    },
    'Whistling pipes': {
      says: 'upper octaves through a filter that rings like a whistle',
      brief: 'whistling upper octaves',
      nouns: ['octaves', 'overtones'],
      roles: ['pitch'],
      traits: ['high', 'bright', 'cold', 'strange'],
    },
    'Slow pedals': {
      says: 'a deep bass two octaves down that swells in slowly',
      brief: 'a slow, deep bass swell',
      nouns: ['bass', 'swell'],
      roles: ['pitch'],
      traits: ['low', 'dark', 'warm', 'slow'],
    },
    'Hollow pair': {
      says: 'the octaves below and above alone, beating out of tune',
      brief: 'a detuned pair of octaves',
      nouns: ['pair', 'octaves'],
      roles: ['pitch'],
      traits: ['heavy', 'low', 'high'],
    },
    'Late bloom': {
      says: 'four octaves that bloom about two seconds after each note',
      brief: 'a late bloom of octaves',
      nouns: ['bloom'],
      roles: ['pitch'],
      traits: ['slow', 'low', 'high'],
    },
  },
}
