import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'pad-follower',
  jitter: ['rise', 'fall'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    'String pad': {
      says: 'a soft string pad that swells in behind what is played',
      brief: 'a soft following string pad',
      nouns: ['strings', 'pad', 'section'],
      roles: ['hold'],
      traits: ['warm'],
    },
    'Slow swell': {
      says: 'a string pad that takes seconds to swell in after a chord',
      brief: 'a slow-swelling string pad',
      nouns: ['swell', 'strings', 'pad'],
      roles: ['hold'],
      traits: ['slow', 'warm'],
    },
    Lingering: {
      says: 'a dark string pad that lingers long after each chord',
      brief: 'a dark lingering pad',
      nouns: ['strings', 'pad', 'afterglow'],
      roles: ['hold'],
      traits: ['dark', 'long', 'slow'],
    },
    'Octave halo': {
      says: 'a string pad with a second section an octave above',
      brief: 'strings with an octave above',
      nouns: ['halo', 'strings', 'octave'],
      roles: ['hold', 'pitch', 'halo'],
      traits: ['high'],
    },
    'Low section': {
      says: 'a dark string pad doubled an octave below the playing',
      brief: 'low strings an octave under',
      nouns: ['basses', 'strings', 'section'],
      roles: ['hold', 'pitch'],
      traits: ['low', 'dark', 'warm'],
    },
    Doubler: {
      says: 'a string voice that doubles each note almost at once',
      brief: 'a quick string double',
      nouns: ['double', 'strings', 'unison'],
      roles: ['width', 'hold'],
      traits: ['faint', 'short'],
    },
    Glassy: {
      says: 'a bright, thin pad an octave up that follows closely',
      brief: 'a glassy octave-up pad',
      nouns: ['glass', 'halo', 'strings'],
      roles: ['hold', 'pitch'],
      traits: ['bright', 'high', 'cold', 'wide'],
    },
    'Barely there': {
      says: 'a quiet string pad kept far behind the playing',
      brief: 'a barely audible string pad',
      nouns: ['trace', 'strings', 'hint'],
      roles: ['hold'],
      traits: ['faint', 'slow'],
    },
    'Pad alone': {
      says: 'a string pad alone, in place of the instrument playing it',
      brief: 'a string pad by itself',
      nouns: ['strings', 'pad', 'section'],
      roles: ['hold', 'swell'],
      traits: ['heavy', 'far', 'wide'],
    },
    'Dark cellos': {
      says: 'a dark, low string pad like cellos under the playing',
      brief: 'a dark pad like cellos',
      nouns: ['cellos', 'strings', 'basses'],
      roles: ['hold', 'pitch'],
      traits: ['dark', 'low', 'warm', 'slow'],
    },
    'Still pipes': {
      says: 'a steady, unmoving voice per note, like organ pipes',
      brief: 'a still pad like organ pipes',
      nouns: ['pipes', 'organ', 'drone'],
      roles: ['hold'],
      traits: ['narrow', 'clean', 'faint'],
    },
    Restless: {
      says: 'a wide string pad that never stops shifting and shimmering',
      brief: 'a restless shifting pad',
      nouns: ['strings', 'shimmer', 'swarm'],
      roles: ['hold', 'motion'],
      traits: ['wide', 'unsteady', 'high'],
    },
    'Late tide': {
      says: 'a string pad that arrives long after the chord and stays',
      brief: 'a late, long-staying pad',
      nouns: ['tide', 'strings', 'swell'],
      roles: ['hold'],
      traits: ['slow', 'long'],
    },
    'Catch all': {
      says: 'a wide string pad that picks up even the softest notes',
      brief: 'a pad that catches it all',
      nouns: ['strings', 'pad', 'catch'],
      roles: ['hold'],
      traits: ['wide'],
    },
    'High mist': {
      says: 'a thin, high pad an octave up with nothing low in it',
      brief: 'a thin high mist of strings',
      nouns: ['mist', 'halo', 'strings'],
      roles: ['hold', 'pitch', 'halo'],
      traits: ['high', 'cold', 'slow'],
    },
    'Felted pad': {
      says: 'a muffled pad with all its top taken off, slow to fade',
      brief: 'a muffled, felted pad',
      nouns: ['felt', 'pad', 'strings'],
      roles: ['hold'],
      traits: ['dark', 'warm'],
    },
  },
}
