import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'patina',
  jitter: [],
  trim: [
    { param: 'output', kind: 'db' },
    { param: 'mix', kind: 'mix' },
  ],
  voices: {
    'Quarter inch reel': {
      says: 'a tape reel with soft saturation, slight wobble and hiss',
      brief: 'a lightly worn reel',
      nouns: ['reel', 'tape'],
      roles: ['wear'],
      traits: ['warm', 'faint'],
    },
    'New tape': {
      says: 'a fresh reel of tape, open on top and nearly steady',
      brief: 'a fresh reel of tape',
      nouns: ['tape', 'reel'],
      roles: ['wear', 'drive'],
      traits: ['clean', 'faint'],
    },
    'Worn cassette': {
      says: 'a worn cassette that wobbles, drops out and hisses',
      brief: 'a wobbling, hissing cassette',
      nouns: ['cassette', 'tape'],
      roles: ['wear'],
      traits: ['worn', 'unsteady', 'noisy'],
    },
    'Dusty record': {
      says: 'a dusty record, gently warped, with crackle in the groove',
      brief: 'a crackling old record',
      nouns: ['record', 'dust', 'groove'],
      roles: ['wear'],
      traits: ['worn', 'unsteady', 'noisy'],
    },
    Shortwave: {
      says: 'a shortwave broadcast, narrow and mono, fading under static',
      brief: 'a fading shortwave signal',
      nouns: ['shortwave', 'static', 'signal'],
      roles: ['wear'],
      traits: ['narrow', 'far', 'worn', 'noisy'],
    },
    'Early sampler': {
      says: 'an early sampler whose quiet tails crumble into grain',
      brief: 'a grainy early sampler',
      nouns: ['sampler', 'grain', 'bits'],
      roles: ['wear'],
      traits: ['cold', 'bright', 'faint'],
    },
    'Hot valve': {
      says: 'a valve stage driven hard until it thickens and sags',
      brief: 'a hot valve stage',
      nouns: ['valve', 'glow'],
      roles: ['drive'],
      traits: ['warm'],
    },
    'Falling apart': {
      says: 'a ruined cassette that lurches, drops out and hisses hard',
      brief: 'a ruined cassette',
      nouns: ['cassette', 'wreck', 'tape'],
      roles: ['wear'],
      traits: ['worn', 'unsteady', 'noisy', 'strange'],
    },
    'Reel pushed hard': {
      says: 'a tape reel pushed hard into thick saturation',
      brief: 'a reel pushed hard',
      nouns: ['reel', 'tape'],
      roles: ['drive', 'wear'],
      traits: ['warm'],
    },
    'Scratched record': {
      says: 'a badly worn record, swaying in pitch under loud crackle',
      brief: 'a worn, swaying record',
      nouns: ['record', 'crackle', 'scratch'],
      roles: ['wear', 'hiss'],
      traits: ['worn', 'noisy', 'unsteady'],
    },
    'Kitchen radio': {
      says: 'a small radio speaker, mono and boxy, with the lows gone',
      brief: 'a small mono radio',
      nouns: ['radio', 'speaker', 'wireless'],
      roles: ['wear'],
      traits: ['narrow', 'cold', 'worn'],
    },
    'Distant station': {
      says: 'a far radio station, sinking in and out of heavy static',
      brief: 'a station lost in static',
      nouns: ['station', 'static', 'signal'],
      roles: ['wear', 'hiss'],
      traits: ['narrow', 'far', 'noisy', 'worn'],
    },
    'Eight bit': {
      says: 'a coarse early sampler, gritty, with bright hash on top',
      brief: 'a coarse, gritty sampler',
      nouns: ['bits', 'sampler', 'grit'],
      roles: ['wear'],
      traits: ['cold', 'bright', 'worn'],
    },
    'Muffled sampler': {
      says: 'an early sampler at a low rate, its top filtered away',
      brief: 'a muffled early sampler',
      nouns: ['sampler', 'bits'],
      roles: ['wear'],
      traits: ['dark', 'faint'],
    },
    'Valve bloom': {
      says: 'a valve stage that gives way under loud notes, tails rising',
      brief: 'a sagging valve stage',
      nouns: ['valve', 'bloom', 'glow'],
      roles: ['drive', 'glue'],
      traits: ['warm', 'faint'],
    },
    'Valve fuzz': {
      says: 'a valve driven all the way into a bright, buzzing fuzz',
      brief: 'a buzzing valve fuzz',
      nouns: ['fuzz', 'valve', 'buzz'],
      roles: ['drive'],
      traits: ['bright', 'strange'],
    },
  },
}
