import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'phaser',
  jitter: ['rate'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    'Warm six-stage': {
      says: 'a six-stage phaser turning about every three seconds',
      brief: 'a six-stage phaser',
      nouns: ['phaser', 'swirl'],
      roles: ['motion'],
      traits: ['slow', 'wide'],
    },
    'Classic four-stage': {
      says: 'a four-stage phaser with two broad notches, turning slowly',
      brief: 'a four-stage phaser',
      nouns: ['phaser', 'swirl'],
      roles: ['motion'],
      traits: ['slow', 'wide'],
    },
    'Deep eight-stage': {
      says: 'a deep eight-stage phaser with sharp peaks between notches',
      brief: 'a deep eight-stage phaser',
      nouns: ['phaser', 'sweep'],
      roles: ['motion'],
      traits: ['slow', 'wide'],
    },
    'Slow swirl': {
      says: 'a phaser taking about a quarter of a minute to come round',
      brief: 'a slow phaser swirl',
      nouns: ['swirl', 'phaser'],
      roles: ['motion'],
      traits: ['slow', 'wide'],
    },
    'Fast throb': {
      says: 'a shallow phaser pulsing four or five times a second',
      brief: 'a quick shallow phaser',
      nouns: ['phaser'],
      roles: ['pulse'],
      traits: ['fast'],
    },
    'Twelve stage cloud': {
      says: 'a dense many-notched phaser drifting opposite on each side',
      brief: 'a dense drifting phaser',
      nouns: ['phaser', 'cloud'],
      roles: ['motion', 'width'],
      traits: ['slow', 'wide'],
    },
    'Negative notch': {
      says: 'a hollow, resonant phaser turning about every four seconds',
      brief: 'a hollow, resonant phaser',
      nouns: ['phaser'],
      roles: ['motion'],
      traits: ['slow', 'wide'],
    },
    'Random steps': {
      says: 'a phaser jumping to a new place about three times a second',
      brief: 'a randomly stepping phaser',
      nouns: ['phaser'],
      roles: ['pulse'],
      traits: ['fast', 'strange'],
    },
    'Saw riser': {
      says: 'a phaser that climbs for about two seconds and snaps back',
      brief: 'a climbing phaser',
      nouns: ['phaser'],
      roles: ['motion'],
      traits: ['fast'],
    },
    'Bass safe': {
      says: 'a four-stage phaser kept high, leaving the low end alone',
      brief: 'a phaser kept up high',
      nouns: ['phaser', 'swirl'],
      roles: ['motion'],
      traits: ['slow'],
    },
    'Faint shade': {
      says: 'a trace of slow four-stage phaser under the dry sound',
      brief: 'a trace of slow phaser',
      nouns: ['phaser', 'trace'],
      roles: ['motion'],
      traits: ['faint', 'slow'],
    },
    'Glacial sweep': {
      says: 'a ten-stage phaser that takes most of a minute to sweep',
      brief: 'a glacial phaser sweep',
      nouns: ['sweep', 'phaser'],
      roles: ['motion'],
      traits: ['slow', 'wide'],
    },
    'Endless fall': {
      says: 'a ten-stage phaser falling from the top again and again',
      brief: 'a falling phaser',
      nouns: ['phaser'],
      roles: ['motion'],
      traits: ['fast'],
    },
    'Two-tone flip': {
      says: 'a phaser flipping between two tones, opposite on each side',
      brief: 'a two-tone phaser flip',
      nouns: ['phaser'],
      roles: ['pulse'],
      traits: ['fast', 'wide'],
    },
    'Still formant': {
      says: 'a motionless phaser that leaves two fixed peaks in the tone',
      brief: 'a phaser held still',
      nouns: ['filter', 'phaser'],
      roles: ['tone'],
      traits: ['faint'],
    },
    'Stereo scatter': {
      says: 'a phaser with no dry sound, pulling the two sides apart',
      brief: 'a phaser with no dry sound',
      nouns: ['phaser'],
      roles: ['width', 'motion'],
      traits: ['wide', 'slow'],
    },
  },
}
