import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'phaser',
  jitter: ['rate'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    'Warm six-stage': {
      says: 'a six-stage phaser turning about every three seconds',
      brief: 'a six-stage phaser',
      nouns: ['phaser', 'swirl'],
      roles: ['motion'],
      traits: ['slow', 'wide'],
    },
    'Classic four-stage': {
      says: 'a four-stage phaser with two broad notches, turning slowly',
      brief: 'a four-stage phaser',
      nouns: ['phaser', 'swirl'],
      roles: ['motion'],
      traits: ['slow', 'wide'],
    },
    'Deep eight-stage': {
      says: 'a deep eight-stage phaser with sharp peaks between notches',
      brief: 'a deep eight-stage phaser',
      nouns: ['phaser', 'sweep'],
      roles: ['motion'],
      traits: ['slow', 'wide'],
    },
    'Slow swirl': {
      says: 'a phaser swirl about a quarter of a minute round',
      brief: 'a slow phaser swirl',
      nouns: ['swirl', 'phaser'],
      roles: ['motion'],
      traits: ['slow', 'wide'],
    },
    'Fast throb': {
      says: 'a quick shallow phaser throb, the same on both sides',
      brief: 'a quick phaser throb',
      nouns: ['throb', 'phaser'],
      roles: ['pulse'],
      traits: ['fast'],
    },
    'Twelve stage cloud': {
      says: 'twelve phaser stages tuned far apart, drifting slowly',
      brief: 'a twelve-stage phaser cloud',
      nouns: ['cloud', 'phaser'],
      roles: ['motion', 'width'],
      traits: ['slow', 'wide'],
    },
    'Negative notch': {
      says: 'a hollow phaser with peaks where its notches would be',
      brief: 'a hollow peaking phaser',
      nouns: ['phaser', 'hollow'],
      roles: ['motion'],
      traits: ['slow', 'wide'],
    },
    'Random steps': {
      says: 'a phaser jumping to a new place about three times a second',
      brief: 'a randomly stepping phaser',
      nouns: ['steps', 'phaser'],
      roles: ['pulse'],
      traits: ['fast', 'strange'],
    },
    'Saw riser': {
      says: 'a phaser that climbs for about two seconds and snaps back',
      brief: 'a climbing phaser',
      nouns: ['riser', 'phaser'],
      roles: ['motion'],
      traits: ['slow'],
    },
    'Bass safe': {
      says: 'a four-stage phaser kept high, leaving the low end alone',
      brief: 'a phaser kept up high',
      nouns: ['phaser', 'swirl'],
      roles: ['motion'],
      traits: ['slow'],
    },
    'Faint shade': {
      says: 'a trace of slow four-stage phaser under the dry sound',
      brief: 'a trace of slow phaser',
      nouns: ['shade', 'phaser'],
      roles: ['motion'],
      traits: ['faint', 'slow'],
    },
    'Glacial sweep': {
      says: 'a ten-stage phaser that takes most of a minute to sweep',
      brief: 'a glacial phaser sweep',
      nouns: ['sweep', 'phaser', 'glacier'],
      roles: ['motion'],
      traits: ['slow', 'wide'],
    },
    'Endless fall': {
      says: 'a ten-stage phaser falling from the top again and again',
      brief: 'a falling phaser',
      nouns: ['fall', 'phaser'],
      roles: ['motion'],
      traits: ['slow'],
    },
    'Two-tone flip': {
      says: 'a phaser flipping between two tones, opposite on each side',
      brief: 'a two-tone phaser flip',
      nouns: ['flip', 'phaser'],
      roles: ['pulse'],
      traits: ['wide'],
    },
    'Still formant': {
      says: 'a phaser held still, two fixed peaks like a vowel',
      brief: 'a phaser held still',
      nouns: ['formant', 'vowel', 'filter'],
      roles: ['tone'],
      traits: ['faint'],
    },
    'Stereo scatter': {
      says: 'a phaser with no dry sound, pulling the two sides apart',
      brief: 'an all-wet stereo phaser',
      nouns: ['scatter', 'phaser'],
      roles: ['width', 'motion'],
      traits: ['wide', 'slow'],
    },
  },
}
