import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'pitch-shifter',
  jitter: ['size', 'delay'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    'Octave up': {
      says: 'a single voice an octave above the dry sound',
      brief: 'an octave above',
      nouns: ['octave'],
      roles: ['pitch'],
      traits: ['high', 'bright'],
    },
    'Octave down': {
      says: 'a single voice an octave below the dry sound, darkened',
      brief: 'an octave below',
      nouns: ['octave', 'bass'],
      roles: ['pitch'],
      traits: ['low', 'dark'],
    },
    'Fifth above': {
      says: 'a single voice a fifth above the dry sound',
      brief: 'a fifth above',
      nouns: ['fifth', 'harmony'],
      roles: ['pitch'],
      traits: ['high'],
    },
    'Octaves both': {
      says: 'an octave above and an octave below, clean on chords',
      brief: 'octaves above and below',
      nouns: ['octaves'],
      roles: ['pitch'],
      traits: ['low', 'high'],
    },
    'Pad fifth': {
      says: 'a wide, slightly detuned fifth above held chords',
      brief: 'a wide fifth above chords',
      nouns: ['fifths', 'fifth'],
      roles: ['pitch'],
      traits: ['wide', 'high'],
    },
    'Pad below': {
      says: 'a dark octave below held chords, every note moved cleanly',
      brief: 'a dark octave below chords',
      nouns: ['octave', 'floor'],
      roles: ['pitch'],
      traits: ['low', 'dark'],
    },
    Doubler: {
      says: 'two copies a few cents sharp and flat, left and right',
      brief: 'a detuned stereo double',
      nouns: ['double', 'pair'],
      roles: ['width'],
      traits: ['wide'],
    },
    'Rising steps': {
      says: 'echoes that climb an octave on every repeat',
      brief: 'echoes climbing by octaves',
      nouns: ['steps', 'stairs', 'echoes'],
      roles: ['echo', 'pitch'],
      traits: ['high', 'bright'],
    },
    Shimmer: {
      says: 'a grainy octave and twelfth above, thickened by feedback',
      brief: 'a grainy octave sheen',
      nouns: ['shimmer', 'sheen'],
      roles: ['pitch', 'grain'],
      traits: ['high', 'bright'],
    },
    'Broken choir': {
      says: 'a fluttering fifth above and fourth below, out of tune',
      brief: 'a fluttering, sour harmony',
      nouns: ['choir', 'voices'],
      roles: ['pitch'],
      traits: ['unsteady', 'worn', 'wide'],
    },
    'Slow cloud': {
      says: 'a scattered cloud of long grains, some an octave up',
      brief: 'a cloud of long grains',
      nouns: ['cloud', 'grains'],
      roles: ['grain', 'pitch'],
      traits: ['wide', 'high'],
    },
    'Metal grains': {
      says: 'a buzzing metallic fifth above from very short grains',
      brief: 'a buzzing metallic fifth',
      nouns: ['metal', 'buzz', 'grains'],
      roles: ['pitch', 'grain'],
      traits: ['cold', 'strange', 'high'],
    },
    'Falling steps': {
      says: 'echoes that fall a fourth further on every repeat',
      brief: 'echoes falling by fourths',
      nouns: ['steps', 'descent', 'echoes'],
      roles: ['echo', 'pitch'],
      traits: ['low'],
    },
    'High sparks': {
      says: 'scattered sparks two octaves up, echoing higher still',
      brief: 'sparks two octaves up',
      nouns: ['sparks', 'glitter'],
      roles: ['grain', 'pitch'],
      traits: ['high', 'bright'],
    },
    'Faint air': {
      says: 'a faint octave above, a little air over the dry sound',
      brief: 'a faint octave of air',
      nouns: ['air', 'octave'],
      roles: ['pitch'],
      traits: ['faint', 'high'],
    },
    'Two octaves': {
      says: 'dark voices one and two octaves below the dry sound',
      brief: 'dark voices far below',
      nouns: ['depths', 'bass'],
      roles: ['pitch'],
      traits: ['low', 'dark'],
    },
  },
}
