import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'radio',
  jitter: [],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    'Night shortwave': {
      says: 'a shortwave station at night, thin, mono, fading in static',
      brief: 'a shortwave station at night',
      nouns: ['shortwave', 'station', 'static'],
      roles: ['wear'],
      traits: ['heavy', 'far', 'narrow', 'cold', 'worn', 'noisy'],
    },
    'Kitchen radio': {
      says: 'a small medium-wave radio, boxy and nasal, with light static',
      brief: 'a small boxy radio',
      nouns: ['radio', 'station'],
      roles: ['wear'],
      traits: ['narrow', 'cold', 'worn', 'noisy'],
    },
    'Far station': {
      says: 'a far shortwave station that sinks deep into rising static',
      brief: 'a far station under static',
      nouns: ['station', 'static', 'signal'],
      roles: ['wear'],
      traits: ['heavy', 'far', 'narrow', 'worn', 'noisy', 'bright'],
    },
    'Off the dial': {
      says: 'a shortwave set tuned off the station, whistling and broken',
      brief: 'a radio tuned off-station',
      nouns: ['static', 'radio', 'whistle'],
      roles: ['wear'],
      traits: ['heavy', 'strange', 'narrow', 'worn', 'noisy'],
    },
    'Sideband voices': {
      says: 'a mistuned sideband signal in static, every pitch gone sour',
      brief: 'a mistuned sideband signal',
      nouns: ['signal', 'sideband', 'radio'],
      roles: ['wear', 'pitch'],
      traits: ['heavy', 'strange', 'narrow', 'worn', 'noisy'],
    },
    Numbers: {
      says: 'a nasal shortwave channel crossed by whistles and data tones',
      brief: 'a nasal shortwave channel',
      nouns: ['shortwave', 'signal'],
      roles: ['wear'],
      traits: ['heavy', 'strange', 'narrow', 'cold', 'worn', 'noisy'],
    },
    'Storm coming': {
      says: 'a medium-wave station under the crackle of a far storm',
      brief: 'a station under storm static',
      nouns: ['static', 'crackle', 'storm'],
      roles: ['wear', 'hiss'],
      traits: ['heavy', 'narrow', 'worn', 'noisy', 'bright'],
    },
    'Between stations': {
      says: 'a dial left between stations, mostly whistle and static',
      brief: 'a dial between stations',
      nouns: ['static', 'whistle'],
      roles: ['wear', 'hiss'],
      traits: ['heavy', 'strange', 'far', 'narrow', 'noisy', 'bright'],
    },
    'Clean transistor': {
      says: 'a small mono transistor radio with a clear, steady signal',
      brief: 'a clear transistor radio',
      nouns: ['radio', 'station'],
      roles: ['wear'],
      traits: ['narrow'],
    },
    'Hint of static': {
      says: 'a medium-wave radio under the dry sound, mostly its static',
      brief: 'radio static under the sound',
      nouns: ['static', 'radio', 'hiss'],
      roles: ['hiss', 'wear'],
      traits: ['noisy'],
    },
    'Ghost voices': {
      says: 'a wrongly pitched sideband copy shadowing the dry sound',
      brief: 'an off-pitch radio copy',
      nouns: ['signal', 'sideband'],
      roles: ['pitch', 'wear'],
      traits: ['strange', 'cold'],
    },
    'Clear sideband': {
      says: 'a well-tuned sideband signal, mono, with light static',
      brief: 'a well-tuned sideband signal',
      nouns: ['signal', 'sideband', 'radio'],
      roles: ['wear'],
      traits: ['narrow', 'cold', 'noisy'],
    },
    'Sour sideband': {
      says: 'a sideband signal tuned far off, its harmonies turned sour',
      brief: 'a sour, off-tune sideband',
      nouns: ['signal', 'sideband'],
      roles: ['pitch', 'wear'],
      traits: ['heavy', 'strange', 'narrow', 'bright'],
    },
    'Drifting dial': {
      says: 'a medium-wave set whose dial slips off into whistle and back',
      brief: 'a radio with a sliding dial',
      nouns: ['radio', 'drift'],
      roles: ['wear'],
      traits: ['heavy', 'narrow', 'dark', 'worn', 'noisy', 'slow'],
    },
    'Crowded band': {
      says: 'a shortwave station crowded by whistles, buzz and data tones',
      brief: 'a crowded shortwave band',
      nouns: ['shortwave', 'whistles'],
      roles: ['wear'],
      traits: ['heavy', 'strange', 'narrow', 'noisy', 'bright'],
    },
    'Static wash': {
      says: 'a steady shortwave signal half buried in a wash of static',
      brief: 'a signal buried in static',
      nouns: ['static', 'wash', 'hiss'],
      roles: ['hiss', 'wear'],
      traits: ['heavy', 'narrow', 'noisy', 'bright'],
    },
  },
}
