import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'radio',
  jitter: [],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    'Night shortwave': {
      says: 'a shortwave station at night, thin, mono, fading in static',
      brief: 'a shortwave station at night',
      nouns: ['shortwave', 'station', 'static'],
      roles: ['wear'],
      traits: ['heavy', 'far', 'narrow', 'cold', 'worn', 'noisy', 'long'],
    },
    'Kitchen radio': {
      says: 'a small medium-wave radio, boxy and honking, nearly steady',
      brief: 'a small boxy radio',
      nouns: ['radio', 'speaker', 'wireless'],
      roles: ['wear'],
      traits: ['narrow', 'cold', 'worn'],
    },
    'Far station': {
      says: 'a far shortwave station that sinks deep into rising static',
      brief: 'a far station under static',
      nouns: ['station', 'static', 'signal'],
      roles: ['wear', 'hiss'],
      traits: ['heavy', 'far', 'narrow', 'worn', 'noisy', 'bright', 'long'],
    },
    'Off the dial': {
      says: 'a shortwave set tuned off the station, whistling and broken',
      brief: 'a radio tuned off-station',
      nouns: ['dial', 'whistle', 'static'],
      roles: ['wear'],
      traits: ['heavy', 'strange', 'narrow', 'worn', 'noisy', 'long'],
    },
    'Sideband voices': {
      says: 'a sideband signal tuned wrong, every pitch shifted and sour',
      brief: 'a mistuned sideband signal',
      nouns: ['sideband', 'voices', 'signal'],
      roles: ['wear', 'pitch'],
      traits: ['heavy', 'strange', 'narrow', 'worn', 'noisy', 'long'],
    },
    Numbers: {
      says: 'a nasal shortwave channel crossed by whistles and data tones',
      brief: 'a nasal shortwave channel',
      nouns: ['numbers', 'shortwave', 'signal'],
      roles: ['wear'],
      traits: ['heavy', 'strange', 'narrow', 'cold', 'worn', 'noisy'],
    },
    'Storm coming': {
      says: 'a medium-wave station under the crackle of a far storm',
      brief: 'a station under storm static',
      nouns: ['storm', 'static', 'crackle'],
      roles: ['wear', 'hiss'],
      traits: ['heavy', 'narrow', 'worn', 'noisy', 'bright', 'long'],
    },
    'Between stations': {
      says: 'a dial left between stations, mostly whistle and static',
      brief: 'a dial between stations',
      nouns: ['static', 'dial', 'whistle'],
      roles: ['wear', 'hiss'],
      traits: ['heavy', 'strange', 'far', 'narrow', 'noisy', 'bright', 'long'],
    },
    'Clean transistor': {
      says: 'a small mono transistor radio with a clear, steady signal',
      brief: 'a clear transistor radio',
      nouns: ['radio', 'speaker', 'set'],
      roles: ['wear'],
      traits: ['narrow', 'clean'],
    },
    'Hint of static': {
      says: 'a medium-wave radio mixed in low, mostly its static',
      brief: 'radio static mixed in low',
      nouns: ['static', 'radio', 'hiss'],
      roles: ['hiss', 'wear'],
      traits: ['noisy'],
    },
    'Ghost voices': {
      says: 'a quiet, wrongly pitched sideband copy under the dry sound',
      brief: 'a quiet off-pitch copy',
      nouns: ['ghosts', 'voices', 'sideband'],
      roles: ['pitch', 'wear'],
      traits: ['strange', 'cold'],
    },
    'Clear sideband': {
      says: 'a well-tuned sideband signal, steady, full-band and mono',
      brief: 'a well-tuned sideband link',
      nouns: ['sideband', 'signal', 'link'],
      roles: ['wear'],
      traits: ['narrow', 'cold'],
    },
    'Sour sideband': {
      says: 'a sideband signal tuned far off, its harmonies turned sour',
      brief: 'a sour, off-tune sideband',
      nouns: ['discord', 'sideband'],
      roles: ['pitch', 'wear'],
      traits: ['heavy', 'strange', 'narrow', 'bright'],
    },
    'Drifting dial': {
      says: 'a medium-wave set whose dial slides off the station and back',
      brief: 'a radio with a sliding dial',
      nouns: ['dial', 'drift', 'radio'],
      roles: ['wear'],
      traits: ['heavy', 'narrow', 'dark', 'worn', 'slow'],
    },
    'Crowded band': {
      says: 'a shortwave station crowded by whistles, buzz and data tones',
      brief: 'a crowded shortwave band',
      nouns: ['shortwave', 'whistles', 'chatter'],
      roles: ['wear'],
      traits: ['heavy', 'strange', 'narrow', 'noisy', 'bright', 'long'],
    },
    'Static wash': {
      says: 'a full-band shortwave signal half buried in steady static',
      brief: 'a signal buried in static',
      nouns: ['static', 'wash', 'hiss'],
      roles: ['hiss', 'wear'],
      traits: ['heavy', 'narrow', 'noisy', 'bright', 'long'],
    },
  },
}
