import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 're-amp',
  jitter: [],
  trim: [
    { param: 'output', kind: 'db' },
    { param: 'mix', kind: 'mix' },
  ],
  voices: {
    'Combo in a room': {
      says: 'a combo amplifier recorded fairly close in a small room',
      brief: 'a combo amp in a room',
      nouns: ['amp'],
      roles: ['drive'],
      traits: ['short'],
    },
    'Bedside radio': {
      says: 'a small, boxy radio speaker close by in a small room',
      brief: 'a small radio speaker',
      nouns: ['radio'],
      roles: ['drive', 'wear'],
      traits: ['cold', 'worn', 'short'],
    },
    'Down the hall': {
      says: 'a combo amplifier heard from the far side of a big room',
      brief: 'a far-off combo amp',
      nouns: ['hallway', 'amp', 'corridor'],
      roles: ['room'],
      traits: ['far', 'wide'],
    },
    'Station platform': {
      says: 'a nasal horn loudspeaker heard from far across a big room',
      brief: 'a far-off horn loudspeaker',
      nouns: ['station', 'platform'],
      roles: ['room'],
      traits: ['far', 'wide', 'bright', 'cold'],
    },
    'Warm stack': {
      says: 'a dark, driven amplifier stack with the mic off to one side',
      brief: 'a warm amplifier stack',
      nouns: ['amp', 'valves'],
      roles: ['drive'],
      traits: ['dark', 'warm'],
    },
    'Speaker on the edge': {
      says: 'a combo amplifier driven hard and recorded right up close',
      brief: 'a hard-driven combo amp',
      nouns: ['amp', 'valves'],
      roles: ['drive'],
      traits: ['warm'],
    },
    'Just the room': {
      says: 'a clean speaker heard from well back in a room',
      brief: 'a clean speaker in a room',
      nouns: ['room'],
      roles: ['room'],
      traits: ['clean', 'far', 'wide', 'short'],
    },
    'Pillow speaker': {
      says: 'a small amplifier muffled as if under a pillow',
      brief: 'a small muffled amplifier',
      nouns: ['amp'],
      roles: ['drive', 'wear'],
      traits: ['worn', 'dark'],
    },
    'Just the valves': {
      says: 'amplifier valves driven until they round off every peak',
      brief: 'a driven valve amplifier',
      nouns: ['valves', 'amp'],
      roles: ['drive'],
      traits: ['warm'],
    },
    'Clean and bright': {
      says: 'a clean combo amplifier with the treble all the way up',
      brief: 'a clean, bright combo amp',
      nouns: ['amp'],
      roles: ['drive'],
      traits: ['bright', 'clean'],
    },
    'Dark and woolly': {
      says: 'a dark amplifier stack with the bass full up and no treble',
      brief: 'a dark, woolly amp stack',
      nouns: ['amp'],
      roles: ['drive'],
      traits: ['dark', 'warm'],
    },
    'In the cupboard': {
      says: 'a combo amplifier boxed in by the walls of a cupboard',
      brief: 'an amp in a cupboard',
      nouns: ['amp'],
      roles: ['drive', 'room'],
      traits: ['short', 'wide'],
    },
    'Far end of the hall': {
      says: 'a clean speaker at the far end of a big, echoing room',
      brief: 'a speaker far across a room',
      nouns: ['room', 'hallway'],
      roles: ['room'],
      traits: ['far', 'wide'],
    },
    'Room underneath': {
      says: 'a far-off room laid in beneath the sound',
      brief: 'a room beneath the sound',
      nouns: ['room'],
      roles: ['room'],
      traits: ['clean', 'wide', 'short'],
    },
    'Noisy valves': {
      says: 'a driven combo amplifier with its hiss and hum right up',
      brief: 'a hissing, humming amp',
      nouns: ['amp', 'valves', 'hum'],
      roles: ['drive'],
      traits: ['noisy'],
    },
    'Stack flat out': {
      says: 'an amplifier stack turned all the way up',
      brief: 'a flat-out amplifier stack',
      nouns: ['amp', 'valves'],
      roles: ['drive'],
      traits: ['warm'],
    },
  },
}
