import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 're-amp',
  jitter: [],
  trim: [
    { param: 'output', kind: 'db' },
    { param: 'mix', kind: 'mix' },
  ],
  voices: {
    'Combo in a room': {
      says: 'a combo amplifier miked fairly close in a small room',
      brief: 'a combo amp in a room',
      nouns: ['amp', 'combo', 'cabinet'],
      roles: ['drive'],
      traits: ['short'],
    },
    'Bedside radio': {
      says: 'a small, boxy radio speaker, close by in a small room',
      brief: 'a small radio speaker',
      nouns: ['radio', 'speaker'],
      roles: ['drive', 'wear'],
      traits: ['cold', 'worn', 'short'],
    },
    'Down the hall': {
      says: 'a combo amplifier heard from the far side of a big room',
      brief: 'a far-off combo amp',
      nouns: ['hallway', 'amp', 'corridor'],
      roles: ['drive', 'room'],
      traits: ['far', 'wide'],
    },
    'Station platform': {
      says: 'a honky horn loudspeaker heard from far across a big room',
      brief: 'a far-off horn loudspeaker',
      nouns: ['horn', 'platform', 'station'],
      roles: ['drive', 'room'],
      traits: ['far', 'wide', 'bright', 'cold'],
    },
    'Warm stack': {
      says: 'a closed amplifier stack, driven and dark, miked off-centre',
      brief: 'a warm amplifier stack',
      nouns: ['stack', 'amp'],
      roles: ['drive'],
      traits: ['dark', 'warm'],
    },
    'Speaker on the edge': {
      says: 'a combo amplifier driven hard, miked right on the cone',
      brief: 'a hard-driven combo amp',
      nouns: ['amp', 'cone', 'speaker'],
      roles: ['drive'],
      traits: ['warm'],
    },
    'Just the room': {
      says: 'a clean speaker in a room, miked from well back',
      brief: 'a clean miked room',
      nouns: ['room'],
      roles: ['room'],
      traits: ['clean', 'far', 'wide', 'short'],
    },
    'Pillow speaker': {
      says: 'a small speaker, close and muffled, as if under a pillow',
      brief: 'a muffled small speaker',
      nouns: ['speaker', 'pillow'],
      roles: ['drive', 'wear'],
      traits: ['worn'],
    },
    'Just the valves': {
      says: 'driven amplifier valves heard through a flat speaker',
      brief: 'a driven valve amplifier',
      nouns: ['valves', 'amp'],
      roles: ['drive'],
      traits: ['warm'],
    },
    'Clean and bright': {
      says: 'a clean combo amplifier with the treble all the way up',
      brief: 'a clean, bright combo amp',
      nouns: ['amp', 'combo'],
      roles: ['drive'],
      traits: ['bright', 'clean'],
    },
    'Dark and woolly': {
      says: 'an amplifier stack, all bass, with the mic turned away',
      brief: 'a dark, woolly stack',
      nouns: ['stack', 'amp'],
      roles: ['drive'],
      traits: ['dark', 'warm'],
    },
    'In the cupboard': {
      says: 'a combo amplifier shut in a cupboard, the mic pulled back',
      brief: 'an amp in a cupboard',
      nouns: ['cupboard', 'amp'],
      roles: ['drive', 'room'],
      traits: ['short', 'wide'],
    },
    'Far end of the hall': {
      says: 'a clean speaker at the far end of a big, live room',
      brief: 'a speaker far across a room',
      nouns: ['room', 'hallway'],
      roles: ['room'],
      traits: ['far', 'wide'],
    },
    'Room underneath': {
      says: 'a far-miked room laid in under the clean sound',
      brief: 'a room under the clean sound',
      nouns: ['room'],
      roles: ['room'],
      traits: ['clean', 'wide', 'short'],
    },
    'Noisy valves': {
      says: 'a driven combo amplifier with its hiss and hum right up',
      brief: 'a hissing, humming amp',
      nouns: ['amp', 'valves', 'hum'],
      roles: ['drive', 'hiss'],
      traits: ['noisy'],
    },
    'Stack flat out': {
      says: 'an amplifier stack turned all the way up',
      brief: 'a flat-out amplifier stack',
      nouns: ['stack', 'amp'],
      roles: ['drive'],
      traits: ['warm'],
    },
  },
}
