import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'reverse-delay',
  jitter: ['time'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    'Backwards echo': {
      says: 'a backwards echo of each phrase, swelling in and cut off',
      brief: 'a backwards echo',
      nouns: ['echo', 'mirror'],
      roles: ['echo'],
      traits: ['backwards'],
    },
    'Slow swells': {
      says: 'slow backwards swells that rise and die behind the playing',
      brief: 'slow backwards swells',
      nouns: ['swells', 'tide'],
      roles: ['echo'],
      traits: ['backwards', 'slow', 'long'],
    },
    'Rising glass': {
      says: 'backwards swells that climb an octave on every pass',
      brief: 'rising backwards swells',
      nouns: ['glass', 'swells'],
      roles: ['echo', 'pitch'],
      traits: ['backwards', 'high', 'bright', 'long'],
    },
    Undertow: {
      says: 'long backwards phrases an octave down, dark and slow',
      brief: 'a low backwards undertow',
      nouns: ['undertow', 'tide'],
      roles: ['echo', 'pitch'],
      traits: ['backwards', 'low', 'dark', 'slow', 'long', 'heavy'],
    },
    Flicker: {
      says: 'short backwards chunks that flicker from side to side',
      brief: 'a backwards flicker',
      nouns: ['flicker', 'shards'],
      roles: ['grain', 'echo'],
      traits: ['backwards', 'fast'],
    },
    'Long mirror': {
      says: 'whole phrases played backwards about four seconds later',
      brief: 'a long backwards mirror',
      nouns: ['mirror', 'echo'],
      roles: ['echo', 'loop'],
      traits: ['backwards', 'long', 'slow'],
    },
    'Hard splices': {
      says: 'backwards chunks spliced hard, with no fades between them',
      brief: 'hard backwards splices',
      nouns: ['splices', 'echo'],
      roles: ['echo', 'grain'],
      traits: ['backwards'],
    },
    'Tight stutter': {
      says: 'a tight backwards stutter close behind each note',
      brief: 'a tight backwards stutter',
      nouns: ['stutter'],
      roles: ['grain'],
      traits: ['backwards', 'fast', 'short', 'faint'],
    },
    'Faint reflection': {
      says: 'a faint backwards swell behind each phrase',
      brief: 'a faint backwards swell',
      nouns: ['mirror', 'trace'],
      roles: ['echo'],
      traits: ['backwards', 'faint'],
    },
    'Backwards only': {
      says: 'the playing turned backwards in place of the dry sound',
      brief: 'the playing turned backwards',
      nouns: ['mirror', 'swells'],
      roles: ['swell'],
      traits: ['backwards', 'heavy'],
    },
    'Glass splinters': {
      says: 'short backwards chunks that climb by octaves and splinter',
      brief: 'rising backwards splinters',
      nouns: ['splinters', 'glass', 'shards'],
      roles: ['grain', 'pitch', 'echo'],
      traits: ['backwards', 'high', 'bright', 'cold', 'fast'],
    },
    'Descending steps': {
      says: 'backwards repeats that step down an octave each time',
      brief: 'falling backwards repeats',
      nouns: ['steps', 'stairs'],
      roles: ['echo', 'pitch'],
      traits: ['backwards', 'low', 'dark'],
    },
    'Folding over': {
      says: 'backwards chunks fed back until they fold over each other',
      brief: 'folding backwards chunks',
      nouns: ['folds', 'mirror'],
      roles: [],
      traits: ['backwards', 'long', 'heavy'],
      skip: 'It grows by itself: half a minute after the playing stops it is louder than it was while played.',
    },
    'Dark fog': {
      says: 'a dark fog of slow backwards swells',
      brief: 'a dark backwards fog',
      nouns: ['fog', 'swells'],
      roles: ['echo'],
      traits: ['backwards', 'dark', 'long', 'slow', 'far'],
    },
    'Thin and airy': {
      says: 'thin backwards repeats with their lows cut away',
      brief: 'thin backwards repeats',
      nouns: ['air', 'mirror'],
      roles: ['echo'],
      traits: ['backwards', 'cold', 'bright'],
    },
    'Phrase and mirror': {
      says: 'each phrase answered once by itself played backwards',
      brief: 'a single backwards answer',
      nouns: ['mirror', 'answer'],
      roles: ['echo'],
      traits: ['backwards', 'slow', 'clean'],
    },
  },
}
