import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'rotary',
  jitter: [],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    Chorale: {
      says: 'a rotating speaker on its slow speed',
      brief: 'a slow rotating speaker',
      nouns: ['chorale', 'rotary', 'speaker'],
      roles: ['motion'],
      traits: ['warm'],
    },
    Tremolo: {
      says: 'a rotating speaker on its fast speed',
      brief: 'a fast rotating speaker',
      nouns: ['rotary', 'speaker', 'rotor'],
      roles: ['pulse'],
      traits: ['fast', 'warm'],
    },
    'Stopped horn': {
      says: 'a rotating speaker at a standstill, heard close and in mono',
      brief: 'a stopped rotating speaker',
      nouns: ['cabinet', 'horn', 'speaker'],
      roles: ['drive', 'tone'],
      traits: ['narrow', 'warm'],
    },
    Growl: {
      says: 'a fast rotating speaker with its amplifier growling',
      brief: 'a fast growling speaker',
      nouns: ['growl', 'rotary'],
      roles: ['pulse', 'drive'],
      traits: ['fast', 'warm'],
    },
    'Across the room': {
      says: 'a slow rotating speaker heard from across the room',
      brief: 'a far slow rotating speaker',
      nouns: ['rotary', 'speaker'],
      roles: ['motion'],
      traits: ['far'],
    },
    'Heavy rotors': {
      says: 'a fast rotating speaker whose drum pulses the lows deeply',
      brief: 'a fast deep-drum speaker',
      nouns: ['rotors', 'rotary'],
      roles: ['pulse'],
      traits: ['fast', 'warm'],
    },
    'Guitar swirl': {
      says: 'a fast spinning horn laid over the dry sound',
      brief: 'a fast horn swirl',
      nouns: ['swirl', 'horn'],
      roles: ['pulse'],
      traits: ['fast', 'dark'],
    },
    'Faint motion': {
      says: 'a slow rotating speaker set shallow and mixed half dry',
      brief: 'a barely turning speaker',
      nouns: ['rotary', 'sway'],
      roles: ['motion'],
      traits: ['faint', 'dark', 'clean'],
    },
    'Soft blend': {
      says: 'a clean slow rotating speaker blended under the dry sound',
      brief: 'a soft slow rotary blend',
      nouns: ['rotary', 'blend'],
      roles: ['motion'],
      traits: ['faint', 'dark', 'clean'],
    },
    'Mono cabinet': {
      says: 'a slow rotating speaker heard through one microphone',
      brief: 'a mono rotating speaker',
      nouns: ['cabinet', 'rotary'],
      roles: ['motion'],
      traits: ['narrow', 'warm'],
    },
    'Dark drum': {
      says: 'a slow rotating speaker that is mostly its low, dark drum',
      brief: 'a slow dark bass rotor',
      nouns: ['rotor', 'drum'],
      roles: ['motion'],
      traits: ['dark', 'warm', 'clean'],
    },
    'Bright horn': {
      says: 'a fast rotating speaker with the horn to the fore',
      brief: 'a fast forward horn',
      nouns: ['horn', 'rotary'],
      roles: ['pulse'],
      traits: ['fast'],
    },
    'Far shimmer': {
      says: 'a fast spinning horn heard from far off, smooth and chorused',
      brief: 'a far fast spinning horn',
      nouns: ['horn', 'swirl'],
      roles: ['pulse', 'motion'],
      traits: ['fast', 'far', 'clean'],
    },
    'Close pulse': {
      says: 'a fast rotating speaker at full depth, microphones close',
      brief: 'a close fast rotary pulse',
      nouns: ['pulse', 'rotary'],
      roles: ['pulse'],
      traits: ['fast', 'warm'],
    },
    'Slow burn': {
      says: 'a slow rotating speaker with its amplifier driven hard',
      brief: 'a slow overdriven speaker',
      nouns: ['rotary', 'growl', 'speaker'],
      roles: ['motion', 'drive'],
      traits: ['warm'],
    },
    'Parked growl': {
      says: 'a stopped speaker cabinet with its amplifier growling',
      brief: 'a stopped growling cabinet',
      nouns: ['cabinet', 'growl'],
      roles: ['drive'],
      traits: ['warm', 'narrow'],
    },
  },
}
