import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'rotary',
  jitter: [],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    Chorale: {
      says: 'a rotating speaker on its slow speed',
      brief: 'a slow rotating speaker',
      nouns: ['rotary'],
      roles: ['motion'],
      traits: ['warm'],
    },
    Tremolo: {
      says: 'a rotating speaker on its fast speed',
      brief: 'a fast rotating speaker',
      nouns: ['rotary'],
      roles: ['pulse'],
      traits: ['fast', 'warm'],
    },
    'Stopped horn': {
      says: 'a rotating speaker at a standstill, heard close and in mono',
      brief: 'a stopped rotating speaker',
      nouns: ['rotary'],
      roles: ['drive'],
      traits: ['narrow', 'warm'],
    },
    Growl: {
      says: 'a fast rotating speaker with its amplifier growling',
      brief: 'a fast growling speaker',
      nouns: ['rotary'],
      roles: ['pulse', 'drive'],
      traits: ['fast', 'warm'],
    },
    'Across the room': {
      says: 'a slow rotating speaker heard from across the room',
      brief: 'a distant, slow rotary',
      nouns: ['rotary'],
      roles: ['motion'],
      traits: ['far'],
    },
    'Heavy rotors': {
      says: 'a fast rotating speaker that pulses the lows deeply',
      brief: 'a fast deep-pulsing speaker',
      nouns: ['rotary'],
      roles: ['pulse'],
      traits: ['fast', 'warm'],
    },
    'Guitar swirl': {
      says: 'a fast spinning speaker horn laid over the dry sound',
      brief: 'a fast rotary swirl',
      nouns: ['swirl', 'rotary'],
      roles: ['pulse'],
      traits: ['fast', 'dark'],
    },
    'Faint motion': {
      says: 'a slow rotating speaker with a shallow, gentle sway',
      brief: 'a slow, gentle rotary sway',
      nouns: ['rotary', 'sway'],
      roles: ['motion'],
      traits: ['faint', 'dark', 'clean'],
    },
    'Soft blend': {
      says: 'a clean slow rotating speaker blended under the dry sound',
      brief: 'a soft slow rotary blend',
      nouns: ['rotary'],
      roles: ['motion'],
      traits: ['faint', 'dark', 'clean'],
    },
    'Mono cabinet': {
      says: 'a slow rotating speaker heard through one microphone',
      brief: 'a mono rotating speaker',
      nouns: ['rotary'],
      roles: ['motion'],
      traits: ['narrow', 'warm'],
    },
    'Dark drum': {
      says: 'a dark slow rotating speaker that mostly turns the lows',
      brief: 'a dark slow rotating speaker',
      nouns: ['rotary'],
      roles: ['motion'],
      traits: ['dark', 'warm', 'clean'],
    },
    'Bright horn': {
      says: 'a fast rotating speaker with its bright horn to the fore',
      brief: 'a fast bright rotary',
      nouns: ['rotary'],
      roles: ['pulse'],
      traits: ['fast', 'bright'],
    },
    'Far shimmer': {
      says: 'a fast rotating speaker heard from far off, smooth and even',
      brief: 'a distant, fast rotary swirl',
      nouns: ['swirl', 'rotary'],
      roles: ['pulse', 'motion'],
      traits: ['fast', 'far', 'clean'],
    },
    'Close pulse': {
      says: 'a fast rotating speaker heard close, pulsing hard',
      brief: 'a close fast rotary pulse',
      nouns: ['pulse', 'rotary'],
      roles: ['pulse'],
      traits: ['fast', 'warm'],
    },
    'Slow burn': {
      says: 'a slow rotating speaker with its amplifier driven hard',
      brief: 'a slow overdriven speaker',
      nouns: ['rotary'],
      roles: ['motion', 'drive'],
      traits: ['warm'],
    },
    'Parked growl': {
      says: 'a stopped rotating speaker with its amplifier growling',
      brief: "a stopped rotary's amp growl",
      nouns: ['amp', 'valves'],
      roles: ['drive'],
      traits: ['warm', 'narrow'],
    },
  },
}
