import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'saturator',
  jitter: [],
  trim: [
    { param: 'outputDb', kind: 'db' },
    { param: 'mix', kind: 'mix' },
  ],
  voices: {
    Init: {
      says: 'a soft clipper at its starting point',
      brief: 'a soft clipper at rest',
      nouns: ['clipper'],
      roles: [],
      traits: ['faint'],
      skip: 'It is the device at rest: on the bench it is the dry sound six decibels louder and nothing else.',
    },
    'Warm glue': {
      says: 'a few decibels of soft saturation with the top eased',
      brief: 'a little soft saturation',
      nouns: ['warmth'],
      roles: ['drive', 'glue'],
      traits: ['warm', 'faint', 'whole'],
    },
    'On tape': {
      says: 'tape-style saturation that rounds peaks and dulls the top',
      brief: 'soft tape-style saturation',
      nouns: ['warmth'],
      roles: ['drive'],
      traits: ['warm', 'dark', 'faint'],
    },
    'Tube preamp': {
      says: 'a valve preamp, gently driven and a little bright on top',
      brief: 'a brightish valve preamp',
      nouns: ['valves', 'preamp'],
      roles: ['drive'],
      traits: ['bright', 'faint'],
    },
    'Bass grit': {
      says: 'dark, thick valve grit that fills out the low end',
      brief: 'dark, thick valve grit',
      nouns: ['grit', 'valves'],
      roles: ['drive'],
      traits: ['dark', 'warm'],
    },
    'Drum bus crunch': {
      says: 'soft clipping, a little bright, laid under the clean sound',
      brief: 'a layer of soft clipping',
      nouns: ['grit'],
      roles: ['drive'],
      traits: ['bright', 'faint'],
    },
    'Hard clip master': {
      says: 'a hard clipper that touches only the very loudest peaks',
      brief: 'a peak-only hard clipper',
      nouns: ['limiter'],
      roles: ['ceiling'],
      traits: ['faint', 'whole'],
    },
    'Fuzz pedal': {
      says: 'a bright, buzzing fuzz from a hard clipper driven flat',
      brief: 'a bright, buzzing fuzz',
      nouns: ['fuzz'],
      roles: ['drive'],
      traits: ['bright', 'cold'],
    },
    'Wavefold lead': {
      says: 'a wavefolder that wraps the peaks over as bright overtones',
      brief: 'a bright wavefolder',
      nouns: ['overtones'],
      roles: ['drive'],
      traits: ['bright', 'cold'],
    },
    'Blown speaker': {
      says: 'a wavefolder at full drive, broken up like a torn speaker',
      brief: 'a wavefolder at full drive',
      nouns: ['fuzz', 'grit'],
      roles: ['drive'],
      traits: ['strange', 'worn', 'wide'],
    },
    'Lo-fi': {
      says: 'a dull, hard-clipped fuzz with a rough digital edge',
      brief: 'a dull digital fuzz',
      nouns: ['grit'],
      roles: ['drive'],
      traits: ['dark', 'cold', 'strange'],
    },
    'Parallel shine': {
      says: 'bright tape-style saturation mixed in under the clean sound',
      brief: 'a bright layer of saturation',
      nouns: ['sheen'],
      roles: ['drive'],
      traits: ['bright', 'faint'],
    },
    'Soft tape warmth': {
      says: 'tape-style saturation that rounds only the loudest peaks',
      brief: 'light tape-style saturation',
      nouns: ['warmth'],
      roles: ['drive'],
      traits: ['warm', 'faint', 'whole'],
    },
    'Folded glass': {
      says: "a hint of a wavefolder's glassy edge under the clean sound",
      brief: 'a hint of wavefolder',
      nouns: ['overtones'],
      roles: ['drive'],
      traits: ['bright', 'cold', 'faint'],
    },
    'Octave glow': {
      says: 'soft saturation that adds the octave above each note',
      brief: 'octave-adding saturation',
      nouns: ['glow', 'overtone'],
      roles: ['drive'],
      traits: ['high', 'bright', 'faint'],
    },
    'Sustain bed': {
      says: 'a hard-clipped copy held at one level under the clean sound',
      brief: 'a flat clipped under-layer',
      nouns: ['fuzz'],
      roles: ['drive'],
      traits: ['dark'],
    },
  },
}
