import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'saturator',
  jitter: [],
  trim: [
    { param: 'outputDb', kind: 'db' },
    { param: 'mix', kind: 'mix' },
  ],
  voices: {
    Init: {
      says: 'a soft clipper at its starting point',
      brief: 'a soft clipper at rest',
      nouns: ['clipper'],
      roles: [],
      traits: ['faint'],
      skip: 'It is the device at rest: on the bench it is the dry sound six decibels louder and nothing else.',
    },
    'Warm glue': {
      says: 'a few decibels of soft saturation with the top eased',
      brief: 'a little soft saturation',
      nouns: ['glue', 'drive'],
      roles: ['drive', 'glue'],
      traits: ['warm', 'faint'],
    },
    'On tape': {
      says: 'a tape-style curve that rounds the peaks and dulls the top',
      brief: 'soft tape-style saturation',
      nouns: ['tape', 'reel'],
      roles: ['drive'],
      traits: ['warm', 'dark', 'faint'],
    },
    'Tube preamp': {
      says: 'a valve preamp curve, lopsided and a little brighter on top',
      brief: 'a brightish valve curve',
      nouns: ['valve', 'preamp', 'tube'],
      roles: ['drive'],
      traits: ['bright', 'faint'],
    },
    'Bass grit': {
      says: 'a dark, thick valve curve mixed over some of the clean sound',
      brief: 'dark, thick valve grit',
      nouns: ['grit', 'valve'],
      roles: ['drive'],
      traits: ['dark', 'warm', 'faint'],
    },
    'Drum bus crunch': {
      says: 'soft clipping, a little bright, laid under the clean sound',
      brief: 'soft clipping, mixed low',
      nouns: ['crunch', 'grit'],
      roles: ['drive'],
      traits: ['bright', 'faint'],
    },
    'Hard clip master': {
      says: 'a hard clipper that touches only the very loudest peaks',
      brief: 'a peak-only hard clipper',
      nouns: ['clipper', 'ceiling'],
      roles: ['ceiling'],
      traits: ['faint'],
    },
    'Fuzz pedal': {
      says: 'a bright, buzzing fuzz from a hard clipper driven flat',
      brief: 'a bright, buzzing fuzz',
      nouns: ['fuzz', 'buzz'],
      roles: ['drive'],
      traits: ['bright', 'cold'],
    },
    'Wavefold lead': {
      says: 'a wavefolder that wraps the peaks over into bright overtones',
      brief: 'a bright wavefolder',
      nouns: ['fold', 'edge'],
      roles: ['drive'],
      traits: ['bright', 'cold'],
    },
    'Blown speaker': {
      says: 'a wavefolder at full drive, broken up like a torn speaker',
      brief: 'a wavefolder at full drive',
      nouns: ['wreck', 'speaker', 'cone'],
      roles: ['drive'],
      traits: ['strange', 'worn', 'wide'],
    },
    'Lo-fi': {
      says: 'a dull hard clipper with no oversampling, so it aliases',
      brief: 'a dull, aliasing clipper',
      nouns: ['clipper', 'grit', 'dust'],
      roles: ['drive', 'wear'],
      traits: ['dark', 'worn'],
    },
    'Parallel shine': {
      says: 'bright tape-style saturation mixed in under the clean sound',
      brief: 'bright saturation, mixed low',
      nouns: ['sheen', 'edge'],
      roles: ['drive'],
      traits: ['bright', 'faint'],
    },
    'Soft tape warmth': {
      says: 'a tape-style curve only just leaned on',
      brief: 'a barely driven tape curve',
      nouns: ['tape', 'reel'],
      roles: ['drive'],
      traits: ['warm', 'faint'],
    },
    'Folded glass': {
      says: "a hint of a wavefolder's glassy edge under the clean sound",
      brief: 'a hint of wavefolder',
      nouns: ['glass', 'fold'],
      roles: ['drive'],
      traits: ['bright', 'cold', 'faint'],
    },
    'Octave glow': {
      says: 'a lopsided soft curve that adds the octave above each note',
      brief: 'an octave-adding soft curve',
      nouns: ['glow', 'overtone'],
      roles: ['drive'],
      traits: ['high', 'bright', 'faint'],
    },
    'Sustain bed': {
      says: 'a hard-clipped copy held at one level under the clean sound',
      brief: 'a flat clipped under-layer',
      nouns: ['bed', 'fuzz'],
      roles: ['drive'],
      traits: ['dark'],
    },
  },
}
