import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'shaped-reverb',
  jitter: ['time', 'preDelay'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    Reverse: {
      says: 'a reverb that grows backwards behind each note and cuts off',
      brief: 'a backwards reverb',
      nouns: ['cloud', 'swell', 'rise'],
      roles: ['room'],
      traits: ['backwards', 'wide'],
    },
    Gated: {
      says: 'a short burst of reverb that holds and stops dead',
      brief: 'a short gated reverb',
      nouns: ['gate', 'burst', 'room'],
      roles: ['room'],
      traits: ['short', 'faint'],
    },
    Bloom: {
      says: 'a cloud of reverb that swells in after each note and fades',
      brief: 'a swelling reverb cloud',
      nouns: ['cloud', 'swell', 'bloom'],
      roles: ['hall'],
      traits: ['slow', 'wide'],
    },
    Falling: {
      says: 'a reverb that falls away in a straight line',
      brief: 'a straight-falling reverb',
      nouns: ['room', 'fall', 'slope'],
      roles: ['room'],
      traits: ['clean'],
    },
    Breathing: {
      says: 'a reverb that breathes in slow waves over and over',
      brief: 'a breathing reverb',
      nouns: ['breath', 'waves', 'tide'],
      roles: ['hall', 'motion'],
      traits: ['long', 'slow', 'wide'],
    },
    Ghost: {
      says: 'a dark reverb that rises backwards and leaves a dim tail',
      brief: 'a dark backwards reverb',
      nouns: ['ghost', 'shade', 'cloud'],
      roles: ['hall'],
      traits: ['dark', 'backwards', 'slow', 'wide'],
    },
    'Short halo': {
      says: 'a brief swell of reverb close behind each note',
      brief: 'a brief swell of reverb',
      nouns: ['glow', 'bloom', 'room'],
      roles: ['room'],
      traits: ['short'],
    },
    'Long rise': {
      says: 'a reverb that rises backwards for about four seconds',
      brief: 'a long backwards rise',
      nouns: ['rise', 'swell', 'cloud'],
      roles: ['hall'],
      traits: ['backwards', 'slow', 'wide', 'heavy'],
    },
    Scattered: {
      says: 'a handful of separate echoes that fall away and repeat',
      brief: 'a scatter of falling echoes',
      nouns: ['echoes', 'scatter', 'shards'],
      roles: ['echo'],
      traits: ['clean'],
    },
    'Gate steps': {
      says: 'gated bursts of reverb repeating about four times a second',
      brief: 'repeating gated bursts',
      nouns: ['steps', 'gate', 'stutter'],
      roles: ['pulse', 'echo'],
      traits: ['fast'],
    },
    'Slow tide': {
      says: 'a reverb that swells and ebbs in waves of about four seconds',
      brief: 'a slow tide of reverb',
      nouns: ['tide', 'waves', 'swell'],
      roles: ['hall', 'motion'],
      traits: ['long', 'slow'],
    },
    Ripples: {
      says: 'quick waves of reverb rippling about twice a second',
      brief: 'quick ripples of reverb',
      nouns: ['ripples', 'waves', 'pulse'],
      roles: ['pulse', 'echo'],
      traits: ['fast', 'wide'],
    },
    'Mono slap': {
      says: 'a short mono slap of a few reflections',
      brief: 'a short mono slap',
      nouns: ['slap', 'wall', 'room'],
      roles: ['room'],
      traits: ['short', 'narrow', 'faint'],
    },
    'Dark swell': {
      says: 'a dull reverb that swells in over seconds and fades slowly',
      brief: 'a slow dark swell',
      nouns: ['swell', 'cloud', 'fog'],
      roles: ['hall'],
      traits: ['dark', 'slow', 'wide'],
    },
    Sparkles: {
      says: 'a few thin bright echoes that rise backwards and repeat',
      brief: 'thin backwards echoes',
      nouns: ['sparkles', 'glints', 'shards'],
      roles: ['echo'],
      traits: ['bright', 'cold', 'backwards'],
    },
    'Late wall': {
      says: 'a late wall of reverb that holds and stops dead',
      brief: 'a late wall of reverb',
      nouns: ['wall', 'gate', 'room'],
      roles: ['room'],
      traits: ['clean'],
    },
  },
}
