import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'shaped-reverb',
  jitter: ['time', 'preDelay'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    Reverse: {
      says: 'a reverb that swells up behind each note and cuts off',
      brief: 'a rising, cut-off reverb',
      nouns: ['swell'],
      roles: ['room'],
      traits: ['wide', 'backwards'],
    },
    Gated: {
      says: 'a short burst of reverb that holds and stops dead',
      brief: 'a short gated reverb',
      nouns: ['room'],
      roles: ['room'],
      traits: ['short', 'fast', 'faint'],
    },
    Bloom: {
      says: 'a reverb that swells in after each note and fades away',
      brief: 'a swelling, fading reverb',
      nouns: ['swell', 'bloom'],
      roles: ['hall'],
      traits: ['slow', 'wide'],
    },
    Falling: {
      says: 'a reverb that fades evenly to nothing in a second or two',
      brief: 'an evenly fading reverb',
      nouns: ['room'],
      roles: ['room'],
      traits: ['clean'],
    },
    Breathing: {
      says: 'a long reverb that comes and goes in waves, over and over',
      brief: 'a long reverb in waves',
      nouns: ['tide', 'waves'],
      roles: ['hall'],
      traits: ['long', 'wide'],
    },
    Ghost: {
      says: 'a dark reverb that rises behind each note and lingers',
      brief: 'a dark rising reverb',
      nouns: ['shade', 'swell'],
      roles: ['hall'],
      traits: ['dark', 'slow', 'wide'],
    },
    'Short halo': {
      says: 'a brief swell of reverb close behind each note',
      brief: 'a brief swell of reverb',
      nouns: ['glow', 'bloom', 'room'],
      roles: ['room'],
      traits: ['short'],
    },
    'Long rise': {
      says: 'a reverb that rises for about four seconds behind each note',
      brief: 'a long rising reverb',
      nouns: ['swell'],
      roles: ['hall'],
      traits: ['slow', 'wide', 'heavy', 'backwards'],
    },
    Scattered: {
      says: 'a handful of separate echoes that fall away and repeat',
      brief: 'a scatter of falling echoes',
      nouns: ['echoes'],
      roles: ['echo'],
      traits: ['clean'],
    },
    'Gate steps': {
      says: 'gated bursts of reverb repeating about four times a second',
      brief: 'repeating gated bursts',
      nouns: ['pulse'],
      roles: ['pulse'],
      traits: ['fast'],
    },
    'Slow tide': {
      says: 'a reverb that swells and ebbs in waves of over a second each',
      brief: 'a slow tide of reverb',
      nouns: ['tide', 'waves', 'swell'],
      roles: ['hall'],
      traits: ['long', 'slow'],
    },
    Ripples: {
      says: 'quick waves of reverb rippling about twice a second',
      brief: 'quick ripples of reverb',
      nouns: ['ripples', 'waves', 'pulse'],
      roles: ['pulse'],
      traits: ['fast', 'wide'],
    },
    'Mono slap': {
      says: 'a short mono burst of a few close reflections',
      brief: 'a short mono burst',
      nouns: ['room'],
      roles: ['room'],
      traits: ['short', 'narrow', 'faint'],
    },
    'Dark swell': {
      says: 'a dull reverb that swells in over seconds and fades slowly',
      brief: 'a slow, dark swell of reverb',
      nouns: ['swell', 'fog'],
      roles: ['hall'],
      traits: ['dark', 'slow', 'wide'],
    },
    Sparkles: {
      says: 'a few thin bright echoes that grow, cut off and repeat',
      brief: 'thin bright rising echoes',
      nouns: ['echoes', 'sparkles'],
      roles: ['echo'],
      traits: ['bright', 'cold'],
    },
    'Late wall': {
      says: 'a late wall of reverb that holds and fades away',
      brief: 'a late wall of reverb',
      nouns: ['room'],
      roles: ['room'],
      traits: ['clean'],
    },
  },
}
