import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'shimmer',
  jitter: ['decay', 'predelay'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    'Rising choir': {
      says: 'a reverb whose tail climbs an octave on every pass',
      brief: 'an octave-climbing reverb',
      nouns: ['halo', 'shimmer'],
      roles: ['halo'],
      traits: ['high', 'wide'],
    },
    Fifths: {
      says: 'a reverb whose tail climbs in fifths as it rings',
      brief: 'a reverb rising in fifths',
      nouns: ['fifths', 'halo', 'shimmer'],
      roles: ['halo'],
      traits: ['high', 'wide'],
    },
    'Organ loft': {
      says: 'a dark reverb stacking octaves and fifths like organ pipes',
      brief: 'a dark organ-like reverb',
      nouns: ['loft', 'halo'],
      roles: ['halo'],
      traits: ['dark', 'high', 'wide'],
    },
    Undertow: {
      says: 'a large reverb whose tail sinks an octave on every pass',
      brief: 'an octave-sinking reverb',
      nouns: ['undertow', 'depths', 'halo'],
      roles: ['halo'],
      traits: ['low', 'dark', 'wide'],
    },
    Glass: {
      says: 'a small glassy reverb with a glint two octaves up',
      brief: 'a glassy two-octave reverb',
      nouns: ['glint', 'halo', 'shimmer'],
      roles: ['halo'],
      traits: ['cold', 'bright', 'high'],
    },
    'Plain hall': {
      says: 'a plain hall that rings for about three seconds',
      brief: 'a plain medium hall',
      nouns: ['hall'],
      roles: ['hall'],
      traits: ['clean', 'wide'],
    },
    'Endless ascent': {
      says: 'a vast reverb where most of the tail climbs by octaves',
      brief: 'a vast climbing reverb',
      nouns: ['ascent', 'halo', 'shimmer'],
      roles: ['halo'],
      traits: ['high', 'wide', 'long'],
    },
    'Faint glimmer': {
      says: 'a quiet reverb with a glimmer an octave up in its tail',
      brief: 'a faint octave glimmer',
      nouns: ['glimmer', 'halo', 'glow'],
      roles: ['halo'],
      traits: ['faint', 'high'],
    },
    'Sparkle room': {
      says: 'a small room that sparkles two octaves above the sound',
      brief: 'a sparkling small room',
      nouns: ['sparkle', 'room', 'glint'],
      roles: ['room', 'halo'],
      traits: ['short', 'bright', 'high'],
    },
    'Narrow fifth': {
      says: 'a dull mono reverb whose tail climbs in fifths',
      brief: 'a mono reverb in fifths',
      nouns: ['fifths', 'halo'],
      roles: ['halo'],
      traits: ['narrow', 'dark', 'high'],
    },
    'Muffled choir': {
      says: 'a muffled reverb whose octave climb is soon damped away',
      brief: 'a muffled climbing reverb',
      nouns: ['murmur', 'halo'],
      roles: ['halo'],
      traits: ['dark', 'high'],
    },
    'Late answer': {
      says: 'a reverb that comes in late and climbs by octaves and fifths',
      brief: 'a late climbing reverb',
      nouns: ['halo', 'shimmer'],
      roles: ['halo'],
      traits: ['high', 'wide'],
    },
    'Rising tail alone': {
      says: 'the octave-climbing tail of a large reverb with no dry sound',
      brief: 'a rising reverb tail alone',
      nouns: ['halo', 'ascent', 'shimmer'],
      roles: ['halo'],
      traits: ['heavy', 'far', 'bright', 'high', 'wide'],
    },
    'Still pipes': {
      says: 'a small reverb with a long still ring of octaves and fifths',
      brief: 'a still octave-fifth reverb',
      nouns: ['halo', 'fifths', 'shimmer'],
      roles: ['halo'],
      traits: ['dark', 'high', 'long'],
    },
    'Swaying hall': {
      says: 'a hall that sways in pitch with a trace of the octave above',
      brief: 'a swaying hall',
      nouns: ['hall', 'sway', 'drift'],
      roles: ['hall'],
      traits: ['unsteady'],
    },
    'Low shadow': {
      says: 'a small room that casts a shadow an octave below',
      brief: 'a room with a low shadow',
      nouns: ['shadow', 'room'],
      roles: ['room', 'halo'],
      traits: ['low', 'wide'],
    },
  },
}
