import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'spectral-blur',
  // Blur sets how long things hang, but it is a share of the knob, not a time.
  jitter: [],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    'Hanging mist': {
      says: 'a diffuse mist where each note hangs on after it is played',
      brief: 'a hanging mist of overtones',
      nouns: ['mist', 'haze', 'wash'],
      roles: ['grain'],
      traits: ['wide'],
    },
    'Clean sustain': {
      says: 'every note sustained after it is played, with no smearing',
      brief: 'a clean, unsmeared sustain',
      nouns: ['sustain', 'hold', 'pedal'],
      roles: ['hold', 'grain'],
      traits: ['clean'],
    },
    'Slow dissolve': {
      says: 'a wide, darkened wash in which every note slowly dissolves',
      brief: 'a slowly dissolving wash',
      nouns: ['wash', 'dissolve', 'mist'],
      roles: ['grain', 'hold'],
      traits: ['wide', 'heavy', 'long', 'dark', 'far'],
    },
    'Glass halo': {
      says: 'a short bright haze with an octave above everything',
      brief: 'a bright octave-up haze',
      nouns: ['halo', 'glass', 'haze'],
      roles: ['grain', 'pitch', 'halo'],
      traits: ['bright', 'high', 'cold'],
    },
    'Dark water': {
      says: 'a dark, bassy wash that hangs under the notes for seconds',
      brief: 'a dark, bassy wash',
      nouns: ['water', 'depths', 'wash'],
      roles: ['grain', 'hold'],
      traits: ['dark', 'warm', 'wide'],
    },
    Whisper: {
      says: 'a wide whisper of the sound with its attacks dissolved',
      brief: 'a wide, breathy whisper',
      nouns: ['whisper', 'breath', 'air'],
      roles: ['grain', 'width'],
      traits: ['wide', 'heavy', 'bright', 'short', 'far'],
    },
    Endless: {
      says: 'a very wide wash in which every note hangs for many seconds',
      brief: 'a long-hanging wide wash',
      nouns: ['wash', 'horizon', 'mist'],
      roles: ['hold', 'grain'],
      traits: ['long', 'wide', 'heavy', 'far', 'slow'],
    },
    'Faint haze': {
      says: 'a faint haze just behind the dry sound',
      brief: 'a faint haze',
      nouns: ['haze', 'veil', 'gauze'],
      roles: ['grain'],
      traits: ['faint', 'short'],
    },
    'Softened attacks': {
      says: 'the sound with its attacks blurred soft and nothing added',
      brief: 'softly blurred attacks',
      nouns: ['blur', 'felt'],
      roles: ['grain'],
      traits: ['faint'],
    },
    'Diffuse room': {
      says: 'a short diffuse haze around the sound, like a small room',
      brief: 'a short, room-like haze',
      nouns: ['room', 'haze', 'air'],
      roles: ['room', 'grain'],
      traits: ['short'],
    },
    'Long clean hold': {
      says: 'a quiet, unsmeared sustain that holds each note for seconds',
      brief: 'a long clean sustain',
      nouns: ['hold', 'sustain', 'pedal'],
      roles: ['hold'],
      traits: ['clean'],
    },
    'Band of fog': {
      says: 'a wide fog kept to the middle band, hanging for seconds',
      brief: 'a wide mid-band fog',
      nouns: ['fog', 'band', 'mist'],
      roles: ['grain', 'hold'],
      traits: ['wide'],
    },
    'Sub bed': {
      says: 'a low blurred bed under the sound, nothing above the bass',
      brief: 'a low blurred bed',
      nouns: ['bed', 'depths', 'rumble'],
      roles: ['hold', 'grain'],
      traits: ['dark', 'warm', 'wide'],
    },
    'High air': {
      says: 'a thin, bright haze that hangs high above the sound',
      brief: 'a thin haze of high air',
      nouns: ['air', 'haze', 'breath'],
      roles: ['grain', 'halo'],
      traits: ['bright', 'cold', 'high'],
    },
    'Bright octave cloud': {
      says: 'a bright blurred cloud an octave above everything played',
      brief: 'a bright octave-up cloud',
      nouns: ['cloud', 'shimmer', 'glare'],
      roles: ['grain', 'pitch', 'halo'],
      traits: ['bright', 'high', 'wide', 'cold'],
    },
    'Pad from anything': {
      says: 'a wide pad made of the sound with its attacks dissolved',
      brief: 'a wide pad with no attacks',
      nouns: ['pad', 'wash', 'cloud'],
      roles: ['hold', 'swell', 'grain'],
      traits: ['heavy', 'far', 'wide', 'bright'],
    },
  },
}
