import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'spectral-drifter',
  jitter: ['decay'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    Bloom: {
      says: 'faint reversed grains that slide up towards the octave',
      brief: 'faint rising grains',
      nouns: ['grains', 'drift', 'bloom'],
      roles: ['grain', 'pitch'],
      traits: ['faint', 'backwards', 'unsteady', 'high'],
    },
    Shimmer: {
      says: 'faint reversed grains that climb quickly towards the octave',
      brief: 'faint climbing grains',
      nouns: ['shimmer', 'grains', 'glint'],
      roles: ['pitch', 'grain'],
      traits: ['faint', 'backwards', 'unsteady', 'high'],
    },
    'Winter drift': {
      says: 'faint dark grains in reverse that sag in pitch as notes ring',
      brief: 'faint dark sagging grains',
      nouns: ['drift', 'grains', 'frost'],
      roles: ['grain', 'pitch'],
      traits: ['faint', 'backwards', 'dark', 'low', 'unsteady', 'strange'],
    },
    Scatter: {
      says: 'faint reversed grains that drift apart both up and down',
      brief: 'faint scattering grains',
      nouns: ['grains', 'drift'],
      roles: ['grain', 'pitch'],
      traits: ['faint', 'backwards', 'unsteady', 'strange'],
    },
    'Octave halo': {
      says: 'a faint layer of reversed grains an octave above the sound',
      brief: 'faint grains an octave up',
      nouns: ['halo', 'octave', 'grains'],
      roles: ['pitch', 'grain'],
      traits: ['faint', 'backwards', 'high'],
    },
    'Sub octave': {
      says: 'a faint layer of reversed grains an octave below the sound',
      brief: 'faint grains an octave down',
      nouns: ['octave', 'grains', 'shadow'],
      roles: ['pitch', 'grain'],
      traits: ['faint', 'backwards', 'low', 'dark'],
    },
    'Fifth above': {
      says: 'a faint layer of reversed grains a fifth above the sound',
      brief: 'faint grains a fifth up',
      nouns: ['fifths', 'grains', 'halo'],
      roles: ['pitch', 'grain'],
      traits: ['faint', 'backwards', 'high'],
    },
    'Organ stack': {
      says: 'faint reversed grains stacked a fifth and an octave up',
      brief: 'faint grains above the notes',
      nouns: ['stack', 'harmony', 'grains'],
      roles: ['pitch', 'grain'],
      traits: ['faint', 'backwards', 'high'],
    },
    'Octaves both ways': {
      says: 'faint reversed grains an octave above and an octave below',
      brief: 'faint grains in two octaves',
      nouns: ['octaves', 'grains', 'span'],
      roles: ['pitch', 'grain'],
      traits: ['faint', 'backwards', 'high', 'low'],
    },
    'Detune cloud': {
      says: 'a faint cloud of reversed grains slightly sharp and flat',
      brief: 'a faint detuned grain cloud',
      nouns: ['cloud', 'grains', 'haze'],
      roles: ['grain'],
      traits: ['faint', 'backwards'],
    },
    'Reversed smear': {
      says: 'a faint smear of reversed grains at the played pitch',
      brief: 'a smear of reversed grains',
      nouns: ['blur', 'grains', 'haze'],
      roles: ['grain'],
      traits: ['faint', 'backwards'],
    },
    'Rising glide': {
      says: 'faint reversed grains that glide up an octave within seconds',
      brief: 'faint upward-gliding grains',
      nouns: ['grains', 'glide'],
      roles: ['pitch', 'grain'],
      traits: ['faint', 'backwards', 'unsteady', 'high'],
    },
    'Slow climb': {
      says: 'faint reversed grains that creep upwards over a minute or so',
      brief: 'faint slow-climbing grains',
      nouns: ['drift', 'grains'],
      roles: ['grain', 'pitch'],
      traits: ['faint', 'backwards', 'slow', 'unsteady', 'high'],
    },
    Splintered: {
      says: 'faint reversed grains splintered to out-of-tune pitches',
      brief: 'faint out-of-tune splinters',
      nouns: ['grains', 'drift'],
      roles: ['grain', 'pitch'],
      traits: ['faint', 'backwards', 'strange'],
    },
  },
}
