import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'spring-reverb',
  jitter: ['decay', 'predelay'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    'Two spring tank': {
      says: 'a two-spring tank with a little chirp and drip',
      brief: 'a two-spring tank',
      nouns: ['springs'],
      roles: ['room'],
      traits: ['wide'],
    },
    'Surf drip': {
      says: 'two slack springs that splash and drip on every attack',
      brief: 'two splashing springs',
      nouns: ['springs'],
      roles: ['room'],
      traits: ['bright', 'wide'],
    },
    'Dark amp spring': {
      says: 'a single dull spring kept low in the centre of the sound',
      brief: 'a dull single spring',
      nouns: ['spring'],
      roles: ['room'],
      traits: ['faint', 'short', 'dark'],
    },
    'Long three spring': {
      says: 'three long springs that chirp and drip',
      brief: 'three long springs',
      nouns: ['springs'],
      roles: ['hall'],
      traits: [],
    },
    'Slack and strange': {
      says: 'three slack springs where every echo is a long chirp',
      brief: 'three slack chirping springs',
      nouns: ['springs'],
      roles: ['room'],
      traits: ['strange', 'bright', 'wide'],
    },
    'Dub send': {
      says: 'a hard-driven two-spring tank that answers a moment late',
      brief: 'a driven spring tank',
      nouns: ['springs'],
      roles: ['hall'],
      traits: ['wide', 'bright'],
    },
    'Tank alone': {
      says: 'three springs heard alone with none of the dry sound left',
      brief: 'three springs on their own',
      nouns: ['springs'],
      roles: ['hall'],
      traits: ['heavy', 'far', 'wide', 'bright'],
    },
    'Hint of spring': {
      says: 'a hint of a two-spring tank behind the sound',
      brief: 'a hint of spring tank',
      nouns: ['springs'],
      roles: ['room'],
      traits: ['faint', 'short'],
    },
    'Overdriven tank': {
      says: 'a two-spring tank with its input driven into saturation',
      brief: 'an overdriven spring tank',
      nouns: ['springs'],
      roles: ['room'],
      traits: ['bright', 'wide'],
    },
    Underwater: {
      says: 'three long springs with all the top taken off',
      brief: 'three dull, long springs',
      nouns: ['springs'],
      roles: ['hall'],
      traits: ['dark'],
    },
    'Late splash': {
      says: 'a bright spring splash that lands a moment after the note',
      brief: 'a late bright spring splash',
      nouns: ['springs'],
      roles: ['room'],
      traits: ['bright', 'short', 'wide'],
    },
    'Single slack coil': {
      says: 'one slack spring in the centre whose echoes chirp brightly',
      brief: 'one slack chirping spring',
      nouns: ['spring'],
      roles: ['room'],
      traits: ['bright', 'narrow', 'strange'],
    },
    'Tight long tank': {
      says: 'two taut springs that ring long and clean with no drip',
      brief: 'two taut, long springs',
      nouns: ['springs'],
      roles: ['hall'],
      traits: ['wide', 'clean'],
    },
    'Narrow warm tank': {
      says: 'three taut springs kept soft and close to the centre',
      brief: 'a soft, narrow spring tank',
      nouns: ['springs'],
      roles: ['room'],
      traits: ['faint', 'narrow'],
    },
    'Quick twang': {
      says: 'a quick bright twang of springs behind each attack',
      brief: 'a quick spring twang',
      nouns: ['twang', 'springs'],
      roles: ['room'],
      traits: ['bright', 'short'],
    },
    'Dark late coil': {
      says: 'one taut dull spring that answers late and rings long',
      brief: 'one dull, late spring',
      nouns: ['spring'],
      roles: ['room'],
      traits: ['dark', 'narrow'],
    },
  },
}
