import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'stereo-detune',
  jitter: ['delay'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    Classic: {
      says: 'a sharp copy on the left and a flat one on the right',
      brief: 'a detuned copy either side',
      nouns: ['double', 'pair'],
      roles: ['width'],
      traits: ['faint', 'clean'],
    },
    'Soft halo': {
      says: 'two dull copies a few cents off, tucked behind the sound',
      brief: 'two soft detuned copies',
      nouns: ['double', 'halo'],
      roles: ['width'],
      traits: ['faint', 'clean'],
    },
    Doubled: {
      says: 'a second take either side, a little late and out of tune',
      brief: 'a doubled take either side',
      nouns: ['double', 'takes'],
      roles: ['width'],
      traits: ['faint'],
    },
    'Piano haze': {
      says: 'two dull copies that wander in a haze round the notes',
      brief: 'a dull detuned haze',
      nouns: ['haze', 'double'],
      roles: ['width'],
      traits: ['dark', 'faint'],
    },
    Wider: {
      says: 'a sharp copy and a flat one, full-range, wide to either side',
      brief: 'two wide detuned copies',
      nouns: ['double'],
      roles: ['width'],
      traits: ['wide'],
    },
    Spiral: {
      says: 'repeats that rise in pitch on the left and sink on the right',
      brief: 'spiralling detuned repeats',
      nouns: ['spiral', 'double'],
      roles: ['width'],
      traits: ['dark', 'unsteady'],
    },
    Cloud: {
      says: 'two copies that repeat into a blur round the upper notes',
      brief: 'a small detuned blur',
      nouns: ['blur', 'double'],
      roles: ['width'],
      traits: ['faint'],
    },
    Seasick: {
      says: 'two copies far out of tune that sway like a worn tape',
      brief: 'two sour swaying copies',
      nouns: ['sway', 'wobble', 'double'],
      roles: ['width', 'motion'],
      traits: ['unsteady', 'worn', 'wide', 'strange'],
    },
    Thickener: {
      says: 'a sharp and a flat copy kept in the centre, thick not wide',
      brief: 'two detuned centre copies',
      nouns: ['double', 'layer'],
      roles: ['width'],
      traits: ['faint', 'clean'],
    },
    'Faint width': {
      says: 'a trace of dull detuned copies at the edges',
      brief: 'a trace of detuned width',
      nouns: ['trace', 'double'],
      roles: ['width'],
      traits: ['faint', 'dark'],
    },
    'Top only': {
      says: 'a sharp and a flat copy of the highs only, to either side',
      brief: 'detuned copies of the highs',
      nouns: ['double'],
      roles: ['width'],
      traits: ['faint'],
    },
    Shadow: {
      says: 'two dark late copies that shadow the sound on either side',
      brief: 'two dark late copies',
      nouns: ['shadow', 'double'],
      roles: ['width'],
      traits: ['dark', 'wide'],
    },
    'Late copy': {
      says: 'two copies heard just after the sound, the left one first',
      brief: 'two copies a moment late',
      nouns: ['double', 'copy'],
      roles: ['width'],
      traits: [],
    },
    Drifting: {
      says: 'two copies in tune that wander like extra takes',
      brief: 'two wandering extra takes',
      nouns: ['takes', 'drift', 'double'],
      roles: ['width', 'motion'],
      traits: ['unsteady', 'wide'],
    },
    Melting: {
      says: 'dark repeats that slide further out of tune on every pass',
      brief: 'dark repeats going off pitch',
      nouns: ['spiral', 'blur'],
      roles: ['width'],
      traits: ['strange', 'dark', 'unsteady'],
    },
    'Wet only': {
      says: 'a sharp copy hard left and a flat one hard right, alone',
      brief: 'detuned copies heard alone',
      nouns: ['pair', 'double'],
      roles: ['width'],
      traits: ['wide'],
    },
  },
}
