import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'stereo-detune',
  jitter: ['delay'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    Classic: {
      says: 'a sharp copy on the left and a flat one on the right',
      brief: 'a detuned copy either side',
      nouns: ['double', 'pair'],
      roles: ['width'],
      traits: ['faint', 'clean'],
    },
    'Soft halo': {
      says: 'two duller copies a few cents off, tucked behind the sound',
      brief: 'two soft detuned copies',
      nouns: ['double', 'veil'],
      roles: ['width'],
      traits: ['faint', 'clean'],
    },
    Doubled: {
      says: 'a second take either side, a little late and out of tune',
      brief: 'a doubled take either side',
      nouns: ['double', 'takes'],
      roles: ['width'],
      traits: ['faint'],
    },
    'Piano haze': {
      says: 'two dull copies that wander, a haze round the notes',
      brief: 'a dull detuned haze',
      nouns: ['haze', 'double'],
      roles: ['width'],
      traits: ['dark', 'faint'],
    },
    Wider: {
      says: 'two full-range copies tuned further apart, reaching lower',
      brief: 'two wider detuned copies',
      nouns: ['width', 'double'],
      roles: ['width'],
      traits: ['wide'],
    },
    Spiral: {
      says: 'fed-back copies that climb on the left and sink on the right',
      brief: 'spiralling detuned repeats',
      nouns: ['spiral', 'double'],
      roles: ['width'],
      traits: ['dark', 'unsteady'],
    },
    Cloud: {
      says: 'two copies fed back into a small blur round the upper notes',
      brief: 'a small detuned blur',
      nouns: ['blur', 'double'],
      roles: ['width'],
      traits: ['faint'],
    },
    Seasick: {
      says: 'two copies far out of tune that sway like a worn tape',
      brief: 'two sour swaying copies',
      nouns: ['sway', 'wobble', 'double'],
      roles: ['width', 'wear'],
      traits: ['unsteady', 'worn', 'wide', 'strange'],
    },
    Thickener: {
      says: 'a sharp and a flat copy kept in the centre, thick not wide',
      brief: 'two detuned centre copies',
      nouns: ['double', 'layer'],
      roles: ['width'],
      traits: ['faint', 'clean'],
    },
    'Faint width': {
      says: 'a trace of dull detuned copies at the edges',
      brief: 'a trace of detuned width',
      nouns: ['width', 'trace'],
      roles: ['width'],
      traits: ['faint', 'dark'],
    },
    'Top only': {
      says: 'detuned copies of the highs only, the body left as it was',
      brief: 'detuned copies of the highs',
      nouns: ['air', 'double'],
      roles: ['width'],
      traits: ['faint'],
    },
    Shadow: {
      says: 'two dark late copies, a shadow either side of the sound',
      brief: 'two dark late copies',
      nouns: ['shadow', 'double'],
      roles: ['width'],
      traits: ['dark', 'wide'],
    },
    'Late copy': {
      says: 'two copies a slap behind, the left one first',
      brief: 'two slapped-back copies',
      nouns: ['slap', 'double', 'copy'],
      roles: ['width'],
      traits: [],
    },
    Drifting: {
      says: 'two copies in tune that wander like extra takes',
      brief: 'two wandering extra takes',
      nouns: ['takes', 'drift', 'double'],
      roles: ['width', 'motion'],
      traits: ['unsteady', 'wide'],
    },
    Melting: {
      says: 'dark repeats that slide further out of tune on every pass',
      brief: 'dark repeats going off pitch',
      nouns: ['smear', 'slide'],
      roles: ['width'],
      traits: ['strange', 'dark', 'unsteady'],
    },
    'Wet only': {
      says: 'only the two detuned copies, hard left and right',
      brief: 'the detuned copies alone',
      nouns: ['pair', 'double'],
      roles: ['width'],
      traits: ['wide'],
    },
  },
}
