import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'sustainer',
  // Not `decay`: at its top it never fades, and three voices say so.
  jitter: ['attack', 'glide'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    'Sustain pedal': {
      says: 'a held pad caught from each chord that glides to the next',
      brief: 'a pad held from each chord',
      nouns: ['pad'],
      roles: ['hold'],
      traits: ['clean'],
    },
    'Slow strings': {
      says: 'a held pad that swells in slowly like bowed strings',
      brief: 'a slow bowed-string pad',
      nouns: ['pad', 'strings'],
      roles: ['hold'],
      traits: ['slow', 'long'],
    },
    'Stacked harmony': {
      says: 'a held pad where each new chord piles onto the last',
      brief: 'a pad of piled-up chords',
      nouns: ['harmony', 'pad'],
      roles: ['hold'],
      traits: ['long'],
    },
    'Frozen moment': {
      says: 'a moment caught and frozen when its switch is pressed',
      brief: 'a moment frozen by a switch',
      nouns: ['freeze', 'moment'],
      roles: [],
      traits: ['frozen'],
      skip: 'It catches nothing until Hold is switched on by hand: left alone it only turns the dry sound down.',
    },
    'Glass organ': {
      says: 'a still, bright held tone like an organ that never fades',
      brief: 'an unfading organ-like tone',
      nouns: ['organ', 'drone', 'pipes'],
      roles: ['hold'],
      traits: ['frozen', 'long', 'bright', 'cold', 'narrow'],
    },
    'Dark bed': {
      says: 'a dark, round pad that melts slowly from chord to chord',
      brief: 'a dark, slow-melting pad',
      nouns: ['pad', 'drone'],
      roles: ['hold'],
      traits: ['dark', 'long', 'slow', 'warm'],
    },
    'Quick catch': {
      says: 'a held tone that takes over each note at once and soon fades',
      brief: 'a held tone that soon fades',
      nouns: ['pad', 'glow'],
      roles: ['hold'],
      traits: ['fast'],
    },
    'Long glide': {
      says: 'a held pad that takes seconds to melt into each new chord',
      brief: 'a pad that glides slowly',
      nouns: ['pad', 'glide'],
      roles: ['hold'],
      traits: ['slow', 'long'],
    },
    'Shimmer cloud': {
      says: 'a wide cloud of piled-up chords whose overtones all drift',
      brief: 'a wide drifting chord cloud',
      nouns: ['cloud', 'shimmer'],
      roles: ['hold', 'motion'],
      traits: ['wide', 'long', 'heavy', 'unsteady', 'bright'],
    },
    'Endless drone': {
      says: 'a slow drone that swells from the playing and never fades',
      brief: 'an unfading slow drone',
      nouns: ['drone', 'pad'],
      roles: ['hold'],
      traits: ['frozen', 'long', 'slow', 'heavy', 'wide'],
    },
    'Held sound alone': {
      says: 'a held pad that stands alone in place of what was played',
      brief: 'a held pad by itself',
      nouns: ['pad'],
      roles: ['hold', 'swell'],
      traits: ['heavy', 'far'],
    },
    'Thin halo': {
      says: 'a thin held pad with no lows that swells in behind the notes',
      brief: 'a thin halo of held sound',
      nouns: ['halo', 'trace', 'glow'],
      roles: ['hold'],
      traits: ['cold', 'bright', 'slow'],
    },
    'Brief afterglow': {
      says: 'a short glow of held tone that dies just after each note',
      brief: 'a short glow after each note',
      nouns: ['afterglow', 'glow', 'trace'],
      roles: ['hold'],
      traits: ['short'],
    },
    'Wavering choir': {
      says: 'a held pad whose every overtone wavers in pitch and level',
      brief: 'a wavering held pad',
      nouns: ['pad', 'drift'],
      roles: ['hold', 'motion'],
      traits: ['unsteady'],
    },
    'High frost': {
      says: 'a thin, bright held pad with everything low taken out',
      brief: 'a thin, bright held pad',
      nouns: ['frost', 'halo', 'pad'],
      roles: ['hold'],
      traits: ['bright', 'cold', 'long', 'slow'],
    },
    'Slow bloom layers': {
      says: 'layers of held chords that bloom slowly and never fade',
      brief: 'slow unfading chord layers',
      nouns: ['bloom', 'drone'],
      roles: ['hold'],
      traits: ['frozen', 'long', 'slow', 'heavy'],
    },
  },
}
