import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'swarm-reverb',
  jitter: ['length', 'glide'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    Cavern: {
      says: 'a cavern built from a rush of short echoes',
      brief: 'a cavern of short echoes',
      nouns: ['cavern', 'cave'],
      roles: ['hall'],
      traits: [],
    },
    Pattering: {
      says: 'a quick patter of separate echoes behind each note',
      brief: 'a patter of short echoes',
      nouns: ['patter', 'echoes'],
      roles: ['room'],
      traits: ['short'],
    },
    Endless: {
      says: 'a blurred cave that goes on ringing for minutes',
      brief: 'a cave ringing for minutes',
      nouns: ['cave', 'cavern', 'wash'],
      roles: ['hall', 'hold'],
      traits: ['long', 'heavy'],
    },
    Bending: {
      says: 'a cave whose echoes bend slowly up and down in pitch',
      brief: 'a cave that bends in pitch',
      nouns: ['cave', 'drift'],
      roles: ['hall'],
      traits: ['long', 'unsteady', 'slow'],
    },
    Intervals: {
      says: 'a cave whose echoes jump now and then by a fifth or octave',
      brief: 'a cave that jumps in pitch',
      nouns: ['cave', 'cavern'],
      roles: ['hall'],
      traits: ['long', 'unsteady', 'strange'],
    },
    'Dark well': {
      says: 'a deep dark well of slow blurred echoes',
      brief: 'a deep dark well',
      nouns: ['cave', 'depths'],
      roles: ['hall'],
      traits: ['dark', 'long'],
    },
    'Tight swarm': {
      says: 'a tight cluster of echoes close behind each note',
      brief: 'a tight cluster of echoes',
      nouns: ['cluster', 'room'],
      roles: ['room'],
      traits: ['short'],
    },
    'Slow stretch': {
      says: 'a long blurred cave that slides slowly between intervals',
      brief: 'a cave that slides in pitch',
      nouns: ['cave', 'cavern'],
      roles: ['hall'],
      traits: ['long', 'slow', 'unsteady', 'strange'],
    },
    Runaway: {
      says: 'a cave whose echoes feed on themselves and build',
      brief: 'a self-feeding cave',
      nouns: ['cave'],
      roles: [],
      traits: ['long', 'heavy', 'strange'],
      skip: 'Its feedback is above unity: the cave feeds on itself and grows without end.',
    },
    'Long scatter': {
      says: 'one slow scatter of echoes over about a second and no tail',
      brief: 'one long scatter of echoes',
      nouns: ['echoes', 'patter'],
      roles: ['room'],
      traits: [],
    },
    'Vast hollow': {
      says: 'a vast blurred hollow that rings for half a minute',
      brief: 'a vast blurred hollow',
      nouns: ['cavern', 'hollow', 'void'],
      roles: ['hall'],
      traits: ['long', 'heavy', 'wide'],
    },
    'Metal pipe': {
      says: 'a short pipe that rings like metal on every attack',
      brief: 'a short ringing metal pipe',
      nouns: ['ring', 'culvert'],
      roles: ['room', 'halo'],
      traits: ['short', 'cold'],
    },
    Glinting: {
      says: 'a long thin cave whose single echoes swell and fade',
      brief: 'a long flickering cave',
      nouns: ['glints', 'cave'],
      roles: ['hall'],
      traits: ['long', 'cold', 'bright'],
    },
    'Mine shaft': {
      says: 'a dull mono shaft of echoes that rings for seconds',
      brief: 'a dull mono shaft of echoes',
      nouns: ['tunnel'],
      roles: ['hall'],
      traits: ['narrow', 'dark'],
    },
    'Faint scatter': {
      says: 'a faint scatter of echoes just behind the sound',
      brief: 'a faint scatter of echoes',
      nouns: ['echoes', 'patter'],
      roles: ['room'],
      traits: ['faint', 'short'],
    },
    'Glass rain': {
      says: 'a fine patter of thin high echoes with no bass in them',
      brief: 'a thin patter of high echoes',
      nouns: ['rain', 'patter'],
      roles: ['room'],
      traits: ['faint', 'cold', 'bright'],
    },
  },
}
