import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'swell',
  jitter: ['attack', 'release'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    Bowed: {
      says: 'a swell that fades every note in like a bow stroke',
      brief: 'a bowed swell',
      nouns: ['bow', 'swell', 'strings'],
      roles: ['swell'],
      traits: ['clean'],
    },
    'Slow attack': {
      says: 'a short swell that rounds the front off every note',
      brief: 'a short, rounding swell',
      nouns: ['swell', 'bow'],
      roles: ['swell'],
      traits: ['clean', 'faint'],
    },
    Tide: {
      says: 'a swell that takes seconds to rise after each silence',
      brief: 'a seconds-long swell',
      nouns: ['tide', 'swell'],
      roles: ['swell'],
      traits: ['slow', 'clean'],
    },
    'Soft pick': {
      says: 'a quick fade-in that only softens the edge of each note',
      brief: 'a softened attack',
      nouns: ['swell'],
      roles: ['swell'],
      traits: ['fast', 'clean', 'faint'],
    },
    'Piano to pad': {
      says: 'a swell of about a second that turns struck notes to pads',
      brief: 'a struck-to-pad swell',
      nouns: ['pad', 'swell'],
      roles: ['swell'],
      traits: ['slow', 'clean'],
    },
    Shadow: {
      says: 'a slow swell after each silence, with some dry attack left',
      brief: 'a half-hidden slow swell',
      nouns: ['shadow', 'swell'],
      roles: ['swell'],
      traits: ['slow', 'clean', 'faint'],
    },
    'Loud notes only': {
      says: 'a quick swell that opens for loud notes and mutes the rest',
      brief: 'a swell for loud notes only',
      nouns: ['gate', 'swell'],
      roles: ['swell'],
      traits: ['fast'],
    },
    'Volume pedal': {
      says: 'a swell that stays low and arrives late, like a rocked pedal',
      brief: 'a volume-pedal swell',
      nouns: ['pedal', 'swell'],
      roles: ['swell'],
      traits: ['clean'],
    },
    Backwards: {
      says: 'a swell that arrives late, so notes seem to play in reverse',
      brief: 'a reverse-sounding swell',
      nouns: ['swell', 'rise'],
      roles: ['swell'],
      traits: ['clean', 'backwards'],
    },
    'Ghost pick': {
      says: 'a half-deep swell that leaves a ghost of each attack',
      brief: 'a half-deep swell',
      nouns: ['ghost', 'swell'],
      roles: ['swell'],
      traits: ['clean', 'faint'],
    },
    Glacier: {
      says: 'a swell that takes about four seconds to open after silence',
      brief: 'a very slow swell',
      nouns: ['glacier', 'swell', 'tide'],
      roles: ['swell'],
      traits: ['slow', 'clean'],
    },
    'First note only': {
      says: 'a slow swell on only the first note after each silence',
      brief: 'a first-note swell',
      nouns: ['swell', 'rise'],
      roles: ['swell'],
      traits: ['slow', 'clean', 'faint'],
    },
    'String section': {
      says: "a smooth swell on every note, like a string section's bows",
      brief: 'a string-like swell',
      nouns: ['strings', 'section', 'swell'],
      roles: ['swell'],
      traits: ['clean'],
    },
    'Slow bow': {
      says: 'a longer bowed swell that leans into every note',
      brief: 'a long bowed swell',
      nouns: ['bow', 'swell'],
      roles: ['swell'],
      traits: ['clean'],
    },
    Sunrise: {
      says: 'a slow swell after each silence that opens only at the end',
      brief: 'a late-blooming slow swell',
      nouns: ['sunrise', 'swell', 'rise'],
      roles: ['swell'],
      traits: ['slow', 'clean'],
    },
    'Half bowed': {
      says: 'a bowed swell at half strength under the dry attacks',
      brief: 'a half-strength bowed swell',
      nouns: ['bow', 'swell'],
      roles: ['swell'],
      traits: ['clean', 'faint'],
    },
  },
}
