import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'swell',
  jitter: ['attack', 'release'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    Bowed: {
      says: 'a swell that fades every note in like a bow stroke',
      brief: 'a bowed swell',
      nouns: ['swell'],
      roles: ['swell'],
      traits: ['clean'],
    },
    'Slow attack': {
      says: 'a short swell that rounds the front off every note',
      brief: 'a short, rounding swell',
      nouns: ['swell'],
      roles: ['swell'],
      traits: ['clean'],
    },
    Tide: {
      says: 'a swell that takes seconds to rise after each silence',
      brief: 'a seconds-long swell',
      nouns: ['tide', 'swell'],
      roles: ['swell'],
      traits: ['slow', 'clean'],
    },
    'Soft pick': {
      says: 'a quick fade-in that only softens the edge of each note',
      brief: 'a softened attack',
      nouns: ['swell'],
      roles: ['swell'],
      traits: ['clean', 'faint'],
    },
    'Piano to pad': {
      says: 'a swell of about a second that turns struck notes to pads',
      brief: 'a swell of about a second',
      nouns: ['swell', 'pad'],
      roles: ['swell'],
      traits: ['slow', 'clean'],
    },
    Shadow: {
      says: 'a slow swell after each silence that leaves some attack in',
      brief: 'a half-hidden slow swell',
      nouns: ['swell', 'shadow'],
      roles: ['swell'],
      traits: ['slow', 'clean', 'faint'],
    },
    'Loud notes only': {
      says: 'a gate that opens softly for loud notes and mutes the rest',
      brief: 'a soft-opening gate',
      nouns: ['gate'],
      roles: [],
      traits: ['fast'],
      skip: 'It is a gate, not a swell: it mutes all but the loud notes, a fix for one instrument that fills no slot of a chain.',
    },
    'Volume pedal': {
      says: 'a late swell on every note like a rocked volume pedal',
      brief: 'a volume-pedal swell',
      nouns: ['swell'],
      roles: ['swell'],
      traits: ['clean'],
    },
    Backwards: {
      says: 'a swell so late that notes seem to play in reverse',
      brief: 'a reverse-sounding swell',
      nouns: ['swell'],
      roles: ['swell'],
      traits: ['clean'],
    },
    'Ghost pick': {
      says: 'a shallow swell that leaves a ghost of each attack',
      brief: 'a shallow swell',
      nouns: ['swell'],
      roles: ['swell'],
      traits: ['clean', 'faint'],
    },
    Glacier: {
      says: 'a swell that takes about four seconds to open after silence',
      brief: 'a very slow swell',
      nouns: ['swell', 'tide'],
      roles: ['swell'],
      traits: ['slow', 'clean'],
    },
    'First note only': {
      says: 'a slow swell on only the first note after each silence',
      brief: 'a swell after each silence',
      nouns: ['swell'],
      roles: ['swell'],
      traits: ['slow', 'clean', 'faint'],
    },
    'String section': {
      says: 'a smooth swell that brings every note in like bowed strings',
      brief: 'a string-like swell',
      nouns: ['swell'],
      roles: ['swell'],
      traits: ['clean'],
    },
    'Slow bow': {
      says: 'a long bowed swell that leans slowly into every note',
      brief: 'a long bowed swell',
      nouns: ['swell'],
      roles: ['swell'],
      traits: ['clean'],
    },
    Sunrise: {
      says: 'a slow swell after each silence, opening late in its rise',
      brief: 'a late-blooming slow swell',
      nouns: ['swell'],
      roles: ['swell'],
      traits: ['slow', 'clean'],
    },
    'Half bowed': {
      says: 'a bowed swell that lets part of each attack through',
      brief: 'a partial bowed swell',
      nouns: ['swell'],
      roles: ['swell'],
      traits: ['clean', 'faint'],
    },
  },
}
