import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'sympathetic',
  jitter: ['decay'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    'Piano pedal': {
      says: 'eight strings in C major that ring on as under a held pedal',
      brief: 'eight sympathetic strings',
      nouns: ['strings', 'pedal'],
      roles: ['halo'],
      traits: [],
    },
    'Sitar drone': {
      says: 'thirteen drone strings in D major kept near the centre',
      brief: 'thirteen drone strings',
      nouns: ['drone', 'strings'],
      roles: ['halo'],
      traits: ['narrow'],
    },
    'Minor strings': {
      says: 'twelve strings in A minor that ring with notes in that key',
      brief: 'twelve strings in A minor',
      nouns: ['strings', 'harp'],
      roles: ['halo'],
      traits: [],
    },
    'Open triad': {
      says: 'four strings tuned to a G major chord that ring in sympathy',
      brief: 'four strings on a G chord',
      nouns: ['triad', 'strings', 'chord'],
      roles: ['halo'],
      traits: [],
    },
    'Glass harp': {
      says: 'sixteen hard-driven strings in F major that ring for seconds',
      brief: 'sixteen ringing strings',
      nouns: ['harp', 'strings', 'glass'],
      roles: ['halo'],
      traits: [],
    },
    'Long ring': {
      says: 'sixteen strings in C major that ring for about ten seconds',
      brief: 'sixteen long-ringing strings',
      nouns: ['strings', 'ring', 'harp'],
      roles: ['halo'],
      traits: ['long'],
    },
    'Follow the tune': {
      says: 'ten strings that tune themselves to the notes they hear',
      brief: 'ten self-tuning strings',
      nouns: ['strings', 'harp'],
      roles: ['halo'],
      traits: [],
    },
    'Short halo': {
      says: 'a brief ring of sixteen strings behind each note',
      brief: 'a brief ring of strings',
      nouns: ['halo', 'strings', 'ring'],
      roles: ['halo'],
      traits: ['short', 'faint'],
    },
    'Strings alone': {
      says: 'sixteen strings in E minor heard alone with no dry sound',
      brief: 'strings with no dry sound',
      nouns: ['strings', 'harp'],
      roles: ['halo'],
      traits: ['heavy', 'far', 'wide', 'long'],
    },
    'Faint ring': {
      says: 'a faint ring of six strings in A major',
      brief: 'a faint ring of strings',
      nouns: ['ring', 'strings'],
      roles: ['halo'],
      traits: ['faint'],
    },
    'Centre drone': {
      says: 'four long strings on an A minor chord held in the centre',
      brief: 'four centred drone strings',
      nouns: ['drone', 'strings'],
      roles: ['halo'],
      traits: ['narrow', 'long'],
    },
    'Minor wash': {
      says: 'a wide wash of sixteen long strings in D minor',
      brief: 'a wide wash of strings',
      nouns: ['wash', 'strings'],
      roles: ['halo'],
      traits: ['long', 'wide'],
    },
    'Learn and hold': {
      says: 'sixteen strings that learn the tune and ring on long',
      brief: 'sixteen self-tuning strings',
      nouns: ['strings', 'harp', 'memory'],
      roles: ['halo'],
      traits: ['long', 'wide'],
    },
    'Brief pluck': {
      says: 'five strings in F major that ring for about half a second',
      brief: 'five briefly ringing strings',
      nouns: ['pluck', 'strings'],
      roles: ['halo'],
      traits: ['short', 'faint'],
    },
    Hammered: {
      says: 'nine hard-driven strings in E minor that soon fall silent',
      brief: 'nine hard-driven strings',
      nouns: ['strings', 'dulcimer'],
      roles: ['halo'],
      traits: ['short'],
    },
    'Echo the tune': {
      says: 'four strings that retune to what is played and ring briefly',
      brief: 'four self-tuning strings',
      nouns: ['strings', 'trace'],
      roles: ['halo'],
      traits: ['faint', 'short', 'narrow'],
    },
  },
}
