import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'tape-loop',
  jitter: ['length'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    'Slow fade': {
      says: 'a short tape loop where each pass comes back quieter',
      brief: 'a fading tape loop',
      nouns: ['loop', 'reel'],
      roles: ['loop'],
      traits: ['warm', 'long'],
    },
    'Two decks': {
      says: 'about four seconds of tape between two decks, piling up',
      brief: 'tape between two decks',
      nouns: ['decks', 'loop', 'layers'],
      roles: ['loop'],
      traits: ['long', 'warm'],
    },
    'Long horizon': {
      says: 'a tape loop about thirteen seconds round',
      brief: 'a very long tape loop',
      nouns: ['horizon', 'loop'],
      roles: [],
      traits: ['long', 'slow'],
      skip: 'Its first pass comes back after thirteen seconds: a ten-second audition hears nothing of it.',
    },
    'Slowed down': {
      says: 'a tape loop at half speed, an octave down and darker',
      brief: 'a half-speed tape loop',
      nouns: ['loop', 'reel'],
      roles: ['loop', 'pitch'],
      traits: ['dark', 'low', 'slow', 'long'],
    },
    'Backwards layers': {
      says: 'a tape loop that plays its layers back in reverse',
      brief: 'a backwards tape loop',
      nouns: ['loop', 'layers'],
      roles: ['loop'],
      traits: ['backwards', 'long'],
    },
    'Worn out': {
      says: 'a tape loop that wears thinner and duller on every pass',
      brief: 'a wearing tape loop',
      nouns: ['loop', 'reel', 'oxide'],
      roles: ['loop', 'wear'],
      traits: ['worn', 'dark', 'unsteady', 'long'],
    },
    'Endless hold': {
      says: 'a tape loop that never fades, holding every layer',
      brief: 'an unfading tape loop',
      nouns: ['loop', 'hold'],
      roles: ['loop', 'hold'],
      traits: ['frozen', 'long', 'heavy'],
    },
    'One second round': {
      says: 'a one-second tape loop that soon dies away',
      brief: 'a one-second tape loop',
      nouns: ['loop', 'round'],
      roles: ['loop', 'echo'],
      traits: ['short'],
    },
    'Octave up ghosts': {
      says: 'a double-speed tape loop, an octave up and thin',
      brief: 'an octave-up tape loop',
      nouns: ['ghosts', 'loop'],
      roles: ['loop', 'pitch'],
      traits: ['high', 'bright', 'fast'],
    },
    'Slow backwards': {
      says: 'a half-speed tape loop in reverse, low and dark',
      brief: 'a slow backwards loop',
      nouns: ['loop', 'reel'],
      roles: ['loop', 'pitch'],
      traits: ['backwards', 'low', 'dark', 'slow', 'long'],
    },
    'Fast backwards': {
      says: 'a double-speed tape loop in reverse, an octave up',
      brief: 'a fast backwards loop',
      nouns: ['loop', 'ghosts'],
      roles: ['loop', 'pitch'],
      traits: ['backwards', 'high', 'fast', 'strange'],
    },
    'Clean layers': {
      says: 'a clean tape loop that piles up layers without wear',
      brief: 'a clean tape loop',
      nouns: ['layers', 'loop'],
      roles: ['loop'],
      traits: ['clean', 'long'],
    },
    'Crossing sides': {
      says: 'a tape loop whose passes cross from side to side',
      brief: 'a side-to-side tape loop',
      nouns: ['loop', 'sides'],
      roles: ['loop'],
      traits: ['wide', 'long'],
    },
    'Thin and distant': {
      says: 'a thin, far-off tape loop with its lows cut away',
      brief: 'a thin far-off loop',
      nouns: ['loop', 'reel'],
      roles: ['loop'],
      traits: ['far', 'cold', 'faint'],
    },
    'Faint afterimage': {
      says: 'a tape loop kept low, an afterimage behind the playing',
      brief: 'a faint tape loop',
      nouns: ['loop', 'trace'],
      roles: ['loop'],
      traits: ['faint'],
    },
    'Dark dissolve': {
      says: 'a long dark tape loop whose layers slowly dissolve',
      brief: 'a dark dissolving loop',
      nouns: ['loop', 'reel'],
      roles: ['loop', 'wear'],
      traits: ['dark', 'worn', 'long', 'slow'],
    },
  },
}
