import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'tape',
  jitter: [],
  trim: [
    { param: 'output', kind: 'db' },
    { param: 'mix', kind: 'mix' },
  ],
  voices: {
    'Quarter inch': {
      says: 'a reel of tape at middle speed, with a little drift and hiss',
      brief: 'a reel of tape',
      nouns: ['reel', 'tape'],
      roles: ['wear'],
      traits: ['warm', 'faint'],
    },
    'Mastering deck': {
      says: 'a fast, steady reel pushed into soft saturation',
      brief: 'a fast steady reel',
      nouns: ['deck', 'reel'],
      roles: ['drive', 'wear'],
      traits: ['clean', 'warm', 'faint'],
    },
    'Cassette four-track': {
      says: 'a four-track cassette, dull on top, unsteady and hissing',
      brief: 'a four-track cassette',
      nouns: ['cassette', 'tape'],
      roles: ['wear'],
      traits: ['worn', 'warm', 'dark', 'unsteady', 'noisy'],
    },
    'Worn thin': {
      says: 'an old slow reel that drifts, dulls and drops out',
      brief: 'an old reel dropping out',
      nouns: ['reel', 'oxide', 'tape'],
      roles: ['wear'],
      traits: ['worn', 'dark', 'unsteady', 'noisy'],
    },
    'Hot glue': {
      says: 'a fast reel with no hiss, driven hard so peaks are squashed',
      brief: 'a reel driven hot',
      nouns: ['tape', 'reel'],
      roles: ['drive', 'glue'],
      traits: ['clean', 'warm', 'faint'],
    },
    Seasick: {
      says: 'a slow reel whose pitch sways widely and never settles',
      brief: 'a slow reel that sways',
      nouns: ['drift', 'reel', 'sway'],
      roles: ['wear', 'motion'],
      traits: ['unsteady', 'slow', 'worn'],
    },
    'Old dictation': {
      says: 'a worn dictation cassette, dull, trembling and full of hiss',
      brief: 'a worn dictation cassette',
      nouns: ['cassette', 'memo', 'tape'],
      roles: ['wear'],
      traits: ['worn', 'dark', 'unsteady', 'noisy'],
    },
    'Clean transfer': {
      says: 'a clean pass over fast new tape, with nothing added',
      brief: 'a clean pass over tape',
      nouns: ['tape', 'reel'],
      roles: ['wear'],
      traits: ['clean', 'faint'],
    },
    'Warm thump': {
      says: 'a cassette with a full head bump and a rolled-off top',
      brief: 'a thick, soft cassette',
      nouns: ['cassette', 'thump', 'tape'],
      roles: ['wear', 'drive'],
      traits: ['warm', 'dark', 'faint'],
    },
    'Under a blanket': {
      says: 'a muffled cassette, its top rolled off and its lows lifted',
      brief: 'a muffled cassette',
      nouns: ['cassette', 'blanket', 'tape'],
      roles: ['wear'],
      traits: ['dark', 'warm', 'worn', 'faint'],
    },
    'Needles pinned': {
      says: 'a reel driven as hard as it goes, thick with harmonics',
      brief: 'an overdriven reel',
      nouns: ['reel', 'needles', 'tape'],
      roles: ['drive', 'wear'],
      traits: ['warm'],
    },
    'Drifting chorus': {
      says: 'a drifting reel laid half against the dry sound, a chorus',
      brief: 'a slow tape chorus',
      nouns: ['chorus', 'drift', 'reel'],
      roles: ['motion', 'wear'],
      traits: ['slow', 'unsteady', 'faint'],
    },
    'Flutter shimmer': {
      says: 'a slow reel that trembles fast, mixed against the dry sound',
      brief: 'a trembling reel',
      nouns: ['flutter', 'reel', 'tremor'],
      roles: ['wear', 'motion'],
      traits: ['unsteady', 'fast', 'faint'],
    },
    'Hiss and air': {
      says: 'a clean bright reel under a thick layer of tape hiss',
      brief: 'a reel thick with hiss',
      nouns: ['hiss', 'air', 'reel'],
      roles: ['hiss', 'wear'],
      traits: ['noisy', 'bright'],
    },
    'Crumbling oxide': {
      says: 'a flaking reel whose sound ducks and dulls at random',
      brief: 'a flaking reel',
      nouns: ['oxide', 'reel', 'flakes'],
      roles: ['wear'],
      traits: ['worn', 'unsteady'],
    },
    'Chewed cassette': {
      says: 'a mangled cassette that lurches, trembles and drops out',
      brief: 'a mangled cassette',
      nouns: ['cassette', 'tangle', 'tape'],
      roles: ['wear'],
      traits: ['worn', 'unsteady', 'noisy', 'strange'],
    },
  },
}
