import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'tape-echo',
  jitter: ['time'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    'Warm repeats': {
      says: 'a tape echo whose warm repeats soften as they fade',
      brief: 'a warm tape echo',
      nouns: ['echo', 'repeats'],
      roles: ['echo'],
      traits: ['warm'],
    },
    'Short and soft': {
      says: 'a short, soft tape echo close behind the playing',
      brief: 'a short soft tape echo',
      nouns: ['echo', 'slap'],
      roles: ['echo', 'room'],
      traits: ['short', 'warm'],
    },
    'Three heads': {
      says: 'three tape heads in a row, a cluster on every repeat',
      brief: 'a three-head tape echo',
      nouns: ['heads', 'echo'],
      roles: ['echo'],
      traits: ['warm'],
    },
    'Worn tape': {
      says: 'a dull, wobbling, saturated echo on worn tape',
      brief: 'a worn tape echo',
      nouns: ['echo', 'reel', 'oxide'],
      roles: ['echo', 'wear'],
      traits: ['worn', 'dark', 'unsteady', 'warm'],
    },
    'Dub wash': {
      says: 'dotted tape repeats that pile up in a darkening wash',
      brief: 'a dotted tape echo wash',
      nouns: ['wash', 'echo'],
      roles: ['echo'],
      traits: ['long', 'dark', 'warm'],
    },
    Runaway: {
      says: 'a tape echo fed back until it saturates and will not stop',
      brief: 'a runaway tape echo',
      nouns: ['drone', 'echo'],
      roles: [],
      traits: ['long', 'heavy'],
      skip: 'Its feedback is above one, so the repeats never die away: half a minute on it is still near its loudest.',
    },
    'Single slap': {
      says: 'a single saturated tape slap behind each note',
      brief: 'a single tape slap',
      nouns: ['slap'],
      roles: ['room', 'echo'],
      traits: ['short', 'faint', 'warm'],
    },
    'Wobbly double': {
      says: 'a wobbling tape double a moment behind each note',
      brief: 'a wobbling tape double',
      nouns: ['double', 'wobble'],
      roles: ['width'],
      traits: ['unsteady', 'short'],
    },
    'Clean and steady': {
      says: 'a steady tape echo with no wobble, dirt or dulling',
      brief: 'a clean steady tape echo',
      nouns: ['echo', 'repeats'],
      roles: ['echo'],
      traits: ['clean'],
    },
    'Dotted bounce': {
      says: 'dotted tape repeats that bounce from side to side',
      brief: 'a bouncing dotted tape echo',
      nouns: ['bounce', 'echo'],
      roles: ['echo'],
      traits: ['warm'],
    },
    'Long dark trail': {
      says: 'a slow tape echo with a long trail that dulls as it goes',
      brief: 'a long dark tape trail',
      nouns: ['trail', 'echo'],
      roles: ['echo'],
      traits: ['long', 'dark', 'slow'],
    },
    'Thin and fading': {
      says: 'tape repeats that lose their lows and thin out as they fade',
      brief: 'a thinning tape echo',
      nouns: ['echo', 'repeats'],
      roles: ['echo'],
      traits: ['cold'],
    },
    'Faint trace': {
      says: 'a faint trace of tape echo behind the playing',
      brief: 'a faint tape echo',
      nouns: ['trace', 'echo'],
      roles: ['echo'],
      traits: ['faint', 'warm'],
    },
    'Two head gallop': {
      says: 'two tape heads that make every repeat gallop',
      brief: 'a galloping tape echo',
      nouns: ['gallop', 'heads', 'echo'],
      roles: ['echo'],
      traits: ['warm'],
    },
    'Hovering wash': {
      says: 'a wash of three fed-back tape heads that hovers and fades',
      brief: 'a hovering tape wash',
      nouns: ['wash', 'haze'],
      roles: ['echo', 'hall'],
      traits: ['long', 'dark', 'unsteady', 'warm'],
    },
    'Tiny room cluster': {
      says: 'a tight cluster of tape repeats, like a very small room',
      brief: 'a tight tape cluster',
      nouns: ['cluster', 'room'],
      roles: ['room'],
      traits: ['short', 'faint'],
    },
  },
}
