import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'tremolo',
  jitter: ['rate'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    'Amp tremolo': {
      says: 'a steady amplifier tremolo, about four pulses a second',
      brief: 'an amplifier tremolo',
      nouns: ['tremolo', 'pulse'],
      roles: ['pulse'],
      traits: ['fast', 'clean'],
    },
    'Harmonic shimmer': {
      says: 'a harmonic tremolo whose lows and highs trade places quickly',
      brief: 'a harmonic tremolo',
      nouns: ['tremolo', 'ripple'],
      roles: ['pulse', 'motion'],
      traits: ['fast'],
    },
    'Slow pan': {
      says: 'a slow pan from side to side, a few seconds each way',
      brief: 'a slow pan from side to side',
      nouns: ['sway'],
      roles: ['motion', 'width'],
      traits: ['slow', 'wide', 'clean'],
    },
    Chopper: {
      says: 'a hard chop to silence about seven times a second',
      brief: 'a hard fast chop',
      nouns: ['tremolo'],
      roles: ['pulse'],
      traits: ['fast', 'strange'],
    },
    'Sea swell': {
      says: 'the level rising and falling at random, like surf',
      brief: 'a random surf-like swell',
      nouns: ['swell', 'tide'],
      roles: ['motion', 'swell'],
      traits: ['slow'],
    },
    'Wide shimmer': {
      says: 'a quick harmonic tremolo with its two sides in opposite step',
      brief: 'a quick harmonic tremolo',
      nouns: ['tremolo', 'flicker'],
      roles: ['pulse'],
      traits: ['fast', 'wide'],
    },
    'Pitch wobble': {
      says: 'a quick shallow vibrato such as a string player makes',
      brief: 'a shallow vibrato',
      nouns: ['vibrato', 'wobble'],
      roles: ['motion', 'pulse'],
      traits: ['fast', 'unsteady', 'faint'],
    },
    'Slow chorus': {
      says: 'a thin chorus of one copy bending against the dry sound',
      brief: 'a thin, simple chorus',
      nouns: ['chorus', 'sway'],
      roles: ['motion', 'width'],
      traits: ['wide'],
    },
    'Gentle breath': {
      says: 'the level breathing in and out about every four seconds',
      brief: 'a slow breathing level',
      nouns: ['swell', 'breath'],
      roles: ['motion', 'swell'],
      traits: ['slow', 'faint', 'clean'],
    },
    'On and off': {
      says: 'a square tremolo that switches the sound hard on and off',
      brief: 'a hard on-and-off tremolo',
      nouns: ['tremolo'],
      roles: ['pulse'],
      traits: ['fast', 'strange'],
    },
    'Fast shudder': {
      says: 'a shudder in the level, too fast to count',
      brief: 'a fast shudder',
      nouns: ['tremolo'],
      roles: ['pulse'],
      traits: ['fast'],
    },
    'Side to side': {
      says: 'a hard pan that jumps from one side to the other',
      brief: 'a hard side-to-side pan',
      nouns: ['pulse'],
      roles: ['pulse', 'width'],
      traits: ['fast', 'wide'],
    },
    'Wandering pan': {
      says: 'a pan that wanders to a new place every second or so',
      brief: 'a wandering pan',
      nouns: ['drift'],
      roles: ['motion', 'width'],
      traits: ['clean'],
    },
    'Tilting tone': {
      says: 'the tone rocking slowly from dark to bright, sides opposed',
      brief: 'a slowly rocking tone',
      nouns: ['sway'],
      roles: ['motion'],
      traits: ['slow', 'wide'],
    },
    'Wide wobble': {
      says: 'a deep pitch wobble with the two sides bending out of step',
      brief: 'a deep wide pitch wobble',
      nouns: ['wobble', 'vibrato'],
      roles: ['pulse', 'width'],
      traits: ['wide', 'unsteady', 'fast'],
    },
    'Drifting comb': {
      says: 'a slow flanger-like sweep, opposite on each side',
      brief: 'a slow flanger-like sweep',
      nouns: ['drift'],
      roles: ['motion'],
      traits: ['slow', 'wide'],
    },
  },
}
