import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'vintage-digital',
  jitter: [],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    Sampler: {
      says: 'the converters of an early sampler, twelve bits, low rate',
      brief: 'early sampler converters',
      nouns: ['sampler', 'bits'],
      roles: ['wear'],
      traits: ['cold', 'faint'],
    },
    Glaze: {
      says: 'a thin twelve-bit glaze from converters at a moderate rate',
      brief: 'a thin twelve-bit glaze',
      nouns: ['glaze', 'bits'],
      roles: ['wear'],
      traits: ['cold', 'faint'],
    },
    Toy: {
      says: 'eight-bit companded converters with false tones folded in',
      brief: 'toy eight-bit converters',
      nouns: ['toy', 'bits'],
      roles: ['wear'],
      traits: ['cold', 'worn', 'faint'],
    },
    Dusty: {
      says: 'ten-bit converters on a shaky clock, dull, with riding hiss',
      brief: 'dull, shaky converters',
      nouns: ['dust', 'sampler', 'bits'],
      roles: ['wear'],
      traits: ['dark', 'worn', 'faint'],
    },
    Glassy: {
      says: 'old converters with no output filter, a glassy ring on top',
      brief: 'unfiltered old converters',
      nouns: ['glass', 'sampler'],
      roles: ['wear'],
      traits: ['bright', 'cold', 'faint'],
    },
    Metallic: {
      says: 'low-rate converters that fold the highs down as false tones',
      brief: 'folding low-rate converters',
      nouns: ['metal', 'bits', 'sampler'],
      roles: ['wear'],
      traits: ['cold', 'worn', 'faint'],
    },
    Phone: {
      says: 'a digital telephone line, eight bits, band-limited and dull',
      brief: 'a digital telephone line',
      nouns: ['phone', 'line'],
      roles: ['wear'],
      traits: ['dark', 'faint'],
    },
    Worn: {
      says: 'nine-bit converters on an unsteady clock, hiss on high notes',
      brief: 'worn nine-bit converters',
      nouns: ['sampler', 'bits', 'grain'],
      roles: ['wear'],
      traits: ['cold', 'worn', 'faint'],
    },
    Crushed: {
      says: 'five-bit converters fed hot, a coarse grain on every note',
      brief: 'hot five-bit converters',
      nouns: ['bits', 'grain', 'grit'],
      roles: ['wear'],
      traits: ['cold', 'worn', 'faint'],
    },
    Coarse: {
      says: 'seven-bit converters whose quiet tails break up and cut off',
      brief: 'seven-bit converters',
      nouns: ['bits', 'steps', 'grain'],
      roles: ['wear'],
      traits: ['cold', 'worn', 'faint'],
    },
    Jittery: {
      says: 'smooth, dull converters whose clock is badly unsteady',
      brief: 'converters with a bad clock',
      nouns: ['clock', 'sampler'],
      roles: ['wear'],
      traits: ['dark', 'worn', 'faint'],
    },
    Sunken: {
      says: 'converters at a very low rate, filtered smooth and dull',
      brief: 'dull low-rate converters',
      nouns: ['sampler', 'depths', 'bits'],
      roles: ['wear'],
      traits: ['dark', 'worn'],
    },
    'Grit bed': {
      says: 'a bed of six-bit grit and false tones under the clean sound',
      brief: 'a bed of digital grit',
      nouns: ['grit', 'bed', 'bits'],
      roles: ['wear'],
      traits: ['cold', 'faint'],
    },
    'Flat tops': {
      says: 'clean converters fed hot, so the loudest peaks flatten',
      brief: 'converters fed too hot',
      nouns: ['peaks', 'clip'],
      roles: ['drive'],
      traits: ['faint'],
    },
    Rasp: {
      says: 'four-bit companded converters that rasp on every note',
      brief: 'rasping four-bit converters',
      nouns: ['rasp', 'bits', 'grit'],
      roles: ['wear'],
      traits: ['cold', 'worn'],
    },
    Clang: {
      says: 'raw converters at a very low rate, bright and clanging',
      brief: 'clanging raw converters',
      nouns: ['clang', 'metal', 'bits'],
      roles: ['wear'],
      traits: ['bright', 'cold', 'worn', 'strange'],
    },
  },
}
