import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'vintage-digital',
  jitter: [],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    Sampler: {
      says: 'the converters of an early sampler, soft on top and gritty',
      brief: 'early sampler converters',
      nouns: ['sampler', 'converter'],
      roles: ['wear'],
      traits: ['dark', 'cold'],
    },
    Glaze: {
      says: 'a thin twelve-bit glaze from converters at a moderate rate',
      brief: 'a thin twelve-bit glaze',
      nouns: ['glaze', 'sampler'],
      roles: ['wear'],
      traits: ['cold', 'faint'],
    },
    Toy: {
      says: 'toy eight-bit converters, dull, with false tones folded in',
      brief: 'toy eight-bit converters',
      nouns: ['converter', 'sampler'],
      roles: ['wear'],
      traits: ['dark', 'cold', 'strange'],
    },
    Dusty: {
      says: 'dull ten-bit converters that hiss along with every note',
      brief: 'dull, hissing converters',
      nouns: ['sampler', 'dust'],
      roles: ['wear'],
      traits: ['dark', 'cold'],
    },
    Glassy: {
      says: 'old converters left unsmoothed, with a glassy ring on top',
      brief: 'glassy old converters',
      nouns: ['glass', 'sampler'],
      roles: ['wear'],
      traits: ['bright', 'cold'],
    },
    Metallic: {
      says: 'low-rate converters that fold the highs down as false tones',
      brief: 'converters with false tones',
      nouns: ['converter', 'sampler'],
      roles: ['wear'],
      traits: ['dark', 'cold', 'strange'],
    },
    Phone: {
      says: 'an eight-bit digital telephone line, band-limited and dull',
      brief: 'a digital telephone line',
      nouns: ['converter'],
      roles: ['wear'],
      traits: ['dark'],
    },
    Worn: {
      says: 'worn nine-bit converters, grainy, hissing on the high notes',
      brief: 'worn nine-bit converters',
      nouns: ['sampler', 'grain'],
      roles: ['wear'],
      traits: ['cold'],
    },
    Crushed: {
      says: 'five-bit converters fed hot, coarse and grainy on every note',
      brief: 'coarse five-bit converters',
      nouns: ['grain', 'grit'],
      roles: ['wear'],
      traits: ['cold'],
    },
    Coarse: {
      says: 'seven-bit converters whose quiet tails break up and cut off',
      brief: 'grainy seven-bit converters',
      nouns: ['grain', 'converter'],
      roles: ['wear'],
      traits: ['cold'],
    },
    Jittery: {
      says: 'smooth, dull converters with a hiss that rides high notes',
      brief: 'smooth converters that hiss',
      nouns: ['sampler', 'converter'],
      roles: ['wear'],
      traits: ['dark'],
    },
    Sunken: {
      says: 'converters at a very low rate, filtered smooth and dull',
      brief: 'dull low-rate converters',
      nouns: ['sampler', 'converter'],
      roles: ['wear'],
      traits: ['dark', 'far'],
    },
    'Grit bed': {
      says: 'a bed of six-bit grit and false tones under the clean sound',
      brief: 'a bed of digital grit',
      nouns: ['grit', 'trace'],
      roles: ['wear'],
      traits: ['cold', 'faint'],
    },
    'Flat tops': {
      says: 'clean converters fed hot, so the loudest peaks flatten',
      brief: 'converters fed too hot',
      nouns: ['converter'],
      roles: ['drive'],
      traits: ['faint'],
    },
    Rasp: {
      says: 'coarse four-bit converters that rasp on every note',
      brief: 'rasping four-bit converters',
      nouns: ['grit', 'fuzz'],
      roles: ['wear'],
      traits: ['cold'],
    },
    Clang: {
      says: 'raw converters at a very low rate, bright and clanging',
      brief: 'clanging raw converters',
      nouns: ['clang', 'sampler'],
      roles: ['wear'],
      traits: ['bright', 'cold', 'strange'],
    },
  },
}
