import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'vinyl',
  jitter: ['spin'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    'New pressing': {
      says: 'the light surface hiss and fine crackle of a new record',
      brief: 'the hiss of a new record',
      nouns: ['record', 'hiss'],
      roles: ['hiss'],
      traits: ['faint', 'noisy'],
    },
    'Charity shop find': {
      says: 'a well-played record, dulled, swaying, with ticks and pops',
      brief: 'a well-played old record',
      nouns: ['record', 'dust', 'groove'],
      roles: ['wear'],
      traits: ['worn', 'noisy', 'unsteady', 'dark'],
    },
    'Ballroom 78': {
      says: 'a worn shellac disc, nearly mono, narrow-band and noisy',
      brief: 'a worn shellac disc',
      nouns: ['record', 'crackle'],
      roles: ['wear'],
      traits: ['worn', 'noisy', 'narrow', 'cold', 'unsteady'],
    },
    'Jukebox single': {
      says: 'a played single on a bright cartridge, lightly crackling',
      brief: 'a bright, played single',
      nouns: ['record', 'jukebox'],
      roles: ['wear'],
      traits: ['bright', 'noisy'],
    },
    Warped: {
      says: 'a badly warped record whose pitch sways once a turn',
      brief: 'a badly warped record',
      nouns: ['record', 'sway', 'wobble'],
      roles: ['wear', 'motion'],
      traits: ['unsteady', 'slow', 'worn'],
    },
    'Dust and scratches': {
      says: 'a record thick with dust, ticking and popping throughout',
      brief: 'a dusty, ticking record',
      nouns: ['dust', 'crackle', 'record'],
      roles: ['wear', 'hiss'],
      traits: ['noisy', 'worn'],
    },
    'Inner groove': {
      says: 'a worn-out groove that dulls the top and fuzzes loud highs',
      brief: 'a worn-out record groove',
      nouns: ['groove', 'record'],
      roles: ['wear'],
      traits: ['worn', 'narrow', 'dark'],
    },
    'Locked scratch': {
      says: 'a record with loud clicks and a scratch on every turn',
      brief: 'a record with a loud scratch',
      nouns: ['clicks', 'record'],
      roles: ['wear'],
      traits: ['noisy', 'worn', 'strange'],
    },
    'Slow platter': {
      says: 'a warped record through a dark cartridge, swaying slowly',
      brief: 'a dark, swaying record',
      nouns: ['record', 'sway'],
      roles: ['wear', 'motion'],
      traits: ['dark', 'warm', 'unsteady', 'slow'],
    },
    'Parlour 78': {
      says: 'a lightly played shellac disc, nearly mono, no bass or top',
      brief: 'a shellac disc, nearly mono',
      nouns: ['record'],
      roles: ['wear'],
      traits: ['narrow', 'cold', 'worn'],
    },
    'Bright needle': {
      says: 'a record played through a bright, thin cartridge',
      brief: 'a bright, thin record',
      nouns: ['record'],
      roles: ['wear'],
      traits: ['bright', 'cold'],
    },
    'Dull stylus': {
      says: 'a worn record through a dark, dull cartridge',
      brief: 'a dull, worn record',
      nouns: ['record', 'groove'],
      roles: ['wear'],
      traits: ['dark', 'warm', 'worn'],
    },
    'Crackle bed': {
      says: 'a thick bed of record crackle over steady surface hiss',
      brief: 'a thick bed of crackle',
      nouns: ['crackle', 'dust'],
      roles: ['hiss'],
      traits: ['noisy'],
    },
    'Surface and rumble': {
      says: 'the steady surface hiss and turntable rumble of a record',
      brief: 'surface hiss and rumble',
      nouns: ['hiss', 'record'],
      roles: ['hiss'],
      traits: ['noisy', 'heavy'],
    },
    'Warp chorus': {
      says: 'a warped record mixed against the dry sound as a slow chorus',
      brief: 'a slow record-warp chorus',
      nouns: ['chorus', 'sway'],
      roles: ['motion', 'wear'],
      traits: ['slow', 'unsteady', 'clean'],
    },
    'Ruined record': {
      says: 'a ruined record, lurching in pitch under clicks and crackle',
      brief: 'a wrecked, lurching record',
      nouns: ['record', 'crackle', 'clicks'],
      roles: ['wear'],
      traits: ['heavy', 'worn', 'noisy', 'unsteady', 'strange', 'dark'],
    },
  },
}
