import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'vinyl',
  jitter: ['spin'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    'New pressing': {
      says: 'a new record with a little surface hiss and fine crackle',
      brief: 'a new record',
      nouns: ['record', 'pressing', 'groove'],
      roles: ['wear'],
      traits: ['faint', 'noisy'],
    },
    'Charity shop find': {
      says: 'a well-played record, dulled, swaying, with ticks and pops',
      brief: 'a well-played old record',
      nouns: ['record', 'dust', 'groove'],
      roles: ['wear'],
      traits: ['worn', 'noisy', 'unsteady', 'dark'],
    },
    'Ballroom 78': {
      says: 'a worn shellac disc, nearly mono, narrow-band and noisy',
      brief: 'a worn shellac disc',
      nouns: ['shellac', 'disc', 'record'],
      roles: ['wear'],
      traits: ['worn', 'noisy', 'narrow', 'cold', 'unsteady'],
    },
    'Jukebox single': {
      says: 'a played single on a bright cartridge, lightly crackling',
      brief: 'a bright, played single',
      nouns: ['single', 'record', 'jukebox'],
      roles: ['wear'],
      traits: ['bright', 'noisy'],
    },
    Warped: {
      says: 'a badly warped record whose pitch sways once a turn',
      brief: 'a badly warped record',
      nouns: ['warp', 'record', 'sway'],
      roles: ['wear', 'motion'],
      traits: ['unsteady', 'slow', 'worn'],
    },
    'Dust and scratches': {
      says: 'a record thick with dust, ticking and popping throughout',
      brief: 'a dusty, ticking record',
      nouns: ['dust', 'crackle', 'record'],
      roles: ['wear', 'hiss'],
      traits: ['noisy', 'worn'],
    },
    'Inner groove': {
      says: 'a worn-out groove that dulls the top and fuzzes loud highs',
      brief: 'a worn-out groove',
      nouns: ['groove', 'record'],
      roles: ['wear'],
      traits: ['worn', 'narrow'],
    },
    'Locked scratch': {
      says: 'a record with loud clicks and a scratch on every turn',
      brief: 'a record with a loud scratch',
      nouns: ['scratch', 'clicks', 'record'],
      roles: ['wear', 'hiss'],
      traits: ['noisy', 'worn', 'strange', 'long'],
    },
    'Slow platter': {
      says: 'a warped record through a dark cartridge, swaying slowly',
      brief: 'a dark, swaying record',
      nouns: ['platter', 'record', 'sway'],
      roles: ['wear', 'motion'],
      traits: ['dark', 'warm', 'unsteady', 'slow'],
    },
    'Parlour 78': {
      says: 'a lightly played shellac disc, nearly mono, no bass or top',
      brief: 'a shellac disc, nearly mono',
      nouns: ['shellac', 'parlour', 'disc'],
      roles: ['wear'],
      traits: ['narrow', 'cold', 'worn'],
    },
    'Bright needle': {
      says: 'an unworn record through a bright, thin cartridge',
      brief: 'a bright, thin cartridge',
      nouns: ['needle', 'record', 'stylus'],
      roles: ['wear'],
      traits: ['bright', 'cold'],
    },
    'Dull stylus': {
      says: 'a worn record through a dark, dull cartridge',
      brief: 'a dull, worn record',
      nouns: ['stylus', 'record', 'groove'],
      roles: ['wear'],
      traits: ['dark', 'warm', 'worn'],
    },
    'Crackle bed': {
      says: 'a flat, unworn record under a thick bed of crackle',
      brief: 'a thick bed of crackle',
      nouns: ['crackle', 'dust', 'bed'],
      roles: ['hiss', 'wear'],
      traits: ['noisy'],
    },
    'Surface and rumble': {
      says: 'the steady surface hiss and turntable rumble of a record',
      brief: 'surface hiss and rumble',
      nouns: ['surface', 'rumble', 'hiss'],
      roles: ['hiss', 'wear'],
      traits: ['noisy', 'heavy', 'long'],
    },
    'Warp chorus': {
      says: 'a warped record with no noise, mixed in as a slow chorus',
      brief: 'a slow record-warp chorus',
      nouns: ['chorus', 'warp', 'sway'],
      roles: ['motion', 'wear'],
      traits: ['slow', 'unsteady', 'clean'],
    },
    'Ruined record': {
      says: 'a ruined record, lurching in pitch under clicks and crackle',
      brief: 'a wrecked, lurching record',
      nouns: ['record', 'wreck', 'scratch'],
      roles: ['wear', 'hiss'],
      traits: ['heavy', 'worn', 'noisy', 'unsteady', 'strange', 'long'],
    },
  },
}
