import { type DeviceLexicon } from './types'

export const LEXICON: DeviceLexicon = {
  device: 'vowel-reverb',
  jitter: ['decay', 'preDelay'],
  trim: [{ param: 'mix', kind: 'mix' }],
  voices: {
    'Choir of ah': {
      says: 'a hall whose tail sings a soft ah',
      brief: 'a hall that sings ah',
      nouns: ['choir', 'hall', 'voices'],
      roles: ['halo'],
      traits: [],
    },
    'Low monks': {
      says: 'a large hall whose tail hums a deep oh in bass voices',
      brief: 'a hall of deep bass voices',
      nouns: ['choir', 'chant'],
      roles: ['halo'],
      traits: ['dark', 'low', 'long'],
    },
    'High ee': {
      says: 'a hall whose tail sings a high ee',
      brief: 'a hall that sings a high ee',
      nouns: ['choir', 'voices'],
      roles: ['halo'],
      traits: ['bright'],
    },
    'Vowel drift': {
      says: 'a hall whose choir wanders from vowel to vowel',
      brief: 'a wandering-vowel choir',
      nouns: ['choir', 'voices', 'drift'],
      roles: ['halo'],
      traits: ['slow'],
    },
    Whispering: {
      says: 'a medium hall with only a breath of voice in its tail',
      brief: 'a hall with a hint of voice',
      nouns: ['hall', 'whisper'],
      roles: ['hall', 'halo'],
      traits: ['clean'],
    },
    'Oo behind': {
      says: 'a soft sung oo that follows a moment behind each note',
      brief: 'a sung oo just behind',
      nouns: ['choir', 'voices', 'shadow'],
      roles: ['halo'],
      traits: [],
    },
    Cathedral: {
      says: 'a cathedral whose long tail sings a soft open ah',
      brief: 'a singing cathedral',
      nouns: ['cathedral', 'choir', 'nave'],
      roles: ['halo', 'hall'],
      traits: ['long', 'wide'],
    },
    Chapel: {
      says: 'a small chapel with a short sung eh in its tail',
      brief: 'a small singing chapel',
      nouns: ['chapel', 'room', 'choir'],
      roles: ['room', 'halo'],
      traits: ['short', 'faint'],
    },
    'Plain hall': {
      says: 'a plain hall of about four seconds',
      brief: 'a plain medium hall',
      nouns: ['hall'],
      roles: ['hall'],
      traits: ['clean'],
    },
    'Choir alone': {
      says: 'a wordless choir alone with none of the dry sound left',
      brief: 'a wordless choir alone',
      nouns: ['choir', 'voices', 'chant'],
      roles: ['halo'],
      traits: ['heavy', 'far', 'long', 'wide'],
    },
    'Faint voices': {
      says: 'faint voices singing behind the sound',
      brief: 'faint voices behind',
      nouns: ['voices', 'choir', 'murmur'],
      roles: ['halo'],
      traits: ['faint'],
    },
    'Lone voice': {
      says: 'a small mono reverb whose tail holds one fixed sung eh',
      brief: 'a mono reverb singing eh',
      nouns: ['voice'],
      roles: ['halo'],
      traits: ['faint', 'narrow'],
    },
    'High choir': {
      says: 'a vast hall whose long tail sings a high bright ah',
      brief: 'a long high choir',
      nouns: ['choir', 'voices'],
      roles: ['halo', 'hall'],
      traits: ['bright', 'long'],
    },
    'Endless oo': {
      says: 'a huge hall whose tail hums a soft oo for a long while',
      brief: 'a very long sung oo',
      nouns: ['choir', 'drone'],
      roles: ['halo', 'hall'],
      traits: ['long', 'wide'],
    },
    'Late basses': {
      says: 'a hall of deep voices that sing ee late behind each note',
      brief: 'a hall of late deep voices',
      nouns: ['choir', 'voices'],
      roles: ['halo'],
      traits: ['low'],
    },
    Humming: {
      says: 'a dull closed-mouth hum of deep voices behind the sound',
      brief: 'a deep hum of voices',
      nouns: ['murmur', 'choir'],
      roles: ['halo'],
      traits: ['dark', 'warm', 'low', 'wide'],
    },
  },
}
