// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Radio, shared with
// src/dsp/devices/radio.gen.ts:
//    0  band: 0 Medium wave, 1 Shortwave, 2 Sideband, default 1
//    1  tuning: -1..1, default 0
//    2  drift: 0..1, default 0.2
//    3  fading: 0..1, default 0.6
//    4  static: 0..1, default 0.3
//    5  interference: 0..1, default 0.15
//    6  bandwidth: 0..1, default 0.5
//    7  speaker: 0..1, default 0.4
//    8  mix: 0..1, default 1

#pragma once

namespace livemix {
namespace radio {

enum Param : int {
  kBand = 0,
  kTuning = 1,
  kDrift = 2,
  kFading = 3,
  kStatic = 4,
  kInterference = 5,
  kBandwidth = 6,
  kSpeaker = 7,
  kMix = 8,
  kNumParams = 9,
};

inline constexpr float kParamMin[kNumParams] = {0.0f, -1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
inline constexpr float kParamMax[kNumParams] = {2.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f};
inline constexpr float kParamDefault[kNumParams] = {1.0f, 0.0f, 0.2f, 0.6f, 0.3f, 0.15f, 0.5f, 0.4f, 1.0f};

}  // namespace radio
}  // namespace livemix
