// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Magnet Piano, shared with
// src/dsp/devices/magnet-piano.gen.ts:
//    0  bloom: 0.05..10 s, default 1
//    1  harmonic: 1..8, default 1
//    2  bright: 0..1, default 0.2
//    3  hammer: 0..1, default 0
//    4  shimmer: 0..1, default 0.25
//    5  sweep: 0..1, default 0
//    6  sweepRate: 0.02..2 Hz, default 0.12
//    7  sympathy: 0..1, default 0.3
//    8  damper: 0.05..12 s, default 1.5
//    9  body: 0..1, default 0.4
//   10  width: 0..1, default 0.6
//   11  volume: -48..6 dB, default -6

#pragma once

namespace livemix {
namespace magnet_piano {

enum Param : int {
  kBloom = 0,
  kHarmonic = 1,
  kBright = 2,
  kHammer = 3,
  kShimmer = 4,
  kSweep = 5,
  kSweepRate = 6,
  kSympathy = 7,
  kDamper = 8,
  kBody = 9,
  kWidth = 10,
  kVolume = 11,
  kNumParams = 12,
};

inline constexpr float kParamMin[kNumParams] = {0.05f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.02f, 0.0f, 0.05f, 0.0f, 0.0f, -48.0f};
inline constexpr float kParamMax[kNumParams] = {10.0f, 8.0f, 1.0f, 1.0f, 1.0f, 1.0f, 2.0f, 1.0f, 12.0f, 1.0f, 1.0f, 6.0f};
inline constexpr float kParamDefault[kNumParams] = {1.0f, 1.0f, 0.2f, 0.0f, 0.25f, 0.0f, 0.12f, 0.3f, 1.5f, 0.4f, 0.6f, -6.0f};

}  // namespace magnet_piano
}  // namespace livemix
