// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Flock, shared with
// src/dsp/devices/flock.gen.ts:
//    0  birds: 1..8, default 5
//    1  gather: 0.02..12 s, default 1.2
//    2  from: 0 Below, 1 Above, 2 Around, default 0
//    3  stray: 0..1, default 0.3
//    4  flutter: 0.05..8 Hz, default 0.5
//    5  tone: 0..1, default 0.25
//    6  chirp: 0..1, default 0
//    7  octaves: 0..1, default 0.3
//    8  leave: 0.05..15 s, default 2.5
//    9  width: 0..1, default 0.7
//   10  volume: -48..6 dB, default -9

#pragma once

namespace livemix {
namespace flock {

enum Param : int {
  kBirds = 0,
  kGather = 1,
  kFrom = 2,
  kStray = 3,
  kFlutter = 4,
  kTone = 5,
  kChirp = 6,
  kOctaves = 7,
  kLeave = 8,
  kWidth = 9,
  kVolume = 10,
  kNumParams = 11,
};

inline constexpr float kParamMin[kNumParams] = {1.0f, 0.02f, 0.0f, 0.0f, 0.05f, 0.0f, 0.0f, 0.0f, 0.05f, 0.0f, -48.0f};
inline constexpr float kParamMax[kNumParams] = {8.0f, 12.0f, 2.0f, 1.0f, 8.0f, 1.0f, 1.0f, 1.0f, 15.0f, 1.0f, 6.0f};
inline constexpr float kParamDefault[kNumParams] = {5.0f, 1.2f, 0.0f, 0.3f, 0.5f, 0.25f, 0.0f, 0.3f, 2.5f, 0.7f, -9.0f};

}  // namespace flock
}  // namespace livemix
