// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Shortwave, shared with
// src/dsp/devices/shortwave.gen.ts:
//    0  signal: 0 Whistle, 1 Warble, 2 Pips, 3 Voices, default 0
//    1  tuneIn: 0..1, default 0.25
//    2  drift: 0..1, default 0.15
//    3  rate: 0.25..12 Hz, default 2
//    4  shift: 0 Octave down, 1 Octave up, 2 Two octaves up, default 1
//    5  fading: 0..1, default 0.5
//    6  beat: 0..1, default 0
//    7  static: 0..1, default 0.3
//    8  band: 0..1, default 0.25
//    9  attack: 0.005..8 s, default 0.15
//   10  release: 0.05..12 s, default 1.8
//   11  volume: -48..6 dB, default -10

#pragma once

namespace livemix {
namespace shortwave {

enum Param : int {
  kSignal = 0,
  kTuneIn = 1,
  kDrift = 2,
  kRate = 3,
  kShift = 4,
  kFading = 5,
  kBeat = 6,
  kStatic = 7,
  kBand = 8,
  kAttack = 9,
  kRelease = 10,
  kVolume = 11,
  kNumParams = 12,
};

inline constexpr float kParamMin[kNumParams] = {0.0f, 0.0f, 0.0f, 0.25f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.005f, 0.05f, -48.0f};
inline constexpr float kParamMax[kNumParams] = {3.0f, 1.0f, 1.0f, 12.0f, 2.0f, 1.0f, 1.0f, 1.0f, 1.0f, 8.0f, 12.0f, 6.0f};
inline constexpr float kParamDefault[kNumParams] = {0.0f, 0.25f, 0.15f, 2.0f, 1.0f, 0.5f, 0.0f, 0.3f, 0.25f, 0.15f, 1.8f, -10.0f};

}  // namespace shortwave
}  // namespace livemix
