// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Tape Loop, shared with
// src/dsp/devices/tape-loop.gen.ts:
//    0  length: 1..30 s, default 1.8
//    1  feedback: 0..1, default 0.7
//    2  speed: 0 Half, 1 Normal, 2 Double, default 1
//    3  direction: 0 Forward, 1 Reverse, default 0
//    4  record: 0 On, 1 Off, default 0
//    5  wear: 0..1, default 0.3
//    6  wow: 0..1, default 0.2
//    7  lowCut: 20..800 Hz, default 60
//    8  spread: 0..1, default 0.3
//    9  mix: 0..1, default 0.5

#pragma once

namespace livemix {
namespace tape_loop {

enum Param : int {
  kLength = 0,
  kFeedback = 1,
  kSpeed = 2,
  kDirection = 3,
  kRecord = 4,
  kWear = 5,
  kWow = 6,
  kLowCut = 7,
  kSpread = 8,
  kMix = 9,
  kNumParams = 10,
};

inline constexpr float kParamMin[kNumParams] = {1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 20.0f, 0.0f, 0.0f};
inline constexpr float kParamMax[kNumParams] = {30.0f, 1.0f, 2.0f, 1.0f, 1.0f, 1.0f, 1.0f, 800.0f, 1.0f, 1.0f};
inline constexpr float kParamDefault[kNumParams] = {1.8f, 0.7f, 1.0f, 0.0f, 0.0f, 0.3f, 0.2f, 60.0f, 0.3f, 0.5f};

}  // namespace tape_loop
}  // namespace livemix
