// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Underwater, shared with
// src/dsp/devices/underwater.gen.ts:
//    0  depth: 0..1, default 0.55
//    1  waver: 0..1, default 0.35
//    2  rate: 0.05..3 Hz, default 0.3
//    3  bubbles: 0..1, default 0.4
//    4  bubbleSize: 0..1, default 0.45
//    5  resonance: 0..1, default 0.4
//    6  surface: 0..1, default 0.3
//    7  pressure: 0..1, default 0.35
//    8  width: 0..1, default 0.5
//    9  mix: 0..1, default 1

#pragma once

namespace livemix {
namespace underwater {

enum Param : int {
  kDepth = 0,
  kWaver = 1,
  kRate = 2,
  kBubbles = 3,
  kBubbleSize = 4,
  kResonance = 5,
  kSurface = 6,
  kPressure = 7,
  kWidth = 8,
  kMix = 9,
  kNumParams = 10,
};

inline constexpr float kParamMin[kNumParams] = {0.0f, 0.0f, 0.05f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
inline constexpr float kParamMax[kNumParams] = {1.0f, 1.0f, 3.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f};
inline constexpr float kParamDefault[kNumParams] = {0.55f, 0.35f, 0.3f, 0.4f, 0.45f, 0.4f, 0.3f, 0.35f, 0.5f, 1.0f};

}  // namespace underwater
}  // namespace livemix
