// Bass notes and held bass tones: single notes on the five bass instruments, each starting on its attack
// and dying away inside its length, and eight held tones that loop.
// Numbers 201 to 232. What every sound here is held to is in docs/factory.md.
//
// Every instrument parameter is written out: the preset named is only the nearest starting point.

import { type PatchDevice } from '../../../core/devices/patch'
import { breathe, hall, quarterTurn, soften } from '../parts'
import { type FactorySound } from '../types'
import { looped, played, sound } from './recipe'

/**
 * Holds the body of a plucked note up under its pick: a ceiling the pluck leans on, let go at once.
 * It only works once `gain` brings the pluck over the ceiling: the upright ring, peaking near -19 dBFS
 * at its volume, needs more than 7.
 */
const hold = (gain: number): PatchDevice => ({
  deviceId: 'ambient-limiter',
  preset: 'Pinned',
  params: { ceiling: -12, gain, release: 0.3, ride: 0, autoGain: 0 },
})

/**
 * `quarterTurn` three times round: the fold still meets every partial a quarter turn off, and inside one
 * loop the wave passes through every shape that turning its partials together gives, the most peaked one
 * among them. The bank brings the peak to -6 dBFS, so a held tone comes out up to 1.7 LU less loud for
 * it, with the same partials at the same levels.
 */
const threeQuarterTurn = (seconds: number): PatchDevice => {
  const turn = quarterTurn(seconds)
  return { ...turn, params: { ...turn.params, fine: 3 / (4 * seconds) } }
}

export const BASS_NOTES: readonly FactorySound[] = [
  // Sub bass: a sine, its fall onto the note and the harmonics added to it.
  sound({
    id: 'sub-boom-e',
    number: 201,
    name: 'Sub boom {E}',
    kind: 'oneshot',
    description:
      'A long sine bass boom that falls two octaves onto a low {E} and rings for seconds.',
    instrument: {
      deviceId: 'sub-bass',
      preset: 'Long boom',
      params: {
        shape: 0.1,
        harmonics: 0.35,
        drop: 24,
        fall: 220,
        attack: 0.002,
        decay: 8,
        release: 3,
        drive: 0.3,
        glide: 0,
        volume: -9,
      },
    },
    effects: [hall('Room', 0.12)],
    ...played(6, [[0, 5, 28]], 0.5),
  }),
  sound({
    id: 'soft-sub-a',
    number: 202,
    name: 'Soft sub {A}',
    kind: 'oneshot',
    description:
      'A soft round sine bass note on a low {A} with its octave and fifth just heard, fading slowly.',
    instrument: {
      deviceId: 'sub-bass',
      preset: 'Soft sub',
      params: {
        shape: 0.15,
        harmonics: 0.3,
        drop: 0,
        fall: 40,
        attack: 0.05,
        decay: 5,
        release: 1.5,
        drive: 0.1,
        glide: 0,
        volume: -9,
      },
    },
    effects: [hall('Room', 0.1)],
    ...played(4, [[0, 2.6, 33]], 0.4),
  }),
  sound({
    id: 'sub-thump-d',
    number: 203,
    name: 'Sub thump {D}',
    kind: 'oneshot',
    description:
      'A short sine bass thump that drops an octave onto {D} and is gone in half a second.',
    instrument: {
      deviceId: 'sub-bass',
      preset: 'Short thump',
      params: {
        shape: 0.05,
        harmonics: 0.25,
        drop: 12,
        fall: 30,
        attack: 0.001,
        decay: 0.7,
        release: 0.3,
        drive: 0.25,
        glide: 0,
        volume: -5,
      },
    },
    effects: [hall('Room', 0.08)],
    ...played(2, [[0, 0.8, 38]], 0.2),
  }),
  sound({
    id: 'hum-note-g',
    number: 204,
    name: 'Hum note {G}',
    kind: 'oneshot',
    description:
      'A squared-off bass hum on {G} with its octave and fifth added, so small speakers play it.',
    instrument: {
      deviceId: 'sub-bass',
      preset: 'Small speaker hum',
      params: {
        shape: 1,
        harmonics: 0.6,
        drop: 0,
        fall: 40,
        attack: 0.03,
        decay: 3.5,
        release: 0.8,
        drive: 0.35,
        glide: 0,
        volume: -11,
      },
    },
    effects: [hall('Room', 0.1)],
    ...played(4, [[0, 2.4, 43]], 0.4),
  }),
  sound({
    id: 'sub-swell-c',
    number: 205,
    name: 'Sub swell {C}',
    kind: 'pad',
    description: 'A sine bass on {C} that swells in over two seconds and fades away again.',
    instrument: {
      deviceId: 'sub-bass',
      preset: 'Slow swell',
      params: {
        shape: 0.3,
        harmonics: 0.5,
        drop: 0,
        fall: 40,
        attack: 2,
        decay: 20,
        release: 4,
        drive: 0.25,
        glide: 0,
        volume: -7,
      },
    },
    effects: [hall('Room', 0.12)],
    ...played(6, [[0, 2.2, 36]], 0.5),
  }),
  sound({
    id: 'click-sub-f',
    number: 206,
    name: 'Click sub {F}',
    kind: 'oneshot',
    description:
      'A deep sine bass on a low {F} with a click at its start, where it snaps down three octaves.',
    instrument: {
      deviceId: 'sub-bass',
      preset: 'Hard knock',
      params: {
        shape: 0.4,
        harmonics: 0.3,
        drop: 36,
        fall: 35,
        attack: 0.001,
        decay: 3,
        release: 0.8,
        drive: 1,
        glide: 0,
        volume: -6,
      },
    },
    effects: [hall('Room', 0.08)],
    ...played(3, [[0, 2, 29]], 0.3),
  }),

  // FM bass: a sine bent by a second sine, bright where it is struck.
  sound({
    id: 'fm-round-knock-c',
    number: 207,
    name: 'Round knock {C}',
    kind: 'oneshot',
    description: 'A round FM bass note on {C}: a knock at the front that settles to a plain tone.',
    instrument: {
      deviceId: 'fm-bass',
      preset: 'Round knock',
      params: {
        ratio: 1,
        depth: 0.6,
        bite: 0.12,
        body: 0.1,
        feedback: 0,
        sub: 0,
        decay: 1.6,
        release: 0.3,
        glide: 0,
        volume: -9,
      },
    },
    effects: [hall('Room', 0.1)],
    ...played(2.5, [[0, 1.6, 36]], 0.3),
  }),
  sound({
    id: 'fm-wooden-knock-g',
    number: 208,
    name: 'Wooden knock {G}',
    kind: 'oneshot',
    description:
      'A hollow wooden FM bass knock on {G}: a tenth of a second of overtones, then a short round note.',
    instrument: {
      deviceId: 'fm-bass',
      preset: 'Wooden knock',
      params: {
        ratio: 3,
        depth: 0.7,
        bite: 0.1,
        body: 0.15,
        feedback: 0,
        sub: 0,
        decay: 0.6,
        release: 0.15,
        glide: 0,
        volume: -7,
      },
    },
    effects: [hall('Room', 0.12)],
    ...played(2, [[0, 0.9, 43]], 0.2),
  }),
  sound({
    id: 'fm-rubber-note-e',
    number: 209,
    name: 'Rubber FM bass {E}',
    kind: 'oneshot',
    description: 'A rubbery FM bass note on {E}, hollow and bright, over a sine an octave below.',
    instrument: {
      deviceId: 'fm-bass',
      preset: 'Rubber bass',
      params: {
        ratio: 2,
        depth: 0.55,
        bite: 0.3,
        body: 0.7,
        feedback: 0.25,
        sub: 0.3,
        decay: 1.1,
        release: 0.12,
        glide: 0,
        volume: -9,
      },
    },
    effects: [hall('Room', 0.1)],
    ...played(2, [[0, 1.2, 40]], 0.2),
  }),
  sound({
    id: 'fm-growl-a',
    number: 210,
    name: 'FM growl {A}',
    kind: 'oneshot',
    description: 'A buzzing FM bass growl on a low {A}, its edge darkening as the note falls away.',
    instrument: {
      deviceId: 'fm-bass',
      preset: 'Low growl',
      params: {
        ratio: 1,
        depth: 0.62,
        bite: 1.2,
        body: 0.5,
        feedback: 0.85,
        sub: 0,
        decay: 4,
        release: 0.6,
        glide: 0,
        volume: -9,
      },
    },
    effects: [hall('Room', 0.1)],
    ...played(4, [[0, 2.8, 33]], 0.4),
  }),
  sound({
    id: 'fm-glass-pluck-f',
    number: 211,
    name: 'Glass bass pluck {F}',
    kind: 'oneshot',
    description: 'A glassy FM pluck low down on {F}, bell-like overtones over a round bass tone.',
    instrument: {
      deviceId: 'fm-bass',
      preset: 'Low bell',
      params: {
        ratio: 5,
        depth: 0.4,
        bite: 0.5,
        body: 0.05,
        feedback: 0,
        sub: 0.25,
        decay: 3,
        release: 1,
        glide: 0,
        volume: -10,
      },
    },
    effects: [hall('Room', 0.15)],
    ...played(3, [[0, 1.8, 41]], 0.3),
  }),

  // Acid bass: one oscillator through a resonant filter that each note opens and closes.
  // A gain above 0.7 is an accent, so the others are played at 0.65.
  sound({
    id: 'acid-squelch-d',
    number: 212,
    name: 'Squelch bass {D}',
    kind: 'oneshot',
    description: 'A squelching sawtooth bass note on {D}, its resonant filter snapping shut.',
    instrument: {
      deviceId: 'acid-bass',
      preset: 'Wet squelch',
      params: {
        wave: 0,
        cutoff: 150,
        resonance: 0.88,
        envMod: 0.85,
        decay: 0.45,
        accent: 0.6,
        slide: 0.07,
        sustain: 3,
        drive: 0.4,
        volume: -10,
      },
    },
    effects: [hall('Room', 0.1)],
    ...played(2, [[0, 1.2, 38, 0.65]], 0.2),
  }),
  sound({
    id: 'acid-accent-g',
    number: 213,
    name: 'Accent bass {G}',
    kind: 'oneshot',
    description:
      'An accented sawtooth bass note on {G} that bites: the filter flung open and shut.',
    instrument: {
      deviceId: 'acid-bass',
      preset: 'Resonant scream',
      params: {
        wave: 0,
        cutoff: 235,
        resonance: 0.9,
        envMod: 0.3,
        decay: 0.5,
        accent: 1,
        slide: 0.08,
        sustain: 2.5,
        drive: 0.4,
        volume: -7,
      },
    },
    effects: [hall('Room', 0.1)],
    ...played(2, [[0, 1, 43, 1]], 0.2),
  }),
  sound({
    id: 'acid-slow-close-g',
    number: 214,
    name: 'Slow closing bass {G}',
    kind: 'oneshot',
    description: 'A long sawtooth bass note on a low {G} whose filter takes five seconds to close.',
    instrument: {
      deviceId: 'acid-bass',
      preset: 'Slow closing tone',
      params: {
        wave: 0,
        cutoff: 80,
        resonance: 0.35,
        envMod: 0.7,
        decay: 6,
        accent: 0.3,
        slide: 0.3,
        sustain: 12,
        drive: 0.6,
        volume: -9,
      },
    },
    effects: [hall('Room', 0.12)],
    ...played(6, [[0, 5.6, 31, 0.65]], 0.4),
  }),
  sound({
    id: 'acid-hollow-square-a',
    number: 215,
    name: 'Hollow square bass {A}',
    kind: 'oneshot',
    description: 'A hollow square-wave bass note on {A}, woody, the filter easing shut behind it.',
    instrument: {
      deviceId: 'acid-bass',
      preset: 'Hollow square line',
      params: {
        wave: 1,
        cutoff: 500,
        resonance: 0.3,
        envMod: 0.4,
        decay: 0.7,
        accent: 0.5,
        slide: 0.1,
        sustain: 3,
        drive: 0.15,
        volume: -6,
      },
    },
    effects: [hall('Room', 0.1)],
    ...played(3, [[0, 1.8, 45, 0.65]], 0.3),
  }),

  // String bass: plucked electric, fretless and upright strings.
  sound({
    id: 'finger-bass-e',
    number: 216,
    name: 'Finger bass {E}',
    kind: 'oneshot',
    description: 'A low {E} on an electric bass played with a finger, warm, left to ring.',
    instrument: {
      deviceId: 'string-bass',
      preset: 'Warm fingers',
      params: {
        type: 0,
        touch: 0.3,
        position: 0.22,
        tone: 0.55,
        mute: 0,
        sustain: 6,
        release: 0.4,
        growl: 0.2,
        resonance: 0.35,
        volume: -6,
      },
    },
    effects: [hall('Room', 0.1)],
    ...played(4, [[0, 3.2, 28]], 0.4),
  }),
  sound({
    id: 'picked-bass-a',
    number: 217,
    name: 'Picked bass {A}',
    kind: 'oneshot',
    description:
      'An {A} on an electric bass struck with a pick near the bridge, bright with a click.',
    instrument: {
      deviceId: 'string-bass',
      preset: 'Bright pick',
      params: {
        type: 0,
        touch: 0.9,
        position: 0.11,
        tone: 0.9,
        mute: 0,
        sustain: 5,
        release: 0.3,
        growl: 0.1,
        resonance: 0.55,
        volume: -6,
      },
    },
    effects: [soften(18), hall('Room', 0.1)],
    ...played(3, [[0, 2.3, 45]], 0.3),
  }),
  sound({
    id: 'muted-bass-thud-g',
    number: 218,
    name: 'Muted bass thud {G}',
    kind: 'oneshot',
    description: 'A low {G} on an electric bass with the hand on the strings: a dull, short thud.',
    instrument: {
      deviceId: 'string-bass',
      preset: 'Muted thud',
      params: {
        type: 0,
        touch: 0.2,
        position: 0.35,
        tone: 0.3,
        mute: 0.55,
        sustain: 5,
        release: 0.1,
        growl: 0,
        resonance: 0.2,
        volume: 2.5,
      },
    },
    effects: [hold(8), hall('Room', 0.06)],
    ...played(2, [[0, 1, 31]], 0.2),
  }),
  sound({
    id: 'fretless-bloom-d',
    number: 219,
    name: 'Fretless bloom {D}',
    kind: 'oneshot',
    description: 'A {D} on a fretless bass that starts soft and sings open after the pluck.',
    instrument: {
      deviceId: 'string-bass',
      preset: 'Singing fretless',
      params: {
        type: 1,
        touch: 0.35,
        position: 0.2,
        tone: 0.6,
        mute: 0,
        sustain: 7,
        release: 0.5,
        growl: 0.8,
        resonance: 0.5,
        volume: -7.5,
      },
    },
    effects: [hall('Room', 0.12)],
    ...played(4, [[0, 3, 38]], 0.4),
  }),
  sound({
    id: 'upright-pluck-a',
    number: 220,
    name: 'Upright pluck {A}',
    kind: 'oneshot',
    description:
      'A low {A} on an upright bass plucked once, round and short, with the thump of its body.',
    instrument: {
      deviceId: 'string-bass',
      preset: 'Round upright',
      params: {
        type: 2,
        touch: 0.25,
        position: 0.3,
        tone: 0.45,
        mute: 0,
        sustain: 3,
        release: 0.15,
        growl: 0.2,
        resonance: 0.45,
        volume: -2,
      },
    },
    effects: [hold(11), hall('Room', 0.12)],
    ...played(2, [[0, 1.3, 33]], 0.2),
  }),
  sound({
    id: 'upright-ring-c',
    number: 221,
    name: 'Upright ring {C}',
    kind: 'oneshot',
    description: 'A {C} on an upright bass left to ring for seconds in its wooden body.',
    instrument: {
      deviceId: 'string-bass',
      preset: 'Long wooden ring',
      params: {
        type: 2,
        touch: 0.3,
        position: 0.25,
        tone: 0.5,
        mute: 0,
        sustain: 16,
        release: 1.2,
        growl: 0.3,
        resonance: 0.9,
        volume: -7.5,
      },
    },
    effects: [hold(9), hall('Room', 0.15)],
    ...played(6, [[0, 4.6, 36]], 0.5),
  }),
  sound({
    id: 'bass-octave-e',
    number: 222,
    name: 'Bass octave {E}',
    kind: 'oneshot',
    description:
      'An {E} and its octave on two strings of an electric bass, plucked together by a thumb at the neck.',
    instrument: {
      deviceId: 'string-bass',
      preset: 'Thumb at the neck',
      params: {
        type: 0,
        touch: 0.05,
        position: 0.45,
        tone: 0.4,
        mute: 0,
        sustain: 8,
        release: 0.5,
        growl: 0,
        resonance: 0.15,
        volume: -5.5,
      },
    },
    effects: [hall('Room', 0.1)],
    ...played(
      4,
      [
        [0, 3, 40],
        [0, 3, 52, 0.6],
      ],
      0.4,
    ),
  }),

  // Ladder bass: two oscillators and a sub through a four-pole filter.
  sound({
    id: 'thick-ladder-bass-a',
    number: 223,
    name: 'Thick ladder bass {A}',
    kind: 'oneshot',
    description:
      'Two detuned sawtooths on {A} over a sine an octave down: a thick bass note through a ladder filter.',
    instrument: {
      deviceId: 'ladder-bass',
      preset: 'Sequence bass',
      params: {
        wave: 0,
        beat: 12,
        sub: 0.5,
        cutoff: 400,
        emphasis: 0.15,
        contour: 0.5,
        decay: 2.5,
        drive: 0.5,
        glide: 0,
        volume: -9,
      },
    },
    effects: [hall('Room', 0.1)],
    ...played(3, [[0, 2.4, 45]], 0.3),
  }),
  sound({
    id: 'slide-bass-f',
    number: 224,
    name: 'Slide bass {F}',
    kind: 'oneshot',
    description:
      'A ladder-filter bass that is struck on {C} and slides down a fifth into {F}, where it rings out.',
    // Both keys go down together and the one written last sounds, with no glide and one strike. When it comes
    // up 80 ms later the pitch glides to the key still held. One moment, so a variant's speed cannot part them.
    instrument: {
      deviceId: 'ladder-bass',
      preset: 'Rubber pluck',
      params: {
        wave: 0,
        beat: 6,
        sub: 0,
        cutoff: 350,
        emphasis: 0.3,
        contour: 0.5,
        decay: 2.5,
        drive: 0.5,
        glide: 0.2,
        volume: -9,
      },
    },
    effects: [hall('Room', 0.1)],
    ...played(
      3,
      [
        [0, 2.3, 41],
        [0, 0.08, 48],
      ],
      0.3,
    ),
  }),

  // Held tones: each loops. A steady one is tuned to whole cycles and given a quarter turn, or three where
  // its partials can make a taller wave (see `threeQuarterTurn`).
  sound({
    id: 'pure-sub-a',
    number: 225,
    name: 'Pure sub {A}',
    kind: 'drone',
    description: 'A held sine bass on a low {A} with a trace of its octave, perfectly still.',
    instrument: {
      deviceId: 'sub-bass',
      preset: 'Pure sine',
      params: {
        shape: 0,
        harmonics: 0.12,
        drop: 0,
        fall: 40,
        attack: 0.02,
        decay: 20,
        release: 0.6,
        drive: 0,
        glide: 0,
        volume: -9,
      },
    },
    effects: [quarterTurn(8)],
    ...looped(8, 1, 1, [33]),
    tuning: 'whole-cycles',
  }),
  sound({
    id: 'harmonic-sub-c',
    number: 226,
    name: 'Harmonic sub {C}',
    kind: 'drone',
    description:
      'A held sine bass on {C} with its octave and the fifth above added, for small speakers.',
    instrument: {
      deviceId: 'sub-bass',
      preset: 'Pedal tone',
      params: {
        shape: 0.2,
        harmonics: 1,
        drop: 0,
        fall: 40,
        attack: 0.015,
        decay: 20,
        release: 0.12,
        drive: 0.1,
        glide: 0,
        volume: -11,
      },
    },
    effects: [hall('Room', 0.1), threeQuarterTurn(8)],
    ...looped(8, 1, 1, [36]),
    tuning: 'whole-cycles',
  }),
  sound({
    id: 'square-hum-g',
    number: 227,
    name: 'Square hum {G}',
    kind: 'drone',
    description: 'A held square-wave bass hum on {G} behind a filter, hollow and steady.',
    instrument: {
      deviceId: 'acid-bass',
      preset: 'Held sub tone',
      params: {
        wave: 1,
        cutoff: 800,
        resonance: 0.2,
        envMod: 0,
        decay: 2,
        accent: 0,
        slide: 0.2,
        sustain: 20,
        drive: 0,
        volume: -6.5,
      },
    },
    effects: [hall('Room', 0.1), threeQuarterTurn(8)],
    ...looped(8, 1, 1, [[43, 0.6]]),
    tuning: 'whole-cycles',
  }),
  sound({
    id: 'fm-slow-growl-a',
    number: 228,
    name: 'Slow growl {A}',
    kind: 'drone',
    description:
      'A held FM bass on a low {A} whose buzzing growl opens and closes once in sixteen seconds.',
    instrument: {
      deviceId: 'fm-bass',
      preset: 'Held hum',
      params: {
        ratio: 1,
        depth: 0.55,
        bite: 2.5,
        body: 0.8,
        feedback: 0.7,
        sub: 0,
        decay: 20,
        release: 2.5,
        glide: 0,
        volume: -11.5,
      },
    },
    effects: [
      {
        deviceId: 'auto-filter',
        params: {
          type: 0,
          slope: 1,
          cutoffHz: 350,
          resonance: 1,
          driveDb: 0,
          envAmount: 0,
          lfoAmount: 60,
          lfoRateHz: 0.0625,
          lfoShape: 0,
          mix: 1,
        },
      },
      quarterTurn(16),
    ],
    ...looped(16, 4, 2, [33]),
    tuning: 'whole-cycles',
  }),
  sound({
    id: 'dark-bass-tone-f',
    number: 229,
    name: 'Dark bass tone {F}',
    kind: 'drone',
    description: 'A held sawtooth bass on {F} behind a low filter: dark, round and still.',
    instrument: {
      deviceId: 'acid-bass',
      preset: 'Soft dark line',
      params: {
        wave: 0,
        cutoff: 280,
        resonance: 0.15,
        envMod: 0,
        decay: 2,
        accent: 0,
        slide: 0.15,
        sustain: 20,
        drive: 0.1,
        volume: -7,
      },
    },
    effects: [hall('Room', 0.12), threeQuarterTurn(8)],
    ...looped(8, 1, 1, [[41, 0.6]]),
    tuning: 'whole-cycles',
  }),
  sound({
    id: 'beating-bass-d',
    number: 230,
    name: 'Beating bass {D}',
    kind: 'pad',
    description:
      'Two sawtooth bass oscillators on {D} three cents apart: the low tone slowly fades and returns as they beat.',
    instrument: {
      deviceId: 'ladder-bass',
      preset: 'Pedal drone',
      params: {
        wave: 0,
        beat: 2.945,
        sub: 0,
        cutoff: 300,
        emphasis: 0.1,
        contour: 0,
        decay: 10,
        drive: 0.2,
        glide: 0,
        volume: -9,
      },
    },
    effects: [hall('Room', 0.12), threeQuarterTurn(8)],
    ...looped(8, 2, 2, [38]),
    tuning: 'whole-cycles',
  }),
  sound({
    id: 'resonant-bass-tone-a',
    number: 231,
    name: 'Resonant bass tone {A}',
    kind: 'drone',
    description:
      'A held sawtooth bass on {A} with the filter ringing in its lower overtones: nasal and still.',
    instrument: {
      deviceId: 'acid-bass',
      preset: 'Long glide drone',
      params: {
        wave: 0,
        cutoff: 330,
        resonance: 0.55,
        envMod: 0,
        decay: 2,
        accent: 0,
        slide: 0.2,
        sustain: 20,
        drive: 0.1,
        volume: -9,
      },
    },
    effects: [hall('Room', 0.12), threeQuarterTurn(8)],
    ...looped(8, 1, 1, [[45, 0.6]]),
    tuning: 'whole-cycles',
  }),
  sound({
    id: 'breathing-sub-e',
    number: 232,
    name: 'Breathing sub {E}',
    kind: 'pad',
    description:
      'A held sine bass on {E} under its octave and fifth, breathing in and out once in eight seconds.',
    instrument: {
      deviceId: 'sub-bass',
      preset: 'Dark drone',
      params: {
        shape: 0.25,
        harmonics: 0.85,
        drop: 0,
        fall: 40,
        attack: 0.05,
        decay: 20,
        release: 1,
        drive: 0.1,
        glide: 0,
        volume: -9,
      },
    },
    effects: [breathe(0.125, 0.9), hall('Room', 0.12), quarterTurn(8)],
    ...looped(8, 1, 1, [40]),
    tuning: 'whole-cycles',
  }),
]
