// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Reverse Delay, shared with
// src/dsp/devices/reverse-delay.gen.ts:
//    0  time: 50..4000 ms, default 600
//    1  feedback: 0..0.95, default 0.35
//    2  pitch: 0 Normal, 1 Octave up, 2 Octave down, default 0
//    3  smooth: 0..1, default 0.35
//    4  tone: 500..16000 Hz, default 6000
//    5  spread: 0..1, default 0.5
//    6  mix: 0..1, default 0.4
//    7  lowCut: 20..800 Hz, default 100

#pragma once

namespace livemix {
namespace reverse_delay {

enum Param : int {
  kTime = 0,
  kFeedback = 1,
  kPitch = 2,
  kSmooth = 3,
  kTone = 4,
  kSpread = 5,
  kMix = 6,
  kLowCut = 7,
  kNumParams = 8,
};

inline constexpr float kParamMin[kNumParams] = {50.0f, 0.0f, 0.0f, 0.0f, 500.0f, 0.0f, 0.0f, 20.0f};
inline constexpr float kParamMax[kNumParams] = {4000.0f, 0.95f, 2.0f, 1.0f, 16000.0f, 1.0f, 1.0f, 800.0f};
inline constexpr float kParamDefault[kNumParams] = {600.0f, 0.35f, 0.0f, 0.35f, 6000.0f, 0.5f, 0.4f, 100.0f};

}  // namespace reverse_delay
}  // namespace livemix
