import { type FactoryPreset } from '../types'

// Every instrument parameter is written out in every preset: the device
// preset named is the nearest starting point, and nothing here leans on its
// values.

export const ACID_BASS_PRESETS: readonly FactoryPreset[] = [
  {
    id: 'acid-held-square-sub',
    name: 'Held square acid sub',
    category: 'bass',
    description:
      'A square closed down to its fundamental that holds while the key is down, with a transformer thickening the harmonics just above it.',
    instrument: {
      deviceId: 'acid-bass',
      preset: 'Held sub tone',
      params: {
        wave: 1,
        cutoff: 100,
        resonance: 0.2,
        envMod: 0.08,
        decay: 2,
        accent: 0,
        slide: 0.25,
        sustain: 20,
        drive: 0,
        volume: -4,
      },
    },
    effects: [{ deviceId: 'analog-drive', preset: 'Low warmth', params: { output: -9.5 } }],
  },
  {
    id: 'acid-swelling-saw-sub',
    name: 'Swelling acid sub',
    category: 'bass',
    description:
      'A saw closed down to a sub with its strike taken off, so each held note swells in over a few tenths of a second, warmed by a triode.',
    instrument: {
      deviceId: 'acid-bass',
      preset: 'Held sub tone',
      params: {
        wave: 0,
        cutoff: 130,
        resonance: 0.25,
        envMod: 0.08,
        decay: 2,
        accent: 0.2,
        slide: 0.2,
        sustain: 20,
        drive: 0,
        volume: -2,
      },
    },
    effects: [
      { deviceId: 'swell', preset: 'Slow attack', params: { attack: 450 } },
      { deviceId: 'analog-drive', preset: 'Triode glow', params: { output: -6.5 } },
    ],
  },
  {
    id: 'acid-deep-square-sweep',
    name: 'Deep acid square sweep',
    category: 'bass',
    description:
      'A long square note under a resonant filter that sinks three octaves in six seconds, with a short halo of reverb above 250 Hz.',
    instrument: {
      deviceId: 'acid-bass',
      preset: 'Deep slow sweep',
      params: {
        wave: 1,
        cutoff: 55,
        resonance: 0.6,
        envMod: 0.6,
        decay: 6,
        accent: 0,
        slide: 0.4,
        sustain: 15,
        drive: 0,
        volume: -7,
      },
    },
    effects: [{ deviceId: 'shaped-reverb', preset: 'Short halo', params: { lowCut: 250 } }],
  },
  {
    id: 'acid-slow-closing-saw',
    name: 'Slow closing acid saw',
    category: 'bass',
    description:
      'A held saw whose filter opens on each note and closes over two and a half seconds, in a small dark room thinned below 250 Hz.',
    instrument: {
      deviceId: 'acid-bass',
      preset: 'Slow closing tone',
      params: {
        wave: 0,
        cutoff: 70,
        resonance: 0.4,
        envMod: 0.5,
        decay: 2.5,
        accent: 0,
        slide: 0.3,
        sustain: 20,
        drive: 0,
        volume: -8.5,
      },
    },
    effects: [
      { deviceId: 'expanse', preset: 'Small dark room', params: { lowCut: 250, mix: 0.2 } },
    ],
  },
  {
    id: 'acid-long-glide-line',
    name: 'Long glide acid line',
    category: 'bass',
    description:
      'A held saw with a nasal peak at 600 Hz that takes a full second to slide to a key pressed over the last, widened above 300 Hz.',
    instrument: {
      deviceId: 'acid-bass',
      preset: 'Long glide drone',
      params: {
        wave: 0,
        cutoff: 600,
        resonance: 0.55,
        envMod: 0.05,
        decay: 4,
        accent: 0.2,
        slide: 1,
        sustain: 20,
        drive: 0.106,
        volume: -8,
      },
    },
    effects: [{ deviceId: 'stereo-detune', preset: 'Soft halo', params: { focus: 300 } }],
  },
  {
    id: 'acid-soft-dark-line',
    name: 'Soft dark acid line',
    category: 'bass',
    description:
      'A dark saw line with only a small filter sweep and almost no resonance, on cassette tape, with a trace of a tight chamber.',
    instrument: {
      deviceId: 'acid-bass',
      preset: 'Soft dark line',
      params: {
        wave: 0,
        cutoff: 110,
        resonance: 0.15,
        envMod: 0.2,
        decay: 0.8,
        accent: 0.25,
        slide: 0.15,
        sustain: 5,
        drive: 0,
        volume: -1,
      },
    },
    effects: [
      { deviceId: 'tape', preset: 'Under a blanket', params: { hiss: 0, output: -6 } },
      { deviceId: 'hall-reverb', preset: 'Tight chamber', params: { mix: 0.12 } },
    ],
  },
  {
    id: 'acid-quiet-square-pulse',
    name: 'Quiet acid pulse',
    category: 'bass',
    description:
      'A soft square note that fades in about a second, with ripples of reverb above 300 Hz pulsing on behind it.',
    instrument: {
      deviceId: 'acid-bass',
      preset: 'Quiet pulse',
      params: {
        wave: 1,
        cutoff: 220,
        resonance: 0.3,
        envMod: 0.15,
        decay: 0.3,
        accent: 0.15,
        slide: 0.12,
        sustain: 1.2,
        drive: 0,
        volume: -1,
      },
    },
    effects: [{ deviceId: 'shaped-reverb', preset: 'Ripples', params: { lowCut: 300, mix: 0.3 } }],
  },
  {
    id: 'acid-muted-tape-thump',
    name: 'Muted acid thump',
    category: 'bass',
    description:
      'A dark thump whose filter shuts in under a tenth of a second, on cassette with the head bump up, its strike held by a limiter.',
    instrument: {
      deviceId: 'acid-bass',
      preset: 'Muted thump',
      params: {
        wave: 0,
        cutoff: 65,
        resonance: 0.1,
        envMod: 0.6,
        decay: 0.08,
        accent: 0.5,
        slide: 0.03,
        sustain: 0.8,
        drive: 0,
        volume: 0,
      },
    },
    effects: [
      { deviceId: 'tape', preset: 'Warm thump', params: { hiss: 0 } },
      { deviceId: 'ambient-limiter', params: { ceiling: -10, gain: 4, release: 0.2, ride: 0 } },
    ],
  },
  {
    id: 'acid-dub-weight',
    name: 'Acid dub weight',
    category: 'bass',
    description:
      'A dark resonant square that yawns shut on each note and fades, driven into a transformer, with a mono amp spring behind it.',
    instrument: {
      deviceId: 'acid-bass',
      preset: 'Dub weight',
      params: {
        wave: 1,
        cutoff: 90,
        resonance: 0.5,
        envMod: 0.3,
        decay: 0.25,
        accent: 0.4,
        slide: 0.18,
        sustain: 3,
        drive: 0.452,
        volume: -6,
      },
    },
    effects: [
      { deviceId: 'analog-drive', preset: 'Iron lows' },
      { deviceId: 'spring-reverb', preset: 'Dark amp spring', params: { mix: 0.3 } },
    ],
  },
  {
    id: 'acid-rubber-slides',
    name: 'Rubber slide acid bass',
    category: 'bass',
    description:
      'A resonant saw that takes half a second to bend between overlapping keys, made round and heavy by a tape preamp.',
    instrument: {
      deviceId: 'acid-bass',
      preset: 'Rubber slides',
      params: {
        wave: 0,
        cutoff: 160,
        resonance: 0.78,
        envMod: 0.42,
        decay: 0.6,
        accent: 0.5,
        slide: 0.5,
        sustain: 8,
        drive: 0.106,
        volume: -16.5,
      },
    },
    effects: [{ deviceId: 'analog-drive', preset: 'Tape weight' }],
  },
  {
    id: 'acid-hollow-phased-square',
    name: 'Hollow phased acid line',
    category: 'bass',
    description:
      'An open, woody square line with a slow four-stage phaser turning in its upper harmonics.',
    instrument: {
      deviceId: 'acid-bass',
      preset: 'Hollow square line',
      params: {
        wave: 1,
        cutoff: 700,
        resonance: 0.3,
        envMod: 0.35,
        decay: 0.7,
        accent: 0.5,
        slide: 0.1,
        sustain: 5,
        drive: 0.078,
        volume: -6,
      },
    },
    effects: [{ deviceId: 'phaser', preset: 'Bass safe', params: { stereo: 45 } }],
  },
  {
    id: 'acid-console-line',
    name: 'Console acid line',
    category: 'bass',
    description:
      'The plain acid line: a resonant saw whose filter snaps shut in a third of a second, pushed through a console channel.',
    instrument: {
      deviceId: 'acid-bass',
      preset: 'Acid line',
      params: {
        wave: 0,
        cutoff: 280,
        resonance: 0.7,
        envMod: 0.55,
        decay: 0.35,
        accent: 0.6,
        slide: 0.12,
        sustain: 4,
        drive: 0.134,
        volume: -5.5,
      },
    },
    effects: [{ deviceId: 'analog-drive', preset: 'Console' }],
  },
  {
    id: 'acid-open-saw-chorus',
    name: 'Open acid saw chorus',
    category: 'bass',
    description:
      'A bright, buzzing saw with the filter open at 2.2 kHz, with a two-voice chorus on everything above 400 Hz.',
    instrument: {
      deviceId: 'acid-bass',
      preset: 'Bright open saw',
      params: {
        wave: 0,
        cutoff: 2200,
        resonance: 0.2,
        envMod: 0.3,
        decay: 0.6,
        accent: 0.5,
        slide: 0.06,
        sustain: 4,
        drive: 0.163,
        volume: -2,
      },
    },
    effects: [{ deviceId: 'chorus', preset: 'Classic chorus', params: { hpHz: 400, mix: 0.3 } }],
  },
  {
    id: 'acid-driven-growl',
    name: 'Driven acid growl',
    category: 'bass',
    description:
      'A half-open saw with the instrument drive near the top, into a triode fuzz that holds every note up as it fades.',
    instrument: {
      deviceId: 'acid-bass',
      preset: 'Driven growl',
      params: {
        wave: 0,
        cutoff: 300,
        resonance: 0.4,
        envMod: 0.5,
        decay: 0.9,
        accent: 0.6,
        slide: 0.1,
        sustain: 4,
        drive: 0.684,
        volume: -12.5,
      },
    },
    effects: [
      {
        deviceId: 'analog-drive',
        preset: 'Dark fuzz',
        params: { tone: -0.3, highCut: 5000, output: -4 },
      },
    ],
  },
  {
    id: 'acid-wet-squelch',
    name: 'Wet acid squelch',
    category: 'bass',
    description:
      'High resonance and a deep, quick filter sweep make every note squelch; a limiter holds the strikes, in a small box.',
    instrument: {
      deviceId: 'acid-bass',
      preset: 'Wet squelch',
      params: {
        wave: 0,
        cutoff: 150,
        resonance: 0.88,
        envMod: 0.85,
        decay: 0.2,
        accent: 0.9,
        slide: 0.07,
        sustain: 2,
        drive: 0.051,
        volume: -4.5,
      },
    },
    effects: [
      { deviceId: 'ambient-limiter', params: { ceiling: -12, gain: 1, release: 0.2, ride: 0 } },
      { deviceId: 'expanse', preset: 'Small box', params: { lowCut: 400, mix: 0.15 } },
    ],
  },
  {
    id: 'acid-resonant-scream',
    name: 'Screaming acid line',
    category: 'bass',
    description:
      'Resonance near its limit, full accent and the instrument drive up, then a pentode: a line that whistles and tears.',
    instrument: {
      deviceId: 'acid-bass',
      preset: 'Resonant scream',
      params: {
        wave: 0,
        cutoff: 600,
        resonance: 0.95,
        envMod: 0.75,
        decay: 0.5,
        accent: 1,
        slide: 0.08,
        sustain: 3,
        drive: 0.553,
        volume: -9.5,
      },
    },
    effects: [{ deviceId: 'analog-drive', preset: 'Bite', params: { lowCut: 20 } }],
  },
  {
    id: 'acid-short-hard-pluck',
    name: 'Short hard acid pluck',
    category: 'bass',
    description:
      'A driven pluck that is gone in a third of a second whatever the key does, squared off by a limiter, in a small box.',
    instrument: {
      deviceId: 'acid-bass',
      preset: 'Short pluck',
      params: {
        wave: 0,
        cutoff: 220,
        resonance: 0.5,
        envMod: 0.7,
        decay: 0.12,
        accent: 0.6,
        slide: 0.05,
        sustain: 0.3,
        drive: 0.368,
        volume: 3,
      },
    },
    effects: [
      { deviceId: 'ambient-limiter', params: { ceiling: -9, gain: 8, release: 0.2, ride: 0 } },
      { deviceId: 'expanse', preset: 'Small box', params: { lowCut: 400, mix: 0.25 } },
    ],
  },
  {
    id: 'acid-far-closing-drone',
    name: 'Far closing acid drone',
    category: 'drone',
    description:
      'One held saw note that opens wide and darkens over ten seconds: a far-off drone in a long reverb.',
    instrument: {
      deviceId: 'acid-bass',
      preset: 'Slow closing tone',
      params: {
        wave: 0,
        cutoff: 80,
        resonance: 0.45,
        envMod: 0.7,
        decay: 10,
        accent: 0,
        slide: 0.3,
        sustain: 20,
        drive: 0,
        volume: -8,
      },
    },
    effects: [
      {
        deviceId: 'expanse',
        preset: 'Open space',
        params: { lowCut: 300, decay: 8, width: 0.7, mix: 0.35 },
      },
    ],
  },
  {
    id: 'acid-gliding-lead',
    name: 'Gliding acid lead',
    category: 'keys',
    description:
      'A driven, half-open resonant saw lead that holds and glides between overlapping keys, with tape repeats and a small plate.',
    instrument: {
      deviceId: 'acid-bass',
      preset: 'Bright open saw',
      params: {
        wave: 0,
        cutoff: 900,
        resonance: 0.55,
        envMod: 0.4,
        decay: 1.5,
        accent: 0.5,
        slide: 0.15,
        sustain: 20,
        drive: 0.368,
        volume: -8,
      },
    },
    effects: [
      { deviceId: 'tape-echo', preset: 'Warm repeats', params: { mix: 0.25 } },
      { deviceId: 'plate-reverb', preset: 'Small plate', params: { mix: 0.2 } },
    ],
  },
  {
    id: 'acid-blip-echoes',
    name: 'Acid blip echoes',
    category: 'plucked',
    description:
      'Resonant blips a fifth of a second long, squared off by a limiter and bounced by a dotted tape echo.',
    instrument: {
      deviceId: 'acid-bass',
      preset: 'Short pluck',
      params: {
        wave: 0,
        cutoff: 300,
        resonance: 0.8,
        envMod: 0.7,
        decay: 0.12,
        accent: 0.6,
        slide: 0.05,
        sustain: 0.2,
        drive: 0.163,
        volume: 3,
      },
    },
    effects: [
      { deviceId: 'ambient-limiter', params: { ceiling: -9, gain: 11, release: 0.2, ride: 0 } },
      { deviceId: 'tape-echo', preset: 'Dotted bounce', params: { time: 375, mix: 0.35 } },
    ],
  },
]
