import { type FactoryPreset } from '../types'

export const ACOUSTIC_GUITAR_PRESETS: readonly FactoryPreset[] = [
  {
    id: 'steel-fingerstyle-room',
    name: 'Steel fingerstyle room',
    category: 'plucked',
    description: 'A steel-string guitar picked with the fingers, close, in a small wooden room.',
    instrument: {
      deviceId: 'acoustic-guitar',
      preset: 'Steel fingerstyle',
      params: { volume: -4 },
    },
    effects: [{ deviceId: 'fdn-reverb', preset: 'Room', params: { mix: 0.3 } }],
    preview: 'keys',
  },
  {
    id: 'nylon-at-dusk',
    name: 'Nylon at dusk',
    category: 'plucked',
    description:
      'A few round nylon notes played with the pad of the finger, on worn tape, left in a very large space.',
    instrument: { deviceId: 'acoustic-guitar', preset: 'Nylon dusk', params: { volume: -3 } },
    effects: [
      { deviceId: 'tape', preset: 'Quarter inch' },
      { deviceId: 'expanse', preset: 'Open space', params: { mix: 0.35 } },
    ],
    preview: 'keys',
  },
  {
    id: 'twelve-string-hall',
    name: 'Twelve string hall',
    category: 'plucked',
    description:
      'Twelve strings in octave and unison pairs, strummed with a pick and heard in a hall.',
    instrument: { deviceId: 'acoustic-guitar', preset: 'Twelve string', params: { volume: -5 } },
    effects: [{ deviceId: 'hall-reverb', preset: 'Hall', params: { mix: 0.4 } }],
    preview: 'keys',
  },
  {
    id: 'open-strings-ringing',
    name: 'Open strings ringing',
    category: 'plucked',
    description:
      'Steel strings left to ring into each other, with tuned strings that answer and a quiet room behind.',
    instrument: { deviceId: 'acoustic-guitar', preset: 'Let ring', params: { volume: -6 } },
    effects: [
      { deviceId: 'sympathetic', preset: 'Long ring', params: { mix: 0.3 } },
      { deviceId: 'bloom-reverb', preset: 'Still room', params: { mix: 0.25 } },
    ],
    preview: 'keys',
  },
  {
    id: 'muted-acoustic-echo',
    name: 'Muted acoustic echo',
    category: 'plucked',
    description:
      'Short muted plucks near the bridge that a three-head tape echo turns into a pattern, with a spring behind.',
    instrument: { deviceId: 'acoustic-guitar', preset: 'Muted pattern', params: { volume: 0 } },
    effects: [
      { deviceId: 'tape-echo', preset: 'Three heads', params: { time: 375, mix: 0.4 } },
      { deviceId: 'spring-reverb', preset: 'Two spring tank', params: { mix: 0.2 } },
    ],
    preview: 'keys',
  },
  {
    id: 'nylon-parlour-plate',
    name: 'Nylon parlour plate',
    category: 'plucked',
    description:
      'A nylon-string guitar played with the fingertips, clear and close, with a short plate behind it.',
    instrument: {
      deviceId: 'acoustic-guitar',
      preset: 'Nylon dusk',
      params: {
        body: 0.85,
        position: 0.22,
        nail: 0.45,
        sustain: 4.5,
        release: 1.2,
        tone: 0.6,
        shimmer: 0.2,
        strum: 12,
        volume: 2,
      },
    },
    effects: [{ deviceId: 'plate-reverb', preset: 'Small plate', params: { mix: 0.22 } }],
  },
  {
    id: 'flatpick-chamber',
    name: 'Flatpick chamber',
    category: 'plucked',
    description:
      'A full steel-string chord strummed with a hard pick, bright with a click on each string, in a tight chamber.',
    instrument: {
      deviceId: 'acoustic-guitar',
      preset: 'Steel fingerstyle',
      params: {
        body: 0.9,
        position: 0.2,
        nail: 0.9,
        sustain: 11,
        release: 2,
        tone: 0.7,
        strum: 28,
      },
    },
    effects: [{ deviceId: 'hall-reverb', preset: 'Tight chamber', params: { mix: 0.22 } }],
    preview: 'chord',
  },
  {
    id: 'twelve-under-thumb',
    name: 'Twelve under thumb',
    category: 'plucked',
    description:
      'A twelve-string brushed with the thumb over the soundhole, round and soft, in a small room.',
    instrument: {
      deviceId: 'acoustic-guitar',
      preset: 'Twelve string',
      params: {
        body: 0.95,
        position: 0.36,
        nail: 0.05,
        sustain: 7,
        release: 3,
        tone: 0.42,
        shimmer: 0.35,
        strum: 60,
        volume: -7,
      },
    },
    effects: [{ deviceId: 'ether-reverb', preset: 'Room', params: { mix: 0.28 } }],
    preview: 'chord',
  },
  {
    id: 'picked-nylon-close',
    name: 'Picked nylon close',
    category: 'plucked',
    description:
      'Nylon strings played with a hard pick near the bridge, snappy and short, through a console preamp with a little ambience.',
    instrument: {
      deviceId: 'acoustic-guitar',
      preset: 'Nylon dusk',
      params: {
        body: 0.7,
        position: 0.15,
        nail: 0.95,
        sustain: 3,
        release: 0.5,
        tone: 0.72,
        shimmer: 0.15,
        strum: 8,
        volume: -1,
      },
    },
    effects: [
      { deviceId: 'analog-drive', preset: 'Console', params: { output: 1.5 } },
      { deviceId: 'fdn-reverb', preset: 'Short ambience', params: { mix: 0.2 } },
    ],
  },
  {
    id: 'bare-nylon-harp',
    name: 'Bare nylon harp',
    category: 'plucked',
    description:
      'Nylon strings with the wooden body taken away, rolled slowly from low to high like a harp, in an airy hall.',
    instrument: {
      deviceId: 'acoustic-guitar',
      preset: 'Nylon dusk',
      params: {
        body: 0.05,
        position: 0.4,
        nail: 0.35,
        sustain: 9,
        release: 6,
        tone: 0.7,
        shimmer: 0.1,
        strum: 120,
        volume: -11,
      },
    },
    effects: [{ deviceId: 'hall-reverb', preset: 'Airy tail', params: { mix: 0.3 } }],
    preview: 'chord',
  },
  {
    id: 'glassy-bridge-steel',
    name: 'Glassy bridge steel',
    category: 'plucked',
    description:
      'Steel strings picked right at the bridge with almost no body, thin and glassy, lightly driven and chorused in a bright plate.',
    instrument: {
      deviceId: 'acoustic-guitar',
      preset: 'Steel fingerstyle',
      params: {
        body: 0.15,
        position: 0.06,
        nail: 1,
        sustain: 6,
        release: 3,
        tone: 1,
        shimmer: 0.5,
        strum: 6,
        volume: 0,
      },
    },
    effects: [
      { deviceId: 'analog-drive', preset: 'Sheen', params: { drive: 0.45, output: 0.5 } },
      { deviceId: 'chorus', preset: 'Guitar shimmer', params: { mix: 0.35 } },
      { deviceId: 'plate-reverb', preset: 'Bright plate', params: { mix: 0.3 } },
    ],
  },
  {
    id: 'dark-low-nylon',
    name: 'Dark low nylon',
    category: 'plucked',
    description:
      'Low nylon notes under the thumb with the tone right down, all wood and thump, warmed by a transformer in a dark hall.',
    instrument: {
      deviceId: 'acoustic-guitar',
      preset: 'Soft thumb',
      params: {
        type: 1,
        position: 0.4,
        sustain: 8,
        release: 4,
        tone: 0.08,
        shimmer: 0.15,
        strum: 40,
        volume: -1,
      },
    },
    effects: [
      { deviceId: 'analog-drive', preset: 'Low warmth' },
      { deviceId: 'hall-reverb', preset: 'Dark hall', params: { mix: 0.3 } },
    ],
    preview: 'low',
  },
  {
    id: 'beating-steel-chord',
    name: 'Beating steel chord',
    category: 'plucked',
    description:
      'A strummed steel chord left to ring, every string beating against itself, in a long three-spring tank.',
    instrument: {
      deviceId: 'acoustic-guitar',
      preset: 'Let ring',
      params: {
        body: 0.7,
        position: 0.28,
        nail: 0.25,
        sustain: 12,
        release: 10,
        tone: 0.55,
        shimmer: 1.5,
        strum: 80,
      },
    },
    effects: [{ deviceId: 'spring-reverb', preset: 'Long three spring', params: { mix: 0.3 } }],
    preview: 'chord',
  },
  {
    id: 'muted-twelve-drip',
    name: 'Muted twelve drip',
    category: 'plucked',
    description:
      'Twelve strings damped with the hand and picked at the bridge, each short note splashing in a slack spring.',
    instrument: {
      deviceId: 'acoustic-guitar',
      preset: 'Muted pattern',
      params: {
        type: 2,
        body: 0.5,
        position: 0.08,
        nail: 0.7,
        sustain: 0.7,
        release: 0.07,
        tone: 0.6,
        shimmer: 0.8,
        volume: 2,
      },
    },
    effects: [
      { deviceId: 'analog-drive', preset: 'Console', params: { output: 3 } },
      { deviceId: 'spring-reverb', preset: 'Surf drip', params: { mix: 0.33, width: 0.7 } },
    ],
  },
  {
    id: 'rotary-steel-string',
    name: 'Rotary steel string',
    category: 'plucked',
    description:
      'Soft fingerpicked steel strings played through a fast rotary speaker, the highs spinning from side to side, in a room.',
    instrument: {
      deviceId: 'acoustic-guitar',
      preset: 'Steel fingerstyle',
      params: {
        body: 0.85,
        position: 0.28,
        nail: 0.35,
        sustain: 7,
        release: 3,
        tone: 0.5,
        strum: 35,
        volume: 0.5,
      },
    },
    effects: [
      { deviceId: 'rotary', preset: 'Guitar swirl', params: { mix: 1 } },
      { deviceId: 'hall-reverb', preset: 'Room' },
    ],
  },
  {
    id: 'acoustic-through-amp',
    name: 'Acoustic through amp',
    category: 'plucked',
    description:
      'A thin steel string picked hard through a driven combo amplifier, pulsing with tremolo, with a dark spring behind.',
    instrument: {
      deviceId: 'acoustic-guitar',
      preset: 'Steel fingerstyle',
      params: {
        body: 0.3,
        position: 0.12,
        nail: 0.9,
        sustain: 4,
        release: 0.8,
        tone: 0.5,
        strum: 20,
        volume: 3,
      },
    },
    effects: [
      { deviceId: 're-amp', preset: 'Combo in a room', params: { drive: 0.55, output: -4.5 } },
      { deviceId: 'tremolo', preset: 'Amp tremolo', params: { depth: 0.45 } },
      { deviceId: 'spring-reverb', preset: 'Dark amp spring' },
    ],
  },
  {
    id: 'acoustic-music-box',
    name: 'Acoustic music box',
    category: 'bell',
    description:
      'A bare steel string picked hard at the bridge and moved up an octave or two, small and bright like a music box.',
    instrument: {
      deviceId: 'acoustic-guitar',
      preset: 'Steel fingerstyle',
      params: {
        body: 0,
        position: 0.06,
        nail: 1,
        sustain: 1.8,
        release: 1.2,
        tone: 0.9,
        shimmer: 0,
        strum: 0,
        volume: 0,
      },
    },
    effects: [
      { deviceId: 'octaves', preset: 'High voice alone', params: { dry: 0.2, up2: 0.25 } },
      { deviceId: 'analog-drive', preset: 'Console', params: { output: 1 } },
      { deviceId: 'ether-reverb', preset: 'Bright chamber', params: { mix: 0.25 } },
    ],
  },
  {
    id: 'twelve-string-choir',
    name: 'Twelve string choir',
    category: 'plucked',
    description:
      'A twelve-string chord strummed slowly, its pairs well out of tune, in a hall that sings ah back.',
    instrument: {
      deviceId: 'acoustic-guitar',
      preset: 'Twelve string',
      params: {
        position: 0.2,
        nail: 0.3,
        sustain: 10,
        release: 7,
        tone: 0.55,
        shimmer: 1.1,
        strum: 110,
        volume: -5.5,
      },
    },
    effects: [{ deviceId: 'vowel-reverb', preset: 'Choir of ah', params: { mix: 0.45 } }],
    preview: 'chord',
  },
  {
    id: 'shortwave-nylon',
    name: 'Shortwave nylon',
    category: 'plucked',
    description:
      'A nylon guitar heard over a shortwave radio at night, thin and fading in and out over quiet static, in a dark plate.',
    instrument: {
      deviceId: 'acoustic-guitar',
      preset: 'Nylon dusk',
      params: {
        body: 0.6,
        position: 0.14,
        nail: 0.5,
        sustain: 5,
        release: 2,
        tone: 0.55,
        strum: 15,
        volume: 4.5,
      },
    },
    effects: [
      {
        deviceId: 'radio',
        preset: 'Night shortwave',
        params: { static: 0.08, fading: 0.45, interference: 0 },
      },
      { deviceId: 'plate-reverb', preset: 'Dark plate', params: { mix: 0.25 } },
    ],
  },
  {
    id: 'steel-across-valley',
    name: 'Steel across valley',
    category: 'plucked',
    description:
      'A strummed steel-string heard from far off, its top and bottom thinned, lost in a ten second open space.',
    instrument: {
      deviceId: 'acoustic-guitar',
      preset: 'Steel fingerstyle',
      params: {
        body: 0.5,
        position: 0.24,
        nail: 0.7,
        sustain: 8,
        release: 5,
        tone: 0.5,
        strum: 45,
        volume: -3,
      },
    },
    effects: [
      { deviceId: 'ambient-eq', preset: 'Distant' },
      { deviceId: 'fdn-reverb', preset: 'Open valley', params: { mix: 0.7 } },
    ],
    preview: 'chord',
  },
]
