import { type FactoryPreset } from '../types'

export const CHOIR_PRESETS: readonly FactoryPreset[] = [
  {
    id: 'worn-tape-choir',
    name: 'Worn tape choir',
    category: 'voice',
    description: 'An open ah that speaks quickly, played back from a cassette with wow and hiss.',
    instrument: {
      deviceId: 'choir',
      preset: 'Airport ah',
      params: {
        motion: 0.15,
        vibrato: 14,
        attack: 0.25,
        release: 1.6,
        tone: 4200,
        width: 0.6,
        volume: -12,
      },
    },
    effects: [
      { deviceId: 'tape', preset: 'Cassette four-track' },
      { deviceId: 'spring-reverb', preset: 'Long three spring', params: { mix: 0.25 } },
    ],
  },
  {
    id: 'low-monks-cathedral',
    name: 'Monks in a cathedral',
    category: 'voice',
    description: 'Bass voices on a closed oh without vibrato, a long way down a stone nave.',
    instrument: { deviceId: 'choir', preset: 'Low monks', params: { volume: -8 } },
    effects: [{ deviceId: 'zita-rev1', preset: 'Cathedral', params: { mix: 0.4 } }],
    preview: 'low',
  },
  {
    id: 'boys-ooh-halo',
    name: 'Treble ooh halo',
    category: 'voice',
    description: 'Small high voices singing ooh, with a reverb that climbs an octave above them.',
    instrument: { deviceId: 'choir', preset: 'Boys ooh' },
    effects: [{ deviceId: 'shimmer', preset: 'Rising choir', params: { mix: 0.35 } }],
  },
  {
    id: 'slow-vowel-choir',
    name: 'Slow vowel choir',
    category: 'voice',
    description:
      'A large section that drifts from vowel to vowel and takes three seconds to enter.',
    instrument: { deviceId: 'choir', preset: 'Slow vowels', params: { volume: -6 } },
    effects: [
      { deviceId: 'chorus', preset: 'Vocal thickener' },
      { deviceId: 'fdn-reverb', preset: 'Breathing', params: { mix: 0.4 } },
    ],
  },
  {
    id: 'breath-voices',
    name: 'Breath voices',
    category: 'voice',
    description:
      'More air than tone: a whispered chord for the top of a mix, in a very large room.',
    instrument: { deviceId: 'choir', preset: 'Breath', params: { width: 0.8, volume: -14 } },
    effects: [{ deviceId: 'expanse', preset: 'Open space', params: { mix: 0.35 } }],
  },
  {
    id: 'quartet-on-ee',
    name: 'Quartet on ee',
    category: 'voice',
    description: 'One man to a note on a close ee with a little vibrato, in a small plate.',
    instrument: {
      deviceId: 'choir',
      preset: 'Soloist',
      params: {
        vowel: 0.5,
        voice: 1.02,
        motion: 0.1,
        vibrato: 8,
        vibratoRate: 5.4,
        attack: 0.2,
        release: 1.2,
        volume: -8,
      },
    },
    effects: [{ deviceId: 'dattorro', preset: 'Small plate' }],
  },
  {
    id: 'rehearsal-room-oh',
    name: 'Rehearsal room oh',
    category: 'voice',
    description:
      'A mixed section on a rounded oh with light vibrato and some breath, in a small live room.',
    instrument: {
      deviceId: 'choir',
      preset: 'Airport ah',
      params: {
        vowel: 0.75,
        voice: 1.08,
        motion: 0.2,
        breath: 0.4,
        ensemble: 0.75,
        attack: 0.5,
        release: 1.8,
        tone: 5000,
      },
    },
    effects: [{ deviceId: 'ether-reverb', preset: 'Bright chamber' }],
  },
  {
    id: 'opera-chorus-ah',
    name: 'Opera chorus ah',
    category: 'voice',
    description: 'A full section on an open ah with a wide quick vibrato, in a bright hall.',
    instrument: {
      deviceId: 'choir',
      preset: 'Airport ah',
      params: {
        vowel: 0.02,
        voice: 1.25,
        motion: 0.2,
        breath: 0.15,
        ensemble: 1,
        vibrato: 34,
        vibratoRate: 6.2,
        attack: 0.18,
        release: 1.4,
        tone: 9000,
        volume: -11,
      },
    },
    effects: [{ deviceId: 'zita-rev1', preset: 'Bright hall', params: { mix: 0.3 } }],
  },
  {
    id: 'tenors-old-record',
    name: 'Tenors, old record',
    category: 'voice',
    description:
      'Men on eh with some vibrato in a room, played off a worn record with crackle and warp.',
    instrument: {
      deviceId: 'choir',
      preset: 'Airport ah',
      params: {
        vowel: 0.25,
        voice: 1,
        motion: 0.15,
        breath: 0.2,
        ensemble: 0.8,
        vibrato: 14,
        vibratoRate: 5,
        attack: 0.35,
        release: 1.6,
        tone: 5000,
        width: 0.5,
      },
    },
    effects: [
      { deviceId: 'zita-rev1', preset: 'Room' },
      { deviceId: 'vinyl', preset: 'Charity shop find' },
    ],
  },
  {
    id: 'choir-stabs-echo',
    name: 'Choir stabs echo',
    category: 'keys',
    description:
      'An open ah with some breath that starts and stops at once, with a dotted tape echo and a plate.',
    instrument: {
      deviceId: 'choir',
      preset: 'Airport ah',
      params: {
        vowel: 0.1,
        motion: 0.1,
        breath: 0.45,
        ensemble: 1,
        vibrato: 0,
        attack: 0.01,
        release: 0.3,
        tone: 10000,
        volume: -6,
      },
    },
    effects: [
      { deviceId: 'tape-echo', preset: 'Dotted bounce', params: { mix: 0.3 } },
      { deviceId: 'dattorro', preset: 'Medium plate', params: { mix: 0.2 } },
    ],
  },
  {
    id: 'basses-on-ah',
    name: 'Basses on ah',
    category: 'voice',
    description:
      'The largest voices on an open ah with a slow vibrato, warmed by a transformer, in a dark plate.',
    instrument: {
      deviceId: 'choir',
      preset: 'Airport ah',
      params: {
        vowel: 0.06,
        voice: 0.8,
        motion: 0.25,
        breath: 0.2,
        ensemble: 0.9,
        vibrato: 7,
        vibratoRate: 4.4,
        attack: 0.8,
        release: 3,
        tone: 5000,
        width: 0.6,
        volume: -8,
      },
    },
    effects: [
      { deviceId: 'analog-drive', preset: 'Iron lows' },
      { deviceId: 'dattorro', preset: 'Dark plate', params: { mix: 0.3 } },
    ],
    preview: 'low',
  },
  {
    id: 'overtone-choir-drone',
    name: 'Overtone choir drone',
    category: 'drone',
    description:
      'Bass voices on ee with a narrow peak sweeping slowly through their overtones, held level by a compressor, in a hall.',
    instrument: {
      deviceId: 'choir',
      preset: 'Glass ee',
      params: {
        voice: 0.84,
        motion: 0.5,
        breath: 0.02,
        attack: 1.5,
        release: 6,
        tone: 9000,
        width: 0.5,
      },
    },
    effects: [
      {
        deviceId: 'auto-filter',
        preset: 'Resonant peak',
        params: { cutoffHz: 2050, resonance: 6, envAmount: 0, lfoAmount: 15, lfoRateHz: 0.15 },
      },
      {
        deviceId: 'ambient-comp',
        params: { threshold: -30, ratio: 6, attack: 40, release: 0.6, knee: 8, makeup: 4 },
      },
      { deviceId: 'zita-rev1', preset: 'Hall' },
    ],
  },
  {
    id: 'whispers-pattering',
    name: 'Whispers pattering',
    category: 'texture',
    description:
      'A whispered ee, more air than note, chopped on and off and scattered into a swarm of short echoes.',
    instrument: {
      deviceId: 'choir',
      preset: 'Breath',
      params: {
        vowel: 0.5,
        voice: 1.36,
        motion: 0.8,
        attack: 0.04,
        release: 0.5,
        tone: 12000,
        volume: -11.5,
      },
    },
    effects: [
      {
        deviceId: 'tremolo',
        preset: 'On and off',
        params: { rate: 2.2, drift: 0.4, smooth: 0.15 },
      },
      { deviceId: 'swarm-reverb', preset: 'Pattering', params: { mix: 0.45 } },
    ],
    preview: 'chord',
  },
  {
    id: 'sung-pipe-organ',
    name: 'Sung pipe organ',
    category: 'organ',
    description:
      'A closed oo with no vibrato that speaks at once, with octaves above and below it like organ stops, in a hall.',
    instrument: {
      deviceId: 'choir',
      preset: 'Boys ooh',
      params: {
        voice: 1.1,
        motion: 0,
        breath: 0.05,
        ensemble: 0.15,
        vibrato: 0,
        attack: 0.04,
        release: 0.2,
        tone: 5000,
        width: 0.4,
        volume: -12,
      },
    },
    effects: [
      { deviceId: 'octaves', preset: 'Organ' },
      { deviceId: 'zita-rev1', preset: 'Hall', params: { mix: 0.3 } },
    ],
  },
  {
    id: 'choir-ensemble-pad',
    name: 'Choir ensemble pad',
    category: 'pad',
    description:
      'Voices with no breath or vibrato through an ensemble chorus and a slow phaser, like a string machine set to voices.',
    instrument: {
      deviceId: 'choir',
      preset: 'Airport ah',
      params: {
        vowel: 0.45,
        motion: 0.55,
        breath: 0,
        ensemble: 1,
        vibrato: 0,
        attack: 1.1,
        release: 3.5,
        tone: 4200,
        width: 0.5,
        volume: -2,
      },
    },
    effects: [
      { deviceId: 'chorus', preset: 'Lush ensemble', params: { mix: 0.45 } },
      {
        deviceId: 'phaser',
        preset: 'Warm six-stage',
        params: { centerHz: 1600, rate: 0.12, mix: 0.35 },
      },
      { deviceId: 'dattorro', preset: 'Medium plate', params: { mix: 0.3 } },
    ],
  },
  {
    id: 'wavering-choir-eh',
    name: 'Wavering choir eh',
    category: 'voice',
    description:
      'A section whose slow wide vibrato never lines up, drifting around eh, in a large space that sways too.',
    instrument: {
      deviceId: 'choir',
      preset: 'Slow vowels',
      params: {
        vowel: 0.22,
        voice: 1.2,
        motion: 0.9,
        breath: 0.25,
        ensemble: 1,
        vibrato: 48,
        vibratoRate: 3.2,
        attack: 1.2,
        release: 4,
        tone: 7000,
        width: 0.8,
      },
    },
    effects: [{ deviceId: 'expanse', preset: 'Seasick choir', params: { mix: 0.35 } }],
  },
  {
    id: 'tide-of-voices',
    name: 'Tide of voices',
    category: 'voice',
    description:
      'A breathy section between ee and oh that takes seconds to swell in and longer to leave, in an open valley.',
    instrument: {
      deviceId: 'choir',
      preset: 'Slow vowels',
      params: {
        vowel: 0.6,
        voice: 1.14,
        motion: 0.6,
        breath: 0.4,
        ensemble: 1,
        vibrato: 4,
        attack: 5,
        release: 12,
        volume: -8,
      },
    },
    effects: [{ deviceId: 'fdn-reverb', preset: 'Open valley', params: { mix: 0.4 } }],
  },
  {
    id: 'glass-ee-choir',
    name: 'Glass ee choir',
    category: 'voice',
    description:
      'A straight ee from a large section with no vibrato, a blurred octave above it, in a bright plate.',
    instrument: {
      deviceId: 'choir',
      preset: 'Glass ee',
      params: { voice: 1.3, attack: 0.8, release: 3.5, width: 0.8 },
    },
    effects: [
      { deviceId: 'spectral-blur', preset: 'Glass halo', params: { mix: 0.4 } },
      { deviceId: 'dattorro', preset: 'Bright plate' },
    ],
  },
  {
    id: 'baritone-solo-oh',
    name: 'Baritone solo oh',
    category: 'voice',
    description: 'One low man singing a line on oh with a full vibrato, in a hall.',
    instrument: {
      deviceId: 'choir',
      preset: 'Soloist',
      params: {
        vowel: 0.7,
        voice: 0.94,
        breath: 0.12,
        vibrato: 24,
        vibratoRate: 5,
        attack: 0.14,
        release: 0.7,
        tone: 6000,
        width: 0.3,
        volume: -6,
      },
    },
    effects: [{ deviceId: 'zita-rev1', preset: 'Hall', params: { mix: 0.25 } }],
    preview: 'line',
  },
  {
    id: 'valley-women-eh',
    name: 'Valley women eh',
    category: 'voice',
    description:
      'Women on a hard bright eh with no vibrato and a quick start, driven through a console and sung across an open valley.',
    instrument: {
      deviceId: 'choir',
      preset: 'Airport ah',
      params: {
        vowel: 0.2,
        voice: 1.25,
        motion: 0.05,
        breath: 0.05,
        ensemble: 1,
        vibrato: 0,
        attack: 0.09,
        release: 0.9,
        tone: 12000,
        width: 0.7,
        volume: -16,
      },
    },
    effects: [
      { deviceId: 'analog-drive', preset: 'Sheen' },
      { deviceId: 'fdn-reverb', preset: 'Open valley', params: { mix: 0.25 } },
    ],
  },
]
