import { type FactoryPreset } from '../types'

export const DRONE_PRESETS: readonly FactoryPreset[] = [
  {
    id: 'tanpura-strings',
    name: 'Tanpura and strings',
    category: 'drone',
    description:
      'The buzzing harmonic series of a tanpura, with a bank of sympathetic strings ringing behind it.',
    instrument: {
      deviceId: 'drone',
      preset: 'Tanpura',
      params: { wave: 1, cutoff: 7000, movement: 0.8, rate: 0.25, width: 0.75, volume: -11.5 },
    },
    effects: [
      { deviceId: 'sympathetic', preset: 'Sitar drone', params: { mix: 0.5, width: 0.7 } },
      { deviceId: 'hall-reverb', preset: 'Room' },
    ],
  },
  {
    id: 'sub-octave-floor',
    name: 'Sub octave floor',
    category: 'drone',
    description:
      'Stacked octaves over a heavy sub, kept dark and pushed into tape: a floor to build on.',
    instrument: {
      deviceId: 'drone',
      preset: 'Deep octaves',
      params: { partials: 0.6, wave: 0.6, sub: 0.6, cutoff: 800, volume: -8 },
    },
    effects: [
      { deviceId: 'tape', preset: 'Hot glue', params: { output: -4.5 } },
      { deviceId: 'hall-reverb', preset: 'Hall', params: { mix: 0.25 } },
    ],
  },
  {
    id: 'major-light-drone',
    name: 'Major light',
    category: 'drone',
    description: 'A just major chord of soft tones with air around it, rising into an octave halo.',
    instrument: {
      deviceId: 'drone',
      preset: 'Major light',
      params: { partials: 1, wave: 0.25, air: 0.45, cutoff: 8000, attack: 3.5, volume: -9 },
    },
    effects: [{ deviceId: 'shimmer', preset: 'Rising choir', params: { mix: 0.4, shimmer: 0.6 } }],
    preview: 'hold',
  },
  {
    id: 'fog-cluster-drone',
    name: 'Fog cluster',
    category: 'drone',
    description: 'Eight sines a tone or less apart, never still, smeared into a slow grey cloud.',
    instrument: {
      deviceId: 'drone',
      preset: 'Fog cluster',
      params: { attack: 8, width: 0.6, volume: -10 },
    },
    effects: [
      { deviceId: 'spectral-blur', preset: 'Hanging mist', params: { width: 0.7 } },
      { deviceId: 'expanse', preset: 'Open space', params: { mix: 0.3, width: 0.7 } },
    ],
    preview: 'hold',
  },
  {
    id: 'latched-pedal-tone',
    name: 'Latched pedal tone',
    category: 'drone',
    description:
      'One thick, slowly beating unison that stays on when the key is let go; press it again to stop.',
    instrument: {
      deviceId: 'drone',
      preset: 'Latched unison',
      params: { wave: 0.9, sub: 0.1, cutoff: 3000, volume: -9 },
    },
    effects: [
      { deviceId: 'phaser', preset: 'Slow swirl', params: { mix: 0.4 } },
      { deviceId: 'fdn-reverb', preset: 'Hall', params: { mix: 0.3 } },
    ],
  },
  {
    id: 'small-room-fifths',
    name: 'Small room fifths',
    category: 'drone',
    description:
      'A root with its fifth, octave and twelfth in soft rounded tones, drifting a little, in a small room.',
    instrument: {
      deviceId: 'drone',
      preset: 'Open fifths',
      params: {
        partials: 0.45,
        wave: 0.3,
        movement: 0.35,
        sub: 0.25,
        air: 0.08,
        cutoff: 3000,
        attack: 1.2,
        release: 4,
        volume: -9,
      },
    },
    effects: [{ deviceId: 'ether-reverb', preset: 'Room' }],
  },
  {
    id: 'drone-organ-octaves',
    name: 'Drone organ octaves',
    category: 'organ',
    description:
      'Sine octaves stacked four octaves up from every key, speaking at once and almost still, in a small plate.',
    instrument: {
      deviceId: 'drone',
      preset: 'Deep octaves',
      params: {
        partials: 1,
        wave: 0.08,
        movement: 0.15,
        rate: 0.1,
        sub: 0.2,
        air: 0.04,
        cutoff: 9000,
        attack: 0.06,
        release: 0.6,
        width: 0.5,
        volume: -11,
      },
    },
    effects: [{ deviceId: 'plate-reverb', preset: 'Small plate' }],
  },
  {
    id: 'minor-drone-plate',
    name: 'Minor drone, plate',
    category: 'drone',
    description:
      'A just minor chord from each key with the filter opened up, about a second to rise, on a plate.',
    instrument: {
      deviceId: 'drone',
      preset: 'Minor dusk',
      params: {
        partials: 0.75,
        wave: 0.15,
        movement: 0.45,
        rate: 0.07,
        sub: 0.25,
        air: 0.1,
        cutoff: 3400,
        attack: 2,
        release: 6,
        width: 0.7,
        volume: -8.5,
      },
    },
    effects: [{ deviceId: 'plate-reverb', preset: 'Medium plate', params: { mix: 0.28 } }],
  },
  {
    id: 'still-sine-pedal',
    name: 'Still sine pedal',
    category: 'drone',
    description:
      'One near sine and its sub octave, in the centre and perfectly still, warmed by a transformer in a booth.',
    instrument: {
      deviceId: 'drone',
      preset: 'Latched unison',
      params: {
        partials: 0,
        wave: 0.12,
        movement: 0,
        sub: 0.6,
        air: 0,
        cutoff: 1200,
        attack: 0.3,
        release: 1.5,
        width: 0,
        hold: 0,
        volume: -14,
      },
    },
    effects: [
      { deviceId: 'analog-drive', preset: 'Low warmth' },
      { deviceId: 'ether-reverb', preset: 'Small booth' },
    ],
  },
  {
    id: 'string-machine-drone',
    name: 'String machine drone',
    category: 'string',
    description:
      'Bright sawtooth octaves, each drifting a few cents, through a three voice ensemble chorus in a hall.',
    instrument: {
      deviceId: 'drone',
      preset: 'Deep octaves',
      params: {
        partials: 0.72,
        wave: 0.95,
        movement: 0.5,
        rate: 0.25,
        sub: 0.15,
        cutoff: 3800,
        attack: 0.5,
        release: 2.2,
        volume: -7,
      },
    },
    effects: [
      { deviceId: 'chorus', preset: 'Lush ensemble' },
      { deviceId: 'hall-reverb', preset: 'Hall', params: { mix: 0.25 } },
    ],
  },
  {
    id: 'spinning-major-reeds',
    name: 'Spinning major reeds',
    category: 'drone',
    description:
      'A just major chord of reedy tones that speaks quickly, turning slowly in a rotary speaker in a room.',
    instrument: {
      deviceId: 'drone',
      preset: 'Major light',
      params: {
        partials: 0.85,
        wave: 0.7,
        movement: 0.25,
        rate: 0.2,
        sub: 0.15,
        air: 0.2,
        cutoff: 3600,
        attack: 0.35,
        release: 1.5,
        width: 0.5,
        volume: -7.5,
      },
    },
    effects: [
      { deviceId: 'rotary', preset: 'Chorale' },
      { deviceId: 'fdn-reverb', preset: 'Room', params: { mix: 0.22 } },
    ],
    preview: 'hold',
  },
  {
    id: 'bright-fifth-stack',
    name: 'Bright fifth stack',
    category: 'drone',
    description:
      'Sawtooth fifths and octaves piled up to twelve times the root, filter wide open, in a bright hall.',
    instrument: {
      deviceId: 'drone',
      preset: 'Open fifths',
      params: {
        partials: 1,
        wave: 1,
        movement: 0.7,
        rate: 0.14,
        sub: 0.1,
        air: 0.12,
        cutoff: 12000,
        attack: 4,
        release: 7,
        width: 0.9,
        volume: -8,
      },
    },
    effects: [{ deviceId: 'hall-reverb', preset: 'Bright hall', params: { mix: 0.3 } }],
  },
  {
    id: 'swept-overtone-drone',
    name: 'Swept overtone drone',
    category: 'drone',
    description:
      'A sawtooth harmonic series held nearly still while a ringing peak climbs and falls through it.',
    instrument: {
      deviceId: 'drone',
      preset: 'Tanpura',
      params: {
        wave: 1,
        movement: 0.2,
        rate: 0.1,
        sub: 0.25,
        air: 0,
        cutoff: 9000,
        attack: 1,
        release: 5,
        width: 0.4,
        volume: -18,
      },
    },
    effects: [
      {
        deviceId: 'auto-filter',
        preset: 'Init',
        params: {
          type: 4,
          cutoffHz: 800,
          resonance: 5,
          driveDb: 6,
          lfoAmount: 50,
          lfoRateHz: 0.15,
          lfoShape: 1,
        },
      },
      { deviceId: 'hall-reverb', preset: 'Hall', params: { mix: 0.3 } },
    ],
  },
  {
    id: 'flickering-harmonics',
    name: 'Flickering harmonics',
    category: 'drone',
    description:
      'Eight pure harmonics that each flutter in level and place, with grains of them an octave above.',
    instrument: {
      deviceId: 'drone',
      preset: 'Tanpura',
      params: {
        wave: 0,
        movement: 1,
        rate: 1.6,
        sub: 0,
        air: 0,
        cutoff: 10000,
        attack: 1.2,
        release: 5,
        width: 1,
        volume: -10,
      },
    },
    effects: [
      { deviceId: 'grain-delay', preset: 'Crystals', params: { feedback: 0.3, mix: 0.25 } },
      { deviceId: 'fdn-reverb', preset: 'Bright air', params: { mix: 0.3 } },
    ],
  },
  {
    id: 'tuned-air-pipe',
    name: 'Tuned air pipe',
    category: 'wind',
    description:
      'One sine and an equally loud band of noise tuned to the key, quick to speak, like breath across a wide pipe.',
    instrument: {
      deviceId: 'drone',
      preset: 'Latched unison',
      params: {
        partials: 0,
        wave: 0,
        movement: 0.6,
        rate: 0.5,
        sub: 0,
        air: 1,
        cutoff: 7000,
        attack: 0.25,
        release: 1.2,
        width: 0.8,
        hold: 0,
        volume: -11.5,
      },
    },
    effects: [{ deviceId: 'ether-reverb', preset: 'Bright chamber' }],
  },
  {
    id: 'restless-saw-swarm',
    name: 'Restless saw swarm',
    category: 'drone',
    description:
      'Eight sawtooths on one pitch, each wavering in tune and level about twice a second, across a valley.',
    instrument: {
      deviceId: 'drone',
      preset: 'Latched unison',
      params: {
        wave: 1,
        movement: 1,
        rate: 2,
        sub: 0.3,
        air: 0,
        cutoff: 4500,
        attack: 1,
        release: 4,
        width: 0.8,
        hold: 0,
        volume: -8.5,
      },
    },
    effects: [{ deviceId: 'fdn-reverb', preset: 'Open valley' }],
  },
  {
    id: 'cluster-reed-spring',
    name: 'Cluster reed spring',
    category: 'drone',
    description:
      'Five reedy tones a tone or less apart that speak at once, close and sour, in a long spring tank.',
    instrument: {
      deviceId: 'drone',
      preset: 'Fog cluster',
      params: {
        partials: 0.6,
        wave: 0.75,
        movement: 0.3,
        rate: 0.3,
        sub: 0.1,
        air: 0.15,
        cutoff: 2400,
        attack: 0.25,
        release: 1.2,
        width: 0.6,
        volume: -8.5,
      },
    },
    effects: [{ deviceId: 'spring-reverb', preset: 'Long three spring', params: { width: 0.4 } }],
    preview: 'hold',
  },
  {
    id: 'rumbling-air-floor',
    name: 'Rumbling air floor',
    category: 'drone',
    description:
      'A low sine, its octave and its sub under a wandering band of tuned noise, roughened by an overdriven valve, in a narrow tunnel.',
    instrument: {
      deviceId: 'drone',
      preset: 'Deep octaves',
      params: {
        partials: 0.15,
        wave: 0,
        movement: 0.9,
        rate: 0.6,
        sub: 0.7,
        air: 1,
        attack: 2.5,
        release: 8,
        width: 0.5,
        volume: -8,
      },
    },
    effects: [
      { deviceId: 'analog-drive', preset: 'Bite', params: { drive: 1, lowCut: 20, output: -7 } },
      { deviceId: 'expanse', preset: 'Narrow tunnel', params: { mix: 0.3 } },
    ],
  },
  {
    id: 'warped-shellac-minor',
    name: 'Warped shellac minor',
    category: 'drone',
    description:
      'A just minor chord on a warped shellac disc: narrow and swaying in pitch, with crackle and surface noise that never stop.',
    instrument: {
      deviceId: 'drone',
      preset: 'Minor dusk',
      params: {
        partials: 1,
        wave: 0.7,
        movement: 0.5,
        rate: 0.06,
        sub: 0,
        air: 0.15,
        cutoff: 4000,
        attack: 3,
        release: 6,
        volume: -4.5,
      },
    },
    effects: [
      { deviceId: 'vinyl', preset: 'Parlour 78', params: { warp: 0.55, crackle: 0.35 } },
      { deviceId: 'hall-reverb', preset: 'Room' },
    ],
  },
  {
    id: 'fifth-keys-echoed',
    name: 'Fifth keys, echoed',
    category: 'keys',
    description:
      'Fifths switched on and off like organ keys, with no fade in, repeating off three tape heads.',
    instrument: {
      deviceId: 'drone',
      preset: 'Open fifths',
      params: {
        partials: 0.55,
        wave: 0.4,
        movement: 0.2,
        rate: 0.3,
        sub: 0.2,
        air: 0.05,
        cutoff: 3200,
        attack: 0.01,
        release: 0.35,
        width: 0.5,
        volume: -10,
      },
    },
    effects: [
      { deviceId: 'tape-echo', preset: 'Three heads', params: { mix: 0.35 } },
      { deviceId: 'ether-reverb', preset: 'Room' },
    ],
  },
]
