import { type FactoryPreset } from '../types'

export const EMBER_PRESETS: readonly FactoryPreset[] = [
  {
    id: 'warm-chorus-pad',
    name: 'Warm chorus pad',
    category: 'pad',
    description: 'Two detuned saws and a sub under a low filter, through a slow stereo chorus.',
    instrument: {
      deviceId: 'ember',
      preset: 'Warm pad',
      params: { cutoff: 750, unisonVoices: 1, volume: -2 },
    },
    effects: [
      { deviceId: 'chorus', preset: 'Lush ensemble', params: { depth: 45, mix: 0.45 } },
      { deviceId: 'plate-reverb', preset: 'Small plate', params: { mix: 0.2 } },
    ],
  },
  {
    id: 'slow-filter-swell',
    name: 'Slow filter swell',
    category: 'pad',
    description:
      'A dark saw chord whose filter takes four seconds to open, then closes into a hall.',
    instrument: {
      deviceId: 'ember',
      preset: 'Slow strings',
      params: {
        filterSlope: 1,
        cutoff: 320,
        resonance: 0.22,
        filterEnvAmount: 0.5,
        filterAttack: 4,
        filterDecay: 4,
        filterSustain: 0.7,
        filterRelease: 5,
        ampAttack: 3.2,
        ampRelease: 5,
        unisonVoices: 2,
        unisonSpread: 0.6,
        volume: -8,
      },
    },
    effects: [{ deviceId: 'hall-reverb', preset: 'Hall', params: { mix: 0.3 } }],
  },
  {
    id: 'glass-octave-pad',
    name: 'Glass octave pad',
    category: 'pad',
    description:
      'A triangle an octave up with a pulse of moving width above it, left in a long plate.',
    instrument: {
      deviceId: 'ember',
      preset: 'Glass pad',
      params: {
        osc1Coarse: 12,
        osc2Coarse: 24,
        osc2Pw: 0.5,
        oscMix: 0.42,
        cutoff: 7000,
        ampRelease: 5,
        unisonVoices: 2,
        unisonSpread: 0.7,
        volume: -9,
      },
    },
    effects: [{ deviceId: 'plate-reverb', preset: 'Long plate', params: { mix: 0.3 } }],
  },
  {
    id: 'soft-brass-pad',
    name: 'Soft brass pad',
    category: 'pad',
    description: 'Speaks at once and then mellows, like quiet synth brass played back from tape.',
    instrument: {
      deviceId: 'ember',
      preset: 'Brass',
      params: {
        cutoff: 950,
        filterEnvAmount: 0.42,
        filterAttack: 0.25,
        filterDecay: 2.2,
        filterSustain: 0.35,
        filterRelease: 2,
        ampAttack: 0.09,
        ampRelease: 2.4,
        unisonVoices: 2,
        unisonDetune: 10,
        unisonSpread: 0.7,
        volume: -6,
      },
    },
    effects: [
      { deviceId: 'tape', preset: 'Quarter inch' },
      { deviceId: 'plate-reverb', preset: 'Small plate' },
    ],
  },
  {
    id: 'low-ember-drone',
    name: 'Low ember drone',
    category: 'drone',
    description:
      'Two saws a fifth apart over a sub, barely open, with a filter that breathes slowly.',
    instrument: {
      deviceId: 'ember',
      preset: 'Dark drone',
      params: {
        osc2Shape: 0,
        osc2Coarse: 7,
        oscMix: 0.3,
        subLevel: 0.3,
        cutoff: 650,
        volume: -5,
      },
    },
    effects: [{ deviceId: 'fdn-reverb', preset: 'Breathing', params: { mix: 0.35 } }],
    preview: 'low',
  },
  {
    id: 'pulse-width-strings',
    name: 'Pulse width strings',
    category: 'string',
    description:
      'Two pulse waves whose width is swept by a slow triangle, through an ensemble chorus into a room.',
    instrument: {
      deviceId: 'ember',
      preset: 'Init',
      params: {
        osc1Shape: 1,
        osc2Shape: 1,
        osc2Fine: 9,
        osc2Pw: 0.42,
        oscMix: 0.5,
        filterSlope: 0,
        cutoff: 2600,
        resonance: 0.1,
        keyTrack: 0.5,
        ampAttack: 0.35,
        ampDecay: 1,
        ampSustain: 0.9,
        ampRelease: 1.4,
        velToAmp: 0.4,
        lfo1Shape: 1,
        lfo1Rate: 0.7,
        lfo1Dest: 4,
        lfo1Amount: 0.6,
        lfo2Rate: 5.6,
        lfo2Amount: 0.004,
        unisonVoices: 2,
        unisonDetune: 9,
        unisonSpread: 0.6,
        volume: -8,
      },
    },
    effects: [
      { deviceId: 'chorus', preset: 'Lush ensemble', params: { mix: 0.4 } },
      { deviceId: 'hall-reverb', preset: 'Room' },
    ],
  },
  {
    id: 'ember-sine-organ',
    name: 'Ember sine organ',
    category: 'organ',
    description:
      'Three sines an octave apart that speak at once and hold their level, through a slowly turning speaker in a room.',
    instrument: {
      deviceId: 'ember',
      preset: 'Init',
      params: {
        osc1Shape: 3,
        osc2Shape: 3,
        osc2Coarse: 12,
        oscMix: 0.4,
        subLevel: 0.45,
        ampAttack: 0.008,
        ampRelease: 0.08,
        velToAmp: 0.1,
        volume: -14.5,
      },
    },
    effects: [
      { deviceId: 'rotary', preset: 'Chorale', params: { drive: 0.15 } },
      { deviceId: 'fdn-reverb', preset: 'Room', params: { mix: 0.2 } },
    ],
  },
  {
    id: 'synced-saw-pad',
    name: 'Synced saw pad',
    category: 'pad',
    description:
      'A saw tuned high and restarted on every cycle of a lower one, nasal and hollow, three voices wide in a plate.',
    instrument: {
      deviceId: 'ember',
      preset: 'Init',
      params: {
        osc2Coarse: 16,
        osc2Sync: 1,
        oscMix: 0.75,
        cutoff: 1800,
        resonance: 0.15,
        keyTrack: 0.4,
        filterEnvAmount: 0.25,
        filterAttack: 1.5,
        filterDecay: 2.5,
        filterRelease: 3,
        ampAttack: 0.9,
        ampDecay: 2,
        ampSustain: 0.85,
        ampRelease: 3.5,
        velToAmp: 0.5,
        lfo1Rate: 0.1,
        lfo1Amount: 0.1,
        unisonVoices: 3,
        unisonDetune: 12,
        unisonSpread: 0.8,
        volume: -7,
      },
    },
    effects: [{ deviceId: 'plate-reverb', preset: 'Medium plate', params: { mix: 0.3 } }],
  },
  {
    id: 'high-pass-saw-veil',
    name: 'High pass saw veil',
    category: 'pad',
    description:
      'Saws an octave apart in four detuned voices, everything under a kilohertz filtered away, thin and bright, in a long airy hall.',
    instrument: {
      deviceId: 'ember',
      preset: 'Init',
      params: {
        osc2Coarse: 12,
        osc2Fine: -7,
        oscMix: 0.45,
        noiseLevel: 0.03,
        filterType: 1,
        filterSlope: 0,
        cutoff: 1100,
        resonance: 0.25,
        keyTrack: 0.3,
        ampAttack: 1.4,
        ampDecay: 2,
        ampSustain: 0.9,
        ampRelease: 4,
        velToAmp: 0.5,
        lfo1Rate: 0.09,
        lfo1Amount: 0.15,
        lfo2Shape: 1,
        lfo2Rate: 0.23,
        lfo2Dest: 3,
        lfo2Amount: 0.2,
        unisonVoices: 4,
        unisonDetune: 20,
        unisonSpread: 0.9,
        volume: -1,
      },
    },
    effects: [{ deviceId: 'hall-reverb', preset: 'Airy tail', params: { mix: 0.4 } }],
  },
  {
    id: 'band-pass-choir',
    name: 'Band pass choir',
    category: 'voice',
    description:
      'A thin pulse and a saw through a resonant band that drifts like a mouth, in a hall that sings ah.',
    instrument: {
      deviceId: 'ember',
      preset: 'Init',
      params: {
        osc1Shape: 1,
        osc1Pw: 0.28,
        osc2Fine: 7,
        oscMix: 0.4,
        filterType: 2,
        filterSlope: 0,
        cutoff: 850,
        resonance: 0.55,
        keyTrack: 0.15,
        ampAttack: 0.7,
        ampDecay: 1.5,
        ampSustain: 0.9,
        ampRelease: 2.2,
        velToAmp: 0.4,
        lfo1Rate: 0.12,
        lfo1Amount: 0.12,
        lfo2Rate: 5.3,
        lfo2Amount: 0.006,
        unisonVoices: 3,
        unisonDetune: 14,
        unisonSpread: 0.8,
      },
    },
    effects: [{ deviceId: 'vowel-reverb', preset: 'Choir of ah' }],
  },
  {
    id: 'ember-tine-keys',
    name: 'Ember tine keys',
    category: 'keys',
    description:
      'A sine with a triangle an octave up and a quick filter bark, fading while held, panned gently from side to side.',
    instrument: {
      deviceId: 'ember',
      preset: 'Init',
      params: {
        osc1Shape: 3,
        osc2Shape: 2,
        osc2Coarse: 12,
        oscMix: 0.3,
        filterSlope: 0,
        cutoff: 900,
        filterDrive: 0.2,
        keyTrack: 0.6,
        filterEnvAmount: 0.5,
        velToFilter: 0.5,
        filterAttack: 0.001,
        filterDecay: 0.25,
        filterSustain: 0,
        ampAttack: 0.002,
        ampDecay: 2.8,
        ampSustain: 0.12,
        ampRelease: 0.6,
        velToAmp: 0.8,
        volume: 1,
      },
    },
    effects: [
      { deviceId: 'tremolo', preset: 'Slow pan', params: { rate: 1.1, depth: 0.5 } },
      { deviceId: 'plate-reverb', preset: 'Small plate' },
    ],
  },
  {
    id: 'resonant-saw-pluck',
    name: 'Resonant saw pluck',
    category: 'plucked',
    description:
      'Two saws through a resonant filter that snaps shut, drifting from side to side, with a slap echo.',
    instrument: {
      deviceId: 'ember',
      preset: 'Init',
      params: {
        osc2Fine: 6,
        oscMix: 0.4,
        filterSlope: 0,
        cutoff: 380,
        filterDrive: 0.25,
        resonance: 0.5,
        keyTrack: 0.5,
        filterEnvAmount: 0.65,
        velToFilter: 0.4,
        filterAttack: 0.001,
        filterSustain: 0,
        filterRelease: 0.2,
        ampAttack: 0.001,
        ampDecay: 0.9,
        ampSustain: 0,
        ampRelease: 0.4,
        velToAmp: 0.4,
        lfo1Rate: 0.7,
        lfo1Dest: 3,
        lfo1Amount: 0.8,
        volume: 3,
      },
    },
    effects: [
      { deviceId: 'analog-delay', preset: 'Slapback' },
      { deviceId: 'ether-reverb', preset: 'Small booth' },
    ],
  },
  {
    id: 'ember-breath-pipe',
    name: 'Ember breath pipe',
    category: 'wind',
    description:
      'One triangle voice with noise for breath and a chiff as it starts, with a short glide between notes, in a hall.',
    instrument: {
      deviceId: 'ember',
      preset: 'Init',
      params: {
        osc1Shape: 2,
        noiseLevel: 0.7,
        filterSlope: 0,
        cutoff: 1046,
        resonance: 0.1,
        keyTrack: 1,
        filterEnvAmount: 0.3,
        filterAttack: 0.01,
        filterDecay: 0.18,
        filterSustain: 0,
        ampAttack: 0.09,
        ampDecay: 0.6,
        ampSustain: 0.85,
        ampRelease: 0.45,
        velToAmp: 0.5,
        lfo2Rate: 4.8,
        lfo2Amount: 0.005,
        voiceMode: 2,
        glide: 0.09,
        volume: -5,
      },
    },
    effects: [
      { deviceId: 'analog-delay', preset: 'Faint halo' },
      { deviceId: 'hall-reverb', preset: 'Hall', params: { mix: 0.3 } },
    ],
  },
  {
    id: 'ember-music-box',
    name: 'Ember music box',
    category: 'bell',
    description:
      'A triangle an octave up with a sine above it, struck and fading, each note answered backwards in a plate.',
    instrument: {
      deviceId: 'ember',
      preset: 'Init',
      params: {
        osc1Shape: 2,
        osc1Coarse: 12,
        osc2Shape: 3,
        osc2Coarse: 24,
        osc2Fine: 4,
        oscMix: 0.3,
        filterSlope: 0,
        cutoff: 3000,
        keyTrack: 0.8,
        filterEnvAmount: 0.4,
        filterAttack: 0.001,
        filterDecay: 0.15,
        filterSustain: 0,
        ampAttack: 0.001,
        ampDecay: 1.7,
        ampSustain: 0,
        ampRelease: 1.7,
        velToAmp: 0.4,
        volume: 6,
      },
    },
    effects: [
      { deviceId: 'reverse-delay', preset: 'Backwards echo', params: { mix: 0.3 } },
      { deviceId: 'plate-reverb', preset: 'Bright plate', params: { mix: 0.2 } },
    ],
  },
  {
    id: 'dimming-saw-pad',
    name: 'Dimming saw pad',
    category: 'pad',
    description:
      'Starts bright and at once, dims over three seconds while held, then brightens again as it fades away.',
    instrument: {
      deviceId: 'ember',
      preset: 'Init',
      params: {
        osc2Fine: -9,
        oscMix: 0.5,
        subLevel: 0.15,
        cutoff: 7000,
        resonance: 0.18,
        keyTrack: 0.3,
        filterEnvAmount: -0.6,
        filterAttack: 3,
        filterDecay: 1,
        filterSustain: 1,
        filterRelease: 4,
        ampAttack: 0.05,
        ampDecay: 1,
        ampRelease: 4.5,
        velToAmp: 0.5,
        unisonVoices: 2,
        unisonDetune: 12,
        unisonSpread: 0.7,
        volume: -8,
      },
    },
    effects: [{ deviceId: 'fdn-reverb', preset: 'Open valley', params: { mix: 0.3 } }],
  },
  {
    id: 'throbbing-saw-pad',
    name: 'Throbbing saw pad',
    category: 'pad',
    description:
      'A saw chord pulsed six times a second by a triangle wave while its filter drifts, over bouncing tape echoes.',
    instrument: {
      deviceId: 'ember',
      preset: 'Init',
      params: {
        osc2Fine: 8,
        oscMix: 0.5,
        cutoff: 2400,
        resonance: 0.2,
        keyTrack: 0.4,
        ampAttack: 0.02,
        ampRelease: 1.5,
        velToAmp: 0.5,
        lfo1Shape: 1,
        lfo1Rate: 6,
        lfo1Dest: 2,
        lfo1Amount: 0.9,
        lfo2Rate: 0.1,
        lfo2Dest: 1,
        lfo2Amount: 0.25,
        unisonVoices: 2,
        unisonDetune: 10,
        unisonSpread: 0.6,
        volume: -4,
      },
    },
    effects: [
      { deviceId: 'tape-echo', preset: 'Dotted bounce', params: { time: 500, mix: 0.3 } },
      { deviceId: 'fdn-reverb', preset: 'Hall', params: { mix: 0.25 } },
    ],
  },
  {
    id: 'harmonic-sweep-drone',
    name: 'Harmonic sweep drone',
    category: 'drone',
    description:
      'A low saw and pulse under a sharply resonant filter that slowly rises and falls through their overtones one by one.',
    instrument: {
      deviceId: 'ember',
      preset: 'Init',
      params: {
        osc2Shape: 1,
        osc2Fine: 5,
        osc2Pw: 0.3,
        oscMix: 0.35,
        subLevel: 0.25,
        cutoff: 950,
        resonance: 0.85,
        filterDrive: 0.2,
        keyTrack: 0.5,
        ampAttack: 2,
        ampDecay: 1,
        ampRelease: 6,
        velToAmp: 0.4,
        lfo1Shape: 1,
        lfo1Rate: 0.06,
        lfo1Amount: 0.4,
        volume: -12.5,
      },
    },
    effects: [{ deviceId: 'hall-reverb', preset: 'Warm undertow', params: { mix: 0.3 } }],
  },
  {
    id: 'noise-rain-patter',
    name: 'Noise rain patter',
    category: 'texture',
    description:
      'High hiss whose level and tone are thrown about at random, pattering in a cave of short echoes.',
    instrument: {
      deviceId: 'ember',
      preset: 'Init',
      params: {
        osc1Shape: 3,
        osc1Coarse: -24,
        noiseLevel: 1,
        filterType: 1,
        cutoff: 3500,
        resonance: 0.4,
        ampAttack: 0.8,
        ampRelease: 3,
        velToAmp: 0,
        lfo1Shape: 4,
        lfo1Rate: 22,
        lfo1Dest: 2,
        lfo1Amount: 1,
        lfo2Shape: 4,
        lfo2Rate: 9,
        lfo2Dest: 1,
        lfo2Amount: 0.2,
        volume: -2,
      },
    },
    effects: [{ deviceId: 'swarm-reverb', preset: 'Pattering' }],
  },
  {
    id: 'six-voice-saws',
    name: 'Six voice saws',
    category: 'pad',
    description:
      'Six saw voices detuned across half a semitone, bright and beating against each other, in a small room.',
    instrument: {
      deviceId: 'ember',
      preset: 'Init',
      params: {
        osc2Fine: 7,
        oscMix: 0.5,
        filterSlope: 0,
        cutoff: 6500,
        resonance: 0.05,
        keyTrack: 0.5,
        velToFilter: 0.3,
        ampAttack: 0.03,
        ampDecay: 0.5,
        ampSustain: 0.9,
        ampRelease: 0.9,
        velToAmp: 0.5,
        unisonVoices: 6,
        unisonDetune: 24,
        unisonSpread: 0.85,
        volume: -10,
      },
    },
    effects: [{ deviceId: 'hall-reverb', preset: 'Room' }],
  },
  {
    id: 'triangle-tape-pad',
    name: 'Triangle tape pad',
    category: 'pad',
    description:
      'Two triangles a few cents apart and a sub octave under a low filter, on a cassette in a small room.',
    instrument: {
      deviceId: 'ember',
      preset: 'Init',
      params: {
        osc1Shape: 2,
        osc2Shape: 2,
        osc2Fine: 4,
        oscMix: 0.5,
        subLevel: 0.35,
        cutoff: 700,
        keyTrack: 0.3,
        ampAttack: 0.5,
        ampDecay: 1,
        ampRelease: 2,
        velToAmp: 0.5,
        volume: -10,
      },
    },
    effects: [
      { deviceId: 'tape', preset: 'Cassette four-track' },
      { deviceId: 'ether-reverb', preset: 'Room' },
    ],
  },
]
