import { type FactoryPreset } from '../types'

export const FM_GLASS_PRESETS: readonly FactoryPreset[] = [
  {
    id: 'glass-bell-plate',
    name: 'Glass bell plate',
    category: 'bell',
    description: 'The inharmonic glass bell as it comes, ringing into a long bright plate.',
    instrument: {
      deviceId: 'fm-glass',
      preset: 'Glass bell',
      params: { spread: 0.35, volume: -5 },
    },
    effects: [{ deviceId: 'plate-reverb', preset: 'Long plate', params: { mix: 0.35 } }],
  },
  {
    id: 'ice-chime-crystals',
    name: 'Ice chime crystals',
    category: 'bell',
    description: 'Short bright chimes whose echoes come back an octave higher each time.',
    instrument: { deviceId: 'fm-glass', preset: 'Ice chimes', params: { volume: -3 } },
    effects: [
      { deviceId: 'grain-delay', preset: 'Crystals', params: { mix: 0.3 } },
      { deviceId: 'hall-reverb', preset: 'Hall', params: { mix: 0.3 } },
    ],
  },
  {
    id: 'temple-bowl-hall',
    name: 'Temple bowl',
    category: 'bell',
    description: 'A slow bowl tone with a soft strike that hangs for a long time in a dark hall.',
    instrument: { deviceId: 'fm-glass', preset: 'Temple bowl', params: { brightness: 0.3 } },
    effects: [
      {
        deviceId: 'fdn-reverb',
        preset: 'Breathing',
        params: { decay: 12, damping: 0.6, mix: 0.4 },
      },
    ],
  },
  {
    id: 'water-garden-mallets',
    name: 'Water garden mallets',
    category: 'bell',
    description: 'Soft FM mallets with dotted tape echoes, for slow repeating patterns.',
    instrument: { deviceId: 'fm-glass', preset: 'Vibes', params: { volume: -7 } },
    effects: [
      { deviceId: 'tape-echo', preset: 'Warm repeats', params: { heads: 3, time: 450, mix: 0.3 } },
      { deviceId: 'hall-reverb', preset: 'Room', params: { mix: 0.3 } },
    ],
  },
  {
    id: 'crystal-pad-drift',
    name: 'Crystal pad',
    category: 'pad',
    description: 'A held FM pad whose brightness blooms after the note, widened by a slow chorus.',
    instrument: {
      deviceId: 'fm-glass',
      preset: 'Crystal pad',
      params: { spread: 0.6, volume: -16 },
    },
    effects: [
      { deviceId: 'chorus', preset: 'Slow drift', params: { mix: 0.4 } },
      { deviceId: 'expanse', preset: 'Open space', params: { mix: 0.35, width: 0.7 } },
    ],
    preview: 'chord',
  },
  {
    id: 'panning-tine-keys',
    name: 'Panning tine keys',
    category: 'keys',
    description:
      'FM tine keys, a pure tone under a short metallic ting, swaying from side to side in a small room.',
    instrument: {
      deviceId: 'fm-glass',
      params: {
        algorithm: 1,
        ratio: 9,
        brightness: 0.34,
        decay: 1.3,
        attack: 0.002,
        release: 0.45,
        detune: 4,
        feedback: 0,
        velocity: 0.7,
        spread: 0.3,
      },
    },
    effects: [
      { deviceId: 'tremolo', preset: 'Slow pan', params: { rate: 0.9, depth: 0.6 } },
      { deviceId: 'hall-reverb', preset: 'Room', params: { mix: 0.22 } },
    ],
  },
  {
    id: 'hollow-glass-organ',
    name: 'Hollow glass organ',
    category: 'organ',
    description:
      'Held odd harmonics like a stopped pipe, with a short chiff, turning in a slow rotary speaker.',
    instrument: {
      deviceId: 'fm-glass',
      params: {
        algorithm: 2,
        ratio: 3,
        brightness: 0.6,
        decay: 0.3,
        attack: 0.006,
        release: 0.12,
        sustain: 1,
        detune: 0,
        feedback: 0.15,
        velocity: 0.1,
        volume: -23.5,
      },
    },
    effects: [
      { deviceId: 'rotary', preset: 'Chorale', params: { drive: 0.1, mix: 0.8 } },
      { deviceId: 'hall-reverb', preset: 'Tight chamber' },
    ],
  },
  {
    id: 'operator-strings',
    name: 'Operator strings',
    category: 'string',
    description:
      'FM strings made buzzy by heavy feedback, detuned sixteen cents and thickened by an ensemble chorus in a hall.',
    instrument: {
      deviceId: 'fm-glass',
      params: {
        algorithm: 3,
        ratio: 1,
        brightness: 0.4,
        decay: 2,
        attack: 0.4,
        release: 1.4,
        sustain: 1,
        detune: 16,
        feedback: 0.85,
        velocity: 0.3,
        spread: 0.45,
        volume: -13,
      },
    },
    effects: [
      { deviceId: 'chorus', preset: 'Lush ensemble', params: { spread: 60, mix: 0.45 } },
      { deviceId: 'hall-reverb', preset: 'Hall', params: { mix: 0.3 } },
    ],
  },
  {
    id: 'glass-reed-line',
    name: 'Glass reed line',
    category: 'wind',
    description:
      'One hollow reed voice of odd harmonics that speaks quickly, with a light vibrato, in a small chamber.',
    instrument: {
      deviceId: 'fm-glass',
      params: {
        ratio: 3,
        brightness: 0.55,
        decay: 1.2,
        attack: 0.06,
        release: 0.2,
        sustain: 0.85,
        detune: 0,
        feedback: 0.4,
        velocity: 0.5,
        spread: 0,
        volume: -16,
      },
    },
    effects: [
      { deviceId: 'tremolo', preset: 'Pitch wobble', params: { depth: 0.15 } },
      { deviceId: 'hall-reverb', preset: 'Tight chamber', params: { mix: 0.25 } },
    ],
  },
  {
    id: 'horn-on-shellac',
    name: 'Horn on shellac',
    category: 'wind',
    description:
      'A soft FM horn whose brightness swells in behind each note, on a plate, played back from a crackling 78.',
    instrument: {
      deviceId: 'fm-glass',
      params: {
        algorithm: 3,
        ratio: 1,
        brightness: 0.5,
        decay: 0.6,
        attack: 0.09,
        release: 0.35,
        sustain: 0.8,
        detune: 0,
        feedback: 0.5,
        spread: 0,
        volume: -9.5,
      },
    },
    effects: [
      { deviceId: 'plate-reverb', preset: 'Medium plate', params: { mix: 0.3 } },
      { deviceId: 'vinyl', preset: 'Parlour 78' },
    ],
  },
  {
    id: 'glass-wire-harp',
    name: 'Glass wire harp',
    category: 'plucked',
    description:
      'A bright pluck that falls quickly to a pure tone, like a harp strung with wire, with a faint halo of hall.',
    instrument: {
      deviceId: 'fm-glass',
      params: {
        algorithm: 1,
        ratio: 5,
        brightness: 0.5,
        decay: 0.45,
        attack: 0.001,
        release: 1.5,
        detune: 3,
        feedback: 0.3,
        velocity: 0.85,
        spread: 0.5,
        volume: -6.5,
      },
    },
    effects: [{ deviceId: 'hall-reverb', preset: 'Faint halo', params: { mix: 0.18 } }],
  },
  {
    id: 'buzzing-wire-pluck',
    name: 'Buzzing wire pluck',
    category: 'plucked',
    description:
      'A buzzing pluck at full feedback that sets a bank of strings tuned to A minor ringing behind it.',
    instrument: {
      deviceId: 'fm-glass',
      params: {
        algorithm: 2,
        ratio: 1,
        brightness: 0.72,
        decay: 1.2,
        attack: 0.001,
        release: 0.9,
        detune: 9,
        feedback: 1,
        velocity: 0.7,
        spread: 0.35,
        volume: -12.2,
      },
    },
    effects: [
      {
        deviceId: 'sympathetic',
        preset: 'Sitar drone',
        params: { root: 9, mode: 1, mix: 0.35 },
      },
      { deviceId: 'fdn-reverb', preset: 'Room', params: { mix: 0.2 } },
    ],
  },
  {
    id: 'low-tower-bells',
    name: 'Low tower bells',
    category: 'bell',
    description:
      'Heavy bells for the low keys with a clanging inharmonic strike and a long ring, across an open valley.',
    instrument: {
      deviceId: 'fm-glass',
      params: {
        ratio: 4,
        brightness: 0.6,
        decay: 5,
        attack: 0.004,
        release: 9,
        detune: 3,
        feedback: 0.2,
        velocity: 0.3,
        spread: 0.4,
        volume: -12,
      },
    },
    effects: [{ deviceId: 'fdn-reverb', preset: 'Open valley', params: { mix: 0.3 } }],
    preview: 'low',
  },
  {
    id: 'beating-bronze-bars',
    name: 'Beating bronze bars',
    category: 'bell',
    description:
      'Paired metal bars tuned fourteen cents apart so every note shimmers, with a clanging strike, in bright air.',
    instrument: {
      deviceId: 'fm-glass',
      params: {
        algorithm: 2,
        ratio: 2,
        brightness: 0.5,
        decay: 2.2,
        attack: 0.002,
        release: 6,
        detune: 14,
        velocity: 0.45,
        spread: 0.8,
        volume: -8.6,
      },
    },
    effects: [
      { deviceId: 'ambient-eq', params: { lowCut: 40, clear: 0 } },
      { deviceId: 'fdn-reverb', preset: 'Bright air', params: { mix: 0.25 } },
    ],
  },
  {
    id: 'glass-glockenspiel',
    name: 'Glass glockenspiel',
    category: 'bell',
    description:
      'A small glockenspiel: nearly pure tones with a high ping on the strike, in a room.',
    instrument: {
      deviceId: 'fm-glass',
      params: {
        algorithm: 2,
        ratio: 11,
        brightness: 0.4,
        decay: 0.9,
        attack: 0.001,
        release: 1.4,
        detune: 1,
        feedback: 0,
        spread: 0.3,
        volume: -10,
      },
    },
    effects: [{ deviceId: 'hall-reverb', preset: 'Room' }],
  },
  {
    id: 'dry-wooden-bars',
    name: 'Dry wooden bars',
    category: 'bell',
    description:
      'Short woody bar notes with no beating, close and nearly dry, for patterns in the low and middle keys.',
    instrument: {
      deviceId: 'fm-glass',
      params: {
        algorithm: 2,
        ratio: 7,
        brightness: 0.3,
        decay: 0.22,
        attack: 0.001,
        release: 0.3,
        detune: 0,
        feedback: 0,
        velocity: 0.7,
        volume: -6.1,
      },
    },
    effects: [{ deviceId: 'hall-reverb', preset: 'Tight chamber', params: { mix: 0.15 } }],
    preview: 'keys',
  },
  {
    id: 'rubbed-glass-rims',
    name: 'Rubbed glass rims',
    category: 'pad',
    description:
      'Soft held tones that fade in like a wet finger on a glass rim, beating slowly and swelling gently, in a hall.',
    instrument: {
      deviceId: 'fm-glass',
      params: {
        ratio: 1,
        brightness: 0.2,
        decay: 6,
        attack: 0.8,
        release: 2.5,
        sustain: 1,
        detune: 4,
        feedback: 0,
        velocity: 0.2,
        spread: 0.7,
        volume: -16.4,
      },
    },
    effects: [
      { deviceId: 'tremolo', preset: 'Gentle breath', params: { depth: 0.3 } },
      { deviceId: 'hall-reverb', preset: 'Hall', params: { mix: 0.25 } },
    ],
  },
  {
    id: 'glass-furnace-hum',
    name: 'Glass furnace hum',
    category: 'drone',
    description:
      'A low inharmonic hum that fades in slowly, its detuned halves beating about once a second, under a dark vault.',
    instrument: {
      deviceId: 'fm-glass',
      params: {
        algorithm: 3,
        ratio: 2,
        brightness: 0.3,
        decay: 10,
        attack: 2.5,
        release: 6,
        sustain: 1,
        detune: 24,
        feedback: 0.4,
        velocity: 0.2,
        spread: 0.35,
        volume: -13,
      },
    },
    effects: [
      { deviceId: 'ambient-eq', preset: 'Drone', params: { lowCut: 40 } },
      {
        deviceId: 'expanse',
        preset: 'Low cathedral',
        params: { decay: 14, width: 0.4, mix: 0.4 },
      },
    ],
  },
  {
    id: 'splintered-pane',
    name: 'Splintered pane',
    category: 'texture',
    description:
      'A held note under a cluster of very high overtones, broken into short grains an octave up in a glinting cave.',
    instrument: {
      deviceId: 'fm-glass',
      params: {
        algorithm: 1,
        ratio: 11,
        brightness: 0.85,
        decay: 3,
        attack: 0.2,
        sustain: 0.6,
        detune: 30,
        feedback: 1,
        velocity: 0,
        spread: 0.4,
      },
    },
    effects: [
      {
        deviceId: 'grain-cloud',
        preset: 'Glass shards',
        params: { size: 50, density: 35, scatter: 0.4, spread: 0.5, mix: 0.5 },
      },
      { deviceId: 'swarm-reverb', preset: 'Glinting', params: { width: 0.6, mix: 0.3 } },
    ],
  },
  {
    id: 'undertone-glass-pad',
    name: 'Undertone glass pad',
    category: 'pad',
    description:
      'A held pad with its modulators an octave under the notes, rough and low, on a worn cassette in a dark hall.',
    instrument: {
      deviceId: 'fm-glass',
      params: {
        algorithm: 3,
        ratio: 0,
        brightness: 0.5,
        decay: 6,
        attack: 1.2,
        release: 4,
        sustain: 1,
        detune: 8,
        feedback: 0.5,
        velocity: 0.3,
        volume: -17.5,
      },
    },
    effects: [
      { deviceId: 'patina', preset: 'Worn cassette', params: { noise: 0.3 } },
      { deviceId: 'hall-reverb', preset: 'Dark hall', params: { mix: 0.35 } },
    ],
  },
  {
    id: 'glass-mallet-bass',
    name: 'Glass mallet bass',
    category: 'bass',
    description:
      "A struck FM bass: a modulator at the note's own pitch knocks and fades into a round tone, with chorus on the top only.",
    instrument: {
      deviceId: 'fm-glass',
      params: {
        algorithm: 2,
        ratio: 1,
        brightness: 0.4,
        decay: 1.2,
        attack: 0.002,
        release: 0.3,
        sustain: 0,
        detune: 0,
        feedback: 0.25,
        velocity: 0.5,
        spread: 0,
        volume: -8.5,
      },
    },
    effects: [
      { deviceId: 'saturator', preset: 'Soft tape warmth' },
      { deviceId: 'chorus', preset: 'Wide chorus', params: { hpHz: 400, mix: 0.25 } },
    ],
  },
]
