import { type FactoryPreset } from '../types'

export const GRAFT_PRESETS: readonly FactoryPreset[] = [
  {
    id: 'breath-on-wire',
    name: 'Breath on wire',
    category: 'wind',
    description: 'A string blown instead of bowed, close and nearly dry in a small room.',
    instrument: { deviceId: 'graft', preset: 'Blown string', params: { volume: -8 } },
    effects: [{ deviceId: 'hall-reverb', preset: 'Room', params: { mix: 0.15 } }],
    preview: 'line',
  },
  {
    id: 'hollow-pipe',
    name: 'Hollow pipe',
    category: 'wind',
    description:
      'A stopped pipe with plenty of air in it, answered by a soft tape echo on a plate.',
    instrument: { deviceId: 'graft', preset: 'Blown pipe', params: { volume: -7.5 } },
    effects: [
      { deviceId: 'tape-echo', preset: 'Short and soft', params: { mix: 0.2 } },
      { deviceId: 'plate-reverb', preset: 'Small plate', params: { mix: 0.2 } },
    ],
    preview: 'line',
  },
  {
    id: 'far-pipes',
    name: 'Far pipes',
    category: 'wind',
    description: 'Stopped pipes blown softly at the far end of a very large space.',
    instrument: {
      deviceId: 'graft',
      preset: 'Blown pipe',
      params: { pressure: 0.3, swell: 0.2, release: 0.8, volume: -14 },
    },
    effects: [{ deviceId: 'expanse', preset: 'Open space', params: { mix: 0.5 } }],
    preview: 'chord',
  },
  {
    id: 'reed-row',
    name: 'Reed row',
    category: 'wind',
    description: 'A row of blown bars that buzz like free reeds, widened a little in a room.',
    instrument: { deviceId: 'graft', preset: 'Blown bar', params: { volume: -13.5 } },
    effects: [
      { deviceId: 'chorus', preset: 'Subtle widener' },
      { deviceId: 'hall-reverb', preset: 'Room', params: { mix: 0.2 } },
    ],
    preview: 'chord',
  },
  {
    id: 'bowl-breath',
    name: 'Bowl breath',
    category: 'drone',
    description: 'Air across a bowl that beats slowly against itself, held in a dark hall.',
    instrument: { deviceId: 'graft', preset: 'Blown bowl', params: { width: 0.6 } },
    effects: [{ deviceId: 'hall-reverb', preset: 'Dark hall', params: { mix: 0.3 } }],
    preview: 'hold',
  },
  {
    id: 'close-bow',
    name: 'Close bow',
    category: 'string',
    description: 'One bowed string heard from the next chair, with only a tight chamber round it.',
    instrument: { deviceId: 'graft', preset: 'Bowed string', params: { volume: -8 } },
    effects: [{ deviceId: 'hall-reverb', preset: 'Tight chamber', params: { mix: 0.12 } }],
    preview: 'line',
  },
  {
    id: 'slow-bows',
    name: 'Slow bows',
    category: 'pad',
    description: 'Bowed strings that take their time to speak, thickened into a section in a hall.',
    instrument: {
      deviceId: 'graft',
      preset: 'Bowed string',
      params: { pressure: 0.4, swell: 1.2, release: 2.5, wander: 0.5, volume: -8 },
    },
    effects: [
      { deviceId: 'chorus', preset: 'Lush ensemble' },
      { deviceId: 'hall-reverb', preset: 'Hall', params: { mix: 0.35 } },
    ],
    preview: 'chord',
  },
  {
    id: 'hollow-bow',
    name: 'Hollow bow',
    category: 'string',
    description:
      'A bow drawn across a stopped pipe, woody and hollow, with a hint of spring behind.',
    instrument: {
      deviceId: 'graft',
      preset: 'Bowed pipe',
      params: { pressure: 0.7, position: 0.2, volume: -9 },
    },
    effects: [{ deviceId: 'spring-reverb', preset: 'Hint of spring' }],
    preview: 'line',
  },
  {
    id: 'singing-bar',
    name: 'Singing bar',
    category: 'string',
    description: 'A metal bar bowed at its edge until it sings, left to ring in a bright hall.',
    instrument: { deviceId: 'graft', preset: 'Bowed bar', params: { volume: -12.5 } },
    effects: [{ deviceId: 'hall-reverb', preset: 'Bright hall', params: { mix: 0.3 } }],
    preview: 'keys',
  },
  {
    id: 'rim-song',
    name: 'Rim song',
    category: 'drone',
    description: 'A bowl rubbed round its rim, swelling slowly and turning between the speakers.',
    instrument: { deviceId: 'graft', preset: 'Bowed bowl', params: { volume: -6.5 } },
    effects: [{ deviceId: 'fdn-reverb', preset: 'Open valley', params: { mix: 0.3 } }],
    preview: 'hold',
  },
  {
    id: 'metal-bars',
    name: 'Metal bars',
    category: 'bell',
    description: 'Metal bars under mallets, with a gentle tremolo behind them in a hall.',
    instrument: { deviceId: 'graft', preset: 'Struck bar', params: { volume: -3 } },
    effects: [
      { deviceId: 'tremolo', preset: 'Amp tremolo', params: { depth: 0.3 } },
      { deviceId: 'hall-reverb', preset: 'Hall', params: { mix: 0.25 } },
    ],
    preview: 'bells',
  },
  {
    id: 'wood-bars',
    name: 'Wood bars',
    category: 'bell',
    description: 'Short wooden bars struck in the middle, dry and close in a small room.',
    instrument: { deviceId: 'graft', preset: 'Struck wood bar', params: { volume: -3 } },
    effects: [{ deviceId: 'fdn-reverb', preset: 'Short ambience', params: { mix: 0.15 } }],
    preview: 'keys',
  },
  {
    id: 'quiet-bowl',
    name: 'Quiet bowl',
    category: 'bell',
    description: 'A bowl struck once and left to beat for a long time at the far end of a nave.',
    instrument: { deviceId: 'graft', preset: 'Struck bowl', params: { width: 0.4, volume: -6.5 } },
    effects: [{ deviceId: 'hall-reverb', preset: 'Vast nave', params: { mix: 0.35 } }],
    preview: 'bells',
  },
  {
    id: 'bowl-in-mist',
    name: 'Bowl in mist',
    category: 'pad',
    description: 'Struck bowls whose ring is smeared into a hanging mist that outlasts them.',
    instrument: {
      deviceId: 'graft',
      preset: 'Struck bowl',
      params: { pressure: 0.3, position: 0.5, volume: -9.5 },
    },
    effects: [
      { deviceId: 'spectral-blur', preset: 'Hanging mist' },
      { deviceId: 'plate-reverb', preset: 'Long plate', params: { mix: 0.25 } },
    ],
    preview: 'chord',
  },
  {
    id: 'hammered-wire',
    name: 'Hammered wire',
    category: 'keys',
    description: 'A string under a small hard hammer, bright and long, with warm tape repeats.',
    instrument: {
      deviceId: 'graft',
      preset: 'Struck string',
      params: { pressure: 0.6, position: 0.2, air: 0.2, volume: -4.5 },
    },
    effects: [
      { deviceId: 'tape-echo', preset: 'Warm repeats', params: { mix: 0.2 } },
      { deviceId: 'plate-reverb', preset: 'Medium plate', params: { mix: 0.2 } },
    ],
    preview: 'keys',
  },
  {
    id: 'tube-thumps',
    name: 'Tube thumps',
    category: 'bell',
    description: 'Stopped tubes slapped on their open ends, short and breathy, in a spring tank.',
    instrument: {
      deviceId: 'graft',
      preset: 'Struck pipe',
      params: { decay: 0.9, air: 0.6, volume: -3.5 },
    },
    effects: [{ deviceId: 'spring-reverb', preset: 'Two spring tank' }],
    preview: 'low',
  },
  {
    id: 'thumb-tines',
    name: 'Thumb tines',
    category: 'plucked',
    description: 'Metal tines plucked with the thumbs, each with its scratch, in a small room.',
    instrument: { deviceId: 'graft', preset: 'Plucked bar', params: { volume: -7.5 } },
    effects: [{ deviceId: 'hall-reverb', preset: 'Room', params: { mix: 0.2 } }],
    preview: 'keys',
  },
  {
    id: 'picked-wire',
    name: 'Picked wire',
    category: 'plucked',
    description: 'A string picked near its end, dry and forward, with one short slap behind it.',
    instrument: {
      deviceId: 'graft',
      preset: 'Plucked string',
      params: { volume: -6 },
    },
    effects: [{ deviceId: 'analog-delay', preset: 'Slapback', params: { mix: 0.18 } }],
    preview: 'keys',
  },
  {
    id: 'picked-pipe',
    name: 'Picked pipe',
    category: 'plucked',
    description:
      'A pluck that rings in a stopped pipe, hollow and short, with dark echoes after it.',
    instrument: { deviceId: 'graft', preset: 'Plucked pipe', params: { decay: 1.6, volume: -3 } },
    effects: [
      { deviceId: 'analog-delay', preset: 'Dark echo', params: { mix: 0.25 } },
      { deviceId: 'plate-reverb', preset: 'Dark plate', params: { mix: 0.2 } },
    ],
    preview: 'line',
  },
  {
    id: 'wire-in-the-nave',
    name: 'Wire in the nave',
    category: 'plucked',
    description: 'Long plucked strings heard from the back of a cathedral, more room than string.',
    instrument: {
      deviceId: 'graft',
      preset: 'Plucked string',
      params: { decay: 8, pressure: 0.5, release: 3, volume: -11 },
    },
    effects: [{ deviceId: 'hall-reverb', preset: 'Cathedral', params: { mix: 0.5 } }],
    preview: 'chord',
  },
]
