import { type FactoryPreset } from '../types'

export const GRAIN_SYNTH_PRESETS: readonly FactoryPreset[] = [
  {
    id: 'frozen-grain-pad',
    name: 'Frozen moment pad',
    category: 'pad',
    description:
      'One instant of the loaded sound held still as a smooth, dark cloud to play chords on.',
    instrument: {
      deviceId: 'grain-synth',
      preset: 'Frozen moment',
      params: {
        position: 0.15,
        density: 6,
        attack: 0.3,
        release: 2.5,
        spread: 0.4,
        tone: 4000,
        volume: -13,
      },
    },
    effects: [{ deviceId: 'expanse', preset: 'Open space', params: { mix: 0.3, width: 0.8 } }],
  },
  {
    id: 'octave-grain-cloud',
    name: 'Octave grain cloud',
    category: 'pad',
    description:
      'A dense cloud that swells in slowly, with most of its grains thrown up or down an octave.',
    instrument: {
      deviceId: 'grain-synth',
      preset: 'Shimmer',
      params: {
        position: 0.1,
        density: 8,
        octaves: 0.7,
        attack: 2.5,
        release: 6,
        spread: 0.5,
        tone: 14000,
        volume: -13,
      },
    },
    effects: [{ deviceId: 'fdn-reverb', preset: 'Hall', params: { mix: 0.3 } }],
  },
  {
    id: 'backwards-grain-wash',
    name: 'Backwards wash',
    category: 'texture',
    description:
      'Long reversed grains that creep backwards through the sound and swell into a cathedral.',
    instrument: {
      deviceId: 'grain-synth',
      preset: 'Backwards wash',
      params: { position: 0.12, scan: -0.08, size: 700, spread: 0.5, volume: -10 },
    },
    effects: [{ deviceId: 'hall-reverb', preset: 'Cathedral', params: { mix: 0.35 } }],
  },
  {
    id: 'slow-tape-stretch',
    name: 'Slow tape stretch',
    category: 'texture',
    description:
      'The loaded sound played at an eighth of its speed and its own pitch, on a reel that is wearing out.',
    instrument: {
      deviceId: 'grain-synth',
      preset: 'Slow stretch',
      params: {
        size: 300,
        density: 8,
        spray: 0.05,
        attack: 0.8,
        release: 2,
        spread: 0.2,
        tone: 5000,
        volume: -4,
      },
    },
    effects: [
      { deviceId: 'tape', preset: 'Worn thin', params: { output: -3 } },
      { deviceId: 'hall-reverb', preset: 'Hall', params: { mix: 0.3 } },
    ],
  },
  {
    id: 'scattered-grains',
    name: 'Scattered grains',
    category: 'texture',
    description:
      'Single short grains picked from around one spot, thrown across octaves and repeated an octave up.',
    instrument: {
      deviceId: 'grain-synth',
      preset: 'Stutter',
      params: {
        position: 0.2,
        scan: 0.02,
        size: 80,
        density: 1,
        spray: 0.5,
        octaves: 0.5,
        shape: 0.2,
        attack: 0.05,
        release: 1.5,
        spread: 0.7,
        tone: 16000,
        volume: -7.5,
      },
    },
    effects: [
      { deviceId: 'grain-delay', preset: 'Crystals' },
      { deviceId: 'fdn-reverb', preset: 'Hall', params: { mix: 0.3 } },
    ],
  },
  {
    id: 'sample-as-keys',
    name: 'Sample as keys',
    category: 'keys',
    description:
      'The loaded sound played from its start at its own speed on every key, whatever the pitch, in a small plate.',
    instrument: {
      deviceId: 'grain-synth',
      preset: 'Slow stretch',
      params: {
        scan: 1,
        size: 120,
        spray: 0,
        attack: 0.005,
        release: 0.5,
        volume: -15.5,
      },
    },
    effects: [{ deviceId: 'plate-reverb', preset: 'Small plate', params: { mix: 0.2 } }],
  },
  {
    id: 'plain-grain-cloud',
    name: 'Plain grain cloud',
    category: 'pad',
    description:
      'A soft cloud of grains drifting slowly through the loaded sound, quick enough for chords, in a small room.',
    instrument: {
      deviceId: 'grain-synth',
      preset: 'Cloud',
      params: { attack: 0.2, volume: -14.5 },
    },
    effects: [{ deviceId: 'ether-reverb', preset: 'Room', params: { mix: 0.2 } }],
  },
  {
    id: 'grains-left-ringing',
    name: 'Grains left ringing',
    category: 'bell',
    description:
      'A held instant of the loaded sound that speaks at once and rings on for seconds after a short touch, in a bright hall.',
    instrument: {
      deviceId: 'grain-synth',
      preset: 'Frozen moment',
      params: {
        size: 160,
        octaves: 0.2,
        attack: 0.005,
        release: 7,
        tone: 15000,
        volume: -14,
      },
    },
    effects: [
      { deviceId: 'hall-reverb', preset: 'Bright hall', params: { mix: 0.25 } },
      { deviceId: 'ambient-limiter', preset: 'Margin', params: { ceiling: -4 } },
    ],
  },
  {
    id: 'low-grain-drone',
    name: 'Low grain drone',
    category: 'drone',
    description:
      'Two second grains, half of them backwards, barely moving through the loaded sound, filtered low and warmed, in a dark hall.',
    instrument: {
      deviceId: 'grain-synth',
      params: {
        position: 0.3,
        scan: 0.01,
        size: 2000,
        spray: 0.1,
        detune: 5,
        octaves: 0,
        reverse: 0.5,
        attack: 3,
        release: 9,
        spread: 0.35,
        tone: 1500,
        volume: -15,
      },
    },
    effects: [
      { deviceId: 'analog-drive', preset: 'Low warmth' },
      { deviceId: 'hall-reverb', preset: 'Dark hall', params: { mix: 0.35 } },
    ],
  },
  {
    id: 'grain-octave-organ',
    name: 'Grain octave organ',
    category: 'organ',
    description:
      'A held instant of the loaded sound with no grain at the played pitch, each an octave above or below it, in a rotary speaker.',
    instrument: {
      deviceId: 'grain-synth',
      preset: 'Frozen moment',
      params: {
        position: 0.35,
        size: 260,
        density: 12,
        spray: 0.02,
        detune: 2,
        octaves: 1,
        attack: 0.02,
        release: 0.25,
        spread: 0.3,
        tone: 6000,
        volume: -16,
      },
    },
    effects: [
      { deviceId: 'rotary', preset: 'Chorale' },
      { deviceId: 'hall-reverb', preset: 'Tight chamber' },
    ],
  },
  {
    id: 'slow-grain-pulses',
    name: 'Slow grain pulses',
    category: 'pad',
    description:
      'One long grain at a time under each key, so a held chord rises and falls in slow uneven waves, in a long plate.',
    instrument: {
      deviceId: 'grain-synth',
      params: {
        scan: 0.05,
        size: 700,
        density: 1,
        spray: 0.1,
        detune: 3,
        octaves: 0,
        reverse: 0,
        attack: 0.3,
        release: 3,
        spread: 0.25,
        tone: 8000,
        volume: -16,
      },
    },
    effects: [{ deviceId: 'plate-reverb', preset: 'Long plate', params: { mix: 0.3 } }],
  },
  {
    id: 'whole-sound-cloud',
    name: 'Whole sound cloud',
    category: 'pad',
    description:
      'Short grains pulled from all over the loaded sound at once, forwards and backwards, quick to speak, in an airy hall.',
    instrument: {
      deviceId: 'grain-synth',
      params: {
        position: 0.5,
        scan: 0,
        size: 150,
        spray: 1,
        detune: 0,
        octaves: 0,
        reverse: 0.5,
        attack: 0.1,
        release: 2.5,
        spread: 0.8,
        tone: 16000,
        volume: -16,
      },
    },
    effects: [{ deviceId: 'fdn-reverb', preset: 'Bright air', params: { mix: 0.3 } }],
  },
  {
    id: 'blurred-pitch-swarm',
    name: 'Blurred pitch swarm',
    category: 'pad',
    description:
      'Every grain lands up to a semitone off its key, so a chord smears into a swarm around its notes, in a very large space.',
    instrument: {
      deviceId: 'grain-synth',
      params: {
        position: 0.5,
        scan: 0.08,
        size: 200,
        density: 12,
        spray: 0.25,
        detune: 100,
        octaves: 0,
        reverse: 0.2,
        attack: 1.5,
        release: 4,
        spread: 0.9,
        tone: 12000,
        volume: -18,
      },
    },
    effects: [{ deviceId: 'fdn-reverb', preset: 'Open valley', params: { mix: 0.35 } }],
  },
  {
    id: 'buzzing-grain-line',
    name: 'Buzzing grain line',
    category: 'wind',
    description:
      'Grains too short to settle, restarted so fast that every note of a line comes out rough and buzzing, through a small amplifier.',
    instrument: {
      deviceId: 'grain-synth',
      params: {
        position: 0.4,
        size: 14,
        density: 2.5,
        spray: 0.02,
        detune: 0,
        octaves: 0,
        shape: 0.4,
        reverse: 0,
        attack: 0.03,
        release: 0.25,
        spread: 0.25,
        volume: -15,
      },
    },
    effects: [
      { deviceId: 're-amp', preset: 'Combo in a room' },
      { deviceId: 'ambient-limiter', preset: 'Margin', params: { ceiling: -4 } },
    ],
  },
  {
    id: 'backwards-at-speed',
    name: 'Backwards at speed',
    category: 'keys',
    description:
      'The loaded sound run backwards from its middle at its own speed under every key, whatever the pitch, into a spring tank.',
    instrument: {
      deviceId: 'grain-synth',
      params: {
        position: 0.5,
        scan: -1,
        size: 150,
        density: 4,
        spray: 0,
        detune: 0,
        octaves: 0,
        reverse: 1,
        attack: 0.01,
        release: 0.8,
        spread: 0.3,
        tone: 12000,
        volume: -16,
      },
    },
    effects: [{ deviceId: 'spring-reverb', preset: 'Two spring tank', params: { width: 0.4 } }],
  },
  {
    id: 'double-speed-scan',
    name: 'Double speed scan',
    category: 'texture',
    description:
      'The loaded sound hurried through at twice its speed, round and round, at whatever pitch the key gives it, into a tape echo.',
    instrument: {
      deviceId: 'grain-synth',
      params: {
        position: 0,
        scan: 2,
        size: 200,
        spray: 0.05,
        detune: 0,
        octaves: 0,
        reverse: 0,
        attack: 0.1,
        release: 1.5,
        spread: 0.6,
        tone: 12000,
        volume: -12.5,
      },
    },
    effects: [
      { deviceId: 'tape-echo', preset: 'Three heads', params: { spread: 0, mix: 0.3 } },
      { deviceId: 'ambient-limiter', preset: 'Margin', params: { ceiling: -4 } },
    ],
  },
  {
    id: 'fine-grain-flutter',
    name: 'Fine grain flutter',
    category: 'pad',
    description:
      'Short soft grains that barely overlap, so each held note flutters some twenty times a second, in a slow phaser and a plate.',
    instrument: {
      deviceId: 'grain-synth',
      params: {
        scan: 0.15,
        size: 60,
        density: 1.3,
        spray: 0.05,
        octaves: 0,
        reverse: 0,
        attack: 0.15,
        release: 0.8,
        spread: 0.4,
        tone: 11000,
        volume: -10,
      },
    },
    effects: [
      { deviceId: 'phaser', preset: 'Slow swirl', params: { mix: 0.35 } },
      { deviceId: 'plate-reverb', preset: 'Medium plate', params: { mix: 0.25 } },
      { deviceId: 'ambient-limiter', preset: 'Margin', params: { ceiling: -4 } },
    ],
  },
  {
    id: 'slowed-sampler-keys',
    name: 'Slowed sampler keys',
    category: 'keys',
    description:
      'The loaded sound at half its speed whatever the key, through the gritty converters of an early sampler, in a small room.',
    instrument: {
      deviceId: 'grain-synth',
      preset: 'Slow stretch',
      params: {
        position: 0.1,
        scan: 0.5,
        size: 250,
        density: 3,
        spray: 0,
        shape: 0.4,
        attack: 0.005,
        release: 1.2,
        tone: 7000,
        volume: -12,
      },
    },
    effects: [
      { deviceId: 'vintage-digital', preset: 'Sampler' },
      { deviceId: 'ether-reverb', preset: 'Room', params: { mix: 0.2 } },
      { deviceId: 'ambient-limiter', preset: 'Margin', params: { ceiling: -4 } },
    ],
  },
  {
    id: 'distant-grain-blur',
    name: 'Distant grain blur',
    category: 'pad',
    description:
      'The loaded sound passing at its own speed, blurred by long grains picked from around each moment, heard from far down a hall.',
    instrument: {
      deviceId: 'grain-synth',
      params: {
        position: 0,
        scan: 1,
        size: 1000,
        density: 10,
        spray: 0.4,
        detune: 4,
        octaves: 0,
        reverse: 0.3,
        attack: 1.2,
        release: 4,
        spread: 0.25,
        tone: 6000,
        volume: -19,
      },
    },
    effects: [{ deviceId: 'hall-reverb', preset: 'Far away', params: { mix: 0.5 } }],
  },
  {
    id: 'grain-locked-groove',
    name: 'Grain locked groove',
    category: 'texture',
    description:
      'A slice of the loaded sound under half a second long, cut square and repeated a little unevenly, on a dusty record that crackles on after.',
    instrument: {
      deviceId: 'grain-synth',
      preset: 'Stutter',
      params: {
        scan: 0,
        size: 450,
        density: 1,
        shape: 1,
        release: 0.4,
        spread: 0.1,
        tone: 9000,
        volume: -10,
      },
    },
    effects: [
      { deviceId: 'vinyl', preset: 'Dust and scratches' },
      { deviceId: 'fdn-reverb', preset: 'Room', params: { mix: 0.15 } },
      { deviceId: 'ambient-limiter', preset: 'Margin', params: { ceiling: -4 } },
    ],
  },
]
