import { type FactoryPreset } from '../types'

export const MODAL_BELLS_PRESETS: readonly FactoryPreset[] = [
  {
    id: 'rubbed-bowls',
    name: 'Rubbed bowls',
    category: 'bell',
    description: 'Bronze bowls rubbed until they sing and left to ring into each other in a hall.',
    instrument: {
      deviceId: 'modal-bells',
      preset: 'Rubbed bowl',
      params: { decay: 7, release: 0.3, volume: -8 },
    },
    effects: [{ deviceId: 'hall-reverb', preset: 'Hall', params: { mix: 0.3 } }],
    preview: 'line',
  },
  {
    id: 'kalimba-backwards-echo',
    name: 'Kalimba backwards echo',
    category: 'bell',
    description: 'A dry thumb piano whose notes come back reversed, in a small wooden room.',
    instrument: {
      deviceId: 'modal-bells',
      preset: 'Kalimba',
      params: { hardness: 0.8, brightness: 0.65, volume: -5.5 },
    },
    effects: [
      { deviceId: 'reverse-delay', preset: 'Backwards echo' },
      { deviceId: 'hall-reverb', preset: 'Room', params: { mix: 0.25 } },
    ],
  },
  {
    id: 'motor-vibraphone',
    name: 'Motor vibraphone',
    category: 'bell',
    description: 'Vibraphone bars with the pedal down and the motor turning slowly, on a plate.',
    instrument: {
      deviceId: 'modal-bells',
      preset: 'Vibraphone',
      params: { release: 0.3, volume: -4 },
    },
    effects: [
      { deviceId: 'tremolo', preset: 'Amp tremolo', params: { rate: 3.2, depth: 0.45, phase: 90 } },
      { deviceId: 'plate-reverb', preset: 'Long plate', params: { mix: 0.35 } },
    ],
  },
  {
    id: 'worn-music-box',
    name: 'Worn music box',
    category: 'bell',
    description: 'A small music box comb recorded on cassette, a little unsteady, in a bedroom.',
    instrument: {
      deviceId: 'modal-bells',
      preset: 'Music box',
      params: { spread: 0.4, volume: -4 },
    },
    effects: [
      { deviceId: 'tape', preset: 'Cassette four-track', params: { hiss: 0.3 } },
      { deviceId: 'fdn-reverb', preset: 'Room', params: { mix: 0.3 } },
    ],
  },
  {
    id: 'distant-gong',
    name: 'Distant gong',
    category: 'bell',
    description: 'A large gong struck once, its tail sinking and darkening across a wide space.',
    instrument: {
      deviceId: 'modal-bells',
      preset: 'Gong',
      params: { damping: 0.3, hardness: 0.75, brightness: 0.8, spread: 0.6, volume: -7 },
    },
    effects: [{ deviceId: 'bloom-reverb', preset: 'Long dark', params: { mix: 0.4, width: 0.4 } }],
    preview: 'low',
  },
  {
    id: 'short-wood-marimba',
    name: 'Short wood marimba',
    category: 'bell',
    description:
      'Wooden bars under medium mallets, struck off centre and gone in a second, in a small room.',
    instrument: {
      deviceId: 'modal-bells',
      preset: 'Vibraphone',
      params: {
        decay: 1.4,
        damping: 0.85,
        hardness: 0.55,
        position: 0.75,
        detune: 0.1,
        brightness: 0.45,
        release: 0.4,
        spread: 0.1,
        volume: -8,
      },
    },
    effects: [
      { deviceId: 'plate-reverb', preset: 'Tight room' },
      { deviceId: 'ambient-limiter', preset: 'Wall only', params: { ceiling: -3, gain: 6 } },
    ],
    preview: 'keys',
  },
  {
    id: 'toy-piano-rods',
    name: 'Toy piano rods',
    category: 'keys',
    description:
      'Hard little hammers on steel rods clamped at one end, bright and clanky, in a small still room.',
    instrument: {
      deviceId: 'modal-bells',
      preset: 'Kalimba',
      params: {
        decay: 1.8,
        damping: 0.4,
        hardness: 0.9,
        position: 0.05,
        detune: 0.2,
        brightness: 0.8,
        release: 0.3,
        spread: 0.2,
        volume: -13.5,
      },
    },
    effects: [
      { deviceId: 'bloom-reverb', preset: 'Still room', params: { decay: 1.6 } },
      { deviceId: 'ambient-limiter', preset: 'Wall only', params: { ceiling: -3, gain: 7 } },
    ],
  },
  {
    id: 'felt-hammer-celesta',
    name: 'Felt hammer celesta',
    category: 'keys',
    description:
      'Steel plates under felt hammers, round and quick to fade, with a faint detuned halo, in a chamber.',
    instrument: {
      deviceId: 'modal-bells',
      preset: 'Music box',
      params: {
        damping: 0.5,
        hardness: 0.35,
        position: 0.85,
        detune: 0.15,
        brightness: 0.4,
        release: 0.45,
        spread: 0.15,
        volume: -10,
      },
    },
    effects: [
      { deviceId: 'stereo-detune', preset: 'Soft halo' },
      { deviceId: 'hall-reverb', preset: 'Tight chamber' },
      { deviceId: 'ambient-limiter', preset: 'Wall only', params: { ceiling: -3, gain: 3 } },
    ],
  },
  {
    id: 'slit-tongue-drum',
    name: 'Slit tongue drum',
    category: 'bell',
    description:
      'Steel tongues whose first overtone is an octave, tapped softly, with sympathetic strings in A minor and a hall behind.',
    instrument: {
      deviceId: 'modal-bells',
      preset: 'Music box',
      params: {
        decay: 6,
        damping: 0.35,
        hardness: 0.45,
        position: 0.8,
        detune: 0.1,
        stretch: 0.68,
        release: 0.15,
        spread: 0.2,
        volume: -13,
      },
    },
    effects: [
      { deviceId: 'sympathetic', preset: 'Minor strings', params: { mix: 0.2, width: 0.3 } },
      { deviceId: 'fdn-reverb', preset: 'Hall', params: { mix: 0.2 } },
    ],
    preview: 'keys',
  },
  {
    id: 'bow-on-vibraphone',
    name: 'Bow on vibraphone',
    category: 'pad',
    description:
      'Vibraphone bars drawn with a bow instead of struck, steady and glassy, a drifting copy either side, in a hall.',
    instrument: {
      deviceId: 'modal-bells',
      preset: 'Vibraphone',
      params: {
        decay: 9,
        damping: 0.4,
        hardness: 0.1,
        detune: 0,
        sustain: 1,
        brightness: 0.85,
        release: 0.35,
        spread: 0,
        volume: -16.5,
      },
    },
    effects: [
      { deviceId: 'stereo-detune', preset: 'Drifting', params: { mix: 0.35 } },
      { deviceId: 'hall-reverb', preset: 'Hall', params: { mix: 0.3 } },
    ],
  },
  {
    id: 'rubbed-bowl-organ',
    name: 'Rubbed bowl organ',
    category: 'organ',
    description:
      'Rubbed bowls with their overtones squeezed into octave and twelfth, turning in a rotary speaker.',
    instrument: {
      deviceId: 'modal-bells',
      preset: 'Rubbed bowl',
      params: {
        decay: 6,
        damping: 0.3,
        hardness: 0.1,
        detune: 0,
        stretch: 0.675,
        brightness: 0.8,
        release: 0.6,
        spread: 0.7,
        volume: -16.5,
      },
    },
    effects: [
      { deviceId: 'rotary', preset: 'Chorale', params: { drive: 0.1 } },
      { deviceId: 'hall-reverb', preset: 'Hall', params: { mix: 0.25 } },
    ],
  },
  {
    id: 'paired-bronze-bars',
    name: 'Paired bronze bars',
    category: 'bell',
    description:
      'Bronze bars tuned in pairs a few hertz apart so every note shimmers fast, in bright air.',
    instrument: {
      deviceId: 'modal-bells',
      preset: 'Music box',
      params: {
        decay: 5,
        damping: 0.25,
        hardness: 0.7,
        position: 0.05,
        detune: 6.5,
        release: 0.1,
        spread: 0.2,
        volume: -4.5,
      },
    },
    effects: [{ deviceId: 'fdn-reverb', preset: 'Bright air', params: { mix: 0.25 } }],
  },
  {
    id: 'great-tower-bell',
    name: 'Great tower bell',
    category: 'bell',
    description:
      'The largest bell in the tower, struck low: a hum an octave under the note, in a large dark space.',
    instrument: {
      deviceId: 'modal-bells',
      preset: 'Church bell',
      params: {
        decay: 32,
        damping: 0.4,
        position: 0,
        detune: 0.9,
        brightness: 0.65,
        spread: 0.5,
        volume: -16,
      },
    },
    effects: [
      { deviceId: 'fdn-reverb', preset: 'Dark cave', params: { mix: 0.3 } },
      { deviceId: 'ambient-limiter', preset: 'Wall only', params: { ceiling: -3, gain: 5 } },
    ],
    preview: 'low',
  },
  {
    id: 'brass-disc-crotales',
    name: 'Brass disc crotales',
    category: 'bell',
    description:
      'Small thick brass discs struck with a hard beater, high and exact, on a bright plate.',
    instrument: {
      deviceId: 'modal-bells',
      preset: 'Gong',
      params: {
        decay: 10,
        damping: 0.15,
        hardness: 0.9,
        position: 0.1,
        detune: 0.1,
        stretch: 1.27,
        brightness: 0.55,
        release: 0.05,
        spread: 0.1,
        volume: -10,
      },
    },
    effects: [{ deviceId: 'plate-reverb', preset: 'Bright plate', params: { mix: 0.3 } }],
  },
  {
    id: 'long-tube-chimes',
    name: 'Long tube chimes',
    category: 'bell',
    description:
      'Hanging metal tubes heard from a distance, single strokes flickering back as if a breeze moved them.',
    instrument: {
      deviceId: 'modal-bells',
      preset: 'Music box',
      params: {
        decay: 9,
        damping: 0.12,
        hardness: 0.8,
        position: 0.02,
        detune: 0.2,
        brightness: 0.7,
        release: 0,
        spread: 0.3,
        volume: -11.5,
      },
    },
    effects: [
      { deviceId: 'echo-memory', preset: 'Flickers', params: { mix: 0.3 } },
      { deviceId: 'expanse', preset: 'Thin air', params: { mix: 0.6 } },
      { deviceId: 'ambient-limiter', preset: 'Wall only', params: { ceiling: -3, gain: 6 } },
    ],
  },
  {
    id: 'bowed-steel-sheet',
    name: 'Bowed steel sheet',
    category: 'texture',
    description:
      'A sheet of steel struck once and kept sounding with a bow, its crowded overtones beating, in one slack spring.',
    instrument: {
      deviceId: 'modal-bells',
      preset: 'Gong',
      params: {
        decay: 14,
        damping: 0.3,
        hardness: 0.7,
        position: 0.3,
        detune: 3,
        stretch: 0.6,
        sustain: 0.8,
        brightness: 0.8,
        release: 0.3,
        volume: -9,
      },
    },
    effects: [
      { deviceId: 'stereo-widener', preset: 'Narrow', params: { width: 0.15 } },
      { deviceId: 'spring-reverb', preset: 'Single slack coil', params: { mix: 0.3 } },
      { deviceId: 'ambient-limiter', preset: 'Master', params: { ceiling: -3, gain: 2 } },
    ],
  },
  {
    id: 'rubbed-bell-hum',
    name: 'Rubbed bell hum',
    category: 'drone',
    description:
      'A heavy bell rubbed until its hum holds an octave under the note, turning slowly, in a dark hall.',
    instrument: {
      deviceId: 'modal-bells',
      preset: 'Church bell',
      params: {
        decay: 20,
        damping: 0.6,
        hardness: 0.1,
        position: 0.5,
        detune: 0.4,
        sustain: 1,
        brightness: 0.9,
        release: 0.35,
        spread: 1,
        volume: -5.5,
      },
    },
    effects: [{ deviceId: 'hall-reverb', preset: 'Dark hall', params: { mix: 0.3 } }],
    preview: 'hold',
  },
  {
    id: 'tapped-icicles',
    name: 'Tapped icicles',
    category: 'bell',
    description:
      'Thin glass tapped hard, its overtones pulled apart and bright, with reversed splinters an octave up.',
    instrument: {
      deviceId: 'modal-bells',
      preset: 'Glass harp',
      params: {
        decay: 2.2,
        damping: 0.2,
        hardness: 0.9,
        position: 0,
        detune: 0.4,
        stretch: 1.3,
        sustain: 0,
        brightness: 0.85,
        release: 0.2,
        spread: 0.1,
        volume: -14,
      },
    },
    effects: [
      { deviceId: 'reverse-delay', preset: 'Glass splinters', params: { mix: 0.2 } },
      { deviceId: 'plate-reverb', preset: 'Small plate' },
      { deviceId: 'ambient-limiter', preset: 'Wall only', params: { ceiling: -3, gain: 7 } },
    ],
  },
  {
    id: 'clock-chime-rods',
    name: 'Clock chime rods',
    category: 'bell',
    description:
      'The long steel rods of a hall clock struck by its hammers, on a worn dictation tape.',
    instrument: {
      deviceId: 'modal-bells',
      preset: 'Kalimba',
      params: {
        decay: 8,
        damping: 0.15,
        hardness: 0.85,
        position: 0.05,
        detune: 0.3,
        brightness: 0.8,
        release: 0,
        spread: 0.1,
        volume: -12,
      },
    },
    effects: [
      { deviceId: 'tape', preset: 'Old dictation', params: { hiss: 0.4 } },
      { deviceId: 'hall-reverb', preset: 'Room', params: { mix: 0.2 } },
    ],
  },
  {
    id: 'tuning-fork-keys',
    name: 'Tuning fork keys',
    category: 'keys',
    description:
      'A keyboard of tuning forks: pure soft tones with a faint clang, in a light chorus and a small room.',
    instrument: {
      deviceId: 'modal-bells',
      preset: 'Kalimba',
      params: {
        decay: 5,
        damping: 0.55,
        hardness: 0.65,
        position: 0.5,
        detune: 0.15,
        brightness: 0.3,
        release: 0.55,
        spread: 0,
        volume: -6,
      },
    },
    effects: [
      { deviceId: 'chorus', preset: 'Classic chorus', params: { mix: 0.15 } },
      { deviceId: 'bloom-reverb', preset: 'Still room', params: { decay: 2, mix: 0.25 } },
    ],
  },
]
