import { type FactoryPreset } from '../types'

export const ORGAN_PRESETS: readonly FactoryPreset[] = [
  {
    id: 'parlour-pump-organ',
    name: 'Parlour pump organ',
    category: 'organ',
    description: 'A reedy pump organ with an uneven bellows, close up in a small room on old tape.',
    instrument: { deviceId: 'organ', preset: 'Pump organ', params: { celeste: 0.5, volume: -10 } },
    effects: [
      { deviceId: 'tape', preset: 'Cassette four-track', params: { hiss: 0.25, output: -3.5 } },
      { deviceId: 'hall-reverb', preset: 'Room', params: { mix: 0.35 } },
      { deviceId: 'stereo-widener', preset: 'Wide' },
    ],
  },
  {
    id: 'chapel-flutes-nave',
    name: 'Chapel flutes',
    category: 'organ',
    description: 'Stopped flutes with no reed at all, speaking quickly into a long stone nave.',
    instrument: { deviceId: 'organ', preset: 'Chapel flutes', params: { volume: -14 } },
    effects: [{ deviceId: 'hall-reverb', preset: 'Cathedral', params: { mix: 0.4 } }],
  },
  {
    id: 'slow-rotary-organ',
    name: 'Slow rotary organ',
    category: 'organ',
    description:
      'A fuller registration through a rotating speaker on its slow setting and a plate.',
    instrument: {
      deviceId: 'organ',
      preset: 'Full organ',
      params: { sub: 0.4, reed: 0.4, twelfth: 0.3, fifteenth: 0.45, release: 0.5, volume: -12 },
    },
    effects: [
      { deviceId: 'rotary', preset: 'Chorale' },
      { deviceId: 'plate-reverb', preset: 'Small plate', params: { decay: 0.7 } },
    ],
  },
  {
    id: 'distant-pipes-swell',
    name: 'Distant pipes',
    category: 'organ',
    description: 'Pipes heard from the far end of the building: three seconds to speak, all tail.',
    instrument: { deviceId: 'organ', preset: 'Distant pipes', params: { volume: -12 } },
    effects: [{ deviceId: 'expanse', preset: 'Open space', params: { mix: 0.45 } }],
  },
  {
    id: 'celeste-reed-drone',
    name: 'Celeste reed drone',
    category: 'drone',
    description:
      'Two low ranks tuned slightly apart so they beat, with upper octaves blooming behind.',
    instrument: {
      deviceId: 'organ',
      preset: 'Celeste drone',
      params: { sub: 0.35, octave: 0.4, reed: 0.3, celeste: 1, tone: 2600, volume: -14 },
    },
    effects: [
      { deviceId: 'saturator', preset: 'Warm glue' },
      { deviceId: 'shimmer', preset: 'Organ loft', params: { mix: 0.3 } },
    ],
  },
  {
    id: 'small-chamber-organ',
    name: 'Small chamber organ',
    category: 'organ',
    description:
      'Three flute ranks stacked in octaves with no sub rank, quick to speak, close in a tight chamber.',
    instrument: {
      deviceId: 'organ',
      preset: 'Chapel flutes',
      params: {
        sub: 0,
        octave: 0.6,
        fifteenth: 0.4,
        breath: 0.2,
        bellows: 0,
        attack: 0.03,
        release: 0.15,
        tone: 7000,
        volume: -12,
      },
    },
    effects: [{ deviceId: 'hall-reverb', preset: 'Tight chamber', params: { mix: 0.25 } }],
  },
  {
    id: 'bright-parish-organ',
    name: 'Bright parish organ',
    category: 'organ',
    description:
      'Bright principal ranks with little sub and the tone wide open, in a church of two and a half seconds.',
    instrument: {
      deviceId: 'organ',
      preset: 'Full organ',
      params: {
        sub: 0.15,
        octave: 0.85,
        twelfth: 0.4,
        fifteenth: 0.85,
        reed: 0.4,
        celeste: 0,
        bellows: 0.05,
        attack: 0.06,
        release: 0.3,
        tone: 12000,
        volume: -14,
      },
    },
    effects: [
      {
        deviceId: 'fdn-reverb',
        preset: 'Hall',
        params: { decay: 2.5, breathDepth: 0, mix: 0.3 },
      },
    ],
  },
  {
    id: 'tonewheel-and-chorus',
    name: 'Tonewheel and chorus',
    category: 'organ',
    description:
      'Pure tonewheel flutes that switch on and off at once, through a fast chorus vibrato and a combo amplifier.',
    instrument: {
      deviceId: 'organ',
      params: {
        sub: 0.85,
        octave: 0.55,
        twelfth: 0.35,
        fifteenth: 0,
        reed: 0,
        celeste: 0,
        breath: 0,
        bellows: 0,
        attack: 0.005,
        release: 0.04,
        tone: 5000,
        volume: -9.5,
      },
    },
    effects: [
      {
        deviceId: 'chorus',
        preset: 'Classic chorus',
        params: { rate: 6.5, depth: 20, delayMs: 6, mix: 0.4 },
      },
      { deviceId: 're-amp', preset: 'Combo in a room', params: { drive: 0.2, mix: 0.8 } },
    ],
  },
  {
    id: 'swell-string-stops',
    name: 'Swell string stops',
    category: 'organ',
    description:
      'Thin string stops with a second rank tuned sharp so the chord beats slowly, no sub, easing in over half a second in a hall.',
    instrument: {
      deviceId: 'organ',
      preset: 'Harmonium',
      params: {
        sub: 0,
        octave: 0.25,
        twelfth: 0,
        fifteenth: 0.1,
        reed: 0.5,
        celeste: 0.75,
        breath: 0.08,
        bellows: 0.15,
        attack: 0.6,
        release: 1.4,
        tone: 3800,
        volume: -12,
      },
    },
    effects: [{ deviceId: 'hall-reverb', preset: 'Hall' }],
  },
  {
    id: 'trembling-reed-stop',
    name: 'Trembling reed stop',
    category: 'organ',
    description:
      'A nasal reed stop with a rank a twelfth above, shaken by its tremulant like a thin voice, far off in a dark hall.',
    instrument: {
      deviceId: 'organ',
      preset: 'Harmonium',
      params: {
        sub: 0.1,
        octave: 0.15,
        twelfth: 0.4,
        fifteenth: 0,
        reed: 1,
        celeste: 0,
        breath: 0.15,
        bellows: 0.1,
        tremulant: 0.75,
        attack: 0.15,
        release: 0.8,
        tone: 2600,
        volume: -13,
      },
    },
    effects: [
      {
        deviceId: 'hall-reverb',
        preset: 'Dark hall',
        params: { lowDecay: 5, midDecay: 4, mix: 0.6 },
      },
    ],
  },
  {
    id: 'hollow-quint-flute',
    name: 'Hollow quint flute',
    category: 'wind',
    description:
      'A solo flute with a strong rank a twelfth above and nothing between, hollow and plain, with dark repeats in a room.',
    instrument: {
      deviceId: 'organ',
      preset: 'Tremulant flute',
      params: {
        octave: 0,
        twelfth: 0.9,
        reed: 0,
        breath: 0.8,
        bellows: 0.1,
        tremulant: 0.15,
        attack: 0.04,
        release: 0.25,
        tone: 5000,
        volume: -7,
      },
    },
    effects: [
      { deviceId: 'analog-delay', preset: 'Dark echo', params: { mix: 0.25 } },
      { deviceId: 'hall-reverb', preset: 'Room' },
    ],
  },
  {
    id: 'struck-pipe-chimes',
    name: 'Struck pipe chimes',
    category: 'bell',
    description:
      'High flute ranks that speak at once and fade slowly after the key lifts, like struck pipes, in a bright hall.',
    instrument: {
      deviceId: 'organ',
      preset: 'Chapel flutes',
      params: {
        sub: 0,
        octave: 0.5,
        twelfth: 0.3,
        fifteenth: 0.9,
        breath: 0.5,
        bellows: 0,
        attack: 0.005,
        release: 4,
        tone: 10000,
        volume: -6.5,
      },
    },
    effects: [{ deviceId: 'fdn-reverb', preset: 'Bright air', params: { mix: 0.3 } }],
  },
  {
    id: 'ice-rink-organ',
    name: 'Ice rink organ',
    category: 'organ',
    description:
      'Flutes and a little reed under a full tremulant, thin through a horn loudspeaker across a big hall.',
    instrument: {
      deviceId: 'organ',
      params: {
        sub: 0.6,
        octave: 0.6,
        twelfth: 0.45,
        fifteenth: 0.2,
        celeste: 0,
        breath: 0.05,
        bellows: 0,
        tremulant: 1,
        attack: 0.01,
        release: 0.1,
        tone: 6000,
        volume: -13,
      },
    },
    effects: [
      {
        deviceId: 're-amp',
        preset: 'Station platform',
        params: { drive: 0.3, noise: 0.05, mix: 0.85 },
      },
      {
        deviceId: 'fdn-reverb',
        preset: 'Hall',
        params: { decay: 3.5, breathDepth: 0, mix: 0.35 },
      },
    ],
  },
  {
    id: 'swell-box-breathing',
    name: 'Swell box breathing',
    category: 'organ',
    description:
      'Reedy ranks behind swell shutters that open and close every five seconds, worked by a slow low pass filter, in a hall.',
    instrument: {
      deviceId: 'organ',
      preset: 'Full organ',
      params: {
        sub: 0.5,
        octave: 0.6,
        twelfth: 0.3,
        fifteenth: 0.4,
        reed: 0.7,
        celeste: 0.1,
        attack: 0.15,
        release: 1,
        tone: 8000,
        volume: -14.5,
      },
    },
    effects: [
      {
        deviceId: 'auto-filter',
        preset: 'Glacial low-pass',
        params: { cutoffHz: 900, resonance: 0.8, driveDb: 0, lfoAmount: 60, lfoRateHz: 0.2 },
      },
      { deviceId: 'hall-reverb', preset: 'Hall', params: { mix: 0.3 } },
    ],
  },
  {
    id: 'upper-ranks-rising',
    name: 'Upper ranks rising',
    category: 'pad',
    description:
      'No sub and strong upper ranks, bright and glassy, swelling in over two seconds and slow to leave, with a long bright tail.',
    instrument: {
      deviceId: 'organ',
      preset: 'Full organ',
      params: {
        sub: 0,
        twelfth: 0.4,
        fifteenth: 0.75,
        reed: 0.2,
        celeste: 0.3,
        breath: 0.2,
        bellows: 0.2,
        attack: 4.5,
        release: 5,
        tone: 10000,
        volume: -12,
      },
    },
    effects: [{ deviceId: 'hall-reverb', preset: 'Airy tail', params: { mix: 0.4 } }],
  },
  {
    id: 'reed-box-drone',
    name: 'Reed box drone',
    category: 'drone',
    description:
      'A bright buzzing reed drone with no sub and a slow bellows, with tuned strings ringing in sympathy behind it.',
    instrument: {
      deviceId: 'organ',
      preset: 'Pump organ',
      params: {
        sub: 0,
        octave: 0.6,
        twelfth: 0.25,
        fifteenth: 0.2,
        reed: 1,
        celeste: 0.35,
        breath: 0.3,
        bellows: 0.6,
        attack: 0.8,
        release: 2,
        tone: 4200,
        volume: -14,
      },
    },
    effects: [
      { deviceId: 'sympathetic', preset: 'Minor strings', params: { width: 0.3, mix: 0.35 } },
      { deviceId: 'hall-reverb', preset: 'Room' },
    ],
  },
  {
    id: 'pedal-and-piccolo',
    name: 'Pedal and piccolo',
    category: 'drone',
    description:
      'The sub rank and a rank two octaves up with the octave between left out, rocked slowly from dark to bright, in a hall.',
    instrument: {
      deviceId: 'organ',
      params: {
        sub: 1,
        octave: 0,
        twelfth: 0,
        fifteenth: 0.85,
        reed: 0.05,
        celeste: 0.15,
        bellows: 0.2,
        attack: 0.5,
        release: 2.5,
        tone: 7000,
        volume: -6.5,
      },
    },
    effects: [
      { deviceId: 'tremolo', preset: 'Tilting tone', params: { phase: 30, crossover: 200 } },
      { deviceId: 'hall-reverb', preset: 'Hall' },
    ],
  },
  {
    id: 'ciphering-pipes',
    name: 'Ciphering pipes',
    category: 'organ',
    description:
      'Flute pipes that go on sounding for seconds after the keys lift, as if stuck open, held by a sustainer in a hall.',
    instrument: {
      deviceId: 'organ',
      preset: 'Chapel flutes',
      params: {
        sub: 0.3,
        octave: 0.45,
        fifteenth: 0.2,
        reed: 0.1,
        attack: 0.05,
        release: 0.3,
        volume: -14,
      },
    },
    effects: [
      {
        deviceId: 'sustainer',
        preset: 'Glass organ',
        params: { decay: 20, tone: 0.2, lowCut: 60, mix: 0.6 },
      },
      { deviceId: 'hall-reverb', preset: 'Hall', params: { mix: 0.3 } },
    ],
  },
  {
    id: 'flute-pipe-cascade',
    name: 'Flute pipe cascade',
    category: 'keys',
    description:
      'Flute notes that speak at once and come back as loops of themselves an octave and more above, fading in a hall.',
    instrument: {
      deviceId: 'organ',
      preset: 'Chapel flutes',
      params: {
        sub: 0.1,
        octave: 0.5,
        fifteenth: 0.3,
        breath: 0.35,
        attack: 0.008,
        release: 0.12,
        tone: 6000,
      },
    },
    effects: [
      {
        deviceId: 'cascade',
        preset: 'Octave stack',
        params: { time: 300, repeats: 6, high: 0.7, mix: 0.4 },
      },
      { deviceId: 'fdn-reverb', preset: 'Hall', params: { breathDepth: 0, mix: 0.3 } },
    ],
  },
  {
    id: 'medium-wave-organ',
    name: 'Medium wave organ',
    category: 'organ',
    description:
      'A full organ in a hall over a medium wave set with a small speaker: thin, boxy and narrow, with static that stays on after the notes.',
    instrument: {
      deviceId: 'organ',
      preset: 'Full organ',
      params: {
        sub: 0.6,
        twelfth: 0.4,
        fifteenth: 0.5,
        reed: 0.45,
        attack: 0.08,
        release: 0.6,
        tone: 6000,
        volume: -14.5,
      },
    },
    effects: [
      { deviceId: 'hall-reverb', preset: 'Hall' },
      {
        deviceId: 'radio',
        preset: 'Kitchen radio',
        params: { fading: 0.3, static: 0.12, interference: 0, speaker: 0.7 },
      },
      { deviceId: 'fdn-reverb', preset: 'Room', params: { mix: 0.2 } },
    ],
  },
  {
    id: 'reed-organ-pedal',
    name: 'Reed organ pedal',
    category: 'bass',
    description:
      'Reed organ pedal notes, a reedy rank with a quieter octave under it, through a slowly turning mono cabinet in a chamber.',
    instrument: {
      deviceId: 'organ',
      params: {
        sub: 0.3,
        octave: 0.25,
        twelfth: 0,
        fifteenth: 0,
        reed: 0.4,
        celeste: 0,
        breath: 0.1,
        bellows: 0,
        attack: 0.03,
        release: 0.25,
        tone: 1500,
        volume: -7,
      },
    },
    effects: [
      { deviceId: 'rotary', preset: 'Mono cabinet' },
      { deviceId: 'hall-reverb', preset: 'Tight chamber', params: { mix: 0.1 } },
    ],
  },
]
