import { type FactoryPreset } from '../types'

export const SUB_BASS_PRESETS: readonly FactoryPreset[] = [
  {
    id: 'pure-sine-sub-floor',
    name: 'Pure sine sub floor',
    category: 'bass',
    description:
      'A plain sine with nothing added, held while the key is down and let go over a second, its bottom lifted by a clean tape head bump.',
    instrument: {
      deviceId: 'sub-bass',
      preset: 'Pure sine',
      params: {
        shape: 0,
        harmonics: 0,
        drop: 0,
        fall: 40,
        attack: 0.03,
        decay: 20,
        release: 1,
        drive: 0,
        glide: 0.08,
        volume: -18,
      },
    },
    effects: [{ deviceId: 'tape', preset: 'Clean transfer', params: { bump: 0.5 } }],
  },
  {
    id: 'blooming-sub-swell',
    name: 'Blooming sub swell',
    category: 'bass',
    description:
      'A round sub that blooms out of silence in most of a second and fades over four, so a line runs into one bed, warmed by a transformer.',
    instrument: {
      deviceId: 'sub-bass',
      preset: 'Slow swell',
      params: {
        shape: 0.2,
        harmonics: 0.3,
        drop: 0,
        fall: 40,
        attack: 0.7,
        decay: 20,
        release: 4,
        drive: 0.25,
        glide: 0.3,
        volume: -16,
      },
    },
    effects: [{ deviceId: 'analog-drive', preset: 'Low warmth', params: { output: -9 } }],
  },
  {
    id: 'slow-pulsing-sub',
    name: 'Slow pulsing sub',
    category: 'bass',
    description:
      'A soft sub that hangs for two seconds after each key while a tremolo turns it down by 10 dB and up again twice a second.',
    instrument: {
      deviceId: 'sub-bass',
      preset: 'Soft sub',
      params: {
        shape: 0.15,
        harmonics: 0.25,
        drop: 0,
        fall: 40,
        attack: 0.12,
        decay: 20,
        release: 2.5,
        drive: 0.1,
        glide: 0.06,
        volume: -13,
      },
    },
    effects: [
      {
        deviceId: 'tremolo',
        preset: 'Gentle breath',
        params: { rate: 2, depth: 0.7, drift: 0, smooth: 0.4 },
      },
    ],
  },
  {
    id: 'sighing-sub-fall',
    name: 'Sighing sub fall',
    category: 'bass',
    description:
      'Each note fades in an octave high and sinks onto its pitch in over half a second, in a small dark room that stays above the bass.',
    instrument: {
      deviceId: 'sub-bass',
      preset: 'Falling sigh',
      params: {
        shape: 0.05,
        harmonics: 0.2,
        drop: 12,
        fall: 600,
        attack: 0.35,
        decay: 5,
        release: 3,
        drive: 0,
        glide: 0.06,
        volume: -14.5,
      },
    },
    effects: [
      {
        deviceId: 'expanse',
        preset: 'Small dark room',
        params: { lowCut: 250, width: 0.6, mix: 0.25 },
      },
    ],
  },
  {
    id: 'wavering-cassette-sub',
    name: 'Wavering cassette sub',
    category: 'bass',
    description:
      'A soft round sub with a little octave in it on a cassette four-track: it wavers by about ten cents and sits in a little hiss.',
    instrument: {
      deviceId: 'sub-bass',
      preset: 'Pure sine',
      params: {
        shape: 0.3,
        harmonics: 0.35,
        drop: 0,
        fall: 40,
        attack: 0.03,
        decay: 20,
        release: 1.2,
        drive: 0,
        glide: 0.08,
        volume: -18.5,
      },
    },
    effects: [{ deviceId: 'tape', preset: 'Cassette four-track', params: { wow: 0.5, hiss: 0.3 } }],
  },
  {
    id: 'soft-sub-pulse-box',
    name: 'Soft sub pulse',
    category: 'bass',
    description:
      'A soft pulse with a rounded start that dies away in a second and a half, with an octave over it for a small box to answer.',
    instrument: {
      deviceId: 'sub-bass',
      preset: 'Soft pulse',
      params: {
        shape: 0.1,
        harmonics: 0.4,
        drop: 0,
        fall: 40,
        attack: 0.08,
        decay: 1.6,
        release: 0.9,
        drive: 0,
        glide: 0.06,
        volume: -11,
      },
    },
    effects: [
      { deviceId: 'expanse', preset: 'Small box', params: { lowCut: 200, width: 0.5, mix: 0.25 } },
    ],
  },
  {
    id: 'knocked-soft-sub',
    name: 'Knocked soft sub',
    category: 'bass',
    description:
      'The plain soft sub: a fifth of fall at the start of each note for a soft knock, then a held round tone on warm tape.',
    instrument: {
      deviceId: 'sub-bass',
      preset: 'Soft sub',
      params: {
        shape: 0.15,
        harmonics: 0.2,
        drop: 7,
        fall: 40,
        attack: 0.004,
        decay: 20,
        release: 0.4,
        drive: 0.15,
        glide: 0.06,
        volume: -17.5,
      },
    },
    effects: [{ deviceId: 'saturator', preset: 'Soft tape warmth' }],
  },
  {
    id: 'gliding-sub-line',
    name: 'Gliding sub line',
    category: 'bass',
    description:
      'A sub that slides for half a second to any key pressed over the last, with detuned copies of its overtones at the sides.',
    instrument: {
      deviceId: 'sub-bass',
      preset: 'Gliding sub',
      params: {
        shape: 0,
        harmonics: 0.65,
        drop: 0,
        fall: 40,
        attack: 0.08,
        decay: 20,
        release: 1.5,
        drive: 0.1,
        glide: 0.5,
        volume: -16.5,
      },
    },
    effects: [{ deviceId: 'stereo-detune', preset: 'Classic', params: { focus: 300 } }],
  },
  {
    id: 'sine-pedal-halo',
    name: 'Sine pedal with halo',
    category: 'bass',
    description:
      'A sine with its octave and twelfth at full, steady as an organ pedal, with a short halo of reverb that stays above the bass.',
    instrument: {
      deviceId: 'sub-bass',
      preset: 'Pedal tone',
      params: {
        shape: 0.35,
        harmonics: 1,
        drop: 0,
        fall: 40,
        attack: 0.015,
        decay: 20,
        release: 0.12,
        drive: 0,
        glide: 0.02,
        volume: -17,
      },
    },
    effects: [{ deviceId: 'shaped-reverb', preset: 'Short halo', params: { lowCut: 300 } }],
  },
  {
    id: 'small-speaker-sub-hum',
    name: 'Small speaker sub hum',
    category: 'bass',
    description:
      'A sub with its octave, fifth and odd harmonics turned well up and a valve stage after it, so a small speaker still finds the note.',
    instrument: {
      deviceId: 'sub-bass',
      preset: 'Small speaker hum',
      params: {
        shape: 0.8,
        harmonics: 0.9,
        drop: 0,
        fall: 40,
        attack: 0.03,
        decay: 20,
        release: 0.5,
        drive: 0.35,
        glide: 0.06,
        volume: -20.5,
      },
    },
    effects: [{ deviceId: 'saturator', preset: 'Tube preamp' }],
  },
  {
    id: 'hollow-square-sub',
    name: 'Hollow square sub',
    category: 'bass',
    description:
      'A sine bent all the way to a rounded square and driven, hollow and woody, with a chorus on its overtones only.',
    instrument: {
      deviceId: 'sub-bass',
      preset: 'Hollow square',
      params: {
        shape: 1,
        harmonics: 0,
        drop: 0,
        fall: 40,
        attack: 0.01,
        decay: 20,
        release: 0.2,
        drive: 0.6,
        glide: 0.05,
        volume: -14,
      },
    },
    effects: [{ deviceId: 'chorus', preset: 'Wide chorus', params: { hpHz: 400, mix: 0.3 } }],
  },
  {
    id: 'long-sub-boom',
    name: 'Long sub boom',
    category: 'bass',
    description:
      'A boom that starts two octaves up, lands in a fifth of a second and rings for seconds after the key, thickened by a tape head bump.',
    instrument: {
      deviceId: 'sub-bass',
      preset: 'Long boom',
      params: {
        shape: 0.2,
        harmonics: 0.4,
        drop: 24,
        fall: 220,
        attack: 0.002,
        decay: 7,
        release: 3,
        drive: 0.3,
        glide: 0.06,
        volume: -17.5,
      },
    },
    effects: [{ deviceId: 'tape', preset: 'Warm thump' }],
  },
  {
    id: 'sub-dive-hall-trail',
    name: 'Sub dive with hall trail',
    category: 'bass',
    description:
      'A tone that dives three octaves in most of a second and lands in tune, its fall left ringing in a hall that is cut off below 400 Hz.',
    instrument: {
      deviceId: 'sub-bass',
      preset: 'Deep dive',
      params: {
        shape: 0.1,
        harmonics: 0.15,
        drop: 36,
        fall: 800,
        attack: 0.005,
        decay: 9,
        release: 4,
        drive: 0.2,
        glide: 0.06,
        volume: -14,
      },
    },
    effects: [
      {
        deviceId: 'expanse',
        preset: 'Open space',
        params: { size: 0.7, decay: 5, lowCut: 400, highCut: 5000, mix: 0.35 },
      },
    ],
  },
  {
    id: 'dub-weight-sub',
    name: 'Dub weight sub',
    category: 'bass',
    description:
      'A rounded, driven sub that knocks a minor third above each note and sinks while held, weighted by a tape preamp with its low bump up.',
    instrument: {
      deviceId: 'sub-bass',
      preset: 'Dub weight',
      params: {
        shape: 0.3,
        harmonics: 0,
        drop: 3,
        fall: 90,
        attack: 0.01,
        decay: 2.5,
        release: 0.3,
        drive: 0.7,
        glide: 0.12,
        volume: -16,
      },
    },
    effects: [{ deviceId: 'analog-drive', preset: 'Tape weight', params: { output: -10.5 } }],
  },
  {
    id: 'driven-sub-pulse',
    name: 'Driven sub pulse',
    category: 'bass',
    description:
      'A hard driven pulse with the octave and fifth over it, dying in under a second, pushed through a triode for more edge.',
    instrument: {
      deviceId: 'sub-bass',
      preset: 'Driven pulse',
      params: {
        shape: 0.3,
        harmonics: 0.5,
        drop: 0,
        fall: 40,
        attack: 0.006,
        decay: 0.9,
        release: 0.2,
        drive: 0.9,
        glide: 0.03,
        volume: -8,
      },
    },
    effects: [{ deviceId: 'analog-drive', preset: 'Triode glow', params: { output: -2.5 } }],
  },
  {
    id: 'knocking-sub-drop',
    name: 'Knocking sub drop',
    category: 'bass',
    description:
      'A hard knock that falls two and a half octaves in a twentieth of a second onto a short dry note, through a transformer.',
    instrument: {
      deviceId: 'sub-bass',
      preset: 'Hard knock',
      params: {
        shape: 0.5,
        harmonics: 0.1,
        drop: 30,
        fall: 45,
        attack: 0.001,
        decay: 0.45,
        release: 0.12,
        drive: 0.9,
        glide: 0,
        volume: -5,
      },
    },
    effects: [{ deviceId: 'analog-drive', preset: 'Iron lows', params: { output: -3 } }],
  },
  {
    id: 'shortest-sub-thump',
    name: 'Shortest sub thump',
    category: 'bass',
    description:
      'The hardest and shortest strike: an octave and a half of fall in 15 ms, driven flat, gone in a seventh of a second, under a brickwall.',
    instrument: {
      deviceId: 'sub-bass',
      preset: 'Short thump',
      params: {
        shape: 0.05,
        harmonics: 0.3,
        drop: 18,
        fall: 15,
        attack: 0.001,
        decay: 0.14,
        release: 0.04,
        drive: 1,
        glide: 0,
        volume: 0,
      },
    },
    effects: [
      { deviceId: 'ambient-limiter', params: { ceiling: -9, gain: 4, release: 0.2, ride: 0 } },
    ],
  },
  {
    id: 'far-off-sub-drone',
    name: 'Far-off sub drone',
    category: 'drone',
    description:
      'A far-off drone: a low tone with a few overtones that swells over three seconds and fades over eight, in a long low hall with no top.',
    instrument: {
      deviceId: 'sub-bass',
      preset: 'Dark drone',
      params: {
        shape: 0.3,
        harmonics: 0.4,
        drop: 0,
        fall: 40,
        attack: 3,
        decay: 20,
        release: 8,
        drive: 0,
        glide: 2,
        volume: -13,
      },
    },
    effects: [
      {
        deviceId: 'expanse',
        preset: 'Low cathedral',
        params: { lowCut: 250, mix: 0.45, width: 0.6 },
      },
    ],
  },
  {
    id: 'gliding-sine-lead',
    name: 'Gliding sine lead',
    category: 'keys',
    description:
      'A sine lead with its octave and twelfth half up that slides between overlapping keys, with a soft short echo in a room.',
    instrument: {
      deviceId: 'sub-bass',
      preset: 'Gliding sub',
      params: {
        shape: 0.1,
        harmonics: 0.5,
        drop: 0,
        fall: 40,
        attack: 0.02,
        decay: 20,
        release: 0.5,
        drive: 0.2,
        glide: 0.12,
        volume: -17,
      },
    },
    effects: [
      { deviceId: 'tape-echo', preset: 'Short and soft', params: { mix: 0.2 } },
      { deviceId: 'hall-reverb', preset: 'Room' },
    ],
  },
  {
    id: 'falling-sine-chime',
    name: 'Falling sine chime',
    category: 'bell',
    description:
      'Struck sine notes that start an octave high, land in a thirtieth of a second and ring for about a second in a room.',
    instrument: {
      deviceId: 'sub-bass',
      preset: 'Hard knock',
      params: {
        shape: 0,
        harmonics: 0.5,
        drop: 12,
        fall: 35,
        attack: 0.001,
        decay: 1.2,
        release: 1.5,
        drive: 0.1,
        glide: 0,
        volume: -10,
      },
    },
    effects: [{ deviceId: 'hall-reverb', preset: 'Room' }],
  },
]
