import { type FactoryPreset } from '../types'

export const WAVETABLE_PRESETS: readonly FactoryPreset[] = [
  {
    id: 'glass-ripples',
    name: 'Glass ripples',
    category: 'pad',
    description: 'The glass table moving quickly enough to hear, with tape echoes trailing behind.',
    instrument: {
      deviceId: 'wavetable',
      preset: 'Glass morning',
      params: {
        position: 0.65,
        motion: 0.6,
        rate: 0.6,
        sub: 0.15,
        cutoff: 7000,
        attack: 0.25,
        release: 2.5,
      },
    },
    effects: [
      { deviceId: 'tape-echo', preset: 'Three heads', params: { mix: 0.3 } },
      { deviceId: 'plate-reverb', preset: 'Small plate' },
    ],
  },
  {
    id: 'vowel-tide',
    name: 'Vowel tide',
    category: 'pad',
    description: 'The vowel table travelling end to end, so the chord slowly mouths its way round.',
    instrument: {
      deviceId: 'wavetable',
      preset: 'Slow choir',
      params: { motion: 1, rate: 0.09, spread: 0.6 },
    },
    effects: [
      { deviceId: 'chorus', preset: 'Slow drift', params: { spread: 60, mix: 0.35 } },
      { deviceId: 'expanse', preset: 'Open space', params: { mix: 0.3, width: 0.8 } },
    ],
  },
  {
    id: 'reed-to-saw-sunrise',
    name: 'Reed sunrise',
    category: 'pad',
    description:
      'Each note travels between a soft reed and a full saw at its own pace, with tape saturation.',
    instrument: {
      deviceId: 'wavetable',
      preset: 'Reed organ',
      params: {
        position: 0.5,
        motion: 1,
        rate: 0.12,
        detune: 11,
        sub: 0.3,
        cutoff: 6000,
        attack: 1.8,
        release: 4,
        spread: 0.8,
        volume: -15,
      },
    },
    effects: [
      { deviceId: 'saturator', preset: 'On tape', params: { toneDb: 0, outputDb: -5.5 } },
      { deviceId: 'hall-reverb', preset: 'Hall' },
    ],
  },
  {
    id: 'hollow-undertow',
    name: 'Hollow undertow',
    category: 'pad',
    description:
      'A dark hollow tone with a strong sub and a slow phaser, for the bottom of a piece.',
    instrument: {
      deviceId: 'wavetable',
      preset: 'Hollow drift',
      params: { sub: 0.55, cutoff: 650 },
    },
    effects: [
      { deviceId: 'phaser', preset: 'Slow swirl', params: { mix: 0.4 } },
      { deviceId: 'fdn-reverb', preset: 'Hall', params: { mix: 0.3 } },
    ],
  },
  {
    id: 'spectral-mist',
    name: 'Spectral mist',
    category: 'pad',
    description: 'Takes five seconds to arrive, bright and shifting, with an octave halo above it.',
    instrument: {
      deviceId: 'wavetable',
      preset: 'Spectral cloud',
      params: { spread: 0.7, volume: -12 },
    },
    effects: [{ deviceId: 'shimmer', preset: 'Rising choir', params: { mix: 0.35, width: 0.7 } }],
  },
  {
    id: 'saw-table-strings',
    name: 'Saw table strings',
    category: 'string',
    description:
      'Full sawtooth waves a fifth of a semitone apart, quick to speak, in an ensemble chorus and a room.',
    instrument: {
      deviceId: 'wavetable',
      preset: 'Reed organ',
      params: {
        position: 0.92,
        motion: 0.12,
        rate: 0.25,
        detune: 20,
        sub: 0.1,
        cutoff: 3600,
        resonance: 0.05,
        attack: 0.3,
        release: 1.4,
        spread: 0.6,
        volume: -10,
      },
    },
    effects: [
      { deviceId: 'chorus', preset: 'Lush ensemble', params: { mix: 0.3 } },
      { deviceId: 'hall-reverb', preset: 'Room', params: { mix: 0.22 } },
    ],
  },
  {
    id: 'pulse-table-sweep',
    name: 'Pulse table sweep',
    category: 'pad',
    description:
      'A square wave whose pulse narrows and widens every second and a half, each note in its own time, over a sub octave.',
    instrument: {
      deviceId: 'wavetable',
      preset: 'Hollow drift',
      params: {
        position: 0.45,
        motion: 0.8,
        rate: 0.7,
        detune: 6,
        sub: 0.4,
        cutoff: 9000,
        resonance: 0.05,
        attack: 0.3,
        release: 1.8,
        spread: 0.6,
        volume: -13,
      },
    },
    effects: [{ deviceId: 'fdn-reverb', preset: 'Hall', params: { mix: 0.2 } }],
  },
  {
    id: 'square-table-lead',
    name: 'Square table lead',
    category: 'wind',
    description:
      'A plain square wave for single lines, soft at the top, with a light vibrato in a small room.',
    instrument: {
      deviceId: 'wavetable',
      preset: 'Hollow drift',
      params: {
        position: 0,
        motion: 0.06,
        rate: 0.4,
        detune: 0,
        sub: 0,
        cutoff: 2200,
        resonance: 0.12,
        attack: 0.07,
        release: 0.35,
        spread: 0.25,
      },
    },
    effects: [
      { deviceId: 'tremolo', preset: 'Pitch wobble', params: { depth: 0.2, phase: 0 } },
      { deviceId: 'hall-reverb', preset: 'Tight chamber' },
    ],
  },
  {
    id: 'glass-table-chime',
    name: 'Glass table chime',
    category: 'bell',
    description:
      'The far end of the glass table with every partial sounding, struck short and left to ring in bright air.',
    instrument: {
      deviceId: 'wavetable',
      preset: 'Glass morning',
      params: {
        position: 1,
        motion: 0,
        detune: 5,
        sub: 0,
        cutoff: 14000,
        resonance: 0,
        attack: 0.005,
        release: 3.2,
        spread: 0.6,
        volume: -8,
      },
    },
    effects: [{ deviceId: 'fdn-reverb', preset: 'Bright air', params: { mix: 0.2, size: 1.3 } }],
  },
  {
    id: 'still-vowel-choir',
    name: 'Still vowel choir',
    category: 'voice',
    description:
      'The vowel table held still at its oo end, so the whole chord sings one unchanging vowel, thickened by chorus in a small chamber.',
    instrument: {
      deviceId: 'wavetable',
      preset: 'Slow choir',
      params: {
        position: 1,
        motion: 0,
        detune: 16,
        sub: 0,
        cutoff: 5000,
        attack: 0.4,
        release: 1.6,
        spread: 0.7,
        volume: -10,
      },
    },
    effects: [
      { deviceId: 'chorus', preset: 'Vocal thickener' },
      { deviceId: 'hall-reverb', preset: 'Tight chamber', params: { mix: 0.25 } },
    ],
  },
  {
    id: 'reed-table-pipes',
    name: 'Reed table pipes',
    category: 'organ',
    description:
      'A still reed tone with octaves stacked below and above it like organ stops, in a hall.',
    instrument: {
      deviceId: 'wavetable',
      preset: 'Reed organ',
      params: {
        position: 0,
        motion: 0,
        detune: 0,
        sub: 0,
        cutoff: 5000,
        resonance: 0,
        attack: 0.03,
        release: 0.25,
        volume: -18.5,
      },
    },
    effects: [
      { deviceId: 'octaves', preset: 'Organ', params: { sub2: 0 } },
      { deviceId: 'hall-reverb', preset: 'Hall', params: { mix: 0.3 } },
    ],
  },
  {
    id: 'narrow-pulse-keys',
    name: 'Narrow pulse keys',
    category: 'keys',
    description:
      'A thin nasal pulse that speaks at once, through a slow four stage phaser with a short slap behind it.',
    instrument: {
      deviceId: 'wavetable',
      preset: 'Hollow drift',
      params: {
        position: 1,
        motion: 0,
        detune: 4,
        sub: 0.2,
        cutoff: 3000,
        attack: 0.005,
        release: 0.45,
        spread: 0.4,
        volume: -6.5,
      },
    },
    effects: [
      { deviceId: 'phaser', preset: 'Classic four-stage', params: { stereo: 20, mix: 0.35 } },
      { deviceId: 'analog-delay', preset: 'Slapback' },
    ],
  },
  {
    id: 'resonant-saw-keys',
    name: 'Resonant saw keys',
    category: 'keys',
    description:
      'Dark detuned saws behind a resonant filter at one kilohertz, with dotted tape echoes fading into a hall.',
    instrument: {
      deviceId: 'wavetable',
      preset: 'Reed organ',
      params: {
        position: 0.75,
        motion: 0,
        detune: 14,
        sub: 0.25,
        cutoff: 1000,
        resonance: 0.55,
        attack: 0.005,
        release: 0.3,
        volume: -6.5,
      },
    },
    effects: [
      {
        deviceId: 'tape-echo',
        preset: 'Dotted bounce',
        params: { spread: 0, highCut: 2500, mix: 0.3 },
      },
      { deviceId: 'fdn-reverb', preset: 'Hall', params: { mix: 0.25 } },
    ],
  },
  {
    id: 'overtone-table-drone',
    name: 'Overtone table drone',
    category: 'drone',
    description:
      'A tone whose clusters of overtones wander up and down over ten seconds, like overtone singing, in a hall.',
    instrument: {
      deviceId: 'wavetable',
      preset: 'Spectral cloud',
      params: {
        position: 0.35,
        rate: 0.1,
        detune: 5,
        cutoff: 6000,
        attack: 1.8,
        release: 5,
        spread: 0.5,
        volume: -10,
      },
    },
    effects: [{ deviceId: 'hall-reverb', preset: 'Hall', params: { mix: 0.3 } }],
  },
  {
    id: 'beating-saw-drone',
    name: 'Beating saw drone',
    category: 'drone',
    description:
      'Two saws thirty cents apart over a sub octave, under a resonant filter at 900 hertz, through a transformer in a dark hall.',
    instrument: {
      deviceId: 'wavetable',
      preset: 'Reed organ',
      params: {
        position: 0.65,
        motion: 0.5,
        rate: 0.04,
        detune: 30,
        sub: 0.35,
        cutoff: 900,
        resonance: 0.5,
        attack: 2.2,
        release: 6,
        spread: 0.6,
        volume: -8,
      },
    },
    effects: [
      { deviceId: 'analog-drive', preset: 'Iron lows' },
      { deviceId: 'hall-reverb', preset: 'Dark hall', params: { mix: 0.3 } },
    ],
  },
  {
    id: 'reed-table-celeste',
    name: 'Reed table celeste',
    category: 'organ',
    description:
      'Two ranks of soft reeds tuned a third of a semitone apart so every note beats, like a celeste stop, in a room.',
    instrument: {
      deviceId: 'wavetable',
      preset: 'Reed organ',
      params: {
        position: 0.12,
        motion: 0,
        detune: 36,
        sub: 0.15,
        cutoff: 3200,
        resonance: 0.05,
        attack: 0.1,
        release: 0.5,
        volume: -13,
      },
    },
    effects: [{ deviceId: 'hall-reverb', preset: 'Room', params: { mix: 0.3 } }],
  },
  {
    id: 'vowel-table-flutter',
    name: 'Vowel table flutter',
    category: 'voice',
    description:
      'Each note flickers between vowels six times a second in its own time, so the chord chatters far down a dark hall.',
    instrument: {
      deviceId: 'wavetable',
      preset: 'Slow choir',
      params: {
        position: 0.6,
        motion: 0.4,
        rate: 6,
        detune: 8,
        cutoff: 6000,
        attack: 0.15,
        release: 1.2,
        spread: 0.4,
        volume: -12,
      },
    },
    effects: [{ deviceId: 'hall-reverb', preset: 'Far away', params: { mix: 0.55 } }],
  },
  {
    id: 'spectral-bubbles',
    name: 'Spectral bubbles',
    category: 'texture',
    description:
      'Clusters of partials that sweep up and down twice a second, each key and each side out of step, with pattering echoes.',
    instrument: {
      deviceId: 'wavetable',
      preset: 'Spectral cloud',
      params: {
        rate: 2,
        detune: 3,
        cutoff: 10000,
        resonance: 0.2,
        attack: 0.2,
        release: 2.5,
        spread: 0.8,
        volume: -9,
      },
    },
    effects: [{ deviceId: 'swarm-reverb', preset: 'Pattering', params: { width: 0, mix: 0.25 } }],
    preview: 'keys',
  },
  {
    id: 'whistling-saw-pad',
    name: 'Whistling saw pad',
    category: 'pad',
    description:
      'A filter ringing hard at 1800 hertz picks out harmonics that come and go as reed turns to saw, in a very large space.',
    instrument: {
      deviceId: 'wavetable',
      preset: 'Reed organ',
      params: {
        position: 0.5,
        motion: 0.9,
        rate: 0.15,
        detune: 7,
        sub: 0.1,
        cutoff: 1800,
        resonance: 0.85,
        attack: 1,
        release: 4,
        spread: 0.7,
        volume: -6.5,
      },
    },
    effects: [{ deviceId: 'fdn-reverb', preset: 'Open valley', params: { mix: 0.3 } }],
  },
  {
    id: 'glass-keys-on-record',
    name: 'Glass keys on record',
    category: 'keys',
    description:
      'A soft glass key sound and its room on a worn record that warps and crackles, its surface noise running on after the notes stop.',
    instrument: {
      deviceId: 'wavetable',
      preset: 'Glass morning',
      params: {
        motion: 0.15,
        rate: 0.2,
        detune: 0,
        sub: 0.2,
        cutoff: 2800,
        resonance: 0.1,
        attack: 0.008,
        release: 1.3,
        volume: -13.5,
      },
    },
    effects: [
      { deviceId: 'hall-reverb', preset: 'Room', params: { mix: 0.2 } },
      { deviceId: 'vinyl', preset: 'Charity shop find' },
    ],
  },
  {
    id: 'hollow-table-bass',
    name: 'Hollow table bass',
    category: 'bass',
    description:
      'A hollow wave that narrows and widens while it is held and takes a third of a second to arrive, with a faint sung chapel.',
    instrument: {
      deviceId: 'wavetable',
      params: {
        table: 3,
        position: 0.25,
        motion: 0.5,
        rate: 0.25,
        detune: 0,
        sub: 0,
        cutoff: 700,
        resonance: 0.1,
        attack: 0.3,
        release: 0.9,
        spread: 0,
        volume: -7,
      },
    },
    effects: [{ deviceId: 'vowel-reverb', preset: 'Chapel', params: { lowCut: 250, mix: 0.2 } }],
  },
]
