// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Flanger, shared with
// src/dsp/devices/flanger.gen.ts:
//    0  delayMs: 0.5..10 ms, default 2.5
//    1  rate: 0.01..10 Hz, default 0.25
//    2  depth: 0..100 %, default 50
//    3  feedback: -95..95 %, default 30
//    4  shape: 0 Sine, 1 Triangle, 2 Saw up, 3 Saw down, 4 Square, 5 Random, default 0
//    5  stereo: 0..180 deg, default 90
//    6  mix: 0..1, default 0.5

#pragma once

namespace livemix {
namespace flanger {

enum Param : int {
  kDelayMs = 0,
  kRate = 1,
  kDepth = 2,
  kFeedback = 3,
  kShape = 4,
  kStereo = 5,
  kMix = 6,
  kNumParams = 7,
};

inline constexpr float kParamMin[kNumParams] = {0.5f, 0.01f, 0.0f, -95.0f, 0.0f, 0.0f, 0.0f};
inline constexpr float kParamMax[kNumParams] = {10.0f, 10.0f, 100.0f, 95.0f, 5.0f, 180.0f, 1.0f};
inline constexpr float kParamDefault[kNumParams] = {2.5f, 0.25f, 50.0f, 30.0f, 0.0f, 90.0f, 0.5f};

}  // namespace flanger
}  // namespace livemix
