// Agent-authored scores (U38): the session script a planner fills, its
// validation and canon, the tuin music selector port, voice assets, the
// compiler to a score, the offline bounce, and the agent tools over them.

export {
  SCRIPT_CUE_BUFFER_SECONDS,
  SCRIPT_CUE_GAP_SECONDS,
  SCRIPT_DUCK_ATTACK_SECONDS,
  SCRIPT_DUCK_DB,
  SCRIPT_DUCK_HOLD_SECONDS,
  SCRIPT_DUCK_RELEASE_SECONDS,
  SCRIPT_LANE_IDS,
  SCRIPT_MUSIC_DB,
  SCRIPT_SECTION_FADE_IN_SECONDS,
  SCRIPT_SESSION_FADE_IN_SECONDS,
  SCRIPT_SESSION_FADE_OUT_SECONDS,
  SCRIPT_TRACK_IDS,
  SCRIPT_TRIM_FADE_OUT_SECONDS,
  SCRIPT_VOICE_FADE_IN_SECONDS,
  SCRIPT_VOICE_FADE_OUT_SECONDS,
  breathBreakpoints,
  compileScript,
  compileScriptDetailed,
  duckBreakpoints,
  operationsToLoad,
  selectTracksForScript,
  type AmbienceOptions,
  type BreathGuideOptions,
  type CompileMix,
  type CompileScriptOptions,
  type CompileWarning,
  type CompileWarningCode,
  type CompiledCue,
  type CompiledHold,
  type CompiledScript,
  type CompiledSection,
  type DuckOptions,
  type LoadOperationsOptions,
  type ScriptTrackRole,
} from './compile'
export { PythonRandom } from './pythonRandom'
export { renderScriptToWav, type RenderScriptOptions, type RenderedScript } from './render'
export {
  BREATH_ROUTES,
  BREATH_STYLES,
  CANONICAL_THEMES,
  CUE_KINDS,
  DEFAULT_BREATHING,
  DEFAULT_SECTION_NAMES,
  HOLD_KINDS,
  SECTION_NUMBER_BY_ROLE,
  SECTION_ROLES,
  SESSION_SCRIPT_CANON,
  SESSION_SCRIPT_FORMAT,
  SESSION_SCRIPT_SCHEMA,
  SessionScriptError,
  TIMES_OF_DAY,
  breathCycleSec,
  checkScriptCanon,
  foreignTags,
  formatScriptIssues,
  normaliseScript,
  parseSessionScript,
  pauseSeconds,
  scriptDurationSec,
  sessionScriptPromptContract,
  stripPauseTags,
  validateSessionScript,
  type BreathHold,
  type BreathRoute,
  type BreathStyle,
  type BreathingPattern,
  type CanonIssue,
  type CanonOptions,
  type CanonRule,
  type CueKind,
  type HoldKind,
  type ParseSessionScriptOptions,
  type ScriptIssue,
  type ScriptSection,
  type SectionRole,
  type SessionScript,
  type TimeOfDay,
  type VoiceCue,
} from './script'
export {
  AVERAGE_TRACK_SECONDS,
  UNKNOWN_CAMELOT,
  fallbackIntensities,
  pythonChooser,
  sectionTargetIntensity,
  selectNextTrack,
  selectTracksForSection,
  selectTracksForSession,
  type SectionNumber,
  type SectionSelection,
  type SelectNextOptions,
  type SelectSectionOptions,
  type SelectSessionOptions,
  type SessionSelection,
  type TrackChooser,
} from './selector'
export {
  SCRIPT_TOOL_NAMES,
  SCRIPT_TOOL_RATE_LIMITS,
  ScriptAuthoring,
  createScriptAuthoring,
  scoreExtentSec,
  scriptTools,
  type RenderJob,
  type RenderJobStatus,
  type ScriptAuthoringOptions,
  type ScriptRenderOptions,
  type ScriptToolName,
} from './tools'
export {
  cueKey,
  cueRefs,
  estimateSpeechSeconds,
  estimatedVoiceProvider,
  staticVoiceProvider,
  synthesizeVoice,
  type EstimateOptions,
  type SynthesizeVoiceOptions,
  type SynthesizedVoice,
  type VoiceAsset,
  type VoiceCueRef,
  type VoiceProvider,
  type VoiceSynthesizer,
} from './voice'
