// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Choir, shared with
// src/dsp/devices/choir.gen.ts:
//    0  vowel: 0..1, default 0.04
//    1  voice: 0.8..1.4 x, default 1.16
//    2  motion: 0..1, default 0.35
//    3  breath: 0..1, default 0.3
//    4  ensemble: 0..1, default 0.65
//    5  vibrato: 0..60 ct, default 10
//    6  vibratoRate: 3..8 Hz, default 5.2
//    7  attack: 0.01..10 s, default 0.9
//    8  release: 0.05..15 s, default 2.8
//    9  tone: 400..12000 Hz, default 6500
//   10  width: 0..1, default 0.8
//   11  volume: -48..6 dB, default -10

#pragma once

namespace livemix {
namespace choir {

enum Param : int {
  kVowel = 0,
  kVoice = 1,
  kMotion = 2,
  kBreath = 3,
  kEnsemble = 4,
  kVibrato = 5,
  kVibratoRate = 6,
  kAttack = 7,
  kRelease = 8,
  kTone = 9,
  kWidth = 10,
  kVolume = 11,
  kNumParams = 12,
};

inline constexpr float kParamMin[kNumParams] = {0.0f, 0.8f, 0.0f, 0.0f, 0.0f, 0.0f, 3.0f, 0.01f, 0.05f, 400.0f, 0.0f, -48.0f};
inline constexpr float kParamMax[kNumParams] = {1.0f, 1.4f, 1.0f, 1.0f, 1.0f, 60.0f, 8.0f, 10.0f, 15.0f, 12000.0f, 1.0f, 6.0f};
inline constexpr float kParamDefault[kNumParams] = {0.04f, 1.16f, 0.35f, 0.3f, 0.65f, 10.0f, 5.2f, 0.9f, 2.8f, 6500.0f, 0.8f, -10.0f};

}  // namespace choir
}  // namespace livemix
