// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Reed Organ, shared with
// src/dsp/devices/organ.gen.ts:
//    0  sub: 0..1, default 0.3
//    1  octave: 0..1, default 0.45
//    2  twelfth: 0..1, default 0.12
//    3  fifteenth: 0..1, default 0.18
//    4  reed: 0..1, default 0.3
//    5  celeste: 0..1, default 0.3
//    6  breath: 0..1, default 0.2
//    7  bellows: 0..1, default 0.3
//    8  tremulant: 0..1, default 0
//    9  attack: 0.005..6 s, default 0.12
//   10  release: 0.02..10 s, default 0.4
//   11  tone: 300..12000 Hz, default 3200
//   12  volume: -48..6 dB, default -10

#pragma once

namespace livemix {
namespace organ {

enum Param : int {
  kSub = 0,
  kOctave = 1,
  kTwelfth = 2,
  kFifteenth = 3,
  kReed = 4,
  kCeleste = 5,
  kBreath = 6,
  kBellows = 7,
  kTremulant = 8,
  kAttack = 9,
  kRelease = 10,
  kTone = 11,
  kVolume = 12,
  kNumParams = 13,
};

inline constexpr float kParamMin[kNumParams] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.005f, 0.02f, 300.0f, -48.0f};
inline constexpr float kParamMax[kNumParams] = {1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 6.0f, 10.0f, 12000.0f, 6.0f};
inline constexpr float kParamDefault[kNumParams] = {0.3f, 0.45f, 0.12f, 0.18f, 0.3f, 0.3f, 0.2f, 0.3f, 0.0f, 0.12f, 0.4f, 3200.0f, -10.0f};

}  // namespace organ
}  // namespace livemix
