// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Melt, shared with
// src/dsp/devices/melt.gen.ts:
//    0  sag: -100..100 ct/s, default -30
//    1  hold: 0.4..20 s, default 5
//    2  solid: 0..1000 ms, default 120
//    3  size: 0..1, default 0.35
//    4  blur: 0..1, default 0.55
//    5  dim: 0..1, default 0.4
//    6  drip: 0..1, default 0.2
//    7  width: 0..1, default 1
//    8  mix: 0..1, default 0.4

#pragma once

namespace livemix {
namespace melt {

enum Param : int {
  kSag = 0,
  kHold = 1,
  kSolid = 2,
  kSize = 3,
  kBlur = 4,
  kDim = 5,
  kDrip = 6,
  kWidth = 7,
  kMix = 8,
  kNumParams = 9,
};

inline constexpr float kParamMin[kNumParams] = {-100.0f, 0.4f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
inline constexpr float kParamMax[kNumParams] = {100.0f, 20.0f, 1000.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f};
inline constexpr float kParamDefault[kNumParams] = {-30.0f, 5.0f, 120.0f, 0.35f, 0.55f, 0.4f, 0.2f, 1.0f, 0.4f};

}  // namespace melt
}  // namespace livemix
