// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Sampler, shared with
// src/dsp/devices/sampler.gen.ts:
//    0  start: 0..1, default 0.15
//    1  end: 0..1, default 0.85
//    2  loop: 0 Off, 1 Forward, 2 Ping-pong, default 1
//    3  crossfade: 0..500 ms, default 50
//    4  reverse: 0 Off, 1 On, default 0
//    5  tune: -24..24 st, default 0
//    6  fine: -100..100 ct, default 0
//    7  attack: 0.001..8 s, default 0.06
//    8  release: 0.01..12 s, default 0.6
//    9  tone: 200..18000 Hz, default 8000
//   10  wobble: 0..1, default 0.2
//   11  velocity: 0..1, default 0.6
//   12  volume: -48..6 dB, default -9

#pragma once

namespace livemix {
namespace sampler {

enum Param : int {
  kStart = 0,
  kEnd = 1,
  kLoop = 2,
  kCrossfade = 3,
  kReverse = 4,
  kTune = 5,
  kFine = 6,
  kAttack = 7,
  kRelease = 8,
  kTone = 9,
  kWobble = 10,
  kVelocity = 11,
  kVolume = 12,
  kNumParams = 13,
};

inline constexpr float kParamMin[kNumParams] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, -24.0f, -100.0f, 0.001f, 0.01f, 200.0f, 0.0f, 0.0f, -48.0f};
inline constexpr float kParamMax[kNumParams] = {1.0f, 1.0f, 2.0f, 500.0f, 1.0f, 24.0f, 100.0f, 8.0f, 12.0f, 18000.0f, 1.0f, 1.0f, 6.0f};
inline constexpr float kParamDefault[kNumParams] = {0.15f, 0.85f, 1.0f, 50.0f, 0.0f, 0.0f, 0.0f, 0.06f, 0.6f, 8000.0f, 0.2f, 0.6f, -9.0f};

}  // namespace sampler
}  // namespace livemix
