// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of String Bass, shared with
// src/dsp/devices/string-bass.gen.ts:
//    0  type: 0 Electric, 1 Fretless, 2 Upright, default 0
//    1  touch: 0..1, default 0.3
//    2  position: 0.05..0.5, default 0.22
//    3  tone: 0..1, default 0.55
//    4  mute: 0..1, default 0
//    5  sustain: 0.5..20 s, default 5
//    6  release: 0.03..3 s, default 0.15
//    7  growl: 0..1, default 0.25
//    8  resonance: 0..1, default 0.35
//    9  volume: -48..6 dB, default -6

#pragma once

namespace livemix {
namespace string_bass {

enum Param : int {
  kType = 0,
  kTouch = 1,
  kPosition = 2,
  kTone = 3,
  kMute = 4,
  kSustain = 5,
  kRelease = 6,
  kGrowl = 7,
  kResonance = 8,
  kVolume = 9,
  kNumParams = 10,
};

inline constexpr float kParamMin[kNumParams] = {0.0f, 0.0f, 0.05f, 0.0f, 0.0f, 0.5f, 0.03f, 0.0f, 0.0f, -48.0f};
inline constexpr float kParamMax[kNumParams] = {2.0f, 1.0f, 0.5f, 1.0f, 1.0f, 20.0f, 3.0f, 1.0f, 1.0f, 6.0f};
inline constexpr float kParamDefault[kNumParams] = {0.0f, 0.3f, 0.22f, 0.55f, 0.0f, 5.0f, 0.15f, 0.25f, 0.35f, -6.0f};

}  // namespace string_bass
}  // namespace livemix
