// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Fog, shared with
// src/dsp/devices/fog.gen.ts:
//    0  size: 10..600 ms, default 150
//    1  density: 0..1, default 0.8
//    2  layers: 1..3, default 1
//    3  drift: 0..1, default 0.3
//    4  soften: 0..1, default 0.3
//    5  damp: 0..1, default 0.25
//    6  lowCut: 20..1000 Hz, default 20
//    7  width: 0..1, default 1
//    8  mix: 0..1, default 1

#pragma once

namespace livemix {
namespace fog {

enum Param : int {
  kSize = 0,
  kDensity = 1,
  kLayers = 2,
  kDrift = 3,
  kSoften = 4,
  kDamp = 5,
  kLowCut = 6,
  kWidth = 7,
  kMix = 8,
  kNumParams = 9,
};

inline constexpr float kParamMin[kNumParams] = {10.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 20.0f, 0.0f, 0.0f};
inline constexpr float kParamMax[kNumParams] = {600.0f, 1.0f, 3.0f, 1.0f, 1.0f, 1.0f, 1000.0f, 1.0f, 1.0f};
inline constexpr float kParamDefault[kNumParams] = {150.0f, 0.8f, 1.0f, 0.3f, 0.3f, 0.25f, 20.0f, 1.0f, 1.0f};

}  // namespace fog
}  // namespace livemix
