// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Outdoors, shared with
// src/dsp/devices/outdoors.gen.ts:
//    0  type: 0 Birds, 1 Crickets, 2 Frogs, 3 Stream, 4 Thunder, 5 Chimes, default 5
//    1  density: 0..1, default 0.5
//    2  distance: 0..1, default 0.4
//    3  movement: 0..1, default 0.5
//    4  tone: 0..1, default 0.5
//    5  attack: 0.01..20 s, default 2
//    6  release: 0.05..30 s, default 4
//    7  width: 0..1, default 1
//    8  volume: -48..6 dB, default -9

#pragma once

namespace livemix {
namespace outdoors {

enum Param : int {
  kType = 0,
  kDensity = 1,
  kDistance = 2,
  kMovement = 3,
  kTone = 4,
  kAttack = 5,
  kRelease = 6,
  kWidth = 7,
  kVolume = 8,
  kNumParams = 9,
};

inline constexpr float kParamMin[kNumParams] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.01f, 0.05f, 0.0f, -48.0f};
inline constexpr float kParamMax[kNumParams] = {5.0f, 1.0f, 1.0f, 1.0f, 1.0f, 20.0f, 30.0f, 1.0f, 6.0f};
inline constexpr float kParamDefault[kNumParams] = {5.0f, 0.5f, 0.4f, 0.5f, 0.5f, 2.0f, 4.0f, 1.0f, -9.0f};

}  // namespace outdoors
}  // namespace livemix
