// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Chamber Strings, shared with
// src/dsp/devices/chamber-strings.gen.ts:
//    0  players: 1..6, default 4
//    1  attack: 0.05..6 s, default 0.6
//    2  release: 0.1..8 s, default 1.2
//    3  bow: 0..1, default 0.4
//    4  air: 0..1, default 0.3
//    5  vibrato: 0..40 ct, default 6
//    6  mute: 0..1, default 0.2
//    7  scatter: 0..1, default 0.35
//    8  width: 0..1, default 0.7
//    9  volume: -48..6 dB, default -9

#pragma once

namespace livemix {
namespace chamber_strings {

enum Param : int {
  kPlayers = 0,
  kAttack = 1,
  kRelease = 2,
  kBow = 3,
  kAir = 4,
  kVibrato = 5,
  kMute = 6,
  kScatter = 7,
  kWidth = 8,
  kVolume = 9,
  kNumParams = 10,
};

inline constexpr float kParamMin[kNumParams] = {1.0f, 0.05f, 0.1f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, -48.0f};
inline constexpr float kParamMax[kNumParams] = {6.0f, 6.0f, 8.0f, 1.0f, 1.0f, 40.0f, 1.0f, 1.0f, 1.0f, 6.0f};
inline constexpr float kParamDefault[kNumParams] = {4.0f, 0.6f, 1.2f, 0.4f, 0.3f, 6.0f, 0.2f, 0.35f, 0.7f, -9.0f};

}  // namespace chamber_strings
}  // namespace livemix
