// GENERATED by scripts/gen-devices.mjs from cpp/devices/analog-drive/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const ANALOG_DRIVE_PARAMS = {
  drive: {
    id: 0,
    name: 'Drive',
    min: 0,
    max: 1,
    default: 0.3,
    taper: 'linear',
    unit: '',
    description:
      'How hard the sound hits the circuit. Low adds weight and holds the peaks, the middle is clearly driven, and the top compresses, thickens and finally squares off.',
  },
  circuit: {
    id: 1,
    name: 'Circuit',
    min: 0,
    max: 4,
    default: 0,
    taper: 'linear',
    unit: '',
    choices: ['Tape preamp', 'Console', 'Transformer', 'Triode', 'Pentode'],
    description:
      'What is overdriven. Tape preamp is warm and dull, Console firm in the mids, Transformer thick and loose in the lows, Triode smooth and open, Pentode lean with a bite.',
  },
  push: {
    id: 2,
    name: 'Push',
    min: 0,
    max: 1,
    default: 0,
    taper: 'linear',
    unit: '',
    choices: ['Off', 'On'],
    description:
      'Sends the sound into the circuit far hotter, past anything Drive reaches alone, with the level brought back down after it. This is the setting that goes too far.',
  },
  lowCut: {
    id: 3,
    name: 'Low Cut',
    min: 20,
    max: 1000,
    default: 20,
    taper: 'log',
    unit: 'Hz',
    description:
      'Takes the lows out before the circuit, so the bass stops driving it and the distortion gets tighter and thinner. At the bottom it is out of the path.',
  },
  lowBump: {
    id: 4,
    name: 'Low Bump',
    min: 0,
    max: 1,
    default: 0,
    taper: 'linear',
    unit: '',
    description:
      'A resonant bump in the lows just above the Low Cut, going into the circuit, so that part of the sound is what breaks up.',
  },
  tone: {
    id: 5,
    name: 'Tone',
    min: -1,
    max: 1,
    default: 0,
    taper: 'linear',
    unit: '',
    description:
      'Tilts the driven sound after the circuit. Down is darker and fuller, up is brighter and leaner.',
  },
  highCut: {
    id: 6,
    name: 'High Cut',
    min: 1000,
    max: 20000,
    default: 20000,
    taper: 'log',
    unit: 'Hz',
    description:
      'A steep filter after the circuit that takes the fizz off the top of the driven sound. At the top it is out of the path.',
  },
  autoGain: {
    id: 7,
    name: 'Auto Gain',
    min: 0,
    max: 1,
    default: 1,
    taper: 'linear',
    unit: '',
    choices: ['Off', 'On'],
    description:
      "On keeps the loudness about where it was while Drive changes the character. Off lets Drive make it louder as well, up to the circuit's ceiling.",
  },
  output: {
    id: 8,
    name: 'Output',
    min: -24,
    max: 12,
    default: 0,
    taper: 'linear',
    unit: 'dB',
    description:
      'Level of the driven sound. The clean part of Mix is not affected. Very loud settings are held back softly before they reach the output.',
  },
  mix: {
    id: 9,
    name: 'Mix',
    min: 0,
    max: 1,
    default: 1,
    taper: 'linear',
    unit: '',
    description:
      'Balance between the clean sound and the driven one. Part way keeps the clean attack and lays the grit under it.',
  },
} as const satisfies Record<string, ParamSpec>

export type AnalogDriveParamName = keyof typeof ANALOG_DRIVE_PARAMS

export const ANALOG_DRIVE_DEVICE = defineWasmDevice({
  id: 'analog-drive',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/analog-drive.wasm', import.meta.url),
  params: ANALOG_DRIVE_PARAMS,
  latencySamples: () => 39,
})

export const ANALOG_DRIVE_DESCRIPTOR = wasmDeviceDescriptor(ANALOG_DRIVE_DEVICE, {
  name: 'Analog Drive',
  category: 'drive',
  description:
    'Five circuits to push a sound through (tape preamp, console, transformer, triode, pentode), from weight and glue to a folded-over fuzz, with the level roughly held while you turn it up.',
  presets: {
    'Warm glue': { circuit: 0, drive: 0.36, lowBump: 0.2, tone: -0.2, output: -2 },
    'Tape weight': { circuit: 0, drive: 0.6, lowBump: 0.7, tone: -0.4, highCut: 6500, output: -5 },
    Console: { circuit: 1, drive: 0.45, lowCut: 45, tone: 0.2 },
    'Iron lows': { circuit: 2, drive: 0.5, lowCut: 40, lowBump: 0.5, tone: -0.1, output: -4 },
    'Triode glow': { circuit: 3, drive: 0.5, output: -1 },
    Bite: { circuit: 4, drive: 0.55, lowCut: 90, highCut: 9000 },
    Crushed: { circuit: 1, drive: 0.2, push: 1, lowCut: 60, highCut: 4200, mix: 0.5 },
    'Dark fuzz': {
      circuit: 3,
      drive: 0.45,
      push: 1,
      lowCut: 50,
      tone: -0.7,
      highCut: 2400,
      output: -4.5,
    },
    'Parallel grit': {
      circuit: 4,
      drive: 0.7,
      lowCut: 220,
      tone: 0.3,
      highCut: 10000,
      output: 4,
      mix: 0.3,
    },
    'First hint': { circuit: 0, drive: 0.15 },
    'Low warmth': { circuit: 2, drive: 0.25, lowCut: 30, lowBump: 1, tone: -0.3, output: -4 },
    Sheen: { circuit: 1, drive: 0.65, lowCut: 120, tone: 0.6, highCut: 14000 },
    'Worn tape': {
      circuit: 0,
      drive: 0.5,
      push: 1,
      lowBump: 0.5,
      tone: -0.5,
      highCut: 5000,
      output: -9,
    },
    'Iron melt': { circuit: 2, drive: 0.3, push: 1, lowBump: 0.4, highCut: 5000, output: -7 },
    'Torn cone': {
      circuit: 4,
      drive: 0.8,
      push: 1,
      lowCut: 150,
      tone: -0.2,
      highCut: 3500,
      output: -4,
    },
    'Hot channel': { circuit: 1, drive: 0.4, autoGain: 0, output: -17 },
  },
  formerPresets: {
    'Console edge': 'Console',
    'Glowing triode': 'Triode glow',
    'Crushed piano': 'Crushed',
    'Dark fuzz bed': 'Dark fuzz',
    'Deep warmth': 'Low warmth',
    'Forward sheen': 'Sheen',
  },
})

export type AnalogDrive = WasmDevice<typeof ANALOG_DRIVE_PARAMS>

/** Five circuits to push a sound through (tape preamp, console, transformer, triode, pentode), from weight and glue to a folded-over fuzz, with the level roughly held while you turn it up. */
export function createAnalogDrive(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof ANALOG_DRIVE_PARAMS> = {},
): Promise<AnalogDrive> {
  return WasmDevice.create(context, ANALOG_DRIVE_DEVICE, options)
}
