// GENERATED by scripts/gen-devices.mjs from cpp/devices/analog-delay/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const ANALOG_DELAY_PARAMS = {
  time: {
    id: 0,
    name: 'Time',
    min: 20,
    max: 1200,
    default: 380,
    taper: 'log',
    unit: 'ms',
    description:
      'The gap between repeats. It sets the clock of the delay line, so longer times are darker and grainier, and moving it bends the pitch of the echoes already in the line.',
  },
  feedback: {
    id: 1,
    name: 'Feedback',
    min: 0,
    max: 1.1,
    default: 0.45,
    taper: 'linear',
    unit: '',
    description:
      'How much of each echo goes round again. Near the top the repeats stop dying away and build into a soft, saturated drone.',
  },
  modDepth: {
    id: 2,
    name: 'Mod Depth',
    min: 0,
    max: 1,
    default: 0.3,
    taper: 'linear',
    unit: '',
    description:
      'How far the clock wobbles. A little gives the repeats a chorus shimmer, a lot gives a seasick vibrato.',
  },
  modRate: {
    id: 3,
    name: 'Mod Rate',
    min: 0.05,
    max: 8,
    default: 0.6,
    taper: 'log',
    unit: 'Hz',
    description: 'Speed of the clock wobble, from a slow drift to a fast warble.',
  },
  tone: {
    id: 4,
    name: 'Tone',
    min: 800,
    max: 8000,
    default: 3200,
    taper: 'log',
    unit: 'Hz',
    description:
      'Brightness of the echoes. Each repeat passes the filters again and comes back duller. At long times the clock holds the top end down whatever this is set to.',
  },
  age: {
    id: 5,
    name: 'Age',
    min: 0,
    max: 1,
    default: 0.3,
    taper: 'linear',
    unit: '',
    description:
      'Wear on the circuit. Higher settings add hiss that breathes with the signal, earlier saturation, softer attacks on the repeats and a faint clock whine at long times.',
  },
  intervalA: {
    id: 6,
    name: 'Interval A',
    min: 0,
    max: 6,
    default: 0,
    taper: 'linear',
    unit: '',
    choices: [
      'Off',
      'Octave down',
      'Fifth down',
      'Fourth down',
      'Fourth up',
      'Fifth up',
      'Octave up',
    ],
    description:
      'The first clock step. The echoes in the line jump by this interval when the step arrives and jump back by it when the clock returns.',
  },
  intervalB: {
    id: 7,
    name: 'Interval B',
    min: 0,
    max: 6,
    default: 0,
    taper: 'linear',
    unit: '',
    choices: [
      'Off',
      'Octave down',
      'Fifth down',
      'Fourth down',
      'Fourth up',
      'Fifth up',
      'Octave up',
    ],
    description:
      'The second clock step, taken after the clock has returned from the first. Off repeats Interval A alone.',
  },
  step: {
    id: 8,
    name: 'Step',
    min: 0,
    max: 3,
    default: 1,
    taper: 'linear',
    unit: '',
    choices: ['1', '2', '4', '8'],
    description:
      'How many repeats pass between clock steps. Short steps give a busy sequence of jumping echoes, long ones an occasional lurch.',
  },
  glide: {
    id: 9,
    name: 'Glide',
    min: 0,
    max: 1,
    default: 0,
    taper: 'linear',
    unit: '',
    description:
      'How slowly the clock moves to each step. At zero the echoes jump cleanly by the interval, higher up they slide like a tape being slowed by hand.',
  },
  spread: {
    id: 10,
    name: 'Spread',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
    description:
      'Stereo width of the echoes. The left and right lines drift and wobble apart, so the repeats widen and move while the dry signal stays put.',
  },
  mix: {
    id: 11,
    name: 'Mix',
    min: 0,
    max: 1,
    default: 0.35,
    taper: 'linear',
    unit: '',
    description: 'Balance between the dry signal and the echoes.',
  },
} as const satisfies Record<string, ParamSpec>

export type AnalogDelayParamName = keyof typeof ANALOG_DELAY_PARAMS

export const ANALOG_DELAY_DEVICE = defineWasmDevice({
  id: 'analog-delay',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/analog-delay.wasm', import.meta.url),
  params: ANALOG_DELAY_PARAMS,
})

export const ANALOG_DELAY_DESCRIPTOR = wasmDeviceDescriptor(ANALOG_DELAY_DEVICE, {
  name: 'Analog Delay',
  category: 'delay',
  description:
    'Bucket-brigade delay: dark, soft, slightly noisy repeats that dull as the time gets longer, with chorus on the echoes and a stepped clock that makes them jump by musical intervals.',
  presets: {
    'Dark repeats': {
      time: 380,
      feedback: 0.45,
      modDepth: 0.3,
      modRate: 0.6,
      tone: 3200,
      age: 0.3,
      spread: 0.5,
      mix: 0.35,
    },
    'Chorus echo': {
      time: 290,
      feedback: 0.4,
      modDepth: 0.55,
      modRate: 0.9,
      tone: 4500,
      age: 0.2,
      spread: 0.8,
      mix: 0.4,
    },
    'Seasick vibrato': {
      time: 160,
      feedback: 0.35,
      modDepth: 0.75,
      modRate: 3.1,
      tone: 3600,
      age: 0.4,
      spread: 0.3,
      mix: 0.5,
    },
    'Long and murky': {
      time: 900,
      feedback: 0.6,
      modDepth: 0.4,
      modRate: 0.25,
      tone: 2400,
      age: 0.6,
      spread: 0.6,
      mix: 0.4,
    },
    Slapback: {
      time: 95,
      feedback: 0.12,
      modDepth: 0.15,
      tone: 5000,
      age: 0.2,
      spread: 0.2,
      mix: 0.3,
    },
    'Octave hops': {
      time: 420,
      feedback: 0.6,
      modDepth: 0.15,
      tone: 4500,
      intervalA: 6,
      intervalB: 0,
      step: 1,
      glide: 0,
      mix: 0.4,
    },
    'Fifths and fourths': {
      time: 330,
      feedback: 0.65,
      modDepth: 0.2,
      tone: 4000,
      intervalA: 5,
      intervalB: 3,
      step: 0,
      glide: 0,
      mix: 0.4,
    },
    'Falling tape': {
      time: 500,
      feedback: 0.55,
      modDepth: 0.4,
      modRate: 0.3,
      age: 0.5,
      intervalA: 1,
      intervalB: 0,
      step: 2,
      glide: 0.85,
      mix: 0.4,
    },
    Runaway: {
      time: 300,
      feedback: 1.05,
      modDepth: 0.4,
      tone: 2800,
      age: 0.5,
      spread: 0.7,
      mix: 0.3,
    },
  },
})

export type AnalogDelay = WasmDevice<typeof ANALOG_DELAY_PARAMS>

/** Bucket-brigade delay: dark, soft, slightly noisy repeats that dull as the time gets longer, with chorus on the echoes and a stepped clock that makes them jump by musical intervals. */
export function createAnalogDelay(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof ANALOG_DELAY_PARAMS> = {},
): Promise<AnalogDelay> {
  return WasmDevice.create(context, ANALOG_DELAY_DEVICE, options)
}
