// GENERATED by scripts/gen-devices.mjs from cpp/devices/aurora/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const AURORA_PARAMS = {
  brilliance: {
    id: 0,
    name: 'Brilliance',
    min: 100,
    max: 16000,
    default: 1100,
    taper: 'log',
    unit: 'Hz',
    description:
      'Where the low-pass filters of both layers rest. Lower is dark and muted, like brass played softly; higher is bright and buzzing.',
  },
  lowCut: {
    id: 1,
    name: 'Low cut',
    min: 20,
    max: 2000,
    default: 40,
    taper: 'log',
    unit: 'Hz',
    description:
      'Where the high-pass filters of both layers sit. Raising it thins the body and leaves a nasal, airy band, the way strings and voices are voiced.',
  },
  resonance: {
    id: 2,
    name: 'Resonance',
    min: 0,
    max: 1,
    default: 0.25,
    taper: 'linear',
    unit: '',
    description:
      'Emphasis at the corners of both filters. It makes the band between Low cut and Brilliance ring, which turns the tone vocal and horn-like.',
  },
  contour: {
    id: 3,
    name: 'Contour',
    min: 0,
    max: 1,
    default: 0.6,
    taper: 'linear',
    unit: '',
    description:
      'How far each note starts below its resting brightness and overshoots above it before settling, the opening of a brass attack. At zero the filter stays still.',
  },
  attack: {
    id: 4,
    name: 'Attack',
    min: 0.005,
    max: 6,
    default: 0.4,
    taper: 'log',
    unit: 's',
    description:
      'How long a note takes to speak. The level fades in and the contour reaches its brightest point over this time.',
  },
  swell: {
    id: 5,
    name: 'Swell',
    min: 0,
    max: 1,
    default: 0.7,
    taper: 'linear',
    unit: '',
    description:
      'How much a held note keeps growing louder and brighter after its attack, as if the key were pressed harder. At zero a held note stays as it is.',
  },
  release: {
    id: 6,
    name: 'Release',
    min: 0.05,
    max: 12,
    default: 3,
    taper: 'log',
    unit: 's',
    description:
      'How long a note takes to fade after the key is let go. With Contour up, the tone darkens as it fades.',
  },
  detune: {
    id: 7,
    name: 'Detune',
    min: 0,
    max: 30,
    default: 8,
    taper: 'linear',
    unit: 'ct',
    description:
      'Tuning gap between the two layers, which sets how fast they beat, and how far each voice sits and wanders from the others. At zero everything is in tune.',
  },
  ring: {
    id: 8,
    name: 'Ring',
    min: 0,
    max: 1,
    default: 0,
    taper: 'linear',
    unit: '',
    description:
      'Amount of a ring modulator sweep at the start of each note: a metallic, bell-like onset that falls in pitch and melts into the pad. At zero there is none.',
  },
  volume: {
    id: 9,
    name: 'Volume',
    min: -48,
    max: 6,
    default: -9,
    taper: 'linear',
    unit: 'dB',
    description:
      'Output level of the instrument. A soft clip after it rounds off the peaks when many notes stack up.',
  },
} as const satisfies Record<string, ParamSpec>

export type AuroraParamName = keyof typeof AURORA_PARAMS

export const AURORA_DEVICE = defineWasmDevice({
  id: 'aurora',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/aurora.wasm', import.meta.url),
  params: AURORA_PARAMS,
})

export const AURORA_DESCRIPTOR = wasmDeviceDescriptor(AURORA_DEVICE, {
  name: 'Aurora',
  category: 'instrument',
  description:
    'Dual-layer brass and string pad in the style of the two-channel polysynths of the late seventies: notes start dark, speak with a filter overshoot and keep swelling while held.',
  presets: {
    'Slow brass': {
      brilliance: 1100,
      lowCut: 40,
      resonance: 0.25,
      contour: 0.6,
      attack: 0.4,
      swell: 0.7,
      release: 3,
      detune: 8,
    },
    'Soft horns': {
      brilliance: 800,
      lowCut: 180,
      resonance: 0.35,
      contour: 0.3,
      attack: 1.5,
      swell: 0.4,
      release: 4,
      detune: 6,
    },
    'Wide strings': {
      brilliance: 5000,
      lowCut: 250,
      resonance: 0.1,
      contour: 0.1,
      attack: 1,
      swell: 0.3,
      release: 4,
      detune: 14,
    },
    'Night choir': {
      brilliance: 1500,
      lowCut: 400,
      resonance: 0.6,
      contour: 0.2,
      attack: 2,
      swell: 0.5,
      release: 5,
      detune: 10,
    },
    'Metal dawn': {
      brilliance: 1800,
      contour: 0.4,
      attack: 0.2,
      swell: 0.5,
      release: 6,
      ring: 0.55,
    },
    'Slow bloom': {
      brilliance: 700,
      resonance: 0.3,
      contour: 0.8,
      attack: 3,
      swell: 1,
      release: 8,
      detune: 10,
    },
  },
})

export type Aurora = WasmDevice<typeof AURORA_PARAMS>

/** Dual-layer brass and string pad in the style of the two-channel polysynths of the late seventies: notes start dark, speak with a filter overshoot and keep swelling while held. Play it through `NoteDevice`: `noteOn(id, frequency, gain)` / `noteOff(id)`. */
export function createAurora(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof AURORA_PARAMS> = {},
): Promise<Aurora> {
  return WasmDevice.create(context, AURORA_DEVICE, options)
}
