// GENERATED by scripts/gen-devices.mjs from cpp/devices/bowed-string/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const BOWED_STRING_PARAMS = {
  mode: {
    id: 0,
    name: 'Mode',
    min: 0,
    max: 2,
    default: 1,
    taper: 'linear',
    unit: '',
    choices: ['Pluck', 'Ebow', 'Bow'],
    description:
      'How the string is played: plucked and left to ring, held singing by an ebow, or bowed with a rosin edge. Applies from the next note.',
  },
  attack: {
    id: 1,
    name: 'Attack',
    min: 0.005,
    max: 10,
    default: 1.2,
    taper: 'log',
    unit: 's',
    description:
      'How long an ebowed or bowed note takes to bloom. On Pluck it is a volume swell over the pick, switched off at the shortest setting.',
  },
  release: {
    id: 2,
    name: 'Release',
    min: 0.05,
    max: 15,
    default: 2,
    taper: 'log',
    unit: 's',
    description:
      'How long the string rings on after the key is released. It never rings longer than Decay.',
  },
  brightness: {
    id: 3,
    name: 'Brightness',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
    description:
      'How long the upper partials ring, from a dull, damped string to a bright, wiry one. It also brightens the pick, the ebow and the bow.',
  },
  decay: {
    id: 4,
    name: 'Decay',
    min: 0.3,
    max: 30,
    default: 6,
    taper: 'log',
    unit: 's',
    description:
      'How long a plucked string rings while its key is held. It also limits how long any note rings after release.',
  },
  position: {
    id: 5,
    name: 'Position',
    min: 0.02,
    max: 0.5,
    default: 0.14,
    taper: 'linear',
    unit: '',
    description:
      'Where along the string it is played, from thin and bright near the bridge to rounder and hollow towards the middle. Clearest on Pluck.',
  },
  pressure: {
    id: 6,
    name: 'Pressure',
    min: 0,
    max: 1,
    default: 0.4,
    taper: 'linear',
    unit: '',
    description:
      'How hard the ebow or bow presses: the ebow moves towards the octave, the bow from flute-like to raspy. Pluck ignores it.',
  },
  body: {
    id: 7,
    name: 'Body',
    min: 0,
    max: 1,
    default: 0.4,
    taper: 'linear',
    unit: '',
    description:
      "How much of the instrument's resonant body is heard. More adds low and mid resonances and takes away some of the bare string.",
  },
  vibrato: {
    id: 8,
    name: 'Vibrato',
    min: 0,
    max: 1,
    default: 0.15,
    taper: 'linear',
    unit: '',
    description: 'Depth of the pitch vibrato. It fades in a moment after each note starts.',
  },
  vibratoRate: {
    id: 9,
    name: 'Vibrato Rate',
    min: 2,
    max: 9,
    default: 5,
    taper: 'linear',
    unit: 'Hz',
    description: 'How fast the vibrato wavers.',
  },
  detune: {
    id: 10,
    name: 'Detune',
    min: 0,
    max: 25,
    default: 6,
    taper: 'linear',
    unit: 'ct',
    description:
      "Tunes each note's two strings apart, left and right, so they beat slowly, or leaves one string at zero. Applies from the next note.",
  },
  volume: {
    id: 11,
    name: 'Volume',
    min: -48,
    max: 6,
    default: -9,
    taper: 'linear',
    unit: 'dB',
    description:
      'Output level of the instrument. A soft clip after it rounds off the peaks when many notes stack up.',
  },
} as const satisfies Record<string, ParamSpec>

export type BowedStringParamName = keyof typeof BOWED_STRING_PARAMS

export const BOWED_STRING_DEVICE = defineWasmDevice({
  id: 'bowed-string',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/bowed-string.wasm', import.meta.url),
  params: BOWED_STRING_PARAMS,
})

export const BOWED_STRING_DESCRIPTOR = wasmDeviceDescriptor(BOWED_STRING_DEVICE, {
  name: 'Bow',
  category: 'instrument',
  description:
    'One string, three ways to play it: plucked, held singing by an ebow, or bowed. Sustained guitar swells and cello-like drones from a waveguide string with a resonant body.',
  experimental: true,
  presets: {
    'Ebow swell': {},
    'Cello drone': {
      mode: 2,
      attack: 0.6,
      release: 1.5,
      brightness: 0.4,
      position: 0.1,
      pressure: 0.55,
      body: 0.8,
      vibrato: 0.25,
      vibratoRate: 5.5,
      detune: 0,
    },
    'Glass bow': {
      mode: 2,
      attack: 3,
      release: 6,
      brightness: 0.75,
      decay: 12,
      position: 0.06,
      pressure: 0.15,
      body: 0.25,
      vibrato: 0.1,
      vibratoRate: 4.5,
      detune: 9,
    },
    'Octave feedback': {
      attack: 2.5,
      release: 5,
      brightness: 0.7,
      decay: 10,
      position: 0.3,
      pressure: 0.9,
      body: 0.3,
      vibrato: 0.3,
      vibratoRate: 5.5,
      detune: 10,
    },
    'Felt guitar': {
      mode: 0,
      attack: 0.005,
      release: 1.2,
      brightness: 0.35,
      decay: 5,
      position: 0.22,
      body: 0.6,
      vibrato: 0,
      detune: 4,
    },
    'Volume swell': {
      mode: 0,
      attack: 0.9,
      release: 4,
      brightness: 0.6,
      decay: 14,
      position: 0.12,
      body: 0.35,
      vibrato: 0.1,
      detune: 8,
    },
  },
})

export type BowedString = WasmDevice<typeof BOWED_STRING_PARAMS>

/** One string, three ways to play it: plucked, held singing by an ebow, or bowed. Sustained guitar swells and cello-like drones from a waveguide string with a resonant body. Play it through `NoteDevice`: `noteOn(id, frequency, gain)` / `noteOff(id)`. */
export function createBowedString(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof BOWED_STRING_PARAMS> = {},
): Promise<BowedString> {
  return WasmDevice.create(context, BOWED_STRING_DEVICE, options)
}
