// GENERATED by scripts/gen-devices.mjs from cpp/devices/bowed-string/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const BOWED_STRING_PARAMS = {
  mode: {
    id: 0,
    name: 'Mode',
    min: 0,
    max: 2,
    default: 1,
    taper: 'linear',
    unit: '',
    choices: ['Pluck', 'Ebow', 'Bow'],
  },
  attack: { id: 1, name: 'Attack', min: 0.005, max: 10, default: 1.2, taper: 'log', unit: 's' },
  release: { id: 2, name: 'Release', min: 0.05, max: 15, default: 2, taper: 'log', unit: 's' },
  brightness: {
    id: 3,
    name: 'Brightness',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
  },
  decay: { id: 4, name: 'Decay', min: 0.3, max: 30, default: 6, taper: 'log', unit: 's' },
  position: {
    id: 5,
    name: 'Position',
    min: 0.02,
    max: 0.5,
    default: 0.14,
    taper: 'linear',
    unit: '',
  },
  pressure: { id: 6, name: 'Pressure', min: 0, max: 1, default: 0.4, taper: 'linear', unit: '' },
  body: { id: 7, name: 'Body', min: 0, max: 1, default: 0.4, taper: 'linear', unit: '' },
  vibrato: { id: 8, name: 'Vibrato', min: 0, max: 1, default: 0.15, taper: 'linear', unit: '' },
  vibratoRate: {
    id: 9,
    name: 'Vibrato Rate',
    min: 2,
    max: 9,
    default: 5,
    taper: 'linear',
    unit: 'Hz',
  },
  detune: { id: 10, name: 'Detune', min: 0, max: 25, default: 6, taper: 'linear', unit: 'ct' },
  volume: { id: 11, name: 'Volume', min: -48, max: 6, default: -9, taper: 'linear', unit: 'dB' },
} as const satisfies Record<string, ParamSpec>

export type BowedStringParamName = keyof typeof BOWED_STRING_PARAMS

export const BOWED_STRING_DEVICE = defineWasmDevice({
  id: 'bowed-string',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/bowed-string.wasm', import.meta.url),
  params: BOWED_STRING_PARAMS,
})

export const BOWED_STRING_DESCRIPTOR = wasmDeviceDescriptor(BOWED_STRING_DEVICE, {
  name: 'Bow',
  category: 'instrument',
  description:
    'One string, three ways to play it: plucked, held singing by an ebow, or bowed. Sustained guitar swells and cello-like drones from a waveguide string with a resonant body.',
  experimental: true,
  presets: {
    'Ebow swell': {},
    'Cello drone': {
      mode: 2,
      attack: 0.6,
      release: 1.5,
      brightness: 0.4,
      position: 0.1,
      pressure: 0.55,
      body: 0.8,
      vibrato: 0.25,
      vibratoRate: 5.5,
      detune: 0,
    },
    'Glass bow': {
      mode: 2,
      attack: 3,
      release: 6,
      brightness: 0.75,
      decay: 12,
      position: 0.06,
      pressure: 0.15,
      body: 0.25,
      vibrato: 0.1,
      vibratoRate: 4.5,
      detune: 9,
    },
    'Octave feedback': {
      attack: 2.5,
      release: 5,
      brightness: 0.7,
      decay: 10,
      position: 0.3,
      pressure: 0.9,
      body: 0.3,
      vibrato: 0.3,
      vibratoRate: 5.5,
      detune: 10,
    },
    'Felt guitar': {
      mode: 0,
      attack: 0.005,
      release: 1.2,
      brightness: 0.35,
      decay: 5,
      position: 0.22,
      body: 0.6,
      vibrato: 0,
      detune: 4,
    },
    'Volume swell': {
      mode: 0,
      attack: 0.9,
      release: 4,
      brightness: 0.6,
      decay: 14,
      position: 0.12,
      body: 0.35,
      vibrato: 0.1,
      detune: 8,
    },
  },
})

export type BowedString = WasmDevice<typeof BOWED_STRING_PARAMS>

/** One string, three ways to play it: plucked, held singing by an ebow, or bowed. Sustained guitar swells and cello-like drones from a waveguide string with a resonant body. Play it through `NoteDevice`: `noteOn(id, frequency, gain)` / `noteOff(id)`. */
export function createBowedString(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof BOWED_STRING_PARAMS> = {},
): Promise<BowedString> {
  return WasmDevice.create(context, BOWED_STRING_DEVICE, options)
}
