// GENERATED by scripts/gen-devices.mjs from cpp/devices/cascade/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const CASCADE_PARAMS = {
  pattern: {
    id: 0,
    name: 'Pattern',
    min: 0,
    max: 3,
    default: 0,
    taper: 'linear',
    unit: '',
    choices: ['Stack', 'Restrike', 'Drone', 'Steps'],
    description:
      'How a slice is replayed. Stack loops it at several speeds at once, Restrike strikes its start again and again, Drone holds a short piece, Steps climbs like an arpeggio.',
  },
  time: {
    id: 1,
    name: 'Time',
    min: 60,
    max: 2000,
    default: 400,
    taper: 'log',
    unit: 'ms',
    description:
      'How long after a note it first comes back, and the pulse its repeats fall on. Short times give a fast glittering stutter; long times replay whole phrases.',
  },
  repeats: {
    id: 2,
    name: 'Repeats',
    min: 1,
    max: 16,
    default: 5,
    taper: 'linear',
    unit: '',
    description:
      'How many times each slice comes back before it stops, which sets how long the cascade goes on after you stop playing.',
  },
  decay: {
    id: 3,
    name: 'Decay',
    min: 0,
    max: 1,
    default: 0.4,
    taper: 'linear',
    unit: '',
    description:
      'How much quieter and darker each repeat is than the one before. Fully down, every repeat is as loud and as bright as the first.',
  },
  high: {
    id: 4,
    name: 'High',
    min: 0,
    max: 1,
    default: 0.6,
    taper: 'linear',
    unit: '',
    description:
      'Level of the replays that run faster than you played. They sound an octave or more above and come round two or four times in the space of one slower repeat.',
  },
  low: {
    id: 5,
    name: 'Low',
    min: 0,
    max: 1,
    default: 0,
    taper: 'linear',
    unit: '',
    description:
      'Level of a half-speed replay: the slice an octave down and twice as long, underneath the rest and in the middle of the stereo picture.',
  },
  interval: {
    id: 6,
    name: 'Interval',
    min: 0,
    max: 1,
    default: 0,
    taper: 'linear',
    unit: '',
    choices: ['Octaves', 'Octaves and fifths'],
    description:
      'Which speeds the faster replays use. Octaves stays on the note you played. Octaves and fifths adds replays a fifth above, which fall three against two with the rest.',
  },
  shape: {
    id: 7,
    name: 'Shape',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
    description:
      'The envelope of every replay. Low gives sharp plucked fronts that die away; high makes each one swell in and out, so the pattern blurs into a wash.',
  },
  reverse: {
    id: 8,
    name: 'Reverse',
    min: 0,
    max: 1,
    default: 0,
    taper: 'linear',
    unit: '',
    description:
      'The chance that a replay runs backwards. Fully down everything runs forwards; fully up everything runs backwards.',
  },
  spread: {
    id: 9,
    name: 'Spread',
    min: 0,
    max: 1,
    default: 0.6,
    taper: 'linear',
    unit: '',
    description:
      'How far the replays are placed to the left and right. The faster ones sit furthest out and swap sides as they repeat.',
  },
  tone: {
    id: 10,
    name: 'Tone',
    min: 800,
    max: 18000,
    default: 9000,
    taper: 'log',
    unit: 'Hz',
    description:
      'Takes the highs off all the replays. Lower settings make the cascade softer and further away.',
  },
  mix: {
    id: 11,
    name: 'Mix',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
    description: 'Balance between the dry signal and the cascade.',
  },
} as const satisfies Record<string, ParamSpec>

export type CascadeParamName = keyof typeof CASCADE_PARAMS

export const CASCADE_DEVICE = defineWasmDevice({
  id: 'cascade',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/cascade.wasm', import.meta.url),
  params: CASCADE_PARAMS,
})

export const CASCADE_DESCRIPTOR = wasmDeviceDescriptor(CASCADE_DEVICE, {
  name: 'Cascade',
  category: 'texture',
  description:
    'Replays little loops of what you just played, stacked at octave (and fifth) speeds in a pattern you can hear, so one note comes back as a shimmering, rhythmic cascade of itself.',
  presets: {
    'Octave stack': {},
    'Glass rain': { time: 140, repeats: 8, decay: 0.3, high: 1, shape: 0, spread: 1, tone: 14000 },
    'Slow tiles': { time: 1100, repeats: 6, decay: 0.3, high: 0.5, low: 0.3, shape: 1, tone: 6500 },
    Restruck: {
      pattern: 1,
      time: 500,
      repeats: 7,
      decay: 0.3,
      high: 0.5,
      shape: 0.15,
      spread: 0.9,
    },
    'Long drone': {
      pattern: 2,
      time: 900,
      repeats: 14,
      decay: 0.2,
      high: 0.3,
      shape: 1,
      spread: 0.8,
      tone: 8000,
    },
    'Rising steps': {
      pattern: 3,
      time: 260,
      repeats: 8,
      decay: 0.25,
      high: 0.8,
      interval: 1,
      shape: 0.2,
      spread: 0.8,
    },
    Undertow: {
      time: 600,
      repeats: 5,
      decay: 0.45,
      high: 0,
      low: 1,
      shape: 0.6,
      reverse: 1,
      spread: 0.8,
      tone: 3500,
    },
    'Sparkle bed': {
      time: 320,
      repeats: 14,
      decay: 0.15,
      high: 1,
      interval: 1,
      shape: 1,
      reverse: 0.4,
      spread: 1,
      tone: 12000,
      mix: 0.35,
    },
    'Dropped marbles': {
      pattern: 1,
      time: 150,
      repeats: 12,
      decay: 0.2,
      high: 0.8,
      interval: 1,
      shape: 0,
      spread: 1,
      tone: 14000,
    },
    'Deep drone': {
      pattern: 2,
      time: 1400,
      repeats: 12,
      decay: 0.3,
      high: 0,
      low: 1,
      shape: 1,
      spread: 0.5,
      tone: 2500,
    },
    'Drone of fifths': {
      pattern: 2,
      time: 400,
      repeats: 16,
      decay: 0.15,
      high: 1,
      interval: 1,
      shape: 1,
      spread: 1,
      tone: 14000,
    },
    'Slow staircase': {
      pattern: 3,
      time: 800,
      repeats: 6,
      decay: 0.3,
      high: 0.6,
      low: 0.5,
      shape: 0.8,
      spread: 0.7,
      tone: 7000,
    },
    'Phrase returns': {
      time: 1500,
      repeats: 3,
      decay: 0.6,
      high: 0,
      low: 0,
      shape: 0.5,
      spread: 0.4,
    },
    'Faint halo': { time: 500, repeats: 4, decay: 0.6, high: 0.4, shape: 1, tone: 5000, mix: 0.15 },
    'Backwards stack': {
      time: 550,
      repeats: 6,
      decay: 0.35,
      high: 0.7,
      shape: 0.8,
      reverse: 1,
      spread: 0.8,
    },
    'Only the echoes': {
      time: 700,
      repeats: 10,
      decay: 0.2,
      high: 0.7,
      low: 0.5,
      shape: 1,
      reverse: 0.5,
      spread: 1,
      tone: 7000,
      mix: 1,
    },
  },
})

export type Cascade = WasmDevice<typeof CASCADE_PARAMS>

/** Replays little loops of what you just played, stacked at octave (and fifth) speeds in a pattern you can hear, so one note comes back as a shimmering, rhythmic cascade of itself. */
export function createCascade(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof CASCADE_PARAMS> = {},
): Promise<Cascade> {
  return WasmDevice.create(context, CASCADE_DEVICE, options)
}
