// GENERATED by scripts/gen-devices.mjs from cpp/devices/dusk/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const DUSK_PARAMS = {
  wave: {
    id: 0,
    name: 'Wave',
    min: 0,
    max: 4,
    default: 4,
    taper: 'linear',
    unit: '',
    choices: ['Saw', 'Square', 'Saw + square', 'Moving pulse', 'Saw + moving pulse'],
    description:
      'Which waves the oscillator plays. Moving pulse slowly sweeps the width of the pulse, so even one held note keeps changing.',
  },
  sub: {
    id: 1,
    name: 'Sub',
    min: 0,
    max: 1,
    default: 0.35,
    taper: 'linear',
    unit: '',
    description:
      'Level of the square wave an octave below the note. It is locked to the oscillator, so it adds weight without beating.',
  },
  lowCut: {
    id: 2,
    name: 'Low cut',
    min: 0,
    max: 3,
    default: 0,
    taper: 'linear',
    unit: '',
    choices: ['Off', 'Light', 'Medium', 'Deep'],
    description:
      'Thins the low end in four steps, from the full sound to a light pad that leaves room for a bass.',
  },
  cutoff: {
    id: 3,
    name: 'Cutoff',
    min: 40,
    max: 18000,
    default: 2500,
    taper: 'log',
    unit: 'Hz',
    description:
      'Brightness of the low-pass filter. It follows the keyboard, so low and high notes keep the same colour.',
  },
  resonance: {
    id: 4,
    name: 'Resonance',
    min: 0,
    max: 1,
    default: 0.15,
    taper: 'linear',
    unit: '',
    description:
      'Emphasis at the cutoff. Higher makes the filter ring, and at the top it sings a pure note of its own that follows the keys.',
  },
  envelope: {
    id: 5,
    name: 'Envelope',
    min: -1,
    max: 1,
    default: 0.25,
    taper: 'linear',
    unit: '',
    description:
      'How far the envelope moves the filter. Above zero a note opens as it arrives and closes as it fades. Below zero it does the opposite.',
  },
  attack: {
    id: 6,
    name: 'Attack',
    min: 0.001,
    max: 8,
    default: 0.6,
    taper: 'log',
    unit: 's',
    description:
      'How long a note takes to fade in. The filter moves with it, so a slow attack also blooms in brightness.',
  },
  release: {
    id: 7,
    name: 'Release',
    min: 0.002,
    max: 12,
    default: 2.5,
    taper: 'log',
    unit: 's',
    description:
      'How long a note takes to fade out after the key is let go. It also sets how quickly a held note settles from its peak.',
  },
  chorus: {
    id: 8,
    name: 'Chorus',
    min: 0,
    max: 3,
    default: 1,
    taper: 'linear',
    unit: '',
    choices: ['Off', 'I', 'II', 'I + II'],
    description:
      'The stereo chorus. I is slow and calm, II is faster and deeper, I + II is a fast shimmer in the centre. Off is plain and mono.',
  },
  volume: {
    id: 9,
    name: 'Volume',
    min: -48,
    max: 6,
    default: -9,
    taper: 'linear',
    unit: 'dB',
    description:
      'Output level of the instrument. A soft clip after it rounds off the peaks when many notes stack up.',
  },
} as const satisfies Record<string, ParamSpec>

export type DuskParamName = keyof typeof DUSK_PARAMS

export const DUSK_DEVICE = defineWasmDevice({
  id: 'dusk',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/dusk.wasm', import.meta.url),
  params: DUSK_PARAMS,
})

export const DUSK_DESCRIPTOR = wasmDeviceDescriptor(DUSK_DEVICE, {
  name: 'Dusk',
  category: 'instrument',
  description:
    'Eighties chorus polysynth for pads: one perfectly tuned oscillator per key with a locked sub octave, a four-pole filter that can sing, and a wide two-line stereo chorus.',
  presets: {
    'Soft strings': {
      wave: 4,
      sub: 0.35,
      lowCut: 0,
      cutoff: 2500,
      resonance: 0.15,
      envelope: 0.25,
      attack: 0.6,
      release: 2.5,
      chorus: 1,
    },
    'Wide pulse': { wave: 3, sub: 0, lowCut: 1, cutoff: 3500, attack: 1.2, release: 4, chorus: 2 },
    'Sub floor': {
      wave: 1,
      sub: 1,
      cutoff: 1200,
      resonance: 0.25,
      envelope: 0.1,
      attack: 0.3,
      release: 3,
    },
    'Singing filter': {
      wave: 0,
      sub: 0,
      lowCut: 3,
      cutoff: 1046.5,
      resonance: 1,
      envelope: 0,
      attack: 0.8,
      release: 5,
    },
    'Slow bloom': {
      wave: 2,
      sub: 0.5,
      cutoff: 300,
      resonance: 0.3,
      envelope: 0.8,
      attack: 3,
      release: 8,
      chorus: 2,
    },
    'Shimmer organ': {
      wave: 1,
      sub: 0.6,
      cutoff: 1800,
      envelope: 0,
      attack: 0.02,
      release: 0.8,
      chorus: 3,
    },
  },
})

export type Dusk = WasmDevice<typeof DUSK_PARAMS>

/** Eighties chorus polysynth for pads: one perfectly tuned oscillator per key with a locked sub octave, a four-pole filter that can sing, and a wide two-line stereo chorus. Play it through `NoteDevice`: `noteOn(id, frequency, gain)` / `noteOff(id)`. */
export function createDusk(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof DUSK_PARAMS> = {},
): Promise<Dusk> {
  return WasmDevice.create(context, DUSK_DEVICE, options)
}
