// GENERATED by scripts/gen-devices.mjs from cpp/devices/flanger/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const FLANGER_PARAMS = {
  delayMs: {
    id: 0,
    name: 'Delay',
    min: 0.5,
    max: 10,
    default: 2.5,
    taper: 'log',
    unit: 'ms',
    description:
      'The centre time of the sweep, which sets where the comb sits. Short puts the notches high and far apart; longer brings them lower and closer.',
  },
  rate: {
    id: 1,
    name: 'Rate',
    min: 0.01,
    max: 10,
    default: 0.25,
    taper: 'log',
    unit: 'Hz',
    description:
      'How fast the comb sweeps up and down. Slow is a long jet sweep; fast is a warble.',
  },
  depth: {
    id: 2,
    name: 'Depth',
    min: 0,
    max: 100,
    default: 50,
    taper: 'linear',
    unit: '%',
    description: 'How far the sweep travels either side of Delay. At zero the comb stands still.',
  },
  feedback: {
    id: 3,
    name: 'Feedback',
    min: -95,
    max: 95,
    default: 30,
    taper: 'linear',
    unit: '%',
    description:
      'Sends the swept signal back in, which sharpens the comb. Negative values hollow it out instead.',
  },
  shape: {
    id: 4,
    name: 'Shape',
    min: 0,
    max: 5,
    default: 0,
    taper: 'linear',
    unit: '',
    choices: ['Sine', 'Triangle', 'Saw up', 'Saw down', 'Square', 'Random'],
    description:
      'The path the sweep follows. Sine and Triangle glide, the saws go one way and snap back, Square and Random jump from point to point.',
  },
  stereo: {
    id: 5,
    name: 'Stereo',
    min: 0,
    max: 180,
    default: 90,
    taper: 'linear',
    unit: 'deg',
    description:
      'Puts the right side of the sweep ahead of the left. At zero both move together; higher values make the sweep cross the stereo field.',
  },
  mix: {
    id: 6,
    name: 'Mix',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
    description:
      'Balance between the dry and the delayed sound. The notches of the comb are deepest in the middle.',
  },
} as const satisfies Record<string, ParamSpec>

export type FlangerParamName = keyof typeof FLANGER_PARAMS

export const FLANGER_DEVICE = defineWasmDevice({
  id: 'flanger',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/flanger.wasm', import.meta.url),
  params: FLANGER_PARAMS,
})

export const FLANGER_DESCRIPTOR = wasmDeviceDescriptor(FLANGER_DEVICE, {
  name: 'Flanger',
  category: 'modulation',
  description:
    'Short swept delay with positive or negative feedback, six LFO shapes and a stereo phase offset: jet sweeps, hollow combs and metallic resonance.',
  presets: {
    'Gentle Sweep': {
      delayMs: 2.5,
      rate: 0.25,
      depth: 50,
      feedback: 30,
      shape: 0,
      stereo: 90,
      mix: 0.5,
    },
    'Classic Jet': {
      delayMs: 2.5,
      rate: 0.25,
      depth: 60,
      feedback: 45,
      shape: 0,
      stereo: 90,
      mix: 0.5,
    },
    'Slow Sweep': {
      delayMs: 4,
      rate: 0.08,
      depth: 80,
      feedback: 30,
      shape: 1,
      stereo: 90,
      mix: 0.5,
    },
    'Negative Hollow': {
      delayMs: 1.5,
      rate: 0.4,
      depth: 50,
      feedback: -70,
      shape: 0,
      stereo: 60,
      mix: 0.5,
    },
    'Through-Zero Feel': {
      delayMs: 0.8,
      rate: 0.3,
      depth: 100,
      feedback: 20,
      shape: 0,
      stereo: 180,
      mix: 0.5,
    },
    'Tremolo Saw': { delayMs: 3, rate: 2, depth: 40, feedback: 10, shape: 2, stereo: 0, mix: 0.5 },
    'Stepped Random': {
      delayMs: 5,
      rate: 4,
      depth: 70,
      feedback: 40,
      shape: 5,
      stereo: 90,
      mix: 0.5,
    },
    'Metal Resonator': {
      delayMs: 1,
      rate: 0.05,
      depth: 30,
      feedback: 92,
      shape: 0,
      stereo: 45,
      mix: 0.45,
    },
    'Wide Wash': {
      delayMs: 8,
      rate: 0.15,
      depth: 55,
      feedback: 25,
      shape: 1,
      stereo: 180,
      mix: 0.4,
    },
    'Square Chop': { delayMs: 2, rate: 1, depth: 50, feedback: 0, shape: 4, stereo: 0, mix: 0.5 },
    'Faint Air': {
      delayMs: 1,
      rate: 0.15,
      depth: 60,
      feedback: 0,
      shape: 0,
      stereo: 180,
      mix: 0.2,
    },
    'Glacial Drift': {
      delayMs: 3,
      rate: 0.02,
      depth: 90,
      feedback: 55,
      shape: 0,
      stereo: 120,
      mix: 0.5,
    },
    'Rising Comb': {
      delayMs: 3.5,
      rate: 0.2,
      depth: 85,
      feedback: 40,
      shape: 3,
      stereo: 90,
      mix: 0.45,
    },
    'Standing Comb': {
      delayMs: 4,
      rate: 0.25,
      depth: 0,
      feedback: -60,
      shape: 0,
      stereo: 0,
      mix: 0.5,
    },
    'Fast Warble': { delayMs: 5, rate: 6, depth: 12, feedback: 20, shape: 0, stereo: 90, mix: 0.5 },
    'Deep Dive': { delayMs: 7, rate: 0.1, depth: 100, feedback: 75, shape: 0, stereo: 0, mix: 0.5 },
  },
})

export type Flanger = WasmDevice<typeof FLANGER_PARAMS>

/** Short swept delay with positive or negative feedback, six LFO shapes and a stereo phase offset: jet sweeps, hollow combs and metallic resonance. */
export function createFlanger(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof FLANGER_PARAMS> = {},
): Promise<Flanger> {
  return WasmDevice.create(context, FLANGER_DEVICE, options)
}
