// GENERATED by scripts/gen-devices.mjs from cpp/devices/flute/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const FLUTE_PARAMS = {
  type: {
    id: 0,
    name: 'Type',
    min: 0,
    max: 4,
    default: 0,
    taper: 'linear',
    unit: '',
    choices: ['Concert', 'Low flute', 'Shakuhachi', 'Pan pipes', 'Wood flute'],
    description:
      'Which flute is played: a clear concert flute, a darker, airier low flute, a breathy shakuhachi, hollow pan pipes or a round wood flute. Applies from the next note.',
  },
  breath: {
    id: 1,
    name: 'Breath',
    min: 0,
    max: 1,
    default: 0.4,
    taper: 'linear',
    unit: '',
    description:
      'How much air is heard in the tone. Low is a clean, pure flute; high is mostly breath with the note inside it.',
  },
  blow: {
    id: 2,
    name: 'Blow',
    min: 0,
    max: 1,
    default: 0.45,
    taper: 'linear',
    unit: '',
    description:
      'How hard the flute is blown. Soft is close to a pure tone; hard adds overtones for a brighter, more open sound. Loud notes are always brighter than soft ones.',
  },
  chiff: {
    id: 3,
    name: 'Chiff',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
    description:
      'The puff of air and the flick of a higher note at the very start of each note. Slow attacks have little of either.',
  },
  attack: {
    id: 4,
    name: 'Attack',
    min: 0.005,
    max: 3,
    default: 0.04,
    taper: 'log',
    unit: 's',
    description:
      'How long the breath takes to arrive. Short is a tongued note; long swells in from nothing. Low notes always speak a little later than high ones.',
  },
  release: {
    id: 5,
    name: 'Release',
    min: 0.03,
    max: 8,
    default: 0.4,
    taper: 'log',
    unit: 's',
    description:
      'How long a note takes to die away after the key is let go. Its pitch sags a little as it fades, as a breath running out does.',
  },
  vibrato: {
    id: 6,
    name: 'Vibrato',
    min: 0,
    max: 1,
    default: 0.35,
    taper: 'linear',
    unit: '',
    description:
      'Depth of the breath vibrato: a wobble in loudness, brightness and pitch that fades in once a note has settled. Each type has its own speed.',
  },
  scoop: {
    id: 7,
    name: 'Scoop',
    min: 0,
    max: 200,
    default: 15,
    taper: 'linear',
    unit: 'ct',
    description:
      "How far below the note each one starts before it bends up into tune. A little sounds played by a person; a lot is the shakuhachi's bend from below.",
  },
  volume: {
    id: 8,
    name: 'Volume',
    min: -48,
    max: 6,
    default: -9,
    taper: 'linear',
    unit: 'dB',
    description:
      'Output level of the instrument. A soft clip after it rounds off the peaks when many notes stack up.',
  },
} as const satisfies Record<string, ParamSpec>

export type FluteParamName = keyof typeof FLUTE_PARAMS

export const FLUTE_DEVICE = defineWasmDevice({
  id: 'flute',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/flute.wasm', import.meta.url),
  params: FLUTE_PARAMS,
})

export const FLUTE_DESCRIPTOR = wasmDeviceDescriptor(FLUTE_DEVICE, {
  name: 'Flute',
  category: 'instrument',
  description:
    'A blown flute for slow lines and held chords: concert and low flutes, shakuhachi, pan pipes and wood flute, with breath in the tone and a touch that brightens as it gets louder.',
  presets: {
    'Concert flute': {
      type: 0,
      breath: 0.4,
      blow: 0.45,
      chiff: 0.5,
      attack: 0.04,
      release: 0.4,
      vibrato: 0.35,
      scoop: 15,
    },
    Shakuhachi: {
      type: 2,
      breath: 0.62,
      blow: 0.55,
      chiff: 0.9,
      attack: 0.02,
      release: 0.7,
      vibrato: 0.6,
      scoop: 120,
    },
    'Pan pipes': {
      type: 3,
      breath: 0.5,
      blow: 0.5,
      chiff: 0.9,
      attack: 0.012,
      release: 0.5,
      vibrato: 0,
      scoop: 25,
    },
    'Breath pad': {
      type: 1,
      breath: 0.95,
      blow: 0.15,
      chiff: 0,
      attack: 1.5,
      release: 2.8,
      vibrato: 0.2,
      scoop: 0,
      volume: -14,
    },
    'Low flute drone': {
      type: 1,
      breath: 0.5,
      blow: 0.25,
      chiff: 0.2,
      attack: 0.7,
      release: 4,
      vibrato: 0.3,
      scoop: 10,
    },
    'Canyon flute': {
      type: 4,
      breath: 0.3,
      blow: 0.4,
      chiff: 0.6,
      attack: 0.03,
      release: 0.8,
      vibrato: 0.4,
      scoop: 40,
    },
    'Soft wind lead': {
      type: 0,
      breath: 0.5,
      blow: 0.25,
      chiff: 0,
      attack: 0.12,
      release: 0.9,
      vibrato: 0.5,
      scoop: 30,
    },
  },
})

export type Flute = WasmDevice<typeof FLUTE_PARAMS>

/** A blown flute for slow lines and held chords: concert and low flutes, shakuhachi, pan pipes and wood flute, with breath in the tone and a touch that brightens as it gets louder. Play it through `NoteDevice`: `noteOn(id, frequency, gain)` / `noteOff(id)`. */
export function createFlute(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof FLUTE_PARAMS> = {},
): Promise<Flute> {
  return WasmDevice.create(context, FLUTE_DEVICE, options)
}
