// GENERATED by scripts/gen-devices.mjs from cpp/devices/fm-bass/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const FM_BASS_PARAMS = {
  ratio: {
    id: 0,
    name: 'Ratio',
    min: 0,
    max: 6,
    default: 1,
    taper: 'linear',
    unit: '',
    choices: ['1/2', '1', '2', '3', '4', '5', '7'],
    description:
      'Pitch of the bending sine against the note, which sets the overtones. 1 is full and round, 2 and 4 hollow, 3, 5 and 7 wooden to glassy, and 1/2 adds an octave below.',
  },
  depth: {
    id: 1,
    name: 'Depth',
    min: 0,
    max: 1,
    default: 0.65,
    taper: 'linear',
    unit: '',
    description:
      'How far the note is bent when it is struck, which is how bright and hard its start is. At zero the bass is a pure sine. Harder playing bends further.',
  },
  bite: {
    id: 2,
    name: 'Bite',
    min: 0.01,
    max: 4,
    default: 0.25,
    taper: 'log',
    unit: 's',
    description:
      'How long the brightness of the strike takes to fall away. Short is a click or a knock on the front of the note; long is a slow darkening.',
  },
  body: {
    id: 3,
    name: 'Body',
    min: 0,
    max: 1,
    default: 0.25,
    taper: 'linear',
    unit: '',
    description:
      'How much of the brightness stays once the strike has passed. At zero the note settles to a pure round tone; at full it stays as bright as it was struck.',
  },
  feedback: {
    id: 4,
    name: 'Feedback',
    min: 0,
    max: 1,
    default: 0,
    taper: 'linear',
    unit: '',
    description:
      'Feeds the bending sine back into itself, which adds an edge: a little rasp at first, a buzzing growl at the top.',
  },
  sub: {
    id: 5,
    name: 'Sub',
    min: 0,
    max: 1,
    default: 0.25,
    taper: 'linear',
    unit: '',
    description:
      'Level of a pure tone one octave below the note, for weight under a thin or hollow sound.',
  },
  decay: {
    id: 6,
    name: 'Decay',
    min: 0.05,
    max: 20,
    default: 1.4,
    taper: 'log',
    unit: 's',
    description:
      'How long a held note takes to die away, from a short thump to a fall of many seconds. At the very top the note holds for as long as the key is down.',
  },
  release: {
    id: 7,
    name: 'Release',
    min: 0.02,
    max: 5,
    default: 0.15,
    taper: 'log',
    unit: 's',
    description:
      'How quickly the note fades once the key is let go. A note never rings longer after the key than it would have while held.',
  },
  glide: {
    id: 8,
    name: 'Glide',
    min: 0,
    max: 1,
    default: 0.06,
    taper: 'linear',
    unit: 's',
    description:
      'Time the pitch takes to slide to a new key pressed while another is still held. Keys played apart start on pitch.',
  },
  volume: {
    id: 9,
    name: 'Volume',
    min: -48,
    max: 6,
    default: -9,
    taper: 'linear',
    unit: 'dB',
    description:
      'Output level of the instrument. A soft clip after it catches peaks at high settings.',
  },
} as const satisfies Record<string, ParamSpec>

export type FmBassParamName = keyof typeof FM_BASS_PARAMS

export const FM_BASS_DEVICE = defineWasmDevice({
  id: 'fm-bass',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/fm-bass.wasm', import.meta.url),
  params: FM_BASS_PARAMS,
})

export const FM_BASS_DESCRIPTOR = wasmDeviceDescriptor(FM_BASS_DEVICE, {
  name: 'FM Bass',
  category: 'instrument',
  description:
    'Two-operator FM bass: a sine whose phase is bent by a second sine, bright where it is struck and rounder as the bend falls away, from a soft thump through a hollow knock to a growl.',
  presets: {
    'Round knock': {
      ratio: 1,
      depth: 0.65,
      bite: 0.25,
      body: 0.25,
      feedback: 0,
      sub: 0.25,
      decay: 1.4,
      release: 0.15,
      glide: 0.06,
      volume: -9,
    },
    'Wooden knock': {
      ratio: 3,
      depth: 0.6,
      bite: 0.05,
      body: 0.04,
      sub: 0.15,
      decay: 0.7,
      release: 0.12,
      volume: -7,
    },
    'Rubber bass': {
      ratio: 2,
      depth: 0.5,
      bite: 0.3,
      body: 0.7,
      feedback: 0.2,
      sub: 0.3,
      decay: 0.9,
      release: 0.08,
      glide: 0.1,
    },
    'Low growl': {
      ratio: 1,
      depth: 0.62,
      bite: 0.8,
      body: 0.6,
      feedback: 0.8,
      sub: 0.35,
      decay: 20,
      release: 0.25,
      glide: 0.08,
    },
    'Sub click': {
      ratio: 4,
      depth: 0.75,
      bite: 0.03,
      body: 0,
      sub: 0.7,
      decay: 1.5,
      release: 0.3,
      volume: -10.5,
    },
    'Slow dark fall': {
      ratio: 1,
      depth: 0.45,
      bite: 4,
      body: 0.1,
      sub: 0.3,
      decay: 14,
      release: 3,
      glide: 0.25,
      volume: -9.5,
    },
    'Glass pluck': {
      ratio: 6,
      depth: 0.45,
      bite: 0.3,
      body: 0.03,
      sub: 0.2,
      decay: 1.8,
      release: 0.7,
    },
    'Held hum': {
      ratio: 0,
      depth: 0.5,
      bite: 2.5,
      body: 0.75,
      feedback: 0.5,
      sub: 0.2,
      decay: 20,
      release: 2.5,
      glide: 0.4,
      volume: -11.5,
    },
    'Soft sine': {
      depth: 0.12,
      bite: 0.5,
      body: 1,
      sub: 0.15,
      decay: 20,
      release: 0.6,
      glide: 0.12,
      volume: -10.5,
    },
    'Short thump': {
      depth: 0.7,
      bite: 0.03,
      body: 0,
      sub: 0.2,
      decay: 0.45,
      release: 0.1,
      glide: 0,
      volume: -6,
    },
    'Hollow pulse': {
      ratio: 2,
      depth: 0.55,
      bite: 1.2,
      body: 0.5,
      sub: 0.2,
      decay: 3,
      release: 0.4,
    },
    'Buzz bass': {
      depth: 0.5,
      bite: 0.2,
      body: 0.9,
      feedback: 1,
      sub: 0.2,
      decay: 2,
      release: 0.06,
      glide: 0.04,
      volume: -7,
    },
    'Deep weight': {
      ratio: 0,
      depth: 0.4,
      bite: 0.25,
      body: 0.6,
      sub: 1,
      decay: 6,
      release: 0.5,
      glide: 0.15,
      volume: -12.5,
    },
    'Low bell': {
      ratio: 5,
      depth: 0.4,
      bite: 1.5,
      body: 0.1,
      sub: 0.35,
      decay: 6,
      release: 2,
      volume: -10,
    },
    'Slow slide drone': {
      depth: 0.4,
      bite: 4,
      body: 0.7,
      feedback: 0.6,
      sub: 0.5,
      decay: 20,
      release: 5,
      glide: 1,
      volume: -10.5,
    },
    'Long tail knock': {
      ratio: 3,
      depth: 0.45,
      bite: 0.1,
      body: 0.05,
      sub: 0.45,
      decay: 8,
      release: 2.5,
      volume: -10,
    },
  },
})

export type FmBass = WasmDevice<typeof FM_BASS_PARAMS>

/** Two-operator FM bass: a sine whose phase is bent by a second sine, bright where it is struck and rounder as the bend falls away, from a soft thump through a hollow knock to a growl. Play it through `NoteDevice`: `noteOn(id, frequency, gain)` / `noteOff(id)`. */
export function createFmBass(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof FM_BASS_PARAMS> = {},
): Promise<FmBass> {
  return WasmDevice.create(context, FM_BASS_DEVICE, options)
}
