// GENERATED by scripts/gen-devices.mjs from cpp/devices/fog/device.json. Do not edit.

import { type DeviceMeterSpec } from '../../core/devices/Device'
import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const FOG_PARAMS = {
  size: {
    id: 0,
    name: 'Size',
    min: 10,
    max: 600,
    default: 150,
    taper: 'log',
    unit: 'ms',
    description:
      'How long the cloud lasts. Short only softens attacks. Long turns each note into a slow swell and anything rhythmic into weather.',
  },
  density: {
    id: 1,
    name: 'Density',
    min: 0,
    max: 1,
    default: 0.8,
    taper: 'linear',
    unit: '',
    description:
      'How finely the cloud is ground. Low is a spray of separate echoes. High is a smooth wash with no grain.',
  },
  layers: {
    id: 2,
    name: 'Layers',
    min: 1,
    max: 3,
    default: 1,
    taper: 'linear',
    unit: '',
    step: 1,
    description:
      'Sends the cloud through itself again. Each layer makes it longer and later, and rounds its start and end.',
  },
  drift: {
    id: 3,
    name: 'Drift',
    min: 0,
    max: 1,
    default: 0.3,
    taper: 'linear',
    unit: '',
    description:
      "Slowly moves the cloud's inner times so a held sound never sits on one colour. Too slow and small to hear as pitch.",
  },
  soften: {
    id: 4,
    name: 'Soften',
    min: 0,
    max: 1,
    default: 0.3,
    taper: 'linear',
    unit: '',
    description:
      'Turns down the first moment of each note before it is blurred, so the hit itself goes. It works on the dry sound too, as far as Mix is up.',
  },
  damp: {
    id: 5,
    name: 'Damp',
    min: 0,
    max: 1,
    default: 0.25,
    taper: 'linear',
    unit: '',
    description:
      'Takes the highs out of the cloud. At zero the cloud has every frequency the sound had.',
  },
  lowCut: {
    id: 6,
    name: 'Low Cut',
    min: 20,
    max: 1000,
    default: 20,
    taper: 'log',
    unit: 'Hz',
    description: 'Takes the lows out of the cloud, so bass notes stay clear of it.',
  },
  width: {
    id: 7,
    name: 'Width',
    min: 0,
    max: 1,
    default: 1,
    taper: 'linear',
    unit: '',
    description:
      'How different the cloud is on the two sides. At zero a mono sound stays in the middle. Low settings spread the highs first.',
  },
  mix: {
    id: 8,
    name: 'Mix',
    min: 0,
    max: 1,
    default: 1,
    taper: 'linear',
    unit: '',
    description: 'Balance between the dry sound and the cloud. Fully up there is only cloud.',
  },
} as const satisfies Record<string, ParamSpec>

export type FogParamName = keyof typeof FOG_PARAMS

export const FOG_METERS = {
  age: { id: 0, name: 'Since the last attack', unit: 's', display: true },
  hit: { id: 1, name: 'Attack level', unit: '', display: true },
  taken: { id: 2, name: 'Attack taken off', unit: '', display: true },
} as const satisfies Record<string, DeviceMeterSpec>

export const FOG_DEVICE = defineWasmDevice({
  id: 'fog',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/fog.wasm', import.meta.url),
  params: FOG_PARAMS,
  meters: FOG_METERS,
})

export const FOG_DESCRIPTOR = wasmDeviceDescriptor(FOG_DEVICE, {
  name: 'Fog',
  category: 'reverb',
  description:
    'Blurs every attack into a soft cloud with no tail at all: the diffusion of a reverb without the reverb.',
  presets: {
    'Soft cloud': {},
    'Thin veil': { size: 40, density: 0.6, soften: 0, damp: 0.1, mix: 0.35 },
    'Morning mist': { size: 90, soften: 0.2, damp: 0.15, mix: 0.6 },
    'Short blur': { size: 25, density: 1, soften: 0, damp: 0 },
    'Slow rise': { size: 400, layers: 2, soften: 0.8, damp: 0.3 },
    'No attack': { size: 250, soften: 1, drift: 0.2 },
    'Deep fog': { size: 600, density: 1, layers: 3, soften: 0.6, damp: 0.45 },
    'Rolling in': { size: 600, density: 0.4, layers: 3, drift: 0.7 },
    'Grain spray': { size: 500, density: 0, soften: 0, damp: 0.05 },
    'Dark bank': { size: 300, layers: 2, damp: 0.85 },
    'Bright haze': { size: 120, damp: 0, lowCut: 400, mix: 0.6 },
    'Upper glow': { size: 350, layers: 2, damp: 0.1, lowCut: 800, mix: 0.45 },
    'Behind glass': { size: 180, damp: 0.6, lowCut: 300, mix: 0.75 },
    'Wide drone': { size: 450, layers: 2, drift: 1, damp: 0.35, soften: 0.5 },
    'Mono smear': { size: 200, drift: 0, width: 0, soften: 0.1 },
    'Pad softener': { size: 60, density: 1, soften: 1, damp: 0.2, mix: 0.5 },
  },
})

export type Fog = WasmDevice<typeof FOG_PARAMS>

/** Blurs every attack into a soft cloud with no tail at all: the diffusion of a reverb without the reverb. */
export function createFog(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof FOG_PARAMS> = {},
): Promise<Fog> {
  return WasmDevice.create(context, FOG_DEVICE, options)
}
