// GENERATED by scripts/gen-devices.mjs from cpp/devices/glints/device.json. Do not edit.

import { type DeviceMeterSpec } from '../../core/devices/Device'
import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const GLINTS_PARAMS = {
  density: {
    id: 0,
    name: 'Density',
    min: 0.2,
    max: 40,
    default: 5,
    taper: 'log',
    unit: '/s',
    description:
      'How many sparks are thrown each second. Low leaves single glints far apart; high runs them together into a glitter.',
  },
  pitch: {
    id: 1,
    name: 'Pitch',
    min: 0,
    max: 4,
    default: 3,
    taper: 'linear',
    unit: '',
    choices: ['Octave', 'Octave and fifth', 'Two octaves', 'Mixed', 'Overtones'],
    description:
      'How far above the playing the sparks sound. Mixed draws from the first three. Overtones throws the natural harmonics up to the eighth, some of which lie between the keys.',
  },
  size: {
    id: 2,
    name: 'Size',
    min: 8,
    max: 300,
    default: 70,
    taper: 'log',
    unit: 'ms',
    description:
      'How long each spark lasts. Short ones are bright ticks. Long ones are small fast phrases, and they wait longer before they can sound.',
  },
  scatter: {
    id: 3,
    name: 'Scatter',
    min: 0,
    max: 2000,
    default: 350,
    taper: 'linear',
    unit: 'ms',
    description:
      'How long after the sound a spark may come. At zero the sparks keep as close to the playing as they can; higher lets them fall later and looser.',
  },
  follow: {
    id: 4,
    name: 'Follow',
    min: 0,
    max: 1,
    default: 0.6,
    taper: 'linear',
    unit: '',
    description:
      'How much the playing sets the pace. At zero sparks fall steadily by chance. At full they come only while you play, more of them the louder and brighter it is.',
  },
  sparkle: {
    id: 5,
    name: 'Sparkle',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
    description:
      'How bright the sparks are. Higher thins their body and sharpens their front edge, so soft blips turn into fine points of light.',
  },
  spread: {
    id: 6,
    name: 'Spread',
    min: 0,
    max: 1,
    default: 0.8,
    taper: 'linear',
    unit: '',
    description:
      'How far sparks are thrown to the left and right. Zero keeps every spark in the centre.',
  },
  trail: {
    id: 7,
    name: 'Trail',
    min: 0,
    max: 1,
    default: 0.3,
    taper: 'linear',
    unit: '',
    description:
      'An echo on the sparks only, crossing from side to side and darker each time. Higher gives each spark more repeats before it dies away.',
  },
  trailTime: {
    id: 8,
    name: 'Trail Time',
    min: 40,
    max: 800,
    default: 180,
    taper: 'log',
    unit: 'ms',
    description:
      'The gap between a spark and each of its echoes. Moving it bends the pitch of the echoes that are sounding.',
  },
  mix: {
    id: 9,
    name: 'Mix',
    min: 0,
    max: 1,
    default: 0.25,
    taper: 'linear',
    unit: '',
    description:
      'Balance between the dry signal and the sparks. Low settings leave the dry sound almost whole; fully up is the sparks alone.',
  },
} as const satisfies Record<string, ParamSpec>

export type GlintsParamName = keyof typeof GLINTS_PARAMS

export const GLINTS_METERS = {
  sparks: { id: 0, name: 'Sparks thrown', unit: '', display: true },
  pace: { id: 1, name: 'Sparks a second now', unit: '', display: true },
  spark1: { id: 2, name: 'Newest spark', unit: '', display: true },
  spark2: { id: 3, name: 'Spark before it', unit: '', display: true },
  spark3: { id: 4, name: 'Third newest spark', unit: '', display: true },
  spark4: { id: 5, name: 'Fourth newest spark', unit: '', display: true },
} as const satisfies Record<string, DeviceMeterSpec>

export const GLINTS_DEVICE = defineWasmDevice({
  id: 'glints',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/glints.wasm', import.meta.url),
  params: GLINTS_PARAMS,
  meters: GLINTS_METERS,
})

export const GLINTS_DESCRIPTOR = wasmDeviceDescriptor(GLINTS_DEVICE, {
  name: 'Glints',
  category: 'texture',
  description:
    'Throws off sparse bright sparks, short pieces of what is playing an octave or two up, each a little later and somewhere else between the speakers.',
  presets: {
    'First light': {},
    'Faint dust': { mix: 0.12, density: 7, size: 30, sparkle: 0.8, scatter: 600, follow: 0.5 },
    'Steady rain': { follow: 0, density: 8, scatter: 1200 },
    Glitter: { density: 25, size: 25, sparkle: 0.9, scatter: 500, follow: 0.7, spread: 1 },
    'Slow stars': {
      density: 0.8,
      size: 200,
      pitch: 2,
      trail: 0.75,
      trailTime: 420,
      scatter: 1500,
      mix: 0.3,
    },
    'Fifths above': { pitch: 1, density: 5, size: 120, mix: 0.28 },
    'Overtone spray': { pitch: 4, density: 18, size: 40, scatter: 800, mix: 0.28 },
    'Wide halo': {
      size: 300,
      density: 10,
      spread: 1,
      sparkle: 0.15,
      pitch: 0,
      scatter: 200,
      follow: 0.3,
      mix: 0.28,
    },
    'Only the sparks': { mix: 1, density: 14 },
    'Tight ticks': { size: 12, scatter: 0, follow: 1, density: 24, sparkle: 1, trail: 0 },
    'Long trails': { trail: 0.85, trailTime: 600, density: 2, mix: 0.28 },
    'Flutter echo': { trail: 0.8, trailTime: 60, density: 4, size: 20, mix: 0.28 },
    'Soft blips': { sparkle: 0, size: 150, density: 6, pitch: 0, mix: 0.3 },
    'Late answers': { scatter: 2000, follow: 0.2, density: 4, size: 100, trail: 0.4, mix: 0.28 },
    'Overtone chimes': {
      pitch: 4,
      size: 250,
      density: 3,
      trail: 0.6,
      trailTime: 300,
      sparkle: 0.3,
      mix: 0.3,
    },
    'Thrown by touch': { follow: 1, density: 30, size: 40, scatter: 100, mix: 0.28 },
  },
})

export type Glints = WasmDevice<typeof GLINTS_PARAMS>

/** Throws off sparse bright sparks, short pieces of what is playing an octave or two up, each a little later and somewhere else between the speakers. */
export function createGlints(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof GLINTS_PARAMS> = {},
): Promise<Glints> {
  return WasmDevice.create(context, GLINTS_DEVICE, options)
}
