// GENERATED by scripts/gen-devices.mjs from cpp/devices/glitch/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const GLITCH_PARAMS = {
  time: {
    id: 0,
    name: 'Time',
    min: 20,
    max: 2000,
    default: 250,
    taper: 'log',
    unit: 'ms',
    description:
      'Length of the slices the sound is cut into. Short slices stutter and buzz; long ones repeat or reverse whole phrases.',
  },
  chance: {
    id: 1,
    name: 'Chance',
    min: 0,
    max: 1,
    default: 0.25,
    taper: 'linear',
    unit: '',
    description:
      'How often a slice goes wrong. At zero nothing ever happens and the sound passes untouched; at full every slice is a glitch.',
  },
  repeat: {
    id: 2,
    name: 'Repeat',
    min: 0,
    max: 1,
    default: 0.7,
    taper: 'linear',
    unit: '',
    description:
      'How likely a glitch is to be a repeat, where the last slice plays again up to eight times. It is weighed against Skip, Reverse and Slow.',
  },
  skip: {
    id: 3,
    name: 'Skip',
    min: 0,
    max: 1,
    default: 0.4,
    taper: 'linear',
    unit: '',
    description:
      'How likely a glitch is to be a skip, where the sound jumps back and sticks on a tiny fragment like a scratched disc.',
  },
  reverse: {
    id: 4,
    name: 'Reverse',
    min: 0,
    max: 1,
    default: 0.3,
    taper: 'linear',
    unit: '',
    description: 'How likely a glitch is to play the last slice backwards.',
  },
  slow: {
    id: 5,
    name: 'Slow',
    min: 0,
    max: 1,
    default: 0.2,
    taper: 'linear',
    unit: '',
    description:
      'How likely a glitch is to slow the sound down: either it drops to half speed, or it winds down to a stop like a tape machine and spins back up.',
  },
  calm: {
    id: 6,
    name: 'Calm',
    min: 0,
    max: 1,
    default: 0.6,
    taper: 'linear',
    unit: '',
    description:
      'Softens every glitch. At zero they are hard digital cuts that click; turned up they fade in and out and get darker, until they are gentle stumbles and smears.',
  },
  decay: {
    id: 7,
    name: 'Decay',
    min: 0,
    max: 1,
    default: 0.3,
    taper: 'linear',
    unit: '',
    description:
      'Makes each repeat quieter and darker than the one before, so a stuck slice dies away instead of hammering.',
  },
  bounce: {
    id: 8,
    name: 'Bounce',
    min: 0,
    max: 1,
    default: 0,
    taper: 'linear',
    unit: '',
    description:
      'Makes each repeat shorter than the last, so the repeats speed up like a dropped ball coming to rest.',
  },
  octaves: {
    id: 9,
    name: 'Octaves',
    min: 0,
    max: 1,
    default: 0,
    taper: 'linear',
    unit: '',
    description:
      'Chance that a repeated or stuck fragment plays an octave up at double speed, or an octave down at half speed.',
  },
  spread: {
    id: 10,
    name: 'Spread',
    min: 0,
    max: 1,
    default: 0.3,
    taper: 'linear',
    unit: '',
    description:
      'Throws each glitch to a random place left or right of centre. Zero leaves them where the sound was.',
  },
  mix: {
    id: 11,
    name: 'Mix',
    min: 0,
    max: 1,
    default: 1,
    taper: 'linear',
    unit: '',
    description:
      'Balance between the untouched sound and the glitched one. Below full, what you play stays audible underneath each glitch.',
  },
} as const satisfies Record<string, ParamSpec>

export type GlitchParamName = keyof typeof GLITCH_PARAMS

export const GLITCH_DEVICE = defineWasmDevice({
  id: 'glitch',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/glitch.wasm', import.meta.url),
  params: GLITCH_PARAMS,
})

export const GLITCH_DESCRIPTOR = wasmDeviceDescriptor(GLITCH_DEVICE, {
  name: 'Glitch',
  category: 'texture',
  description:
    'A buffer that misbehaves by chance: slices of what you play are repeated, stuck like a scratched disc, reversed or slowed to a stop, as hard cuts or as soft stumbles.',
  presets: {
    'Gentle stumble': {
      time: 250,
      chance: 0.25,
      repeat: 0.7,
      skip: 0.4,
      reverse: 0.3,
      slow: 0.2,
      calm: 0.6,
      decay: 0.3,
      bounce: 0,
      octaves: 0,
      spread: 0.3,
      mix: 1,
    },
    'Skipping disc': {
      time: 90,
      chance: 0.25,
      repeat: 0,
      skip: 1,
      reverse: 0,
      slow: 0,
      calm: 0.25,
      decay: 0,
      bounce: 0,
      octaves: 0,
      spread: 0.15,
      mix: 1,
    },
    Stuck: {
      time: 180,
      chance: 0.55,
      repeat: 1,
      skip: 0.25,
      reverse: 0,
      slow: 0,
      calm: 0.35,
      decay: 0.2,
      bounce: 0,
      octaves: 0,
      spread: 0.2,
      mix: 1,
    },
    'Backwards glances': {
      time: 900,
      chance: 0.4,
      repeat: 0,
      skip: 0,
      reverse: 1,
      slow: 0,
      calm: 0.9,
      decay: 0,
      bounce: 0,
      octaves: 0,
      spread: 0.45,
      mix: 1,
    },
    'Winding down': {
      time: 700,
      chance: 0.35,
      repeat: 0,
      skip: 0,
      reverse: 0,
      slow: 1,
      calm: 0.7,
      decay: 0,
      bounce: 0,
      octaves: 0,
      spread: 0,
      mix: 1,
    },
    Bouncing: {
      time: 320,
      chance: 0.3,
      repeat: 1,
      skip: 0,
      reverse: 0,
      slow: 0,
      calm: 0.35,
      decay: 0.45,
      bounce: 0.7,
      octaves: 0,
      spread: 0.5,
      mix: 1,
    },
    Shards: {
      time: 45,
      chance: 0.5,
      repeat: 0.8,
      skip: 0.8,
      reverse: 0.4,
      slow: 0,
      calm: 0,
      decay: 0,
      bounce: 0,
      octaves: 0.6,
      spread: 0.8,
      mix: 1,
    },
    'Rare slips': {
      time: 400,
      chance: 0.07,
      repeat: 0.5,
      skip: 0.5,
      reverse: 0.5,
      slow: 0.5,
      calm: 1,
      decay: 0.4,
      bounce: 0,
      octaves: 0,
      spread: 0.3,
      mix: 1,
    },
    'Octave ghosts': {
      time: 500,
      chance: 0.3,
      repeat: 0.8,
      skip: 0.3,
      reverse: 0.4,
      slow: 0,
      calm: 0.85,
      decay: 0.5,
      bounce: 0,
      octaves: 0.8,
      spread: 0.6,
      mix: 0.6,
    },
  },
})

export type Glitch = WasmDevice<typeof GLITCH_PARAMS>

/** A buffer that misbehaves by chance: slices of what you play are repeated, stuck like a scratched disc, reversed or slowed to a stop, as hard cuts or as soft stumbles. */
export function createGlitch(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof GLITCH_PARAMS> = {},
): Promise<Glitch> {
  return WasmDevice.create(context, GLITCH_DEVICE, options)
}
