// GENERATED by scripts/gen-devices.mjs from cpp/devices/glitch-kit/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const GLITCH_KIT_PARAMS = {
  tune: {
    id: 0,
    name: 'Tune',
    min: -12,
    max: 12,
    default: 0,
    taper: 'linear',
    unit: 'st',
    description:
      'Tunes the whole kit up or down: every pip, pop, sweep, buzz and click band moves with it, and higher sounds get a little shorter. Heard from the next hit.',
  },
  length: {
    id: 1,
    name: 'Length',
    min: 0.25,
    max: 4,
    default: 1,
    taper: 'log',
    unit: '',
    description:
      'How long every sound lasts, from clipped ticks to longer bursts. The spacing of the repeats stays where Density puts it. Heard from the next hit.',
  },
  tone: {
    id: 2,
    name: 'Tone',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
    description:
      'A low-pass filter over the whole kit. Lower is duller and softer, like faults heard through a wall; all the way up is open and bright.',
  },
  edge: {
    id: 3,
    name: 'Edge',
    min: 0,
    max: 1,
    default: 0.35,
    taper: 'linear',
    unit: '',
    description:
      'How hard each sound starts and stops. Low rounds every start and stop; high switches them on and off, so a click at each end becomes part of the sound.',
  },
  density: {
    id: 4,
    name: 'Density',
    min: 0,
    max: 1,
    default: 0.4,
    taper: 'linear',
    unit: '',
    description:
      'How many events the double click, the crackle and the stutter make and how close together they lie. Heard from the next hit.',
  },
  crush: {
    id: 5,
    name: 'Crush',
    min: 0,
    max: 1,
    default: 0,
    taper: 'linear',
    unit: '',
    description:
      'Lowers the bit depth and the sample rate of the whole kit, from clean to coarse, gritty steps with ringing overtones. The level stays about the same.',
  },
  scatter: {
    id: 6,
    name: 'Scatter',
    min: 0,
    max: 1,
    default: 0.25,
    taper: 'linear',
    unit: '',
    description:
      'How much each hit differs from the last in pitch, length, level, place and, for the noisy sounds, the pattern itself. At zero every hit of a key is identical.',
  },
  spread: {
    id: 7,
    name: 'Spread',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
    description:
      'How far the hits are thrown to the left and right. At zero the kit is mono; the low pop stays in the centre at any setting. Heard from the next hit.',
  },
  volume: {
    id: 8,
    name: 'Volume',
    min: -24,
    max: 6,
    default: 0,
    taper: 'linear',
    unit: 'dB',
    description:
      'Output level of the kit. A soft clip after it rounds off the peaks when many hits pile up.',
  },
} as const satisfies Record<string, ParamSpec>

export type GlitchKitParamName = keyof typeof GLITCH_KIT_PARAMS

export const GLITCH_KIT_DEVICE = defineWasmDevice({
  id: 'glitch-kit',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/glitch-kit.wasm', import.meta.url),
  params: GLITCH_KIT_PARAMS,
})

export const GLITCH_KIT_DESCRIPTOR = wasmDeviceDescriptor(GLITCH_KIT_DEVICE, {
  name: 'Glitch Kit',
  category: 'instrument',
  description:
    'Percussion kit of twelve small digital faults: clicks, pops, cuts of noise, static, sine pips, chirps and stutters. Each key of the octave is one sound, and the octave it is played in tunes it.',
  presets: {
    'Clean clicks': {},
    'Soft faults': { length: 1.8, tone: 0.15, edge: 0, scatter: 0.35 },
    'Hard cuts': { length: 0.6, tone: 1, edge: 1, density: 0.6, scatter: 0.05, volume: 1.5 },
    'Old console': {
      tune: 7,
      length: 0.8,
      tone: 0.85,
      edge: 1,
      density: 0.55,
      crush: 0.6,
      scatter: 0,
      volume: 1,
    },
    'Surface noise': {
      length: 2.5,
      tone: 0.4,
      edge: 0.2,
      density: 0.95,
      scatter: 0.8,
      spread: 0.9,
      volume: -3,
    },
    'Small signals': { tune: 7, length: 0.4, tone: 0.7, density: 0.2, volume: 3 },
    'Broken stream': {
      length: 0.8,
      tone: 0.75,
      edge: 0.9,
      density: 0.85,
      crush: 0.6,
      scatter: 0.6,
      spread: 1,
    },
    'Dull ticks': { tune: -5, length: 0.6, tone: 0.05, edge: 0.1, volume: 3 },
    Scattered: { length: 1.3, density: 0.6, scatter: 1, spread: 1, volume: -1 },
    'Low bitrate kit': { tune: -3, length: 1.2, tone: 0.45, edge: 0.6, crush: 1, volume: -1 },
    'Octave down': { tune: -12, length: 2, tone: 0.6, edge: 0.3, volume: -3 },
    'High pips': { tune: 12, tone: 1, edge: 0.2, density: 0.3, volume: 1 },
    'Long bursts': { length: 4, tone: 0.65, edge: 0.5, density: 0.7, volume: -5 },
    'Tight centre': { length: 0.3, tone: 0.8, edge: 0.7, scatter: 0, spread: 0, volume: 3 },
    'Coarse and low': { tune: -12, tone: 0.7, edge: 0.8, crush: 0.8, volume: -1 },
    'Bright dust': {
      tune: 9,
      length: 2,
      tone: 0.9,
      density: 1,
      scatter: 0.7,
      spread: 0.8,
      volume: -2,
    },
  },
})

export type GlitchKit = WasmDevice<typeof GLITCH_KIT_PARAMS>

/** Percussion kit of twelve small digital faults: clicks, pops, cuts of noise, static, sine pips, chirps and stutters. Each key of the octave is one sound, and the octave it is played in tunes it. Play it through `NoteDevice`: `noteOn(id, frequency, gain)` / `noteOff(id)`. */
export function createGlitchKit(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof GLITCH_KIT_PARAMS> = {},
): Promise<GlitchKit> {
  return WasmDevice.create(context, GLITCH_KIT_DEVICE, options)
}
