// GENERATED by scripts/gen-devices.mjs from cpp/devices/grain-delay/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const GRAIN_DELAY_PARAMS = {
  time: { id: 0, name: 'Time', min: 10, max: 2000, default: 350, taper: 'log', unit: 'ms' },
  spray: { id: 1, name: 'Spray', min: 0, max: 1, default: 0.15, taper: 'linear', unit: '' },
  pitch: { id: 2, name: 'Pitch', min: -24, max: 24, default: 12, taper: 'linear', unit: 'st' },
  pitchSpray: {
    id: 3,
    name: 'Pitch Spray',
    min: 0,
    max: 1,
    default: 0.08,
    taper: 'linear',
    unit: '',
  },
  size: { id: 4, name: 'Size', min: 10, max: 500, default: 120, taper: 'log', unit: 'ms' },
  density: { id: 5, name: 'Density', min: 1, max: 8, default: 4, taper: 'log', unit: '' },
  reverse: { id: 6, name: 'Reverse', min: 0, max: 1, default: 0, taper: 'linear', unit: '' },
  feedback: { id: 7, name: 'Feedback', min: 0, max: 1, default: 0.45, taper: 'linear', unit: '' },
  tone: { id: 8, name: 'Tone', min: 500, max: 16000, default: 6000, taper: 'log', unit: 'Hz' },
  spread: { id: 9, name: 'Spread', min: 0, max: 1, default: 0.6, taper: 'linear', unit: '' },
  mix: { id: 10, name: 'Mix', min: 0, max: 1, default: 0.35, taper: 'linear', unit: '' },
} as const satisfies Record<string, ParamSpec>

export type GrainDelayParamName = keyof typeof GRAIN_DELAY_PARAMS

export const GRAIN_DELAY_DEVICE = defineWasmDevice({
  id: 'grain-delay',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/grain-delay.wasm', import.meta.url),
  params: GRAIN_DELAY_PARAMS,
})

export const GRAIN_DELAY_DESCRIPTOR = wasmDeviceDescriptor(GRAIN_DELAY_DEVICE, {
  name: 'Grain Delay',
  category: 'delay',
  description:
    'A delay whose repeats are rebuilt from grains: pitch-shifted, scattered in time and space, optionally reversed; with feedback each repeat climbs or falls again.',
  presets: {
    Crystals: {
      time: 350,
      spray: 0.15,
      pitch: 12,
      pitchSpray: 0.08,
      size: 120,
      density: 4,
      reverse: 0,
      feedback: 0.45,
      tone: 6000,
      spread: 0.6,
      mix: 0.35,
    },
    'Falling embers': {
      time: 520,
      spray: 0.25,
      pitch: -12,
      pitchSpray: 0.06,
      size: 220,
      density: 4,
      reverse: 0.3,
      feedback: 0.55,
      tone: 3600,
      spread: 0.7,
      mix: 0.4,
    },
    'Rising fifths': {
      time: 640,
      spray: 0.1,
      pitch: 7,
      pitchSpray: 0.05,
      size: 160,
      density: 5,
      reverse: 0,
      feedback: 0.6,
      tone: 5000,
      spread: 0.5,
      mix: 0.35,
    },
    'Grain cloud': {
      time: 240,
      spray: 0.65,
      pitch: 0,
      pitchSpray: 0.12,
      size: 80,
      density: 6,
      reverse: 0.5,
      feedback: 0.5,
      tone: 7000,
      spread: 1,
      mix: 0.5,
    },
    'Backwards shards': {
      time: 420,
      spray: 0.2,
      pitch: 0,
      pitchSpray: 0.03,
      size: 260,
      density: 3,
      reverse: 1,
      feedback: 0.35,
      tone: 8000,
      spread: 0.8,
      mix: 0.4,
    },
    'Frozen haze': {
      time: 900,
      spray: 0.7,
      pitch: 0,
      pitchSpray: 0.1,
      size: 380,
      density: 8,
      reverse: 0.5,
      feedback: 0.92,
      tone: 3000,
      spread: 1,
      mix: 0.5,
    },
    'Plain repeat': {
      time: 380,
      spray: 0,
      pitch: 0,
      pitchSpray: 0,
      size: 100,
      density: 2,
      reverse: 0,
      feedback: 0.4,
      tone: 9000,
      spread: 0,
      mix: 0.3,
    },
  },
})

export type GrainDelay = WasmDevice<typeof GRAIN_DELAY_PARAMS>

/** A delay whose repeats are rebuilt from grains: pitch-shifted, scattered in time and space, optionally reversed; with feedback each repeat climbs or falls again. */
export function createGrainDelay(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof GRAIN_DELAY_PARAMS> = {},
): Promise<GrainDelay> {
  return WasmDevice.create(context, GRAIN_DELAY_DEVICE, options)
}
