// GENERATED by scripts/gen-devices.mjs from cpp/devices/grain-synth/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const GRAIN_SYNTH_PARAMS = {
  position: { id: 0, name: 'Position', min: 0, max: 1, default: 0.2, taper: 'linear', unit: '' },
  scan: { id: 1, name: 'Scan', min: -2, max: 2, default: 0.1, taper: 'linear', unit: '' },
  size: { id: 2, name: 'Size', min: 10, max: 2000, default: 280, taper: 'log', unit: 'ms' },
  density: { id: 3, name: 'Density', min: 1, max: 16, default: 6, taper: 'linear', unit: '' },
  spray: { id: 4, name: 'Spray', min: 0, max: 1, default: 0.2, taper: 'linear', unit: '' },
  detune: { id: 5, name: 'Detune', min: 0, max: 100, default: 6, taper: 'linear', unit: 'ct' },
  octaves: { id: 6, name: 'Octaves', min: 0, max: 1, default: 0.08, taper: 'linear', unit: '' },
  shape: { id: 7, name: 'Shape', min: 0, max: 1, default: 0, taper: 'linear', unit: '' },
  reverse: { id: 8, name: 'Reverse', min: 0, max: 1, default: 0.15, taper: 'linear', unit: '' },
  attack: { id: 9, name: 'Attack', min: 0.005, max: 8, default: 0.5, taper: 'log', unit: 's' },
  release: { id: 10, name: 'Release', min: 0.05, max: 12, default: 2, taper: 'log', unit: 's' },
  spread: { id: 11, name: 'Spread', min: 0, max: 1, default: 0.7, taper: 'linear', unit: '' },
  tone: { id: 12, name: 'Tone', min: 200, max: 18000, default: 9000, taper: 'log', unit: 'Hz' },
  volume: { id: 13, name: 'Volume', min: -48, max: 6, default: -9, taper: 'linear', unit: 'dB' },
} as const satisfies Record<string, ParamSpec>

export type GrainSynthParamName = keyof typeof GRAIN_SYNTH_PARAMS

export const GRAIN_SYNTH_DEVICE = defineWasmDevice({
  id: 'grain-synth',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/grain-synth.wasm', import.meta.url),
  params: GRAIN_SYNTH_PARAMS,
})

export const GRAIN_SYNTH_DESCRIPTOR = wasmDeviceDescriptor(GRAIN_SYNTH_DEVICE, {
  name: 'Grain',
  category: 'instrument',
  description:
    'Granular synthesizer: each key plays a cloud of overlapping grains from the loaded sound, with pitch and time independent, from a frozen moment to a slow stretch.',
  presets: {
    Cloud: {
      position: 0.2,
      scan: 0.1,
      size: 280,
      density: 6,
      spray: 0.2,
      detune: 6,
      octaves: 0.08,
      shape: 0,
      reverse: 0.15,
      attack: 0.5,
      release: 2,
      spread: 0.7,
      tone: 9000,
    },
    'Frozen moment': {
      position: 0.45,
      scan: 0,
      size: 420,
      density: 8,
      spray: 0.06,
      detune: 3,
      octaves: 0,
      reverse: 0,
      attack: 1.2,
      release: 3.5,
      spread: 0.5,
      tone: 7000,
    },
    'Slow stretch': {
      position: 0,
      scan: 0.12,
      size: 140,
      density: 4,
      spray: 0.03,
      detune: 0,
      octaves: 0,
      reverse: 0,
      attack: 0.05,
      release: 0.8,
      spread: 0.2,
      tone: 14000,
    },
    Shimmer: {
      position: 0.5,
      scan: 0.05,
      size: 360,
      density: 10,
      spray: 0.3,
      detune: 9,
      octaves: 0.55,
      reverse: 0.3,
      attack: 1.5,
      release: 5,
      spread: 1,
      tone: 12000,
    },
    'Backwards wash': {
      position: 0.6,
      scan: -0.3,
      size: 900,
      density: 8,
      spray: 0.35,
      detune: 5,
      octaves: 0.1,
      reverse: 1,
      attack: 2.5,
      release: 6,
      spread: 0.9,
      tone: 6000,
    },
    Stutter: {
      position: 0.3,
      scan: 0.5,
      size: 45,
      density: 1.5,
      spray: 0,
      detune: 0,
      octaves: 0,
      shape: 0.8,
      reverse: 0,
      attack: 0.005,
      release: 0.2,
      spread: 0.4,
      tone: 16000,
    },
  },
})

export type GrainSynth = WasmDevice<typeof GRAIN_SYNTH_PARAMS>

/** Granular synthesizer: each key plays a cloud of overlapping grains from the loaded sound, with pitch and time independent, from a frozen moment to a slow stretch. Play it through `NoteDevice`: `noteOn(id, frequency, gain)` / `noteOff(id)`. */
export function createGrainSynth(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof GRAIN_SYNTH_PARAMS> = {},
): Promise<GrainSynth> {
  return WasmDevice.create(context, GRAIN_SYNTH_DEVICE, options)
}
