// GENERATED by scripts/gen-devices.mjs from cpp/devices/guitar/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const GUITAR_PARAMS = {
  pickup: {
    id: 0,
    name: 'Pickup',
    min: 0,
    max: 1,
    default: 0.85,
    taper: 'linear',
    unit: '',
    description:
      'Where the pickup sits along the string, from the bridge to the neck. Near the bridge is thin and bright; near the neck is round and flutey.',
  },
  position: {
    id: 1,
    name: 'Position',
    min: 0.05,
    max: 0.35,
    default: 0.14,
    taper: 'linear',
    unit: '',
    description:
      'Where the string is picked. Close to the bridge is wiry and nasal; further over the neck is soft and hollow.',
  },
  hardness: {
    id: 2,
    name: 'Hardness',
    min: 0,
    max: 1,
    default: 0.55,
    taper: 'linear',
    unit: '',
    description:
      'How hard the pick is, from the flesh of a thumb to a stiff plectrum. Harder is brighter with more click at the start of each note.',
  },
  sustain: {
    id: 3,
    name: 'Sustain',
    min: 1,
    max: 30,
    default: 9,
    taper: 'log',
    unit: 's',
    description:
      'How long a held note rings before it has died away. High notes ring for less time than low ones, as they do on a real neck.',
  },
  tone: {
    id: 4,
    name: 'Tone',
    min: 1500,
    max: 5500,
    default: 3600,
    taper: 'log',
    unit: 'Hz',
    description:
      "The guitar's tone control: where the pickup's resonant peak sits. Lower is dull and woolly; higher is glassy and bright.",
  },
  swell: {
    id: 5,
    name: 'Swell',
    min: 0,
    max: 3,
    default: 0,
    taper: 'linear',
    unit: 's',
    description:
      'Fades each note in, as a volume pedal does, so the pick is hidden and the string seems to bloom. At zero notes start at once.',
  },
  strum: {
    id: 6,
    name: 'Strum',
    min: 0,
    max: 80,
    default: 18,
    taper: 'linear',
    unit: 'ms',
    description:
      'Spreads the notes of a chord in time from the lowest string to the highest. At zero they sound together; longer is a slow drag across the strings.',
  },
  shimmer: {
    id: 7,
    name: 'Shimmer',
    min: 0,
    max: 1.5,
    default: 0.3,
    taper: 'linear',
    unit: 'Hz',
    description:
      'How fast each string beats against itself as it rings. Low is a slow, living sustain; high gives the chime of a twelve string.',
  },
  warmth: {
    id: 8,
    name: 'Warmth',
    min: 0,
    max: 1,
    default: 0.3,
    taper: 'linear',
    unit: '',
    description:
      'How hard the amplifier is pushed. Low is clean; higher thickens and compresses the sound until hard notes just begin to break up.',
  },
  volume: {
    id: 9,
    name: 'Volume',
    min: -48,
    max: 6,
    default: -6,
    taper: 'linear',
    unit: 'dB',
    description:
      'Output level of the instrument. A soft clip after it rounds off the peaks when many notes stack up.',
  },
} as const satisfies Record<string, ParamSpec>

export type GuitarParamName = keyof typeof GUITAR_PARAMS

export const GUITAR_DEVICE = defineWasmDevice({
  id: 'guitar',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/guitar.wasm', import.meta.url),
  params: GUITAR_PARAMS,
})

export const GUITAR_DESCRIPTOR = wasmDeviceDescriptor(GUITAR_DEVICE, {
  name: 'Guitar',
  category: 'instrument',
  description:
    'Clean electric guitar: plucked steel strings heard through a pickup whose colour changes with every fret, a clean amplifier and a speaker, with strummed chords and swells.',
  presets: {
    'Glass neck': {
      pickup: 0.85,
      position: 0.14,
      hardness: 0.55,
      sustain: 9,
      tone: 3600,
      swell: 0,
      strum: 18,
      shimmer: 0.3,
      warmth: 0.3,
    },
    'Volume swell': {
      pickup: 0.5,
      hardness: 0.4,
      sustain: 18,
      tone: 3000,
      swell: 1.2,
      strum: 0,
      shimmer: 0.4,
      warmth: 0.5,
      volume: 6,
    },
    'Slow strum': {
      pickup: 0.95,
      position: 0.18,
      hardness: 0.3,
      sustain: 14,
      tone: 2800,
      strum: 60,
      warmth: 0.55,
    },
    'Dark baritone': {
      pickup: 0.15,
      position: 0.08,
      hardness: 0.85,
      sustain: 12,
      tone: 2000,
      strum: 30,
      shimmer: 0.2,
      warmth: 0.45,
    },
    'Muted pattern': {
      pickup: 0.1,
      position: 0.07,
      hardness: 0.5,
      sustain: 1.2,
      tone: 3800,
      strum: 0,
      shimmer: 0.1,
      warmth: 0.8,
      volume: -2,
    },
    'Twelve string': {
      pickup: 0.6,
      position: 0.11,
      hardness: 0.65,
      sustain: 12,
      tone: 4800,
      strum: 32,
      shimmer: 1.3,
      warmth: 0.2,
    },
  },
})

export type Guitar = WasmDevice<typeof GUITAR_PARAMS>

/** Clean electric guitar: plucked steel strings heard through a pickup whose colour changes with every fret, a clean amplifier and a speaker, with strummed chords and swells. Play it through `NoteDevice`: `noteOn(id, frequency, gain)` / `noteOff(id)`. */
export function createGuitar(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof GUITAR_PARAMS> = {},
): Promise<Guitar> {
  return WasmDevice.create(context, GUITAR_DEVICE, options)
}
