// GENERATED by scripts/gen-devices.mjs from cpp/devices/half-speed/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const HALF_SPEED_PARAMS = {
  power: {
    id: 0,
    name: 'Power',
    min: 0,
    max: 1,
    default: 0,
    taper: 'linear',
    unit: '',
    choices: ['On', 'Off'],
    description:
      'Off passes the dry signal. Switching it fades over a moment, and switching On starts a new cycle from the note being played.',
  },
  length: {
    id: 1,
    name: 'Length',
    min: 50,
    max: 4000,
    default: 1000,
    taper: 'log',
    unit: 'ms',
    description:
      'How long each cycle lasts before the slowed sound jumps forward to catch up with your playing. Short cycles stutter; long ones drag whole phrases out behind you.',
  },
  speed: {
    id: 2,
    name: 'Speed',
    min: 0,
    max: 3,
    default: 2,
    taper: 'linear',
    unit: '',
    choices: ['Three quarters', 'Two thirds', 'Half', 'Quarter'],
    description:
      'How slow the playback runs, and so how far the pitch drops: a fourth, a fifth, one octave or two. A change bends the pitch like a tape machine changing speed.',
  },
  fade: {
    id: 3,
    name: 'Fade',
    min: 0.01,
    max: 0.5,
    default: 0.15,
    taper: 'linear',
    unit: '',
    description:
      'How much of each cycle is spent fading from the old cycle into the new one. Low is a tight cut, high lets the end of one cycle wash over the start of the next.',
  },
  smooth: {
    id: 4,
    name: 'Smooth',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
    description:
      'At zero each cycle is heard to start, a rhythm of slowed chunks. Turned up, a second playback half a cycle behind fills the jumps until the sound runs on unbroken.',
  },
  jitter: {
    id: 5,
    name: 'Jitter',
    min: 0,
    max: 1,
    default: 0.1,
    taper: 'linear',
    unit: '',
    description:
      'Makes every cycle a little longer or shorter than the last, so the jumps stop ticking like a machine.',
  },
  lowCut: {
    id: 6,
    name: 'Low Cut',
    min: 20,
    max: 2000,
    default: 20,
    taper: 'log',
    unit: 'Hz',
    description:
      'Removes lows from the slowed sound, which keeps a thick source from turning to mud an octave down.',
  },
  highCut: {
    id: 7,
    name: 'High Cut',
    min: 500,
    max: 20000,
    default: 20000,
    taper: 'log',
    unit: 'Hz',
    description:
      'Removes highs from the slowed sound, for a darker bed that sits under the dry signal.',
  },
  spread: {
    id: 8,
    name: 'Spread',
    min: 0,
    max: 1,
    default: 0.8,
    taper: 'linear',
    unit: '',
    description:
      "Brings a second playback into the right side whose cycles run later than the left's. The further it is turned, the wider the slowed sound. The bass stays in the middle.",
  },
  mix: {
    id: 9,
    name: 'Mix',
    min: 0,
    max: 1,
    default: 1,
    taper: 'linear',
    unit: '',
    description: 'Balance between the dry signal and the slowed sound.',
  },
} as const satisfies Record<string, ParamSpec>

export type HalfSpeedParamName = keyof typeof HALF_SPEED_PARAMS

export const HALF_SPEED_DEVICE = defineWasmDevice({
  id: 'half-speed',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/half-speed.wasm', import.meta.url),
  params: HALF_SPEED_PARAMS,
})

export const HALF_SPEED_DESCRIPTOR = wasmDeviceDescriptor(HALF_SPEED_DEVICE, {
  name: 'Half Speed',
  category: 'pitch',
  description:
    'Plays what you are playing at half speed as you play it: an octave down and twice as slow, in repeating cycles that can chop like a rhythm or run together into one slow, deep bed.',
  presets: {
    'Half speed': {
      length: 1000,
      speed: 2,
      fade: 0.15,
      smooth: 0.5,
      jitter: 0.1,
      lowCut: 20,
      highCut: 20000,
      spread: 0.8,
      mix: 1,
    },
    'Slow chops': { length: 500, fade: 0.06, smooth: 0, jitter: 0, spread: 0 },
    'Continuous octave': { length: 2400, smooth: 1, fade: 0.3, spread: 0.8 },
    'Fifth down bed': { speed: 1, length: 1600, smooth: 0.8, highCut: 6000, spread: 0.7, mix: 0.5 },
    'Two octaves under': {
      speed: 3,
      length: 1500,
      smooth: 1,
      lowCut: 30,
      highCut: 3000,
      spread: 0.4,
      mix: 0.4,
    },
    'Long drag': { length: 4000, fade: 0.3, smooth: 0.6, jitter: 0.2, spread: 1 },
    'Blurred half': { length: 450, fade: 0.5, smooth: 0.4, jitter: 1, highCut: 5000, spread: 1 },
    'Under the mix': { length: 1200, smooth: 1, lowCut: 60, highCut: 2500, spread: 0.6, mix: 0.3 },
    'Short stutter': { length: 110, fade: 0.08, smooth: 0, jitter: 0.3, spread: 0.6 },
    'Fourth down drift': {
      speed: 0,
      length: 3000,
      fade: 0.4,
      smooth: 1,
      jitter: 0.5,
      spread: 1,
      mix: 0.6,
    },
  },
})

export type HalfSpeed = WasmDevice<typeof HALF_SPEED_PARAMS>

/** Plays what you are playing at half speed as you play it: an octave down and twice as slow, in repeating cycles that can chop like a rhythm or run together into one slow, deep bed. */
export function createHalfSpeed(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof HALF_SPEED_PARAMS> = {},
): Promise<HalfSpeed> {
  return WasmDevice.create(context, HALF_SPEED_DEVICE, options)
}
