// GENERATED by scripts/gen-devices.mjs from cpp/devices/half-speed/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const HALF_SPEED_PARAMS = {
  power: {
    id: 0,
    name: 'Power',
    min: 0,
    max: 1,
    default: 0,
    taper: 'linear',
    unit: '',
    choices: ['On', 'Off'],
    description:
      'Off passes the dry signal. Switching it fades over a moment, and switching On starts a new cycle from the note being played.',
  },
  length: {
    id: 1,
    name: 'Length',
    min: 50,
    max: 4000,
    default: 1000,
    taper: 'log',
    unit: 'ms',
    description:
      'How long each cycle lasts before the slowed sound jumps forward to catch up with your playing. Short cycles stutter; long ones drag whole phrases out behind you.',
  },
  speed: {
    id: 2,
    name: 'Speed',
    min: 0,
    max: 3,
    default: 2,
    taper: 'linear',
    unit: '',
    choices: ['Three quarters', 'Two thirds', 'Half', 'Quarter'],
    description:
      'How slow the playback runs, and so how far the pitch drops: a fourth, a fifth, one octave or two octaves down. A change bends the pitch like a tape machine changing speed.',
  },
  fade: {
    id: 3,
    name: 'Fade',
    min: 0.01,
    max: 0.5,
    default: 0.15,
    taper: 'linear',
    unit: '',
    description:
      'How much of each cycle is spent fading from the old cycle into the new one. Low is a tight cut, high lets the end of one cycle wash over the start of the next.',
  },
  smooth: {
    id: 4,
    name: 'Smooth',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
    description:
      'At zero you hear each cycle start, a rhythm of slowed chunks. Turning it up brings in a second playback half a cycle behind, until at full the jumps disappear into one continuous slowed sound.',
  },
  jitter: {
    id: 5,
    name: 'Jitter',
    min: 0,
    max: 1,
    default: 0.1,
    taper: 'linear',
    unit: '',
    description:
      'Makes every cycle a little longer or shorter than the last, so the jumps stop ticking like a machine.',
  },
  lowCut: {
    id: 6,
    name: 'Low Cut',
    min: 20,
    max: 2000,
    default: 20,
    taper: 'log',
    unit: 'Hz',
    description:
      'Removes lows from the slowed sound, which keeps a thick source from turning to mud an octave down.',
  },
  highCut: {
    id: 7,
    name: 'High Cut',
    min: 500,
    max: 20000,
    default: 20000,
    taper: 'log',
    unit: 'Hz',
    description:
      'Removes highs from the slowed sound, for a darker bed that sits under the dry signal.',
  },
  spread: {
    id: 8,
    name: 'Spread',
    min: 0,
    max: 1,
    default: 0.3,
    taper: 'linear',
    unit: '',
    description:
      'Lets the right side run its cycles later than the left, so the jumps land at different moments and the slowed sound widens. The bass stays together.',
  },
  mix: {
    id: 9,
    name: 'Mix',
    min: 0,
    max: 1,
    default: 1,
    taper: 'linear',
    unit: '',
    description: 'Balance between the dry signal and the slowed sound.',
  },
} as const satisfies Record<string, ParamSpec>

export type HalfSpeedParamName = keyof typeof HALF_SPEED_PARAMS

export const HALF_SPEED_DEVICE = defineWasmDevice({
  id: 'half-speed',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/half-speed.wasm', import.meta.url),
  params: HALF_SPEED_PARAMS,
})

export const HALF_SPEED_DESCRIPTOR = wasmDeviceDescriptor(HALF_SPEED_DEVICE, {
  name: 'Half Speed',
  category: 'pitch',
  description:
    'Plays what you are playing at half speed as you play it: an octave down and twice as slow, in repeating cycles that can chop like a rhythm or run together into one slow, deep bed.',
  presets: {
    'Half speed': {},
    'Slow chops': { length: 500, smooth: 0, fade: 0.06, jitter: 0 },
    'Continuous octave': { length: 2400, smooth: 1 },
    'Fifth down bed': { speed: 1, length: 1600, smooth: 0.8, mix: 0.5 },
  },
})

export type HalfSpeed = WasmDevice<typeof HALF_SPEED_PARAMS>

/** Plays what you are playing at half speed as you play it: an octave down and twice as slow, in repeating cycles that can chop like a rhythm or run together into one slow, deep bed. */
export function createHalfSpeed(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof HALF_SPEED_PARAMS> = {},
): Promise<HalfSpeed> {
  return WasmDevice.create(context, HALF_SPEED_DEVICE, options)
}
