// GENERATED by scripts/gen-devices.mjs from cpp/devices/harp/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const HARP_PARAMS = {
  strings: {
    id: 0,
    name: 'Strings',
    min: 0,
    max: 2,
    default: 0,
    taper: 'linear',
    unit: '',
    choices: ['Harp', 'Koto', 'Guzheng'],
    description:
      'The kind of string. Harp is soft gut under a finger; Koto is a dry string under a hard pick; Guzheng is brighter steel that rings longer. Applies from the next note.',
  },
  pluck: {
    id: 1,
    name: 'Pluck',
    min: 0.04,
    max: 0.5,
    default: 0.36,
    taper: 'linear',
    unit: '',
    description:
      'Where along the string it is plucked. Low is near the end: thin, nasal and bright. High is the middle: round and hollow. Applies from the next note.',
  },
  touch: {
    id: 2,
    name: 'Touch',
    min: 0,
    max: 1,
    default: 0.4,
    taper: 'linear',
    unit: '',
    description:
      'How hard the finger or pick is. Low is a soft pad with a dark, rounded start; high is a hard edge with a bright attack and a click. Applies from the next note.',
  },
  decay: {
    id: 3,
    name: 'Decay',
    min: 0.25,
    max: 4,
    default: 1,
    taper: 'log',
    unit: '',
    description:
      'How long the strings ring. Low strings always ring much longer than high ones. Applies from the next note.',
  },
  damp: {
    id: 4,
    name: 'Damp',
    min: 0,
    max: 1,
    default: 0,
    taper: 'linear',
    unit: '',
    description:
      'How much letting go of a key stops its string. At zero nothing stops it and notes ring into each other; at full a hand mutes it at once.',
  },
  halo: {
    id: 5,
    name: 'Halo',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
    description:
      'How much the strings that are already ringing pick up each new note and ring along with it. It needs other notes still sounding to be heard.',
  },
  sweep: {
    id: 6,
    name: 'Sweep',
    min: 0,
    max: 1.5,
    default: 0,
    taper: 'linear',
    unit: 's',
    description:
      'Rolls notes that are played together into a glissando from the lowest to the highest, spread over this time. At zero a chord is plucked together.',
  },
  bend: {
    id: 7,
    name: 'Bend',
    min: 0,
    max: 200,
    default: 0,
    taper: 'linear',
    unit: 'ct',
    description:
      'Presses each note sharp a moment after it is plucked, the way a koto player leans on the string behind the bridge. It only ever rises. Applies from the next note.',
  },
  body: {
    id: 8,
    name: 'Body',
    min: 0,
    max: 1,
    default: 0.6,
    taper: 'linear',
    unit: '',
    description:
      'How much of the wooden soundboard is heard. Low is the bare strings; high is fuller and woodier, more hollow on Koto and Guzheng.',
  },
  volume: {
    id: 9,
    name: 'Volume',
    min: -48,
    max: 6,
    default: -6,
    taper: 'linear',
    unit: 'dB',
    description:
      'Output level of the instrument. A soft clip after it rounds off the peaks when many strings ring at once.',
  },
} as const satisfies Record<string, ParamSpec>

export type HarpParamName = keyof typeof HARP_PARAMS

export const HARP_DEVICE = defineWasmDevice({
  id: 'harp',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/harp.wasm', import.meta.url),
  params: HARP_PARAMS,
})

export const HARP_DESCRIPTOR = wasmDeviceDescriptor(HARP_DEVICE, {
  name: 'Harp',
  category: 'instrument',
  description:
    'A concert harp with koto and guzheng strings: every note is its own plucked string that rings on after the key is let go, over a soundboard, with the other strings ringing in sympathy.',
  presets: {
    'Concert harp': {
      strings: 0,
      pluck: 0.36,
      touch: 0.4,
      decay: 1,
      damp: 0,
      halo: 0.5,
      sweep: 0,
      bend: 0,
      body: 0.6,
    },
    Glissando: { pluck: 0.3, touch: 0.6, halo: 0.8, sweep: 0.8 },
    'Near the soundboard': { pluck: 0.08, touch: 0.55, decay: 0.5, halo: 0.3, body: 0.4 },
    'Long glass ring': { pluck: 0.45, touch: 0.15, decay: 3, halo: 1, body: 0.35 },
    'Muted harp': { pluck: 0.25, touch: 0.3, damp: 0.8, halo: 0.2, body: 0.8 },
    Koto: { strings: 1, pluck: 0.08, touch: 0.75, halo: 0.4, body: 0.7 },
    'Rising koto': {
      strings: 1,
      pluck: 0.1,
      touch: 0.6,
      decay: 1.3,
      halo: 0.5,
      bend: 100,
      body: 0.7,
    },
    'Guzheng cascade': { strings: 2, pluck: 0.1, touch: 0.7, halo: 0.7, sweep: 1, body: 0.55 },
    'Soft silk': { strings: 1, pluck: 0.2, touch: 0.1, decay: 1.6, halo: 0.7, bend: 50, body: 0.8 },
  },
})

export type Harp = WasmDevice<typeof HARP_PARAMS>

/** A concert harp with koto and guzheng strings: every note is its own plucked string that rings on after the key is let go, over a soundboard, with the other strings ringing in sympathy. Play it through `NoteDevice`: `noteOn(id, frequency, gain)` / `noteOff(id)`. */
export function createHarp(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof HARP_PARAMS> = {},
): Promise<Harp> {
  return WasmDevice.create(context, HARP_DEVICE, options)
}
