// GENERATED by scripts/gen-devices.mjs from cpp/devices/ladder-bass/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const LADDER_BASS_PARAMS = {
  wave: {
    id: 0,
    name: 'Wave',
    min: 0,
    max: 1,
    default: 0,
    taper: 'linear',
    unit: '',
    description: 'Shape of the two oscillators, from a bright buzzing sawtooth to a hollow square.',
  },
  beat: {
    id: 1,
    name: 'Beat',
    min: 0,
    max: 25,
    default: 6,
    taper: 'linear',
    unit: 'ct',
    description:
      'How far the two oscillators are tuned apart. A little makes the note swell and fade slowly; more is a thick chorus.',
  },
  sub: {
    id: 2,
    name: 'Sub',
    min: 0,
    max: 1,
    default: 0.3,
    taper: 'linear',
    unit: '',
    description:
      'Level of a pure tone one octave below the note, for weight under the oscillators.',
  },
  cutoff: {
    id: 3,
    name: 'Cutoff',
    min: 30,
    max: 12000,
    default: 500,
    taper: 'log',
    unit: 'Hz',
    description:
      'Where the filter starts removing highs. Lower is darker and rounder. Higher notes open it a little so the top of the keyboard keeps its tone.',
  },
  emphasis: {
    id: 4,
    name: 'Emphasis',
    min: 0,
    max: 1,
    default: 0.3,
    taper: 'linear',
    unit: '',
    description:
      'Resonance at the cutoff: a nasal, whistling peak. As on the original filters, more of it makes the bass thinner and quieter.',
  },
  contour: {
    id: 5,
    name: 'Contour',
    min: 0,
    max: 1,
    default: 0.6,
    taper: 'linear',
    unit: '',
    description:
      'How far each note opens the filter above Cutoff before it closes again. With Decay at the top the filter stays open while a key is held.',
  },
  decay: {
    id: 6,
    name: 'Decay',
    min: 0.03,
    max: 10,
    default: 0.6,
    taper: 'log',
    unit: 's',
    description:
      'How quickly each note closes and fades, from a short blip to a long fall. At the very top the note holds for as long as the key is down.',
  },
  drive: {
    id: 7,
    name: 'Drive',
    min: 0,
    max: 1,
    default: 0.3,
    taper: 'linear',
    unit: '',
    description:
      'Pushes the oscillators harder into the filter, which rounds and thickens the tone into warm overdrive without making it much louder.',
  },
  glide: {
    id: 8,
    name: 'Glide',
    min: 0,
    max: 1,
    default: 0.08,
    taper: 'linear',
    unit: 's',
    description:
      'Time the pitch takes to slide to a new key pressed while another is still held. Keys played apart start on pitch.',
  },
  volume: {
    id: 9,
    name: 'Volume',
    min: -48,
    max: 6,
    default: -9,
    taper: 'linear',
    unit: 'dB',
    description:
      'Output level of the instrument. A soft clip after it catches peaks at high settings.',
  },
} as const satisfies Record<string, ParamSpec>

export type LadderBassParamName = keyof typeof LADDER_BASS_PARAMS

export const LADDER_BASS_DEVICE = defineWasmDevice({
  id: 'ladder-bass',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/ladder-bass.wasm', import.meta.url),
  params: LADDER_BASS_PARAMS,
})

export const LADDER_BASS_DESCRIPTOR = wasmDeviceDescriptor(LADDER_BASS_DEVICE, {
  name: 'Ladder Bass',
  category: 'instrument',
  description:
    'One-voice bass in the style of seventies ladder-filter synthesizers: two beating oscillators and a sub through an overdriven four-pole filter, for sequences, pedal drones and sub tones.',
  presets: {
    'Sequence bass': {
      wave: 0,
      beat: 6,
      sub: 0.3,
      cutoff: 500,
      emphasis: 0.3,
      contour: 0.6,
      decay: 0.6,
      drive: 0.3,
      glide: 0.08,
    },
    'Pedal drone': {
      beat: 9,
      sub: 0.6,
      cutoff: 350,
      emphasis: 0.1,
      contour: 0,
      decay: 10,
      drive: 0.2,
      glide: 0.15,
    },
    'Soft sub': {
      wave: 1,
      beat: 3,
      sub: 1,
      cutoff: 120,
      emphasis: 0,
      contour: 0,
      decay: 10,
      drive: 0,
      glide: 0.1,
    },
    'Singing lead': {
      wave: 0.3,
      beat: 5,
      sub: 0.2,
      cutoff: 1500,
      emphasis: 0.45,
      contour: 0.3,
      decay: 10,
      drive: 0.25,
      glide: 0.12,
      volume: -3,
    },
    'Slow opener': {
      beat: 7,
      sub: 0.4,
      cutoff: 150,
      emphasis: 0.6,
      contour: 0.8,
      decay: 6,
      drive: 0.3,
    },
    'Rubber pluck': {
      wave: 0.6,
      beat: 4,
      sub: 0.2,
      cutoff: 220,
      emphasis: 0.55,
      contour: 0.75,
      decay: 0.9,
      drive: 0.5,
      volume: -6,
    },
  },
})

export type LadderBass = WasmDevice<typeof LADDER_BASS_PARAMS>

/** One-voice bass in the style of seventies ladder-filter synthesizers: two beating oscillators and a sub through an overdriven four-pole filter, for sequences, pedal drones and sub tones. Play it through `NoteDevice`: `noteOn(id, frequency, gain)` / `noteOff(id)`. */
export function createLadderBass(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof LADDER_BASS_PARAMS> = {},
): Promise<LadderBass> {
  return WasmDevice.create(context, LADDER_BASS_DEVICE, options)
}
