// GENERATED by scripts/gen-devices.mjs from cpp/devices/melt/device.json. Do not edit.

import { type DeviceMeterSpec } from '../../core/devices/Device'
import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const MELT_PARAMS = {
  sag: {
    id: 0,
    name: 'Sag',
    min: -100,
    max: 100,
    default: -30,
    taper: 'linear',
    unit: 'ct/s',
    description:
      'How fast the tail slides in pitch as it ages. Below zero it sinks and melts, above zero it lifts and evaporates, and at zero the pitch holds still.',
  },
  hold: {
    id: 1,
    name: 'Hold',
    min: 0.4,
    max: 20,
    default: 5,
    taper: 'log',
    unit: 's',
    description:
      'How long the tail rings before it is gone. Longer settings let the sound slide further from where it started.',
  },
  solid: {
    id: 2,
    name: 'Solid',
    min: 0,
    max: 1000,
    default: 120,
    taper: 'linear',
    unit: 'ms',
    description:
      'How long a sound stays as it was played before the melt is heard behind it. Short settings smear the note at once, long ones leave its start clean.',
  },
  size: {
    id: 3,
    name: 'Size',
    min: 0,
    max: 1,
    default: 0.35,
    taper: 'linear',
    unit: '',
    description:
      'The grain of the melt. Small settings run smooth and close, large ones break the tail into separate repeats that each land a little further off.',
  },
  blur: {
    id: 4,
    name: 'Blur',
    min: 0,
    max: 1,
    default: 0.55,
    taper: 'linear',
    unit: '',
    description:
      'How much the tail smears as it ages. At zero the repeats stay distinct, higher settings dissolve them into a soft wash.',
  },
  dim: {
    id: 5,
    name: 'Dim',
    min: 0,
    max: 1,
    default: 0.4,
    taper: 'linear',
    unit: '',
    description:
      'How fast the tail loses colour as it ages. A sinking tail loses its highs and goes dark, a rising one loses its lows and goes thin.',
  },
  drip: {
    id: 6,
    name: 'Drip',
    min: 0,
    max: 1,
    default: 0.2,
    taper: 'linear',
    unit: '',
    description:
      'Makes the slide uneven. The tail falls in fits, stalling and then running on, instead of in one straight line.',
  },
  width: {
    id: 7,
    name: 'Width',
    min: 0,
    max: 1,
    default: 1,
    taper: 'linear',
    unit: '',
    description:
      'How wide the tail spreads between the speakers. At zero it sits in the centre behind the dry sound.',
  },
  mix: {
    id: 8,
    name: 'Mix',
    min: 0,
    max: 1,
    default: 0.4,
    taper: 'linear',
    unit: '',
    description: 'Balance between the dry sound and the melting tail.',
  },
} as const satisfies Record<string, ParamSpec>

export type MeltParamName = keyof typeof MELT_PARAMS

export const MELT_METERS = {
  wander: { id: 0, name: 'Fall rate off Sag', unit: '', display: true },
} as const satisfies Record<string, DeviceMeterSpec>

export const MELT_DEVICE = defineWasmDevice({
  id: 'melt',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/melt.wasm', import.meta.url),
  params: MELT_PARAMS,
  meters: MELT_METERS,
})

export const MELT_DESCRIPTOR = wasmDeviceDescriptor(MELT_DEVICE, {
  name: 'Melt',
  category: 'texture',
  description:
    'A tail that ages: the longer a sound has rung the further it sags in pitch, darkens and blurs, like wax running, or turned the other way it lifts, thins and evaporates.',
  presets: {
    'Slow melt': {
      sag: -30,
      hold: 5,
      solid: 120,
      size: 0.35,
      blur: 0.55,
      dim: 0.4,
      drip: 0.2,
      width: 1,
      mix: 0.4,
    },
    'Soft sag': { sag: -8, hold: 2.5, solid: 60, blur: 0.7, dim: 0.3, drip: 0.1, mix: 0.25 },
    'Candle wax': { sag: -18, hold: 9, solid: 300, blur: 0.8, dim: 0.55, drip: 0.35, mix: 0.45 },
    Evaporate: { sag: 35, hold: 5, solid: 100, blur: 0.6, dim: 0.5, drip: 0.15, mix: 0.4 },
    'Into thin air': { sag: 70, hold: 8, solid: 250, size: 0.5, blur: 0.85, dim: 0.75, mix: 0.5 },
    'Still halo': { sag: 0, hold: 4, solid: 40, blur: 0.8, dim: 0.2, drip: 0, mix: 0.35 },
    'Drip by drip': {
      sag: -60,
      hold: 7,
      solid: 0,
      size: 0.9,
      blur: 0.15,
      dim: 0.3,
      drip: 0.3,
      mix: 0.45,
    },
    'Rising drops': {
      sag: 50,
      hold: 6,
      solid: 0,
      size: 0.8,
      blur: 0.2,
      dim: 0.4,
      drip: 0.1,
      mix: 0.4,
    },
    'Deep pool': {
      sag: -6,
      hold: 20,
      solid: 400,
      size: 0.6,
      blur: 1,
      dim: 0.3,
      drip: 0.5,
      mix: 0.5,
    },
    'Barely there': { sag: -20, hold: 3, solid: 80, blur: 0.6, dim: 0.4, mix: 0.12 },
    'Sudden slump': {
      sag: -100,
      hold: 2.5,
      solid: 0,
      size: 0.2,
      blur: 0.5,
      dim: 0.6,
      drip: 0,
      mix: 0.5,
    },
    'Wobbly wax': { sag: -45, hold: 6, solid: 60, blur: 0.6, dim: 0.35, drip: 1, mix: 0.45 },
    'Clean start': { sag: -40, hold: 6, solid: 700, blur: 0.65, dim: 0.5, mix: 0.45 },
    'Dark puddle': {
      sag: -25,
      hold: 8,
      solid: 150,
      size: 0.5,
      blur: 0.9,
      dim: 1,
      width: 0.6,
      mix: 0.5,
    },
    'Narrow thread': {
      sag: 15,
      hold: 3,
      solid: 20,
      size: 0,
      blur: 0.3,
      dim: 0.2,
      drip: 0,
      width: 0,
      mix: 0.35,
    },
    'Tail alone': { sag: -30, hold: 6, solid: 0, blur: 0.7, dim: 0.4, mix: 1 },
  },
})

export type Melt = WasmDevice<typeof MELT_PARAMS>

/** A tail that ages: the longer a sound has rung the further it sags in pitch, darkens and blurs, like wax running, or turned the other way it lifts, thins and evaporates. */
export function createMelt(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof MELT_PARAMS> = {},
): Promise<Melt> {
  return WasmDevice.create(context, MELT_DEVICE, options)
}
