// GENERATED by scripts/gen-devices.mjs from cpp/devices/modal-bells/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const MODAL_BELLS_PARAMS = {
  material: {
    id: 0,
    name: 'Material',
    min: 0,
    max: 6,
    default: 1,
    taper: 'linear',
    unit: '',
    choices: ['Church bell', 'Singing bowl', 'Vibraphone', 'Bar', 'Kalimba', 'Glass', 'Gong'],
  },
  decay: { id: 1, name: 'Decay', min: 0.2, max: 40, default: 12, taper: 'log', unit: 's' },
  damping: { id: 2, name: 'Damping', min: 0, max: 1, default: 0.4, taper: 'linear', unit: '' },
  hardness: { id: 3, name: 'Hardness', min: 0, max: 1, default: 0.45, taper: 'linear', unit: '' },
  position: { id: 4, name: 'Position', min: 0, max: 1, default: 0.15, taper: 'linear', unit: '' },
  detune: { id: 5, name: 'Detune', min: 0, max: 8, default: 1, taper: 'linear', unit: 'Hz' },
  stretch: { id: 6, name: 'Stretch', min: 0.5, max: 1.5, default: 1, taper: 'linear', unit: '' },
  sustain: { id: 7, name: 'Sustain', min: 0, max: 1, default: 0, taper: 'linear', unit: '' },
  brightness: {
    id: 8,
    name: 'Brightness',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
  },
  release: { id: 9, name: 'Release', min: 0, max: 1, default: 0.25, taper: 'linear', unit: '' },
  spread: { id: 10, name: 'Spread', min: 0, max: 1, default: 0.6, taper: 'linear', unit: '' },
  volume: { id: 11, name: 'Volume', min: -48, max: 6, default: -9, taper: 'linear', unit: 'dB' },
} as const satisfies Record<string, ParamSpec>

export type ModalBellsParamName = keyof typeof MODAL_BELLS_PARAMS

export const MODAL_BELLS_DEVICE = defineWasmDevice({
  id: 'modal-bells',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/modal-bells.wasm', import.meta.url),
  params: MODAL_BELLS_PARAMS,
})

export const MODAL_BELLS_DESCRIPTOR = wasmDeviceDescriptor(MODAL_BELLS_DEVICE, {
  name: 'Bells',
  category: 'instrument',
  description:
    'Struck and rubbed metal, glass and wood: church bells, singing bowls, vibraphone and chime bars, kalimba, glass and gongs, each a bank of ringing modes at the ratios of the real thing.',
  presets: {
    'Singing bowl': {},
    'Rubbed bowl': {
      decay: 20,
      hardness: 0.2,
      detune: 0.7,
      sustain: 1,
      release: 0.05,
      spread: 0.8,
    },
    'Church bell': {
      material: 0,
      decay: 28,
      damping: 0.45,
      hardness: 0.7,
      position: 0.05,
      detune: 0.6,
      release: 0,
      spread: 0.4,
    },
    Vibraphone: {
      material: 2,
      decay: 7,
      damping: 0.5,
      hardness: 0.3,
      position: 0.9,
      detune: 0.3,
      release: 0.75,
      spread: 0.3,
    },
    'Music box': {
      material: 3,
      decay: 3,
      damping: 0.3,
      hardness: 0.85,
      position: 0.1,
      detune: 0.4,
      brightness: 0.6,
      release: 0.2,
      spread: 0.5,
    },
    Kalimba: {
      material: 4,
      decay: 2.5,
      damping: 0.75,
      hardness: 0.6,
      position: 0.1,
      detune: 0.5,
      release: 0.4,
      spread: 0.3,
    },
    'Glass harp': {
      material: 5,
      decay: 9,
      damping: 0.3,
      hardness: 0.15,
      detune: 1.5,
      sustain: 0.9,
      brightness: 0.4,
      release: 0.3,
      spread: 0.7,
    },
    Gong: {
      material: 6,
      decay: 30,
      damping: 0.5,
      hardness: 0.3,
      position: 0.35,
      detune: 2,
      release: 0,
      spread: 1,
    },
  },
})

export type ModalBells = WasmDevice<typeof MODAL_BELLS_PARAMS>

/** Struck and rubbed metal, glass and wood: church bells, singing bowls, vibraphone and chime bars, kalimba, glass and gongs, each a bank of ringing modes at the ratios of the real thing. Play it through `NoteDevice`: `noteOn(id, frequency, gain)` / `noteOff(id)`. */
export function createModalBells(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof MODAL_BELLS_PARAMS> = {},
): Promise<ModalBells> {
  return WasmDevice.create(context, MODAL_BELLS_DEVICE, options)
}
