// GENERATED by scripts/gen-devices.mjs from cpp/devices/murmuration/device.json. Do not edit.

import { type DeviceMeterSpec } from '../../core/devices/Device'
import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const MURMURATION_PARAMS = {
  birds: {
    id: 0,
    name: 'Birds',
    min: 1,
    max: 16,
    default: 8,
    taper: 'linear',
    unit: '',
    step: 1,
    description:
      'How many copies of the sound fly. One is a single moving echo, a few are a chorus, many are a crowd.',
  },
  range: {
    id: 1,
    name: 'Range',
    min: 1,
    max: 60,
    default: 10,
    taper: 'log',
    unit: 'm',
    description:
      'How far out the flock flies. A short range is a tight shimmer close by, a long one spreads the copies into late echoes that bend further in pitch.',
  },
  speed: {
    id: 2,
    name: 'Speed',
    min: 0.05,
    max: 4,
    default: 1,
    taper: 'log',
    unit: 'x',
    description:
      'How fast the flock flies. Slow drifts and barely bends the pitch, fast swoops and wavers. A flock with a long range is held to a safe speed.',
  },
  together: {
    id: 3,
    name: 'Together',
    min: 0,
    max: 1,
    default: 0.6,
    taper: 'linear',
    unit: '',
    description:
      'How close the birds keep. Up is a tight knot that moves as one thick voice, down scatters them over the whole range as separate echoes.',
  },
  turns: {
    id: 4,
    name: 'Turns',
    min: 0,
    max: 1,
    default: 0.3,
    taper: 'linear',
    unit: '',
    description:
      'How often the whole flock wheels: it rushes off, bunches up, swings round and comes back, bending the pitch as it goes. Zero is a steady drift. A change eases in.',
  },
  air: {
    id: 5,
    name: 'Air',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
    description:
      'How much distance quietens and dulls a bird. Zero keeps every bird as clear and loud as the next, full makes near ones stand out and far ones fade.',
  },
  spread: {
    id: 6,
    name: 'Spread',
    min: 0,
    max: 1,
    default: 0.8,
    taper: 'linear',
    unit: '',
    description:
      'How far round the listener the flock flies. Zero keeps every bird straight ahead, full lets them cross from one side to the other. A stereo sound keeps its own sides.',
  },
  lift: {
    id: 7,
    name: 'Lift',
    min: 0,
    max: 1,
    default: 0.3,
    taper: 'linear',
    unit: '',
    description:
      'Lets the birds fly at different heights, where the low ones are duller than the high ones, so each copy has a tone of its own that keeps changing.',
  },
  ground: {
    id: 8,
    name: 'Ground',
    min: 20,
    max: 500,
    default: 200,
    taper: 'log',
    unit: 'Hz',
    description:
      'Keeps the low end on the ground. Sound below it passes straight through instead of flying, so the flock cannot thin out a bass note. Fully down lets everything fly.',
  },
  mix: {
    id: 9,
    name: 'Mix',
    min: 0,
    max: 1,
    default: 0.4,
    taper: 'linear',
    unit: '',
    description:
      'Balance between the dry sound and the flock. Fully wet leaves only the birds, and the low end that Ground keeps in place.',
  },
} as const satisfies Record<string, ParamSpec>

export type MurmurationParamName = keyof typeof MURMURATION_PARAMS

export const MURMURATION_METERS = {
  flight: { id: 0, name: 'Flight time', unit: 's', display: true },
  turns: { id: 1, name: 'Turns as flown', unit: '', display: true },
} as const satisfies Record<string, DeviceMeterSpec>

export const MURMURATION_DEVICE = defineWasmDevice({
  id: 'murmuration',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/murmuration.wasm', import.meta.url),
  params: MURMURATION_PARAMS,
  meters: MURMURATION_METERS,
})

export const MURMURATION_DESCRIPTOR = wasmDeviceDescriptor(MURMURATION_DEVICE, {
  name: 'Murmuration',
  category: 'modulation',
  description:
    'Turns one voice into a flock of up to sixteen that fly around the listener, each with its own distance, delay and bend in pitch.',
  presets: {
    'Evening flock': {},
    'Two close by': {
      birds: 2,
      range: 3,
      speed: 0.6,
      together: 0.8,
      turns: 0,
      air: 0.2,
      spread: 0.5,
      mix: 0.35,
    },
    'Thick ensemble': {
      birds: 16,
      range: 12,
      speed: 1.2,
      together: 0.55,
      turns: 0.2,
      air: 0.3,
      spread: 1,
      mix: 0.55,
    },
    'Slow drift': { birds: 6, range: 14, speed: 0.2, together: 0.5, turns: 0.1, mix: 0.4 },
    'Cloud far off': {
      birds: 16,
      range: 45,
      speed: 0.35,
      together: 0.1,
      air: 0.8,
      spread: 1,
      lift: 0.6,
      mix: 0.7,
    },
    Wheeling: { birds: 12, range: 16, speed: 1.6, together: 0.7, turns: 1, mix: 0.6 },
    'One bird': { birds: 1, range: 25, speed: 1.1, together: 1, turns: 0.6, air: 0.7, mix: 0.4 },
    'Barely there': { birds: 4, range: 5, speed: 0.5, together: 0.7, air: 0.4, mix: 0.15 },
    'Wide and dull': {
      birds: 10,
      range: 30,
      speed: 0.6,
      together: 0.2,
      air: 1,
      spread: 1,
      lift: 0,
      mix: 0.6,
    },
    Seasick: {
      birds: 5,
      range: 40,
      speed: 4,
      together: 0.9,
      turns: 0.8,
      air: 0.3,
      ground: 20,
      mix: 1,
    },
    'Wet shimmer': { birds: 16, range: 8, speed: 2.6, together: 0.3, air: 0.1, lift: 1, mix: 1 },
    'Straight ahead': { birds: 12, range: 12, together: 0.4, spread: 0, mix: 0.45 },
    'Slapback flock': {
      birds: 3,
      range: 50,
      speed: 0.1,
      together: 1,
      turns: 0,
      air: 0.1,
      mix: 0.4,
    },
    'Comb by the ear': {
      birds: 8,
      range: 1.5,
      speed: 2.5,
      together: 0.3,
      air: 1,
      spread: 1,
      mix: 0.5,
    },
    'High and bright': {
      birds: 9,
      range: 18,
      speed: 0.8,
      together: 0.45,
      air: 0.2,
      lift: 1,
      mix: 0.55,
    },
    'Scattered room': {
      birds: 16,
      range: 60,
      speed: 0.3,
      together: 0,
      turns: 0,
      air: 0.6,
      spread: 1,
      mix: 0.45,
    },
  },
})

export type Murmuration = WasmDevice<typeof MURMURATION_PARAMS>

/** Turns one voice into a flock of up to sixteen that fly around the listener, each with its own distance, delay and bend in pitch. */
export function createMurmuration(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof MURMURATION_PARAMS> = {},
): Promise<Murmuration> {
  return WasmDevice.create(context, MURMURATION_DEVICE, options)
}
