// GENERATED by scripts/gen-devices.mjs from cpp/devices/pitch-shifter/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const PITCH_SHIFTER_PARAMS = {
  pitchA: {
    id: 0,
    name: 'Pitch A',
    min: -24,
    max: 24,
    default: 12,
    taper: 'linear',
    unit: 'st',
    description:
      'The interval of the first voice above or below what is played. It glides when moved, so it can be played like a pitch pedal.',
  },
  pitchB: {
    id: 1,
    name: 'Pitch B',
    min: -24,
    max: 24,
    default: -12,
    taper: 'linear',
    unit: 'st',
    description: 'The interval of the second voice. It is silent until Voice B is raised.',
  },
  levelB: {
    id: 2,
    name: 'Voice B',
    min: 0,
    max: 1,
    default: 0,
    taper: 'linear',
    unit: '',
    description:
      'How loud the second voice is beside the first. Zero leaves a single shifted voice.',
  },
  detune: {
    id: 3,
    name: 'Detune',
    min: 0,
    max: 50,
    default: 0,
    taper: 'linear',
    unit: 'ct',
    description:
      'Pushes voice A a little sharp and voice B a little flat. With both pitches at zero it is a doubler that thickens the sound.',
  },
  mode: {
    id: 4,
    name: 'Mode',
    min: 0,
    max: 2,
    default: 0,
    taper: 'linear',
    unit: '',
    choices: ['Smooth', 'Grain', 'Vintage'],
    description:
      'The character of the shift. Smooth lines its splices up with the sound and stays clean, Grain rebuilds it from overlapping grains, Vintage splices blindly and flutters.',
  },
  size: {
    id: 5,
    name: 'Size',
    min: 10,
    max: 400,
    default: 80,
    taper: 'log',
    unit: 'ms',
    description:
      'The length of the pieces the shifter works with. Short is tight in time and rougher, down to a metallic buzz in Grain; long is smoother and looser.',
  },
  jitter: {
    id: 6,
    name: 'Jitter',
    min: 0,
    max: 1,
    default: 0,
    taper: 'linear',
    unit: '',
    description:
      'Scatters each grain or splice in time and pitch. A little loosens the shift into a chorus; a lot turns it into a noisy cloud.',
  },
  delay: {
    id: 7,
    name: 'Delay',
    min: 0,
    max: 1000,
    default: 0,
    taper: 'linear',
    unit: 'ms',
    description: 'How late the shifted voices arrive. With Feedback it is the gap between repeats.',
  },
  feedback: {
    id: 8,
    name: 'Feedback',
    min: 0,
    max: 0.95,
    default: 0,
    taper: 'linear',
    unit: '',
    description:
      'Sends the shifted voices back in through the delay, so each repeat is shifted again and climbs or falls. With no delay it thickens into a shimmer.',
  },
  tone: {
    id: 9,
    name: 'Tone',
    min: 800,
    max: 18000,
    default: 9000,
    taper: 'log',
    unit: 'Hz',
    description:
      'Darkens the shifted voices. It sits in the feedback path too, so each repeat is duller than the last.',
  },
  spread: {
    id: 10,
    name: 'Spread',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
    description:
      'Moves voice A to the left and voice B to the right. Zero keeps both in the middle.',
  },
  mix: {
    id: 11,
    name: 'Mix',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
    description: 'Balance between the dry signal and the shifted voices.',
  },
} as const satisfies Record<string, ParamSpec>

export type PitchShifterParamName = keyof typeof PITCH_SHIFTER_PARAMS

export const PITCH_SHIFTER_DEVICE = defineWasmDevice({
  id: 'pitch-shifter',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/pitch-shifter.wasm', import.meta.url),
  params: PITCH_SHIFTER_PARAMS,
})

export const PITCH_SHIFTER_DESCRIPTOR = wasmDeviceDescriptor(PITCH_SHIFTER_DEVICE, {
  name: 'Pitch Shifter',
  category: 'pitch',
  description:
    'Two pitch-shifted voices in three characters, clean, grainy or fluttering, with a delay and feedback that make the repeats climb or fall.',
  presets: {
    'Octave up': { pitchA: 12, levelB: 0, mode: 0, size: 80, mix: 0.5 },
    'Octave down': { pitchA: -12, levelB: 0, mode: 0, size: 100, mix: 0.5 },
    'Fifth above': { pitchA: 7, levelB: 0, mode: 0, mix: 0.45 },
    'Octaves both': { pitchA: 12, pitchB: -12, levelB: 1, spread: 0.6, mix: 0.5 },
  },
})

export type PitchShifter = WasmDevice<typeof PITCH_SHIFTER_PARAMS>

/** Two pitch-shifted voices in three characters, clean, grainy or fluttering, with a delay and feedback that make the repeats climb or fall. */
export function createPitchShifter(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof PITCH_SHIFTER_PARAMS> = {},
): Promise<PitchShifter> {
  return WasmDevice.create(context, PITCH_SHIFTER_DEVICE, options)
}
