// GENERATED by scripts/gen-devices.mjs from cpp/devices/reverse-delay/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const REVERSE_DELAY_PARAMS = {
  time: { id: 0, name: 'Time', min: 50, max: 4000, default: 600, taper: 'log', unit: 'ms' },
  feedback: {
    id: 1,
    name: 'Feedback',
    min: 0,
    max: 0.95,
    default: 0.35,
    taper: 'linear',
    unit: '',
  },
  pitch: {
    id: 2,
    name: 'Pitch',
    min: 0,
    max: 2,
    default: 0,
    taper: 'linear',
    unit: '',
    choices: ['Normal', 'Octave up', 'Octave down'],
  },
  smooth: { id: 3, name: 'Smooth', min: 0, max: 1, default: 0.35, taper: 'linear', unit: '' },
  tone: { id: 4, name: 'Tone', min: 500, max: 16000, default: 6000, taper: 'log', unit: 'Hz' },
  spread: { id: 5, name: 'Spread', min: 0, max: 1, default: 0.5, taper: 'linear', unit: '' },
  mix: { id: 6, name: 'Mix', min: 0, max: 1, default: 0.4, taper: 'linear', unit: '' },
  lowCut: { id: 7, name: 'Low Cut', min: 20, max: 800, default: 100, taper: 'log', unit: 'Hz' },
} as const satisfies Record<string, ParamSpec>

export type ReverseDelayParamName = keyof typeof REVERSE_DELAY_PARAMS

export const REVERSE_DELAY_DEVICE = defineWasmDevice({
  id: 'reverse-delay',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/reverse-delay.wasm', import.meta.url),
  params: REVERSE_DELAY_PARAMS,
})

export const REVERSE_DELAY_DESCRIPTOR = wasmDeviceDescriptor(REVERSE_DELAY_DEVICE, {
  name: 'Reverse Delay',
  category: 'delay',
  description:
    'Plays what you just played backwards, in overlapping chunks that swell in and cut off, with feedback, octave shifts and chunks that alternate sides.',
  presets: {
    'Backwards echo': {
      time: 600,
      feedback: 0.35,
      pitch: 0,
      smooth: 0.35,
      tone: 6000,
      spread: 0.5,
      mix: 0.4,
      lowCut: 100,
    },
    'Slow swells': {
      time: 1600,
      feedback: 0.2,
      pitch: 0,
      smooth: 1,
      tone: 4200,
      spread: 0.3,
      mix: 0.5,
    },
    'Rising glass': {
      time: 900,
      feedback: 0.6,
      pitch: 1,
      smooth: 0.8,
      tone: 5000,
      spread: 0.7,
      mix: 0.35,
      lowCut: 220,
    },
    Undertow: {
      time: 2200,
      feedback: 0.45,
      pitch: 2,
      smooth: 0.6,
      tone: 2400,
      spread: 0.4,
      mix: 0.4,
      lowCut: 60,
    },
    Flicker: { time: 130, feedback: 0.5, pitch: 0, smooth: 0.5, tone: 9000, spread: 1, mix: 0.3 },
    'Long mirror': {
      time: 4000,
      feedback: 0.5,
      pitch: 0,
      smooth: 0.45,
      tone: 5200,
      spread: 0.2,
      mix: 0.5,
    },
  },
})

export type ReverseDelay = WasmDevice<typeof REVERSE_DELAY_PARAMS>

/** Plays what you just played backwards, in overlapping chunks that swell in and cut off, with feedback, octave shifts and chunks that alternate sides. */
export function createReverseDelay(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof REVERSE_DELAY_PARAMS> = {},
): Promise<ReverseDelay> {
  return WasmDevice.create(context, REVERSE_DELAY_DEVICE, options)
}
