// GENERATED by scripts/gen-devices.mjs from cpp/devices/reverse-delay/device.json. Do not edit.

import { type DeviceMeterSpec } from '../../core/devices/Device'
import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const REVERSE_DELAY_PARAMS = {
  time: {
    id: 0,
    name: 'Time',
    min: 50,
    max: 4000,
    default: 600,
    taper: 'log',
    unit: 'ms',
    description:
      'Length of each backwards chunk, and how long the wait is to hear it. Short chunks stutter; long ones reverse whole phrases.',
  },
  feedback: {
    id: 1,
    name: 'Feedback',
    min: 0,
    max: 0.95,
    default: 0.35,
    taper: 'linear',
    unit: '',
    description:
      'Sends the chunks back in for more repeats. Each pass is reversed again, so every second repeat plays forwards.',
  },
  pitch: {
    id: 2,
    name: 'Pitch',
    min: 0,
    max: 2,
    default: 0,
    taper: 'linear',
    unit: '',
    choices: ['Normal', 'Octave up', 'Octave down'],
    description:
      'Octave up plays the chunks at double speed and Octave down at half speed. The chunks stay the same length.',
  },
  smooth: {
    id: 3,
    name: 'Smooth',
    min: 0,
    max: 1,
    default: 0.35,
    taper: 'linear',
    unit: '',
    description:
      'How much of each chunk is spent fading in and out. Low splices chunks abruptly; high makes each one swell up and die away.',
  },
  tone: {
    id: 4,
    name: 'Tone',
    min: 500,
    max: 16000,
    default: 6000,
    taper: 'log',
    unit: 'Hz',
    description:
      'Darkens the reversed sound. It sits in the feedback loop, so each repeat is darker than the last.',
  },
  spread: {
    id: 5,
    name: 'Spread',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
    description:
      'Sends alternate chunks to opposite sides. Zero keeps them all in the centre; full bounces them hard left and right.',
  },
  mix: {
    id: 6,
    name: 'Mix',
    min: 0,
    max: 1,
    default: 0.4,
    taper: 'linear',
    unit: '',
    description: 'Balance between the dry signal and the reversed chunks.',
  },
  lowCut: {
    id: 7,
    name: 'Low Cut',
    min: 20,
    max: 800,
    default: 100,
    taper: 'log',
    unit: 'Hz',
    description:
      'Removes lows from the reversed sound. It sits in the feedback loop, so the repeats thin out and the low end does not build up.',
  },
} as const satisfies Record<string, ParamSpec>

export type ReverseDelayParamName = keyof typeof REVERSE_DELAY_PARAMS

export const REVERSE_DELAY_METERS = {
  level: { id: 0, name: 'Record level', unit: '', display: true },
  aBehind: { id: 1, name: 'Reader A behind', unit: '', display: true },
  aGain: { id: 2, name: 'Reader A gain', unit: '', display: true },
  bBehind: { id: 3, name: 'Reader B behind', unit: '', display: true },
  bGain: { id: 4, name: 'Reader B gain', unit: '', display: true },
} as const satisfies Record<string, DeviceMeterSpec>

export const REVERSE_DELAY_DEVICE = defineWasmDevice({
  id: 'reverse-delay',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/reverse-delay.wasm', import.meta.url),
  params: REVERSE_DELAY_PARAMS,
  meters: REVERSE_DELAY_METERS,
})

export const REVERSE_DELAY_DESCRIPTOR = wasmDeviceDescriptor(REVERSE_DELAY_DEVICE, {
  name: 'Reverse Delay',
  category: 'delay',
  description:
    'Plays what you just played backwards, in overlapping chunks that swell in and cut off, with feedback, octave shifts and chunks that alternate sides.',
  presets: {
    'Backwards echo': {
      time: 600,
      feedback: 0.35,
      pitch: 0,
      smooth: 0.35,
      tone: 6000,
      spread: 0.5,
      mix: 0.4,
      lowCut: 100,
    },
    'Slow swells': {
      time: 1600,
      feedback: 0.2,
      pitch: 0,
      smooth: 1,
      tone: 4200,
      spread: 0.3,
      mix: 0.5,
    },
    'Rising glass': {
      time: 900,
      feedback: 0.6,
      pitch: 1,
      smooth: 0.8,
      tone: 5000,
      spread: 0.7,
      mix: 0.35,
      lowCut: 220,
    },
    Undertow: {
      time: 2200,
      feedback: 0.45,
      pitch: 2,
      smooth: 0.6,
      tone: 2400,
      spread: 0.4,
      mix: 0.4,
      lowCut: 60,
    },
    Flicker: { time: 130, feedback: 0.5, pitch: 0, smooth: 0.5, tone: 9000, spread: 1, mix: 0.3 },
    'Long mirror': {
      time: 4000,
      feedback: 0.5,
      pitch: 0,
      smooth: 0.45,
      tone: 5200,
      spread: 0.2,
      mix: 0.5,
    },
    'Hard splices': {
      time: 400,
      feedback: 0.3,
      pitch: 0,
      smooth: 0,
      tone: 9000,
      spread: 0.4,
      mix: 0.4,
    },
    'Tight stutter': {
      time: 60,
      feedback: 0.6,
      pitch: 0,
      smooth: 0.15,
      tone: 7000,
      spread: 0,
      mix: 0.35,
    },
    'Faint reflection': {
      time: 800,
      feedback: 0.2,
      pitch: 0,
      smooth: 0.8,
      tone: 5000,
      spread: 0.6,
      mix: 0.15,
    },
    'Backwards only': {
      time: 1000,
      feedback: 0,
      pitch: 0,
      smooth: 0.5,
      tone: 12000,
      spread: 0.3,
      mix: 1,
      lowCut: 40,
    },
    'Glass splinters': {
      time: 200,
      feedback: 0.7,
      pitch: 1,
      smooth: 0.3,
      tone: 11000,
      spread: 1,
      mix: 0.3,
      lowCut: 300,
    },
    'Descending steps': {
      time: 500,
      feedback: 0.75,
      pitch: 2,
      smooth: 0.4,
      tone: 5000,
      spread: 0.6,
      mix: 0.4,
      lowCut: 40,
    },
    'Folding over': {
      time: 1000,
      feedback: 0.9,
      pitch: 0,
      smooth: 0.7,
      tone: 3500,
      spread: 0.5,
      mix: 0.4,
      lowCut: 160,
    },
    'Dark fog': {
      time: 1500,
      feedback: 0.6,
      pitch: 0,
      smooth: 1,
      tone: 700,
      spread: 0.8,
      mix: 0.5,
      lowCut: 30,
    },
    'Thin and airy': {
      time: 700,
      feedback: 0.5,
      pitch: 0,
      smooth: 0.6,
      tone: 13000,
      spread: 0.7,
      mix: 0.4,
      lowCut: 800,
    },
    'Phrase and mirror': {
      time: 2800,
      feedback: 0,
      pitch: 0,
      smooth: 0.25,
      tone: 16000,
      spread: 0,
      mix: 0.5,
      lowCut: 20,
    },
  },
})

export type ReverseDelay = WasmDevice<typeof REVERSE_DELAY_PARAMS>

/** Plays what you just played backwards, in overlapping chunks that swell in and cut off, with feedback, octave shifts and chunks that alternate sides. */
export function createReverseDelay(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof REVERSE_DELAY_PARAMS> = {},
): Promise<ReverseDelay> {
  return WasmDevice.create(context, REVERSE_DELAY_DEVICE, options)
}
