// GENERATED by scripts/gen-devices.mjs from cpp/devices/sampler/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const SAMPLER_PARAMS = {
  start: { id: 0, name: 'Start', min: 0, max: 1, default: 0.15, taper: 'linear', unit: '' },
  end: { id: 1, name: 'End', min: 0, max: 1, default: 0.85, taper: 'linear', unit: '' },
  loop: {
    id: 2,
    name: 'Loop',
    min: 0,
    max: 2,
    default: 1,
    taper: 'linear',
    unit: '',
    choices: ['Off', 'Forward', 'Ping-pong'],
  },
  crossfade: {
    id: 3,
    name: 'Crossfade',
    min: 0,
    max: 500,
    default: 50,
    taper: 'linear',
    unit: 'ms',
  },
  reverse: {
    id: 4,
    name: 'Reverse',
    min: 0,
    max: 1,
    default: 0,
    taper: 'linear',
    unit: '',
    choices: ['Off', 'On'],
  },
  tune: { id: 5, name: 'Tune', min: -24, max: 24, default: 0, taper: 'linear', unit: 'st' },
  fine: { id: 6, name: 'Fine', min: -100, max: 100, default: 0, taper: 'linear', unit: 'ct' },
  attack: { id: 7, name: 'Attack', min: 0.001, max: 8, default: 0.06, taper: 'log', unit: 's' },
  release: { id: 8, name: 'Release', min: 0.01, max: 12, default: 0.6, taper: 'log', unit: 's' },
  tone: { id: 9, name: 'Tone', min: 200, max: 18000, default: 8000, taper: 'log', unit: 'Hz' },
  wobble: { id: 10, name: 'Wobble', min: 0, max: 1, default: 0.2, taper: 'linear', unit: '' },
  velocity: { id: 11, name: 'Velocity', min: 0, max: 1, default: 0.6, taper: 'linear', unit: '' },
  volume: { id: 12, name: 'Volume', min: -48, max: 6, default: -9, taper: 'linear', unit: 'dB' },
} as const satisfies Record<string, ParamSpec>

export type SamplerParamName = keyof typeof SAMPLER_PARAMS

export const SAMPLER_DEVICE = defineWasmDevice({
  id: 'sampler',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/sampler.wasm', import.meta.url),
  params: SAMPLER_PARAMS,
})

export const SAMPLER_DESCRIPTOR = wasmDeviceDescriptor(SAMPLER_DEVICE, {
  name: 'Sampler',
  category: 'instrument',
  description:
    'One-sound sampler for your own recordings: the keys transpose it, a crossfaded loop holds it as long as you like, and a little tape wobble makes it a pad.',
  presets: {
    'Soft flute': {
      start: 0.15,
      end: 0.85,
      loop: 1,
      crossfade: 50,
      reverse: 0,
      tune: 0,
      fine: 0,
      attack: 0.06,
      release: 0.6,
      tone: 8000,
      wobble: 0.2,
      velocity: 0.6,
    },
    'Tape choir': {
      start: 0.15,
      end: 0.85,
      loop: 1,
      crossfade: 200,
      tune: -12,
      fine: 6,
      attack: 0.7,
      release: 2.8,
      tone: 4200,
      wobble: 0.5,
      velocity: 0.3,
    },
    'One shot': {
      start: 0,
      end: 1,
      loop: 0,
      crossfade: 0,
      attack: 0.001,
      release: 0.3,
      tone: 14000,
      wobble: 0,
      velocity: 1,
    },
    Backwards: {
      start: 0,
      end: 1,
      loop: 0,
      crossfade: 0,
      reverse: 1,
      attack: 0.01,
      release: 1.2,
      tone: 9000,
      wobble: 0.15,
      velocity: 0.7,
    },
    'There and back': {
      start: 0.3,
      end: 0.7,
      loop: 2,
      tune: -12,
      attack: 1.6,
      release: 4.5,
      tone: 3000,
      wobble: 0.3,
      velocity: 0.2,
    },
    'Worn tape': {
      start: 0.15,
      end: 0.85,
      loop: 1,
      crossfade: 120,
      fine: -14,
      attack: 0.12,
      release: 1.5,
      tone: 3200,
      wobble: 0.9,
      velocity: 0.5,
    },
  },
})

export type Sampler = WasmDevice<typeof SAMPLER_PARAMS>

/** One-sound sampler for your own recordings: the keys transpose it, a crossfaded loop holds it as long as you like, and a little tape wobble makes it a pad. Play it through `NoteDevice`: `noteOn(id, frequency, gain)` / `noteOff(id)`. */
export function createSampler(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof SAMPLER_PARAMS> = {},
): Promise<Sampler> {
  return WasmDevice.create(context, SAMPLER_DEVICE, options)
}
