// GENERATED by scripts/gen-devices.mjs from cpp/devices/seasons/device.json. Do not edit.

import { type DeviceMeterSpec } from '../../core/devices/Device'
import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const SEASONS_PARAMS = {
  year: {
    id: 0,
    name: 'Year',
    min: 0,
    max: 1,
    default: 0.125,
    taper: 'linear',
    unit: '',
    description:
      'Where in the year the sound is: spring, summer, autumn, winter, a quarter of the dial each, blending between. Both ends meet. A turning year goes on from here.',
  },
  turning: {
    id: 1,
    name: 'Turning',
    min: 10,
    max: 1800,
    default: 120,
    taper: 'log',
    unit: 's',
    description:
      'How long one year takes when it turns by itself. Short is a restless cycle of colours, long is a change nobody notices happening.',
  },
  depth: {
    id: 2,
    name: 'Depth',
    min: 0,
    max: 1,
    default: 0.75,
    taper: 'linear',
    unit: '',
    description:
      'How far into the season the sound goes. All the way down is the sound as it came in, all the way up is the season at its strongest.',
  },
  space: {
    id: 3,
    name: 'Space',
    min: 0,
    max: 1,
    default: 0.6,
    taper: 'linear',
    unit: '',
    description:
      "How much of the season's room is heard: quick bright reflections in spring, a long soft haze in summer, a short dull room in autumn, a long thin tail in winter.",
  },
  motion: {
    id: 4,
    name: 'Motion',
    min: 0,
    max: 1,
    default: 0.6,
    taper: 'linear',
    unit: '',
    description:
      'How much the season moves: a fast shimmer and a rising tail in spring, a slow sway from side to side in summer, a tumbling and sinking in autumn. Winter barely stirs.',
  },
  grit: {
    id: 5,
    name: 'Grit',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
    description:
      "How much of the season's texture is heard: glassy sparks above the sound in winter and early spring, a warm pressing in summer, the top end breaking up in autumn.",
  },
  tail: {
    id: 6,
    name: 'Tails',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
    description:
      "Stretches or shortens every season's room. The middle is each season's own length. At the top a winter tail rings on long after the note.",
  },
  width: {
    id: 7,
    name: 'Width',
    min: 0,
    max: 2,
    default: 1,
    taper: 'linear',
    unit: '',
    description:
      'Stereo width of the seasoned sound, on top of what the season does itself: summer is wide and winter narrow. All the way down is mono.',
  },
  turn: {
    id: 8,
    name: 'Turn',
    min: 0,
    max: 2,
    default: 1,
    taper: 'linear',
    unit: '',
    choices: ['Still', 'Forward', 'Backward'],
    description:
      'Whether the year turns by itself. Still holds it where it has got to, Forward runs on from spring towards summer, Backward from spring towards winter.',
  },
  mix: {
    id: 9,
    name: 'Mix',
    min: 0,
    max: 1,
    default: 1,
    taper: 'linear',
    unit: '',
    description: 'Balance between the sound as it came in and the seasoned sound.',
  },
} as const satisfies Record<string, ParamSpec>

export type SeasonsParamName = keyof typeof SEASONS_PARAMS

export const SEASONS_METERS = {
  year: { id: 0, name: 'Year now', unit: '', display: true },
  crumble: { id: 1, name: 'Crumble gain', unit: '', display: true },
  glitter: { id: 2, name: 'Glitter level', unit: '', display: true },
  sway: { id: 3, name: 'Sway', unit: '', display: true },
} as const satisfies Record<string, DeviceMeterSpec>

export const SEASONS_DEVICE = defineWasmDevice({
  id: 'seasons',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/seasons.wasm', import.meta.url),
  params: SEASONS_PARAMS,
  meters: SEASONS_METERS,
})

export const SEASONS_DESCRIPTOR = wasmDeviceDescriptor(SEASONS_DEVICE, {
  name: 'Seasons',
  category: 'texture',
  description:
    'One dial turns the year: a bright quick spring, a warm wide summer, a dark crumbling autumn and a thin frozen winter, with every blend between, and the year can turn by itself.',
  presets: {
    'Spring, turning': {},
    'High summer': { year: 0.375, turn: 0, depth: 0.85, space: 0.7, motion: 0.7 },
    'Leaf fall': { year: 0.625, turn: 0, depth: 0.9, space: 0.5, motion: 0.8, grit: 0.8 },
    'Deep winter': { year: 0.875, turn: 0, depth: 0.9, space: 0.8, grit: 0.6, tail: 0.65 },
    'Slow year': { year: 0.545, turning: 600, depth: 0.65, space: 0.5 },
    'Quick year': { year: 0.325, turning: 12, depth: 1, space: 0.7, motion: 0.8, grit: 0.7 },
    Thaw: { year: 0, turn: 0, depth: 0.85, space: 0.7, motion: 0.5, grit: 0.9 },
    'Long evening': {
      year: 0.455,
      turn: 0,
      depth: 0.8,
      space: 0.9,
      motion: 0.4,
      grit: 0.6,
      tail: 0.9,
    },
    'First frost': { year: 0.75, turn: 0, depth: 0.85, space: 0.7, grit: 0.7, tail: 0.6 },
    'Touch of sun': { year: 0.345, turn: 0, depth: 0.3, space: 0.35, motion: 0.5, grit: 0.2 },
    'Frozen lake': {
      year: 0.875,
      turn: 0,
      depth: 1,
      space: 1,
      motion: 0,
      grit: 0.3,
      tail: 1,
      mix: 0.8,
    },
    'Wide midsummer': {
      year: 0.375,
      turn: 0,
      depth: 1,
      space: 0.9,
      motion: 1,
      tail: 0.7,
      width: 1.6,
    },
    'Dry leaves': { year: 0.625, turn: 0, depth: 1, space: 0, motion: 0.4, grit: 1 },
    'Backward year': { year: 0.475, turning: 40, depth: 0.9, space: 0.7, turn: 2 },
    'Bare branches': {
      year: 0.875,
      turn: 0,
      depth: 1,
      space: 0.2,
      motion: 0,
      grit: 0,
      tail: 0.2,
      width: 0.6,
    },
    'Spring showers': { year: 0.095, turn: 0, depth: 1, space: 0.8, motion: 1, grit: 1, tail: 0.3 },
  },
})

export type Seasons = WasmDevice<typeof SEASONS_PARAMS>

/** One dial turns the year: a bright quick spring, a warm wide summer, a dark crumbling autumn and a thin frozen winter, with every blend between, and the year can turn by itself. */
export function createSeasons(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof SEASONS_PARAMS> = {},
): Promise<Seasons> {
  return WasmDevice.create(context, SEASONS_DEVICE, options)
}
