// GENERATED by scripts/gen-devices.mjs from cpp/devices/shaped-reverb/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const SHAPED_REVERB_PARAMS = {
  shape: {
    id: 0,
    name: 'Shape',
    min: 0,
    max: 4,
    default: 1,
    taper: 'linear',
    unit: '',
    choices: ['Gate', 'Reverse', 'Bloom', 'Fall', 'Pulse'],
    description:
      "The outline the reverb's level follows. Gate holds steady and stops dead. Reverse grows louder and cuts off. Bloom swells in and fades away. Fall drops in a straight line. Pulse breathes in three waves.",
  },
  time: {
    id: 1,
    name: 'Time',
    min: 0.1,
    max: 4,
    default: 0.9,
    taper: 'log',
    unit: 's',
    description:
      'How long the shape lasts, from the note to its end. Short settings are a burst behind the note; long ones are a slow cloud. With Repeat up it is also the gap between repeats.',
  },
  density: {
    id: 2,
    name: 'Density',
    min: 0,
    max: 1,
    default: 0.8,
    taper: 'linear',
    unit: '',
    description:
      'How many reflections make up the shape and how blurred they are. Low settings are a handful of separate echoes; high settings are a smooth wash.',
  },
  preDelay: {
    id: 3,
    name: 'Pre-delay',
    min: 0,
    max: 250,
    default: 0,
    taper: 'linear',
    unit: 'ms',
    description:
      'A gap of silence between the note and the start of the shape, which keeps the note clear of the reverb.',
  },
  colour: {
    id: 4,
    name: 'Colour',
    min: -1,
    max: 1,
    default: -0.2,
    taper: 'linear',
    unit: '',
    description:
      'Changes the tone along the shape. Below the centre the reverb gets darker as it goes on; above the centre it starts dark and opens up towards the end.',
  },
  highCut: {
    id: 5,
    name: 'High Cut',
    min: 1000,
    max: 18000,
    default: 9000,
    taper: 'log',
    unit: 'Hz',
    description:
      'Takes the top off the whole reverb. Lower settings are darker and sit further back.',
  },
  lowCut: {
    id: 6,
    name: 'Low Cut',
    min: 20,
    max: 800,
    default: 120,
    taper: 'log',
    unit: 'Hz',
    description:
      'Takes the bottom out of the reverb so low notes do not turn to mud. Higher settings are thinner and lighter.',
  },
  modulation: {
    id: 7,
    name: 'Modulation',
    min: 0,
    max: 1,
    default: 0.3,
    taper: 'linear',
    unit: '',
    description:
      'Slow movement inside the reverb. A little keeps held notes from sounding fixed; more adds a gentle detuned shimmer.',
  },
  repeat: {
    id: 8,
    name: 'Repeat',
    min: 0,
    max: 0.9,
    default: 0,
    taper: 'linear',
    unit: '',
    description:
      'Plays the whole shape again and again, each pass quieter, darker and more blurred. High settings pulse for a long time.',
  },
  tail: {
    id: 9,
    name: 'Tail',
    min: 0,
    max: 1,
    default: 0.25,
    taper: 'linear',
    unit: '',
    description:
      'Adds an ordinary fading reverb behind the shape, so its end is not dead silence. Higher settings are louder and ring for longer; at zero the shape ends in nothing.',
  },
  width: {
    id: 10,
    name: 'Width',
    min: 0,
    max: 1,
    default: 1,
    taper: 'linear',
    unit: '',
    description:
      'How far the reverb spreads between the speakers. At zero it is mono; fully up the two sides are unrelated.',
  },
  mix: {
    id: 11,
    name: 'Mix',
    min: 0,
    max: 1,
    default: 0.4,
    taper: 'linear',
    unit: '',
    description: 'Balance between the dry signal and the reverb. Fully up is the reverb alone.',
  },
} as const satisfies Record<string, ParamSpec>

export type ShapedReverbParamName = keyof typeof SHAPED_REVERB_PARAMS

export const SHAPED_REVERB_DEVICE = defineWasmDevice({
  id: 'shaped-reverb',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/shaped-reverb.wasm', import.meta.url),
  params: SHAPED_REVERB_PARAMS,
})

export const SHAPED_REVERB_DESCRIPTOR = wasmDeviceDescriptor(SHAPED_REVERB_DEVICE, {
  name: 'Shaped Reverb',
  category: 'reverb',
  description:
    'A reverb whose level follows a drawn shape instead of dying away: it can hold and stop dead, rise backwards into a cut, swell and fade, fall in a straight line or breathe in waves.',
  presets: {
    'Backwards cloud': {
      shape: 1,
      time: 1.2,
      density: 0.9,
      colour: 0.3,
      modulation: 0.35,
      tail: 0.3,
      mix: 0.45,
    },
    'Gated room': {
      shape: 0,
      time: 0.35,
      density: 1,
      colour: -0.15,
      highCut: 8000,
      lowCut: 100,
      modulation: 0.15,
      tail: 0,
      mix: 0.4,
    },
    'Slow bloom': {
      shape: 2,
      time: 2.5,
      density: 1,
      colour: -0.4,
      highCut: 7000,
      lowCut: 150,
      modulation: 0.5,
      tail: 0.45,
      mix: 0.5,
    },
    'Straight fall': {
      shape: 3,
      time: 1.6,
      density: 0.85,
      preDelay: 20,
      colour: -0.5,
      tail: 0.2,
      mix: 0.35,
    },
    'Breathing pulses': {
      shape: 4,
      time: 1.8,
      density: 0.9,
      colour: -0.3,
      modulation: 0.4,
      repeat: 0.55,
      tail: 0.3,
      mix: 0.45,
    },
    Ghost: {
      shape: 1,
      time: 2,
      density: 1,
      preDelay: 60,
      colour: -0.8,
      highCut: 3500,
      lowCut: 200,
      modulation: 0.6,
      tail: 0.7,
      mix: 0.5,
    },
    'Short halo': {
      shape: 2,
      time: 0.3,
      density: 1,
      colour: 0,
      highCut: 12000,
      modulation: 0.2,
      tail: 0.15,
      mix: 0.3,
    },
    'Long reverse': {
      shape: 1,
      time: 4,
      density: 1,
      colour: 0.5,
      modulation: 0.5,
      tail: 0.5,
      mix: 0.55,
    },
    'Scattered echoes': {
      shape: 3,
      time: 2.2,
      density: 0.15,
      colour: -0.4,
      repeat: 0.3,
      tail: 0.4,
      mix: 0.4,
    },
    'Stepped gate': {
      shape: 0,
      time: 0.25,
      density: 0.95,
      colour: -0.2,
      modulation: 0.2,
      repeat: 0.7,
      tail: 0.1,
      mix: 0.5,
    },
  },
})

export type ShapedReverb = WasmDevice<typeof SHAPED_REVERB_PARAMS>

/** A reverb whose level follows a drawn shape instead of dying away: it can hold and stop dead, rise backwards into a cut, swell and fade, fall in a straight line or breathe in waves. */
export function createShapedReverb(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof SHAPED_REVERB_PARAMS> = {},
): Promise<ShapedReverb> {
  return WasmDevice.create(context, SHAPED_REVERB_DEVICE, options)
}
