// GENERATED by scripts/gen-devices.mjs from cpp/devices/shimmer/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const SHIMMER_PARAMS = {
  mix: {
    id: 0,
    name: 'Mix',
    min: 0,
    max: 1,
    default: 0.4,
    taper: 'linear',
    unit: '',
    description: 'Balance between the dry signal and the reverb. Fully up is the reverb alone.',
  },
  decay: {
    id: 1,
    name: 'Decay',
    min: 0.5,
    max: 30,
    default: 8,
    taper: 'log',
    unit: 's',
    description:
      'How long the tail rings. Bright sounds still fade sooner as Shimmer goes up, because they climb out of range.',
  },
  shimmer: {
    id: 2,
    name: 'Shimmer',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
    description:
      'How much of the tail goes through the pitch shifter on each pass. Zero is a plain reverb; higher lets more of it climb.',
  },
  interval: {
    id: 3,
    name: 'Interval',
    min: 0,
    max: 4,
    default: 0,
    taper: 'linear',
    unit: '',
    choices: ['Octave up', 'Fifth up', 'Octave and fifth', 'Octave down', 'Two octaves'],
    description:
      'The step the tail moves by on every pass. The upward ones climb until they fade out of the top; Octave down sinks lower each time.',
  },
  size: {
    id: 4,
    name: 'Size',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
    description:
      'How big the space sounds. Small packs the echoes close together; large spreads them out. Moving it bends the pitch of the tail.',
  },
  tone: {
    id: 5,
    name: 'Tone',
    min: 500,
    max: 16000,
    default: 6000,
    taper: 'log',
    unit: 'Hz',
    description:
      'Darkens the tail. Lower settings make the highs die away sooner and stop the shimmer from climbing as high.',
  },
  modulation: {
    id: 6,
    name: 'Modulation',
    min: 0,
    max: 1,
    default: 0.3,
    taper: 'linear',
    unit: '',
    description:
      'Slow drift of the delay times, which gives the tail a gentle chorus-like movement. At zero the tail is static.',
  },
  predelay: {
    id: 7,
    name: 'Pre-delay',
    min: 0,
    max: 500,
    default: 20,
    taper: 'linear',
    unit: 'ms',
    description:
      'The gap before the reverb starts, which keeps the start of the sound clear of its tail.',
  },
  lowCut: {
    id: 8,
    name: 'Low Cut',
    min: 20,
    max: 1000,
    default: 100,
    taper: 'log',
    unit: 'Hz',
    description:
      'Removes lows from the reverb so it does not cloud the bass. The dry signal is not touched.',
  },
  width: {
    id: 9,
    name: 'Width',
    min: 0,
    max: 1,
    default: 1,
    taper: 'linear',
    unit: '',
    description: 'Stereo width of the reverb only. Zero is a mono tail; full is the widest.',
  },
} as const satisfies Record<string, ParamSpec>

export type ShimmerParamName = keyof typeof SHIMMER_PARAMS

export const SHIMMER_DEVICE = defineWasmDevice({
  id: 'shimmer',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/shimmer.wasm', import.meta.url),
  params: SHIMMER_PARAMS,
})

export const SHIMMER_DESCRIPTOR = wasmDeviceDescriptor(SHIMMER_DEVICE, {
  name: 'Shimmer',
  category: 'reverb',
  description:
    'Long reverb with a pitch shifter in its feedback loop: every pass climbs an interval, so the tail rises into a soft choir-like halo.',
  presets: {
    'Rising choir': {
      mix: 0.4,
      decay: 8,
      shimmer: 0.5,
      interval: 0,
      size: 0.5,
      tone: 6000,
      modulation: 0.3,
    },
    Fifths: { decay: 10, shimmer: 0.4, interval: 1, size: 0.6, tone: 5000, modulation: 0.35 },
    'Organ loft': {
      decay: 14,
      shimmer: 0.35,
      interval: 2,
      size: 0.8,
      tone: 4200,
      modulation: 0.2,
      predelay: 40,
    },
    Undertow: {
      decay: 12,
      shimmer: 0.55,
      interval: 3,
      size: 0.9,
      tone: 3500,
      modulation: 0.4,
      lowCut: 45,
    },
    Glass: {
      mix: 0.3,
      decay: 6,
      shimmer: 0.3,
      interval: 4,
      size: 0.35,
      tone: 9000,
      modulation: 0.5,
      lowCut: 200,
    },
    'Plain hall': {
      mix: 0.3,
      decay: 3.2,
      shimmer: 0,
      size: 0.45,
      tone: 7000,
      modulation: 0.25,
      predelay: 15,
    },
    'Endless ascent': {
      mix: 0.5,
      decay: 30,
      shimmer: 0.75,
      interval: 0,
      size: 1,
      tone: 5000,
      modulation: 0.45,
      predelay: 60,
    },
  },
})

export type Shimmer = WasmDevice<typeof SHIMMER_PARAMS>

/** Long reverb with a pitch shifter in its feedback loop: every pass climbs an interval, so the tail rises into a soft choir-like halo. */
export function createShimmer(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof SHIMMER_PARAMS> = {},
): Promise<Shimmer> {
  return WasmDevice.create(context, SHIMMER_DEVICE, options)
}
