// GENERATED by scripts/gen-devices.mjs from cpp/devices/skipping-stone/device.json. Do not edit.

import { type DeviceMeterSpec } from '../../core/devices/Device'
import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const SKIPPING_STONE_PARAMS = {
  first: {
    id: 0,
    name: 'First',
    min: 20,
    max: 2000,
    default: 320,
    taper: 'log',
    unit: 'ms',
    description:
      'How long after the sound the first skip lands. Every later gap is measured from this one, so it sets the pace of the whole throw.',
  },
  bounce: {
    id: 1,
    name: 'Bounce',
    min: 0.5,
    max: 1.5,
    default: 0.8,
    taper: 'linear',
    unit: '',
    description:
      'The length of each gap against the one before. Below the middle the skips close up and hurry, above it they slow down and spread out.',
  },
  skips: {
    id: 2,
    name: 'Skips',
    min: 2,
    max: 16,
    default: 8,
    taper: 'linear',
    unit: '',
    step: 1,
    description:
      'How many times the stone lands. The throw ends sooner when the gaps get too short to tell apart or a landing would come too late.',
  },
  loss: {
    id: 3,
    name: 'Loss',
    min: 0,
    max: 12,
    default: 2.5,
    taper: 'linear',
    unit: 'dB',
    description:
      'How much softer each skip is than the one before. At zero every landing is as loud as the first.',
  },
  sink: {
    id: 4,
    name: 'Sink',
    min: 0,
    max: 1,
    default: 0.3,
    taper: 'linear',
    unit: '',
    description:
      'How much duller each skip is than the one before. Turned up, the late landings are only a low thud.',
  },
  drop: {
    id: 5,
    name: 'Drop',
    min: 0,
    max: 200,
    default: 0,
    taper: 'linear',
    unit: 'ct',
    description:
      'Lowers each skip in pitch a little more than the one before. Small amounts sag like a slowing record, and at the top each skip falls a whole tone.',
  },
  throw: {
    id: 6,
    name: 'Throw',
    min: -1,
    max: 1,
    default: 0.6,
    taper: 'linear',
    unit: '',
    description:
      'Carries the skips across the stereo field as they go. Turned right they travel left to right, turned left the other way, and in the middle they stay put.',
  },
  ripple: {
    id: 7,
    name: 'Ripple',
    min: 0,
    max: 1,
    default: 0.35,
    taper: 'linear',
    unit: '',
    description:
      'Blurs the skips into rings, a little more with each one. The first landing stays sharp and the last ones spread into a wash.',
  },
  again: {
    id: 8,
    name: 'Again',
    min: 0,
    max: 0.95,
    default: 0,
    taper: 'linear',
    unit: '',
    description:
      'Throws the stone again from where it stopped, this much softer each time. Turned up, whole throws keep coming, each duller and lower than the last.',
  },
  mix: {
    id: 9,
    name: 'Mix',
    min: 0,
    max: 1,
    default: 0.35,
    taper: 'linear',
    unit: '',
    description: 'Balance between the dry signal and the skips.',
  },
} as const satisfies Record<string, ParamSpec>

export type SkippingStoneParamName = keyof typeof SKIPPING_STONE_PARAMS

export const SKIPPING_STONE_METERS = {
  level: { id: 0, name: 'Thrown level', unit: '', display: true },
  clock: { id: 1, name: 'Running time', unit: '', display: true },
} as const satisfies Record<string, DeviceMeterSpec>

export const SKIPPING_STONE_DEVICE = defineWasmDevice({
  id: 'skipping-stone',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/skipping-stone.wasm', import.meta.url),
  params: SKIPPING_STONE_PARAMS,
  meters: SKIPPING_STONE_METERS,
})

export const SKIPPING_STONE_DESCRIPTOR = wasmDeviceDescriptor(SKIPPING_STONE_DEVICE, {
  name: 'Skipping Stone',
  category: 'delay',
  description:
    'Echoes that land like a stone skipping over water: closer and closer together, each softer and duller, crossing from one side to the other. Or the other way, slowing down and spreading out.',
  presets: {
    'Skipping stone': {
      first: 320,
      bounce: 0.8,
      skips: 8,
      loss: 2.5,
      sink: 0.3,
      drop: 0,
      throw: 0.6,
      ripple: 0.35,
      again: 0,
      mix: 0.35,
    },
    'Soft pebble': {
      first: 180,
      bounce: 0.85,
      skips: 6,
      loss: 4,
      sink: 0.5,
      throw: 0.3,
      ripple: 0.6,
      mix: 0.2,
    },
    'Slowing bounces': {
      first: 120,
      bounce: 1.25,
      skips: 9,
      loss: 2,
      sink: 0.25,
      throw: 0.8,
      ripple: 0.3,
      mix: 0.35,
    },
    'Falling steps': {
      first: 260,
      bounce: 1,
      skips: 8,
      loss: 1.5,
      sink: 0.1,
      drop: 100,
      ripple: 0.1,
      mix: 0.4,
    },
    'Sinking away': {
      first: 400,
      bounce: 0.9,
      skips: 12,
      loss: 3,
      sink: 0.8,
      drop: 12,
      ripple: 0.5,
      mix: 0.4,
    },
    'Ball on glass': {
      first: 240,
      bounce: 0.62,
      skips: 16,
      loss: 1,
      sink: 0,
      throw: 0,
      ripple: 0,
      mix: 0.4,
    },
    'Wide rings': {
      first: 300,
      bounce: 0.9,
      skips: 10,
      loss: 1.5,
      sink: 0.2,
      throw: 1,
      ripple: 1,
      mix: 0.45,
    },
    'Thrown again': { first: 350, bounce: 0.75, skips: 6, loss: 2, again: 0.7, mix: 0.4 },
    'Long way out': {
      first: 900,
      bounce: 1.15,
      skips: 10,
      loss: 1.5,
      sink: 0.35,
      ripple: 0.5,
      again: 0.5,
      mix: 0.4,
    },
    'Nearly dry': { first: 280, bounce: 0.8, skips: 5, loss: 3, sink: 0.4, ripple: 0.5, mix: 0.12 },
    'Even steps': {
      first: 250,
      bounce: 1,
      skips: 8,
      loss: 2,
      sink: 0.15,
      throw: -0.8,
      ripple: 0,
      mix: 0.35,
    },
    'Two skips': {
      first: 140,
      bounce: 1.5,
      skips: 2,
      loss: 0,
      sink: 0,
      throw: 1,
      ripple: 0,
      mix: 0.4,
    },
    'Deep water': { first: 500, bounce: 0.85, skips: 12, loss: 2, sink: 1, ripple: 0.7, mix: 0.5 },
    'Endless descent': {
      first: 420,
      bounce: 0.9,
      skips: 5,
      loss: 1,
      sink: 0.2,
      drop: 50,
      ripple: 0.4,
      again: 0.85,
      mix: 0.4,
    },
    'Rain on the lake': {
      first: 60,
      bounce: 1.12,
      skips: 16,
      loss: 0.8,
      sink: 0.1,
      throw: 1,
      ripple: 0.25,
      mix: 0.35,
    },
    'Slow crossing': {
      first: 1400,
      bounce: 0.7,
      skips: 8,
      loss: 2,
      throw: 1,
      ripple: 0.6,
      again: 0.4,
      mix: 0.4,
    },
  },
})

export type SkippingStone = WasmDevice<typeof SKIPPING_STONE_PARAMS>

/** Echoes that land like a stone skipping over water: closer and closer together, each softer and duller, crossing from one side to the other. Or the other way, slowing down and spreading out. */
export function createSkippingStone(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof SKIPPING_STONE_PARAMS> = {},
): Promise<SkippingStone> {
  return WasmDevice.create(context, SKIPPING_STONE_DEVICE, options)
}
