// GENERATED by scripts/gen-devices.mjs from cpp/devices/spectral-blur/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const SPECTRAL_BLUR_PARAMS = {
  blur: {
    id: 0,
    name: 'Blur',
    min: 0,
    max: 1,
    default: 0.6,
    taper: 'linear',
    unit: '',
    description:
      'How long each frequency hangs after the sound has moved on. Low is a short haze; high sustains it for many seconds.',
  },
  smear: {
    id: 1,
    name: 'Smear',
    min: 0,
    max: 1,
    default: 0.7,
    taper: 'linear',
    unit: '',
    description:
      'Scrambles the phase of every frequency, which dissolves attacks into a diffuse wash. At zero the phases are left as they are.',
  },
  freeze: {
    id: 2,
    name: 'Freeze',
    min: 0,
    max: 1,
    default: 0,
    taper: 'linear',
    unit: '',
    choices: ['Off', 'On'],
    description:
      'On holds the spectrum of the moment and ignores new input. The held sound keeps drifting a little, so it is a slow drone and not a loop.',
  },
  tilt: {
    id: 3,
    name: 'Tilt',
    min: -6,
    max: 6,
    default: -0.5,
    taper: 'linear',
    unit: 'dB/oct',
    description:
      'Leans the tone of the wet signal. Negative values are darker and bassier, positive values brighter and thinner.',
  },
  lowCut: {
    id: 4,
    name: 'Low Cut',
    min: 20,
    max: 2000,
    default: 20,
    taper: 'log',
    unit: 'Hz',
    description: 'Removes lows from the wet signal. At its lowest setting it is off.',
  },
  highCut: {
    id: 5,
    name: 'High Cut',
    min: 500,
    max: 20000,
    default: 12000,
    taper: 'log',
    unit: 'Hz',
    description: 'Removes highs from the wet signal. At its highest setting it is off.',
  },
  shimmer: {
    id: 6,
    name: 'Shimmer',
    min: 0,
    max: 1,
    default: 0.15,
    taper: 'linear',
    unit: '',
    description:
      'Adds a copy of the blurred sound an octave higher. Low is a faint halo; high is a bright octave over everything.',
  },
  width: {
    id: 7,
    name: 'Width',
    min: 0,
    max: 1,
    default: 1,
    taper: 'linear',
    unit: '',
    description:
      'Makes the smearing differ between left and right, which widens the wash. At zero a mono input stays mono. Needs Smear or Freeze to act.',
  },
  mix: {
    id: 8,
    name: 'Mix',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
    description: 'Balance between the dry signal and the blurred one.',
  },
} as const satisfies Record<string, ParamSpec>

export type SpectralBlurParamName = keyof typeof SPECTRAL_BLUR_PARAMS

export const SPECTRAL_BLUR_DEVICE = defineWasmDevice({
  id: 'spectral-blur',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/spectral-blur.wasm', import.meta.url),
  params: SPECTRAL_BLUR_PARAMS,
  latencySamples: () => 2304,
})

export const SPECTRAL_BLUR_DESCRIPTOR = wasmDeviceDescriptor(SPECTRAL_BLUR_DEVICE, {
  name: 'Spectral Blur',
  category: 'texture',
  description:
    'Smears and freezes the spectrum: every frequency hangs for as long as Blur says, phases dissolve into a diffuse wash, and Freeze holds the moment as a slowly living drone.',
  presets: {
    'Hanging mist': {
      blur: 0.6,
      smear: 0.7,
      tilt: -0.5,
      lowCut: 20,
      highCut: 12000,
      shimmer: 0.15,
      width: 1,
      mix: 0.5,
    },
    'Clean sustain': {
      blur: 0.7,
      smear: 0,
      tilt: 0,
      lowCut: 20,
      highCut: 20000,
      shimmer: 0,
      width: 0,
      mix: 0.45,
    },
    'Slow dissolve': {
      blur: 0.88,
      smear: 1,
      tilt: -1.5,
      lowCut: 80,
      highCut: 8000,
      shimmer: 0.1,
      width: 1,
      mix: 0.7,
    },
    'Glass halo': {
      blur: 0.55,
      smear: 0.5,
      tilt: 1.5,
      lowCut: 250,
      highCut: 16000,
      shimmer: 0.7,
      width: 1,
      mix: 0.45,
    },
    'Dark water': {
      blur: 0.8,
      smear: 0.85,
      tilt: -3,
      lowCut: 20,
      highCut: 2500,
      shimmer: 0,
      width: 0.8,
      mix: 0.6,
    },
    Whisper: {
      blur: 0.15,
      smear: 1,
      tilt: 0,
      lowCut: 150,
      highCut: 14000,
      shimmer: 0.25,
      width: 1,
      mix: 1,
    },
    Endless: {
      blur: 1,
      smear: 0.9,
      tilt: -1,
      lowCut: 40,
      highCut: 10000,
      shimmer: 0.3,
      width: 1,
      mix: 0.75,
    },
  },
})

export type SpectralBlur = WasmDevice<typeof SPECTRAL_BLUR_PARAMS>

/** Smears and freezes the spectrum: every frequency hangs for as long as Blur says, phases dissolve into a diffuse wash, and Freeze holds the moment as a slowly living drone. */
export function createSpectralBlur(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof SPECTRAL_BLUR_PARAMS> = {},
): Promise<SpectralBlur> {
  return WasmDevice.create(context, SPECTRAL_BLUR_DEVICE, options)
}
