// GENERATED by scripts/gen-devices.mjs from cpp/devices/stereo-detune/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const STEREO_DETUNE_PARAMS = {
  detune: {
    id: 0,
    name: 'Detune',
    min: 0,
    max: 50,
    default: 9,
    taper: 'linear',
    unit: 'ct',
    description:
      'How far the two copies are tuned from the dry sound, the left sharp and the right flat. A little widens softly; more beats against the dry sound and turns sour.',
  },
  delay: {
    id: 1,
    name: 'Delay',
    min: 12,
    max: 60,
    default: 14,
    taper: 'linear',
    unit: 'ms',
    description:
      'How far behind the dry sound the copies sit, the right one a little later than the left. Short settings fuse with the source; long ones are heard as a doubled take.',
  },
  drift: {
    id: 2,
    name: 'Drift',
    min: 0,
    max: 1,
    default: 0.15,
    taper: 'linear',
    unit: '',
    description:
      'Lets the tuning and timing of each copy wander slowly and at random. At zero the copies hold perfectly still; higher settings sway like a worn tape.',
  },
  feedback: {
    id: 3,
    name: 'Feedback',
    min: 0,
    max: 0.7,
    default: 0,
    taper: 'linear',
    unit: '',
    description:
      'Feeds each copy back into itself, so it is detuned again on every pass: the left side climbs and the right side sinks as the repeats blur and fade.',
  },
  focus: {
    id: 4,
    name: 'Focus',
    min: 20,
    max: 1000,
    default: 180,
    taper: 'log',
    unit: 'Hz',
    description:
      'Everything below this stays dry and where it was, so the bass keeps its weight. Raise it to widen only the upper part of the sound.',
  },
  tone: {
    id: 5,
    name: 'Tone',
    min: 1000,
    max: 18000,
    default: 10000,
    taper: 'log',
    unit: 'Hz',
    description:
      'Rolls the treble off the two copies. Lower settings tuck them behind the dry sound as a soft halo; with Feedback up, each repeat gets darker.',
  },
  width: {
    id: 6,
    name: 'Width',
    min: 0,
    max: 1,
    default: 1,
    taper: 'linear',
    unit: '',
    description:
      'How far apart the two copies sit. At full they are hard left and right; at zero both are in the centre and the effect thickens without widening.',
  },
  mix: {
    id: 7,
    name: 'Mix',
    min: 0,
    max: 1,
    default: 0.36,
    taper: 'linear',
    unit: '',
    description:
      'Balance between the dry sound and the two copies. The sound below Focus stays at full level wherever this is set.',
  },
} as const satisfies Record<string, ParamSpec>

export type StereoDetuneParamName = keyof typeof STEREO_DETUNE_PARAMS

export const STEREO_DETUNE_DEVICE = defineWasmDevice({
  id: 'stereo-detune',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/stereo-detune.wasm', import.meta.url),
  params: STEREO_DETUNE_PARAMS,
})

export const STEREO_DETUNE_DESCRIPTOR = wasmDeviceDescriptor(STEREO_DETUNE_DEVICE, {
  name: 'Stereo Detune',
  category: 'spatial',
  description:
    'A copy a few cents sharp on the left and a few cents flat on the right, each a few milliseconds late: makes one source wide and thick with no chorus sweep.',
  presets: {
    Classic: {
      detune: 9,
      delay: 14,
      drift: 0.15,
      feedback: 0,
      focus: 180,
      tone: 10000,
      width: 1,
      mix: 0.36,
    },
    'Soft halo': { detune: 4, delay: 12, drift: 0.1, tone: 6000, mix: 0.28 },
    Doubled: { detune: 20, delay: 32, drift: 0.25, tone: 8000, mix: 0.38 },
    'Piano haze': { detune: 12, delay: 18, drift: 0.45, focus: 250, tone: 3500, mix: 0.38 },
    Wider: { detune: 14, delay: 20, drift: 0.2, focus: 120, tone: 18000, mix: 0.43 },
    Spiral: {
      detune: 14,
      delay: 45,
      drift: 0.2,
      feedback: 0.62,
      focus: 300,
      tone: 5000,
      mix: 0.35,
    },
    Cloud: { detune: 6, delay: 22, drift: 0.3, feedback: 0.5, focus: 400, tone: 9000, mix: 0.36 },
    Seasick: { detune: 40, delay: 24, drift: 0.9, tone: 6000, mix: 0.4 },
    Thickener: { detune: 7, delay: 12, drift: 0.1, width: 0, mix: 0.28 },
    'Faint width': { detune: 8, delay: 13, drift: 0.1, tone: 3000, mix: 0.14 },
    'Top only': { detune: 10, delay: 12, drift: 0.15, focus: 1000, tone: 18000, mix: 0.5 },
    Shadow: { detune: 16, delay: 28, drift: 0.2, feedback: 0.3, tone: 1500, mix: 0.5 },
    'Late copy': { detune: 5, delay: 60, drift: 0.1, tone: 12000, mix: 0.4 },
    Drifting: { detune: 0, delay: 25, drift: 0.6, tone: 10000, mix: 0.45 },
    Melting: { detune: 50, delay: 30, drift: 0.3, feedback: 0.7, focus: 400, tone: 2500, mix: 0.4 },
    'Wet only': { detune: 12, delay: 16, drift: 0.2, focus: 150, tone: 12000, mix: 1 },
  },
  formerPresets: {
    'Classic wide': 'Classic',
    'Subtle halo': 'Soft halo',
    'Thick double': 'Doubled',
    'Treated piano': 'Piano haze',
    'Wide open': 'Wider',
    'Detune cloud': 'Cloud',
    'Centre thickener': 'Thickener',
    'Top end only': 'Top only',
    'Dark shadow': 'Shadow',
    'Late double': 'Late copy',
    'Drifting double': 'Drifting',
    'Melting repeats': 'Melting',
    'Copies only': 'Wet only',
  },
})

export type StereoDetune = WasmDevice<typeof STEREO_DETUNE_PARAMS>

/** A copy a few cents sharp on the left and a few cents flat on the right, each a few milliseconds late: makes one source wide and thick with no chorus sweep. */
export function createStereoDetune(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof STEREO_DETUNE_PARAMS> = {},
): Promise<StereoDetune> {
  return WasmDevice.create(context, STEREO_DETUNE_DEVICE, options)
}
