// GENERATED by scripts/gen-devices.mjs from cpp/devices/string-machine/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const STRING_MACHINE_PARAMS = {
  attack: { id: 0, name: 'Attack', min: 0.005, max: 8, default: 0.6, taper: 'log', unit: 's' },
  release: { id: 1, name: 'Release', min: 0.05, max: 12, default: 1.8, taper: 'log', unit: 's' },
  low: { id: 2, name: 'Cello', min: 0, max: 1, default: 0.4, taper: 'linear', unit: '' },
  high: { id: 3, name: 'Violin', min: 0, max: 1, default: 0.35, taper: 'linear', unit: '' },
  tone: { id: 4, name: 'Tone', min: 200, max: 12000, default: 3200, taper: 'log', unit: 'Hz' },
  ensemble: { id: 5, name: 'Ensemble', min: 0, max: 1, default: 0.8, taper: 'linear', unit: '' },
  speed: { id: 6, name: 'Speed', min: 0.25, max: 2, default: 1, taper: 'linear', unit: '' },
  drift: { id: 7, name: 'Drift', min: 0, max: 1, default: 0.3, taper: 'linear', unit: '' },
  width: { id: 8, name: 'Width', min: 0, max: 1, default: 0.8, taper: 'linear', unit: '' },
  volume: { id: 9, name: 'Volume', min: -48, max: 6, default: -9, taper: 'linear', unit: 'dB' },
} as const satisfies Record<string, ParamSpec>

export type StringMachineParamName = keyof typeof STRING_MACHINE_PARAMS

export const STRING_MACHINE_DEVICE = defineWasmDevice({
  id: 'string-machine',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/string-machine.wasm', import.meta.url),
  params: STRING_MACHINE_PARAMS,
})

export const STRING_MACHINE_DESCRIPTOR = wasmDeviceDescriptor(STRING_MACHINE_DEVICE, {
  name: 'String Machine',
  category: 'instrument',
  description:
    'Seventies string ensemble: three octaves of sawtooth per key through a tone filter and a three-phase bucket-brigade ensemble chorus.',
  presets: {
    Solina: {
      attack: 0.6,
      release: 1.8,
      low: 0.4,
      high: 0.35,
      tone: 3200,
      ensemble: 0.8,
      speed: 1,
      drift: 0.3,
    },
    'Slow strings': {
      attack: 3.5,
      release: 6,
      low: 0.6,
      high: 0.2,
      tone: 1800,
      ensemble: 0.9,
      speed: 0.7,
      drift: 0.5,
    },
    Glass: {
      attack: 1.2,
      release: 4,
      low: 0,
      high: 1,
      tone: 7000,
      ensemble: 0.7,
      speed: 1.3,
      drift: 0.2,
    },
    Cellos: {
      attack: 0.9,
      release: 2.5,
      low: 1,
      high: 0,
      tone: 1200,
      ensemble: 0.6,
      speed: 0.8,
      drift: 0.4,
    },
    'Dry saws': {
      attack: 0.02,
      release: 0.4,
      low: 0.3,
      high: 0.3,
      tone: 6000,
      ensemble: 0,
      drift: 0.1,
      width: 0,
    },
  },
})

export type StringMachine = WasmDevice<typeof STRING_MACHINE_PARAMS>

/** Seventies string ensemble: three octaves of sawtooth per key through a tone filter and a three-phase bucket-brigade ensemble chorus. Play it through `NoteDevice`: `noteOn(id, frequency, gain)` / `noteOff(id)`. */
export function createStringMachine(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof STRING_MACHINE_PARAMS> = {},
): Promise<StringMachine> {
  return WasmDevice.create(context, STRING_MACHINE_DEVICE, options)
}
