// GENERATED by scripts/gen-devices.mjs from cpp/devices/sub-bass/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const SUB_BASS_PARAMS = {
  shape: {
    id: 0,
    name: 'Shape',
    min: 0,
    max: 1,
    default: 0.15,
    taper: 'linear',
    unit: '',
    description:
      'Bends the pure tone toward a rounder, squarer wave: fuller and more hollow, without getting louder and without losing any of the bottom.',
  },
  harmonics: {
    id: 1,
    name: 'Harmonics',
    min: 0,
    max: 1,
    default: 0.2,
    taper: 'linear',
    unit: '',
    description:
      'Adds the octave and the fifth above it on top of the note, so it is still heard on speakers too small to play its bottom. The low tone itself stays as loud as it was.',
  },
  drop: {
    id: 2,
    name: 'Drop',
    min: 0,
    max: 36,
    default: 7,
    taper: 'linear',
    unit: 'st',
    description:
      'How far above its note each strike starts before it falls onto it. A little is a soft knock at the start; a lot is a boom or a dive. A note slid to from a held one does not drop.',
  },
  fall: {
    id: 3,
    name: 'Fall',
    min: 5,
    max: 800,
    default: 40,
    taper: 'log',
    unit: 'ms',
    description:
      'How long the pitch takes to fall onto the note. Short is a thump, long is a slow dive that lands exactly in tune.',
  },
  attack: {
    id: 4,
    name: 'Attack',
    min: 0.001,
    max: 3,
    default: 0.004,
    taper: 'log',
    unit: 's',
    description: 'How quickly the note comes up, from an immediate start to a slow swell.',
  },
  decay: {
    id: 5,
    name: 'Decay',
    min: 0.05,
    max: 20,
    default: 20,
    taper: 'log',
    unit: 's',
    description:
      'How long a held note takes to die away, from a short knock to a ring of many seconds. At the very top the note holds for as long as the key is down.',
  },
  release: {
    id: 6,
    name: 'Release',
    min: 0.02,
    max: 8,
    default: 0.4,
    taper: 'log',
    unit: 's',
    description:
      'How long the note takes to fade once the key is let go, from a quick stop to a long tail.',
  },
  drive: {
    id: 7,
    name: 'Drive',
    min: 0,
    max: 1,
    default: 0.15,
    taper: 'linear',
    unit: '',
    description:
      'Soft saturation that thickens the tone and gives it an edge without making it louder. It bites hardest on loud notes and at the start of a note, and lets the tail go clean.',
  },
  glide: {
    id: 8,
    name: 'Glide',
    min: 0,
    max: 2,
    default: 0.06,
    taper: 'linear',
    unit: 's',
    description:
      'Time the pitch takes to slide to a new key pressed while another is still held. Keys played apart start on pitch.',
  },
  volume: {
    id: 9,
    name: 'Volume',
    min: -48,
    max: 6,
    default: -9,
    taper: 'linear',
    unit: 'dB',
    description:
      'Output level of the instrument. A soft clip after it catches peaks at high settings.',
  },
} as const satisfies Record<string, ParamSpec>

export type SubBassParamName = keyof typeof SUB_BASS_PARAMS

export const SUB_BASS_DEVICE = defineWasmDevice({
  id: 'sub-bass',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/sub-bass.wasm', import.meta.url),
  params: SUB_BASS_PARAMS,
})

export const SUB_BASS_DESCRIPTOR = wasmDeviceDescriptor(SUB_BASS_DEVICE, {
  name: 'Sub Bass',
  category: 'instrument',
  description:
    'One-voice deep sine bass: a pure low tone that can start above its note and fall onto it, with added harmonics so small speakers find it, a soft drive and a long fade, for booms, held subs and slow soft pulses.',
  presets: {
    'Soft sub': {
      shape: 0.15,
      harmonics: 0.2,
      drop: 7,
      fall: 40,
      attack: 0.004,
      decay: 20,
      release: 0.4,
      drive: 0.15,
      glide: 0.06,
    },
    'Pure sine': {
      shape: 0,
      harmonics: 0,
      drop: 0,
      attack: 0.02,
      decay: 20,
      release: 0.6,
      drive: 0,
      glide: 0.08,
    },
    'Long boom': {
      shape: 0.1,
      harmonics: 0.25,
      drop: 24,
      fall: 220,
      attack: 0.002,
      decay: 7,
      release: 3,
      drive: 0.3,
    },
    'Short thump': {
      shape: 0.05,
      harmonics: 0.3,
      drop: 14,
      fall: 28,
      attack: 0.001,
      decay: 0.28,
      release: 0.08,
      drive: 0.35,
      glide: 0,
    },
    'Small speaker hum': {
      shape: 0.85,
      harmonics: 0.8,
      drop: 0,
      attack: 0.03,
      decay: 20,
      release: 0.5,
      drive: 0.25,
      volume: -11,
    },
    'Slow swell': {
      shape: 0.2,
      harmonics: 0.15,
      drop: 0,
      attack: 2,
      decay: 20,
      release: 5,
      drive: 0.1,
      glide: 0.3,
      volume: -6,
    },
    'Gliding sub': {
      shape: 0.25,
      harmonics: 0.3,
      drop: 0,
      attack: 0.02,
      decay: 20,
      release: 0.5,
      drive: 0.2,
      glide: 0.45,
    },
    'Driven pulse': {
      shape: 0.3,
      harmonics: 0.4,
      drop: 4,
      fall: 20,
      attack: 0.002,
      decay: 0.7,
      release: 0.15,
      drive: 0.8,
      glide: 0.03,
    },
    'Deep dive': {
      shape: 0.1,
      harmonics: 0.15,
      drop: 36,
      fall: 800,
      attack: 0.005,
      decay: 9,
      release: 4,
      drive: 0.2,
    },
    'Soft pulse': {
      shape: 0.1,
      harmonics: 0.1,
      drop: 0,
      attack: 0.08,
      decay: 1.6,
      release: 0.9,
      drive: 0,
    },
    'Dark drone': {
      shape: 0,
      harmonics: 0.05,
      drop: 0,
      attack: 1.2,
      decay: 20,
      release: 8,
      drive: 0,
      glide: 1.5,
    },
    'Pedal tone': {
      shape: 0.2,
      harmonics: 1,
      drop: 0,
      attack: 0.015,
      decay: 20,
      release: 0.12,
      drive: 0,
      glide: 0.02,
      volume: -11,
    },
    'Dub weight': {
      shape: 0.35,
      harmonics: 0.15,
      drop: 2,
      fall: 60,
      attack: 0.008,
      decay: 20,
      release: 0.25,
      drive: 0.45,
      glide: 0.12,
    },
    'Hard knock': {
      shape: 0,
      harmonics: 0.1,
      drop: 30,
      fall: 55,
      attack: 0.001,
      decay: 0.4,
      release: 0.1,
      drive: 0.55,
      glide: 0,
    },
    'Falling sigh': {
      shape: 0.05,
      harmonics: 0.1,
      drop: 12,
      fall: 600,
      attack: 0.6,
      decay: 5,
      release: 3,
      drive: 0,
    },
    'Hollow square': {
      shape: 1,
      harmonics: 0,
      drop: 0,
      attack: 0.01,
      decay: 20,
      release: 0.2,
      drive: 0.6,
      glide: 0.05,
    },
  },
})

export type SubBass = WasmDevice<typeof SUB_BASS_PARAMS>

/** One-voice deep sine bass: a pure low tone that can start above its note and fall onto it, with added harmonics so small speakers find it, a soft drive and a long fade, for booms, held subs and slow soft pulses. Play it through `NoteDevice`: `noteOn(id, frequency, gain)` / `noteOff(id)`. */
export function createSubBass(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof SUB_BASS_PARAMS> = {},
): Promise<SubBass> {
  return WasmDevice.create(context, SUB_BASS_DEVICE, options)
}
