// GENERATED by scripts/gen-devices.mjs from cpp/devices/sustainer/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const SUSTAINER_PARAMS = {
  mode: {
    id: 0,
    name: 'Mode',
    min: 0,
    max: 2,
    default: 0,
    taper: 'linear',
    unit: '',
    choices: ['Auto', 'Layer', 'Latch'],
    description:
      'Auto catches every new note or chord and lets it replace what was held. Layer adds each new one on top of the old ones, so harmony piles up. Latch catches nothing until Hold is switched on.',
  },
  hold: {
    id: 1,
    name: 'Hold',
    min: 0,
    max: 1,
    default: 0,
    taper: 'linear',
    unit: '',
    choices: ['Off', 'On'],
    description:
      'In Auto and Layer, On keeps what is held and stops listening for new notes, so you can play over it. In Latch, On catches the sound of that moment and Off lets it go.',
  },
  sensitivity: {
    id: 2,
    name: 'Sensitivity',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
    description:
      'How easily a new note is caught. Low needs a loud, clear attack; high also catches soft notes and gentle changes of harmony.',
  },
  attack: {
    id: 3,
    name: 'Attack',
    min: 0.01,
    max: 5,
    default: 0.25,
    taper: 'log',
    unit: 's',
    description:
      'How slowly the held sound rises under the note you played. Short takes over at once; long swells in like bowed strings.',
  },
  decay: {
    id: 4,
    name: 'Decay',
    min: 0.2,
    max: 60,
    default: 8,
    taper: 'log',
    unit: 's',
    description:
      'How long the held sound takes to die away once you stop playing. All the way up it never fades.',
  },
  glide: {
    id: 5,
    name: 'Glide',
    min: 0.02,
    max: 5,
    default: 0.4,
    taper: 'log',
    unit: 's',
    description:
      'How long the old held sound takes to give way to a new one. Short changes chord at once; long lets one harmony melt into the next.',
  },
  motion: {
    id: 6,
    name: 'Motion',
    min: 0,
    max: 1,
    default: 0.35,
    taper: 'linear',
    unit: '',
    description:
      'How much the held sound moves. At zero it is perfectly still, like an organ pipe; higher, every overtone drifts and shimmers on its own, differently left and right.',
  },
  ensemble: {
    id: 7,
    name: 'Ensemble',
    min: 0,
    max: 1,
    default: 0.2,
    taper: 'linear',
    unit: '',
    description:
      'Adds two slightly detuned copies of the held sound, one to each side, for the width and slow beating of a string section.',
  },
  tone: {
    id: 8,
    name: 'Tone',
    min: -1,
    max: 1,
    default: 0,
    taper: 'linear',
    unit: '',
    description:
      'Tilts the held sound. Left of centre is darker and rounder, right is brighter and airier.',
  },
  lowCut: {
    id: 9,
    name: 'Low Cut',
    min: 20,
    max: 500,
    default: 60,
    taper: 'log',
    unit: 'Hz',
    description:
      'Removes lows from the held sound so it does not cloud the bass of what you play over it.',
  },
  mix: {
    id: 10,
    name: 'Mix',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
    description: 'Balance between what you play and the held sound.',
  },
} as const satisfies Record<string, ParamSpec>

export type SustainerParamName = keyof typeof SUSTAINER_PARAMS

export const SUSTAINER_DEVICE = defineWasmDevice({
  id: 'sustainer',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/sustainer.wasm', import.meta.url),
  params: SUSTAINER_PARAMS,
})

export const SUSTAINER_DESCRIPTOR = wasmDeviceDescriptor(SUSTAINER_DEVICE, {
  name: 'Sustain',
  category: 'texture',
  description:
    'Catches what you play and holds it as an endless, even pad: play a chord and it hangs there, play the next and it glides over.',
  presets: {
    'Sustain pedal': { mode: 0 },
    'Slow strings': { attack: 2, ensemble: 0.8 },
    'Stacked harmony': { mode: 1, decay: 20 },
    'Frozen moment': { mode: 2 },
    'Glass organ': { motion: 0, tone: 0.5 },
    'Dark bed': { tone: -0.7, decay: 40 },
  },
})

export type Sustainer = WasmDevice<typeof SUSTAINER_PARAMS>

/** Catches what you play and holds it as an endless, even pad: play a chord and it hangs there, play the next and it glides over. */
export function createSustainer(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof SUSTAINER_PARAMS> = {},
): Promise<Sustainer> {
  return WasmDevice.create(context, SUSTAINER_DEVICE, options)
}
