// GENERATED by scripts/gen-devices.mjs from cpp/devices/sympathetic/device.json. Do not edit.

import { type DeviceMeterSpec } from '../../core/devices/Device'
import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const SYMPATHETIC_PARAMS = {
  root: {
    id: 0,
    name: 'Root',
    min: 0,
    max: 11,
    default: 0,
    taper: 'linear',
    unit: '',
    choices: ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'],
    description:
      'The key the strings are tuned in. Match it to the key of the music so the strings ring with the notes you play.',
  },
  mode: {
    id: 1,
    name: 'Mode',
    min: 0,
    max: 2,
    default: 0,
    taper: 'linear',
    unit: '',
    choices: ['Major', 'Minor', 'Learn'],
    description:
      'Major or Minor picks the scale the strings are tuned to. Learn builds the scale from the notes it hears you play.',
  },
  sympathy: {
    id: 2,
    name: 'Sympathy',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
    description:
      'How hard the input drives the strings. Low is a faint halo behind the notes; high makes the strings ring out loudly.',
  },
  strings: {
    id: 3,
    name: 'Strings',
    min: 0,
    max: 12,
    default: 4,
    taper: 'linear',
    unit: '',
    choices: ['4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16'],
    description:
      'How many strings ring. The first few are the root, octave, fifth and third. More add the other scale notes and higher octaves.',
  },
  decay: {
    id: 4,
    name: 'Decay',
    min: 0.5,
    max: 10,
    default: 3,
    taper: 'log',
    unit: 's',
    description:
      'How long the strings ring after the sound that set them off. The highest strings die away sooner.',
  },
  mix: {
    id: 5,
    name: 'Mix',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
    description:
      'Balance between the dry signal and the ringing strings. Fully up is the strings alone.',
  },
  width: {
    id: 6,
    name: 'Width',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
    description:
      'Spreads the strings across the stereo field. Zero puts them all in the centre; higher fans them out and widens the result.',
  },
} as const satisfies Record<string, ParamSpec>

export type SympatheticParamName = keyof typeof SYMPATHETIC_PARAMS

export const SYMPATHETIC_METERS = {
  strings1: { id: 0, name: 'Strings 1 to 4', unit: '', display: true },
  strings2: { id: 1, name: 'Strings 5 to 8', unit: '', display: true },
  strings3: { id: 2, name: 'Strings 9 to 12', unit: '', display: true },
  strings4: { id: 3, name: 'Strings 13 to 16', unit: '', display: true },
  note: { id: 4, name: 'Note heard', unit: '', display: true },
  scale: { id: 5, name: 'Scale in use', unit: '', display: true },
} as const satisfies Record<string, DeviceMeterSpec>

export const SYMPATHETIC_DEVICE = defineWasmDevice({
  id: 'sympathetic',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/sympathetic.wasm', import.meta.url),
  params: SYMPATHETIC_PARAMS,
  meters: SYMPATHETIC_METERS,
})

export const SYMPATHETIC_DESCRIPTOR = wasmDeviceDescriptor(SYMPATHETIC_DEVICE, {
  name: 'Sympathetic',
  category: 'reverb',
  description:
    'Harmonic reverb: a bank of tuned strings that ring in sympathy with the notes you play, like a piano with the sustain pedal held or the drone strings of a sitar.',
  presets: {
    'Piano pedal': { root: 0, mode: 0, sympathy: 0.5, strings: 4, decay: 3, mix: 0.5, width: 0.5 },
    'Sitar drone': { root: 2, mode: 0, sympathy: 0.8, strings: 9, decay: 6, mix: 0.4, width: 0.35 },
    'Minor strings': {
      root: 9,
      mode: 1,
      sympathy: 0.6,
      strings: 8,
      decay: 4,
      mix: 0.45,
      width: 0.7,
    },
    'Open triad': { root: 7, mode: 0, sympathy: 0.7, strings: 0, decay: 5, mix: 0.4, width: 0.3 },
    'Glass harp': { root: 5, mode: 0, sympathy: 0.85, strings: 12, decay: 7, mix: 0.7, width: 0.9 },
    'Long ring': { root: 0, mode: 0, sympathy: 0.4, strings: 12, decay: 10, mix: 0.6, width: 0.85 },
    'Follow the tune': {
      root: 0,
      mode: 2,
      sympathy: 0.6,
      strings: 6,
      decay: 4,
      mix: 0.5,
      width: 0.6,
    },
    'Short halo': {
      root: 0,
      mode: 0,
      sympathy: 0.9,
      strings: 12,
      decay: 0.8,
      mix: 0.35,
      width: 0.6,
    },
    'Strings alone': { root: 4, mode: 1, sympathy: 0.5, strings: 12, decay: 8, mix: 1, width: 1 },
    'Faint ring': { root: 9, mode: 0, sympathy: 0.5, strings: 2, decay: 2, mix: 0.2, width: 0.5 },
    'Centre drone': { root: 9, mode: 1, sympathy: 0.3, strings: 0, decay: 10, mix: 0.35, width: 0 },
    'Minor wash': { root: 2, mode: 1, sympathy: 0.55, strings: 12, decay: 10, mix: 0.65, width: 1 },
    'Learn and hold': {
      root: 0,
      mode: 2,
      sympathy: 0.8,
      strings: 12,
      decay: 9,
      mix: 0.6,
      width: 0.9,
    },
    'Brief pluck': { root: 5, mode: 0, sympathy: 1, strings: 1, decay: 0.5, mix: 0.5, width: 0.4 },
    Hammered: { root: 4, mode: 1, sympathy: 0.9, strings: 5, decay: 1.5, mix: 0.5, width: 0.75 },
    'Echo the tune': {
      root: 0,
      mode: 2,
      sympathy: 0.7,
      strings: 0,
      decay: 1.5,
      mix: 0.4,
      width: 0.3,
    },
  },
  formerPresets: {
    'Long resonance': 'Long ring',
    'Follow the melody': 'Follow the tune',
    'Wide minor wash': 'Minor wash',
    'Hammered strings': 'Hammered',
  },
})

export type Sympathetic = WasmDevice<typeof SYMPATHETIC_PARAMS>

/** Harmonic reverb: a bank of tuned strings that ring in sympathy with the notes you play, like a piano with the sustain pedal held or the drone strings of a sitar. */
export function createSympathetic(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof SYMPATHETIC_PARAMS> = {},
): Promise<Sympathetic> {
  return WasmDevice.create(context, SYMPATHETIC_DEVICE, options)
}
