// GENERATED by scripts/gen-devices.mjs from cpp/devices/sympathetic/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const SYMPATHETIC_PARAMS = {
  root: {
    id: 0,
    name: 'Root',
    min: 0,
    max: 11,
    default: 0,
    taper: 'linear',
    unit: '',
    choices: ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'],
  },
  mode: {
    id: 1,
    name: 'Mode',
    min: 0,
    max: 2,
    default: 0,
    taper: 'linear',
    unit: '',
    choices: ['Major', 'Minor', 'Learn'],
  },
  sympathy: { id: 2, name: 'Sympathy', min: 0, max: 1, default: 0.5, taper: 'linear', unit: '' },
  strings: {
    id: 3,
    name: 'Strings',
    min: 0,
    max: 12,
    default: 4,
    taper: 'linear',
    unit: '',
    choices: ['4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16'],
  },
  decay: { id: 4, name: 'Decay', min: 0.5, max: 10, default: 3, taper: 'log', unit: 's' },
  mix: { id: 5, name: 'Mix', min: 0, max: 1, default: 0.5, taper: 'linear', unit: '' },
  width: { id: 6, name: 'Width', min: 0, max: 1, default: 0.5, taper: 'linear', unit: '' },
} as const satisfies Record<string, ParamSpec>

export type SympatheticParamName = keyof typeof SYMPATHETIC_PARAMS

export const SYMPATHETIC_DEVICE = defineWasmDevice({
  id: 'sympathetic',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/sympathetic.wasm', import.meta.url),
  params: SYMPATHETIC_PARAMS,
})

export const SYMPATHETIC_DESCRIPTOR = wasmDeviceDescriptor(SYMPATHETIC_DEVICE, {
  name: 'Sympathetic',
  category: 'reverb',
  description:
    'Harmonic reverb: a bank of tuned strings that ring in sympathy with the notes you play, like a piano with the sustain pedal held or the drone strings of a sitar.',
  presets: {
    'Piano pedal': { root: 0, mode: 0, sympathy: 0.5, strings: 4, decay: 3, mix: 0.5, width: 0.5 },
    'Sitar drone': { root: 2, mode: 0, sympathy: 0.8, strings: 9, decay: 6, mix: 0.4, width: 0.35 },
    'Minor strings': {
      root: 9,
      mode: 1,
      sympathy: 0.6,
      strings: 8,
      decay: 4,
      mix: 0.45,
      width: 0.7,
    },
    'Open triad': { root: 7, mode: 0, sympathy: 0.7, strings: 0, decay: 5, mix: 0.4, width: 0.3 },
    'Glass harp': { root: 5, mode: 0, sympathy: 0.85, strings: 12, decay: 7, mix: 0.7, width: 0.9 },
    'Long resonance': {
      root: 0,
      mode: 0,
      sympathy: 0.4,
      strings: 12,
      decay: 10,
      mix: 0.6,
      width: 0.85,
    },
    'Follow the melody': {
      root: 0,
      mode: 2,
      sympathy: 0.6,
      strings: 6,
      decay: 4,
      mix: 0.5,
      width: 0.6,
    },
    'Short halo': {
      root: 0,
      mode: 0,
      sympathy: 0.9,
      strings: 12,
      decay: 0.8,
      mix: 0.35,
      width: 0.6,
    },
  },
})

export type Sympathetic = WasmDevice<typeof SYMPATHETIC_PARAMS>

/** Harmonic reverb: a bank of tuned strings that ring in sympathy with the notes you play, like a piano with the sustain pedal held or the drone strings of a sitar. */
export function createSympathetic(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof SYMPATHETIC_PARAMS> = {},
): Promise<Sympathetic> {
  return WasmDevice.create(context, SYMPATHETIC_DEVICE, options)
}
