// GENERATED by scripts/gen-devices.mjs from cpp/devices/tamer/device.json. Do not edit.

import { type DeviceMeterSpec } from '../../core/devices/Device'
import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const TAMER_PARAMS = {
  depth: {
    id: 0,
    name: 'Depth',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
    description:
      'How much of what stands out is taken away. Low only touches the worst tones; all the way up levels every peak with the sound around it. Zero turns it off.',
  },
  sharpness: {
    id: 1,
    name: 'Sharpness',
    min: 0,
    max: 1,
    default: 0.6,
    taper: 'linear',
    unit: '',
    description:
      'How narrow the cuts are. Up picks out single ringing tones and leaves their neighbours; down evens out broad humps, more like a tone control.',
  },
  time: {
    id: 2,
    name: 'Time',
    min: 10,
    max: 1000,
    default: 60,
    taper: 'log',
    unit: 'ms',
    description:
      'How fast a cut comes in. Short catches the harsh start of a sound; long only acts on what stays. It lets go four times slower.',
  },
  from: {
    id: 3,
    name: 'From',
    min: 80,
    max: 2000,
    default: 120,
    taper: 'log',
    unit: 'Hz',
    description:
      'The bottom of the range that is worked on. Everything below is left alone, so raise it to keep the weight of a sound out of reach.',
  },
  to: {
    id: 4,
    name: 'To',
    min: 1000,
    max: 20000,
    default: 16000,
    taper: 'log',
    unit: 'Hz',
    description:
      'The top of the range that is worked on. Everything above is left alone, so lower it to keep the air of a sound out of reach.',
  },
  listen: {
    id: 5,
    name: 'Listen',
    min: 0,
    max: 1,
    default: 0,
    taper: 'linear',
    unit: '',
    choices: ['Off', 'On'],
    description:
      'On plays only what is being taken away, so the settings can be tuned by ear. Turn it off again to hear the result.',
  },
} as const satisfies Record<string, ParamSpec>

export type TamerParamName = keyof typeof TAMER_PARAMS

export const TAMER_METERS = {
  reduction: { id: 0, name: 'Reduction', unit: 'dB' },
  cut1: { id: 1, name: 'Cut, points 1 to 4', unit: '', display: true },
  cut2: { id: 2, name: 'Cut, points 5 to 8', unit: '', display: true },
  cut3: { id: 3, name: 'Cut, points 9 to 12', unit: '', display: true },
  cut4: { id: 4, name: 'Cut, points 13 to 16', unit: '', display: true },
  cut5: { id: 5, name: 'Cut, points 17 to 20', unit: '', display: true },
  cut6: { id: 6, name: 'Cut, points 21 to 24', unit: '', display: true },
  cut7: { id: 7, name: 'Cut, points 25 to 28', unit: '', display: true },
  cut8: { id: 8, name: 'Cut, points 29 to 32', unit: '', display: true },
  cut9: { id: 9, name: 'Cut, points 33 to 36', unit: '', display: true },
  cut10: { id: 10, name: 'Cut, points 37 to 40', unit: '', display: true },
  cut11: { id: 11, name: 'Cut, points 41 to 44', unit: '', display: true },
  cut12: { id: 12, name: 'Cut, points 45 to 48', unit: '', display: true },
} as const satisfies Record<string, DeviceMeterSpec>

export const TAMER_DEVICE = defineWasmDevice({
  id: 'tamer',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/tamer.wasm', import.meta.url),
  params: TAMER_PARAMS,
  meters: TAMER_METERS,
})

export const TAMER_DESCRIPTOR = wasmDeviceDescriptor(TAMER_DEVICE, {
  name: 'Tamer',
  category: 'eq',
  description:
    'Finds the tones that ring out above the bed of sound around them, as they happen, and turns only those down. Leaves clean notes alone. Adds no delay.',
  presets: {
    Even: { depth: 0.5, sharpness: 0.6, time: 60, from: 120, to: 16000, listen: 0 },
    Gentle: { depth: 0.3, sharpness: 0.4, time: 120, from: 120, to: 16000, listen: 0 },
    'Harsh sample': { depth: 0.8, sharpness: 0.8, time: 30, from: 1500, to: 12000, listen: 0 },
    'Bright tail': { depth: 0.65, sharpness: 0.7, time: 250, from: 1000, to: 16000, listen: 0 },
    Master: { depth: 0.25, sharpness: 0.5, time: 200, from: 150, to: 14000, listen: 0 },
    'Ringing tones': { depth: 0.9, sharpness: 1, time: 150, from: 120, to: 16000, listen: 0 },
    Mud: { depth: 0.6, sharpness: 0.5, time: 100, from: 100, to: 1000, listen: 0 },
    'Broad and slow': { depth: 0.6, sharpness: 0.1, time: 500, from: 120, to: 16000, listen: 0 },
    Mic: { depth: 0.5, sharpness: 0.8, time: 40, from: 200, to: 8000, listen: 0 },
    Flatten: { depth: 1, sharpness: 0.3, time: 100, from: 80, to: 20000, listen: 0 },
  },
})

export type Tamer = WasmDevice<typeof TAMER_PARAMS>

/** Finds the tones that ring out above the bed of sound around them, as they happen, and turns only those down. Leaves clean notes alone. Adds no delay. */
export function createTamer(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof TAMER_PARAMS> = {},
): Promise<Tamer> {
  return WasmDevice.create(context, TAMER_DEVICE, options)
}
