// GENERATED by scripts/gen-devices.mjs from cpp/devices/tape-orchestra/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const TAPE_ORCHESTRA_PARAMS = {
  tape: {
    id: 0,
    name: 'Tape',
    min: 0,
    max: 5,
    default: 0,
    taper: 'linear',
    unit: '',
    choices: ['Strings', 'Cellos', 'Flutes', 'Horns', 'Reeds', 'Choir'],
    description:
      'Which recording is on the tapes: a small violin section, cellos, flutes, French horns, a clarinet and oboe blend, or a mixed choir on ah. Notes already sounding cross over to the new tape.',
  },
  age: {
    id: 1,
    name: 'Age',
    min: 0,
    max: 1,
    default: 0.35,
    taper: 'linear',
    unit: '',
    description:
      'How worn the tapes and the machine are. More gives every key a deeper wobble of its own, a flatter lurch as the tape is gripped, keys that sit a little out of tune and level with each other, a narrower and grittier sound and, near the top, dropouts.',
  },
  hiss: {
    id: 2,
    name: 'Hiss',
    min: 0,
    max: 1,
    default: 0.2,
    taper: 'linear',
    unit: '',
    description:
      'Tape hiss under the notes. It is only there while keys sound and grows as more of them are held.',
  },
  tone: {
    id: 3,
    name: 'Tone',
    min: -1,
    max: 1,
    default: 0,
    taper: 'linear',
    unit: '',
    description:
      'Tilts the playback from dark and muffled, through the plain tape in the middle, to open and airy.',
  },
  speed: {
    id: 4,
    name: 'Speed',
    min: 0,
    max: 1,
    default: 0,
    taper: 'linear',
    unit: '',
    choices: ['Normal', 'Half'],
    description:
      'Half runs the tapes at half speed: everything sounds an octave lower and darker, with slower attacks, slower vibrato and twice the tape length. Switching while notes sound slows the tape down or brings it back up.',
  },
  length: {
    id: 5,
    name: 'Length',
    min: 2,
    max: 9,
    default: 9,
    taper: 'linear',
    unit: 's',
    description:
      'How much tape each key has. A held note fades out over its last half second when the tape runs out and has to be struck again. Fully up, the tape never ends.',
  },
  attack: {
    id: 6,
    name: 'Attack',
    min: 0.005,
    max: 4,
    default: 0.06,
    taper: 'log',
    unit: 's',
    description:
      'Fades each note in, on top of the start that is recorded on the tape. Short lets the bow scrape or breath through; long is a swell.',
  },
  release: {
    id: 7,
    name: 'Release',
    min: 0.02,
    max: 6,
    default: 0.4,
    taper: 'log',
    unit: 's',
    description: 'How long a note takes to fade out after the key is let go.',
  },
  players: {
    id: 8,
    name: 'Section',
    min: 0,
    max: 1,
    default: 0.6,
    taper: 'linear',
    unit: '',
    description:
      'How different the players on each tape are. At zero they play as one; higher they drift apart in tuning, come in at slightly different moments and swell on their own, like a looser section.',
  },
  vibrato: {
    id: 9,
    name: 'Vibrato',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
    description:
      'How much vibrato the players use. Each one starts it a little after the note begins and at a rate of their own.',
  },
  spread: {
    id: 10,
    name: 'Spread',
    min: 0,
    max: 1,
    default: 0.7,
    taper: 'linear',
    unit: '',
    description:
      'How far the players of each key sit apart between left and right. At zero the instrument is mono.',
  },
  volume: {
    id: 11,
    name: 'Volume',
    min: -48,
    max: 6,
    default: -9,
    taper: 'linear',
    unit: 'dB',
    description:
      'Output level of the instrument. A soft clip after it rounds off the peaks when many notes stack up.',
  },
} as const satisfies Record<string, ParamSpec>

export type TapeOrchestraParamName = keyof typeof TAPE_ORCHESTRA_PARAMS

export const TAPE_ORCHESTRA_DEVICE = defineWasmDevice({
  id: 'tape-orchestra',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/tape-orchestra.wasm', import.meta.url),
  params: TAPE_ORCHESTRA_PARAMS,
})

export const TAPE_ORCHESTRA_DESCRIPTOR = wasmDeviceDescriptor(TAPE_ORCHESTRA_DEVICE, {
  name: 'Tape Orchestra',
  category: 'instrument',
  description:
    'Orchestral sections played from a strip of worn tape under every key: strings, cellos, flutes, horns, reeds and a choir that wobble, lurch, hiss and run out.',
  presets: {
    'Three violins': { tape: 0, length: 8 },
    'Slow strings': { tape: 0, attack: 0.9, release: 1.6 },
    'Horn chorale': { tape: 3 },
    'Flutes on tape': { tape: 2 },
  },
})

export type TapeOrchestra = WasmDevice<typeof TAPE_ORCHESTRA_PARAMS>

/** Orchestral sections played from a strip of worn tape under every key: strings, cellos, flutes, horns, reeds and a choir that wobble, lurch, hiss and run out. Play it through `NoteDevice`: `noteOn(id, frequency, gain)` / `noteOff(id)`. */
export function createTapeOrchestra(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof TAPE_ORCHESTRA_PARAMS> = {},
): Promise<TapeOrchestra> {
  return WasmDevice.create(context, TAPE_ORCHESTRA_DEVICE, options)
}
