// GENERATED by scripts/gen-devices.mjs from cpp/devices/tine-piano/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const TINE_PIANO_PARAMS = {
  bell: { id: 0, name: 'Bell', min: 0, max: 1, default: 0.45, taper: 'linear', unit: '' },
  bark: { id: 1, name: 'Bark', min: 0, max: 1, default: 0.35, taper: 'linear', unit: '' },
  decay: { id: 2, name: 'Decay', min: 0.25, max: 4, default: 1, taper: 'log', unit: '' },
  release: { id: 3, name: 'Release', min: 0.03, max: 3, default: 0.25, taper: 'log', unit: 's' },
  hardness: { id: 4, name: 'Hardness', min: 0, max: 1, default: 0.7, taper: 'linear', unit: '' },
  tremolo: { id: 5, name: 'Tremolo', min: 0, max: 1, default: 0.3, taper: 'linear', unit: '' },
  tremoloRate: { id: 6, name: 'Rate', min: 0.1, max: 10, default: 3.2, taper: 'log', unit: 'Hz' },
  pan: { id: 7, name: 'Pan', min: 0, max: 1, default: 1, taper: 'linear', unit: '' },
  tone: { id: 8, name: 'Tone', min: 0, max: 1, default: 0.55, taper: 'linear', unit: '' },
  drive: { id: 9, name: 'Drive', min: 0, max: 1, default: 0.15, taper: 'linear', unit: '' },
  volume: { id: 10, name: 'Volume', min: -48, max: 6, default: -9, taper: 'linear', unit: 'dB' },
} as const satisfies Record<string, ParamSpec>

export type TinePianoParamName = keyof typeof TINE_PIANO_PARAMS

export const TINE_PIANO_DEVICE = defineWasmDevice({
  id: 'tine-piano',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/tine-piano.wasm', import.meta.url),
  params: TINE_PIANO_PARAMS,
})

export const TINE_PIANO_DESCRIPTOR = wasmDeviceDescriptor(TINE_PIANO_DEVICE, {
  name: 'Tine',
  category: 'instrument',
  description:
    'Modelled tine electric piano: struck tines and tone bars read by a pickup that barks when played hard, through a suitcase amplifier with stereo tremolo.',
  presets: {
    'Soft suitcase': {
      bell: 0.45,
      bark: 0.35,
      decay: 1,
      release: 0.25,
      hardness: 0.7,
      tremolo: 0.3,
      tremoloRate: 3.2,
      pan: 1,
      tone: 0.55,
      drive: 0.15,
    },
    'Bell tines': {
      bell: 0.9,
      bark: 0.15,
      decay: 1.2,
      hardness: 0.8,
      tremolo: 0.15,
      tremoloRate: 2.4,
      tone: 0.75,
      drive: 0.05,
    },
    'Barking stage': {
      bell: 0.3,
      bark: 0.85,
      hardness: 1,
      release: 0.15,
      tremolo: 0,
      tone: 0.65,
      drive: 0.45,
    },
    'Dark felt': {
      bell: 0.1,
      bark: 0.2,
      decay: 1.5,
      release: 0.5,
      hardness: 0.4,
      tremolo: 0,
      tone: 0.25,
      drive: 0.1,
    },
    'Slow pan': {
      bell: 0.5,
      bark: 0.3,
      decay: 1.6,
      release: 0.8,
      tremolo: 0.75,
      tremoloRate: 0.45,
      pan: 1,
      tone: 0.5,
    },
    Tremolo: {
      bell: 0.35,
      bark: 0.5,
      tremolo: 0.6,
      tremoloRate: 5.8,
      pan: 0,
      tone: 0.6,
      drive: 0.25,
    },
    'Long sustain': {
      bell: 0.6,
      bark: 0.25,
      decay: 3,
      release: 1.5,
      hardness: 0.6,
      tremolo: 0.2,
      tremoloRate: 1.1,
      tone: 0.45,
      drive: 0.1,
    },
  },
})

export type TinePiano = WasmDevice<typeof TINE_PIANO_PARAMS>

/** Modelled tine electric piano: struck tines and tone bars read by a pickup that barks when played hard, through a suitcase amplifier with stereo tremolo. Play it through `NoteDevice`: `noteOn(id, frequency, gain)` / `noteOff(id)`. */
export function createTinePiano(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof TINE_PIANO_PARAMS> = {},
): Promise<TinePiano> {
  return WasmDevice.create(context, TINE_PIANO_DEVICE, options)
}
