// GENERATED by scripts/gen-devices.mjs from cpp/devices/vowel-reverb/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const VOWEL_REVERB_PARAMS = {
  vowel: {
    id: 0,
    name: 'Vowel',
    min: 0,
    max: 4,
    default: 0,
    taper: 'linear',
    unit: '',
    description:
      'Which vowel the tail sings, from Ah through Eh, Ee and Oh to Oo. Settings in between are a mouth halfway from one vowel to the next.',
  },
  resonance: {
    id: 1,
    name: 'Resonance',
    min: 0,
    max: 1,
    default: 0.6,
    taper: 'linear',
    unit: '',
    description:
      'How strongly the vowel is pressed onto the reverb. At zero it is a plain hall; higher settings make the tail more vocal, and the vowel grows clearer the longer it rings.',
  },
  voice: {
    id: 2,
    name: 'Voice',
    min: 0,
    max: 1,
    default: 0.4,
    taper: 'linear',
    unit: '',
    description:
      'The size of the singers, from a deep bass choir through tenor and alto to a bright soprano one.',
  },
  motion: {
    id: 3,
    name: 'Motion',
    min: 0,
    max: 1,
    default: 0.3,
    taper: 'linear',
    unit: '',
    description:
      'Lets the vowel wander slowly towards its neighbours on its own, a little differently on each side, so the tail sounds like people singing instead of a fixed filter.',
  },
  decay: {
    id: 4,
    name: 'Decay',
    min: 0.5,
    max: 40,
    default: 6,
    taper: 'log',
    unit: 's',
    description:
      "How long the sung notes of the tail take to die away. The sound between the vowel's resonances fades sooner as Resonance goes up.",
  },
  size: {
    id: 5,
    name: 'Size',
    min: 0,
    max: 1,
    default: 0.6,
    taper: 'linear',
    unit: '',
    description:
      'How big the room is, from a small chapel to a cathedral. Larger rooms answer later and more slowly. Moving it bends the pitch of the tail.',
  },
  preDelay: {
    id: 6,
    name: 'Pre-delay',
    min: 0,
    max: 200,
    default: 20,
    taper: 'linear',
    unit: 'ms',
    description:
      'The gap before the reverb starts, which keeps the start of the sound clear of the choir behind it.',
  },
  modulation: {
    id: 7,
    name: 'Modulation',
    min: 0,
    max: 1,
    default: 0.4,
    taper: 'linear',
    unit: '',
    description:
      'Slow pitch drift inside the reverb. A little makes the tail an ensemble of voices that are never quite in unison; a lot is a wide chorus.',
  },
  lowCut: {
    id: 8,
    name: 'Low Cut',
    min: 20,
    max: 800,
    default: 100,
    taper: 'log',
    unit: 'Hz',
    description:
      'Removes lows from the reverb so it does not cloud the bass. The dry signal is not touched.',
  },
  highCut: {
    id: 9,
    name: 'High Cut',
    min: 1500,
    max: 18000,
    default: 9000,
    taper: 'log',
    unit: 'Hz',
    description:
      'Darkens the reverb. It also works inside the room, so the highs die away sooner than the rest.',
  },
  width: {
    id: 10,
    name: 'Width',
    min: 0,
    max: 1,
    default: 1,
    taper: 'linear',
    unit: '',
    description: 'Stereo width of the reverb only. Zero is a mono tail; full is the widest.',
  },
  mix: {
    id: 11,
    name: 'Mix',
    min: 0,
    max: 1,
    default: 0.4,
    taper: 'linear',
    unit: '',
    description: 'Balance between the dry signal and the reverb. Fully up is the reverb alone.',
  },
} as const satisfies Record<string, ParamSpec>

export type VowelReverbParamName = keyof typeof VOWEL_REVERB_PARAMS

export const VOWEL_REVERB_DEVICE = defineWasmDevice({
  id: 'vowel-reverb',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/vowel-reverb.wasm', import.meta.url),
  params: VOWEL_REVERB_PARAMS,
})

export const VOWEL_REVERB_DESCRIPTOR = wasmDeviceDescriptor(VOWEL_REVERB_DEVICE, {
  name: 'Vowel Reverb',
  category: 'reverb',
  description:
    'A hall whose tail sings: the reverb is shaped by the formants of a sung vowel, so what goes in comes back as a soft wordless choir.',
  presets: {
    'Choir of ah': { vowel: 0 },
    'Low monks': { vowel: 3.5, voice: 0 },
    'High ee': { vowel: 2, voice: 1 },
    'Moving vowels': { motion: 1 },
  },
})

export type VowelReverb = WasmDevice<typeof VOWEL_REVERB_PARAMS>

/** A hall whose tail sings: the reverb is shaped by the formants of a sung vowel, so what goes in comes back as a soft wordless choir. */
export function createVowelReverb(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof VOWEL_REVERB_PARAMS> = {},
): Promise<VowelReverb> {
  return WasmDevice.create(context, VOWEL_REVERB_DEVICE, options)
}
