// GENERATED by scripts/gen-devices.mjs from cpp/devices/vowel-reverb/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const VOWEL_REVERB_PARAMS = {
  vowel: {
    id: 0,
    name: 'Vowel',
    min: 0,
    max: 4,
    default: 0,
    taper: 'linear',
    unit: '',
    description:
      'Which vowel the tail sings, from Ah through Eh, Ee and Oh to Oo. Settings in between are a mouth halfway from one vowel to the next.',
  },
  resonance: {
    id: 1,
    name: 'Resonance',
    min: 0,
    max: 1,
    default: 0.6,
    taper: 'linear',
    unit: '',
    description:
      'How strongly the vowel is pressed onto the reverb. Right down it is a plain hall; higher makes the tail more vocal, and the vowel grows clearer the longer it rings.',
  },
  voice: {
    id: 2,
    name: 'Voice',
    min: 0,
    max: 1,
    default: 0.4,
    taper: 'linear',
    unit: '',
    description:
      'The size of the singers, from a deep bass choir through tenor and alto to a bright soprano one.',
  },
  motion: {
    id: 3,
    name: 'Motion',
    min: 0,
    max: 1,
    default: 0.3,
    taper: 'linear',
    unit: '',
    description:
      'Lets the vowel wander slowly towards its neighbours on its own, a little differently on each side, so the tail sounds like people singing instead of a fixed filter.',
  },
  decay: {
    id: 4,
    name: 'Decay',
    min: 0.5,
    max: 40,
    default: 6,
    taper: 'log',
    unit: 's',
    description:
      "How long the sung notes of the tail take to die away. The sound between the vowel's resonances fades sooner as Resonance goes up.",
  },
  size: {
    id: 5,
    name: 'Size',
    min: 0,
    max: 1,
    default: 0.6,
    taper: 'linear',
    unit: '',
    description:
      'How big the room is, from a small chapel to a cathedral. Larger rooms answer later and more slowly. Moving it bends the pitch of the tail.',
  },
  preDelay: {
    id: 6,
    name: 'Pre-delay',
    min: 0,
    max: 200,
    default: 20,
    taper: 'linear',
    unit: 'ms',
    description:
      'The gap before the reverb starts, which keeps the start of the sound clear of the choir behind it.',
  },
  modulation: {
    id: 7,
    name: 'Modulation',
    min: 0,
    max: 1,
    default: 0.4,
    taper: 'linear',
    unit: '',
    description:
      'Slow pitch drift inside the reverb. A little makes the tail an ensemble of voices that are never quite in unison; a lot is a wide chorus.',
  },
  lowCut: {
    id: 8,
    name: 'Low Cut',
    min: 20,
    max: 800,
    default: 100,
    taper: 'log',
    unit: 'Hz',
    description:
      'Removes lows from the reverb so it does not cloud the bass. The dry signal is not touched.',
  },
  highCut: {
    id: 9,
    name: 'High Cut',
    min: 1500,
    max: 18000,
    default: 9000,
    taper: 'log',
    unit: 'Hz',
    description:
      'Darkens the reverb. It also works inside the room, so the highs die away sooner than the rest.',
  },
  width: {
    id: 10,
    name: 'Width',
    min: 0,
    max: 1,
    default: 1,
    taper: 'linear',
    unit: '',
    description:
      'Stereo width of the reverb only, from a mono tail in the middle to the widest spread. The dry signal keeps its own width.',
  },
  mix: {
    id: 11,
    name: 'Mix',
    min: 0,
    max: 1,
    default: 0.4,
    taper: 'linear',
    unit: '',
    description: 'Balance between the dry signal and the reverb. Fully up is the reverb alone.',
  },
} as const satisfies Record<string, ParamSpec>

export type VowelReverbParamName = keyof typeof VOWEL_REVERB_PARAMS

export const VOWEL_REVERB_DEVICE = defineWasmDevice({
  id: 'vowel-reverb',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/vowel-reverb.wasm', import.meta.url),
  params: VOWEL_REVERB_PARAMS,
})

export const VOWEL_REVERB_DESCRIPTOR = wasmDeviceDescriptor(VOWEL_REVERB_DEVICE, {
  name: 'Vowel Reverb',
  category: 'reverb',
  description:
    'A hall whose tail sings: the reverb is shaped by the formants of a sung vowel, so what goes in comes back as a soft wordless choir.',
  presets: {
    'Choir of ah': {
      vowel: 0,
      resonance: 0.6,
      voice: 0.4,
      motion: 0.3,
      decay: 6,
      size: 0.6,
      mix: 0.4,
    },
    'Low monks': {
      vowel: 3.4,
      resonance: 0.75,
      voice: 0,
      motion: 0.25,
      decay: 12,
      size: 0.85,
      modulation: 0.3,
      lowCut: 60,
      highCut: 4500,
      mix: 0.45,
      width: 0.8,
    },
    'High ee': {
      vowel: 2,
      resonance: 0.7,
      voice: 1,
      motion: 0.15,
      decay: 5,
      size: 0.5,
      lowCut: 200,
      highCut: 14000,
      mix: 0.35,
    },
    'Vowel drift': { vowel: 1.5, resonance: 0.8, voice: 0.5, motion: 1, decay: 8, modulation: 0.5 },
    Whispering: {
      vowel: 0.5,
      resonance: 0.2,
      voice: 0.6,
      motion: 0.4,
      decay: 3.5,
      size: 0.5,
      highCut: 11000,
      mix: 0.3,
    },
    'Oo behind': {
      vowel: 4,
      resonance: 0.85,
      voice: 0.8,
      motion: 0.2,
      decay: 4.5,
      size: 0.45,
      preDelay: 80,
      lowCut: 150,
      highCut: 6000,
      mix: 0.3,
      width: 0.7,
    },
    Cathedral: {
      vowel: 0.3,
      resonance: 0.55,
      voice: 0.35,
      motion: 0.4,
      decay: 20,
      size: 1,
      preDelay: 40,
      modulation: 0.5,
      highCut: 7000,
      mix: 0.45,
    },
    Chapel: {
      vowel: 1,
      resonance: 0.5,
      voice: 0.6,
      motion: 0.2,
      decay: 1.6,
      size: 0.15,
      preDelay: 5,
      modulation: 0.25,
      mix: 0.3,
    },
    'Plain hall': { resonance: 0, decay: 4, size: 0.7, highCut: 12000, mix: 0.35 },
    'Choir alone': { vowel: 0.8, resonance: 0.7, voice: 0.5, decay: 10, size: 0.8, mix: 1 },
    'Faint voices': { vowel: 2.5, resonance: 0.8, voice: 0.7, decay: 4, mix: 0.15 },
    'Lone voice': {
      vowel: 1,
      resonance: 1,
      voice: 0.15,
      motion: 0,
      decay: 3,
      size: 0.3,
      width: 0,
      mix: 0.35,
    },
    'High choir': {
      vowel: 0,
      resonance: 0.8,
      voice: 1,
      decay: 25,
      size: 1,
      modulation: 0.6,
      lowCut: 400,
      highCut: 18000,
      mix: 0.4,
    },
    'Endless oo': {
      vowel: 4,
      resonance: 0.7,
      voice: 0.3,
      motion: 0.5,
      decay: 40,
      size: 0.9,
      highCut: 5000,
      mix: 0.5,
    },
    'Late basses': { vowel: 2, resonance: 0.7, voice: 0.1, decay: 7, size: 0.7, preDelay: 200 },
    Humming: {
      vowel: 4,
      resonance: 0.5,
      voice: 0,
      decay: 10,
      size: 0.7,
      lowCut: 40,
      highCut: 1500,
      mix: 0.5,
    },
  },
  formerPresets: {
    'Moving vowels': 'Vowel drift',
    'Whispering hall': 'Whispering',
    'Cathedral choir': 'Cathedral',
    'Small chapel': 'Chapel',
    'Plain stone hall': 'Plain hall',
    'Soprano clouds': 'High choir',
    'Humming dark': 'Humming',
  },
})

export type VowelReverb = WasmDevice<typeof VOWEL_REVERB_PARAMS>

/** A hall whose tail sings: the reverb is shaped by the formants of a sung vowel, so what goes in comes back as a soft wordless choir. */
export function createVowelReverb(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof VOWEL_REVERB_PARAMS> = {},
): Promise<VowelReverb> {
  return WasmDevice.create(context, VOWEL_REVERB_DEVICE, options)
}
