// GENERATED by scripts/gen-devices.mjs from cpp/devices/weather/device.json. Do not edit.

import { type DeviceMeterSpec } from '../../core/devices/Device'
import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const WEATHER_PARAMS = {
  kind: {
    id: 0,
    name: 'Kind',
    min: 0,
    max: 4,
    default: 0,
    taper: 'linear',
    unit: '',
    choices: ['Wind', 'Clouds', 'Rain', 'Surf', 'Storm'],
    description:
      'Which weather the sound is left out in: gusting wind, passing clouds, rain, surf breaking over it, or a storm of wind, rain and far thunder together.',
  },
  exposure: {
    id: 1,
    name: 'Exposure',
    min: 0,
    max: 1,
    default: 0.6,
    taper: 'linear',
    unit: '',
    description:
      'How much the weather moves the sound itself: level sinks and highs dull under each gust, shadow, drop or wave, and wind and surf roughen it. At zero it is untouched.',
  },
  voice: {
    id: 2,
    name: 'Voice',
    min: 0,
    max: 1,
    default: 0.4,
    taper: 'linear',
    unit: '',
    description:
      "How much of the weather's own sound is heard: whistle, hush, drops, wash and thunder. It is as loud as the playing lets it be. At zero only what Exposure does is left.",
  },
  calm: {
    id: 3,
    name: 'Calm',
    min: 0,
    max: 1,
    default: 0.3,
    taper: 'linear',
    unit: '',
    description:
      'How long the lulls between gusts, clouds, showers and waves are. At zero one follows the other. Turned up, the sound is left in peace for longer.',
  },
  colour: {
    id: 4,
    name: 'Colour',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
    description:
      'Dark to bright weather. Low settings howl, thud and roar and dull more of the sound. High settings whistle, tick and fizz and take only its top.',
  },
  sway: {
    id: 5,
    name: 'Sway',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
    description:
      'How much the weather moves from side to side: gusts lean, drops scatter, clouds and waves cross from one side to the other. At zero it all stays in the middle.',
  },
  linger: {
    id: 6,
    name: 'Linger',
    min: 1,
    max: 60,
    default: 10,
    taper: 'log',
    unit: 's',
    description:
      "How long the weather's own sound stays as it was after the playing falls away or stops, before it sinks to where the playing is now and, in silence, fades out.",
  },
  mix: {
    id: 7,
    name: 'Mix',
    min: 0,
    max: 1,
    default: 1,
    taper: 'linear',
    unit: '',
    description: 'Balance between the dry signal and the sound out in the weather.',
  },
  force: {
    id: 8,
    name: 'Force',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
    description:
      'How strong the weather is: the height of the gusts, the depth of the shadows, how hard it rains, the size of the waves. At zero the sound is left alone.',
  },
  pace: {
    id: 9,
    name: 'Pace',
    min: 0.25,
    max: 4,
    default: 1,
    taper: 'log',
    unit: '',
    description:
      "How fast the weather changes: low for long slow gusts, clouds and waves, high for short quick ones and thicker rain. A drop's tick and a thunder roll keep their length.",
  },
} as const satisfies Record<string, ParamSpec>

export type WeatherParamName = keyof typeof WEATHER_PARAMS

export const WEATHER_METERS = {
  level: { id: 0, name: 'Weather now', unit: '', display: true },
  gain: { id: 1, name: 'Level under it', unit: '', display: true },
  drops: { id: 2, name: 'Drops so far', unit: '', display: true },
  gate: { id: 3, name: 'Weather on', unit: '', display: true },
  rolls: { id: 4, name: 'Thunder so far', unit: '', display: true },
  top: { id: 5, name: 'Highs under it', unit: '', display: true },
} as const satisfies Record<string, DeviceMeterSpec>

export const WEATHER_DEVICE = defineWasmDevice({
  id: 'weather',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/weather.wasm', import.meta.url),
  params: WEATHER_PARAMS,
  meters: WEATHER_METERS,
})

export const WEATHER_DESCRIPTOR = wasmDeviceDescriptor(WEATHER_DEVICE, {
  name: 'Weather',
  category: 'texture',
  description:
    'Leaves the sound out in the weather: gusts of wind, clouds passing over, rain tapping on it, surf washing through it or a storm, each moving its level and tone and adding a thin sound of its own.',
  presets: {
    'Breezy day': {
      kind: 0,
      force: 0.5,
      pace: 1,
      exposure: 0.6,
      voice: 0.4,
      colour: 0.5,
      sway: 0.5,
      calm: 0.3,
      linger: 10,
      mix: 1,
    },
    Gale: { kind: 0, force: 1, pace: 1.6, exposure: 0.65, voice: 0.5, colour: 0.45, calm: 0 },
    'Whistling gap': {
      kind: 0,
      force: 0.8,
      exposure: 0.25,
      voice: 0.75,
      colour: 0.95,
      sway: 0.8,
      calm: 0.15,
    },
    'Dry gusts': { kind: 0, force: 1, pace: 2.2, exposure: 0.8, voice: 0, calm: 0.3 },
    'Passing clouds': { kind: 1, force: 0.8, pace: 1.5, exposure: 0.9, voice: 0.25, sway: 0.9 },
    Overcast: { kind: 1, force: 1, pace: 0.5, exposure: 1, voice: 0.5, colour: 0.15, calm: 0 },
    'Light rain': { kind: 2, force: 0.4, exposure: 0.5, voice: 0.5, colour: 0.7 },
    Downpour: { kind: 2, force: 1, pace: 2.5, exposure: 0.9, voice: 0.6, colour: 0.55, calm: 0 },
    'Slow drips': {
      kind: 2,
      force: 0.45,
      pace: 0.3,
      exposure: 1,
      voice: 0.8,
      colour: 0.1,
      sway: 1,
      calm: 0.1,
    },
    'Slow surf': { kind: 3, force: 0.7, exposure: 0.7, voice: 0.5 },
    Breakers: { kind: 3, force: 1, pace: 2, exposure: 1, voice: 0.75, colour: 0.6, calm: 0 },
    'Far shore': {
      kind: 3,
      force: 0.6,
      pace: 0.7,
      exposure: 0.35,
      voice: 0.45,
      colour: 0.1,
      sway: 0.3,
      linger: 30,
      mix: 0.45,
    },
    'Storm front': { kind: 4, force: 0.8, exposure: 0.7, voice: 0.55 },
    'Far thunder': {
      kind: 4,
      force: 0.5,
      pace: 0.7,
      exposure: 0.2,
      voice: 0.6,
      colour: 0,
      calm: 0.5,
      linger: 30,
    },
    'Dappled shade': {
      kind: 1,
      force: 0.75,
      pace: 4,
      exposure: 1,
      voice: 0,
      colour: 0.8,
      sway: 1,
      calm: 0.1,
    },
    'Hail on glass': {
      kind: 2,
      force: 0.9,
      pace: 4,
      exposure: 0.6,
      voice: 0.7,
      colour: 1,
      sway: 1,
      calm: 0,
    },
  },
})

export type Weather = WasmDevice<typeof WEATHER_PARAMS>

/** Leaves the sound out in the weather: gusts of wind, clouds passing over, rain tapping on it, surf washing through it or a storm, each moving its level and tone and adding a thin sound of its own. */
export function createWeather(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof WEATHER_PARAMS> = {},
): Promise<Weather> {
  return WasmDevice.create(context, WEATHER_DEVICE, options)
}
