// GENERATED by scripts/gen-devices.mjs from cpp/devices/wind-harp/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const WIND_HARP_PARAMS = {
  wind: {
    id: 0,
    name: 'Wind',
    min: 0,
    max: 1,
    default: 0.42,
    taper: 'linear',
    unit: '',
    description:
      'How hard the wind blows. A light wind sings the low harmonics of each string and a strong one the high ones, with the air around it rising too.',
  },
  gust: {
    id: 1,
    name: 'Gust',
    min: 0,
    max: 1,
    default: 0.5,
    taper: 'linear',
    unit: '',
    description:
      'How much the wind comes and goes. At zero it is steady and each string holds its harmonic; higher, it swells and fades and the lit harmonics climb and fall with it.',
  },
  lull: {
    id: 2,
    name: 'Lull',
    min: 0,
    max: 1,
    default: 0.3,
    taper: 'linear',
    unit: '',
    description:
      'How often the wind drops away to almost nothing for a few seconds and lets the strings ring down. At zero it never does.',
  },
  strings: {
    id: 3,
    name: 'Strings',
    min: 1,
    max: 4,
    default: 2,
    taper: 'linear',
    unit: '',
    step: 1,
    description:
      'Strings per key, tuned a little apart and spread across the stereo field, each catching the wind its own way. One is pure; more beat and sing different harmonics.',
  },
  glint: {
    id: 4,
    name: 'Glint',
    min: 0,
    max: 1,
    default: 0.7,
    taper: 'linear',
    unit: '',
    description:
      "How far up the harmonics the wind can light. Low keeps to the string's own note and its first overtones; high lets the top ones flash.",
  },
  ring: {
    id: 5,
    name: 'Ring',
    min: 0.3,
    max: 20,
    default: 4,
    taper: 'log',
    unit: 's',
    description:
      'How long a harmonic sings on after the wind has moved off it, and how slowly it wakes. Short follows every gust; long blurs them into a glow.',
  },
  hum: {
    id: 6,
    name: 'Hum',
    min: 0,
    max: 1,
    default: 0.2,
    taper: 'linear',
    unit: '',
    description:
      "How much of each string's own low note is always there under the harmonics, whatever the wind is doing.",
  },
  air: {
    id: 7,
    name: 'Air',
    min: 0,
    max: 1,
    default: 0.25,
    taper: 'linear',
    unit: '',
    description:
      'The sound of the wind itself: a soft rush of noise around the strings that swells and brightens with the same gusts.',
  },
  touch: {
    id: 8,
    name: 'Touch',
    min: 0,
    max: 1,
    default: 0.25,
    taper: 'linear',
    unit: '',
    description:
      'A soft pluck when a key goes down, so a short note still sounds. At zero nothing is plucked and a note fades in as the wind finds it.',
  },
  release: {
    id: 9,
    name: 'Release',
    min: 0.05,
    max: 12,
    default: 2.5,
    taper: 'log',
    unit: 's',
    description:
      'How long a string takes to fade after its key is let go. The wind keeps playing it while it fades.',
  },
  width: {
    id: 10,
    name: 'Width',
    min: 0,
    max: 1,
    default: 0.7,
    taper: 'linear',
    unit: '',
    description:
      'How far apart the strings of a key and the two sides of the air sit in the stereo field, down to mono at zero.',
  },
  volume: {
    id: 11,
    name: 'Volume',
    min: -48,
    max: 6,
    default: -9,
    taper: 'linear',
    unit: 'dB',
    description:
      'Output level of the instrument. A soft clip after it rounds off the peaks when many keys are held.',
  },
} as const satisfies Record<string, ParamSpec>

export type WindHarpParamName = keyof typeof WIND_HARP_PARAMS

export const WIND_HARP_DEVICE = defineWasmDevice({
  id: 'wind-harp',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/wind-harp.wasm', import.meta.url),
  params: WIND_HARP_PARAMS,
})

export const WIND_HARP_DESCRIPTOR = wasmDeviceDescriptor(WIND_HARP_DEVICE, {
  name: 'Wind Harp',
  category: 'instrument',
  description:
    'A harp of strings played by the wind: it rises and falls across the held keys and lights one harmonic of each string after another, so a chord shimmers and breathes by itself.',
  presets: {
    'Wind harp': {},
    'Still air': {
      wind: 0.15,
      gust: 0.25,
      lull: 0,
      glint: 0.45,
      hum: 0.5,
      air: 0.04,
      volume: -12.5,
    },
    'High gale': {
      wind: 0.85,
      gust: 0.8,
      strings: 3,
      glint: 1,
      ring: 2.5,
      hum: 0.1,
      air: 0.3,
      volume: -6.5,
    },
    'Long lulls': {
      wind: 0.5,
      gust: 0.3,
      lull: 1,
      ring: 3.5,
      hum: 0.1,
      air: 0.15,
      touch: 0.1,
      volume: -7,
    },
    'Plucked course': {
      wind: 0.2,
      gust: 0.3,
      lull: 0,
      strings: 4,
      ring: 3,
      air: 0,
      touch: 1,
      width: 0.9,
      volume: -19,
    },
    'Glass whistle': {
      wind: 0.75,
      gust: 0.35,
      lull: 0,
      strings: 1,
      glint: 1,
      ring: 1.5,
      hum: 0,
      air: 0.08,
      touch: 0,
      volume: -4,
    },
    'Low hum': {
      wind: 0.1,
      gust: 0.3,
      lull: 0,
      glint: 0.3,
      ring: 6,
      hum: 1,
      air: 0.04,
      touch: 0.15,
      release: 4,
      volume: -15.5,
    },
    'Sea breeze': { wind: 0.45, gust: 0.9, lull: 0.4, ring: 3, air: 0.55, touch: 0.15, volume: -8 },
    'Shimmer course': {
      wind: 0.6,
      lull: 0,
      strings: 4,
      glint: 0.85,
      ring: 5,
      hum: 0.1,
      width: 1,
      volume: -7.5,
    },
    'Slow swell': { wind: 0.3, gust: 0.7, lull: 0.1, strings: 3, ring: 12, touch: 0, release: 8 },
    'Bare string': {
      wind: 0.3,
      gust: 0.25,
      lull: 0,
      strings: 1,
      air: 0,
      touch: 0.5,
      width: 0,
      volume: -11.5,
    },
    'Fence wires': {
      wind: 0.7,
      gust: 0.6,
      strings: 3,
      glint: 0.75,
      ring: 1.5,
      hum: 0.8,
      air: 0.12,
      touch: 0.1,
      volume: -8.5,
    },
    'Night wind': {
      wind: 0.25,
      gust: 0.8,
      lull: 0.5,
      ring: 5,
      hum: 0.1,
      air: 1,
      touch: 0,
      release: 5,
      volume: -11.5,
    },
    'Soft pluck': {
      wind: 0.4,
      gust: 0.25,
      lull: 0,
      strings: 1,
      glint: 0.6,
      ring: 1.2,
      hum: 0,
      air: 0,
      touch: 0.7,
      release: 1.2,
      volume: -10.5,
    },
    'Overtone ladder': {
      wind: 0.5,
      gust: 1,
      lull: 0,
      strings: 1,
      glint: 1,
      ring: 0.8,
      hum: 0.15,
      air: 0.04,
      touch: 0.1,
      volume: -7,
    },
    'Storm front': {
      wind: 0.7,
      gust: 1,
      lull: 0.6,
      strings: 4,
      glint: 0.8,
      ring: 4,
      air: 0.5,
      width: 1,
      volume: -8,
    },
  },
})

export type WindHarp = WasmDevice<typeof WIND_HARP_PARAMS>

/** A harp of strings played by the wind: it rises and falls across the held keys and lights one harmonic of each string after another, so a chord shimmers and breathes by itself. Play it through `NoteDevice`: `noteOn(id, frequency, gain)` / `noteOff(id)`. */
export function createWindHarp(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof WIND_HARP_PARAMS> = {},
): Promise<WindHarp> {
  return WasmDevice.create(context, WIND_HARP_DEVICE, options)
}
