// GENERATED by scripts/gen-devices.mjs from cpp/devices/zither/device.json. Do not edit.

import { type ParamSpec } from '../../core/params'
import { wasmDeviceDescriptor } from '../descriptor'
import { defineWasmDevice, WasmDevice, type WasmDeviceOptions } from '../WasmDevice'

export const ZITHER_PARAMS = {
  exciter: {
    id: 0,
    name: 'Exciter',
    min: 0,
    max: 2,
    default: 0,
    taper: 'linear',
    unit: '',
    choices: ['Finger', 'Pick', 'Hammer'],
    description:
      'What sets the strings going. A fingertip is soft and round, a pick is bright and thin, and a felt hammer strikes with a wider, softer blow and a small bounce. Applies from the next string that is played.',
  },
  chord: {
    id: 1,
    name: 'Chord',
    min: 0,
    max: 7,
    default: 0,
    taper: 'linear',
    unit: '',
    choices: ['Single', 'Octave', 'Fifth and octave', 'Major', 'Minor', 'Sus 2', 'Sus 4', 'Add 9'],
    description:
      'Which open strings one key plays: a single string, or a chord laid out over two octaves above the played note, like the strings of a chord zither. Applies from the next key.',
  },
  strum: {
    id: 2,
    name: 'Strum',
    min: 0,
    max: 600,
    default: 120,
    taper: 'linear',
    unit: 'ms',
    description:
      'How long the hand takes to cross the strings of a chord. At zero they sound together; short is a strum, long is a slow harp glissando.',
  },
  direction: {
    id: 3,
    name: 'Direction',
    min: 0,
    max: 2,
    default: 0,
    taper: 'linear',
    unit: '',
    choices: ['Up', 'Down', 'Alternate'],
    description:
      'Which way a chord is strummed and rolled: from the low string up, from the high string down, or the other way round on every new key.',
  },
  roll: {
    id: 4,
    name: 'Roll',
    min: 0,
    max: 16,
    default: 0,
    taper: 'linear',
    unit: 'Hz',
    description:
      'While a key is held, goes on striking its strings softly, one after another, this many times a second: the hammered tremolo that keeps a string shimmering, a little uneven like a hand. Off at zero; the slowest roll is two strokes a second.',
  },
  decay: {
    id: 5,
    name: 'Decay',
    min: 0.5,
    max: 20,
    default: 6,
    taper: 'log',
    unit: 's',
    description:
      'How long a string rings while its key is held. Low strings ring somewhat longer than this and high strings shorter, as on a real instrument.',
  },
  release: {
    id: 6,
    name: 'Release',
    min: 0.05,
    max: 20,
    default: 3,
    taper: 'log',
    unit: 's',
    description:
      'How quickly a hand damps the strings when the key is let go. Short stops them at once; at the top the strings are never damped and ring out on their own, as on a harp.',
  },
  brightness: {
    id: 7,
    name: 'Brightness',
    min: 0,
    max: 1,
    default: 0.55,
    taper: 'linear',
    unit: '',
    description:
      'How hard and narrow the finger, pick or hammer is and how long the upper partials ring. Low is soft, round and quickly mellow; high is glassy and stays bright. Applies from the next string that is played.',
  },
  position: {
    id: 8,
    name: 'Position',
    min: 0.05,
    max: 0.5,
    default: 0.2,
    taper: 'linear',
    unit: '',
    description:
      'Where along the string it is played. Near the bridge is thin and nasal; toward the middle is hollow and round, with every second partial missing. Applies from the next string that is played.',
  },
  courses: {
    id: 9,
    name: 'Courses',
    min: 0,
    max: 1,
    default: 0.3,
    taper: 'linear',
    unit: '',
    description:
      'Gives every note a second string tuned slightly apart from the first, one a little to each side, so the pair beats and shimmers; further up the detuning is wider. At zero each note is a single string. Applies from the next string that is played.',
  },
  sympathy: {
    id: 10,
    name: 'Sympathy',
    min: 0,
    max: 1,
    default: 0.3,
    taper: 'linear',
    unit: '',
    description:
      'How strongly twelve undamped strings, one for every note of the scale, pick up what is played. They answer only to notes that are in tune with them, and ring on after the played strings are damped.',
  },
  body: {
    id: 11,
    name: 'Body',
    min: 0,
    max: 3,
    default: 1,
    taper: 'linear',
    unit: '',
    choices: ['Harp', 'Zither', 'Dulcimer', 'Koto'],
    description:
      'The soundbox the strings are mounted on: the warm board of a harp, the bright flat box of a zither, the ringing box of a hammered dulcimer or the hollow, nasal body of a koto.',
  },
  volume: {
    id: 12,
    name: 'Volume',
    min: -48,
    max: 6,
    default: -9,
    taper: 'linear',
    unit: 'dB',
    description:
      'Output level of the instrument. A soft clip after it rounds off the peaks when many strings stack up.',
  },
} as const satisfies Record<string, ParamSpec>

export type ZitherParamName = keyof typeof ZITHER_PARAMS

export const ZITHER_DEVICE = defineWasmDevice({
  id: 'zither',
  // Static literal so Vite can rewrite it to a hashed asset URL at build time.
  wasm: () => new URL('../wasm/zither.wasm', import.meta.url),
  params: ZITHER_PARAMS,
})

export const ZITHER_DESCRIPTOR = wasmDeviceDescriptor(ZITHER_DEVICE, {
  name: 'Zither',
  category: 'instrument',
  description:
    'A box of open strings to pluck, strum and hammer: harp, zither, autoharp and hammered dulcimer, with twelve sympathetic strings that ring on behind what is played.',
  presets: {
    'Open zither': {
      exciter: 1,
      chord: 2,
      strum: 110,
      brightness: 0.6,
      position: 0.16,
      sympathy: 0.4,
      volume: -7,
    },
    'Concert harp': {
      exciter: 0,
      chord: 0,
      decay: 9,
      release: 20,
      brightness: 0.6,
      position: 0.3,
      courses: 0,
      sympathy: 0.2,
      body: 0,
      volume: -13,
    },
    'Harp glissando': {
      exciter: 0,
      chord: 7,
      strum: 480,
      direction: 2,
      decay: 8,
      release: 20,
      brightness: 0.6,
      position: 0.28,
      courses: 0,
      sympathy: 0.35,
      body: 0,
      volume: -12,
    },
    'Hammered shimmer': {
      exciter: 2,
      chord: 1,
      strum: 60,
      roll: 9,
      decay: 8,
      release: 4,
      brightness: 0.6,
      position: 0.14,
      courses: 0.4,
      sympathy: 0.7,
      body: 2,
      volume: -7.5,
    },
    'Autoharp major': {
      exciter: 1,
      chord: 3,
      strum: 90,
      decay: 5,
      release: 2,
      brightness: 0.65,
      position: 0.18,
      courses: 0.25,
      sympathy: 0.3,
      volume: -7,
    },
    'Autoharp minor': {
      exciter: 1,
      chord: 4,
      strum: 90,
      decay: 5,
      release: 2,
      brightness: 0.65,
      position: 0.18,
      courses: 0.25,
      sympathy: 0.3,
      volume: -7,
    },
    'Koto pluck': {
      exciter: 1,
      chord: 0,
      decay: 2.5,
      release: 1.2,
      brightness: 0.7,
      position: 0.08,
      courses: 0,
      sympathy: 0.15,
      body: 3,
      volume: -2.5,
    },
    'Twelve-string haze': {
      exciter: 1,
      chord: 1,
      strum: 40,
      decay: 12,
      release: 8,
      brightness: 0.6,
      position: 0.2,
      courses: 0.85,
      sympathy: 0.5,
      volume: -7.5,
    },
    'Single felt string': {
      exciter: 2,
      chord: 0,
      decay: 5,
      release: 2,
      brightness: 0.4,
      position: 0.35,
      courses: 0,
      sympathy: 0.25,
      body: 0,
      volume: -11,
    },
    'Slow sus arpeggio': {
      exciter: 0,
      chord: 5,
      strum: 360,
      direction: 2,
      roll: 3,
      decay: 10,
      release: 20,
      brightness: 0.5,
      position: 0.25,
      courses: 0.2,
      sympathy: 0.45,
      body: 0,
      volume: -12,
    },
  },
})

export type Zither = WasmDevice<typeof ZITHER_PARAMS>

/** A box of open strings to pluck, strum and hammer: harp, zither, autoharp and hammered dulcimer, with twelve sympathetic strings that ring on behind what is played. Play it through `NoteDevice`: `noteOn(id, frequency, gain)` / `noteOff(id)`. */
export function createZither(
  context: BaseAudioContext,
  options: WasmDeviceOptions<typeof ZITHER_PARAMS> = {},
): Promise<Zither> {
  return WasmDevice.create(context, ZITHER_DEVICE, options)
}
