// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Wavetable, shared with
// src/dsp/devices/wavetable.gen.ts:
//    0  table: 0 Glass, 1 Vowels, 2 Reed to Saw, 3 Hollow, 4 Spectral, default 0
//    1  position: 0..1, default 0.3
//    2  motion: 0..1, default 0.45
//    3  rate: 0.01..10 Hz, default 0.11
//    4  detune: 0..50 ct, default 9
//    5  sub: 0..1, default 0.25
//    6  cutoff: 80..20000 Hz, default 4200
//    7  resonance: 0..1, default 0.15
//    8  attack: 0.005..20 s, default 1.2
//    9  release: 0.02..30 s, default 3.5
//   10  spread: 0..1, default 0.7
//   11  volume: -48..6 dB, default -9

#pragma once

namespace livemix {
namespace wavetable {

enum Param : int {
  kTable = 0,
  kPosition = 1,
  kMotion = 2,
  kRate = 3,
  kDetune = 4,
  kSub = 5,
  kCutoff = 6,
  kResonance = 7,
  kAttack = 8,
  kRelease = 9,
  kSpread = 10,
  kVolume = 11,
  kNumParams = 12,
};

inline constexpr float kParamMin[kNumParams] = {0.0f, 0.0f, 0.0f, 0.01f, 0.0f, 0.0f, 80.0f, 0.0f, 0.005f, 0.02f, 0.0f, -48.0f};
inline constexpr float kParamMax[kNumParams] = {4.0f, 1.0f, 1.0f, 10.0f, 50.0f, 1.0f, 20000.0f, 1.0f, 20.0f, 30.0f, 1.0f, 6.0f};
inline constexpr float kParamDefault[kNumParams] = {0.0f, 0.3f, 0.45f, 0.11f, 9.0f, 0.25f, 4200.0f, 0.15f, 1.2f, 3.5f, 0.7f, -9.0f};

}  // namespace wavetable
}  // namespace livemix
