// The public surface of `@kieranklaassen/live-mix`: every symbol a consumer
// (ambient-live, Breathwork Live's SectionPlaylist) imports from the root
// entry must be present. A named export list in src/index.ts can silently drop
// a symbol; this pins the ones the adopters rely on.

import { readFile } from 'node:fs/promises'
import { describe, expect, it } from 'vitest'

import * as core from '../index'
import * as dsp from '../dsp/index'
import * as motion from '../motion/index'
import * as native from '../native/index'
import * as testing from '../testing/index'
import * as wam from '../wam/index'

const coreSymbols = [
  'createEngine',
  'Engine',
  'Bus',
  'MasterBus',
  'OutputRouter',
  'isIOSWebKit',
  'Meter',
  'Transport',
  'Scheduler',
  'Cycle',
  'SampleStore',
  'AudioTrack',
  'LiveInputTrack',
  'ReturnTrack',
  'InstrumentTrack',
  'SendList',
  'Ducker',
  'createDucker',
  'ConvolverReverb',
  'createConvolverReverb',
  'generateHallImpulse',
  'CONVOLVER_REVERB_PARAMS',
  'CONVOLVER_REVERB_DESCRIPTOR',
  'REVERB_DECAY_SECONDS',
  'REVERB_WET_LEVEL',
  'CROSSFADE_SECONDS',
  'STEER_CROSSFADE_SECONDS',
  'STOP_FADE_SECONDS',
  'JOIN_EASE_SECONDS',
  'REJOIN_FADE_SECONDS',
  'MAX_CLIP_GAIN_DB',
  'DUCK_DEPTH',
  'DUCK_TIME_CONSTANT',
  'ENV_ATTACK_MS',
  'ENV_RELEASE_MS',
  'ENV_POLL_MS',
  'ENV_GAIN_SCALE',
  'fadeGain',
  'computePeaks',
  'slicePeaks',
  'analyzeSound',
  'detectOnsets',
  'estimateTempo',
  'DEFAULT_ONSET_HOP_SECONDS',
  'DEFAULT_ONSET_MIN_GAP_SECONDS',
  'MIN_TEMPO_BPM',
  'MAX_TEMPO_BPM',
  'MIN_TEMPO_ONSETS',
  'clipsInWindow',
  'clipsSoundingAt',
  'equalPowerFadeIn',
  'equalPowerFadeOut',
  'devices',
  'DeviceRegistry',
  'clampParam',
  'describeParams',
  'ChannelStrip',
  'SoloInPlace',
  'GroupTrack',
  'resolveInput',
  'WorkletDucker',
  'DuckerKernel',
  'DUCKER_PARAMS',
  'DUCKER_PROCESSOR_NAME',
  'LufsMeter',
  'LoudnessAnalyzer',
  'MasterLimiter',
  'EngineStats',
  'METER_PROCESSOR_NAME',
  'Emitter',
  'isJsonObject',
  'isJsonValue',
  'canonicalJson',
  'sameJson',
  'isAudibleClip',
  'isPlacedClip',
  'clipPan',
  'clipLowpassHz',
  'spaceSendGain',
  'placedTrimGain',
  'generateSpaceImpulse',
  'spaceImpulseChannel',
  'resolveSpace',
  'DEFAULT_SPACE',
  'SPACE_LEVEL_HIGH_HZ',
  'SPACE_LEVEL_LOW_HZ',
  'GRAIN_ECHOES_PER_SEC',
  'MAX_SPACE_DRIVE_DB',
  'MIN_SPACE_LEVEL_DB',
  'MAX_SPACE_LEVEL_DB',
  'SPACE_DRIVE_LEVEL_DB',
  'MAX_SPACE_DRIFT_CENTS',
  'grainEchoesPerSec',
  'sameSpaceImpulse',
  'spaceColour',
  'spaceDriveGains',
  'spaceDrift',
  'SpaceRoom',
  'ParamGlide',
  'PLACEMENT_GLIDE_SECONDS',
  'SharedSpaces',
  'SpaceFeed',
  'stripOnlySetsLevel',
  'mirrorSlice',
  'reversedSourceSec',
  'isObservableDevice',
  'Rack',
  'Chain',
  'createRack',
  'RACK_DESCRIPTOR',
  'RACK_PARAMS',
  'RackMacro',
  'macroMappedValue',
  'macroCurve',
  'captureRackPreset',
  'createRackFromPreset',
  'serializeRackPreset',
  'parseRackPreset',
  'AlignmentDelay',
  'deviceLatencySamples',
  'buildLatencyReport',
  'PDC_MAX_DELAY_SECONDS',
  'rampParamTo',
  'cutQDb',
  'compressorNodeMakeupDb',
  'FLAT_CUT_Q_DB',
  'isCutFilter',
  // Score (U28)
  'SCORE_FORMAT_VERSION',
  'createScore',
  'parseScore',
  'serializeScore',
  'validateScore',
  'OPERATION_TYPES',
  'apply',
  'invert',
  'applyWithInverse',
  'coalesceKey',
  'normaliseMeta',
  'normaliseSource',
  'OperationLog',
  'History',
  'ScoreDocument',
  'ScoreRenderer',
  'loadScore',
  // U36 control surface
  'ControlSurface',
  'MidiInput',
  'OscInput',
  'MidiDecoder',
  'parseMidiMessage',
  'decodeOscPacket',
  'encodeOscMessage',
  'matchOscAddress',
  'createMapping',
  'mapTarget',
  'resolveControlEvent',
  'learnFromEvent',
  'serializeMappingTable',
  'parseMappingTable',
  'ambientLiveMidiMapMigration',
  'loadMappingTable',
  'saveMappingTable',
  'controlTargetKey',
  'sourceKey',
  'describeSource',
  'keyCodeLabel',
  'normalizeParam',
  'denormalizeParam',
  'MAPPING_TABLE_FORMAT',
  // Intensity ladder and agent control API (U29)
  'INTENSITY_LADDER',
  'targetIntensity',
  'resolveReplacementTracks',
  'rankTonal',
  'AgentController',
  'createAgentController',
  'AgentAuditLog',
  'Rails',
  'DEFAULT_RAILS',
  'ToolRegistry',
  'toOpenAiTools',
  'toAnthropicTools',
  'operationSchema',
  'toolNameForOperation',
  'validateSchema',
  'buildSnapshot',
  // Performing: rides, the perform set, the runtime
  'DEFAULT_RIDE_LAYER',
  'Performer',
  'engineStrip',
  'SCENE_RIDE_LAYER',
  'DIAL_RIDE_LAYER',
  'DEFAULT_PERFORM_LOOKAHEAD_SECONDS',
  'DEFAULT_DIAL_GLIDE_SECONDS',
  'DEFAULT_RESET_SECONDS',
  'MORPH_TIME_CONSTANTS',
  'PERFORM_META_KEY',
  'PERFORM_SET_VERSION',
  'MAX_RIDE',
  'DEFAULT_MORPH_BARS',
  'MAX_MORPH_BARS',
  'emptyPerformSet',
  'normalisePerformSet',
  'performSetOf',
  'isEmptyPerformSet',
  'shapeDial',
  'ladderTargets',
  'freeId',
  'withScene',
  'withoutScene',
  'moveScene',
  'withDial',
  'withoutDial',
  'withCue',
  'withoutCue',
  'withoutTrack',
  'sceneTracksIn',
  'drawPerformFollow',
  'resolvePerformFollow',
  'describePerformFollow',
  // Session grid (U31)
  'Session',
  'quantizeLaunch',
  'followTimeSeconds',
  'drawFollowAction',
  'resolveFollowAction',
  'defaultSlot',
  'slotAt',
  'findSlot',
  'findScene',
  'trackSlots',
  'sceneSlots',
  'LAUNCH_MODES',
  'FOLLOW_ACTION_KINDS',
  'DEFAULT_LAUNCH_QUANTIZE',
  // Agent-authored scores (U38)
  'SESSION_SCRIPT_SCHEMA',
  'SESSION_SCRIPT_CANON',
  'parseSessionScript',
  'validateSessionScript',
  'checkScriptCanon',
  'sessionScriptPromptContract',
  'selectTracksForSession',
  'pythonChooser',
  'PythonRandom',
  'compileScript',
  'compileScriptDetailed',
  'operationsToLoad',
  'estimatedVoiceProvider',
  'staticVoiceProvider',
  'synthesizeVoice',
  'renderScriptToWav',
  'scriptTools',
  'ScriptAuthoring',
  'createScriptAuthoring',
  // Controller arbitration and version history (U30)
  'Arbiter',
  'arbiterTargets',
  'arbitratedControlWriter',
  'controlWriteToOperation',
  'DEFAULT_ARBITRATION_POLICY',
  'policyTable',
  'formatPolicyTable',
  'decide',
  'HoldTable',
  'VersionHistory',
  'diffScores',
  'describeFieldChange',
  'memoryVersionStorage',
  'webStorageVersionStorage',
  'indexedDbVersionStorage',
  'CONTROLLER_AUTHOR',
  'SYSTEM_AUTHOR',
  'withVersionCheckpoints',
  // Patches: an instrument with its effects, or an effect chain
  'validatePatch',
  'patchDeviceParams',
  'patchDevices',
  'isInstrumentPatch',
  'isPatch',
  'createPatchDevice',
  'createPatchEffects',
  'replaceInserts',
  'capturePatch',
  'capturePatchDevice',
  // Patches into a score
  'patchEffectOps',
  'scoreDeviceFromPatch',
  // Which preset a device is on
  'presetIsOn',
  'currentPreset',
  'stepPreset',
  'atDefaults',
  'retiredPresets',
  // Offline render holds and the device traits hosted plug-ins use (U39)
  'RENDER_QUANTUM_FRAMES',
  'canHoldRender',
  'holdFrame',
  'holdRenderAt',
  'isEditorDevice',
  'isMeteredDevice',
  'isParamTextDevice',
  // Ableton Push 2 and 3
  'ABLETON_USB_VENDOR_ID',
  'PUSH_3_BUTTONS',
  'PUSH_AFTERTOUCH_MODES',
  'PUSH_BUTTONS',
  'PUSH_COMMANDS',
  'PUSH_DEFAULT_COLORS',
  'PUSH_DISPLAY_FRAME_BYTES',
  'PUSH_DISPLAY_HEIGHT',
  'PUSH_DISPLAY_KEEPALIVE_MS',
  'PUSH_DISPLAY_LINE_BYTES',
  'PUSH_DISPLAY_TIMEOUT_MS',
  'PUSH_DISPLAY_WIDTH',
  'PUSH_ENCODERS',
  'PUSH_ENCODER_STEPS_PER_TURN',
  'PUSH_FIRST_PAD_NOTE',
  'PUSH_FRAME_HEADER',
  'PUSH_IDENTITY_REQUEST',
  'PUSH_LAST_PAD_NOTE',
  'PUSH_LED_ANIMATIONS',
  'PUSH_LOWER_BUTTONS',
  'PUSH_MIDI_MODES',
  'PUSH_PAD_COLUMNS',
  'PUSH_PAD_ROWS',
  'PUSH_PALETTE_FIRST',
  'PUSH_PALETTE_SIZE',
  'PUSH_SCENE_BUTTONS',
  'PUSH_SYSEX_HEADER',
  'PUSH_TOUCH_NOTES',
  'PUSH_TOUCH_STRIP_DEFAULT',
  'PUSH_TOUCH_STRIP_LEDS',
  'PUSH_TRACK_ENCODERS',
  'PUSH_UPPER_BUTTONS',
  'PUSH_USB_FILTERS',
  'PUSH_USB_PRODUCT_IDS',
  'PUSH_WHITE_LEVELS',
  'PushDevice',
  'PushDisplay',
  'clampPushOctave',
  'decodePushFrame',
  'encodePushFrame',
  'findPushPorts',
  'isRgbPushButton',
  'isWebUsbSupported',
  'nearestDefaultPushColor',
  'parsePushIdentity',
  'parsePushPaletteEntry',
  'parsePushPortName',
  'parsePushSysex',
  'pushButtonAt',
  'pushButtonController',
  'pushButtonLedMessage',
  'pushButtons',
  'pushEncoderAt',
  'pushEncoderSteps',
  'pushEncoderValue',
  'pushLayoutBase',
  'pushModelForProductId',
  'pushPadAt',
  'pushPadLedMessage',
  'pushPadNote',
  'pushPadPitch',
  'pushPadPitches',
  'pushPixel',
  'pushSetDisplayBrightness',
  'pushSetLedBrightness',
  'pushSetPaletteEntry',
  'pushSetTouchStripLeds',
  'pushSysex',
  'pushTouchAt',
  'pushTouchStripFlags',
  'pushWhiteFor',
  // A score holds the instrument a track plays and a plug-in's own state
  'isStatefulDevice',
  'patchInstrumentOps',
  'DEFAULT_INSTRUMENT_TAIL_SECONDS',
  // The engine measures its own load; a host marks its own processors
  'LoadProbe',
  'loadCells',
  'LOAD_CELL_BUSY',
  'wasmMemoryBytes',
  'defaultLoadSamplerUrl',
  // A media element that follows a clock it is not the master of (video under audio)
  'followStep',
  'FOLLOW_SEEK_TOLERANCE',
  'FOLLOW_DRIFT_SEEK',
  'FOLLOW_MAX_SEEK_LEAD',
] as const

const dspSymbols = [
  'WasmDevice',
  'defineWasmDevice',
  'createPlateReverb',
  'createFdnReverb',
  'createStereoWidener',
  'createHallReverb',
  'createFetLimiter',
  'registerStockWasmDevices',
  'PLATE_REVERB_PARAMS',
  'WASM_DEVICE_PROCESSOR_NAME',
  'loadDuckerProcessor',
  'createWorkletDucker',
  'duckerProcessorUrl',
  'ensureProcessor',
  'WorkletDucker',
  'createTruePeakLimiter',
  'TRUE_PEAK_LIMITER_PARAMS',
  'truePeakLimiterLatencySamples',
  'createSpectralDrifter',
  'SPECTRAL_DRIFTER_PARAMS',
  'SPECTRAL_DRIFTER_DESCRIPTOR',
  'createEtherReverb',
  'ETHER_REVERB_PARAMS',
  'ETHER_REVERB_DESCRIPTOR',
  'createFeltPiano',
  'FELT_PIANO_PARAMS',
  'FELT_PIANO_DESCRIPTOR',
  // The offline patch renderer and the factory bank (ambient-live's browser)
  'isWasmDescriptor',
  'wasmDeviceDescriptor',
  'renderPatch',
  'canRenderPatch',
  'foldLoop',
  'peakOf',
  'noteFrequency',
  'DEFAULT_PHRASE_GAIN',
  'FACTORY_PRESETS',
  'FACTORY_CHAINS',
  'FACTORY_SOUNDS',
  'FACTORY_PRESET_CATEGORIES',
  'FACTORY_CHAIN_CATEGORIES',
  'FACTORY_PHRASES',
  'FACTORY_PEAK_DB',
  'PREVIEW_SECONDS',
  'CHAIN_PREVIEW_INPUT_SECONDS',
  'CHAIN_PREVIEW_PATCH',
  'CHAIN_PREVIEW_PHRASE',
  'factoryPreset',
  'factoryChain',
  'factorySound',
  'previewPhrase',
  'renderPresetPreview',
  'renderChainPreview',
  'renderFactorySound',
  // The packs: listed with the bank, their presets fetched apart from it
  'FACTORY_PACKS',
  'FACTORY_PACK_SIZE',
  'FACTORY_SOUND_PACK_SIZE',
  'FACTORY_CHAIN_PACK_SIZE',
  'factoryPack',
  'loadFactoryPacks',
  'loadFactoryPackSounds',
  'loadFactoryPackChains',
  // The bank in any key, and new sounds from a seed (ambient-live's master key and Generate)
  'FACTORY_MODES',
  'FACTORY_HOME_KEY',
  'PITCH_CLASS_NAMES',
  'CHORD_COLOURS',
  'GENERATED_KINDS',
  'factoryTranspose',
  'relativeMajorRoot',
  'pitchClassName',
  'transposeWords',
  'transposePatch',
  'transposePhrase',
  'transposeFactorySound',
  'varySound',
  'describeVariant',
  'variationAmounts',
  'VARIATION_KINDS',
  'VARIATION_LIMITS',
  'keyChord',
  'chordTakes',
  'chordTones',
  'chordName',
  'generateSound',
  'renderGeneratedSound',
  'validatePatch',
  'patchDeviceParams',
  'patchDevices',
  'isInstrumentPatch',
  'createPatchDevice',
  'createPatchEffects',
  'replaceInserts',
  'capturePatch',
  'SAMPLE_DEVICE_IDS',
  'STOCK_WASM_DEVICES',
] as const

const testingSymbols = [
  'MockAudioContext',
  'createMockContext',
  'advance',
  'configureMocks',
  // The plug-in host in memory (U39)
  'FakePluginHost',
  'FakeSocket',
  'FAKE_HOST_ADDRESS',
  'FAKE_REVERB',
  'FAKE_STATE',
  'FAKE_SYNTH',
  'fakeReverbParams',
  // An Ableton Link session in memory
  'FakeLinkSession',
  'FAKE_LINK_CLOCK_SKEW_MICROS',
  // A Push with no hardware
  'VirtualPush',
] as const

// What ambient-live's desktop app imports from `./native`.
const nativeSymbols = [
  'NativeHostClient',
  'findNativeHost',
  'NativeDevice',
  'nativeDeviceId',
  'registerNativeDevices',
  'scanNativeDevices',
  'nativeDeviceDescriptor',
  'registerMissingNativeDevices',
  'MissingNativeDevice',
  'isMissingNativeDevice',
  'isNativeDeviceId',
  'nativePluginName',
  'followNativeEdits',
  'captureNativeState',
  'DEFAULT_STATE_DELAY_MS',
  'DEFAULT_STATE_POLL_MS',
  'bridgeLatencyFor',
  'tidyParamText',
  'NATIVE_PROTOCOL_VERSION',
  // Ableton Link and Link Audio through the host
  'NativeLink',
  'LinkClockOffset',
  'OutputClock',
  'idleLinkState',
  'linkBeatAt',
  'linkMicrosAtBeat',
  'linkPhase',
  'nextBeatInPhase',
  'outputClockOffsetMs',
  'LinkAudioSender',
  'defaultLinkAudioPumpUrl',
  'defaultLinkTapProcessorUrl',
  'HOST_MESSAGE_LINK_AUDIO',
  'LINK_AUDIO_BLOCK_FRAMES',
  'LINK_AUDIO_HEADER_BYTES',
  'LINK_TAP_PROCESSOR_NAME',
  'LinkAudioReceiver',
  'defaultLinkAudioIntakeUrl',
  'defaultLinkSourceProcessorUrl',
  'HOST_MESSAGE_LINK_AUDIO_IN',
  'LINK_AUDIO_IN_HEADER_BYTES',
  'LINK_SOURCE_PROCESSOR_NAME',
  'encodeLinkAudioInBlock',
] as const

const wamSymbols = [
  'WamDevice',
  'ensureWamHost',
  'initializeWamHost',
  'describeWamDevice',
  'wamDeviceDescriptor',
  'registerWamDevice',
  'wamDeviceParam',
  'wamParamSpecs',
  'loadWamModule',
  'WAM_DEVICE_RAMP_SECONDS',
] as const

// Every value `./motion` exports: a host's stored motion is read with these
// names, so none may go quietly.
const motionSymbols = [
  'EASING_NAMES',
  'bezierOf',
  'cubicBezier',
  'curveOf',
  'isEasing',
  'MAX_BOUNCE',
  'SETTLED',
  'bounceCurve',
  'dampingRatio',
  'springCurve',
  'springDuration',
  'springValue',
  'NEUTRAL_PROFILE',
  'motionProfile',
  'DEFAULT_BOUNCE',
  'DEFAULT_STRENGTH',
  'NO_POSE',
  'PRESETS',
  'PRESET_NAMES',
  'presetDuration',
  'presetPose',
  'DEFAULT_KEYFRAME_EASING',
  'KEYFRAME_PROPERTIES',
  'keyframeAt',
  'keyframeTimes',
  'keyframeTrack',
  'trackValue',
  'valueAt',
  'withKeyframe',
  'withoutKeyframe',
  'DEFAULT_FADE',
  'layerMotionAt',
  'motionAt',
  'motionIssues',
  'resolveLayerMotion',
  'DEFAULT_SAMPLES',
  'DEFAULT_SHUTTER',
  'shutterTimes',
  'steadyClock',
  'ORIGIN',
  'restValues',
] as const

describe('public entries', () => {
  it.each(coreSymbols)('`.` exports %s', (name) => {
    expect((core as Record<string, unknown>)[name]).toBeDefined()
  })
  it.each(dspSymbols)('`./dsp` exports %s', (name) => {
    expect((dsp as Record<string, unknown>)[name]).toBeDefined()
  })
  it.each(testingSymbols)('`./testing` exports %s', (name) => {
    expect((testing as Record<string, unknown>)[name]).toBeDefined()
  })
  it.each(nativeSymbols)('`./native` exports %s', (name) => {
    expect((native as Record<string, unknown>)[name]).toBeDefined()
  })
  it.each(wamSymbols)('`./wam` exports %s', (name) => {
    expect((wam as Record<string, unknown>)[name]).toBeDefined()
  })
  it.each(motionSymbols)('`./motion` exports %s', (name) => {
    expect((motion as Record<string, unknown>)[name]).toBeDefined()
  })
  it('`./motion` exports nothing that is not pinned here', () => {
    expect(Object.keys(motion).sort()).toEqual([...motionSymbols].sort())
  })
})

describe('version', () => {
  it('LIVE_MIX_VERSION matches package.json', async () => {
    const pkg = JSON.parse(
      await readFile(new URL('../../package.json', import.meta.url), 'utf8'),
    ) as { version: string }
    expect(core.LIVE_MIX_VERSION).toBe(pkg.version)
  })
})
