// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Drone, shared with
// src/dsp/devices/drone.gen.ts:
//    0  shape: 0 Unison, 1 Octaves, 2 Fifths, 3 Harmonic series, 4 Just major, 5 Just minor, 6 Cluster, default 2
//    1  partials: 0..1, default 0.6
//    2  wave: 0..1, default 0.2
//    3  movement: 0..1, default 0.5
//    4  rate: 0.01..2 Hz, default 0.08
//    5  sub: 0..1, default 0.3
//    6  air: 0..1, default 0.15
//    7  cutoff: 60..16000 Hz, default 2400
//    8  attack: 0.01..30 s, default 3
//    9  release: 0.05..30 s, default 6
//   10  width: 0..1, default 0.7
//   11  hold: 0 Off, 1 On, default 0
//   12  volume: -48..6 dB, default -10

#pragma once

namespace livemix {
namespace drone {

enum Param : int {
  kShape = 0,
  kPartials = 1,
  kWave = 2,
  kMovement = 3,
  kRate = 4,
  kSub = 5,
  kAir = 6,
  kCutoff = 7,
  kAttack = 8,
  kRelease = 9,
  kWidth = 10,
  kHold = 11,
  kVolume = 12,
  kNumParams = 13,
};

inline constexpr float kParamMin[kNumParams] = {0.0f, 0.0f, 0.0f, 0.0f, 0.01f, 0.0f, 0.0f, 60.0f, 0.01f, 0.05f, 0.0f, 0.0f, -48.0f};
inline constexpr float kParamMax[kNumParams] = {6.0f, 1.0f, 1.0f, 1.0f, 2.0f, 1.0f, 1.0f, 16000.0f, 30.0f, 30.0f, 1.0f, 1.0f, 6.0f};
inline constexpr float kParamDefault[kNumParams] = {2.0f, 0.6f, 0.2f, 0.5f, 0.08f, 0.3f, 0.15f, 2400.0f, 3.0f, 6.0f, 0.7f, 0.0f, -10.0f};

}  // namespace drone
}  // namespace livemix
