// The sounds of the pack "Ashram Harp and Organ": its presets played, a hundred sounds to
// paint with. Numbers 20001 to 20100.

import { type PatchDevice } from '../../../core/devices/patch'
import { PRESETS } from '../packs/ashram'
import { type FactorySound } from '../types'
import { breathe, cycled, looped, packSounds, played, quarterTurn, soften } from './recipe'

// A tanpura's pluck stands 6 dB over the strings still ringing, which reads as a note and not
// as a drone: the limiter takes the pluck down and the compressor brings the ringing back up
// behind it, as the bank's own tanpura has it.
const LEVELLED: readonly PatchDevice[] = [
  { deviceId: 'fet-limiter', params: { inputGain: 30, outputGain: -12 } },
  {
    deviceId: 'ambient-comp',
    params: {
      threshold: -45,
      ratio: 8,
      attack: 10,
      release: 0.15,
      knee: 6,
      tails: 1,
      scLowCut: 40,
      makeup: 18,
    },
  },
]

// A held wind note is nearly a sine and comes out loud at the bank's peak: this lets each note
// speak and turns its body down a few dB after it.
const SPOKEN: PatchDevice = {
  deviceId: 'ambient-comp',
  params: { threshold: -50, ratio: 2, attack: 80, release: 0.3, knee: 6, tails: 1 },
}

// The drone strings behind a note, tuned to the white keys (A minor) and not to D minor.
const drones = (params: Readonly<Record<string, number>>): PatchDevice => ({
  deviceId: 'sympathetic',
  preset: 'Sitar drone',
  params: { root: 9, mode: 1, ...params },
})

export const SOUNDS: readonly FactorySound[] = packSounds('ashram', 20000, PRESETS, [
  {
    n: 1,
    id: 'morning-tanpura-d',
    name: 'Morning tanpura {D}',
    kind: 'drone',
    description:
      'Four buzzing strings on {D} and {A} plucked round, two rounds to the loop, in a small plate.',
    preset: 'ashram-morning-tanpura',
    set: { speed: 4.047, decay: 30 },
    effects: [
      ...LEVELLED,
      { deviceId: 'plate-reverb', preset: 'Small plate', params: { mix: 0.25 } },
    ],
    ...looped(8, 4.15, 0.45, [50]),
  },
  {
    n: 2,
    id: 'open-bridge-e',
    name: 'Open bridge {E}',
    kind: 'drone',
    description:
      'A quick round on {E} and {B} with the bridge buzzing as far as it goes, through a valve.',
    preset: 'ashram-open-bridge',
    set: { speed: 2.698, decay: 30 },
    effects: [
      ...LEVELLED,
      { deviceId: 'saturator', preset: 'Tube preamp', params: { driveDb: 7, outputDb: -4 } },
      { deviceId: 'hall-reverb', preset: 'Room', params: { mix: 0.3 } },
    ],
    ...looped(8, 2.77, 0.45, [52]),
  },
  {
    n: 3,
    id: 'reed-drone-box-f',
    name: 'Reed drone box {F}',
    kind: 'drone',
    description: 'A reedy {F} and the {C} above it held steady with a little air, on reel tape.',
    preset: 'ashram-reed-drone-box',
    set: { movement: 0.08 },
    // Held level: without the limiter it swelled enough to read as a pad in three keys.
    then: [
      { deviceId: 'ambient-limiter', params: { ceiling: -12, gain: 14, release: 0.3, ride: 0 } },
    ],
    ...looped(8, 5, 3, [41]),
  },
  {
    n: 4,
    id: 'arco-bass-e',
    name: 'Arco bass {E}',
    kind: 'drone',
    description:
      'A low {E} and the {B} over it bowed with weight and a slow vibrato, in a small room.',
    preset: 'ashram-arco-bass',
    then: [quarterTurn(8)],
    tuning: 'whole-cycles',
    ...looped(8, 4, 3, [40, [47, 0.7]]),
  },
  {
    n: 5,
    id: 'prayer-harmonium-a',
    name: 'Prayer harmonium {A}',
    kind: 'drone',
    description:
      'A hand-pumped harmonium holding {A} and {E}, close on quarter-inch tape in a room.',
    preset: 'ashram-prayer-hall-harmonium',
    set: { bellows: 0.2, celeste: 0 },
    then: [quarterTurn(8)],
    tuning: 'whole-cycles',
    ...looped(8, 4, 3, [45, 52]),
  },
  {
    n: 6,
    id: 'square-wave-organ-e',
    name: 'Square wave organ {E}',
    kind: 'drone',
    description: 'A hollow square on {E} and {B} with its sub octave, in a slow rotating speaker.',
    preset: 'ashram-square-wave-organ',
    then: [quarterTurn(8)],
    tuning: 'whole-cycles',
    ...looped(8, 4, 3, [52, 59]),
  },
  {
    n: 7,
    id: 'fourth-string-dusk-a',
    name: 'Fourth string dusk {A}',
    kind: 'drone',
    description:
      'A tanpura on {A} with its first string on the {D} below, a slow phaser turning it in a hall.',
    preset: 'ashram-fourth-string-dusk',
    set: { speed: 2.698, decay: 30 },
    effects: [
      ...LEVELLED,
      {
        deviceId: 'phaser',
        preset: 'Slow swirl',
        params: { centerHz: 900, rate: 0.125, depth: 50, mix: 0.3 },
      },
      { deviceId: 'fdn-reverb', preset: 'Hall', params: { mix: 0.3 } },
    ],
    ...looped(8, 2.77, 0.45, [57]),
  },
  {
    n: 8,
    id: 'pedal-tone-c',
    name: 'Pedal tone {C}',
    kind: 'drone',
    description:
      'One low {C} on the organ pedals with its sub rank, under a slow bass rotor in a hall.',
    preset: 'ashram-pedal-tone',
    set: { celeste: 0 },
    effects: [
      {
        deviceId: 'rotary',
        preset: 'Chorale',
        params: { hornDepth: 0.3, drumDepth: 0.4, balance: 0.3, drive: 0.35 },
      },
      { deviceId: 'hall-reverb', preset: 'Hall', params: { mix: 0.25 } },
    ],
    then: [quarterTurn(8)],
    tuning: 'whole-cycles',
    ...looped(8, 5, 3, [48]),
  },
  {
    n: 9,
    id: 'pedal-synth-a',
    name: 'Pedal synth {A}',
    kind: 'drone',
    description: 'One held {A}, two oscillators beating over a sub, in a slow phaser and a plate.',
    preset: 'ashram-pedal-synth',
    set: { beat: 5.9 },
    effects: [
      { deviceId: 'phaser', preset: 'Bass safe', params: { rate: 0.125, mix: 0.25 } },
      { deviceId: 'plate-reverb', preset: 'Small plate', params: { mix: 0.22 } },
    ],
    then: [quarterTurn(8)],
    tuning: 'whole-cycles',
    ...looped(8, 4, 3, [45]),
  },
  {
    n: 10,
    id: 'alto-flute-dusk-g',
    name: 'Alto flute dusk {G}',
    kind: 'drone',
    description:
      'Three low flutes held on {G}, {D} and {G}, blown softly with breath, over tape hiss in a hall.',
    preset: 'ashram-alto-flute-dusk',
    set: { vibrato: 0.15, breath: 0.4 },
    effects: [
      // A flute's breath wanders by a couple of dB: this holds it level.
      {
        deviceId: 'ambient-comp',
        params: {
          threshold: -60,
          ratio: 4,
          attack: 20,
          release: 0.15,
          knee: 6,
          tails: 1,
          makeup: 24,
        },
      },
      { deviceId: 'noise-floor', preset: 'Tape floor', params: { level: -48 } },
      { deviceId: 'hall-reverb', preset: 'Hall', params: { mix: 0.32 } },
    ],
    then: [quarterTurn(8)],
    tuning: 'whole-cycles',
    ...looped(8, 4, 3, [
      [55, 0.75],
      [62, 0.7],
      [67, 0.7],
    ]),
  },
  {
    n: 11,
    id: 'low-brass-floor-f',
    name: 'Low brass floor {F}',
    kind: 'drone',
    description:
      'Low brass holding {F} and the {C} above it, one player a note, on tape in a hall.',
    preset: 'ashram-low-brass-floor',
    set: { section: 0 },
    then: [quarterTurn(8)],
    tuning: 'whole-cycles',
    ...looped(8, 7, 3, [41, 48]),
  },
  {
    n: 12,
    id: 'cassette-tanpura-c',
    name: 'Cassette tanpura {C}',
    kind: 'drone',
    description:
      'A closed, woody tanpura on {C} and {G} as a home cassette kept it, with hiss, in a room.',
    preset: 'ashram-cassette-tanpura',
    set: { speed: 2.698, decay: 30 },
    effects: [
      ...LEVELLED,
      { deviceId: 'tape', preset: 'Cassette four-track', params: { hiss: 0.35 } },
      { deviceId: 'ether-reverb', preset: 'Room', params: { mix: 0.3, decay: 1.6 } },
    ],
    ...looped(8, 2.77, 0.45, [48]),
  },
  {
    n: 13,
    id: 'sunday-organ-g',
    name: 'Sunday organ {G}',
    kind: 'drone',
    description:
      'A church organ on {G} and {D}, its tremulant nearly off, through a combo amplifier and its spring.',
    preset: 'ashram-sunday-organ',
    set: { tremulant: 0.05 },
    ...looped(8, 4, 3, [55, 62, 67]),
  },
  {
    n: 14,
    id: 'synth-vowels-c',
    name: 'Synth vowels {C}',
    kind: 'drone',
    description:
      'A wavetable {C}, {G} and {C} drifting between vowels once a loop, on a worn cassette in a hall.',
    preset: 'ashram-synth-vowels',
    set: { rate: 0.125 },
    effects: [
      {
        deviceId: 'patina',
        preset: 'Worn cassette',
        params: { wobble: 0.2, noise: 0.2, wear: 0.25 },
      },
      { deviceId: 'hall-reverb', preset: 'Hall', params: { mix: 0.3 } },
    ],
    // Root, fifth and octave, held level: with a third on top and the vowels swelling it read as
    // a phrase in five keys of the twelve.
    then: [
      { deviceId: 'ambient-limiter', params: { ceiling: -12, gain: 17, release: 0.3, ride: 0 } },
    ],
    ...looped(8, 6, 3, [48, 55, 60]),
  },
  {
    n: 15,
    id: 'chorale-organ-d',
    name: 'Chorale organ {D}',
    kind: 'pad',
    description:
      'Flutes and a little reed on {D} and {A}, swelling in a slowly turning speaker and a long plate.',
    preset: 'ashram-chorale-organ',
    then: [breathe(0.125, 0.65)],
    ...looped(8, 5, 3, [50, 57]),
  },
  {
    n: 16,
    id: 'phased-flutes-dm',
    name: 'Phased flutes {D}m',
    kind: 'pad',
    description:
      'Soft organ flutes on {D} minor swept once a loop by a deep eight-stage phaser, in a hall.',
    preset: 'ashram-phased-flutes',
    effects: [
      {
        deviceId: 'phaser',
        preset: 'Deep eight-stage',
        params: { rate: 0.125, feedback: 75, depth: 90 },
      },
      { deviceId: 'hall-reverb', preset: 'Hall', params: { mix: 0.35 } },
    ],
    then: [{ deviceId: 'stereo-widener', params: { width: 0.4 } }],
    ...looped(8, 4, 3, [50, 57, 65]),
  },
  {
    n: 17,
    id: 'overtone-floor-g',
    name: 'Overtone floor {G}',
    kind: 'pad',
    description:
      'The harmonic series of a low {G}, its partials wandering and drifting in a long plate.',
    preset: 'ashram-overtone-floor',
    then: [{ deviceId: 'stereo-widener', params: { width: 0.3 } }],
    ...looped(8, 5, 3, [43]),
  },
  {
    n: 18,
    id: 'folded-low-tone-g',
    name: 'Folded low tone {G}',
    kind: 'pad',
    description:
      'A low {G} whose overtones fold open and shut, swelling in a slow phaser and a hall.',
    preset: 'ashram-folded-low-tone',
    effects: [
      { deviceId: 'phaser', preset: 'Deep eight-stage', params: { rate: 0.125, mix: 0.4 } },
      { deviceId: 'fdn-reverb', preset: 'Hall', params: { mix: 0.3 } },
    ],
    then: [breathe(0.125, 0.45)],
    ...looped(8, 5, 3, [43]),
  },
  {
    n: 19,
    id: 'still-strings-b',
    name: 'Still strings {B}',
    kind: 'pad',
    description:
      'Three players on each of two {B}s an octave apart with no vibrato, over drone strings in a hall.',
    preset: 'ashram-still-strings',
    effects: [
      drones({ sympathy: 0.6, decay: 8, mix: 0.3, width: 0.7 }),
      { deviceId: 'hall-reverb', preset: 'Hall', params: { midDecay: 3.2, mix: 0.35 } },
    ],
    then: [quarterTurn(8)],
    tuning: 'whole-cycles',
    ...looped(8, 6, 3, [59, [71, 0.7]]),
  },
  {
    n: 20,
    id: 'evening-voices-cmaj7',
    name: 'Evening voices {C}maj7',
    kind: 'pad',
    description:
      'A small room of singers on an open ah, rising on {C} major seventh and dying in a plate.',
    preset: 'ashram-evening-voices',
    set: { ensemble: 0.2, vibrato: 3, attack: 1.4 },
    ...played(
      12,
      [
        [0, 5.5, 60],
        [0, 5.5, 64],
        [0, 5.5, 67],
        [0, 5.5, 71, 0.6],
      ],
      2.5,
    ),
  },
  {
    n: 21,
    id: 'slow-brass-dawn-f',
    name: 'Slow brass dawn {F}',
    kind: 'pad',
    description:
      'Soft synthesiser horns on {F} major that swell for six seconds and let go, in a long plate.',
    preset: 'ashram-slow-brass-dawn',
    ...played(
      14,
      [
        [0, 6, 41],
        [0, 6, 48],
        [0, 6, 57],
      ],
      3,
    ),
  },
  {
    n: 22,
    id: 'wide-synth-strings-em7',
    name: 'Wide synth strings {E}m7',
    kind: 'pad',
    description:
      'Polysynth strings on a wide {E} minor seventh, detuned and slowly phased in a hall.',
    preset: 'ashram-wide-synth-strings',
    ...played(
      12,
      [
        [0, 5.5, 52],
        [0, 5.5, 59],
        [0, 5.5, 67],
        [0, 5.5, 74],
      ],
      2.5,
    ),
  },
  {
    n: 23,
    id: 'lamp-lit-pad-d',
    name: 'Lamp-lit pad {D}',
    kind: 'pad',
    description:
      'A warm, dull pad on {D}, {A} and {E} that comes in slowly and fades, darkened, in a hall.',
    preset: 'ashram-lamp-lit-pad',
    ...played(
      14,
      [
        [0, 5.5, 50],
        [0, 5.5, 57],
        [0, 5.5, 64],
      ],
      3,
    ),
  },
  {
    n: 24,
    id: 'still-steel-c',
    name: 'Still steel {C}',
    kind: 'pad',
    description:
      'Steel notes on {C} major with no vibrato, hanging in a slow chorus and a long plate.',
    preset: 'ashram-still-steel',
    // The preset's chorus at a rate that comes round with the loop, and narrowed: it thinned out in mono.
    effects: [
      { deviceId: 'chorus', preset: 'Slow drift', params: { rate: 0.125, spread: 60, mix: 0.3 } },
      { deviceId: 'plate-reverb', preset: 'Long plate', params: { mix: 0.35 } },
    ],
    then: [{ deviceId: 'stereo-widener', params: { width: 0.35 } }],
    ...looped(8, 5, 3, [60, 64, 67]),
  },
  {
    n: 25,
    id: 'held-syllable-am',
    name: 'Held syllable {A}m',
    kind: 'pad',
    description:
      'One instant of a sung {A} minor held as a cloud that swells once a loop, in a hall that sings ah.',
    preset: 'ashram-held-syllable',
    set: { spread: 0.2 },
    source: 'choir-chord-am',
    then: [{ deviceId: 'stereo-widener', params: { width: 0.3 } }, breathe(0.125, 0.4)],
    ...looped(8, 5, 3, [60]),
  },
  {
    n: 26,
    id: 'reel-strings-dm',
    name: 'Reel strings {D}m',
    kind: 'pad',
    description:
      'A violin section on {D} minor played from worn tape, swept by a slow flanger in a plate.',
    preset: 'ashram-reel-strings',
    set: { age: 0.25, vibrato: 0.3, players: 0.4 },
    ...played(
      12,
      [
        [0, 5, 62],
        [0, 5, 69],
        [0, 5, 77],
      ],
      2.5,
    ),
  },
  {
    n: 27,
    id: 'low-desks-a',
    name: 'Low desks {A}',
    kind: 'pad',
    description:
      'Cellos and basses holding a low {A} and {E} with slow, full bows, on tape in a hall.',
    preset: 'ashram-low-desks',
    set: { air: 0.15 },
    ...looped(8, 5, 3, [45, 52]),
  },
  {
    n: 28,
    id: 'sung-reply-dm',
    name: 'Sung reply {D}m',
    kind: 'pad',
    description:
      'A chord of drifting vowels on {D} minor, sung once and sung back by a tape echo in a hall.',
    preset: 'ashram-sung-reply',
    set: { ensemble: 0.4 },
    ...played(
      12,
      [
        [0, 3.5, 50],
        [0, 3.5, 57],
        [0, 3.5, 65],
      ],
      2.5,
    ),
  },
  {
    n: 29,
    id: 'swaying-strings-a',
    name: 'Swaying strings {A}',
    kind: 'pad',
    description:
      'A warm section on {A} and {E} with wide vibrato, its pitch swaying together, in a long plate.',
    preset: 'ashram-swaying-strings',
    set: { vibrato: 10 },
    effects: [
      {
        deviceId: 'tremolo',
        preset: 'Slow chorus',
        params: { rate: 0.8, depth: 0.5, phase: 0, drift: 0.6, mix: 1 },
      },
      { deviceId: 'plate-reverb', preset: 'Long plate', params: { mix: 0.32 } },
    ],
    ...played(
      12,
      [
        [0, 5, 57],
        [0, 5, 64],
      ],
      2.5,
    ),
  },
  {
    n: 30,
    id: 'slow-cycle-a',
    name: 'Slow cycle {A}',
    kind: 'pad',
    description:
      'Long strings on {A} and {E} plucked two seconds apart, rising and sinking in a long plate.',
    preset: 'ashram-slow-cycle',
    set: { speed: 8.094, spread: 0.4 },
    effects: [
      ...LEVELLED,
      { deviceId: 'plate-reverb', preset: 'Long plate', params: { mix: 0.35 } },
      { deviceId: 'stereo-widener', params: { width: 0.35 } },
      breathe(0.125, 0.45),
    ],
    ...looped(16, 8.3, 0.6, [57]),
  },
  {
    n: 31,
    id: 'top-octave-strings-c',
    name: 'Top octave strings {C}',
    kind: 'pad',
    description:
      'A high {C} major on the top octave of a string keyboard, thin and clear, in a long plate.',
    preset: 'ashram-top-octave-strings',
    ...played(
      12,
      [
        [0, 5, 72],
        [0, 5, 76],
        [0, 5, 79],
      ],
      2.5,
    ),
  },
  {
    n: 32,
    id: 'keyboard-strings-f',
    name: 'Keyboard strings {F}',
    kind: 'pad',
    description: 'A seventies string keyboard on {F} major, through a slow phaser and a plate.',
    preset: 'ashram-slow-keyboard-strings',
    set: { width: 0.3, ensemble: 0.5 },
    effects: [
      {
        deviceId: 'phaser',
        preset: 'Warm six-stage',
        params: { rate: 0.125, depth: 70, stereo: 30 },
      },
      { deviceId: 'plate-reverb', preset: 'Medium plate', params: { mix: 0.3 } },
      { deviceId: 'stereo-widener', params: { width: 0.3 } },
    ],
    ...looped(8, 8, 3, [41, 48, 57, 60]),
  },
  {
    n: 33,
    id: 'cassette-loop-bed-g',
    name: 'Cassette loop bed {G}',
    kind: 'pad',
    description:
      'A tanpura on {G} and {D}, low on a wobbling loop that swells, through a worn cassette and a spring.',
    preset: 'ashram-cassette-loop-bed',
    set: { fine: 0 },
    source: 'tanpura-d',
    then: [breathe(0.125, 0.5)],
    ...looped(8, 4, 3, [65]),
  },
  {
    n: 34,
    id: 'rubbed-bowl-g',
    name: 'Rubbed bowl {G}',
    kind: 'pad',
    description:
      'Two singing bowls on {G} and {D} rubbed and kept singing, their modes beating in a long plate.',
    preset: 'ashram-rubbed-bowl',
    then: [{ deviceId: 'stereo-widener', params: { width: 0.2 } }],
    ...looped(8, 6, 3, [55, [62, 0.6]]),
  },
  {
    n: 35,
    id: 'conch-breath-a',
    name: 'Conch breath {A}',
    kind: 'texture',
    description:
      'A band of blown noise around {A} that swells and breathes slowly, in a long plate.',
    preset: 'ashram-conch-breath',
    set: { breatheRate: 0.125, resonance: 6 },
    effects: [
      { deviceId: 'ambient-limiter', params: { ceiling: -6, gain: 12, release: 3 } },
      { deviceId: 'plate-reverb', preset: 'Long plate', params: { mix: 0.35 } },
    ],
    then: [{ deviceId: 'stereo-widener', params: { width: 0.35 } }],
    ...looped(8, 5, 3, [57]),
  },
  {
    n: 36,
    id: 'canyon-wind-gusts',
    name: 'Canyon wind gusts',
    kind: 'texture',
    description:
      'A warm wind that gusts slowly and whistles a little on {D}, in a large open space.',
    preset: 'ashram-warm-canyon-wind',
    ...looped(8, 4, 3, [62]),
  },
  {
    n: 37,
    id: 'lamp-flame-close',
    name: 'Lamp flame close',
    kind: 'texture',
    description:
      'A small flame heard close: a soft flutter and a sparse crackle, narrow, in a room.',
    preset: 'ashram-lamp-flame',
    ...looped(8, 3, 2, [60]),
  },
  {
    n: 38,
    id: 'dorian-air-d',
    name: 'Dorian air {D}',
    kind: 'texture',
    description:
      'Soft bands of noise that turn {D} and {A} into a breathy dorian chord, phased in a hall.',
    preset: 'ashram-dorian-air',
    set: { breatheRate: 0.25, resonance: 6 },
    effects: [
      { deviceId: 'ambient-limiter', params: { ceiling: -6, gain: 10, release: 3 } },
      { deviceId: 'phaser', preset: 'Slow swirl', params: { rate: 0.125, mix: 0.35 } },
      { deviceId: 'fdn-reverb', preset: 'Hall', params: { mix: 0.3 } },
    ],
    ...looped(8, 5, 3, [50, [57, 0.7]]),
  },
  {
    n: 39,
    id: 'prayer-hall-rain',
    name: 'Prayer hall rain',
    kind: 'texture',
    description: 'Heavy rain on a wide roof heard from inside: a dense hiss with a hall behind it.',
    instrument: {
      deviceId: 'atmosphere',
      preset: 'Distant downpour',
      params: { density: 0.95, movement: 0.15, attack: 0.5, width: 0.6 },
    },
    effects: [{ deviceId: 'hall-reverb', preset: 'Hall', params: { mix: 0.4 } }],
    ...looped(8, 2, 2, [55]),
  },
  {
    n: 40,
    id: 'canyon-road-crickets',
    name: 'Canyon road crickets',
    kind: 'texture',
    description:
      'Crickets along a canyon road after dark, scattered in grains, rising and falling far off in a large space.',
    instrument: {
      deviceId: 'outdoors',
      preset: 'Evening field',
      params: { distance: 0.9, movement: 0.5, tone: 0.55, attack: 1, width: 0.8 },
    },
    effects: [
      {
        deviceId: 'grain-cloud',
        preset: 'Soft cloud',
        params: { size: 180, density: 14, scatter: 1, feedback: 0.3, mix: 0.7 },
      },
      { deviceId: 'expanse', preset: 'Open space', params: { decay: 6, mix: 0.3, width: 0.6 } },
    ],
    then: [breathe(0.125, 0.6)],
    ...looped(8, 6, 2, [43, 48, 53, 59, 64, 69, 74, 79]),
  },
  {
    n: 41,
    id: 'creek-below-the-hall',
    name: 'Creek below the hall',
    kind: 'texture',
    description: 'A small creek heard from the bank: single bubbles over a soft rush, in a room.',
    instrument: {
      deviceId: 'outdoors',
      preset: 'Small stream',
      params: { density: 0.5, distance: 0.3, attack: 0.5, width: 0.8 },
    },
    effects: [{ deviceId: 'hall-reverb', preset: 'Room', params: { mix: 0.2 } }],
    ...looped(8, 3, 2, [62]),
  },
  {
    n: 42,
    id: 'old-pressing-crackle',
    name: 'Old pressing crackle',
    kind: 'texture',
    description:
      'The run-out groove of a worn pressing: hiss, clicks and a turning rumble, in a room.',
    instrument: {
      deviceId: 'atmosphere',
      preset: 'Old record',
      params: { density: 0.55, tone: 0.4, width: 0.6 },
    },
    effects: [soften(30), { deviceId: 'hall-reverb', preset: 'Room', params: { mix: 0.2 } }],
    ...looped(8, 2, 2, [55]),
  },
  {
    n: 43,
    id: 'surf-below-the-bluff',
    name: 'Surf below the bluff',
    kind: 'texture',
    description: 'Long waves breaking far below and running back, heard across a large open space.',
    instrument: {
      deviceId: 'atmosphere',
      preset: 'Slow shore',
      params: { movement: 0.25, attack: 0.5, width: 0.6 },
    },
    effects: [
      { deviceId: 'expanse', preset: 'Open space', params: { decay: 6, mix: 0.25, width: 0.6 } },
    ],
    ...looped(16, 6, 3.5, [57]),
  },
  {
    n: 44,
    id: 'lotus-pond-frogs',
    name: 'Lotus pond frogs',
    kind: 'texture',
    description:
      'A pond full of frogs at dusk, croaks and peeps on every side, in the air of a hall.',
    instrument: {
      deviceId: 'outdoors',
      preset: 'Pond at dusk',
      params: { density: 1, distance: 0.65, attack: 1 },
    },
    effects: [soften(12), { deviceId: 'fdn-reverb', preset: 'Hall', params: { mix: 0.2 } }],
    ...looped(16, 3, 3, [41, 48, 53, 60, 64]),
  },
  {
    n: 45,
    id: 'thunder-up-the-canyon',
    name: 'Thunder up the canyon',
    kind: 'texture',
    description:
      'A storm far up the canyon, its rolls of thunder overlapping in a large open space.',
    instrument: {
      deviceId: 'outdoors',
      preset: 'Far storm',
      params: { density: 1, tone: 0.6, movement: 0.5, width: 0.8 },
    },
    effects: [
      soften(8),
      { deviceId: 'expanse', preset: 'Open space', params: { decay: 6, mix: 0.3, width: 0.6 } },
    ],
    ...looped(16, 1, 3, [36, 41, 48, 55]),
  },
  {
    n: 46,
    id: 'saffron-harp-a',
    name: 'Saffron harp {A}',
    kind: 'oneshot',
    description:
      'One {A} plucked mid-string on a concert harp, turned by a slow phaser in a small plate.',
    preset: 'ashram-saffron-harp',
    ...played(8, [[0, 1.2, 69]], 1.5),
  },
  {
    n: 47,
    id: 'wound-string-d',
    name: 'Wound string {D}',
    kind: 'oneshot',
    description:
      'The low wire-wound {D} of the harp plucked full and left to hum in a dark spring.',
    preset: 'ashram-wound-strings',
    ...played(8, [[0, 2.5, 38]], 1.5),
  },
  {
    n: 48,
    id: 'harp-over-drone-g',
    name: 'Harp over drone {G}',
    kind: 'oneshot',
    description:
      'One soft harp {G} that wakes a bank of drone strings, humming on behind it in a hall.',
    preset: 'ashram-harp-over-drone',
    effects: [
      drones({ decay: 7, mix: 0.3, width: 0.6 }),
      { deviceId: 'hall-reverb', preset: 'Hall', params: { mix: 0.3 } },
    ],
    ...played(10, [[0, 2, 55]], 2),
  },
  {
    n: 49,
    id: 'late-set-harp-c',
    name: 'Late set harp {C}',
    kind: 'oneshot',
    description:
      'A short, dry {C} plucked hard near the soundboard of the harp, on tape in a room.',
    preset: 'ashram-late-set-harp',
    set: { decay: 0.9 },
    then: [{ deviceId: 'ambient-limiter', params: { ceiling: -12, gain: 18 } }],
    ...played(3, [[0, 0.8, 72]], 1),
  },
  {
    n: 50,
    id: 'brass-bowl-b',
    name: 'Brass bowl {B}',
    kind: 'oneshot',
    description:
      'A metal bowl struck on a low {B} with a slow beat in its long ring, set in a hall.',
    preset: 'ashram-brass-bowl',
    // On B its untuned overtone lies between white keys. The compressor lets the stroke through
    // and turns the ring down: a ring this even is as loud as a held note.
    effects: [
      {
        deviceId: 'ambient-comp',
        params: { threshold: -36, ratio: 2, attack: 120, release: 3, knee: 6, tails: 0 },
      },
      { deviceId: 'hall-reverb', preset: 'Hall', params: { midDecay: 3.5, mix: 0.3 } },
    ],
    ...played(12, [[0, 3, 47]], 3),
  },
  {
    n: 51,
    id: 'small-hand-bell-e',
    name: 'Small hand bell {E}',
    kind: 'oneshot',
    description:
      'One small bright bell on a high {E}, short, with a clashing overtone, in a spring tank.',
    preset: 'ashram-small-hand-bells',
    set: { detune: 2 },
    effects: [
      { deviceId: 'spring-reverb', preset: 'Two spring tank', params: { drip: 0, mix: 0.2 } },
    ],
    then: [{ deviceId: 'stereo-widener', params: { width: 0.4 } }],
    ...played(5, [[0, 0.5, 76]], 1.5),
  },
  {
    n: 52,
    id: 'courtyard-bell-d',
    name: 'Courtyard bell {D}',
    kind: 'oneshot',
    description:
      'A bronze bell struck once on {D} and heard from down the hall, its hum hanging on.',
    preset: 'ashram-courtyard-bell',
    set: { position: 0.667 },
    then: [{ deviceId: 'ambient-limiter', params: { ceiling: -12, gain: 8 } }],
    ...played(12, [[0, 4, 62]], 3),
  },
  {
    n: 53,
    id: 'tuned-hand-drum-a',
    name: 'Tuned hand drum {A}',
    kind: 'oneshot',
    description:
      'A tongue drum struck firmly on {A} and damped short like a hand drum, on tape in a room.',
    preset: 'ashram-tuned-hand-drum',
    then: [{ deviceId: 'ambient-limiter', preset: 'Pinned' }],
    ...played(3, [[0, 0.4, 57]], 0.8),
  },
  {
    n: 54,
    id: 'late-set-piano-d',
    name: 'Late set piano {D}',
    kind: 'oneshot',
    description:
      'A chord in fourths up from {D} on a bare piano with hard hammers, close on tape in a room.',
    preset: 'ashram-late-set-piano',
    then: [{ deviceId: 'ambient-limiter', preset: 'Pinned' }],
    ...played(
      6,
      [
        [0, 2.5, 50],
        [0, 2.5, 55],
        [0, 2.5, 60],
        [0, 2.5, 65],
      ],
      1.5,
    ),
  },
  {
    n: 55,
    id: 'phased-tines-em7',
    name: 'Phased tines {E}m7',
    kind: 'oneshot',
    description:
      'A soft {E} minor seventh on a hollow electric piano, through a four-stage phaser in a plate.',
    preset: 'ashram-phased-tines',
    ...played(
      8,
      [
        [0, 3, 52],
        [0, 3, 59],
        [0, 3, 62],
        [0, 3, 67],
      ],
      1.5,
    ),
  },
  {
    n: 56,
    id: 'driven-tine-a',
    name: 'Driven tine {A}',
    kind: 'oneshot',
    description:
      'One low {A} played hard so the pickup barks, into a valve stage and a two-spring tank.',
    preset: 'ashram-driven-tines',
    // The valve stage squares the note off, which is loud: the compressor keeps the bark and
    // turns down what follows it.
    effects: [
      { deviceId: 'analog-drive', preset: 'Triode glow', params: { drive: 0.4, output: -3 } },
      {
        deviceId: 'ambient-comp',
        params: { threshold: -40, ratio: 2, attack: 60, release: 2, knee: 6, tails: 0 },
      },
      { deviceId: 'spring-reverb', preset: 'Two spring tank', params: { mix: 0.22 } },
    ],
    ...played(4, [[0, 0.7, 45]], 1.2),
  },
  {
    n: 57,
    id: 'tremolo-dusk-fmaj7',
    name: 'Tremolo dusk {F}maj7',
    kind: 'oneshot',
    description: 'An {F} major seventh on tines pulsing from side to side, on tape in a hall.',
    preset: 'ashram-tremolo-dusk',
    ...played(
      8,
      [
        [0, 3.5, 53],
        [0, 3.5, 57],
        [0, 3.5, 60],
        [0, 3.5, 64],
      ],
      1.5,
    ),
  },
  {
    n: 58,
    id: 'rotor-tines-g7',
    name: 'Rotor tines {G}7',
    kind: 'oneshot',
    description:
      'A {G} seventh chord on the electric piano spun by heavy fast rotors, in a small plate.',
    preset: 'ashram-rotor-tines',
    ...played(
      6,
      [
        [0, 2.5, 55],
        [0, 2.5, 59],
        [0, 2.5, 62],
        [0, 2.5, 65],
      ],
      1.5,
    ),
  },
  {
    n: 59,
    id: 'folded-harp-g',
    name: 'Folded harp {G}',
    kind: 'oneshot',
    description:
      'One bright folded pluck on {G} that dulls as it dies, like a wire harp, in a plate.',
    preset: 'ashram-folded-harp',
    effects: [{ deviceId: 'plate-reverb', preset: 'Medium plate', params: { mix: 0.3 } }],
    then: [{ deviceId: 'ambient-limiter', params: { ceiling: -12, gain: 8 } }],
    ...played(6, [[0, 1, 67]], 1.5),
  },
  {
    n: 60,
    id: 'plectrum-lute-e',
    name: 'Plectrum lute {E}',
    kind: 'oneshot',
    description: 'One nylon {E} picked by the bridge, nasal and close, driven onto tape in a room.',
    preset: 'ashram-plectrum-lute',
    then: [{ deviceId: 'ambient-limiter', params: { ceiling: -12, gain: 18 } }],
    ...played(4, [[0, 1.5, 52]], 1),
  },
  {
    n: 61,
    id: 'brushed-chord-dm',
    name: 'Brushed chord {D}m',
    kind: 'oneshot',
    description:
      'Two octaves of {D} minor brushed almost at once, dull and close, on a home cassette.',
    preset: 'ashram-brushed-chord',
    ...played(
      7,
      [
        [0, 3, 50],
        [0, 3, 53],
        [0, 3, 57],
      ],
      1.5,
    ),
  },
  {
    n: 62,
    id: 'quick-bright-strum-c',
    name: 'Quick bright strum {C}',
    kind: 'oneshot',
    description:
      'A short one-octave strum of {C} major on thin bright strings, in a tremolo and a spring.',
    preset: 'ashram-quick-bright-strum',
    ...played(
      4,
      [
        [0, 1.5, 60],
        [0, 1.5, 64],
        [0, 1.5, 67],
      ],
      1,
    ),
  },
  {
    n: 63,
    id: 'bass-vamp-f',
    name: 'Bass vamp {F}',
    kind: 'oneshot',
    description: 'One round plucked bass {F} that closes in a second, levelled, in a room.',
    preset: 'ashram-bass-vamp',
    then: [{ deviceId: 'ambient-limiter', preset: 'Pinned' }],
    ...played(3, [[0, 1.2, 41]], 0.8),
  },
  {
    n: 64,
    id: 'sustained-lead-a',
    name: 'Sustained lead {A}',
    kind: 'oneshot',
    description:
      'One {A} on the neck pickup held for four seconds through a warm driven stack, in a long plate.',
    preset: 'ashram-sustained-lead',
    ...played(8, [[0, 4, 69]], 2),
  },
  {
    n: 65,
    id: 'reed-wave-organ-em',
    name: 'Reed wave organ {E}m',
    kind: 'oneshot',
    description:
      'A reedy wavetable chord on {E} minor with a quick key, spun by a fast rotor into a spring.',
    preset: 'ashram-reed-wave-organ',
    ...played(
      5,
      [
        [0, 2, 52],
        [0, 2, 59],
        [0, 2, 64],
        [0, 2, 67],
      ],
      1.2,
    ),
  },
  {
    n: 66,
    id: 'twelve-over-drone-am',
    name: 'Twelve over drone {A}m',
    kind: 'oneshot',
    description:
      'A twelve-string strummed slowly on {A} minor, its courses waking drone strings in a hall.',
    preset: 'ashram-twelve-over-drone',
    effects: [
      drones({ sympathy: 0.7, strings: 10, mix: 0.3, width: 0.6 }),
      { deviceId: 'fdn-reverb', preset: 'Hall', params: { mix: 0.28 } },
    ],
    then: [{ deviceId: 'ambient-limiter', params: { ceiling: -12, gain: 8 } }],
    ...played(
      10,
      [
        [0.01, 4.4, 45],
        [0.01, 4.4, 52],
        [0.01, 4.4, 57],
        [0.01, 4.4, 60],
        [0.01, 4.4, 64],
      ],
      2.5,
    ),
  },
  {
    n: 67,
    id: 'swirl-strum-c',
    name: 'Swirl strum {C}',
    kind: 'oneshot',
    description:
      'One slow soft strum of {C} major on a clean guitar, through a fast rotating horn and a spring.',
    preset: 'ashram-swirl-strum',
    then: [{ deviceId: 'ambient-limiter', preset: 'Pinned' }],
    ...played(
      8,
      [
        [0, 4, 48],
        [0, 4, 55],
        [0, 4, 60],
        [0, 4, 64],
        [0, 4, 67],
      ],
      2,
    ),
  },
  {
    n: 68,
    id: 'first-sweep-dm',
    name: 'First sweep {D}m',
    kind: 'melodic',
    description:
      'A {D} minor ninth rolled up the harp in under a second, ringing into a long plate.',
    preset: 'ashram-first-sweep',
    ...played(
      8,
      [
        [0, 2.5, 50],
        [0, 2.5, 57],
        [0, 2.5, 62],
        [0, 2.5, 65],
        [0, 2.5, 69],
        [0, 2.5, 72],
        [0, 2.5, 76],
      ],
      2,
    ),
  },
  {
    n: 69,
    id: 'canyon-sweep-g',
    name: 'Canyon sweep {G}',
    kind: 'melodic',
    description:
      'Long-ringing strings climb slowly from a low {G}, each note repeated by tape in a plate.',
    preset: 'ashram-canyon-sweep',
    set: { sweep: 0, touch: 0.85, pluck: 0.2 },
    then: [{ deviceId: 'stereo-widener', params: { width: 0.35 } }],
    ...played(
      12,
      [
        [0, 3.5, 43, 0.8],
        [0.61, 3.2, 50, 0.65],
        [1.07, 3, 55, 0.65],
        [1.78, 2.8, 59, 0.7],
        [2.21, 2.6, 62, 0.7],
        [3.02, 2.5, 67, 0.8],
        [4.17, 3, 74, 0.85],
      ],
      3,
    ),
  },
  {
    n: 70,
    id: 'falling-strum-am',
    name: 'Falling strum {A}m',
    kind: 'melodic',
    description:
      'Three slow downward sweeps, {A} minor, {F} and {E} minor, with tape repeats trailing into a hall.',
    preset: 'ashram-falling-strum',
    set: { tone: 0.7 },
    ...played(
      14,
      [
        [0, 2.6, 57],
        [0, 2.6, 60],
        [0, 2.6, 64],
        [3.13, 2.2, 53],
        [3.13, 2.2, 57],
        [3.13, 2.2, 60],
        [5.71, 4, 52],
        [5.71, 4, 55],
        [5.71, 4, 59],
      ],
      3,
    ),
  },
  {
    n: 71,
    id: 'veranda-chimes-c',
    name: 'Veranda chimes {C}',
    kind: 'melodic',
    description:
      'Wind chimes on the five notes of {C} stirred by a gusting breeze, ringing into a long spring.',
    preset: 'ashram-veranda-chimes',
    ...looped(16, 3, 3, [60]),
  },
  {
    n: 72,
    id: 'saffron-harp-round-am',
    name: 'Saffron harp round {A}m',
    kind: 'melodic',
    description:
      'A harp climbs {A} minor from the bass and steps back down, slowly phased; it comes round.',
    preset: 'ashram-saffron-harp',
    // The preset's phaser at one turn a loop (0.11 Hz does not come round in 8 s).
    effects: [
      { deviceId: 'phaser', preset: 'Slow swirl', params: { rate: 0.125, mix: 0.4 } },
      { deviceId: 'plate-reverb', preset: 'Small plate', params: { decay: 0.6, mix: 0.28 } },
    ],
    ...cycled(8, [
      [0, 1.6, 45, 0.7],
      [0.52, 1.4, 52, 0.55],
      [1.07, 1.4, 57, 0.6],
      [1.71, 1.6, 60, 0.65],
      [2.63, 2, 64, 0.7],
      [4.12, 1.5, 62, 0.5],
      [4.77, 1.5, 59, 0.55],
      [5.61, 2, 57, 0.6],
    ]),
  },
  {
    n: 73,
    id: 'drone-harp-fall-e',
    name: 'Drone harp fall {E}',
    kind: 'melodic',
    description:
      'Soft harp notes falling from {B} to {E} over drone strings that hum on; it comes round.',
    preset: 'ashram-harp-over-drone',
    effects: [
      drones({ decay: 7, mix: 0.3, width: 0.6 }),
      { deviceId: 'hall-reverb', preset: 'Hall', params: { mix: 0.3 } },
    ],
    ...cycled(8, [
      [0, 2, 71, 0.65],
      [1.31, 2, 69, 0.55],
      [2.47, 2.2, 65, 0.6],
      [4.12, 3, 64, 0.7],
      [5.63, 2, 52, 0.5],
    ]),
  },
  {
    n: 74,
    id: 'reed-solo-e',
    name: 'Reed solo {E}',
    kind: 'melodic',
    description:
      'A snarling reed stop turns a phrase around {E} and comes home, through a growling rotor.',
    preset: 'ashram-reed-solo',
    then: [{ deviceId: 'stereo-widener', params: { width: 0.4 } }],
    ...played(
      8,
      [
        [0, 0.5, 64],
        [0.61, 0.35, 67],
        [1.02, 0.9, 69],
        [2.13, 0.3, 72],
        [2.47, 0.3, 69],
        [2.83, 1.2, 67],
        [4.31, 0.4, 62],
        [4.78, 1.8, 64],
      ],
      1.2,
    ),
  },
  {
    n: 75,
    id: 'octave-line-dm',
    name: 'Octave line {D}m',
    kind: 'melodic',
    description:
      'Violins doubled an octave up climb from {D} to {C} and settle on {A}; it comes round.',
    preset: 'ashram-octave-line',
    set: { attack: 0.05, release: 0.4, bow: 0.8 },
    ...cycled(8, [
      [0, 1, 62],
      [1.38, 0.5, 65],
      [2.11, 0.45, 67],
      [2.83, 1.3, 69],
      [4.62, 0.6, 72],
      [5.47, 1.6, 69],
    ]),
  },
  {
    n: 76,
    id: 'free-violin-am',
    name: 'Free violin {A}m',
    kind: 'melodic',
    description:
      'One violin near the bridge cries up from {A} to a long {E} and falls back, in a spring.',
    preset: 'ashram-free-violin',
    set: { attack: 0.05, release: 0.3 },
    ...played(
      10,
      [
        [0, 0.7, 69],
        [0.97, 0.3, 72],
        [1.52, 0.4, 71],
        [2.21, 1.9, 76],
        [4.63, 0.3, 74],
        [5.19, 0.4, 72],
        [5.88, 2.4, 69],
      ],
      1.5,
    ),
  },
  {
    n: 77,
    id: 'alto-lead-c',
    name: 'Alto lead {C}',
    kind: 'melodic',
    description:
      "A low woman's voice rises from {G} through {C} to {E} and settles; it comes round.",
    preset: 'ashram-alto-lead',
    ...cycled(
      8,
      [
        [0, 1.5, 55],
        [1.62, 1.2, 60],
        [2.93, 0.7, 62],
        [3.71, 1.9, 64],
        [5.74, 1.6, 60],
      ],
      { passes: 2 },
    ),
    loopFold: 'power',
  },
  {
    n: 78,
    id: 'sliding-string-c',
    name: 'Sliding string {C}',
    kind: 'melodic',
    description:
      'Picked steel notes up a {C} chord, the last dragged up a tone, over drone strings; it comes round.',
    preset: 'ashram-sliding-string',
    set: { swell: 0, pick: 0.9 },
    effects: [
      drones({ sympathy: 0.75, decay: 5, mix: 0.3, width: 0.5 }),
      { deviceId: 'plate-reverb', preset: 'Medium plate', params: { mix: 0.25 } },
    ],
    ...cycled(8, [
      [0, 1.3, 60],
      [1.47, 1.3, 64],
      [2.91, 2.6, 67],
      [4.83, 1.2, 69],
      [6.12, 1.4, 64],
    ]),
  },
  {
    n: 79,
    id: 'muted-trumpet-call-a',
    name: 'Muted trumpet call {A}',
    kind: 'melodic',
    description:
      'A muted trumpet calls on {A} and answers itself from above, into a tape echo and a spring.',
    preset: 'ashram-muted-call',
    effects: [
      SPOKEN,
      { deviceId: 'tape-echo', params: { time: 440, feedback: 0.4, mix: 0.25 } },
      { deviceId: 'spring-reverb', preset: 'Long three spring', params: { mix: 0.25 } },
    ],
    ...played(
      10,
      [
        [0, 0.9, 69],
        [1.13, 0.3, 64],
        [1.49, 0.3, 67],
        [1.87, 1.6, 69],
        [4.21, 0.5, 72],
        [4.83, 0.5, 71],
        [5.42, 2, 69],
      ],
      2,
    ),
  },
  {
    n: 80,
    id: 'bamboo-flute-em',
    name: 'Bamboo flute {E}m',
    kind: 'melodic',
    description:
      'A wooden flute scoops up five notes from {E} and turns back, with dark repeats in a hall.',
    preset: 'ashram-bamboo-flute',
    effects: [
      SPOKEN,
      { deviceId: 'analog-delay', preset: 'Dark echo', params: { time: 420, mix: 0.25 } },
      { deviceId: 'fdn-reverb', preset: 'Hall', params: { mix: 0.3 } },
    ],
    ...played(
      10,
      [
        [0, 1.2, 64],
        [1.33, 0.5, 67],
        [1.91, 0.5, 69],
        [2.52, 1.8, 71],
        [4.61, 0.6, 74],
        [5.27, 0.5, 71],
        [5.86, 2.2, 64],
      ],
      2,
    ),
  },
  {
    n: 81,
    id: 'soprano-run-d',
    name: 'Soprano run {D}',
    kind: 'melodic',
    description:
      'A conical reed runs up {D} minor to the octave, holds the top and falls to {A}, on tape in a plate.',
    preset: 'ashram-straight-soprano',
    ...played(
      8,
      [
        [0, 0.2, 62, 0.75],
        [0.17, 0.25, 64, 0.75],
        [0.38, 0.2, 65, 0.8],
        [0.54, 0.3, 69, 0.85],
        [0.81, 0.4, 72, 0.95],
        [1.18, 2.4, 74, 0.8],
        [3.93, 0.4, 72, 0.7],
        [4.37, 2.2, 69, 0.65],
      ],
      1.2,
    ),
  },
  {
    n: 82,
    id: 'club-vibes-round-f',
    name: 'Club vibes round {F}',
    kind: 'melodic',
    description:
      'A vibraphone opens {F} major seventh upward and steps back, motor turning; it comes round.',
    preset: 'ashram-club-vibes',
    set: { motorRate: 3.25 },
    ...cycled(8, [
      [0, 1.5, 65, 0.7],
      [0.71, 1.5, 69, 0.55],
      [1.37, 1.5, 72, 0.6],
      [2.48, 2, 76, 0.7],
      [4.22, 1.5, 74, 0.55],
      [4.93, 1.5, 72, 0.5],
      [5.81, 2, 69, 0.6],
    ]),
    loopFold: 'power',
  },
  {
    n: 83,
    id: 'late-piano-vamp-d',
    name: 'Late piano vamp {D}',
    kind: 'melodic',
    description:
      'Chords in fourths over a {D} and {A} bass on a bare piano, never on a pulse; it comes round.',
    preset: 'ashram-late-set-piano',
    then: [{ deviceId: 'ambient-limiter', preset: 'Pinned' }],
    ...cycled(8, [
      [0, 1.8, 38, 0.75],
      [0.71, 1.2, 55, 0.6],
      [0.71, 1.2, 60, 0.6],
      [0.71, 1.2, 65, 0.6],
      [2.47, 1.3, 57, 0.65],
      [2.47, 1.3, 62, 0.65],
      [2.47, 1.3, 67, 0.65],
      [4.13, 1.5, 45, 0.7],
      [5.02, 1.6, 55, 0.55],
      [5.02, 1.6, 60, 0.55],
      [5.02, 1.6, 65, 0.55],
    ]),
  },
  {
    n: 84,
    id: 'plate-piano-fall-c',
    name: 'Plate piano fall {C}',
    kind: 'melodic',
    description:
      'A lightly felted piano falls slowly from a high {G} to a low {C}, deep in a long plate.',
    preset: 'ashram-plate-piano',
    then: [{ deviceId: 'stereo-widener', params: { width: 0.2 } }],
    ...played(
      12,
      [
        [0, 2.5, 79, 0.6],
        [1.21, 2.5, 76, 0.5],
        [2.63, 2.5, 72, 0.55],
        [4.52, 3.5, 67, 0.6],
        [4.6, 4, 48, 0.5],
      ],
      3,
    ),
  },
  {
    n: 85,
    id: 'long-tine-echo-am',
    name: 'Long tine echo {A}m',
    kind: 'melodic',
    description:
      'Three bell-like tine notes in {A} minor, each repeated by tape heads; it comes round.',
    preset: 'ashram-long-tine-echo',
    effects: [
      {
        deviceId: 'tape-echo',
        preset: 'Dub wash',
        params: { time: 560, feedback: 0.35, spread: 0.7, mix: 0.25 },
      },
      { deviceId: 'plate-reverb', preset: 'Medium plate', params: { mix: 0.25 } },
    ],
    ...cycled(8, [
      [0, 1.5, 69, 0.95],
      [2.31, 1.5, 76, 0.45],
      [4.87, 1.5, 72, 0.5],
    ]),
  },
  {
    n: 86,
    id: 'phased-tines-arp-f',
    name: 'Phased tines arp {F}',
    kind: 'melodic',
    description:
      'A hollow electric piano opens {F} major ninth from the bass, slowly phased; it comes round.',
    preset: 'ashram-phased-tines',
    effects: [
      { deviceId: 'phaser', preset: 'Classic four-stage', params: { rate: 0.5, feedback: 50 } },
      { deviceId: 'plate-reverb', preset: 'Small plate', params: { mix: 0.25 } },
    ],
    ...cycled(8, [
      [0, 2.5, 53, 0.7],
      [0.63, 2, 60, 0.55],
      [1.21, 2, 64, 0.55],
      [1.94, 2.2, 69, 0.65],
      [3.42, 2, 72, 0.6],
      [5.13, 2.4, 67, 0.55],
    ]),
  },
  {
    n: 87,
    id: 'hand-drum-round-a',
    name: 'Hand drum round {A}',
    kind: 'melodic',
    description:
      'A tuned hand drum played around {A} in free time, damped short, on tape; it comes round.',
    preset: 'ashram-tuned-hand-drum',
    then: [{ deviceId: 'ambient-limiter', preset: 'Pinned' }],
    ...cycled(8, [
      [0, 0.4, 57, 0.8],
      [0.63, 0.3, 64, 0.5],
      [1.04, 0.3, 57, 0.6],
      [1.94, 0.4, 62, 0.55],
      [3, 0.3, 64, 0.6],
      [3.34, 0.3, 60, 0.45],
      [4.17, 0.4, 57, 0.75],
      [5.78, 0.3, 64, 0.6],
      [6.55, 0.3, 62, 0.5],
    ]),
  },
  {
    n: 88,
    id: 'bass-vamp-round-d',
    name: 'Bass vamp round {D}',
    kind: 'melodic',
    description:
      'A round plucked bass walks {D}, {A}, {C} and {D} in free time, levelled; it comes round.',
    preset: 'ashram-bass-vamp',
    then: [{ deviceId: 'ambient-limiter', preset: 'Pinned' }],
    ...cycled(8, [
      [0, 1, 38, 0.8],
      [1.47, 0.5, 45, 0.6],
      [1.96, 0.5, 48, 0.6],
      [2.51, 1.2, 50, 0.7],
      [4.42, 0.8, 45, 0.65],
      [5.63, 0.5, 48, 0.55],
      [6.21, 0.9, 45, 0.6],
    ]),
  },
  {
    n: 89,
    id: 'hammered-strings-round-g',
    name: 'Hammered round {G}',
    kind: 'melodic',
    description:
      'Light hammers on doubled strings around {G}, with soft chorused echoes; it comes round.',
    preset: 'ashram-hammered-strings',
    ...cycled(8, [
      [0, 0.08, 67, 0.7],
      [0.71, 0.08, 62, 0.55],
      [1.52, 0.08, 71, 0.6],
      [2.9, 0.08, 74, 0.7],
      [4.4, 0.08, 72, 0.55],
      [5.2, 0.08, 67, 0.6],
    ]),
  },
  {
    n: 90,
    id: 'plectrum-lute-phrase-e',
    name: 'Plectrum lute phrase {E}',
    kind: 'melodic',
    description:
      'Nylon strings picked by the bridge turn around {E} and its upper neighbour, over a low {E}.',
    preset: 'ashram-plectrum-lute',
    then: [{ deviceId: 'ambient-limiter', preset: 'Pinned' }],
    ...played(
      8,
      [
        [0, 2, 40, 0.6],
        [0.05, 0.5, 64, 0.7],
        [0.61, 0.4, 65, 0.6],
        [0.97, 0.7, 67, 0.7],
        [1.83, 0.4, 65, 0.6],
        [2.38, 0.4, 64, 0.6],
        [2.71, 0.5, 62, 0.55],
        [3.42, 2.5, 64, 0.75],
      ],
      1.5,
    ),
  },
  {
    n: 91,
    id: 'turning-harmonium-g',
    name: 'Turning harmonium {G}',
    kind: 'melodic',
    description:
      'A sampled harmonium fifth on {G} played as a line, round a slow rotor; it comes round.',
    preset: 'ashram-turning-sample',
    set: { attack: 0.01, release: 0.25 },
    source: 'harmonium-drone-g',
    // The sample holds G and D: the key four semitones up would put it on B and F sharp.
    ...cycled(8, [
      [0, 1.1, 60],
      [1.71, 0.4, 65],
      [2.49, 1, 67],
      [4.02, 0.35, 65],
      [4.71, 0.35, 62],
      [5.43, 1.4, 60],
    ]),
  },
  {
    n: 92,
    id: 'driven-tines-riff-a',
    name: 'Driven tines riff {A}',
    kind: 'melodic',
    description:
      'A low riff from {A} played hard so the pickup barks, into a valve stage; it comes round.',
    preset: 'ashram-driven-tines',
    ...cycled(8, [
      [0, 0.5, 45, 0.9],
      [0.52, 0.3, 52, 0.6],
      [0.93, 0.4, 55, 0.7],
      [1.37, 1.2, 57, 0.8],
      [3.21, 0.3, 55, 0.6],
      [3.62, 0.4, 52, 0.6],
      [4.18, 1.5, 45, 0.85],
      [5.9, 0.5, 48, 0.6],
    ]),
  },
  {
    n: 93,
    id: 'swirling-organ-vamp-am',
    name: 'Swirling organ vamp {A}m',
    kind: 'melodic',
    description:
      'A full reedy organ moves {A} minor, {G}, {F} and back in a fast rotor; it comes round.',
    preset: 'ashram-swirling-organ',
    ...cycled(8, [
      [0, 1.3, 57],
      [0, 1.3, 60],
      [0, 1.3, 64],
      [1.71, 0.6, 55],
      [1.71, 0.6, 62],
      [1.71, 0.6, 67],
      [2.41, 1.7, 53],
      [2.41, 1.7, 57],
      [2.41, 1.7, 60],
      [4.87, 0.6, 55],
      [4.87, 0.6, 62],
      [5.52, 1.5, 57],
      [5.52, 1.5, 60],
      [5.52, 1.5, 64],
    ]),
    loopFold: 'power',
  },
  {
    n: 94,
    id: 'harp-and-section-am',
    name: 'Harp and section {A}m',
    kind: 'melodic',
    description:
      'Three rolled harp chords, {A} minor, {F} and {G}, each answered by a string section swelling in.',
    preset: 'ashram-harp-and-section',
    set: { touch: 0.8 },
    effects: [
      {
        deviceId: 'pad-follower',
        preset: 'Slow swell',
        params: { rise: 1.6, fall: 6, octaves: 0.3, ensemble: 0.5, mix: 0.3 },
      },
      { deviceId: 'plate-reverb', preset: 'Medium plate', params: { mix: 0.28 } },
    ],
    ...played(
      16,
      [
        [0, 3, 45],
        [0, 3, 52],
        [0, 3, 57],
        [0, 3, 60],
        [0, 3, 64],
        [3.87, 3, 41],
        [3.87, 3, 53],
        [3.87, 3, 57],
        [3.87, 3, 60],
        [3.87, 3, 65],
        [7.31, 4, 43],
        [7.31, 4, 55],
        [7.31, 4, 59],
        [7.31, 4, 62],
        [7.31, 4, 67],
      ],
      3,
    ),
  },
  {
    n: 95,
    id: 'late-harp-line-g',
    name: 'Late harp line {G}',
    kind: 'melodic',
    description:
      'A quick dry line up from {G} to a high {F} and home, plucked hard near the soundboard; it comes round.',
    preset: 'ashram-late-set-harp',
    set: { decay: 0.9 },
    then: [{ deviceId: 'ambient-limiter', preset: 'Pinned' }],
    ...cycled(8, [
      [0, 0.4, 67, 0.7],
      [0.27, 0.4, 69, 0.6],
      [0.49, 0.4, 71, 0.65],
      [0.83, 0.5, 74, 0.75],
      [1.52, 0.4, 72, 0.6],
      [2.47, 0.8, 77, 0.8],
      [4.13, 0.5, 74, 0.6],
      [5.42, 0.9, 67, 0.7],
    ]),
  },
  {
    n: 96,
    id: 'bent-organ-line-c',
    name: 'Bent organ line {C}',
    kind: 'melodic',
    description:
      'A reedy organ line from {C} whose pitch sways like a bent key, echoed on tape; it comes round.',
    preset: 'ashram-bent-organ-line',
    set: { attack: 0.01, release: 0.2 },
    ...cycled(8, [
      [0, 1.1, 72],
      [1.52, 0.4, 74],
      [2.21, 0.9, 77],
      [3.58, 0.35, 76],
      [4.17, 1.2, 74],
      [5.93, 1, 69],
    ]),
    loopFold: 'power',
  },
  {
    n: 97,
    id: 'ringing-steel-round-f',
    name: 'Ringing steel round {F}',
    kind: 'melodic',
    description:
      'A steel pan touched lightly around {F}, every note waking the others; it comes round.',
    preset: 'ashram-ringing-steel',
    then: [{ deviceId: 'stereo-widener', params: { width: 0.4 } }],
    ...cycled(
      8,
      [
        [0, 1.5, 53, 0.75],
        [0.87, 1, 60, 0.5],
        [1.63, 1.2, 57, 0.55],
        [2.91, 1.2, 64, 0.6],
        [4.36, 1.5, 65, 0.65],
        [5.52, 1.2, 60, 0.5],
        [6.61, 1, 59, 0.5],
      ],
      { passes: 2 },
    ),
  },
  {
    n: 98,
    id: 'hand-bells-scatter-b',
    name: 'Hand bells scatter {B}',
    kind: 'melodic',
    description:
      'Small bright bells scattered high around {B}, short, in a spring tank; it comes round.',
    preset: 'ashram-small-hand-bells',
    ...cycled(8, [
      [0, 0.5, 83, 0.7],
      [1.63, 0.5, 88, 0.5],
      [2.14, 0.5, 86, 0.6],
      [4.52, 0.5, 79, 0.55],
      [5.87, 0.5, 83, 0.6],
    ]),
  },
  {
    n: 99,
    id: 'folded-harp-round-c',
    name: 'Folded harp round {C}',
    kind: 'melodic',
    description:
      'Bright folded plucks climb a {C} chord to {E} and step back down, with tape repeats; it comes round.',
    preset: 'ashram-folded-harp',
    ...cycled(8, [
      [0, 1, 60, 0.7],
      [0.57, 1, 67, 0.55],
      [1.21, 1, 72, 0.6],
      [2.03, 1.2, 76, 0.65],
      [3.47, 1, 74, 0.55],
      [4.38, 1, 69, 0.5],
      [5.42, 1.2, 67, 0.6],
    ]),
  },
  {
    n: 100,
    id: 'wound-strings-round-g',
    name: 'Wound strings round {G}',
    kind: 'melodic',
    description:
      'The low wound strings of the harp walk from {G} up an octave and back; it comes round.',
    preset: 'ashram-wound-strings',
    ...cycled(8, [
      [0, 2, 43, 0.8],
      [1.53, 1.5, 50, 0.6],
      [2.87, 2, 55, 0.7],
      [4.61, 1.5, 53, 0.55],
      [5.72, 2, 50, 0.6],
    ]),
  },
])
