// The sounds of the pack "Old Broadcast Hall": its presets played, a hundred sounds to
// paint with. Numbers 17001 to 17100.

import { PRESETS } from '../packs/broadcast-hall'
import { type FactorySound } from '../types'
import { breathe, cycled, looped, packSounds, played, quarterTurn, soften } from './recipe'

export const SOUNDS: readonly FactorySound[] = packSounds('broadcast-hall', 17000, PRESETS, [
  // Drones: one note or a bare fifth, held for as long as the loop lasts.
  {
    n: 1,
    id: 'sixteen-foot-stop-f',
    name: 'Sixteen foot stop {F}',
    kind: 'drone',
    description:
      'A low {F} on the lowest rank of the studio organ, dark and nearly alone in the hall.',
    preset: 'broadcast-hall-sixteen-foot-stop',
    ...looped(8, 5, 2, [41]),
    then: [quarterTurn(8)],
    tuning: 'whole-cycles',
  },
  {
    n: 2,
    id: 'organ-point-fifths-g',
    name: 'Organ point fifths {G}',
    kind: 'drone',
    description:
      'A low {G} and the {D} over it in reedy partials with air in them, on tape in the hall.',
    preset: 'broadcast-hall-organ-point-fifths',
    set: { movement: 0, air: 0.15 },
    ...looped(8, 5, 2, [43]),
    then: [quarterTurn(8)],
    tuning: 'whole-cycles',
  },
  {
    n: 3,
    id: 'minor-reel-drone-d',
    name: 'Minor reel drone {D}',
    kind: 'drone',
    description: 'A dark {D} minor chord of slow partials, wavering on a reel in a long plate.',
    preset: 'broadcast-hall-minor-reel-drone',
    set: { movement: 0.1 },
    ...looped(8, 7, 2, [50]),
  },
  {
    n: 4,
    id: 'pedal-square-c',
    name: 'Pedal square {C}',
    kind: 'drone',
    description:
      'A square wave on a low {C} with its sub octave, half closed, on tape in a long spring.',
    preset: 'broadcast-hall-pedal-square',
    ...looped(8, 4, 2, [48]),
  },
  {
    n: 5,
    id: 'foot-pedal-bass-e',
    name: 'Foot pedal bass {E}',
    kind: 'drone',
    description:
      'Two sawtooths and a sub octave on a low {E} under a nearly closed filter, held by a foot.',
    preset: 'broadcast-hall-foot-pedal-bass',
    set: { beat: 0 },
    ...looped(8, 3, 2, [40]),
    then: [quarterTurn(8)],
    tuning: 'whole-cycles',
  },
  {
    n: 6,
    id: 'evening-broadcast-b',
    name: 'Evening broadcast {B}',
    kind: 'drone',
    description:
      'Two flutes an octave apart on a high {B} from a small medium-wave set: narrow, steady, a little static.',
    preset: 'broadcast-hall-evening-broadcast',
    source: 'flute-octaves-b',
    set: { crossfade: 500 },
    effects: [
      { deviceId: 'radio', preset: 'Kitchen radio', params: { drift: 0, fading: 0 } },
      { deviceId: 'hall-reverb', preset: 'Room', params: { mix: 0.15 } },
    ],
    ...looped(8, 4, 2, [60]),
  },
  {
    n: 7,
    id: 'pump-organ-reeds-c',
    name: 'Pump organ reeds {C}',
    kind: 'drone',
    description: 'A {C} in two octaves on a pumped reed organ close up, the bellows held steady.',
    preset: 'broadcast-hall-pump-organ-close',
    set: { bellows: 0.3 },
    ...looped(8, 4, 2, [48, [60, 0.7]]),
  },
  {
    n: 8,
    id: 'flue-pipe-octaves-b',
    name: 'Flue pipe octaves {B}',
    kind: 'drone',
    description:
      'Stopped wooden pipes on {B} in two octaves with their wind audible, in a short room.',
    preset: 'broadcast-hall-wooden-flue-pipes',
    effects: [
      { deviceId: 'stereo-detune', preset: 'Soft halo', params: { mix: 0.12 } },
      { deviceId: 'fdn-reverb', preset: 'Room', params: { mix: 0.3 } },
    ],
    ...looped(8, 4, 2, [59, [71, 0.7]]),
  },
  {
    n: 9,
    id: 'plain-string-drone-e',
    name: 'Plain string drone {E}',
    kind: 'drone',
    description:
      'Open strings on {E} and {B} plucked round and round with no buzz, on tape in a room.',
    preset: 'broadcast-hall-plain-string-drone',
    set: { speed: 8.09 },
    effects: [
      { deviceId: 'tape', preset: 'Quarter inch' },
      { deviceId: 'fet-limiter', params: { inputGain: 30, outputGain: -12 } },
      {
        deviceId: 'ambient-comp',
        params: {
          threshold: -45,
          ratio: 8,
          attack: 10,
          release: 0.15,
          knee: 6,
          tails: 1,
          scLowCut: 40,
          makeup: 18,
        },
      },
      { deviceId: 'fdn-reverb', preset: 'Room', params: { mix: 0.25 } },
    ],
    ...looped(8, 8.4, 0.5, [52]),
  },
  {
    n: 10,
    id: 'valve-desk-hum-g',
    name: 'Valve desk hum {G}',
    kind: 'drone',
    description:
      'The hum of valve equipment left on overnight, tuned to a low {G}, warm and still.',
    preset: 'broadcast-hall-desk-left-on',
    set: { tone: 0.6, movement: 0.3 },
    ...looped(8, 4, 2, [43, [55, 0.5]]),
    then: [
      { deviceId: 'noise-floor', preset: 'Empty room', params: { level: -36, width: 0.7 } },
      quarterTurn(8),
    ],
    tuning: 'whole-cycles',
  },
  {
    n: 11,
    id: 'sustained-wire-a',
    name: 'Sustained wire {A}',
    kind: 'drone',
    description:
      'Low strings on {A} and {E} held singing with no bow, tuned strings answering in the hall.',
    preset: 'broadcast-hall-sustained-wire',
    set: { detune: 0 },
    effects: [
      { deviceId: 'sympathetic', preset: 'Piano pedal', params: { root: 9, mode: 1, mix: 0.3 } },
      { deviceId: 'hall-reverb', preset: 'Hall', params: { mix: 0.35 } },
    ],
    ...looped(8, 6, 2, [45, [52, 0.6], [57, 0.4]]),
    then: [quarterTurn(8)],
    tuning: 'whole-cycles',
  },
  {
    n: 12,
    id: 'close-bass-clarinets-a',
    name: 'Close bass clarinets {A}',
    kind: 'drone',
    description:
      'Bass clarinets on a low {A}, {E} and the {A} above, blown softly a hand from the microphone.',
    preset: 'broadcast-hall-bass-clarinet-close',
    set: { breath: 0.55 },
    ...looped(8, 4, 2, [45, [52, 0.8], [57, 0.5]]),
    then: [quarterTurn(8)],
    tuning: 'whole-cycles',
  },
  {
    n: 13,
    id: 'low-flute-breath-d',
    name: 'Low flute breath {D}',
    kind: 'drone',
    description:
      'Two low flutes an octave apart on {D}, blown gently, on tape with a spring tank behind.',
    preset: 'broadcast-hall-low-flute-breath',
    set: { breath: 0.5, vibrato: 0 },
    ...looped(8, 4, 2, [
      [62, 0.75],
      [74, 0.75],
    ]),
  },
  {
    n: 14,
    id: 'woody-cello-drone-f',
    name: 'Woody cello drone {F}',
    kind: 'drone',
    description:
      'A low {F} and the {C} over it bowed on one cello, close, on clean tape in the wooden room.',
    preset: 'broadcast-hall-woody-cello-line',
    set: { vibrato: 0 },
    ...looped(8, 4, 2, [41, [48, 0.6]]),
    then: [quarterTurn(8)],
    tuning: 'whole-cycles',
  },
  {
    n: 15,
    id: 'hummed-chapel-fifth-d',
    name: 'Hummed chapel fifth {D}',
    kind: 'drone',
    description:
      'Low voices closed to a breathy oo on {D} and {A}, no vibrato, on tape in a small chapel.',
    preset: 'broadcast-hall-hummed-bass-line',
    set: { ensemble: 0, motion: 0, breath: 0.5 },
    ...looped(8, 5, 2, [50, [57, 0.8]]),
  },
  {
    n: 16,
    id: 'reed-table-drone-g',
    name: 'Reed table drone {G}',
    kind: 'drone',
    description:
      'A reed wave on {G} with its sub octave, held nearly still, on a reel in a spring tank.',
    preset: 'broadcast-hall-reed-table-pad',
    set: { motion: 0.1, rate: 0.125, detune: 0 },
    ...looped(8, 5, 2, [55]),
    then: [quarterTurn(8)],
    tuning: 'whole-cycles',
  },
  {
    n: 17,
    id: 'cistern-reeds-e',
    name: 'Cistern reeds {E}',
    kind: 'drone',
    description:
      'A reed organ holding {E} and {B} in a round stone tank, the walls ringing behind it.',
    preset: 'broadcast-hall-stone-cistern-reeds',
    set: { celeste: 0, bellows: 0.1, twelfth: 0 },
    ...looped(8, 6, 2, [52, [59, 0.7]]),
    then: [quarterTurn(8)],
    tuning: 'whole-cycles',
  },
  {
    n: 18,
    id: 'organ-next-door-d',
    name: 'Organ next door {D}',
    kind: 'drone',
    description:
      'A full organ on {D} and {A} heard from the next studio along, with no top at all.',
    preset: 'broadcast-hall-organ-next-door',
    set: { celeste: 0.1 },
    ...looped(8, 7, 2, [50, [57, 0.8]]),
    then: [quarterTurn(8)],
    tuning: 'whole-cycles',
  },
  // Pads: chords that swell, some looping and some played once and left to die away.
  {
    n: 19,
    id: 'slow-slider-pad-dm',
    name: 'Slow slider pad {D}m',
    kind: 'pad',
    description:
      'A {D} minor chord that starts shut and opens for as long as it is held, in the hall.',
    preset: 'broadcast-hall-slow-slider-pad',
    set: { release: 3, sub: 0.25 },
    ...played(
      10,
      [
        [0, 6.5, 50],
        [0, 6.5, 57],
        [0, 6.5, 62, 0.8],
        [0, 6.5, 65, 0.35],
      ],
      2,
    ),
  },
  {
    n: 20,
    id: 'chorus-buttons-f',
    name: 'Chorus buttons {F}',
    kind: 'pad',
    description:
      'A moving pulse on an {F} major chord with both chorus buttons in, swelling in a spring.',
    preset: 'broadcast-hall-both-chorus-buttons',
    ...looped(8, 3, 2, [53, 60, [65, 0.7], [69, 0.4]]),
    then: [breathe(0.25, 0.4)],
  },
  {
    n: 21,
    id: 'thin-pulse-pad-am',
    name: 'Thin pulse pad {A}m',
    kind: 'pad',
    description:
      'A thin pulse chord on {A} minor with its lows cut away, into three tape heads and a plate.',
    preset: 'broadcast-hall-thin-pulse-pad',
    ...looped(8, 6, 2, [57, 64, [69, 0.8], [72, 0.5]]),
    then: [breathe(0.125, 0.5)],
  },
  {
    n: 22,
    id: 'chamber-polysynth-gsus2',
    name: 'Chamber polysynth {G}sus2',
    kind: 'pad',
    description:
      'The string patch on {G}, {D} and {A} from a loudspeaker at the far end of a hard room.',
    preset: 'broadcast-hall-chamber-polysynth',
    ...looped(8, 5, 2, [43, 55, [62, 0.8], [69, 0.5]]),
    then: [breathe(0.125, 0.45)],
  },
  {
    n: 23,
    id: 'replay-choir-cmaj7',
    name: 'Replay choir {C}maj7',
    kind: 'pad',
    description:
      'A choir on strips of tape in close harmony on {C} major seventh, wavering in the hall.',
    preset: 'broadcast-hall-replay-choir',
    set: { vibrato: 0.15, players: 0.3 },
    ...looped(8, 6, 2, [60, [64, 0.7], [67, 0.8], [71, 0.5]]),
    then: [breathe(0.125, 0.4)],
  },
  {
    n: 24,
    id: 'three-violins-far-em',
    name: 'Three violins far {E}m',
    kind: 'pad',
    description:
      'Violins on worn tape holding a high {E} minor chord, a long way back in the hall.',
    preset: 'broadcast-hall-three-violins-far',
    set: { attack: 1.2, release: 1.5 },
    ...played(
      7,
      [
        [0, 4.5, 64],
        [0, 4.5, 71],
        [0, 4.5, 76, 0.8],
        [0, 4.5, 79, 0.7],
      ],
      1.5,
    ),
  },
  {
    n: 25,
    id: 'slowed-reel-cellos-d',
    name: 'Slowed reel cellos {D}',
    kind: 'pad',
    description:
      'Cellos from tape at half speed on {D} and {A}, an octave down and wavering, in a plate.',
    preset: 'broadcast-hall-half-speed-cellos',
    set: { players: 0.4, vibrato: 0.2 },
    ...looped(8, 5, 2, [50, 57, [62, 0.7]]),
    then: [breathe(0.125, 0.3)],
  },
  {
    n: 26,
    id: 'old-reel-horns-f',
    name: 'Old reel horns {F}',
    kind: 'pad',
    description:
      'A horn section from aged tape on an {F} major chord, dull and hissing, in the hall.',
    preset: 'broadcast-hall-old-reel-horns',
    ...looped(8, 4, 2, [53, 60, [65, 0.8], [69, 0.6]]),
    then: [breathe(0.125, 0.5)],
  },
  {
    n: 27,
    id: 'replay-flutes-gadd9',
    name: 'Replay flutes {G}add9',
    kind: 'pad',
    description:
      'Tape-replay flutes holding {G} with an added ninth, breathy and unsteady, in a spring.',
    preset: 'broadcast-hall-replay-flutes',
    set: { length: 9, attack: 0.4 },
    ...looped(8, 3, 2, [55, 62, [69, 0.7], [71, 0.6]]),
    then: [breathe(0.25, 0.35)],
  },
  {
    n: 28,
    id: 'cistern-swell-am',
    name: 'Cistern swell {A}m',
    kind: 'pad',
    description:
      'A reed organ chord on {A} minor let go in a round stone tank and left to the walls.',
    preset: 'broadcast-hall-stone-cistern-reeds',
    ...played(
      12,
      [
        [0, 5, 45],
        [0, 5, 52],
        [0, 5, 57, 0.8],
        [0, 5, 64, 0.8],
        [0, 5, 72, 0.6],
      ],
      2.5,
    ),
  },
  {
    n: 29,
    id: 'soft-brass-stack-c',
    name: 'Soft brass stack {C}',
    kind: 'pad',
    description:
      'Synthesiser horns on a {C} major chord, each note starting dark and swelling, on tape.',
    preset: 'broadcast-hall-soft-brass-stack',
    set: { release: 2.5 },
    ...played(
      10,
      [
        [0, 5.5, 48],
        [0, 5.5, 55],
        [0, 5.5, 60, 0.8],
        [0, 5.5, 64, 0.8],
      ],
      2,
    ),
  },
  {
    n: 30,
    id: 'string-layer-echo-em7',
    name: 'String layer echo {E}m7',
    kind: 'pad',
    description:
      'Two detuned string layers on {E} minor seventh, one tape head repeating them in a plate.',
    preset: 'broadcast-hall-string-layer-echo',
    set: { detune: 7 },
    ...looped(8, 4, 2, [52, 59, [64, 0.7], [67, 0.4], [74, 0.3]]),
    then: [breathe(0.125, 0.5)],
  },
  {
    n: 31,
    id: 'quartet-on-parquet-dm',
    name: 'Quartet on parquet {D}m',
    kind: 'pad',
    description: 'Four players to a note on {D} minor, with bow noise, heard from across the hall.',
    preset: 'broadcast-hall-quartet-on-parquet',
    ...looped(8, 4, 2, [50, 57, [62, 0.7], [65, 0.4]]),
    then: [breathe(0.125, 0.4)],
  },
  {
    n: 32,
    id: 'muted-tape-bows-am',
    name: 'Muted tape bows {A}m',
    kind: 'pad',
    description:
      'A muted section with no vibrato on {A} minor with a ninth on top, swelling once every 16 s on tape.',
    preset: 'broadcast-hall-muted-tape-bows',
    ...looped(16, 5, 3, [45, 52, [57, 0.8], [60, 0.6], [71, 0.4]]),
    then: [breathe(0.0625, 0.45)],
  },
  {
    n: 33,
    id: 'gallery-voices-f6',
    name: 'Gallery voices {F}6',
    kind: 'pad',
    description:
      'A small choir singing ah on {F} sixth from the gallery, the hall between you and them.',
    preset: 'broadcast-hall-gallery-voices',
    set: { ensemble: 0.2, vibrato: 0 },
    ...looped(8, 5, 2, [53, 60, [62, 0.7], [69, 0.7]]),
    then: [breathe(0.125, 0.5)],
  },
  {
    n: 34,
    id: 'second-synth-pad-csus2',
    name: 'Second synth pad {C}sus2',
    kind: 'pad',
    description:
      'Two detuned sawtooths on {C}, {G} and {D} under a slow filter, in a two-voice chorus.',
    preset: 'broadcast-hall-second-synth-pad',
    set: { lfo1Rate: 0.125, lfo2Rate: 0.25, unisonDetune: 8 },
    ...looped(8, 5, 2, [48, 55, [60, 0.8], [62, 0.5]]),
    then: [breathe(0.125, 0.45)],
  },
  {
    n: 35,
    id: 'hollow-slow-pad-dsus4',
    name: 'Hollow slow pad {D}sus4',
    kind: 'pad',
    description:
      'A hollow wave on {D}, {G} and {A} drifting through its table, three tape heads behind.',
    preset: 'broadcast-hall-hollow-slow-pad',
    set: { rate: 0.0625, spread: 0.5 },
    ...looped(16, 6, 3, [50, 57, [62, 0.8], [67, 0.7]]),
    then: [breathe(0.0625, 0.45)],
  },
  {
    n: 36,
    id: 'reed-table-pad-am',
    name: 'Reed table pad {A}m',
    kind: 'pad',
    description:
      'A wave drifting from reed to sawtooth and back on {A} minor, on a reel in a spring tank.',
    preset: 'broadcast-hall-reed-table-pad',
    set: { rate: 0.0625 },
    ...looped(16, 4, 3, [45, 57, [64, 0.8], [72, 0.6]]),
    then: [breathe(0.0625, 0.35)],
  },
  {
    n: 37,
    id: 'string-ensemble-gsus4',
    name: 'String ensemble {G}sus4',
    kind: 'pad',
    description:
      'A seventies string ensemble on {G}, {C} and {D}, thin, through a slow phaser and a spring.',
    preset: 'broadcast-hall-string-ensemble-keys',
    set: { high: 0.15, ensemble: 0.6, width: 0.6 },
    effects: [
      {
        deviceId: 'phaser',
        preset: 'Slow swirl',
        params: { rate: 0.125, depth: 40, feedback: 10, stereo: 40, mix: 0.25 },
      },
      { deviceId: 'spring-reverb', preset: 'Two spring tank', params: { mix: 0.25 } },
    ],
    ...looped(8, 4, 2, [55, 60, 62, [67, 0.8], [74, 0.6]]),
  },
  {
    n: 38,
    id: 'ensemble-cellos-c',
    name: 'Ensemble cellos {C}',
    kind: 'pad',
    description:
      'The low octave of the string ensemble on {C}, {G} and {E}, through a warm amplifier.',
    preset: 'broadcast-hall-ensemble-cellos',
    ...looped(8, 6, 2, [48, 55, [64, 0.6]]),
    then: [breathe(0.125, 0.4), quarterTurn(8)],
    tuning: 'whole-cycles',
  },
  {
    n: 39,
    id: 'low-brass-chorale-em',
    name: 'Low brass chorale {E}m',
    kind: 'pad',
    description:
      'A section of low brass on {E} minor, slow to speak, played quietly onto tape in a hall.',
    preset: 'broadcast-hall-low-brass-chorale',
    ...looped(8, 6, 2, [40, 47, [52, 0.8], [55, 0.7]]),
  },
  {
    n: 40,
    id: 'still-steel-reel-fmaj7',
    name: 'Still steel reel {F}maj7',
    kind: 'pad',
    description:
      'A steel guitar on {F} major seventh, each note swelled in by the pedal and left long.',
    preset: 'broadcast-hall-still-steel-reel',
    ...played(
      11,
      [
        [0, 7, 53],
        [0.03, 7, 60],
        [0.06, 7, 64, 0.8],
        [0.09, 7, 69, 0.8],
      ],
      2.5,
    ),
  },
  {
    n: 41,
    id: 'late-clarinets-am',
    name: 'Late clarinets {A}m',
    kind: 'pad',
    description:
      'Three clarinets on {A} minor that take two seconds to arrive, tape repeats after them.',
    preset: 'broadcast-hall-late-clarinet-repeats',
    ...played(
      10,
      [
        [0, 5, 57],
        [0, 5, 64, 0.8],
        [0, 5, 72, 0.7],
      ],
      2,
    ),
  },
  {
    n: 42,
    id: 'backwards-answer-dm9',
    name: 'Backwards answer {D}m9',
    kind: 'pad',
    description:
      'A guitar chord on {D} minor ninth faded in with no pick, then answered backwards.',
    preset: 'broadcast-hall-backwards-answer',
    ...played(
      12,
      [
        [0, 4.5, 50],
        [0, 4.5, 57],
        [0, 4.5, 60, 0.8],
        [0, 4.5, 64, 0.8],
        [0, 4.5, 65, 0.8],
      ],
      3,
    ),
  },
  {
    n: 43,
    id: 'frozen-string-bar',
    name: 'Frozen string bar',
    kind: 'pad',
    description:
      'One moment of a string chord on {E} minor seventh held as grains while earlier moments drift back.',
    preset: 'broadcast-hall-frozen-bar',
    source: 'chamber-strings-em7',
    set: { spread: 0.2 },
    effects: [
      { deviceId: 'echo-memory', preset: 'Recalling', params: { spread: 0.3, mix: 0.3 } },
      { deviceId: 'hall-reverb', preset: 'Hall', params: { mix: 0.35 } },
    ],
    ...looped(8, 4, 2, [60]),
    then: [breathe(0.125, 0.45)],
  },
  {
    n: 44,
    id: 'tape-choir-bed-dm9',
    name: 'Tape choir bed {D}m9',
    kind: 'pad',
    description:
      'A choir chord from tape played low on {D} minor ninth with a soft start, under three tape heads.',
    preset: 'broadcast-hall-octave-down-bed',
    source: 'tape-choir-am9',
    set: { fine: 0 },
    ...looped(8, 4, 2, [65]),
    then: [breathe(0.125, 0.5)],
  },
  // Textures: the hall with nothing playing in it, the weather on its roof and the river outside.
  {
    n: 45,
    id: 'skylight-shower',
    name: 'Skylight shower',
    kind: 'texture',
    description:
      'A steady shower on the glass roof high above, evened out by tape, over the rumble of the room.',
    preset: 'broadcast-hall-skylight-shower',
    ...looped(8, 4, 2, [55]),
    then: [{ deviceId: 'noise-floor', preset: 'Empty room', params: { level: -28, width: 0.7 } }],
  },
  {
    n: 46,
    id: 'open-window-river',
    name: 'Open window river',
    kind: 'texture',
    description: 'Slow water moving past the open control-room window, a little way off.',
    preset: 'broadcast-hall-open-window-river',
    ...looped(8, 3, 2, [60]),
  },
  {
    n: 47,
    id: 'courtyard-birds-at-dawn',
    name: 'Courtyard birds at dawn',
    kind: 'texture',
    description:
      'Birds all round the yard outside at first light, far off in a long reverb, on tape.',
    preset: 'broadcast-hall-courtyard-blackbird',
    set: { density: 1, distance: 0.9, movement: 1, tone: 0.3, attack: 1 },
    effects: [
      { deviceId: 'tape', preset: 'Quarter inch' },
      { deviceId: 'expanse', preset: 'Open space', params: { mix: 0.6, width: 0.7 } },
      breathe(0.0625, 0.6),
    ],
    ...looped(16, 4, 3, [48, 53, 57, 60, 64, 67, 72, 77]),
  },
  {
    n: 48,
    id: 'empty-hall-at-night',
    name: 'Empty hall at night',
    kind: 'texture',
    description: 'The rumble and air of the hall at night with nothing playing in it.',
    instrument: {
      deviceId: 'atmosphere',
      preset: 'Hill wind',
      params: {
        density: 0.2,
        movement: 0.3,
        tone: 0.25,
        resonance: 0,
        size: 0.8,
        attack: 1,
        width: 0.6,
        volume: -12,
      },
    },
    effects: [
      { deviceId: 'noise-floor', preset: 'Empty room', params: { level: -30, width: 0.7 } },
      { deviceId: 'hall-reverb', preset: 'Hall', params: { mix: 0.3 } },
    ],
    ...looped(8, 3, 2, [43]),
  },
  {
    n: 49,
    id: 'dial-between-stations',
    name: 'Dial between stations',
    kind: 'texture',
    description:
      'Tuned bands of noise coming and going in the static of a shortwave set, in a room.',
    preset: 'broadcast-hall-air-in-pipes',
    set: { resonance: 6, attack: 0.3, breatheRate: 0.125 },
    effects: [
      { deviceId: 'radio', preset: 'Between stations', params: { static: 0.6 } },
      { deviceId: 'hall-reverb', preset: 'Room', params: { mix: 0.3 } },
    ],
    ...looped(8, 6, 2, [55, 62]),
  },
  {
    n: 50,
    id: 'blank-reel-hiss',
    name: 'Blank reel hiss',
    kind: 'texture',
    description:
      'The hiss of a blank reel running past the heads, over the low rumble of the machine.',
    instrument: {
      deviceId: 'atmosphere',
      preset: 'Mains hum',
      params: { attack: 0.5, volume: -30 },
    },
    effects: [
      {
        deviceId: 'noise-floor',
        preset: 'Wall of hiss',
        params: { level: -34, tone: -0.5, width: 0.4 },
      },
      { deviceId: 'noise-floor', preset: 'Distant rumble', params: { level: -26, width: 0.6 } },
      { deviceId: 'tape', preset: 'Quarter inch', params: { hiss: 0.1 } },
    ],
    ...looped(8, 3, 2, [43]),
  },
  {
    n: 51,
    id: 'control-room-rain',
    name: 'Control room rain',
    kind: 'texture',
    description: 'Single drops of rain on the control-room window, close, rounded off by tape.',
    instrument: {
      deviceId: 'atmosphere',
      preset: 'Rain on the window',
      params: { attack: 0.5, width: 0.6 },
    },
    effects: [
      soften(21),
      { deviceId: 'tape', preset: 'Quarter inch' },
      { deviceId: 'hall-reverb', preset: 'Room', params: { mix: 0.2 } },
    ],
    ...looped(8, 3, 2, [60]),
  },
  {
    n: 52,
    id: 'weir-down-the-river',
    name: 'Weir down the river',
    kind: 'texture',
    description:
      'Fast water over a weir a long way off: an even roar with its top and bottom trimmed.',
    instrument: {
      deviceId: 'outdoors',
      preset: 'Fast water',
      params: { distance: 0.75, tone: 0.3, attack: 1, width: 0.7 },
    },
    effects: [
      { deviceId: 'ambient-eq', params: { lowCut: 80, highCut: 6000 } },
      { deviceId: 'hall-reverb', preset: 'Room', params: { mix: 0.2 } },
    ],
    ...looped(8, 3, 2, [43]),
  },
  {
    n: 53,
    id: 'storm-over-the-river',
    name: 'Storm over the river',
    kind: 'texture',
    description:
      'Thunder far off whose rolls overlap, heard through the roof of the hall, on tape.',
    instrument: {
      deviceId: 'outdoors',
      preset: 'Far storm',
      params: { density: 1, tone: 0.6, movement: 0.4, width: 0.8 },
    },
    effects: [
      soften(8),
      { deviceId: 'tape', preset: 'Quarter inch' },
      { deviceId: 'hall-reverb', preset: 'Hall', params: { mix: 0.3 } },
    ],
    ...looped(16, 1, 3, [36, 43, 48, 53]),
  },
  {
    n: 54,
    id: 'shellac-disc-crackle',
    name: 'Shellac disc crackle',
    kind: 'texture',
    description: 'The crackle of an old disc turning with nothing cut on it, copied to tape.',
    instrument: {
      deviceId: 'atmosphere',
      preset: 'Old record',
      params: { density: 0.5, width: 0.6 },
    },
    effects: [
      soften(30),
      { deviceId: 'tape', preset: 'Quarter inch', params: { hiss: 0.7 } },
      { deviceId: 'hall-reverb', preset: 'Room', params: { mix: 0.15 } },
    ],
    ...looped(8, 2, 2, [60]),
  },
  {
    n: 55,
    id: 'stairwell-draught',
    name: 'Stairwell draught',
    kind: 'texture',
    description:
      'Wind finding its way up the stairwell: a low hollow rush that rises and falls, in a hall.',
    instrument: {
      deviceId: 'atmosphere',
      preset: 'Hill wind',
      params: { resonance: 0.2, movement: 0.35, tone: 0.35, size: 0.6, attack: 0.5, width: 0.6 },
    },
    effects: [{ deviceId: 'hall-reverb', preset: 'Hall', params: { preDelay: 60, mix: 0.4 } }],
    ...looped(16, 5, 3, [45]),
  },
  {
    n: 56,
    id: 'stretched-river-take',
    name: 'Stretched river take',
    kind: 'texture',
    description:
      'A recording of a stream played through slowly in grains, an octave down, half speed under it.',
    preset: 'broadcast-hall-stretched-take',
    source: 'brook-over-stones',
    ...looped(8, 4, 2, [48]),
  },
  // One-shots: a single note or one struck chord, starting on its attack and ringing out.
  {
    n: 57,
    id: 'moderator-upright-c',
    name: 'Moderator upright {C}',
    kind: 'oneshot',
    description:
      'One middle {C} on the upright with the cloth strip down, keys and wood in the microphone.',
    preset: 'broadcast-hall-moderator-upright',
    effects: [
      { deviceId: 'ambient-limiter', preset: 'Pinned', params: { gain: 8, release: 0.3, ride: 0 } },
      { deviceId: 'noise-floor', preset: 'Close mic', params: { level: -50 } },
      { deviceId: 'hall-reverb', preset: 'Room', params: { mix: 0.15 } },
    ],
    ...played(5, [[0, 2.5, 60]], 1.5),
  },
  {
    n: 58,
    id: 'neighbours-asleep-e',
    name: 'Neighbours asleep {E}',
    kind: 'oneshot',
    description:
      'A soft {E} in octaves with its fifth, soft pedal down, as much key noise as tone, on tape.',
    preset: 'broadcast-hall-neighbours-asleep',
    effects: [
      {
        deviceId: 'ambient-limiter',
        preset: 'Pinned',
        params: { gain: 10, release: 0.3, ride: 0 },
      },
      { deviceId: 'tape', preset: 'Quarter inch', params: { wow: 0.15, hiss: 0.3 } },
      { deviceId: 'fdn-reverb', preset: 'Room', params: { mix: 0.2 } },
    ],
    ...played(
      5,
      [
        [0, 3, 52, 0.9],
        [0.02, 3, 59, 0.8],
        [0.04, 3, 64],
      ],
      1.5,
    ),
  },
  {
    n: 59,
    id: 'pedal-down-chamber-am',
    name: 'Pedal down chamber {A}m',
    kind: 'oneshot',
    description:
      'An {A} minor chord with the sustain pedal held, from a loudspeaker in a bare chamber.',
    preset: 'broadcast-hall-pedal-down-chamber',
    ...played(
      8,
      [
        [0, 5, 45],
        [0, 5, 57],
        [0.01, 5, 60, 0.8],
        [0.02, 5, 64, 0.8],
      ],
      2,
    ),
  },
  {
    n: 60,
    id: 'tall-upright-f',
    name: 'Tall upright {F}',
    kind: 'oneshot',
    description:
      'A low {F} in octaves on the long bass strings: a heavy thump and a long wooden decay.',
    preset: 'broadcast-hall-tall-upright',
    ...played(
      7,
      [
        [0, 4.5, 29],
        [0, 4.5, 41, 0.8],
      ],
      1.5,
    ),
    then: [
      { deviceId: 'ambient-limiter', preset: 'Pinned', params: { gain: 5, release: 0.3, ride: 0 } },
    ],
  },
  {
    n: 61,
    id: 'ribbon-upright-g',
    name: 'Ribbon upright {G}',
    kind: 'oneshot',
    description:
      'An open {G} chord on the upright through one old microphone and a valve preamp, in mono.',
    preset: 'broadcast-hall-one-ribbon-microphone',
    ...played(
      5,
      [
        [0, 4, 43],
        [0.01, 4, 50, 0.8],
        [0.02, 4, 59, 0.8],
      ],
      1,
    ),
  },
  {
    n: 62,
    id: 'soundcheck-piano-d',
    name: 'Soundcheck piano {D}',
    kind: 'oneshot',
    description:
      'A {D} in octaves on the stage piano with nobody in the hall, heard from the tenth row.',
    preset: 'broadcast-hall-stage-at-soundcheck',
    effects: [
      { deviceId: 'hall-reverb', preset: 'Hall', params: { preDelay: 40, mix: 0.5 } },
      { deviceId: 'noise-floor', preset: 'Empty room', params: { level: -54 } },
    ],
    ...played(
      6,
      [
        [0, 3, 62],
        [0, 3, 74, 0.8],
      ],
      1.5,
    ),
  },
  {
    n: 63,
    id: 'one-string-each-b',
    name: 'One string each {B}',
    kind: 'oneshot',
    description:
      'One {B} with a single string to the note and no beating, other strings answering in the hall.',
    preset: 'broadcast-hall-one-string-each',
    ...played(6, [[0, 4, 71]], 1),
  },
  {
    n: 64,
    id: 'tine-and-chorus-em7',
    name: 'Tine and chorus {E}m7',
    kind: 'oneshot',
    description:
      'An {E} minor seventh on the tines with a short bell chime at the front, in a slow chorus.',
    preset: 'broadcast-hall-tine-and-chorus',
    ...played(
      5,
      [
        [0, 4, 52, 0.7],
        [0.01, 4, 59, 0.6],
        [0.02, 4, 62, 0.6],
        [0.03, 4, 67, 0.65],
      ],
      1,
    ),
  },
  {
    n: 65,
    id: 'amp-and-hum-a',
    name: 'Amp and hum {A}',
    kind: 'oneshot',
    description:
      'One low {A} on the electric piano from its own speaker across the room, barking, over mains hum.',
    preset: 'broadcast-hall-amp-and-hum',
    ...played(5, [[0, 3, 45]], 1.5),
    then: [{ deviceId: 'stereo-widener', preset: 'Narrow' }],
  },
  {
    n: 66,
    id: 'hot-desk-channel-g',
    name: 'Hot desk channel {G}',
    kind: 'oneshot',
    description:
      'A hard-played {G} in octaves on the electric piano, pushed into the red of a console channel.',
    preset: 'broadcast-hall-hot-desk-channel',
    set: { volume: -20 },
    ...played(
      4,
      [
        [0, 2.5, 43],
        [0, 2.5, 55, 0.8],
      ],
      0.6,
    ),
  },
  {
    n: 67,
    id: 'bass-marimba-c',
    name: 'Bass marimba {C}',
    kind: 'oneshot',
    description:
      'Soft yarn on a low rosewood bar on {C}, the note blooming out of its tube, close.',
    preset: 'broadcast-hall-bass-marimba',
    ...played(4, [[0, 3, 36]], 0.8),
  },
  {
    n: 68,
    id: 'piano-top-celesta-e',
    name: 'Piano-top celesta {E}',
    kind: 'oneshot',
    description:
      'One high {E} on the small celesta on top of the piano, soft and short, over tape hiss.',
    preset: 'broadcast-hall-piano-top-celesta',
    effects: [
      { deviceId: 'ambient-limiter', preset: 'Pinned', params: { gain: 4, release: 0.3, ride: 0 } },
      { deviceId: 'noise-floor', preset: 'Tape floor', params: { level: -52 } },
      { deviceId: 'bloom-reverb', preset: 'Still room', params: { mix: 0.3 } },
    ],
    ...played(3, [[0, 2, 76]], 1),
  },
  {
    n: 69,
    id: 'motor-off-vibes-a',
    name: 'Motor-off vibes {A}',
    kind: 'oneshot',
    description:
      'One {A} on the vibraphone with the motor off, struck softly and left to a long plate.',
    preset: 'broadcast-hall-motor-off-vibes',
    set: { decay: 1.2, damper: 0.5 },
    effects: [{ deviceId: 'plate-reverb', preset: 'Long plate', params: { mix: 0.25 } }],
    ...played(8, [[0, 2, 69]], 1.5),
  },
  {
    n: 70,
    id: 'far-glockenspiel-e',
    name: 'Far glockenspiel {E}',
    kind: 'oneshot',
    description:
      'One high {E} on a glockenspiel at the far side of the hall, its top trimmed, mostly room.',
    preset: 'broadcast-hall-far-glockenspiel',
    ...played(6, [[0, 2, 88]], 1.2),
  },
  {
    n: 71,
    id: 'dry-booth-nylon-a',
    name: 'Dry booth nylon {A}',
    kind: 'oneshot',
    description:
      'The open {A} string of a nylon-string guitar under a fingertip, close in a small dry booth.',
    preset: 'broadcast-hall-dry-booth-nylon',
    effects: [
      {
        deviceId: 'ambient-limiter',
        preset: 'Pinned',
        params: { gain: 10, release: 0.3, ride: 0 },
      },
      { deviceId: 'noise-floor', preset: 'Close mic', params: { level: -52 } },
      { deviceId: 'bloom-reverb', preset: 'Still room', params: { mix: 0.25 } },
    ],
    ...played(4, [[0, 2, 45]], 0.8),
  },
  {
    n: 72,
    id: 'damped-tongue-drum-d',
    name: 'Damped tongue drum {D}',
    kind: 'oneshot',
    description:
      'One {D} on a steel tongue drum set down on a rug, short and round, in a small dark room.',
    preset: 'broadcast-hall-damped-tongue-drum',
    ...played(3, [[0, 2.4, 50]], 0.6),
  },
  {
    n: 73,
    id: 'distant-hall-harp-c',
    name: 'Distant hall harp {C}',
    kind: 'oneshot',
    description: 'One low {C} string of a harp plucked softly at the far side of the hall.',
    preset: 'broadcast-hall-distant-hall-harp',
    ...played(5, [[0, 4, 48]], 1),
  },
  {
    n: 74,
    id: 'piano-lid-music-box-g',
    name: 'Piano-lid music box {G}',
    kind: 'oneshot',
    description:
      'One {G} of a music box set on the piano lid, the strings under it answering the comb.',
    preset: 'broadcast-hall-piano-lid-music-box',
    effects: [
      { deviceId: 'ambient-limiter', preset: 'Pinned', params: { gain: 4, release: 0.3, ride: 0 } },
      { deviceId: 'noise-floor', preset: 'Tape floor', params: { level: -52 } },
      { deviceId: 'sympathetic', preset: 'Piano pedal', params: { root: 9, mode: 1, mix: 0.3 } },
      { deviceId: 'hall-reverb', preset: 'Room', params: { mix: 0.2 } },
    ],
    ...played(4, [[0, 2, 79]], 1),
  },
  {
    n: 75,
    id: 'struck-open-string-e',
    name: 'Struck open string {E}',
    kind: 'oneshot',
    description:
      'One low {E} string struck with a soft hammer, a piano with its case taken away, on tape.',
    preset: 'broadcast-hall-struck-open-strings',
    ...played(6, [[0, 4, 40]], 1),
  },
  {
    n: 76,
    id: 'zither-strum-reel-d',
    name: 'Zither strum reel {D}',
    kind: 'oneshot',
    description:
      'A pick across {D}, its fifth and its octave on open strings, the others humming behind.',
    preset: 'broadcast-hall-zither-strum-reel',
    set: { strum: 40 },
    ...played(6, [[0, 4.5, 50]], 1.5),
  },
  {
    n: 77,
    id: 'glass-tine-keys-fmaj7',
    name: 'Glass tine keys {F}maj7',
    kind: 'oneshot',
    description:
      'An {F} major seventh on a four-operator electric piano, dulled by a cassette four-track.',
    preset: 'broadcast-hall-glass-tine-keys',
    ...played(
      5,
      [
        [0, 3.5, 53, 0.7],
        [0.01, 3.5, 60, 0.6],
        [0.02, 3.5, 64, 0.6],
        [0.03, 3.5, 69, 0.65],
      ],
      0.8,
    ),
  },
  {
    n: 78,
    id: 'brushed-chord-reel-dm7',
    name: 'Brushed chord reel {D}m7',
    kind: 'oneshot',
    description:
      'One octave of strings on {D} minor seventh brushed almost at once, dull, a pad underneath.',
    preset: 'broadcast-hall-brushed-chord-reel',
    set: { pad: 0.2 },
    ...played(
      4,
      [
        [0, 1.2, 50],
        [0, 1.2, 57],
        [0, 1.2, 60],
        [0, 1.2, 65],
      ],
      1,
    ),
  },
  // Phrases: a few notes in free time, ringing out or coming round on themselves.
  {
    n: 79,
    id: 'upright-and-echo-am',
    name: 'Upright and echo {A}m',
    kind: 'melodic',
    description:
      'The damped upright falls through {A} minor into one tape head, each repeat duller; it comes round.',
    preset: 'broadcast-hall-upright-and-echo',
    ...cycled(8, [
      [0, 1.6, 69, 0.9],
      [1.07, 1.2, 64, 0.8],
      [2.53, 1.5, 60, 0.85],
      [3.74, 1.6, 62, 0.75],
      [5.61, 1.6, 57, 0.8],
    ]),
  },
  {
    n: 80,
    id: 'half-speed-overdub-c',
    name: 'Half-speed overdub {C}',
    kind: 'melodic',
    description:
      'A felt piano climbs from {C} and waits while it comes back under itself an octave down, half as fast.',
    preset: 'broadcast-hall-half-speed-overdub',
    ...played(
      12,
      [
        [0, 1.2, 60, 0.8],
        [0.71, 1, 64, 0.75],
        [1.52, 1.6, 67, 0.8],
        [3.05, 2.4, 72, 0.9],
        [5.84, 1.4, 71, 0.7],
        [6.57, 2.6, 67, 0.75],
      ],
      2.5,
    ),
  },
  {
    n: 81,
    id: 'moderator-round-f',
    name: 'Moderator round {F}',
    kind: 'melodic',
    description:
      'The upright with its cloth strip down, slow notes over {F} and then over {D}; it comes round.',
    preset: 'broadcast-hall-moderator-upright',
    ...cycled(12, [
      [0, 5.5, 41, 0.55],
      [0.08, 5.5, 48, 0.45],
      [1.52, 3.5, 69, 0.9],
      [2.41, 3, 67, 0.85],
      [3.63, 2.5, 72, 0.95],
      [5.02, 1.4, 71, 0.8],
      [6.31, 5.3, 38, 0.55],
      [6.38, 5.3, 45, 0.45],
      [7.77, 3, 65, 0.9],
      [8.6, 3, 64, 0.85],
      [9.93, 2, 69, 0.9],
    ]),
  },
  {
    n: 82,
    id: 'echo-arpeggio-dm',
    name: 'Echo arpeggio {D}m',
    kind: 'melodic',
    description:
      'Half-closed sawtooth notes open up {D} minor into a dotted tape echo until they blur; it comes round.',
    preset: 'broadcast-hall-echo-arpeggio',
    ...cycled(8, [
      [0, 0.3, 50, 0.8],
      [0.62, 0.3, 57, 0.7],
      [1.41, 0.3, 62, 0.75],
      [2.03, 0.3, 65, 0.7],
      [3.37, 0.35, 69, 0.8],
      [4.48, 0.4, 64, 0.65],
      [5.91, 0.4, 60, 0.7],
    ]),
  },
  {
    n: 83,
    id: 'whistling-filter-e',
    name: 'Whistling filter {E}',
    kind: 'melodic',
    description:
      'A slow line from {E} whose filter whistles over each note, with faint dark repeats in a hall.',
    preset: 'broadcast-hall-whistling-filter',
    set: { attack: 0.02 },
    effects: [
      { deviceId: 'analog-delay', preset: 'Dark echo', params: { mix: 0.15 } },
      { deviceId: 'fdn-reverb', preset: 'Hall', params: { mix: 0.3 } },
    ],
    ...played(
      11,
      [
        [0, 1.8, 52, 0.5],
        [2.05, 1.2, 55, 0.45],
        [3.42, 2.4, 59, 1],
        [6.1, 1.6, 57, 0.5],
      ],
      2,
    ),
  },
  {
    n: 84,
    id: 'tines-after-hours-dm',
    name: 'Tines after hours {D}m',
    kind: 'melodic',
    description:
      'Round, dark tines wander over {D} minor with a tape repeat behind them and a short spring; it comes round.',
    preset: 'broadcast-hall-tines-after-hours',
    set: { tremoloRate: 1.25 },
    ...cycled(8, [
      [0, 2.2, 50, 0.7],
      [0.04, 2.2, 57, 0.6],
      [1.27, 1.5, 65, 0.65],
      [2.11, 1.5, 64, 0.6],
      [3.46, 2.2, 60, 0.6],
      [4.83, 1.8, 62, 0.6],
      [6.02, 1.4, 57, 0.55],
    ]),
  },
  {
    n: 85,
    id: 'looped-tines-g',
    name: 'Looped tines {G}',
    kind: 'melodic',
    description:
      'Long tines on {G} caught on four seconds of tape between two machines; it comes round.',
    preset: 'broadcast-hall-looped-tines',
    set: { tremoloRate: 1.125 },
    ...cycled(
      8,
      [
        [0, 0.7, 55, 0.7],
        [0.83, 0.6, 62, 0.6],
        [2.21, 0.7, 67, 0.65],
        [3.02, 0.6, 64, 0.6],
        [4.63, 0.7, 59, 0.6],
        [6.11, 0.8, 62, 0.6],
      ],
      { passes: 2 },
    ),
  },
  {
    n: 86,
    id: 'pipes-into-echo-f',
    name: 'Pipes into echo {F}',
    kind: 'melodic',
    description:
      'Flute pipes with a puff of wind on each note of {F} lydian, three tape heads after them; it comes round.',
    preset: 'broadcast-hall-pipes-into-echo',
    ...cycled(8, [
      [0, 0.5, 65, 0.8],
      [0.93, 0.4, 69, 0.7],
      [1.61, 0.6, 72, 0.75],
      [3.2, 0.5, 71, 0.7],
      [4.37, 0.8, 67, 0.75],
      [5.9, 0.5, 64, 0.7],
    ]),
  },
  {
    n: 87,
    id: 'low-pattern-echo-e',
    name: 'Low pattern echo {E}',
    kind: 'melodic',
    description:
      'Short bass notes on {E} that open and shut, two tape heads making a pattern of them; it comes round.',
    preset: 'broadcast-hall-low-pattern-echo',
    ...cycled(8, [
      [0, 0.35, 52, 0.8],
      [0.83, 0.3, 50, 0.7],
      [2.46, 0.35, 45, 0.75],
      [4.27, 0.35, 40, 0.8],
      [5.52, 0.3, 43, 0.7],
      [6.21, 0.3, 45, 0.7],
    ]),
    loopFold: 'power',
    then: [
      {
        deviceId: 'ambient-limiter',
        preset: 'Pinned',
        params: { gain: 12, release: 0.3, ride: 0 },
      },
    ],
  },
  {
    n: 88,
    id: 'round-lead-voice-am',
    name: 'Round lead voice {A}m',
    kind: 'melodic',
    description:
      'A round one-voice lead climbs {A} minor and slides back down, with three echoes and a small plate.',
    preset: 'broadcast-hall-round-lead-voice',
    ...played(
      11,
      [
        [0, 1, 57],
        [1.31, 0.8, 60],
        [2.23, 1.9, 64],
        [3.82, 0.6, 62],
        [4.93, 0.9, 60],
        [6.07, 1.5, 57],
      ],
      2.5,
    ),
  },
  {
    n: 89,
    id: 'rubber-pluck-g',
    name: 'Rubber pluck {G}',
    kind: 'melodic',
    description:
      'A resonant plucked bass on {G} with chorused bucket-brigade repeats in a short room; it comes round.',
    preset: 'broadcast-hall-rubber-pluck-repeats',
    ...cycled(8, [
      [0, 0.6, 43, 0.8],
      [0.84, 0.5, 50, 0.7],
      [1.77, 0.6, 55, 0.75],
      [3.02, 0.5, 53, 0.7],
      [4.21, 0.6, 47, 0.7],
      [5.38, 0.6, 50, 0.7],
      [6.44, 0.5, 45, 0.65],
    ]),
    loopFold: 'power',
    then: [
      { deviceId: 'ambient-limiter', preset: 'Pinned', params: { gain: 8, release: 0.3, ride: 0 } },
    ],
  },
  {
    n: 90,
    id: 'marimba-into-echo-c',
    name: 'Marimba into echo {C}',
    kind: 'melodic',
    description:
      'Short dry marimba notes on {C} into a dotted tape echo, doubling themselves; it comes round.',
    preset: 'broadcast-hall-marimba-into-echo',
    ...cycled(8, [
      [0, 0.4, 60, 0.8],
      [0.71, 0.4, 64, 0.7],
      [1.63, 0.4, 67, 0.75],
      [2.92, 0.4, 72, 0.8],
      [4.18, 0.4, 69, 0.7],
      [5.29, 0.4, 67, 0.7],
      [6.5, 0.4, 62, 0.65],
    ]),
  },
  {
    n: 91,
    id: 'muted-steel-echo-em',
    name: 'Muted steel echo {E}m',
    kind: 'melodic',
    description:
      'Palm-muted steel strings picked on {E} minor into two tape heads that answer; it comes round.',
    preset: 'broadcast-hall-muted-steel-echo',
    ...cycled(8, [
      [0, 0.3, 52, 0.8],
      [0.58, 0.3, 57, 0.7],
      [1.49, 0.3, 64, 0.75],
      [2.31, 0.3, 62, 0.7],
      [3.6, 0.3, 55, 0.7],
      [4.45, 0.3, 60, 0.7],
      [5.73, 0.3, 57, 0.7],
      [6.81, 0.3, 55, 0.65],
    ]),
    then: [
      {
        deviceId: 'ambient-limiter',
        preset: 'Pinned',
        params: { gain: 10, release: 0.3, ride: 0 },
      },
    ],
  },
  {
    n: 92,
    id: 'soft-pluck-pattern-am',
    name: 'Soft pluck pattern {A}m',
    kind: 'melodic',
    description:
      'A short synthesiser pluck high on {A} minor into a dotted tape echo and a plate; it comes round.',
    preset: 'broadcast-hall-soft-pluck-pattern',
    ...cycled(8, [
      [0, 0.5, 76, 0.8],
      [1.37, 0.5, 72, 0.7],
      [1.93, 0.5, 69, 0.75],
      [4.11, 0.5, 74, 0.75],
      [5.26, 0.5, 71, 0.7],
    ]),
  },
  {
    n: 93,
    id: 'steel-pan-echo-d',
    name: 'Steel pan echo {D}',
    kind: 'melodic',
    description:
      'A hand-played steel pan on {D} dorian into a dotted tape echo and a long spring; it comes round.',
    preset: 'broadcast-hall-steel-pan-echo',
    ...cycled(
      8,
      [
        [0, 1, 50, 0.75],
        [0.9, 0.8, 57, 0.6],
        [1.72, 0.8, 60, 0.6],
        [3.11, 1, 62, 0.7],
        [4.3, 0.8, 65, 0.6],
        [5.44, 0.8, 64, 0.6],
        [6.6, 0.8, 57, 0.55],
      ],
      { passes: 2 },
    ),
  },
  {
    n: 94,
    id: 'damped-harp-f',
    name: 'Damped harp {F}',
    kind: 'melodic',
    description:
      'Hand-stopped harp strings climb an {F} chord and step back, with dark repeats and a small plate.',
    preset: 'broadcast-hall-damped-harp-repeats',
    ...played(
      8,
      [
        [0, 0.8, 53, 0.8],
        [0.52, 0.8, 60, 0.7],
        [1.21, 0.8, 65, 0.75],
        [1.83, 0.8, 69, 0.75],
        [2.9, 0.8, 72, 0.85],
        [4.05, 1.5, 69, 0.7],
        [4.71, 1.5, 65, 0.7],
      ],
      1.5,
    ),
  },
  {
    n: 95,
    id: 'slide-and-echo-g',
    name: 'Slide and echo {G}',
    kind: 'melodic',
    description:
      'A steel guitar on {G} bends a string up under the bar and answers itself higher, with tape repeats.',
    preset: 'broadcast-hall-slide-and-echo',
    set: { swell: 0, pick: 0.85 },
    ...played(
      13,
      [
        [0, 3.2, 55, 0.5],
        [0.04, 3.2, 62, 0.5],
        [1.5, 1.4, 64, 0.7],
        [3.6, 3, 60, 0.85],
        [3.64, 3, 67, 0.85],
        [5.2, 1.2, 69, 0.7],
        [7.1, 2.2, 62, 0.8],
        [7.14, 2.2, 67, 0.75],
      ],
      2.5,
    ),
  },
  {
    n: 96,
    id: 'reel-pan-pipes-am',
    name: 'Reel pan pipes {A}m',
    kind: 'melodic',
    description:
      'Pan pipes rise from {A} to a long {E} and fall back, a chiff on every note, into three tape heads.',
    preset: 'broadcast-hall-reel-pan-pipes',
    ...played(
      10,
      [
        [0, 0.9, 69, 0.45],
        [1.14, 0.5, 72, 0.4],
        [1.83, 1.3, 76, 1],
        [3.42, 0.5, 74, 0.5],
        [4.1, 0.7, 72, 0.4],
        [5.02, 1.4, 69, 0.45],
      ],
      2,
    ),
  },
  {
    n: 97,
    id: 'stairwell-trumpet-d',
    name: 'Stairwell trumpet {D}',
    kind: 'melodic',
    description:
      'A soft trumpet calls from {D} up to a long high {D} and comes down, somewhere up the stairwell.',
    preset: 'broadcast-hall-stairwell-trumpet',
    set: { attack: 0.04 },
    ...played(
      11,
      [
        [0, 1.1, 62, 0.7],
        [1.33, 0.6, 69, 0.7],
        [2.1, 2.2, 74, 0.9],
        [4.7, 0.7, 72, 0.7],
        [5.5, 2, 69, 0.75],
      ],
      2,
    ),
  },
  {
    n: 98,
    id: 'soft-mallet-voice-g',
    name: 'Soft mallet voice {G}',
    kind: 'melodic',
    description:
      'A nearly pure struck tone circles {G} mixolydian with dark repeats in a room; it comes round.',
    preset: 'broadcast-hall-soft-mallet-voice',
    ...cycled(8, [
      [0, 1, 67, 0.8],
      [0.77, 1, 71, 0.7],
      [1.93, 1, 74, 0.75],
      [3.08, 1, 77, 0.7],
      [4.31, 1, 76, 0.7],
      [5.6, 1, 72, 0.7],
      [6.72, 1, 69, 0.65],
    ]),
  },
  {
    n: 99,
    id: 'glass-bar-echo-c',
    name: 'Glass bar echo {C}',
    kind: 'melodic',
    description:
      'Soft bars of four sine operators fall from a high {C}, three tape heads and the hall after them; it comes round.',
    preset: 'broadcast-hall-glass-bar-echo',
    ...cycled(8, [
      [0, 1.5, 84, 0.8],
      [1.07, 1.2, 79, 0.7],
      [2.3, 1.5, 76, 0.75],
      [3.94, 1.2, 74, 0.7],
      [5.2, 1.5, 67, 0.7],
      [6.36, 1.2, 71, 0.65],
    ]),
  },
  {
    n: 100,
    id: 'buzzing-bridge-round-e',
    name: 'Buzzing bridge round {E}',
    kind: 'melodic',
    description:
      'Strings on {B} and {E} plucked in turn, each opening into overtones, on a reel in a plate; it comes round.',
    preset: 'broadcast-hall-buzzing-bridge-reel',
    set: { speed: 12 },
    ...cycled(8, [[0, 7.9, 52]]),
  },
])
