// The sounds of the pack "Cornish Lucid Dreams": its presets played, a hundred sounds to
// paint with. Numbers 6001 to 6100.

import { type PatchDevice } from '../../../core/devices/patch'
import { PRESETS } from '../packs/lucid'
import { type FactorySound } from '../types'
import { breathe, cycled, looped, played, quarterTurn, soften, packSounds } from './recipe'

/** Nearly mono: for a sound thrown so wide by a delay or a large space that it thins out in mono. */
const CLOSE: PatchDevice = { deviceId: 'stereo-widener', params: { width: 0.12 } }

/** Pushes a held tone hard into a limiter, so a level that wanders by a few dB stays where it is. */
const FLAT: PatchDevice = { deviceId: 'fet-limiter', preset: 'Flattened' }

/** Brings the two sides in: a pad whose sides beat against each other thins out in mono. */
const NARROW: PatchDevice = { deviceId: 'stereo-widener', preset: 'Narrow' }

export const SOUNDS: readonly FactorySound[] = packSounds('lucid', 6000, PRESETS, [
  // Drones: one note or a bare interval, held level.
  {
    n: 1,
    id: 'mine-rumble-c',
    name: 'Mine rumble {C}',
    kind: 'drone',
    description: 'Octaves of a low {C} over a heavy sub, the filter nearly shut, pushed into tape.',
    preset: 'lucid-mine-rumble',
    set: { movement: 0.15 },
    then: [quarterTurn(8)],
    ...looped(8, 7, 3, [36]),
    tuning: 'whole-cycles',
  },
  {
    n: 2,
    id: 'under-bed-sub-e',
    name: 'Under-bed sub {E}',
    kind: 'drone',
    description: 'A near sine on a low {E} over its sub, pressed into tape: a floor for the rest.',
    preset: 'lucid-under-bed-sub',
    set: { beat: 0 },
    then: [quarterTurn(8)],
    ...looped(8, 3, 2, [40]),
    tuning: 'whole-cycles',
  },
  {
    n: 3,
    id: 'cellar-bow-d',
    name: 'Cellar bow {D}',
    kind: 'drone',
    description:
      'A low {D} bowed hard and slowly with no vibrato, weighted by a tape preamp, in a dark well of echoes.',
    preset: 'lucid-cellar-bow',
    set: { detune: 0, vibrato: 0 },
    then: [quarterTurn(8)],
    ...looped(8, 4, 3, [38]),
    tuning: 'whole-cycles',
  },
  {
    n: 4,
    id: 'pylon-hum-f',
    name: 'Pylon hum {F}',
    kind: 'drone',
    description:
      'The harmonic series of a low {F} as a buzzing saw hum over mains hum, held still in a small dark room.',
    preset: 'lucid-pylon-hum',
    set: { movement: 0.05 },
    effects: [
      { deviceId: 'noise-floor', preset: 'Amp left on', params: { type: 3, level: -44 } },
      { deviceId: 'expanse', preset: 'Small dark room', params: { modDepth: 0 } },
    ],
    then: [FLAT, quarterTurn(8)],
    ...looped(8, 5, 3, [41]),
    tuning: 'whole-cycles',
  },
  {
    n: 5,
    id: 'low-reed-a',
    name: 'Low reed, slowed {A}',
    kind: 'drone',
    description:
      'A low reed on {A} over its own half-speed copy an octave down, on slow tape in a hall.',
    preset: 'lucid-low-reed-slowed',
    set: { breath: 0.3 },
    effects: [
      { deviceId: 'half-speed', preset: 'Smooth octave', params: { highCut: 4000, mix: 0.6 } },
      { deviceId: 'tape', preset: 'Quarter inch', params: { speed: 2, wow: 0, flutter: 0 } },
      { deviceId: 'hall-reverb', preset: 'Hall' },
    ],
    then: [quarterTurn(8)],
    ...looped(8, 6, 3, [45]),
    tuning: 'whole-cycles',
  },
  {
    n: 6,
    id: 'landing-light-c',
    name: 'Landing light {C}',
    kind: 'drone',
    description:
      'A dark polysynth {C} with its chorus off, held level on cassette in a plain dull hall.',
    preset: 'lucid-landing-light-pad',
    set: { chorus: 0 },
    effects: [
      {
        deviceId: 'tape',
        preset: 'Cassette four-track',
        params: { wow: 0, flutter: 0, hiss: 0.3 },
      },
      { deviceId: 'hall-reverb', preset: 'Hall', params: { damping: 3000, mix: 0.4 } },
    ],
    then: [quarterTurn(8)],
    ...looped(8, 6, 3, [48]),
    tuning: 'whole-cycles',
  },
  {
    n: 7,
    id: 'night-section-a',
    name: 'Night section {A}',
    kind: 'drone',
    description: 'A resonant, vowel-like tone on {A} with no bass, held still in a cathedral.',
    preset: 'lucid-night-section',
    set: { detune: 0 },
    effects: [{ deviceId: 'hall-reverb', preset: 'Cathedral', params: { mix: 0.4 } }],
    then: [quarterTurn(8)],
    ...looped(8, 6, 3, [57]),
    tuning: 'whole-cycles',
  },
  {
    n: 8,
    id: 'bowed-gong-a',
    name: 'Bowed gong {A}',
    kind: 'drone',
    description:
      'A gong on {A} kept singing by a bow, its metal combed a little by a slow flanger, in a hall.',
    preset: 'lucid-bowed-gong',
    set: { detune: 0, brightness: 0.85 },
    effects: [
      {
        deviceId: 'flanger',
        preset: 'Metal resonator',
        params: { rate: 0.125, feedback: 70, mix: 0.2 },
      },
      { deviceId: 'hall-reverb', preset: 'Hall', params: { mix: 0.4 } },
    ],
    then: [NARROW, quarterTurn(8)],
    ...looped(8, 5, 3, [57]),
    tuning: 'whole-cycles',
  },
  {
    n: 9,
    id: 'filter-left-open-g',
    name: 'Filter left open {G}',
    kind: 'drone',
    description:
      'A low {G} on a dark brass pad long after its filter has opened, on tape in a dark hall.',
    preset: 'lucid-filter-opens-late',
    set: { detune: 0 },
    effects: [
      { deviceId: 'saturator', preset: 'On tape', params: { outputDb: -4 } },
      { deviceId: 'hall-reverb', preset: 'Dark hall', params: { mix: 0.4 } },
    ],
    then: [quarterTurn(8)],
    ...looped(8, 10, 3, [43]),
    tuning: 'whole-cycles',
  },
  {
    n: 10,
    id: 'fence-wire-d',
    name: 'Singing fence wire {D}',
    kind: 'drone',
    description:
      'A string on {D} and {A} held singing by a magnet, dead level, in a large dark space.',
    preset: 'lucid-singing-fence-wire',
    set: { vibrato: 0, detune: 0 },
    effects: [
      {
        deviceId: 'expanse',
        preset: 'Open space',
        params: { highCut: 4000, mix: 0.45, modDepth: 0 },
      },
    ],
    then: [CLOSE, quarterTurn(8)],
    ...looped(8, 5, 3, [50, 57, 62]),
    tuning: 'whole-cycles',
  },
  {
    n: 11,
    id: 'tone-folding-over-g',
    name: 'Tone folding over {G}',
    kind: 'drone',
    description:
      'A folded tone on {G} turning itself inside out, through a driven spring and a murky delay.',
    preset: 'lucid-tone-folding-over',
    set: { drift: 0, chance: 0 },
    effects: [
      { deviceId: 'spring-reverb', preset: 'Dub send', params: { mix: 0.3 } },
      { deviceId: 'analog-delay', preset: 'Murky', params: { mix: 0.25, modDepth: 0 } },
    ],
    then: [NARROW, quarterTurn(8)],
    ...looped(8, 5, 3, [55]),
    tuning: 'whole-cycles',
  },
  {
    n: 12,
    id: 'hollow-hours-e',
    name: 'Hollow hours {E}',
    kind: 'drone',
    description: 'A hollow table on {E} and {B} over its sub, held still on tape in a dark hall.',
    preset: 'lucid-hollow-hours',
    set: { detune: 0, motion: 0 },
    effects: [
      { deviceId: 'tape', preset: 'Seasick', params: { wow: 0, flutter: 0 } },
      { deviceId: 'hall-reverb', preset: 'Dark hall', params: { mix: 0.45 } },
    ],
    then: [NARROW, quarterTurn(8)],
    ...looped(8, 6, 3, [52, 59]),
    tuning: 'whole-cycles',
  },

  // Pads: chords that swell and move.
  {
    n: 13,
    id: 'hymn-for-sleepers-f',
    name: 'Hymn for sleepers {F}',
    kind: 'pad',
    description:
      'Detuned saws on {F} major behind a nearly shut filter, in a long dark plate on tape.',
    preset: 'lucid-hymn-for-sleepers',
    set: { unisonDetune: 12, osc2Fine: 8, unisonSpread: 0.5 },
    then: [NARROW, breathe(0.125, 0.5)],
    ...looped(8, 6, 3, [41, 53, 57, 60]),
  },
  {
    n: 14,
    id: 'two-tones-beating-g',
    name: 'Two tones beating {G}',
    kind: 'pad',
    description:
      'Pairs of sines on a low {G} and {D} a few cents apart, beating and swelling in a dark hall.',
    preset: 'lucid-two-tones-beating',
    set: { lfo1Rate: 0.125, unisonSpread: 0 },
    effects: [
      { deviceId: 'freq-shifter', preset: 'Slow drift', params: { width: 0, mix: 0.3 } },
      { deviceId: 'hall-reverb', preset: 'Dark hall', params: { mix: 0.4 } },
    ],
    ...looped(8, 6, 3, [43, 50]),
  },
  {
    n: 15,
    id: 'floorboards-c',
    name: 'Under the floorboards {C}',
    kind: 'pad',
    description:
      'A hollow pulse under {C} and {G} with a flat triangle against it, dark in a long damped hall.',
    preset: 'lucid-under-the-floorboards',
    set: { osc2Fine: -22, unisonDetune: 12 },
    ...looped(8, 6, 3, [48, 55, 60]),
  },
  {
    n: 16,
    id: 'night-light-pad-c',
    name: 'Night light pad {C}',
    kind: 'pad',
    description:
      'A triangle and a thin pulse on {C} with a ninth, unsteady, through old converters.',
    preset: 'lucid-night-light-pad',
    set: { unisonDetune: 12, osc2Fine: 7 },
    then: [NARROW, breathe(0.125, 0.6)],
    ...looped(8, 7, 3, [48, 55, 60, 62]),
  },
  {
    n: 17,
    id: 'sung-through-walls-g',
    name: 'Sung through walls {G}',
    kind: 'pad',
    description:
      'A vowel table on octaves and a fifth of {G} with its top shut off, in a hall that sings oo.',
    preset: 'lucid-sung-through-walls',
    set: { detune: 10 },
    then: [NARROW, breathe(0.125, 0.4)],
    ...looped(8, 6, 3, [43, 55, 62, 67]),
  },
  {
    n: 18,
    id: 'glass-motion-am',
    name: 'Glass motion {A}m',
    kind: 'pad',
    description:
      'A glass table on {A} minor shimmering across the chord, with chorus echoes in a plate.',
    preset: 'lucid-glass-motion',
    set: { rate: 0.875, detune: 6 },
    then: [NARROW, breathe(0.125, 0.5)],
    ...looped(8, 7, 3, [57, 64, 72]),
  },
  {
    n: 19,
    id: 'flat-reed-organ-c',
    name: 'Flat reed organ {C}',
    kind: 'pad',
    description:
      'Reed waves on {C} major a little apart, in a slow rotating speaker across the room.',
    preset: 'lucid-flat-reed-organ',
    set: { detune: 14, rate: 0.125 },
    then: [NARROW, breathe(0.125, 0.4)],
    ...looped(8, 4, 3, [48, 55, 60, 64]),
  },
  {
    n: 20,
    id: 'pillow-tone-f',
    name: 'Pillow tone {F}',
    kind: 'pad',
    description:
      'Near sines on {F} over a strong sub that swell and sink like slow breathing, in a cathedral.',
    preset: 'lucid-pillow-tone',
    then: [breathe(0.125, 0.3)],
    ...looped(8, 6, 3, [53, 60, 65]),
  },
  {
    n: 21,
    id: 'struck-air-pad-a',
    name: 'Struck air pad {A}',
    kind: 'pad',
    description:
      'A held, bell-like pad on {A} and {E} at an inharmonic ratio, through a deep chorus.',
    preset: 'lucid-struck-air-pad',
    set: { detune: 6, spread: 0.3 },
    then: [NARROW, breathe(0.125, 0.4)],
    ...looped(8, 6, 3, [57, 64]),
  },
  {
    n: 22,
    id: 'tender-ooh-em',
    name: 'Tender ooh {E}m',
    kind: 'pad',
    description: 'Small high voices on ooh holding {E} minor, soft at the edges, in a long plate.',
    preset: 'lucid-tender-ooh',
    set: { ensemble: 0, vibrato: 0 },
    effects: [
      {
        deviceId: 'chorus',
        params: { rate: 0.5, depth: 30, delayMs: 18, spread: 60, feedback: 10, mix: 0.25 },
      },
      { deviceId: 'plate-reverb', preset: 'Long plate', params: { damping: 0.45, mix: 0.45 } },
    ],
    then: [NARROW, breathe(0.125, 0.5)],
    ...looped(8, 5, 3, [59, 64, 67, 71]),
    loopFold: 'linear',
  },
  {
    n: 23,
    id: 'slowed-treble-e',
    name: 'Slowed treble {E}',
    kind: 'pad',
    description:
      'High voices on {E} and {B} dropped an octave by a fluttering shifter, sampled, in a plate.',
    preset: 'lucid-slowed-treble',
    then: [NARROW, breathe(0.125, 0.4)],
    ...looped(8, 7, 3, [64, 71, 76]),
  },
  {
    n: 24,
    id: 'ring-of-tin-e',
    name: 'Ring of tin {E}',
    kind: 'pad',
    description:
      'Two layers on {E} and {B} ring-modulated into clanging tones, repeated by a murky delay.',
    preset: 'lucid-ring-of-tin',
    then: [NARROW, breathe(0.125, 0.4)],
    ...looped(8, 4, 3, [52, 59]),
  },
  {
    n: 25,
    id: 'strings-gone-sour-dm',
    name: 'Strings gone sour {D}m7',
    kind: 'pad',
    description:
      'String layers on {D} minor seventh a quarter of a semitone apart, chorused and sampled.',
    preset: 'lucid-strings-gone-sour',
    then: [NARROW, breathe(0.125, 0.5)],
    ...looped(8, 5, 3, [50, 57, 65, 72]),
  },
  {
    n: 26,
    id: 'filter-opens-late-g',
    name: 'Filter opens late {G}',
    kind: 'pad',
    description:
      'A low {G} major pad that starts nearly shut and takes most of the note to open, then sinks.',
    preset: 'lucid-filter-opens-late',
    set: { release: 3 },
    ...played(
      12,
      [
        [0, 7, 43],
        [0, 7, 50],
        [0, 7, 59],
      ],
      3,
    ),
  },
  {
    n: 27,
    id: 'muted-hymn-strings-f',
    name: 'Muted hymn strings {F}',
    kind: 'pad',
    description:
      'Five muted players on each note of {F} major, on tired tape in a dark hall that breathes.',
    preset: 'lucid-muted-hymn-strings',
    set: { scatter: 0.4 },
    then: [breathe(0.125, 0.4)],
    ...looped(8, 5, 3, [41, 48, 57, 60, 65]),
  },
  {
    n: 28,
    id: 'thin-high-strings-g',
    name: 'Thin high strings {G}',
    kind: 'pad',
    description: 'Only the top octave of the ensemble on {G} major, wandering in pitch, on tape.',
    preset: 'lucid-thin-high-strings',
    set: { drift: 0.3 },
    then: [NARROW, breathe(0.125, 0.5)],
    ...looped(8, 7, 3, [55, 62, 67, 71]),
  },
  {
    n: 29,
    id: 'unison-adrift-b',
    name: 'Unison adrift {B}',
    kind: 'pad',
    description:
      'Near sines on octaves of {B} wandering in and out of tune, swelling at random in a cathedral.',
    preset: 'lucid-unison-adrift',
    set: { width: 0.3 },
    effects: [
      { deviceId: 'tremolo', preset: 'Sea swell', params: { rate: 0.2, depth: 0.5, phase: 0 } },
      { deviceId: 'hall-reverb', preset: 'Cathedral', params: { mix: 0.25 } },
    ],
    then: [NARROW],
    ...looped(8, 6, 3, [47, 59]),
  },
  {
    n: 30,
    id: 'choir-reel-slowed-am',
    name: 'Choir reel, slowed {A}m',
    kind: 'pad',
    description:
      'A choir on worn tape at half speed on {A} minor, wavering and hissing, in a long plate.',
    preset: 'lucid-choir-reel-slowed',
    set: { length: 9, age: 0.35, vibrato: 0.2, players: 0.4 },
    then: [NARROW, breathe(0.125, 0.5)],
    ...looped(8, 3, 2, [57, 64, 69, 72]),
  },
  {
    n: 31,
    id: 'loose-oscillators-d',
    name: 'Loose oscillators {D}',
    kind: 'pad',
    description:
      'A saw on {D} and a flat pulse an octave under it, twitching in pitch, in a slack spring.',
    preset: 'lucid-loose-oscillators',
    ...looped(8, 4, 3, [50]),
  },
  {
    n: 32,
    id: 'bell-held-under-c',
    name: 'Bell held under {C}',
    kind: 'pad',
    description:
      'A bell tone on {C} held instead of struck, beating low and turning in a dark hall.',
    preset: 'lucid-bell-held-under',
    set: { detune: 6, spread: 0 },
    effects: [
      { deviceId: 'freq-shifter', preset: 'Slow drift', params: { width: 0, fine: 0.7, mix: 0.4 } },
      { deviceId: 'hall-reverb', preset: 'Dark hall', params: { mix: 0.35 } },
    ],
    ...looped(8, 6, 3, [48]),
  },
  {
    n: 33,
    id: 'mineshaft-voices-a',
    name: 'Mineshaft voices {A}',
    kind: 'pad',
    description:
      'Deep voices on a closed oo holding a low {A} and {E}, sampled low, far down a long hall.',
    preset: 'lucid-mineshaft-voices',
    set: { ensemble: 0, vibrato: 0 },
    then: [NARROW, breathe(0.125, 0.5)],
    ...looped(8, 7, 3, [45, 52]),
  },
  {
    n: 34,
    id: 'chapel-celeste-c',
    name: 'Chapel celeste {C}',
    kind: 'pad',
    description:
      'A dark celeste rank on {C} major beating against itself in a turning speaker, in a cathedral.',
    preset: 'lucid-chapel-celeste',
    then: [breathe(0.125, 0.4)],
    ...looped(8, 5, 3, [48, 55, 64]),
  },
  {
    n: 35,
    id: 'foghorn-section-f',
    name: 'Foghorn section {F}',
    kind: 'pad',
    description: 'Low brass on {F} and {C} blown softly, heard across water in a large dark space.',
    preset: 'lucid-foghorn-section',
    then: [NARROW],
    ...looped(8, 7, 3, [41, 48]),
  },
  {
    n: 36,
    id: 'drifting-ensemble-dm',
    name: 'Drifting ensemble {D}m',
    kind: 'pad',
    description:
      'A dark string ensemble on {D} minor, through a slow six-stage phaser into a long plate.',
    preset: 'lucid-dark-drifting-ensemble',
    set: { drift: 0.35 },
    effects: [
      {
        deviceId: 'phaser',
        preset: 'Warm six-stage',
        params: { stereo: 30, rate: 0.125, mix: 0.45 },
      },
      { deviceId: 'plate-reverb', preset: 'Long plate', params: { damping: 0.55, mix: 0.3 } },
    ],
    then: [NARROW, breathe(0.125, 0.4)],
    ...looped(8, 7, 3, [38, 50, 57, 65]),
  },
  {
    n: 37,
    id: 'reed-from-nowhere-c',
    name: 'Reed from nowhere {C}',
    kind: 'pad',
    description:
      'A softly blown {C} and {G} on clarinets, caught and held as a dark bed behind themselves.',
    preset: 'lucid-reed-from-nowhere',
    then: [breathe(0.125, 0.6)],
    ...looped(8, 6, 3, [60, 67]),
  },
  {
    n: 38,
    id: 'wrong-weather-c',
    name: 'Wrong weather {C}',
    kind: 'pad',
    description:
      'A spectral table on {C} and {G}, ring-modulated a little so it curdles, swelling in a cheap hall.',
    preset: 'lucid-wrong-weather',
    then: [NARROW, breathe(0.125, 0.5)],
    ...looped(8, 7, 3, [60, 67]),
  },
  {
    n: 39,
    id: 'steel-in-fog-c',
    name: 'Steel in fog {C}',
    kind: 'pad',
    description:
      'Steel strings on {C}, {G} and {E} that fade in under a slow pedal, their tail swelling after.',
    preset: 'lucid-steel-in-fog',
    ...played(
      12,
      [
        [0, 5, 48],
        [0.3, 4.7, 55],
        [0.7, 4.3, 64],
      ],
      3,
    ),
  },
  {
    n: 40,
    id: 'shed-guitar-swell-am',
    name: 'Shed guitar swell {A}m',
    kind: 'pad',
    description:
      'A dark guitar chord on {A} minor with the pick taken off by a slow swell, in a long plate.',
    preset: 'lucid-shed-guitar-swell',
    then: [NARROW],
    ...played(
      10,
      [
        [0, 6, 45],
        [0, 6, 52],
        [0, 6, 57],
        [0, 6, 60],
        [0, 6, 64],
      ],
      3,
    ),
  },
  {
    n: 41,
    id: 'motor-vibes-asleep-c',
    name: 'Motor vibes, asleep {C}',
    kind: 'pad',
    description:
      'Soft mallets wander up {C} major seventh and back through {A}, over a slow motor in a long hall; it comes round.',
    preset: 'lucid-motor-vibes-asleep',
    then: [NARROW],
    ...cycled(8, [
      [0, 2, 60, 0.7],
      [0.74, 2, 64, 0.6],
      [1.37, 2, 67, 0.6],
      [2.51, 2.5, 71, 0.7],
      [4.29, 2, 69, 0.6],
      [5.18, 2.2, 64, 0.6],
    ]),
  },
  {
    n: 42,
    id: 'sliding-wire-f',
    name: 'Sliding wire {F}',
    kind: 'pad',
    description:
      'Steel notes on {F}, {C} and {G} fading in and sliding a long way into each other, on wowing tape.',
    preset: 'lucid-sliding-wire',
    then: [NARROW],
    ...played(
      12,
      [
        [0, 2.4, 53],
        [1.6, 2.6, 60],
        [3.7, 2.4, 65],
        [5.4, 1.8, 67],
      ],
      3,
    ),
  },

  // Textures: weather, rooms and noise with no pitch to speak of.
  {
    n: 43,
    id: 'whistling-adit',
    name: 'Whistling adit',
    kind: 'texture',
    description:
      'Noise through a resonant band that wanders: a wind whistling one note down a tunnel.',
    preset: 'lucid-adit-wind',
    effects: [
      { deviceId: 'phaser', preset: 'Slow swirl', params: { mix: 0.35 } },
      {
        deviceId: 'ether-reverb',
        preset: 'Cathedral',
        params: { decay: 12, damping: 0.6, mix: 0.25 },
      },
    ],
    then: [CLOSE],
    ...looped(8, 7, 3, [48]),
  },
  {
    n: 44,
    id: 'wind-through-the-hedge',
    name: 'Wind through the hedge',
    kind: 'texture',
    description:
      'Wind pushing through a gap and never settling, through a slow phaser into a dark plate.',
    preset: 'lucid-hedge-gap-wind',
    set: { resonance: 0.3 },
    ...looped(8, 5, 3, [64]),
  },
  {
    n: 45,
    id: 'far-thunder',
    name: 'Far thunder',
    kind: 'texture',
    description: 'Thunder a long way inland, dull and slow to roll, on slow tape in a dark hall.',
    preset: 'lucid-thunder-inland',
    then: [
      {
        deviceId: 'ambient-comp',
        params: { threshold: -50, ratio: 8, attack: 200, release: 2, makeup: 12 },
      },
    ],
    ...looped(16, 1, 3, [36, 43, 48]),
  },
  {
    n: 46,
    id: 'breath-organ-d',
    name: 'Breath organ {D}',
    kind: 'texture',
    description:
      'Low flutes on {D} and {A} blown so softly that the air is most of the sound, in a whispering hall.',
    preset: 'lucid-breath-organ',
    set: { breath: 1, blow: 0.12 },
    ...looped(8, 5, 3, [50, 57, 62]),
  },
  {
    n: 47,
    id: 'air-over-fifths-c',
    name: 'Air over fifths {C}',
    kind: 'texture',
    description:
      'Tuned air on {C} and {G} with barely a tone in it, over a slowed copy a fifth below.',
    preset: 'lucid-air-over-fifths',
    set: { air: 1, partials: 0.25 },
    then: [NARROW],
    ...looped(8, 5, 4, [48]),
  },
  {
    n: 48,
    id: 'cove-at-night',
    name: 'Cove at night',
    kind: 'texture',
    description: 'Slow waves on a shingle cove, dulled on quarter-inch tape, in a long dark plate.',
    instrument: {
      deviceId: 'atmosphere',
      preset: 'Slow shore',
      params: { attack: 0.5, width: 0.6 },
    },
    effects: [
      { deviceId: 'tape', preset: 'Quarter inch', params: { wow: 0.3, hiss: 0.3 } },
      { deviceId: 'plate-reverb', preset: 'Long plate', params: { damping: 0.6, mix: 0.3 } },
    ],
    ...looped(16, 5, 3, [48]),
  },
  {
    n: 49,
    id: 'rain-on-slates',
    name: 'Rain on slates',
    kind: 'texture',
    description:
      'Rain on a slate roof heard from the room under it, through old converters, in a small room.',
    instrument: {
      deviceId: 'atmosphere',
      preset: 'Rain on the window',
      params: { attack: 0.5, width: 0.6, density: 0.7 },
    },
    effects: [
      soften(10),
      { deviceId: 'vintage-digital', preset: 'Glaze', params: { rate: 14000 } },
      { deviceId: 'fdn-reverb', preset: 'Room', params: { mix: 0.3 } },
    ],
    then: [{ deviceId: 'fet-limiter', preset: 'Squash' }],
    ...looped(8, 4, 2, [55]),
  },
  {
    n: 50,
    id: 'grate-fire-late',
    name: 'Grate fire, late',
    kind: 'texture',
    description:
      'A coal fire settling in the grate, recorded on a wavering cassette in a small plate.',
    instrument: { deviceId: 'atmosphere', preset: 'Hearth', params: { attack: 0.5, width: 0.6 } },
    effects: [
      soften(10),
      { deviceId: 'tape', preset: 'Cassette four-track', params: { wow: 0.5 } },
      { deviceId: 'plate-reverb', preset: 'Small plate', params: { mix: 0.3 } },
    ],
    ...looped(8, 3, 2, [50]),
  },
  {
    n: 51,
    id: 'run-out-groove',
    name: 'Run-out groove',
    kind: 'texture',
    description:
      'The crackle of a record left turning after the music, sampled low, in a long dull plate.',
    instrument: { deviceId: 'atmosphere', preset: 'Old record', params: { width: 0.6 } },
    effects: [
      soften(10),
      { deviceId: 'vintage-digital', preset: 'Dusty', params: { jitter: 0.4 } },
      { deviceId: 'plate-reverb', preset: 'Long plate', params: { damping: 0.6, mix: 0.3 } },
    ],
    then: [{ deviceId: 'fet-limiter', preset: 'Squash' }],
    ...looped(8, 2, 2, [60]),
  },
  {
    n: 52,
    id: 'bows-on-air-a',
    name: 'Bows on air {A}',
    kind: 'texture',
    description:
      'Three players on {A} and {E} bowing more air than string, with a dark reverb rising backwards.',
    preset: 'lucid-bows-on-air',
    ...looped(8, 5, 3, [57, 64]),
  },
  {
    n: 53,
    id: 'noise-chord-dark-d',
    name: 'Noise chord, dark {D}',
    kind: 'texture',
    description:
      'Bands of filtered noise on {D} and its mirror images, drifting, on tape in a dark plate.',
    preset: 'lucid-noise-chord-dark',
    then: [NARROW],
    ...looped(8, 5, 3, [50, 57]),
  },
  {
    n: 54,
    id: 'whistling-bands-e',
    name: 'Whistling bands {E}',
    kind: 'texture',
    description:
      'Narrow bands of noise that half whistle a chord around {E} and drift, in a long hall.',
    preset: 'lucid-whistling-bands',
    set: { resonance: 20 },
    then: [NARROW],
    ...looped(8, 5, 3, [64, 67]),
  },
  {
    n: 55,
    id: 'stream-under-mill',
    name: 'Stream under the mill',
    kind: 'texture',
    description: 'A small stream running under a floor, dulled by slow tape, in a dark hall.',
    instrument: {
      deviceId: 'outdoors',
      preset: 'Small stream',
      params: { attack: 0.5, width: 0.7, distance: 0.4 },
    },
    effects: [
      { deviceId: 'tape', preset: 'Quarter inch', params: { speed: 2 } },
      { deviceId: 'fdn-reverb', preset: 'Hall', params: { damping: 0.8, mix: 0.3 } },
    ],
    ...looped(8, 3, 2, [52]),
  },

  // One-shots: one stroke that rings out.
  {
    n: 56,
    id: 'tin-gong-d',
    name: 'Tin gong {D}',
    kind: 'oneshot',
    description:
      'A low inharmonic gong on {D} with a rough edge, struck once and left in a dark well of echoes.',
    preset: 'lucid-tin-gong',
    ...played(12, [[0, 6, 38]], 3),
  },
  {
    n: 57,
    id: 'toy-mallet-g',
    name: 'Wonky toy mallet {G}',
    kind: 'oneshot',
    description:
      'One short mallet stroke on {G}, a little out with itself, with dull repeats in a small room.',
    preset: 'lucid-toy-mallets',
    effects: [
      {
        deviceId: 'analog-delay',
        preset: 'Dark echo',
        params: { time: 330, feedback: 0.5, mix: 0.12 },
      },
      { deviceId: 'ether-reverb', preset: 'Room' },
    ],
    ...played(3, [[0, 0.5, 67]], 1),
  },
  {
    n: 58,
    id: 'lullaby-keys-f',
    name: 'Lullaby chord {F}maj7',
    kind: 'oneshot',
    description:
      'A soft electric piano chord on {F} major seventh, dull and detuned, on cassette in a plate.',
    preset: 'lucid-lullaby-keys',
    then: [NARROW],
    ...played(
      6,
      [
        [0, 3, 53],
        [0.02, 3, 60],
        [0.04, 3, 64],
        [0.06, 3, 69],
      ],
      1.5,
    ),
  },
  {
    n: 59,
    id: 'sampled-comb-a',
    name: 'Sampled comb {A}',
    kind: 'oneshot',
    description:
      'One tooth of a music box comb on a high {A}, through early sampler converters and a dull echo.',
    preset: 'lucid-sampled-comb',
    set: { detune: 1.5 },
    effects: [
      { deviceId: 'vintage-digital', preset: 'Sampler', params: { rate: 11000 } },
      { deviceId: 'analog-delay', preset: 'Dark echo', params: { mix: 0.1 } },
      { deviceId: 'plate-reverb', preset: 'Small plate', params: { mix: 0.3 } },
    ],
    then: [NARROW],
    ...played(3, [[0, 0.8, 81]], 1),
  },
  {
    n: 60,
    id: 'stretched-bowl-f',
    name: 'Stretched bowl {F}',
    kind: 'oneshot',
    description:
      'A singing bowl on {F} with its overtones stretched sharp, softly struck, in a dark hall.',
    preset: 'lucid-stretched-singing-bowl',
    set: { detune: 0.5, spread: 0.2 },
    effects: [{ deviceId: 'hall-reverb', preset: 'Dark hall', params: { mix: 0.4 } }],
    then: [NARROW],
    ...played(12, [[0, 8, 53]], 3),
  },
  // Fifths and octaves only: the fifth harmonic of every string here is a white key.
  {
    n: 61,
    id: 'twelve-strings-f',
    name: 'Twelve strings, once {F}',
    kind: 'oneshot',
    description:
      'A twelve-string strummed once on {F} and {C}, answered by its own notes backwards, in a tank.',
    preset: 'lucid-twelve-strings-reversed',
    then: [{ deviceId: 'fet-limiter', preset: 'Gentle lift' }, NARROW],
    ...played(
      10,
      [
        [0, 3, 41],
        [0, 3, 48],
        [0, 3, 53],
        [0, 3, 60],
        [0, 3, 65],
      ],
      3,
    ),
  },
  {
    n: 62,
    id: 'toy-strum-g',
    name: 'Toy strum, worn {G}',
    kind: 'oneshot',
    description:
      'A quick strum down two octaves of {G} major through eight-bit converters and wavering tape.',
    preset: 'lucid-toy-strum-worn',
    set: { strum: 6 },
    ...played(
      3,
      [
        [0, 1.5, 67],
        [0, 1.5, 71],
        [0, 1.5, 74],
      ],
      1,
    ),
  },
  {
    n: 63,
    id: 'hollow-drum-d',
    name: 'Hollow drum, far {D}',
    kind: 'oneshot',
    description:
      'A tongue drum on {D} under a soft hand, strings ringing after it at the far end of a cathedral.',
    preset: 'lucid-hollow-drum-far',
    effects: [
      {
        deviceId: 'sympathetic',
        preset: 'Minor strings',
        params: { root: 9, width: 0.35, mix: 0.3 },
      },
      { deviceId: 'hall-reverb', preset: 'Cathedral', params: { damping: 2500, mix: 0.5 } },
    ],
    ...played(6, [[0, 2, 50]], 2),
  },
  {
    n: 64,
    id: 'yard-clank-c',
    name: 'Yard clank {C}',
    kind: 'oneshot',
    description:
      'A steel pan on {C} rapped with the knuckles and shifted a little sour, with dull echoes in a small room.',
    preset: 'lucid-yard-clank',
    effects: [
      { deviceId: 'fet-limiter', preset: 'Drive' },
      { deviceId: 'freq-shifter', preset: 'Bell metal', params: { shift: 147, mix: 0.2 } },
      { deviceId: 'analog-delay', preset: 'Dark echo', params: { mix: 0.25 } },
      { deviceId: 'fdn-reverb', preset: 'Room' },
    ],
    ...played(4, [[0, 0.6, 60]], 1),
  },
  {
    n: 65,
    id: 'bent-silk-string-b',
    name: 'Bent silk string {B}',
    kind: 'oneshot',
    description:
      'A koto string on {B} pressed so the note bends up to {C} after the pluck, on tape that wows.',
    preset: 'lucid-bent-silk-string',
    set: { bend: 100 },
    ...played(5, [[0, 2.5, 59]], 1),
  },
  {
    n: 66,
    id: 'dull-tines-dm',
    name: 'Dull tines {D}m9',
    kind: 'oneshot',
    description:
      'An electric piano chord on {D} minor ninth with no bell in it, in a slow chorus on cassette.',
    preset: 'lucid-dull-tines',
    ...played(
      6,
      [
        [0, 3.5, 50],
        [0.008, 3.5, 57],
        [0.016, 3.5, 60],
        [0.024, 3.5, 65],
        [0.032, 3.5, 76],
      ],
      1.5,
    ),
  },
  {
    n: 67,
    id: 'sampled-tines-am',
    name: 'Sampled tines {A}m',
    kind: 'oneshot',
    description:
      'Bell-like tines on {A} minor with a dark pad of the same chord growing behind them.',
    preset: 'lucid-sampled-tines',
    ...played(
      8,
      [
        [0, 3, 57],
        [0.02, 3, 64],
        [0.04, 3, 72],
      ],
      3,
    ),
  },
  {
    n: 68,
    id: 'dull-pluck-g',
    name: 'Dull pluck {G}',
    kind: 'oneshot',
    description: 'One soft dull pluck on a low {G}, with faint dark repeats in a dull amp spring.',
    preset: 'lucid-dull-pluck-pattern',
    set: { sustain: 4 },
    effects: [
      {
        deviceId: 'analog-delay',
        preset: 'Dark echo',
        params: { time: 375, feedback: 0.4, mix: 0.12 },
      },
      { deviceId: 'spring-reverb', preset: 'Dark amp spring', params: { width: 0.6, mix: 0.35 } },
    ],
    ...played(3, [[0, 1.5, 43]], 1),
  },
  {
    n: 69,
    id: 'upright-chord-am',
    name: 'Upright next door {A}m',
    kind: 'oneshot',
    description:
      'A felted, out-of-tune upright playing {A} minor, heard through a wall on cassette.',
    preset: 'lucid-upright-down-the-hall',
    set: { outputDb: -6 },
    then: [NARROW],
    ...played(
      6,
      [
        [0, 3.5, 45],
        [0.02, 3.5, 52],
        [0.04, 3.5, 60],
        [0.06, 3.5, 64],
      ],
      1.5,
    ),
  },
  {
    n: 70,
    id: 'worn-brass-stab-f',
    name: 'Worn brass stab {F}',
    kind: 'oneshot',
    description:
      'A synth brass chord on {F} major that speaks at once and lets go, detuned, on tape.',
    preset: 'lucid-worn-brass-keys',
    set: { swell: 0, detune: 8 },
    ...played(
      4,
      [
        [0, 1.2, 53],
        [0, 1.2, 57],
        [0, 1.2, 60],
        [0, 1.2, 65],
      ],
      1,
    ),
  },
  {
    n: 71,
    id: 'half-speed-piano-c',
    name: 'Half speed piano {C}',
    kind: 'oneshot',
    description:
      'One felt piano {C} with a half-speed copy dragging an octave under it, in a long dull hall.',
    preset: 'lucid-half-speed-piano',
    effects: [
      { deviceId: 'half-speed', preset: 'Long drag', params: { highCut: 5000, mix: 0.4 } },
      { deviceId: 'fdn-reverb', preset: 'Hall', params: { decay: 10, damping: 0.6 } },
    ],
    ...played(8, [[0, 2, 60]], 2.5),
  },
  {
    n: 72,
    id: 'thumb-piano-g',
    name: 'Thumb piano, slow {G}',
    kind: 'oneshot',
    description:
      'One dull thumb piano note on {G} with its own half-speed copy an octave below, on cassette.',
    preset: 'lucid-thumb-piano-slowed',
    ...played(5, [[0, 1, 67]], 2),
  },
  {
    n: 73,
    id: 'slowed-glock-a',
    name: 'Slowed glock {A}',
    kind: 'oneshot',
    description:
      'One glockenspiel bar on {A}, mostly heard at half speed an octave down, on tape that wows.',
    preset: 'lucid-slowed-glockenspiel',
    ...played(6, [[0, 1, 81]], 1.5),
  },
  {
    n: 74,
    id: 'engine-house-gong-e',
    name: 'Engine house gong {E}',
    kind: 'oneshot',
    description:
      'A gong on a low {E} struck with a medium beater, its modes beating, on slow tape in a dark hall.',
    preset: 'lucid-engine-house-gong',
    set: { spread: 0.2 },
    effects: [
      { deviceId: 'tape', preset: 'Quarter inch', params: { speed: 2, wow: 0.35 } },
      { deviceId: 'hall-reverb', preset: 'Dark hall', params: { mix: 0.4 } },
    ],
    then: [NARROW],
    ...played(12, [[0, 8, 40]], 3),
  },
  // The key played is an A: the first string is the fourth under it, an E.
  {
    n: 75,
    id: 'buzz-and-comb-pluck',
    name: 'Buzz and comb pluck',
    kind: 'oneshot',
    description:
      'One pluck of the first string of a buzzing drone lute, an {E}, swept by a slow flanger in a cavern.',
    preset: 'lucid-buzz-and-comb',
    set: { speed: 12 },
    ...played(7, [[0, 2.8, 57]], 2),
  },

  // Phrases: a few notes in free time; those that say so come round.
  {
    n: 76,
    id: 'sine-whistle-tune-am',
    name: 'Sine whistle tune {A}m',
    kind: 'melodic',
    description:
      'A sine whistles a slow tune in {A} minor, sliding from note to note over dark repeats; it comes round.',
    preset: 'lucid-sine-whistle-lead',
    then: [NARROW],
    ...cycled(8, [
      [0, 1.45, 69],
      [1.37, 1, 72],
      [2.31, 1.9, 76],
      [4.12, 0.93, 74],
      [4.97, 2.2, 71],
    ]),
  },
  {
    n: 77,
    id: 'warble-keys-round-c',
    name: 'Warble keys round {C}',
    kind: 'melodic',
    description:
      'Six fluttering glass notes falling through {C} major, through a vibrato echo; it comes round.',
    preset: 'lucid-warble-keys',
    ...cycled(8, [
      [0, 0.6, 72],
      [0.71, 0.5, 67],
      [1.29, 0.9, 64],
      [2.83, 0.6, 69],
      [3.47, 0.5, 65],
      [4.21, 1.4, 60],
    ]),
  },
  {
    n: 78,
    id: 'wonky-box-lullaby-g',
    name: 'Wonky box lullaby {G}',
    kind: 'melodic',
    description:
      'A music box out with itself picks a lullaby down from a high {G}; it comes round.',
    preset: 'lucid-wonky-music-box',
    ...cycled(8, [
      [0, 0.8, 79],
      [0.62, 0.8, 76],
      [1.31, 1, 72],
      [2.54, 0.8, 74],
      [3.13, 0.8, 76],
      [4.42, 1.6, 67],
    ]),
  },
  {
    n: 79,
    id: 'toy-mallets-tune-d',
    name: 'Toy mallets tune {D}',
    kind: 'melodic',
    description:
      'Short mallets climb a {D} minor chord, step back down and stop, with dull repeats.',
    preset: 'lucid-toy-mallets',
    ...played(
      8,
      [
        [0, 0.4, 62],
        [0.53, 0.4, 65],
        [1.02, 0.4, 69],
        [2.07, 0.6, 67],
        [2.71, 0.4, 64],
        [3.9, 1, 62],
      ],
      1.5,
    ),
  },
  {
    n: 80,
    id: 'lullaby-keys-round-f',
    name: 'Lullaby keys round {F}',
    kind: 'melodic',
    description: 'A soft electric piano rocks between {C} and {A} over a low {F}; it comes round.',
    preset: 'lucid-lullaby-keys',
    then: [NARROW],
    ...cycled(8, [
      [0, 2.5, 41, 0.6],
      [0.05, 1.2, 60, 0.7],
      [1.12, 1, 57, 0.6],
      [2.03, 1.6, 65, 0.7],
      [3.66, 1, 64, 0.6],
      [4.48, 0.9, 60, 0.6],
      [5.61, 1.8, 57, 0.65],
    ]),
  },
  {
    n: 81,
    id: 'sampled-comb-round-am',
    name: 'Sampled comb round {A}m',
    kind: 'melodic',
    description: 'A music box comb opens an {A} minor arpeggio and folds it back; it comes round.',
    preset: 'lucid-sampled-comb',
    ...cycled(8, [
      [0, 0.5, 69],
      [0.44, 0.5, 72],
      [0.97, 0.5, 76],
      [1.78, 0.5, 81],
      [3.07, 0.5, 79],
      [3.61, 0.5, 76],
      [4.52, 1, 72],
    ]),
  },
  {
    n: 82,
    id: 'night-radio-voice-e',
    name: 'Night radio voice {E}',
    kind: 'melodic',
    description:
      'One voice a shade sharp on a sideband radio sings from {E} up to {A} and back; it comes round.',
    preset: 'lucid-night-radio-voice',
    set: { attack: 0.05, vibrato: 8 },
    effects: [
      {
        deviceId: 'radio',
        preset: 'Sideband voices',
        params: { tuning: 0.012, static: 0.12, drift: 0, fading: 0, mix: 0.7 },
      },
      { deviceId: 'tape-echo', preset: 'Worn tape', params: { mix: 0.25 } },
      { deviceId: 'fdn-reverb', preset: 'Hall', params: { mix: 0.35 } },
    ],
    ...cycled(8, [
      [0.4, 1.2, 64],
      [2.23, 0.8, 67],
      [3.47, 1.6, 69],
      [6.01, 1.2, 67],
    ]),
  },
  {
    n: 83,
    id: 'worn-brass-broken-dm',
    name: 'Worn brass, broken {D}m',
    kind: 'melodic',
    description:
      'Synth brass breaks a {D} minor chord and then an {F}, on tape in a small plate; it comes round.',
    preset: 'lucid-worn-brass-keys',
    ...cycled(8, [
      [0, 1, 50],
      [0.47, 0.9, 57],
      [1.02, 1.2, 65],
      [2.38, 1, 53],
      [2.91, 0.9, 60],
      [3.49, 1.4, 69],
      [5.13, 1.5, 64],
    ]),
    loopFold: 'power',
  },
  {
    n: 84,
    id: 'lone-horn-line-g',
    name: 'Lone horn line {G}',
    kind: 'melodic',
    description:
      'A soft synth horn climbs slowly from {G} to {D}, with tape echoes in a long spring.',
    preset: 'lucid-lone-horn-line',
    set: { attack: 0.02, contour: 0.8, swell: 0.2, release: 0.8 },
    ...played(
      10,
      [
        [0, 1.2, 55],
        [1.93, 0.8, 57],
        [3.18, 1.5, 59],
        [5.4, 1.8, 62],
      ],
      2,
    ),
  },
  {
    n: 85,
    id: 'nylon-question-em',
    name: 'Nylon question {E}m',
    kind: 'melodic',
    description:
      'A nylon guitar asks with three notes up from {E} and answers back down, on cassette.',
    preset: 'lucid-nylon-on-cassette',
    ...played(
      8,
      [
        [0, 4, 52, 0.5],
        [0.04, 1.1, 64, 0.6],
        [0.58, 1.1, 67, 0.6],
        [1.24, 2, 71, 0.65],
        [3.31, 1, 69, 0.6],
        [3.87, 1.1, 67, 0.55],
        [4.62, 2.6, 64, 0.6],
      ],
      1,
    ),
  },
  {
    n: 86,
    id: 'upright-phrase-c',
    name: 'Upright down the hall {C}',
    kind: 'melodic',
    description:
      'A felted upright through a wall: a rise through {C} major and a step back down; it comes round.',
    preset: 'lucid-upright-down-the-hall',
    set: { outputDb: -6 },
    then: [NARROW],
    ...cycled(8, [
      [0, 0.8, 60],
      [0.93, 0.6, 64],
      [1.62, 1.2, 67],
      [3.41, 0.6, 65],
      [4.23, 0.6, 64],
      [5.17, 1.5, 62],
    ]),
  },
  {
    n: 87,
    id: 'sampled-pipes-air-g',
    name: 'Sampled pipes air {G}',
    kind: 'melodic',
    description:
      'Pan pipes scoop up to each note of a slow air on {G}, as an early sampler would play them, with dull repeats.',
    preset: 'lucid-sampled-pipes',
    then: [NARROW],
    ...played(
      8,
      [
        [0, 0.9, 67],
        [1.04, 0.5, 71],
        [1.57, 1.4, 74],
        [3.21, 0.6, 72],
        [3.88, 0.6, 71],
        [4.59, 1.4, 69],
      ],
      2,
    ),
  },
  {
    n: 88,
    id: 'bent-silk-phrase-e',
    name: 'Bent silk phrase {E}',
    kind: 'melodic',
    description:
      'A koto plays {E}, {B}, {E} and a low {E}, each bent up a semitone after the pluck, to {F} and {C}.',
    preset: 'lucid-bent-silk-string',
    set: { bend: 100 },
    ...played(
      8,
      [
        [0, 1.2, 64],
        [1.33, 1, 59],
        [2.41, 1.6, 64],
        [4.3, 2, 52],
      ],
      1.5,
    ),
  },
  {
    n: 89,
    id: 'distant-trumpet-call-g',
    name: 'Distant muted trumpet {G}',
    kind: 'melodic',
    description:
      'A muted trumpet a long way off calls twice around {G}, repeated by three tape heads.',
    preset: 'lucid-distant-muted-trumpet',
    set: { attack: 0.05 },
    ...played(
      10,
      [
        [0, 0.5, 62, 0.7],
        [0.9, 0.5, 67, 0.8],
        [1.9, 1.6, 71, 0.9],
        [4.4, 0.5, 69, 1],
        [5.2, 2, 67, 1],
      ],
      2.5,
    ),
  },
  {
    n: 90,
    id: 'fairground-far-off-c',
    name: 'Fairground far off {C}',
    kind: 'melodic',
    description:
      'Flute pipes with a heavy tremulant play a tune down to {C} on tape that wows; it comes round.',
    preset: 'lucid-fairground-far-off',
    set: { release: 0.3, attack: 0.02 },
    ...cycled(8, [
      [0, 0.5, 79],
      [0.93, 0.3, 76],
      [1.51, 0.6, 77],
      [2.74, 0.3, 74],
      [3.33, 0.6, 76],
      [4.61, 1.2, 72],
    ]),
    loopFold: 'power',
  },
  {
    n: 91,
    id: 'lost-reel-flutes-dm',
    name: 'Lost reel flutes {D}m',
    kind: 'melodic',
    description:
      'Flutes from the oldest tape at half speed play a slow rise and fall in {D} minor.',
    preset: 'lucid-lost-reel-flutes',
    set: { attack: 0.01, release: 0.3 },
    ...played(
      10,
      [
        [0, 0.9, 62],
        [1.52, 0.5, 65],
        [2.44, 1.4, 69],
        [4.8, 0.6, 67],
        [5.9, 1.8, 62],
      ],
      2,
    ),
  },
  {
    n: 92,
    id: 'sampled-tines-phrase-g',
    name: 'Sampled tines phrase {G}',
    kind: 'melodic',
    description:
      'Bell-like tines rise from {G} to {B}, step down and settle on {A}, a dark pad growing in behind them.',
    preset: 'lucid-sampled-tines',
    ...played(
      12,
      [
        [0, 1.8, 55, 0.8],
        [0.66, 1.5, 62, 0.8],
        [1.49, 1.4, 71, 0.9],
        [2.93, 0.8, 67, 0.8],
        [3.82, 2.5, 69, 0.9],
      ],
      3,
    ),
  },
  {
    n: 93,
    id: 'dripping-on-tin-c',
    name: 'Dripping on tin {C}',
    kind: 'melodic',
    description:
      'Five drips on tin at uneven times, their echoes jumping by fifths and fourths; it comes round.',
    preset: 'lucid-dripping-on-tin',
    then: [NARROW],
    ...cycled(8, [
      [0, 0.2, 72],
      [1.13, 0.2, 79],
      [1.72, 0.2, 72],
      [3.44, 0.2, 84],
      [5.21, 0.2, 77],
    ]),
  },
  {
    n: 94,
    id: 'slack-string-phrase-e',
    name: 'Slack string phrase {E}',
    kind: 'melodic',
    description:
      'One string struck with felt on {E}, {B} and {A}, wavering, others ringing behind it.',
    preset: 'lucid-one-slack-string',
    ...played(
      10,
      [
        [0, 2.5, 52],
        [2.71, 1.8, 59],
        [4.6, 3, 57],
      ],
      2.5,
    ),
  },
  {
    n: 95,
    id: 'hollow-drum-round-d',
    name: 'Hollow drum round {D}',
    kind: 'melodic',
    description:
      'Soft hands circle a tongue drum in {D} minor, far off in a cathedral; it comes round.',
    preset: 'lucid-hollow-drum-far',
    effects: [
      {
        deviceId: 'sympathetic',
        preset: 'Minor strings',
        params: { root: 9, width: 0.35, mix: 0.3 },
      },
      { deviceId: 'hall-reverb', preset: 'Cathedral', params: { damping: 2500, mix: 0.5 } },
    ],
    ...cycled(
      8,
      [
        [0, 1.2, 50, 0.75],
        [0.71, 1, 57, 0.5],
        [1.83, 1.2, 62, 0.6],
        [3.02, 1, 60, 0.5],
        [4.36, 1.4, 53, 0.65],
        [5.18, 1, 57, 0.5],
      ],
      { passes: 2 },
    ),
  },
  {
    n: 96,
    id: 'lane-chimes-far-b',
    name: 'Lane chimes, far {B}',
    kind: 'melodic',
    description:
      'Four thin chimes up from a high {B}, scattered by a grain delay, far off down a long hall.',
    preset: 'lucid-lane-chimes',
    then: [CLOSE],
    ...played(
      8,
      [
        [0, 0.5, 83],
        [0.37, 0.5, 88],
        [1.42, 0.5, 86],
        [2.9, 0.8, 91],
      ],
      3,
    ),
  },
  {
    n: 97,
    id: 'yard-clank-pattern-e',
    name: 'Yard clank pattern {E}',
    kind: 'melodic',
    description:
      'Knuckles on a steel pan shifted a little sour: six raps around {E} at uneven times, with dull echoes.',
    preset: 'lucid-yard-clank',
    effects: [
      { deviceId: 'freq-shifter', preset: 'Bell metal', params: { shift: 147, mix: 0.2 } },
      { deviceId: 'analog-delay', preset: 'Dark echo', params: { mix: 0.3 } },
      { deviceId: 'fdn-reverb', preset: 'Room', params: { mix: 0.4 } },
    ],
    ...played(
      7,
      [
        [0, 0.5, 64],
        [0.71, 0.4, 67],
        [1.13, 0.5, 69],
        [2.42, 0.6, 64],
        [3.3, 0.4, 62],
        [3.87, 1, 64],
      ],
      2,
    ),
  },
  {
    n: 98,
    id: 'toy-strums-worn-c',
    name: 'Toy strums, worn {C}',
    kind: 'melodic',
    description:
      'Three quick strums down {C} major, {A} minor and {F} major through eight-bit converters and wavering tape.',
    preset: 'lucid-toy-strum-worn',
    set: { strum: 6 },
    ...played(
      7,
      [
        [0, 1, 60],
        [0, 1, 64],
        [0, 1, 67],
        [1.31, 1, 57],
        [1.31, 1, 60],
        [1.31, 1, 64],
        [2.87, 1.6, 53],
        [2.87, 1.6, 57],
        [2.87, 1.6, 60],
      ],
      2,
    ),
  },
  {
    n: 99,
    id: 'twelve-strings-up-c',
    name: 'Twelve strings up {C}',
    kind: 'melodic',
    description:
      'A twelve-string picked slowly up {C}, {G}, {C}, {F} and {G}, each note answered backwards, in a tank.',
    preset: 'lucid-twelve-strings-reversed',
    then: [NARROW],
    ...played(
      10,
      [
        [0, 2.5, 48],
        [0.62, 2.5, 55],
        [1.21, 2.5, 60],
        [2.34, 2.5, 65],
        [3.1, 3, 67],
      ],
      3,
    ),
  },
  {
    n: 100,
    id: 'dull-tines-walk-f',
    name: 'Dull tines walk {F}',
    kind: 'melodic',
    description:
      'A dull electric piano walks up from {F} to {C} and back to {G}, in a slow chorus on cassette.',
    preset: 'lucid-dull-tines',
    ...played(
      8,
      [
        [0, 1, 65, 1],
        [0.87, 0.8, 69, 1],
        [1.71, 1.5, 72, 1],
        [3.42, 1, 71, 1],
        [4.33, 2, 67, 1],
      ],
      2,
    ),
  },
])
