// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Rotary, shared with
// src/dsp/devices/rotary.gen.ts:
//    0  speed: 0 Slow, 1 Fast, 2 Brake, default 0
//    1  hornDepth: 0..1, default 0.6
//    2  drumDepth: 0..1, default 0.5
//    3  acceleration: 0.25..4 x, default 1
//    4  drive: 0..1, default 0.25
//    5  balance: 0..1, default 0.5
//    6  distance: 0..1, default 0.3
//    7  spread: 0..1, default 0.7
//    8  mix: 0..1, default 1

#pragma once

namespace livemix {
namespace rotary {

enum Param : int {
  kSpeed = 0,
  kHornDepth = 1,
  kDrumDepth = 2,
  kAcceleration = 3,
  kDrive = 4,
  kBalance = 5,
  kDistance = 6,
  kSpread = 7,
  kMix = 8,
  kNumParams = 9,
};

inline constexpr float kParamMin[kNumParams] = {0.0f, 0.0f, 0.0f, 0.25f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
inline constexpr float kParamMax[kNumParams] = {2.0f, 1.0f, 1.0f, 4.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f};
inline constexpr float kParamDefault[kNumParams] = {0.0f, 0.6f, 0.5f, 1.0f, 0.25f, 0.5f, 0.3f, 0.7f, 1.0f};

}  // namespace rotary
}  // namespace livemix
