// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Sub Bass, shared with
// src/dsp/devices/sub-bass.gen.ts:
//    0  shape: 0..1, default 0.15
//    1  harmonics: 0..1, default 0.2
//    2  drop: 0..36 st, default 7
//    3  fall: 5..800 ms, default 40
//    4  attack: 0.001..3 s, default 0.004
//    5  decay: 0.05..20 s, default 20
//    6  release: 0.02..8 s, default 0.4
//    7  drive: 0..1, default 0.15
//    8  glide: 0..2 s, default 0.06
//    9  volume: -48..6 dB, default -9

#pragma once

namespace livemix {
namespace sub_bass {

enum Param : int {
  kShape = 0,
  kHarmonics = 1,
  kDrop = 2,
  kFall = 3,
  kAttack = 4,
  kDecay = 5,
  kRelease = 6,
  kDrive = 7,
  kGlide = 8,
  kVolume = 9,
  kNumParams = 10,
};

inline constexpr float kParamMin[kNumParams] = {0.0f, 0.0f, 0.0f, 5.0f, 0.001f, 0.05f, 0.02f, 0.0f, 0.0f, -48.0f};
inline constexpr float kParamMax[kNumParams] = {1.0f, 1.0f, 36.0f, 800.0f, 3.0f, 20.0f, 8.0f, 1.0f, 2.0f, 6.0f};
inline constexpr float kParamDefault[kNumParams] = {0.15f, 0.2f, 7.0f, 40.0f, 0.004f, 20.0f, 0.4f, 0.15f, 0.06f, -9.0f};

}  // namespace sub_bass
}  // namespace livemix
