// Design tokens of the kit: every colour, size and font a component reads is
// a `--lm-*` CSS variable, so hosts theme by setting variables (on `:root`,
// on a wrapper, or inline through `themeStyle`) and never by overriding
// component rules. `styles.css` ships the same defaults for consumers that
// import the stylesheet; the presets here serve consumers that do not.

import { type CSSProperties } from 'react'

/** Every CSS variable the components read (without the `--lm-` prefix). */
export const LM_TOKENS = [
  // Colour
  'bg',
  'panel',
  'raised',
  'sunken',
  'border',
  'hairline',
  'text',
  'muted',
  'dim',
  'accent',
  'accent-soft',
  'control-value',
  'danger',
  'solo',
  'mute',
  'meter',
  'meter-hot',
  'meter-rms',
  'meter-lufs',
  'meter-track',
  'meter-border',
  'playhead',
  'clip',
  'clip-border',
  'clip-active',
  'focus',
  // Paint field: grid lines, the automation line, and the brush palette
  // (`brush-N` paints a stroke, `brush-ink-N` draws detail and text on it).
  'grid-line',
  'grid-line-strong',
  'rule',
  'automation',
  'brush-1',
  'brush-2',
  'brush-3',
  'brush-4',
  'brush-5',
  'brush-6',
  'brush-ink-1',
  'brush-ink-2',
  'brush-ink-3',
  'brush-ink-4',
  'brush-ink-5',
  'brush-ink-6',
  // Type
  'font',
  'font-mono',
  'font-size',
  'label-size',
  // Geometry
  'radius',
  'space-1',
  'space-2',
  'space-3',
  'knob-size',
  'fader-width',
  'fader-height',
  'meter-width',
  'strip-width',
  'stroke',
  'lane-height',
  'row',
  'col',
  'transition',
] as const

/** How many brush colours a theme carries (`brush-1` … `brush-6`). */
export const BRUSH_COUNT = 6

export type LiveMixToken = (typeof LM_TOKENS)[number]

/** A full or partial token set, values as CSS text. */
export type LiveMixTheme = Partial<Record<LiveMixToken, string>>

/** Tokens shared by every preset: type and geometry. */
const geometry: LiveMixTheme = {
  font: "ui-sans-serif, system-ui, -apple-system, 'Helvetica Neue', Arial, sans-serif",
  'font-mono': "ui-monospace, 'SF Mono', Menlo, Consolas, monospace",
  'font-size': '11px',
  'label-size': '9px',
  radius: '1px',
  'space-1': '4px',
  'space-2': '8px',
  'space-3': '12px',
  'knob-size': '44px',
  'fader-width': '20px',
  'fader-height': '120px',
  'meter-width': '6px',
  'strip-width': '76px',
  stroke: '2px',
  'lane-height': '44px',
  row: '20px',
  col: '40px',
  transition: '80ms',
}

/**
 * Geometry of the grid themes (`graphite`, `paper`, `water`, `dusk`, `night`,
 * `sand`, `groovebox`, `chalk`, `mist`): everything sits on a 40 × 20 px module, corners are square, a knob fills one column, and the
 * type is a regular-weight geometric sans (Jost first, because Futura's
 * regular face on macOS is Medium and reads bold at 11 px).
 */
const gridGeometry: LiveMixTheme = {
  ...geometry,
  font: "Jost, Futura, 'Futura PT', 'Century Gothic', ui-sans-serif, system-ui, sans-serif",
  'font-mono': "'JetBrains Mono', ui-monospace, 'SF Mono', Menlo, Consolas, monospace",
  radius: '0px',
  'knob-size': '28px',
  'fader-width': '12px',
  'fader-height': '40px',
  stroke: '1.5px',
  'lane-height': '40px',
}

/**
 * The default theme: JAXA-Zen — Paper White surfaces, Ceramic Grey panels,
 * Obsidian ink, Vermillion for accents and the playhead.
 */
export const jaxaZenLight: Required<LiveMixTheme> = {
  ...(geometry as Required<LiveMixTheme>),
  bg: '#FDFDFB',
  panel: '#F4F4F0',
  raised: '#FFFFFF',
  sunken: '#E9E9E4',
  border: '#D6D6D0',
  hairline: '#C4C4BE',
  text: '#1A1A1A',
  muted: '#6B6B66',
  dim: '#A3A39D',
  accent: '#E63946',
  'accent-soft': 'rgba(230, 57, 70, 0.18)',
  'control-value': '#1A1A1A',
  danger: '#E63946',
  solo: '#D9A400',
  mute: '#1A1A1A',
  meter: '#1A1A1A',
  'meter-hot': '#E63946',
  'meter-rms': '#6B6B66',
  'meter-lufs': '#3D5A80',
  'meter-track': '#E9E9E4',
  'meter-border': 'transparent',
  playhead: '#E63946',
  clip: '#FFFFFF',
  'clip-border': '#1A1A1A',
  'clip-active': 'rgba(230, 57, 70, 0.18)',
  focus: '#E63946',
  'grid-line': '#ECECE7',
  'grid-line-strong': '#D6D6D0',
  rule: '#6B6B66',
  automation: '#A8501C',
  'brush-1': '#7BBAB8',
  'brush-2': '#5B9BB0',
  'brush-3': '#ADC088',
  'brush-4': '#79A570',
  'brush-5': '#CDD77F',
  'brush-6': '#B4C0BA',
  'brush-ink-1': '#2A6664',
  'brush-ink-2': '#1F5568',
  'brush-ink-3': '#566C30',
  'brush-ink-4': '#335A2C',
  'brush-ink-5': '#6F7B24',
  'brush-ink-6': '#55625C',
}

/** The same palette on Obsidian, for `data-lm-theme="dark"`. */
export const jaxaZenDark: Required<LiveMixTheme> = {
  ...jaxaZenLight,
  bg: '#141414',
  panel: '#1A1A1A',
  raised: '#242424',
  sunken: '#0E0E0E',
  border: '#2E2E2E',
  hairline: '#3A3A3A',
  text: '#FDFDFB',
  muted: '#9A9A94',
  dim: '#5E5E5A',
  'control-value': '#F4F4F0',
  mute: '#FDFDFB',
  meter: '#F4F4F0',
  'meter-rms': '#9A9A94',
  'meter-lufs': '#98C1D9',
  'meter-track': '#0E0E0E',
  clip: '#242424',
  'clip-border': '#F4F4F0',
  'grid-line': '#1C1C1C',
  'grid-line-strong': '#2E2E2E',
  rule: '#000000',
  automation: '#F2B872',
  'brush-1': '#5FB3A6',
  'brush-2': '#5A9AC0',
  'brush-3': '#A9B060',
  'brush-4': '#6FA070',
  'brush-5': '#D0B860',
  'brush-6': '#8F9994',
  'brush-ink-1': '#B4ECE2',
  'brush-ink-2': '#ADD5EE',
  'brush-ink-3': '#E2E8A8',
  'brush-ink-4': '#B3DCB4',
  'brush-ink-5': '#F2E0A2',
  'brush-ink-6': '#CFD7D3',
}

/** ambient-live's water/moss/sage `al-*` palette mapped onto the kit's tokens. */
export const ambientWater: Required<LiveMixTheme> = {
  ...jaxaZenDark,
  bg: '#0e1c1a',
  panel: '#173028',
  raised: '#214038',
  sunken: '#0b1614',
  border: '#071210',
  hairline: '#3a534c',
  text: '#d7e4df',
  muted: '#8eaaa1',
  dim: '#5d756d',
  accent: '#5fafa0',
  'accent-soft': '#5fafa045',
  'control-value': '#dceae4',
  danger: '#d27a7a',
  solo: '#d9c36a',
  mute: '#d7e4df',
  meter: '#5fafa0',
  'meter-hot': '#d27a7a',
  'meter-rms': '#8eaaa1',
  'meter-lufs': '#7aa6c2',
  'meter-track': '#0b1614',
  playhead: '#5fafa0',
  clip: '#214038',
  'clip-border': '#5fafa0',
  'clip-active': '#5fafa045',
  focus: '#5fafa0',
  'grid-line': '#11221f',
  'grid-line-strong': '#1f3a34',
  rule: '#050d0c',
  automation: '#f2c27a',
  'brush-1': '#6fb3b0',
  'brush-2': '#5a93ad',
  'brush-3': '#a5b98a',
  'brush-4': '#7fa37a',
  'brush-5': '#c4cf86',
  'brush-6': '#8aa39c',
  'brush-ink-1': '#bde6e2',
  'brush-ink-2': '#aed3e6',
  'brush-ink-3': '#dbe7c6',
  'brush-ink-4': '#bcdab6',
  'brush-ink-5': '#e8eebe',
  'brush-ink-6': '#c9d9d3',
}

/**
 * Graphite: the dark grid theme. Neutral green-grey surfaces, a mint accent,
 * and brush colours bright enough to read as paint on the dark field.
 */
export const graphite: Required<LiveMixTheme> = {
  ...jaxaZenDark,
  ...(gridGeometry as Required<LiveMixTheme>),
  bg: '#232826',
  panel: '#2a302d',
  raised: '#3a413d',
  sunken: '#1e2220',
  border: '#141816',
  hairline: '#4a524e',
  text: '#e2e7e4',
  muted: '#a2aca7',
  dim: '#7d8782',
  accent: '#7fd0bd',
  'accent-soft': '#7fd0bd33',
  'control-value': '#f0f4f2',
  danger: '#e07a6a',
  solo: '#e0c05a',
  mute: '#e2e7e4',
  meter: '#7fd0bd',
  'meter-hot': '#e07a6a',
  'meter-rms': '#a2aca7',
  'meter-lufs': '#8fb3cf',
  'meter-track': '#161a18',
  'meter-border': 'transparent',
  playhead: '#f0f4f2',
  clip: '#3a413d',
  'clip-border': '#7fd0bd',
  'clip-active': '#7fd0bd33',
  focus: '#7fd0bd',
  'grid-line': '#272d2a',
  'grid-line-strong': '#3a423e',
  rule: '#0f1211',
  automation: '#f2b872',
  'brush-1': '#5fb3a6',
  'brush-2': '#5a9ac0',
  'brush-3': '#a9b060',
  'brush-4': '#6fa070',
  'brush-5': '#d0b860',
  'brush-6': '#8f9994',
  'brush-ink-1': '#b4ece2',
  'brush-ink-2': '#add5ee',
  'brush-ink-3': '#e2e8a8',
  'brush-ink-4': '#b3dcb4',
  'brush-ink-5': '#f2e0a2',
  'brush-ink-6': '#cfd7d3',
}

/** Paper: the light grid theme. Off-white paper, ink rules, water-to-grass paint. */
export const paper: Required<LiveMixTheme> = {
  ...jaxaZenLight,
  ...(gridGeometry as Required<LiveMixTheme>),
  bg: '#f4f5f0',
  panel: '#f4f5f0',
  raised: '#fcfcfa',
  sunken: '#fbfbf8',
  border: '#c4ccbf',
  hairline: '#b9c2b3',
  text: '#1b2622',
  muted: '#55645c',
  dim: '#66736b',
  accent: '#2e6f63',
  'accent-soft': '#2e6f6326',
  'control-value': '#1b2622',
  danger: '#b04a3c',
  solo: '#d9b13a',
  mute: '#1b2622',
  meter: '#2e6f63',
  'meter-hot': '#b04a3c',
  'meter-rms': '#8fa89c',
  'meter-lufs': '#4f7390',
  'meter-track': '#e3e7de',
  'meter-border': 'transparent',
  playhead: '#1b2622',
  clip: '#fcfcfa',
  'clip-border': '#1b2622',
  'clip-active': '#2e6f6326',
  focus: '#2e6f63',
  'grid-line': '#e6e9e0',
  'grid-line-strong': '#c9d0c4',
  rule: '#55645c',
  automation: '#a8501c',
  'brush-1': '#7bbab8',
  'brush-2': '#5b9bb0',
  'brush-3': '#adc088',
  'brush-4': '#79a570',
  'brush-5': '#cdd77f',
  'brush-6': '#b4c0ba',
  'brush-ink-1': '#2a6664',
  'brush-ink-2': '#1f5568',
  'brush-ink-3': '#566c30',
  'brush-ink-4': '#335a2c',
  'brush-ink-5': '#6f7b24',
  'brush-ink-6': '#55625c',
}

/** Water: `ambientWater`'s deep water/moss palette on the grid geometry. */
export const water: Required<LiveMixTheme> = {
  ...ambientWater,
  ...(gridGeometry as Required<LiveMixTheme>),
  panel: '#132622',
  dim: '#6f8a81',
}

/**
 * Dusk: an ambient dark grid theme. Indigo-grey surfaces, a soft peach accent,
 * and paint in the colours of the hour after sunset, deep enough to carry pale ink.
 */
export const dusk: Required<LiveMixTheme> = {
  ...jaxaZenDark,
  ...(gridGeometry as Required<LiveMixTheme>),
  bg: '#24222e',
  panel: '#2b2937',
  raised: '#3a3848',
  sunken: '#1e1c27',
  border: '#15141c',
  hairline: '#4d4a5e',
  text: '#e6e3ee',
  muted: '#aaa6ba',
  dim: '#84809a',
  accent: '#f0b497',
  'accent-soft': '#f0b49733',
  'control-value': '#f4f1fa',
  danger: '#ec7f8e',
  solo: '#e3c574',
  mute: '#e6e3ee',
  meter: '#f0b497',
  'meter-hot': '#ec7f8e',
  'meter-rms': '#aaa6ba',
  'meter-lufs': '#9fb0e6',
  'meter-track': '#17161f',
  'meter-border': 'transparent',
  playhead: '#f4f1fa',
  clip: '#3a3848',
  'clip-border': '#f0b497',
  'clip-active': '#f0b49733',
  focus: '#f0b497',
  'grid-line': '#282633',
  'grid-line-strong': '#3b3849',
  rule: '#100f16',
  automation: '#8fd6c9',
  'brush-1': '#a15839',
  'brush-2': '#af4761',
  'brush-3': '#8156b3',
  'brush-4': '#4d69aa',
  'brush-5': '#327671',
  'brush-6': '#6c6783',
  'brush-ink-1': '#feeee7',
  'brush-ink-2': '#fdedf1',
  'brush-ink-3': '#f5eefd',
  'brush-ink-4': '#ecf1fd',
  'brush-ink-5': '#dcf6f5',
  'brush-ink-6': '#f1f0f7',
}

/**
 * Night: the darkest grid theme, for late sessions. Near black with a warm cast,
 * a dim amber accent, chrome held low and text kept readable.
 */
export const night: Required<LiveMixTheme> = {
  ...jaxaZenDark,
  ...(gridGeometry as Required<LiveMixTheme>),
  bg: '#100e0d',
  panel: '#161413',
  raised: '#221f1c',
  sunken: '#0b0a09',
  border: '#2a2623',
  hairline: '#3d3833',
  text: '#bcb1a2',
  muted: '#958b7d',
  dim: '#6f675d',
  accent: '#b98d4e',
  'accent-soft': '#b98d4e33',
  'control-value': '#cfc5b6',
  danger: '#c0685a',
  solo: '#b8a04a',
  mute: '#bcb1a2',
  meter: '#b98d4e',
  'meter-hot': '#c0685a',
  'meter-rms': '#958b7d',
  'meter-lufs': '#7890a8',
  'meter-track': '#060505',
  'meter-border': 'transparent',
  playhead: '#cfc5b6',
  clip: '#221f1c',
  'clip-border': '#b98d4e',
  'clip-active': '#b98d4e33',
  focus: '#b98d4e',
  'grid-line': '#181614',
  'grid-line-strong': '#2b2723',
  rule: '#2f2a26',
  automation: '#c7a66a',
  'brush-1': '#815931',
  'brush-2': '#914c41',
  'brush-3': '#735382',
  'brush-4': '#496182',
  'brush-5': '#3b6a5e',
  'brush-6': '#645f55',
  'brush-ink-1': '#ecdac7',
  'brush-ink-2': '#eed6d2',
  'brush-ink-3': '#e5d7ec',
  'brush-ink-4': '#d1dceb',
  'brush-ink-5': '#c5e3dc',
  'brush-ink-6': '#dedbd5',
}

/**
 * Sand: a warm light grid theme. Oat surfaces, brown ink, a terracotta accent,
 * and paint in clay, ochre, sage and dusty blue.
 */
export const sand: Required<LiveMixTheme> = {
  ...jaxaZenLight,
  ...(gridGeometry as Required<LiveMixTheme>),
  bg: '#ede5d7',
  panel: '#e7decd',
  raised: '#f7f2e8',
  sunken: '#f4eee2',
  border: '#cfc3ad',
  hairline: '#bfb198',
  text: '#33261b',
  muted: '#665544',
  dim: '#84725d',
  accent: '#9f4729',
  'accent-soft': '#9f472926',
  'control-value': '#33261b',
  danger: '#a3273f',
  solo: '#8a6612',
  mute: '#33261b',
  meter: '#9f4729',
  'meter-hot': '#a3273f',
  'meter-rms': '#b3a48c',
  'meter-lufs': '#587890',
  'meter-track': '#ddd2be',
  'meter-border': 'transparent',
  playhead: '#33261b',
  clip: '#f7f2e8',
  'clip-border': '#33261b',
  'clip-active': '#9f472926',
  focus: '#9f4729',
  'grid-line': '#e7dfd0',
  'grid-line-strong': '#d1c6b1',
  rule: '#665544',
  automation: '#7a3d6c',
  'brush-1': '#c98b6c',
  'brush-2': '#d0aa58',
  'brush-3': '#a2b389',
  'brush-4': '#8ba8be',
  'brush-5': '#c6a09c',
  'brush-6': '#b3a999',
  'brush-ink-1': '#4f2613',
  'brush-ink-2': '#4a3608',
  'brush-ink-3': '#2e3b1c',
  'brush-ink-4': '#1d3546',
  'brush-ink-5': '#4b2622',
  'brush-ink-6': '#3a342a',
}

/**
 * Groovebox: a light grid theme after hardware grooveboxes. A warm grey body,
 * near-black ink and rules, an orange accent, and paint that leans primary.
 */
export const groovebox: Required<LiveMixTheme> = {
  ...jaxaZenLight,
  ...(gridGeometry as Required<LiveMixTheme>),
  bg: '#eae8e3',
  panel: '#dedbd5',
  raised: '#f5f4f1',
  sunken: '#f1f0ec',
  border: '#b8b5ad',
  hairline: '#a5a299',
  text: '#151515',
  muted: '#4d4b47',
  dim: '#6c6963',
  accent: '#b24200',
  'accent-soft': '#b2420026',
  'control-value': '#151515',
  danger: '#c1272d',
  solo: '#8a6a00',
  mute: '#151515',
  meter: '#151515',
  'meter-hot': '#c1272d',
  'meter-rms': '#8f8c85',
  'meter-lufs': '#2f5fb0',
  'meter-track': '#cfccc5',
  'meter-border': 'transparent',
  playhead: '#151515',
  clip: '#f5f4f1',
  'clip-border': '#151515',
  'clip-active': '#b2420026',
  focus: '#b24200',
  'grid-line': '#e2e0da',
  'grid-line-strong': '#c4c1b9',
  rule: '#151515',
  automation: '#a81f7a',
  'brush-1': '#f07a2a',
  'brush-2': '#4a86d8',
  'brush-3': '#e6c02e',
  'brush-4': '#55a862',
  'brush-5': '#e0655a',
  'brush-6': '#9c9992',
  'brush-ink-1': '#4a1d00',
  'brush-ink-2': '#081a3d',
  'brush-ink-3': '#4d3d00',
  'brush-ink-4': '#0e3316',
  'brush-ink-5': '#400a06',
  'brush-ink-6': '#262522',
}

/**
 * Chalk: the white grid theme. White surfaces, black ink, thin grey rules, one
 * cool blue accent, and paint in clear, soft colours.
 */
export const chalk: Required<LiveMixTheme> = {
  ...jaxaZenLight,
  ...(gridGeometry as Required<LiveMixTheme>),
  bg: '#ffffff',
  panel: '#ffffff',
  raised: '#f2f3f5',
  sunken: '#ffffff',
  border: '#d8dbdf',
  hairline: '#c4c8cd',
  text: '#0a0a0a',
  muted: '#555a60',
  dim: '#7a8087',
  accent: '#1f5fd6',
  'accent-soft': '#1f5fd61f',
  'control-value': '#0a0a0a',
  danger: '#c9302c',
  solo: '#8f6f00',
  mute: '#0a0a0a',
  meter: '#0a0a0a',
  'meter-hot': '#c9302c',
  'meter-rms': '#9aa0a6',
  'meter-lufs': '#1f5fd6',
  'meter-track': '#e6e8eb',
  'meter-border': 'transparent',
  playhead: '#0a0a0a',
  clip: '#f2f3f5',
  'clip-border': '#0a0a0a',
  'clip-active': '#1f5fd61f',
  focus: '#1f5fd6',
  'grid-line': '#eef0f2',
  'grid-line-strong': '#d3d7dc',
  rule: '#8b9198',
  automation: '#c2410c',
  'brush-1': '#74a9e6',
  'brush-2': '#6bc0a2',
  'brush-3': '#e3bd3f',
  'brush-4': '#ee8f80',
  'brush-5': '#a996e4',
  'brush-6': '#b1b7be',
  'brush-ink-1': '#0f3360',
  'brush-ink-2': '#0e3d2e',
  'brush-ink-3': '#4a3a00',
  'brush-ink-4': '#5a1a10',
  'brush-ink-5': '#2b1c63',
  'brush-ink-6': '#2e3338',
}

/**
 * Mist: a softer white grid theme. Cool off-white, pale blue-grey rules, slate
 * ink, a lavender accent, and pastel paint.
 */
export const mist: Required<LiveMixTheme> = {
  ...jaxaZenLight,
  ...(gridGeometry as Required<LiveMixTheme>),
  bg: '#f3f5f8',
  panel: '#eceff4',
  raised: '#fbfcfd',
  sunken: '#f8f9fb',
  border: '#d2d9e2',
  hairline: '#c0cad6',
  text: '#2a3440',
  muted: '#56626f',
  dim: '#75818f',
  accent: '#6c5fc2',
  'accent-soft': '#6c5fc226',
  'control-value': '#2a3440',
  danger: '#b23a55',
  solo: '#8c6d14',
  mute: '#2a3440',
  meter: '#6c5fc2',
  'meter-hot': '#b23a55',
  'meter-rms': '#a3aebb',
  'meter-lufs': '#4f7fa6',
  'meter-track': '#dfe4eb',
  'meter-border': 'transparent',
  playhead: '#2a3440',
  clip: '#fbfcfd',
  'clip-border': '#2a3440',
  'clip-active': '#6c5fc226',
  focus: '#6c5fc2',
  'grid-line': '#e9edf2',
  'grid-line-strong': '#d0d8e1',
  rule: '#8794a3',
  automation: '#a2553a',
  'brush-1': '#b0a4e6',
  'brush-2': '#98c1e8',
  'brush-3': '#9fd3bf',
  'brush-4': '#ebaeb7',
  'brush-5': '#dcc56f',
  'brush-6': '#b6c1cd',
  'brush-ink-1': '#2f2470',
  'brush-ink-2': '#143a5c',
  'brush-ink-3': '#12483a',
  'brush-ink-4': '#5e1f2c',
  'brush-ink-5': '#4a3d08',
  'brush-ink-6': '#2c3743',
}

export const themes = {
  'jaxa-zen': jaxaZenLight,
  'jaxa-zen-dark': jaxaZenDark,
  'ambient-water': ambientWater,
  graphite,
  paper,
  water,
  dusk,
  night,
  sand,
  groovebox,
  chalk,
  mist,
} as const

export type LiveMixThemeName = keyof typeof themes

/** The CSS variable name of a token. */
export function tokenVar(token: LiveMixToken): `--lm-${LiveMixToken}` {
  return `--lm-${token}`
}

/** `var(--lm-token, fallback)` — what components put in inline styles and SVG attributes. */
export function tokenRef(token: LiveMixToken, fallback?: string): string {
  return fallback === undefined ? `var(--lm-${token})` : `var(--lm-${token}, ${fallback})`
}

/**
 * Inline style declaring a theme's tokens, for hosts that set variables on a
 * wrapper element instead of importing `styles.css`.
 */
export function themeStyle(theme: LiveMixTheme): CSSProperties {
  const style: Record<string, string> = {}
  for (const [token, value] of Object.entries(theme)) {
    if (value !== undefined) style[`--lm-${token}`] = value
  }
  return style
}

/** Join class names, dropping falsy entries. */
export function cx(...names: (string | false | null | undefined)[]): string {
  return names.filter(Boolean).join(' ')
}
