// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Ice, shared with
// src/dsp/devices/ice.gen.ts:
//    0  distance: 0..1, default 0.45
//    1  bright: 0..1, default 0.6
//    2  ring: 0.3..30 s, default 5
//    3  thick: 0..1, default 0.5
//    4  crack: 0..1, default 0.35
//    5  stretch: 0..1, default 0.3
//    6  shore: 0..1, default 0.4
//    7  cracks: 0..1, default 0.4
//    8  roam: 0..1, default 0.5
//    9  width: 0..1, default 0.8
//   10  volume: -48..6 dB, default -6

#pragma once

namespace livemix {
namespace ice {

enum Param : int {
  kDistance = 0,
  kBright = 1,
  kRing = 2,
  kThick = 3,
  kCrack = 4,
  kStretch = 5,
  kShore = 6,
  kCracks = 7,
  kRoam = 8,
  kWidth = 9,
  kVolume = 10,
  kNumParams = 11,
};

inline constexpr float kParamMin[kNumParams] = {0.0f, 0.0f, 0.3f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, -48.0f};
inline constexpr float kParamMax[kNumParams] = {1.0f, 1.0f, 30.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 6.0f};
inline constexpr float kParamDefault[kNumParams] = {0.45f, 0.6f, 5.0f, 0.5f, 0.35f, 0.3f, 0.4f, 0.4f, 0.5f, 0.8f, -6.0f};

}  // namespace ice
}  // namespace livemix
