// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Vintage Digital, shared with
// src/dsp/devices/vintage-digital.gen.ts:
//    0  rate: 1000..48000 Hz, default 9000
//    1  bits: 4..16 bit, default 12
//    2  companding: 0 Linear, 1 Mu-law, default 0
//    3  aliasing: 0..1, default 0.35
//    4  filter: 0 None, 1 Soft, 2 Steep, default 1
//    5  jitter: 0..1, default 0.4
//    6  drive: 0..24 dB, default 0
//    7  mix: 0..1, default 1

#pragma once

namespace livemix {
namespace vintage_digital {

enum Param : int {
  kRate = 0,
  kBits = 1,
  kCompanding = 2,
  kAliasing = 3,
  kFilter = 4,
  kJitter = 5,
  kDrive = 6,
  kMix = 7,
  kNumParams = 8,
};

inline constexpr float kParamMin[kNumParams] = {1000.0f, 4.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
inline constexpr float kParamMax[kNumParams] = {48000.0f, 16.0f, 1.0f, 1.0f, 2.0f, 1.0f, 24.0f, 1.0f};
inline constexpr float kParamDefault[kNumParams] = {9000.0f, 12.0f, 0.0f, 0.35f, 1.0f, 0.4f, 0.0f, 1.0f};

}  // namespace vintage_digital
}  // namespace livemix
