// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Ambient Limiter, shared with
// src/dsp/devices/ambient-limiter.gen.ts:
//    0  ceiling: -12..0 dBTP, default -1
//    1  gain: -12..24 dB, default 0
//    2  release: 0.2..10 s, default 1.5
//    3  ride: 0..1, default 1
//    4  autoGain: 0..24 dB, default 0

#pragma once

namespace livemix {
namespace ambient_limiter {

enum Param : int {
  kCeiling = 0,
  kGain = 1,
  kRelease = 2,
  kRide = 3,
  kAutoGain = 4,
  kNumParams = 5,
};

inline constexpr float kParamMin[kNumParams] = {-12.0f, -12.0f, 0.2f, 0.0f, 0.0f};
inline constexpr float kParamMax[kNumParams] = {0.0f, 24.0f, 10.0f, 1.0f, 24.0f};
inline constexpr float kParamDefault[kNumParams] = {-1.0f, 0.0f, 1.5f, 1.0f, 0.0f};

}  // namespace ambient_limiter
}  // namespace livemix
