// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Noise Floor, shared with
// src/dsp/devices/noise-floor.gen.ts:
//    0  type: 0 Tape hiss, 1 Vinyl, 2 Room, 3 Hum 50, 4 Hum 60, 5 Static, 6 Air, default 0
//    1  level: -72..-12 dB, default -42
//    2  follow: -1..1, default 0
//    3  response: 0.02..4 s, default 0.4
//    4  tone: -1..1, default 0
//    5  movement: 0..1, default 0.3
//    6  width: 0..1, default 0.8
//    7  hold: 1..60 s, default 12

#pragma once

namespace livemix {
namespace noise_floor {

enum Param : int {
  kType = 0,
  kLevel = 1,
  kFollow = 2,
  kResponse = 3,
  kTone = 4,
  kMovement = 5,
  kWidth = 6,
  kHold = 7,
  kNumParams = 8,
};

inline constexpr float kParamMin[kNumParams] = {0.0f, -72.0f, -1.0f, 0.02f, -1.0f, 0.0f, 0.0f, 1.0f};
inline constexpr float kParamMax[kNumParams] = {6.0f, -12.0f, 1.0f, 4.0f, 1.0f, 1.0f, 1.0f, 60.0f};
inline constexpr float kParamDefault[kNumParams] = {0.0f, -42.0f, 0.0f, 0.4f, 0.0f, 0.3f, 0.8f, 12.0f};

}  // namespace noise_floor
}  // namespace livemix
