// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Saturator, shared with
// src/dsp/devices/saturator.gen.ts:
//    0  curve: 0 Soft, 1 Hard, 2 Tube, 3 Tape, 4 Fold, default 0
//    1  driveDb: 0..36 dB, default 6
//    2  bias: -1..1, default 0
//    3  toneDb: -12..12 dB, default 0
//    4  outputDb: -24..24 dB, default 0
//    5  mix: 0..1, default 1
//    6  dcBlock: 0 Off, 1 On, default 1
//    7  oversample: 0 1x, 1 2x, 2 4x, default 2
//    8  adaa: 0 Off, 1 On, default 0

#pragma once

namespace livemix {
namespace saturator {

enum Param : int {
  kCurve = 0,
  kDriveDb = 1,
  kBias = 2,
  kToneDb = 3,
  kOutputDb = 4,
  kMix = 5,
  kDcBlock = 6,
  kOversample = 7,
  kAdaa = 8,
  kNumParams = 9,
};

inline constexpr float kParamMin[kNumParams] = {0.0f, 0.0f, -1.0f, -12.0f, -24.0f, 0.0f, 0.0f, 0.0f, 0.0f};
inline constexpr float kParamMax[kNumParams] = {4.0f, 36.0f, 1.0f, 12.0f, 24.0f, 1.0f, 1.0f, 2.0f, 1.0f};
inline constexpr float kParamDefault[kNumParams] = {0.0f, 6.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 2.0f, 0.0f};

}  // namespace saturator
}  // namespace livemix
