// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Shimmer, shared with
// src/dsp/devices/shimmer.gen.ts:
//    0  mix: 0..1, default 0.4
//    1  decay: 0.5..30 s, default 8
//    2  shimmer: 0..1, default 0.5
//    3  interval: 0 Octave up, 1 Fifth up, 2 Octave and fifth, 3 Octave down, 4 Two octaves, default 0
//    4  size: 0..1, default 0.5
//    5  tone: 500..16000 Hz, default 6000
//    6  modulation: 0..1, default 0.3
//    7  predelay: 0..500 ms, default 20
//    8  lowCut: 20..1000 Hz, default 100
//    9  width: 0..1, default 1

#pragma once

namespace livemix {
namespace shimmer {

enum Param : int {
  kMix = 0,
  kDecay = 1,
  kShimmer = 2,
  kInterval = 3,
  kSize = 4,
  kTone = 5,
  kModulation = 6,
  kPredelay = 7,
  kLowCut = 8,
  kWidth = 9,
  kNumParams = 10,
};

inline constexpr float kParamMin[kNumParams] = {0.0f, 0.5f, 0.0f, 0.0f, 0.0f, 500.0f, 0.0f, 0.0f, 20.0f, 0.0f};
inline constexpr float kParamMax[kNumParams] = {1.0f, 30.0f, 1.0f, 4.0f, 1.0f, 16000.0f, 1.0f, 500.0f, 1000.0f, 1.0f};
inline constexpr float kParamDefault[kNumParams] = {0.4f, 8.0f, 0.5f, 0.0f, 0.5f, 6000.0f, 0.3f, 20.0f, 100.0f, 1.0f};

}  // namespace shimmer
}  // namespace livemix
