// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Harp, shared with
// src/dsp/devices/harp.gen.ts:
//    0  strings: 0 Harp, 1 Koto, 2 Guzheng, default 0
//    1  pluck: 0.04..0.5, default 0.36
//    2  touch: 0..1, default 0.4
//    3  decay: 0.25..4, default 1
//    4  damp: 0..1, default 0
//    5  halo: 0..1, default 0.5
//    6  sweep: 0..1.5 s, default 0
//    7  bend: 0..200 ct, default 0
//    8  body: 0..1, default 0.6
//    9  volume: -48..6 dB, default -6

#pragma once

namespace livemix {
namespace harp {

enum Param : int {
  kStrings = 0,
  kPluck = 1,
  kTouch = 2,
  kDecay = 3,
  kDamp = 4,
  kHalo = 5,
  kSweep = 6,
  kBend = 7,
  kBody = 8,
  kVolume = 9,
  kNumParams = 10,
};

inline constexpr float kParamMin[kNumParams] = {0.0f, 0.04f, 0.0f, 0.25f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, -48.0f};
inline constexpr float kParamMax[kNumParams] = {2.0f, 0.5f, 1.0f, 4.0f, 1.0f, 1.0f, 1.5f, 200.0f, 1.0f, 6.0f};
inline constexpr float kParamDefault[kNumParams] = {0.0f, 0.36f, 0.4f, 1.0f, 0.0f, 0.5f, 0.0f, 0.0f, 0.6f, -6.0f};

}  // namespace harp
}  // namespace livemix
