// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Spring, shared with
// src/dsp/devices/spring-reverb.gen.ts:
//    0  mix: 0..1, default 0.3
//    1  decay: 0.5..6 s, default 2.5
//    2  tension: 0..1, default 0.5
//    3  springs: 0 One, 1 Two, 2 Three, default 1
//    4  tone: 500..6000 Hz, default 3500
//    5  drip: 0..1, default 0.4
//    6  predelay: 0..200 ms, default 0
//    7  drive: 0..1, default 0.25
//    8  width: 0..1, default 1

#pragma once

namespace livemix {
namespace spring_reverb {

enum Param : int {
  kMix = 0,
  kDecay = 1,
  kTension = 2,
  kSprings = 3,
  kTone = 4,
  kDrip = 5,
  kPredelay = 6,
  kDrive = 7,
  kWidth = 8,
  kNumParams = 9,
};

inline constexpr float kParamMin[kNumParams] = {0.0f, 0.5f, 0.0f, 0.0f, 500.0f, 0.0f, 0.0f, 0.0f, 0.0f};
inline constexpr float kParamMax[kNumParams] = {1.0f, 6.0f, 1.0f, 2.0f, 6000.0f, 1.0f, 200.0f, 1.0f, 1.0f};
inline constexpr float kParamDefault[kNumParams] = {0.3f, 2.5f, 0.5f, 1.0f, 3500.0f, 0.4f, 0.0f, 0.25f, 1.0f};

}  // namespace spring_reverb
}  // namespace livemix
