// Score (U28): the declarative document that is the source of truth for
// arrangement, automation and device graphs; the operations that edit it;
// the append-only log with authors; undo/redo; and the renderer that makes
// an Engine follow it.

export {
  MASTER_OWNER,
  SCORE_FORMAT_VERSION,
  STRIP_PARAMS,
  STRIP_PARAM_RANGES,
  ScoreValidationError,
  allDevices,
  assertValidScore,
  createScore,
  defaultStrip,
  defaultTempo,
  findDevice,
  findElementTrack,
  findGroup,
  findReturn,
  findStripHost,
  findTrack,
  groupDestination,
  masterDestination,
  migrateScore,
  normaliseClip,
  normaliseQuantize,
  normaliseScore,
  normaliseSlot,
  normaliseSlotClip,
  normaliseTempo,
  parseScore,
  sameDestination,
  sameTarget,
  sameTempo,
  serializeScore,
  stripHosts,
  targetKey,
  validateScore,
  type CreateScoreOptions,
  type DeviceLocation,
  type ParamTarget,
  type Score,
  type ScoreAudioTrack,
  type ScoreDestination,
  type ScoreDevice,
  type ScoreElementTrack,
  type ScoreGroup,
  type ScoreInstrumentTrack,
  type ScoreIssue,
  type ScoreLane,
  type ScoreLiveTrack,
  type ScoreMaster,
  type ScoreModRoute,
  type ScoreModulator,
  type ScoreModulatorKind,
  type ScoreReturn,
  type ScoreSend,
  type ScoreSource,
  type ScoreStrip,
  type ScoreStripHost,
  type ScoreTrack,
  type ScoreTrackKind,
  type ScoreTransport,
  type StripParam,
  type ValidateScoreOptions,
} from './schema'
export {
  OPERATION_TYPES,
  ScoreOperationError,
  apply,
  applyWithInverse,
  coalesceKey,
  describeOperation,
  invert,
  isOperation,
  type Applied,
  type ClipPatch,
  type ModulatorPatch,
  type Operation,
  type OperationType,
  type SlotPatch,
} from './operations'
export {
  AUTOMATION_AUTHOR,
  CONTROLLER_AUTHOR,
  DEFAULT_CHECKPOINT_EVERY,
  LOCAL_AUTHOR,
  LOG_FORMAT_VERSION,
  OperationLog,
  SYSTEM_AUTHOR,
  parseLog,
  serializeLog,
  type Author,
  type AuthorKind,
  type LogCheckpoint,
  type LogEntry,
  type LogEntryKind,
  type OperationLogOptions,
  type SerializedLog,
} from './log'
export {
  DEFAULT_COALESCE_WINDOW_MS,
  DEFAULT_HISTORY_LIMIT,
  History,
  type HistoryEntry,
  type HistoryOptions,
  type HistoryPush,
} from './history'
export {
  ScoreDocument,
  type ApplyOptions,
  type ScoreChange,
  type ScoreChangeKind,
  type ScoreDocumentOptions,
  type ScoreListener,
} from './ScoreDocument'
export {
  ScoreRenderError,
  ScoreRenderer,
  type RenderedHost,
  type ScoreRendererOptions,
} from './ScoreRenderer'
export { loadScore, scoreRendererOf, unloadScore } from './loadScore'
export {
  renderScore,
  renderScoreStems,
  renderableScore,
  type RenderScoreOptions,
  type RenderScoreStemsOptions,
} from './renderScore'
export {
  ANY_TARGET,
  Arbiter,
  MASTER_LEVEL_KEY,
  arbiterKey,
  arbiterTargets,
  conflicts,
  paramTargetOf,
  type ArbiterEvent,
  type ArbiterListener,
  type ArbiterOptions,
  type ArbiterOutcome,
  type ArbiterResult,
  type DropReason,
  type LockOptions,
  type PendingWrite,
  type TargetState,
} from './Arbiter'
export {
  arbitratedControlWriter,
  controlWriteToOperation,
  type ControlWriterOptions,
} from './controlWriter'
export { describeFieldChange, diffScores, type FieldChange, type FieldChangeKind } from './diff'
export {
  DEFAULT_FULL_EVERY,
  DEFAULT_VERSION_BUDGET_BYTES,
  DEFAULT_VERSION_TOTAL_BUDGET_BYTES,
  VERSION_FORMAT,
  VersionHistory,
  parseStoredVersion,
  type Milestone,
  type RestoreOptions,
  type SaveOptions,
  type StoredOp,
  type StoredVersion,
  type VersionDiff,
  type VersionEvent,
  type VersionHistoryOptions,
  type VersionKind,
  type VersionListener,
  type VersionSummary,
} from './versions'
export {
  VERSION_STORAGE_KEY,
  byteLength,
  indexedDbVersionStorage,
  memoryVersionStorage,
  webStorageVersionStorage,
  type IndexedDbVersionStorageOptions,
  type StoredVersionRecord,
  type VersionStorage,
} from './versionStorage'
