// Score (U28): the declarative document that is the source of truth for
// arrangement, automation and device graphs; the operations that edit it;
// the append-only log with authors; undo/redo; and the renderer that makes
// an Engine follow it.

export {
  MASTER_OWNER,
  SCORE_FORMAT_VERSION,
  STRIP_PARAMS,
  STRIP_PARAM_RANGES,
  ScoreValidationError,
  allDevices,
  assertValidScore,
  createScore,
  defaultStrip,
  defaultTempo,
  findDevice,
  findElementTrack,
  findGroup,
  findReturn,
  findStripHost,
  findTrack,
  groupDestination,
  masterDestination,
  migrateScore,
  normaliseClip,
  normaliseScore,
  normaliseTempo,
  parseScore,
  sameDestination,
  sameTarget,
  sameTempo,
  serializeScore,
  stripHosts,
  targetKey,
  validateScore,
  type CreateScoreOptions,
  type DeviceLocation,
  type ParamTarget,
  type Score,
  type ScoreAudioTrack,
  type ScoreDestination,
  type ScoreDevice,
  type ScoreElementTrack,
  type ScoreGroup,
  type ScoreInstrumentTrack,
  type ScoreIssue,
  type ScoreLane,
  type ScoreLiveTrack,
  type ScoreMaster,
  type ScoreModRoute,
  type ScoreModulator,
  type ScoreModulatorKind,
  type ScoreReturn,
  type ScoreSend,
  type ScoreSource,
  type ScoreStrip,
  type ScoreStripHost,
  type ScoreTrack,
  type ScoreTrackKind,
  type ScoreTransport,
  type StripParam,
  type ValidateScoreOptions,
} from './schema'
export {
  OPERATION_TYPES,
  ScoreOperationError,
  apply,
  applyWithInverse,
  coalesceKey,
  describeOperation,
  invert,
  isOperation,
  type Applied,
  type ClipPatch,
  type ModulatorPatch,
  type Operation,
  type OperationType,
} from './operations'
export {
  DEFAULT_CHECKPOINT_EVERY,
  LOCAL_AUTHOR,
  LOG_FORMAT_VERSION,
  OperationLog,
  parseLog,
  serializeLog,
  type Author,
  type AuthorKind,
  type LogCheckpoint,
  type LogEntry,
  type LogEntryKind,
  type OperationLogOptions,
  type SerializedLog,
} from './log'
export {
  DEFAULT_COALESCE_WINDOW_MS,
  DEFAULT_HISTORY_LIMIT,
  History,
  type HistoryEntry,
  type HistoryOptions,
  type HistoryPush,
} from './history'
export {
  ScoreDocument,
  type ApplyOptions,
  type ScoreChange,
  type ScoreChangeKind,
  type ScoreDocumentOptions,
  type ScoreListener,
} from './ScoreDocument'
export {
  ScoreRenderError,
  ScoreRenderer,
  type RenderedHost,
  type ScoreRendererOptions,
} from './ScoreRenderer'
export { loadScore, scoreRendererOf, unloadScore } from './loadScore'
export {
  renderScore,
  renderScoreStems,
  renderableScore,
  type RenderScoreOptions,
  type RenderScoreStemsOptions,
} from './renderScore'
