// MIDI/OSC learn (U36, R15): a mapping table from controller sources to
// engine targets, learn mode, soft takeover, versioned persistence, input
// adapters over Web MIDI and OSC-over-WebSocket, and the `ControlSurface`
// that dispatches through the engine's ramped setters and respects
// automation. Pure modules first, adapters last; nothing reads a browser
// global at import time.

export {
  describeTarget,
  isActionTarget,
  isBooleanTarget,
  parseControlTarget,
  sameControlTarget,
  controlTargetKey,
  type ControlTarget,
  type ControlTargetKind,
  type StripControl,
  type TransportAction,
} from './target'
export {
  MIDI_OMNI,
  describeSource,
  isMidiSource,
  parseControlSource,
  sameSource,
  sourceKey,
  sourceMatches,
  type ControlSource,
  type ControlSourceKind,
  type MidiChannel,
  type MidiSource,
  type OscSource,
} from './source'
export { absoluteEvent, triggerEvent, type ControlEvent } from './event'
export {
  MIDI_14BIT_MAX,
  MidiDecoder,
  RELATIVE_ENCODINGS,
  controlEventsFromMidi,
  decodeRelative,
  midiDataLength,
  parseMidiMessage,
  type MidiDecoderOptions,
  type MidiMessage,
  type RelativeEncoding,
} from './midi'
export { isOscPattern, matchOscAddress, oscPatternToRegExp } from './osc-address'
export {
  OSC_IMMEDIATELY,
  OscDecodeError,
  controlEventsFromOsc,
  decodeOscMessage,
  decodeOscPacket,
  encodeOscBundle,
  encodeOscMessage,
  encodeOscPacket,
  flattenOscPacket,
  isOscBundle,
  oscTimeTagToDate,
  type OscArg,
  type OscBundle,
  type OscMessage,
  type OscPacket,
} from './osc'
export {
  DEFAULT_RELATIVE_STEP,
  IDLE_LEARN,
  MAPPING_CURVES,
  MAPPING_MODES,
  PICKUP_EPSILON,
  UNIT_RANGE,
  applyCurve,
  createMapping,
  createResolveState,
  describeMapping,
  inferMode,
  isMapped,
  learnFromEvent,
  mapTarget,
  mappingFor,
  mappingKey,
  mappingsFor,
  normalizeInput,
  nudgedValue,
  pickupAllows,
  resolveControlEvent,
  shapeValue,
  toggledValue,
  unmapSource,
  unmapTarget,
  updateMapping,
  upgradeLearnedSource,
  type ControlChange,
  type LearnOutcome,
  type LearnState,
  type Mapping,
  type MappingCurve,
  type MappingInit,
  type MappingMode,
  type MappingRange,
  type MappingTable,
  type PickupMemory,
  type ResolveContext,
  type ResolveState,
} from './mapping'
export {
  AMBIENT_LIVE_MIDI_MAP_FORMAT,
  MAPPING_STORAGE_KEY,
  MAPPING_TABLE_FORMAT,
  ambientLiveMidiMapMigration,
  type AmbientLiveMigrationOptions,
  loadMappingTable,
  mappingTableToJSON,
  parseMapping,
  parseMappingTable,
  saveMappingTable,
  serializeMappingTable,
  type MappingMigration,
  type MappingStorageOptions,
  type ParseMappingTableOptions,
  type SerializedMappingTable,
  type StorageLike,
} from './serialize'
export {
  DEFAULT_LEVEL_MAX,
  engineResolver,
  resolveStripHost,
  resolveBinding,
  type BindingOptions,
  type ControlBinding,
  type ControlResolver,
} from './bindings'
export {
  ControlSurface,
  type BeginLearnOptions,
  type ControlInput,
  type ControlSurfaceChange,
  type ControlSurfaceListener,
  type ControlSurfaceOptions,
  type HandleResult,
} from './ControlSurface'
export {
  MidiInput,
  isWebMidiSupported,
  fromMidiAccess,
  type BrowserMidiAccessLike,
  type BrowserMidiInputLike,
  type MidiAccessLike,
  type MidiStateChangeEventLike,
  type MidiAccessRequest,
  type MidiInputOptions,
  type MidiMessageEventLike,
  type MidiMessageListener,
  type MidiPortInfo,
  type MidiPortLike,
} from './MidiInput'
export {
  OscInput,
  isWebSocketSupported,
  webSocketTransport,
  type OscInputOptions,
  type OscPacketBytes,
  type OscTransport,
  type WebSocketFactory,
  type WebSocketLike,
} from './OscInput'
