// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Spectral Blur, shared with
// src/dsp/devices/spectral-blur.gen.ts:
//    0  blur: 0..1, default 0.6
//    1  smear: 0..1, default 0.7
//    2  freeze: 0 Off, 1 On, default 0
//    3  tilt: -6..6 dB/oct, default -0.5
//    4  lowCut: 20..2000 Hz, default 20
//    5  highCut: 500..20000 Hz, default 12000
//    6  shimmer: 0..1, default 0.15
//    7  width: 0..1, default 1
//    8  mix: 0..1, default 0.5

#pragma once

namespace livemix {
namespace spectral_blur {

enum Param : int {
  kBlur = 0,
  kSmear = 1,
  kFreeze = 2,
  kTilt = 3,
  kLowCut = 4,
  kHighCut = 5,
  kShimmer = 6,
  kWidth = 7,
  kMix = 8,
  kNumParams = 9,
};

inline constexpr float kParamMin[kNumParams] = {0.0f, 0.0f, 0.0f, -6.0f, 20.0f, 500.0f, 0.0f, 0.0f, 0.0f};
inline constexpr float kParamMax[kNumParams] = {1.0f, 1.0f, 1.0f, 6.0f, 2000.0f, 20000.0f, 1.0f, 1.0f, 1.0f};
inline constexpr float kParamDefault[kNumParams] = {0.6f, 0.7f, 0.0f, -0.5f, 20.0f, 12000.0f, 0.15f, 1.0f, 0.5f};

}  // namespace spectral_blur
}  // namespace livemix
