// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Phaser, shared with
// src/dsp/devices/phaser.gen.ts:
//    0  stages: 0 4, 1 6, 2 8, 3 10, 4 12, default 1
//    1  centerHz: 100..5000 Hz, default 800
//    2  spread: 0..100 %, default 30
//    3  feedback: -95..95 %, default 40
//    4  rate: 0.01..10 Hz, default 0.3
//    5  depth: 0..100 %, default 60
//    6  shape: 0 Sine, 1 Triangle, 2 Saw up, 3 Saw down, 4 Square, 5 Random, default 0
//    7  stereo: 0..180 deg, default 90
//    8  mix: 0..1, default 0.5

#pragma once

namespace livemix {
namespace phaser {

enum Param : int {
  kStages = 0,
  kCenterHz = 1,
  kSpread = 2,
  kFeedback = 3,
  kRate = 4,
  kDepth = 5,
  kShape = 6,
  kStereo = 7,
  kMix = 8,
  kNumParams = 9,
};

inline constexpr float kParamMin[kNumParams] = {0.0f, 100.0f, 0.0f, -95.0f, 0.01f, 0.0f, 0.0f, 0.0f, 0.0f};
inline constexpr float kParamMax[kNumParams] = {4.0f, 5000.0f, 100.0f, 95.0f, 10.0f, 100.0f, 5.0f, 180.0f, 1.0f};
inline constexpr float kParamDefault[kNumParams] = {1.0f, 800.0f, 30.0f, 40.0f, 0.3f, 60.0f, 0.0f, 90.0f, 0.5f};

}  // namespace phaser
}  // namespace livemix
