#!/bin/bash
# Regenerates the C++ and TypeScript for the Faust devices from cpp/faust/*.dsp.
#
# Faust runs here and nowhere else: the generated C++ (cpp/faust/generated/*.h)
# and param tables (src/dsp/devices/faust/*.ts) are committed, and
# scripts/build-wasm.sh compiles the C++ exactly like a hand-written device.
# No Faust compiler, library or runtime ships to consumers.
#
# The compiler is pinned by building FAUST_VERSION from the release tarball
# (C++ backend only, ~1 minute on four cores) into tmp/faust-<version>/, which
# CI caches. Its bundled libraries are the only ones on the import path, so the
# output does not depend on whatever Faust the machine has installed. CI reruns
# this script and fails when the committed files differ (job `faust`).
set -euo pipefail
cd "$(dirname "$0")/.."

# Keep in sync with .github/workflows/ci.yml (cache key) and docs/faust-devices.md.
FAUST_VERSION="2.88.0"
FAUST_TARBALL_SHA256="e4e175cf236924b5b7d4784cbb8c50cc01e211159e169655dd9e6d8f92b871d9"
FAUST_TARBALL_URL="https://github.com/grame-cncm/faust/releases/download/${FAUST_VERSION}/faust-${FAUST_VERSION}.tar.gz"

# -nvi: no virtual methods, so the DSP is a plain value member with no vtable
# and clone() is dropped at link time (no operator new in the .wasm).
# -ftz 1: flush denormals in every recursive signal; WASM has no hardware FTZ.
# -scn/-ns: derive from the stand-ins in cpp/faust/common/faust_runtime.h.
FAUST_FLAGS=(-lang cpp -nvi -ftz 1 -scn FaustDsp -ns livemix::faust)

toolchain="tmp/faust-${FAUST_VERSION}"
faust="$toolchain/bin/faust"
libraries="$toolchain/libraries"

sha256_check() {
  local expected="$1" file="$2" actual
  if command -v sha256sum >/dev/null 2>&1; then
    actual=$(sha256sum "$file" | cut -d' ' -f1)
  else
    actual=$(shasum -a 256 "$file" | cut -d' ' -f1)
  fi
  if [ "$actual" != "$expected" ]; then
    echo "faust-${FAUST_VERSION}.tar.gz: sha256 mismatch (got $actual)" >&2
    exit 1
  fi
}

ensure_toolchain() {
  if [ -x "$faust" ] && [ -f "$libraries/stdfaust.lib" ]; then
    return
  fi
  for tool in curl tar cmake; do
    if ! command -v "$tool" >/dev/null 2>&1; then
      echo "$tool is required to build the pinned Faust compiler." >&2
      exit 1
    fi
  done
  echo "Building Faust ${FAUST_VERSION} (C++ backend only) into $toolchain"
  local work jobs
  work=$(mktemp -d "${TMPDIR:-/tmp}/faust-build.XXXXXX")
  jobs=$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 2)

  curl -fsSL -o "$work/faust.tar.gz" "$FAUST_TARBALL_URL"
  sha256_check "$FAUST_TARBALL_SHA256" "$work/faust.tar.gz"
  tar -xzf "$work/faust.tar.gz" -C "$work"
  local src="$work/faust-${FAUST_VERSION}"

  # Every backend off except C++ into the compiler; no libfaust, OSC, HTTP or LLVM.
  cat > "$work/backends.cmake" <<'EOF'
foreach (backend C CMAJOR CSHARP DLANG FIR INTERP JAVA JULIA JSFX LINEN LLVM NNX OLDCPP RUST TEMPLATE WASM)
  set (${backend}_BACKEND OFF CACHE STRING "" FORCE)
endforeach ()
set (CPP_BACKEND COMPILER CACHE STRING "" FORCE)
set (INCLUDE_EXECUTABLE ON CACHE STRING "" FORCE)
foreach (target STATIC DYNAMIC OSC HTTP ITP EMCC WASM_GLUE)
  set (INCLUDE_${target} OFF CACHE STRING "" FORCE)
endforeach ()
EOF
  cmake -S "$src/build" -B "$src/build/faustdir" -C "$work/backends.cmake" \
    -DCMAKE_BUILD_TYPE=Release -DINCLUDE_LLVM=OFF -DUSE_LLVM_CONFIG=OFF \
    -DSELF_CONTAINED_LIBRARY=ON >/dev/null
  cmake --build "$src/build/faustdir" --target faust --parallel "$jobs"

  rm -rf "$toolchain"
  mkdir -p "$toolchain/bin" "$libraries"
  cp "$src/build/bin/faust" "$faust"
  cp "$src/libraries/"*.lib "$libraries/"
  rm -rf "$work"
}

# build_device <name> <ClassName>: cpp/faust/<name>.dsp ->
#   cpp/faust/generated/<name>.h and src/dsp/devices/faust/<name>.ts
build_device() {
  local name="$1" class="$2"
  local work
  work=$(mktemp -d "${TMPDIR:-/tmp}/faust-${name}.XXXXXX")

  "$faust" "${FAUST_FLAGS[@]}" -cn "$class" -I "$libraries" \
    -json -O "$work" -o "$name.h" "cpp/faust/$name.dsp"

  {
    echo "// GENERATED by scripts/build-faust.sh from cpp/faust/$name.dsp. Do not edit."
    echo "// FaustDsp, UI and Meta are the stand-ins in cpp/faust/common/faust_runtime.h."
    echo '#include "../common/faust_runtime.h"'
    echo
    cat "$work/$name.h"
  } > "cpp/faust/generated/$name.h"

  node scripts/faust-params-to-ts.mjs "$work/$name.dsp.json" "$name" \
    > "src/dsp/devices/faust/$name.ts"
  pnpm exec prettier --log-level warn --write "src/dsp/devices/faust/$name.ts"

  rm -rf "$work"
  echo "Generated cpp/faust/generated/$name.h and src/dsp/devices/faust/$name.ts"
}

ensure_toolchain
"$faust" --version | head -n 1
mkdir -p cpp/faust/generated src/dsp/devices/faust

build_device zita-rev1 ZitaRev1
build_device limiter-1176 Limiter1176
