#!/bin/bash
# GENERATED by scripts/gen-devices.mjs from cpp/devices/*/device.json. Do not edit.
# Sourced by scripts/build-wasm.sh (build_device) and scripts/test-native.sh
# (native_test).

build_generated_devices() {
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device acoustic-guitar \
    cpp/devices/acoustic-guitar/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device afterglow \
    cpp/devices/afterglow/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_meter" build_device ambient-comp \
    cpp/devices/ambient-comp/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_meter" build_device ambient-eq \
    cpp/devices/ambient-eq/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_meter" build_device ambient-limiter \
    cpp/devices/ambient-limiter/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_meter" build_device analog-delay \
    cpp/devices/analog-delay/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_meter" build_device analog-drive \
    cpp/devices/analog-drive/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device atmosphere \
    cpp/devices/atmosphere/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device aurora \
    cpp/devices/aurora/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_meter" build_device auto-filter \
    cpp/devices/auto-filter/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_meter" build_device bloom-reverb \
    cpp/devices/bloom-reverb/device_api.gen.cpp \
    cpp/devices/spectral-drifter/SpectralDrifter.cpp \
    cpp/devices/stereo-widener/StereoWidener.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device bowed-string \
    cpp/devices/bowed-string/device_api.gen.cpp
  MEMORY_BYTES=16777216 EXTRA_EXPORTS=",_device_meter" build_device cascade \
    cpp/devices/cascade/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device chamber-strings \
    cpp/devices/chamber-strings/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device choir \
    cpp/devices/choir/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device chord-harp \
    cpp/devices/chord-harp/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_meter" build_device chorus \
    cpp/devices/chorus/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device clarinet \
    cpp/devices/clarinet/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device drone \
    cpp/devices/drone/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device droplets \
    cpp/devices/droplets/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device drum-kit \
    cpp/devices/drum-kit/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device dusk \
    cpp/devices/dusk/device_api.gen.cpp
  MEMORY_BYTES=20971520 EXTRA_EXPORTS=",_device_meter" build_device echo-memory \
    cpp/devices/echo-memory/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device ember \
    cpp/devices/ember/device_api.gen.cpp
  MEMORY_BYTES=6291456 EXTRA_EXPORTS="" build_device expanse \
    cpp/devices/expanse/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device feedback \
    cpp/devices/feedback/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_meter" build_device flanger \
    cpp/devices/flanger/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device flock \
    cpp/devices/flock/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device flute \
    cpp/devices/flute/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device fm-glass \
    cpp/devices/fm-glass/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_meter" build_device freq-shifter \
    cpp/devices/freq-shifter/device_api.gen.cpp
  MEMORY_BYTES=10485760 EXTRA_EXPORTS=",_device_meter" build_device glitch \
    cpp/devices/glitch/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device glitch-kit \
    cpp/devices/glitch-kit/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device graft \
    cpp/devices/graft/device_api.gen.cpp
  MEMORY_BYTES=10485760 EXTRA_EXPORTS=",_device_meter" build_device grain-cloud \
    cpp/devices/grain-cloud/device_api.gen.cpp
  MEMORY_BYTES=10485760 EXTRA_EXPORTS=",_device_meter" build_device grain-delay \
    cpp/devices/grain-delay/device_api.gen.cpp
  MEMORY_BYTES=12582912 EXTRA_EXPORTS=",_device_note_on,_device_note_off,_device_sample_capacity,_device_sample_buffer,_device_sample_commit" build_device grain-synth \
    cpp/devices/grain-synth/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device guitar \
    cpp/devices/guitar/device_api.gen.cpp
  MEMORY_BYTES=8388608 EXTRA_EXPORTS=",_device_meter" build_device half-speed \
    cpp/devices/half-speed/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device handpan \
    cpp/devices/handpan/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device harp \
    cpp/devices/harp/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device horns \
    cpp/devices/horns/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device ice \
    cpp/devices/ice/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device ladder-bass \
    cpp/devices/ladder-bass/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_meter" build_device lattice \
    cpp/devices/lattice/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_meter" build_device low-bitrate \
    cpp/devices/low-bitrate/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device magnet-piano \
    cpp/devices/magnet-piano/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device mallets \
    cpp/devices/mallets/device_api.gen.cpp
  MEMORY_BYTES=16777216 EXTRA_EXPORTS=",_device_meter" build_device micro-looper \
    cpp/devices/micro-looper/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device modal-bells \
    cpp/devices/modal-bells/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_meter" build_device noise-floor \
    cpp/devices/noise-floor/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_meter" build_device octaves \
    cpp/devices/octaves/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device organ \
    cpp/devices/organ/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device outdoors \
    cpp/devices/outdoors/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device overtone \
    cpp/devices/overtone/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_meter" build_device pad-follower \
    cpp/devices/pad-follower/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_meter" build_device patina \
    cpp/devices/patina/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device pedal-steel \
    cpp/devices/pedal-steel/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_meter" build_device phaser \
    cpp/devices/phaser/device_api.gen.cpp
  MEMORY_BYTES=6291456 EXTRA_EXPORTS="" build_device pitch-shifter \
    cpp/devices/pitch-shifter/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device prepared-piano \
    cpp/devices/prepared-piano/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_meter" build_device radio \
    cpp/devices/radio/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_meter" build_device re-amp \
    cpp/devices/re-amp/device_api.gen.cpp
  MEMORY_BYTES=20971520 EXTRA_EXPORTS=",_device_meter" build_device reverse-delay \
    cpp/devices/reverse-delay/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device rewind \
    cpp/devices/rewind/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_meter" build_device rotary \
    cpp/devices/rotary/device_api.gen.cpp
  MEMORY_BYTES=25165824 EXTRA_EXPORTS=",_device_note_on,_device_note_off,_device_sample_capacity,_device_sample_buffer,_device_sample_commit" build_device sampler \
    cpp/devices/sampler/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS="" build_device saturator \
    cpp/devices/saturator/device_api.gen.cpp
  MEMORY_BYTES=6291456 EXTRA_EXPORTS="" build_device shaped-reverb \
    cpp/devices/shaped-reverb/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS="" build_device shimmer \
    cpp/devices/shimmer/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device shortwave \
    cpp/devices/shortwave/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_meter" build_device spectral-blur \
    cpp/devices/spectral-blur/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS="" build_device spring-reverb \
    cpp/devices/spring-reverb/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device staircase \
    cpp/devices/staircase/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_meter" build_device stereo-detune \
    cpp/devices/stereo-detune/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device string-machine \
    cpp/devices/string-machine/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_meter" build_device sustainer \
    cpp/devices/sustainer/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_meter" build_device swarm-reverb \
    cpp/devices/swarm-reverb/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_meter" build_device swell \
    cpp/devices/swell/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_meter" build_device sympathetic \
    cpp/devices/sympathetic/device_api.gen.cpp \
    cpp/devices/stereo-widener/StereoWidener.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_meter" build_device tamer \
    cpp/devices/tamer/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device tanpura \
    cpp/devices/tanpura/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_meter" build_device tape \
    cpp/devices/tape/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_meter" build_device tape-echo \
    cpp/devices/tape-echo/device_api.gen.cpp
  MEMORY_BYTES=25165824 EXTRA_EXPORTS=",_device_meter" build_device tape-loop \
    cpp/devices/tape-loop/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device tape-orchestra \
    cpp/devices/tape-orchestra/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device thesis \
    cpp/devices/thesis/device_api.gen.cpp \
    cpp/devices/stereo-widener/StereoWidener.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device tine-piano \
    cpp/devices/tine-piano/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_meter" build_device tremolo \
    cpp/devices/tremolo/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS="" build_device vintage-digital \
    cpp/devices/vintage-digital/device_api.gen.cpp
  MEMORY_BYTES=8388608 EXTRA_EXPORTS=",_device_meter" build_device vinyl \
    cpp/devices/vinyl/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_meter" build_device vowel-reverb \
    cpp/devices/vowel-reverb/device_api.gen.cpp
  MEMORY_BYTES=5242880 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device wavetable \
    cpp/devices/wavetable/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device west-coast \
    cpp/devices/west-coast/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device wind-harp \
    cpp/devices/wind-harp/device_api.gen.cpp
  MEMORY_BYTES=4194304 EXTRA_EXPORTS=",_device_note_on,_device_note_off" build_device zither \
    cpp/devices/zither/device_api.gen.cpp
  MEMORY_BYTES=67108864 EXTRA_EXPORTS=",_device_note_on,_device_note_off,_device_sample_capacity,_device_sample_buffer,_device_sample_commit,_device_zone_capacity,_device_zone_pool_capacity,_device_zones_begin,_device_zone_sample,_device_zone_sample_buffer,_device_zone_fields,_device_zone_add" build_device zone-sampler \
    cpp/devices/zone-sampler/device_api.gen.cpp
}

test_generated_devices() {
  native_test acoustic_guitar_test \
    cpp/test/acoustic_guitar_test.cpp
  native_test afterglow_test \
    cpp/test/afterglow_test.cpp
  native_test ambient_comp_test \
    cpp/test/ambient_comp_test.cpp
  native_test ambient_eq_test \
    cpp/test/ambient_eq_test.cpp
  native_test ambient_limiter_test \
    cpp/test/ambient_limiter_test.cpp
  native_test analog_delay_test \
    cpp/test/analog_delay_test.cpp
  native_test analog_drive_test \
    cpp/test/analog_drive_test.cpp
  native_test atmosphere_test \
    cpp/test/atmosphere_test.cpp
  native_test aurora_test \
    cpp/test/aurora_test.cpp
  native_test auto_filter_test \
    cpp/test/auto_filter_test.cpp
  native_test bloom_reverb_test \
    cpp/test/bloom_reverb_test.cpp \
    cpp/devices/spectral-drifter/SpectralDrifter.cpp \
    cpp/devices/stereo-widener/StereoWidener.cpp
  native_test bowed_string_test \
    cpp/test/bowed_string_test.cpp
  native_test cascade_test \
    cpp/test/cascade_test.cpp
  native_test chamber_strings_test \
    cpp/test/chamber_strings_test.cpp
  native_test choir_test \
    cpp/test/choir_test.cpp
  native_test chord_harp_test \
    cpp/test/chord_harp_test.cpp
  native_test chorus_test \
    cpp/test/chorus_test.cpp
  native_test clarinet_test \
    cpp/test/clarinet_test.cpp
  native_test drone_test \
    cpp/test/drone_test.cpp
  native_test droplets_test \
    cpp/test/droplets_test.cpp
  native_test drum_kit_test \
    cpp/test/drum_kit_test.cpp
  native_test dusk_test \
    cpp/test/dusk_test.cpp
  native_test echo_memory_test \
    cpp/test/echo_memory_test.cpp
  native_test ember_test \
    cpp/test/ember_test.cpp
  native_test expanse_test \
    cpp/test/expanse_test.cpp
  native_test feedback_test \
    cpp/test/feedback_test.cpp
  native_test flanger_test \
    cpp/test/flanger_test.cpp
  native_test flock_test \
    cpp/test/flock_test.cpp
  native_test flute_test \
    cpp/test/flute_test.cpp
  native_test fm_glass_test \
    cpp/test/fm_glass_test.cpp
  native_test freq_shifter_test \
    cpp/test/freq_shifter_test.cpp
  native_test glitch_test \
    cpp/test/glitch_test.cpp
  native_test glitch_kit_test \
    cpp/test/glitch_kit_test.cpp
  native_test graft_test \
    cpp/test/graft_test.cpp
  native_test grain_cloud_test \
    cpp/test/grain_cloud_test.cpp
  native_test grain_delay_test \
    cpp/test/grain_delay_test.cpp
  native_test grain_synth_test \
    cpp/test/grain_synth_test.cpp
  native_test guitar_test \
    cpp/test/guitar_test.cpp
  native_test half_speed_test \
    cpp/test/half_speed_test.cpp
  native_test handpan_test \
    cpp/test/handpan_test.cpp
  native_test harp_test \
    cpp/test/harp_test.cpp
  native_test horns_test \
    cpp/test/horns_test.cpp
  native_test ice_test \
    cpp/test/ice_test.cpp
  native_test ladder_bass_test \
    cpp/test/ladder_bass_test.cpp
  native_test lattice_test \
    cpp/test/lattice_test.cpp
  native_test low_bitrate_test \
    cpp/test/low_bitrate_test.cpp
  native_test magnet_piano_test \
    cpp/test/magnet_piano_test.cpp
  native_test mallets_test \
    cpp/test/mallets_test.cpp
  native_test micro_looper_test \
    cpp/test/micro_looper_test.cpp
  native_test modal_bells_test \
    cpp/test/modal_bells_test.cpp
  native_test noise_floor_test \
    cpp/test/noise_floor_test.cpp
  native_test octaves_test \
    cpp/test/octaves_test.cpp
  native_test organ_test \
    cpp/test/organ_test.cpp
  native_test outdoors_test \
    cpp/test/outdoors_test.cpp
  native_test overtone_test \
    cpp/test/overtone_test.cpp
  native_test pad_follower_test \
    cpp/test/pad_follower_test.cpp
  native_test patina_test \
    cpp/test/patina_test.cpp
  native_test pedal_steel_test \
    cpp/test/pedal_steel_test.cpp
  native_test phaser_test \
    cpp/test/phaser_test.cpp
  native_test pitch_shifter_test \
    cpp/test/pitch_shifter_test.cpp
  native_test prepared_piano_test \
    cpp/test/prepared_piano_test.cpp
  native_test radio_test \
    cpp/test/radio_test.cpp
  native_test re_amp_test \
    cpp/test/re_amp_test.cpp
  native_test reverse_delay_test \
    cpp/test/reverse_delay_test.cpp
  native_test rewind_test \
    cpp/test/rewind_test.cpp
  native_test rotary_test \
    cpp/test/rotary_test.cpp
  native_test sampler_test \
    cpp/test/sampler_test.cpp
  native_test saturator_test \
    cpp/test/saturator_test.cpp
  native_test shaped_reverb_test \
    cpp/test/shaped_reverb_test.cpp
  native_test shimmer_test \
    cpp/test/shimmer_test.cpp
  native_test shortwave_test \
    cpp/test/shortwave_test.cpp
  native_test spectral_blur_test \
    cpp/test/spectral_blur_test.cpp
  native_test spring_reverb_test \
    cpp/test/spring_reverb_test.cpp
  native_test staircase_test \
    cpp/test/staircase_test.cpp
  native_test stereo_detune_test \
    cpp/test/stereo_detune_test.cpp
  native_test string_machine_test \
    cpp/test/string_machine_test.cpp
  native_test sustainer_test \
    cpp/test/sustainer_test.cpp
  native_test swarm_reverb_test \
    cpp/test/swarm_reverb_test.cpp
  native_test swell_test \
    cpp/test/swell_test.cpp
  native_test sympathetic_test \
    cpp/test/sympathetic_test.cpp \
    cpp/devices/stereo-widener/StereoWidener.cpp
  native_test tamer_test \
    cpp/test/tamer_test.cpp
  native_test tanpura_test \
    cpp/test/tanpura_test.cpp
  native_test tape_test \
    cpp/test/tape_test.cpp
  native_test tape_echo_test \
    cpp/test/tape_echo_test.cpp
  native_test tape_loop_test \
    cpp/test/tape_loop_test.cpp
  native_test tape_orchestra_test \
    cpp/test/tape_orchestra_test.cpp
  native_test thesis_test \
    cpp/test/thesis_test.cpp \
    cpp/devices/stereo-widener/StereoWidener.cpp
  native_test tine_piano_test \
    cpp/test/tine_piano_test.cpp
  native_test tremolo_test \
    cpp/test/tremolo_test.cpp
  native_test vintage_digital_test \
    cpp/test/vintage_digital_test.cpp
  native_test vinyl_test \
    cpp/test/vinyl_test.cpp
  native_test vowel_reverb_test \
    cpp/test/vowel_reverb_test.cpp
  native_test wavetable_test \
    cpp/test/wavetable_test.cpp
  native_test west_coast_test \
    cpp/test/west_coast_test.cpp
  native_test wind_harp_test \
    cpp/test/wind_harp_test.cpp
  native_test zither_test \
    cpp/test/zither_test.cpp
  native_test zone_sampler_test \
    cpp/test/zone_sampler_test.cpp
}
