// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Chord Harp, shared with
// src/dsp/devices/chord-harp.gen.ts:
//    0  strum: 0..150 ms, default 40
//    1  direction: 0 Up, 1 Down, 2 Up Down, 3 Random, default 0
//    2  span: 0 1 octave, 1 2 octaves, 2 3 octaves, 3 4 octaves, default 2
//    3  sustain: 0.2..8 s, default 3
//    4  tone: 0..1, default 0.5
//    5  pad: 0..1, default 0.3
//    6  spread: 0..1, default 0.6
//    7  volume: -48..6 dB, default -9

#pragma once

namespace livemix {
namespace chord_harp {

enum Param : int {
  kStrum = 0,
  kDirection = 1,
  kSpan = 2,
  kSustain = 3,
  kTone = 4,
  kPad = 5,
  kSpread = 6,
  kVolume = 7,
  kNumParams = 8,
};

inline constexpr float kParamMin[kNumParams] = {0.0f, 0.0f, 0.0f, 0.2f, 0.0f, 0.0f, 0.0f, -48.0f};
inline constexpr float kParamMax[kNumParams] = {150.0f, 3.0f, 3.0f, 8.0f, 1.0f, 1.0f, 1.0f, 6.0f};
inline constexpr float kParamDefault[kNumParams] = {40.0f, 0.0f, 2.0f, 3.0f, 0.5f, 0.3f, 0.6f, -9.0f};

}  // namespace chord_harp
}  // namespace livemix
