// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Pedal Steel, shared with
// src/dsp/devices/pedal-steel.gen.ts:
//    0  swell: 0..2 s, default 0.4
//    1  sustain: 2..40 s, default 14
//    2  glide: 20..800 ms, default 180
//    3  range: 0..12 st, default 2
//    4  vibrato: 0..40 ct, default 8
//    5  rate: 3..7 Hz, default 5
//    6  pick: 0..1, default 0.45
//    7  tone: 1500..6000 Hz, default 3200
//    8  volume: -48..6 dB, default -9

#pragma once

namespace livemix {
namespace pedal_steel {

enum Param : int {
  kSwell = 0,
  kSustain = 1,
  kGlide = 2,
  kRange = 3,
  kVibrato = 4,
  kRate = 5,
  kPick = 6,
  kTone = 7,
  kVolume = 8,
  kNumParams = 9,
};

inline constexpr float kParamMin[kNumParams] = {0.0f, 2.0f, 20.0f, 0.0f, 0.0f, 3.0f, 0.0f, 1500.0f, -48.0f};
inline constexpr float kParamMax[kNumParams] = {2.0f, 40.0f, 800.0f, 12.0f, 40.0f, 7.0f, 1.0f, 6000.0f, 6.0f};
inline constexpr float kParamDefault[kNumParams] = {0.4f, 14.0f, 180.0f, 2.0f, 8.0f, 5.0f, 0.45f, 3200.0f, -9.0f};

}  // namespace pedal_steel
}  // namespace livemix
