// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Octaves, shared with
// src/dsp/devices/octaves.gen.ts:
//    0  sub2: 0..1, default 0
//    1  sub1: 0..1, default 0.5
//    2  dry: 0..1, default 1
//    3  up1: 0..1, default 0.5
//    4  up2: 0..1, default 0
//    5  attack: 0..2 s, default 0
//    6  filter: 100..16000 Hz, default 16000
//    7  resonance: 0..1, default 0
//    8  detune: 0..1, default 0
//    9  spread: 0..1, default 0.3

#pragma once

namespace livemix {
namespace octaves {

enum Param : int {
  kSub2 = 0,
  kSub1 = 1,
  kDry = 2,
  kUp1 = 3,
  kUp2 = 4,
  kAttack = 5,
  kFilter = 6,
  kResonance = 7,
  kDetune = 8,
  kSpread = 9,
  kNumParams = 10,
};

inline constexpr float kParamMin[kNumParams] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 100.0f, 0.0f, 0.0f, 0.0f};
inline constexpr float kParamMax[kNumParams] = {1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 2.0f, 16000.0f, 1.0f, 1.0f, 1.0f};
inline constexpr float kParamDefault[kNumParams] = {0.0f, 0.5f, 1.0f, 0.5f, 0.0f, 0.0f, 16000.0f, 0.0f, 0.0f, 0.3f};

}  // namespace octaves
}  // namespace livemix
