// GENERATED by scripts/build-faust.sh from cpp/faust/fet-limiter.dsp. Do not edit.
// Ids follow the Faust UI declaration order, the numbering
// cpp/faust/common/faust_runtime.h uses for device_set_param.

import { type ParamSpec } from '../../../core/params'

export const FET_LIMITER_PARAMS = {
  inputGain: {
    id: 0,
    name: 'Input gain',
    min: 0,
    max: 40,
    default: 0,
    taper: 'linear',
    unit: 'dB',
  },
  outputGain: {
    id: 1,
    name: 'Output gain',
    min: -24,
    max: 24,
    default: 0,
    taper: 'linear',
    unit: 'dB',
  },
} as const satisfies Record<string, ParamSpec>

export type FetLimiterParamName = keyof typeof FET_LIMITER_PARAMS
