/**
 * `@kieranklaassen/live-mix` — engine core.
 *
 * Import-safe under SSR: nothing here reads `window` or constructs an
 * `AudioContext` at module load.
 *
 * @module live-mix
 */

export const LIVE_MIX_VERSION = '0.1.0'

export * from './core/clips'
export * from './core/automation'
export {
  isEditorDevice,
  isMeteredDevice,
  isNoteDevice,
  isObservableDevice,
  isParamTextDevice,
  isStatefulDevice,
  type Device,
  type DeviceChange,
  type DeviceChangeListener,
  type DeviceMeterSpec,
  type EditorDevice,
  type MeteredDevice,
  type NoteDevice,
  type ObservableDevice,
  type ParamTextDevice,
  type StatefulDevice,
} from './core/devices/Device'
export { Emitter, type Listener } from './core/events'
export {
  canonicalJson,
  isJsonObject,
  isJsonValue,
  sameJson,
  type JsonObject,
  type JsonValue,
} from './core/json'
export {
  clampParam,
  describeParams,
  denormalizeParam,
  normalizeParam,
  type ParamSpec,
  type ParamTaper,
} from './core/params'
export { ensureProcessor } from './core/worklet-loader'
export {
  createClock,
  startFloorSec,
  startLeadSec,
  type Clock,
  type ClockOptions,
  type IntervalId,
  type TimeoutId,
} from './core/clock'
export {
  OutputRouter,
  isIOSWebKit,
  type OutputMode,
  type OutputRouterOptions,
} from './core/output/OutputRouter'
export {
  Bus,
  LEVEL_RAMP_SECONDS,
  type BusChange,
  type BusChangeKind,
  type BusChangeListener,
  type BusOptions,
} from './core/buses/Bus'
export { MasterBus, type MasterBusOptions } from './core/buses/MasterBus'
export { Meter, type MeterOptions } from './core/analysis/Meter'
export {
  Engine,
  createEngine,
  type AddAudioTrackOptions,
  type AddStretchTrackOptions,
  type AddBusOptions,
  type AddDuckerOptions,
  type AddGroupOptions,
  type AddElementTrackOptions,
  type AddInstrumentTrackOptions,
  type AddLiveInputTrackOptions,
  type AddReturnTrackOptions,
  type AddWorkletDuckerOptions,
  type AlignLatencyOptions,
  type EngineChange,
  type EngineChangeListener,
  type EngineObjectKind,
  type EngineOptions,
  type IoLatency,
} from './core/Engine'
export { LiveInputTrack, type LiveInputTrackOptions } from './core/tracks/LiveInputTrack'
export { InstrumentTrack, type InstrumentTrackOptions } from './core/tracks/InstrumentTrack'
export { ReturnTrack, type ReturnTrackOptions } from './core/tracks/ReturnTrack'
export { SendList, type Send, type SendOptions, type SendTarget } from './core/tracks/Send'
export {
  ChannelStrip,
  DEFAULT_RIDE_LAYER,
  RIDE_ARRIVAL_TIME_CONSTANT,
  SoloInPlace,
  resolveInput,
  type ChannelStripOptions,
  type RampOptions,
  type RideOptions,
  type RoutableInput,
  type StripChange,
  type StripChangeKind,
  type StripChangeListener,
  type StripDestination,
  type StripHost,
  type StripShadow,
} from './core/tracks/ChannelStrip'
export { GroupTrack, type GroupTrackOptions } from './core/tracks/GroupTrack'
export {
  DUCK_DEPTH,
  DUCK_KEY_FFT_SIZE,
  DUCK_TIME_CONSTANT,
  Ducker,
  ENV_ATTACK_MS,
  ENV_GAIN_SCALE,
  ENV_POLL_MS,
  ENV_RELEASE_MS,
  createDucker,
  type DuckerOptions,
} from './core/devices/native/Ducker'
export { type DuckerMode, type SidechainDucker } from './core/devices/native/SidechainDucker'
export {
  DUCKER_BYPASS_RAMP_SECONDS,
  DUCKER_DEFAULT_WINDOW_SIZE,
  DUCKER_PARAMS,
  DUCKER_PROCESSOR_NAME,
  DUCKER_REPORT_HZ,
  DUCK_HOLD_MS,
  type DuckerHostMessage,
  type DuckerMessage,
  type DuckerParamName,
  type DuckerProcessorOptions,
} from './core/devices/native/ducker-abi'
export { DuckerKernel, type DuckerKernelOptions } from './core/devices/native/DuckerKernel'
export {
  WorkletDucker,
  type DuckerNodeFactory,
  type WorkletDuckerOptions,
} from './core/devices/native/WorkletDucker'
export {
  SampleStore,
  bytesOfBuffer,
  type KnownSample,
  type LoadedSample,
  type SampleEviction,
  type SampleEvictionListener,
  type SampleEvictionReason,
  type SampleSource,
  type SampleStoreListener,
  type SampleStoreMetrics,
  type SampleStoreOptions,
} from './core/tracks/SampleStore'
export {
  DEFAULT_RETAIN_GRACE_SECONDS,
  SampleRetainer,
  type RetainedTrack,
  type SampleRetainerOptions,
} from './core/tracks/SampleRetainer'
export {
  ElementSource,
  type ClipSource,
  type ElementSourceOptions,
} from './core/sources/ElementSource'
export {
  FOLLOW_DRIFT_SEEK,
  FOLLOW_MAX_SEEK_LEAD,
  FOLLOW_SEEK_TOLERANCE,
  followStep,
  type FollowingElement,
  type FollowStep,
  type FollowTarget,
} from './core/sources/follow-step'
export {
  ELEMENT_DRIFT_TOLERANCE_SECONDS,
  ElementTrack,
  type ElementTrackOptions,
  type ElementVoice,
  type ElementVoiceOptions,
} from './core/sources/ElementTrack'
export { ClipList, type ClipListListener } from './core/tracks/ClipList'
export {
  AudioTrack,
  CROSSFADE_SECONDS,
  DEFAULT_LOOKAHEAD_SECONDS,
  JOIN_EASE_SECONDS,
  MAX_CLIP_GAIN_DB,
  MIN_PLACED_GAIN_DB,
  PLACEMENT_GLIDE_SECONDS,
  PLACEMENT_RAMP_SECONDS,
  STEER_CROSSFADE_SECONDS,
  STOP_FADE_SECONDS,
  placedTrimGain,
  trimGain,
  type AudioTrackOptions,
  type ClipVoice,
  type ClipVoiceOptions,
  type VoicePlace,
  type VoicePlacement,
} from './core/tracks/AudioTrack'
export {
  DEFAULT_SPACE,
  GRAIN_ECHOES_PER_SEC,
  MAX_SPACE_DRIFT_CENTS,
  MAX_SPACE_DRIVE_DB,
  MAX_SPACE_LEVEL_DB,
  MIN_SPACE_LEVEL_DB,
  SPACE_DRIVE_LEVEL_DB,
  SPACE_LEVEL_HIGH_HZ,
  SPACE_LEVEL_LOW_HZ,
  generateSpaceImpulse,
  grainEchoesPerSec,
  resolveSpace,
  sameSpaceImpulse,
  spaceColour,
  spaceDrift,
  spaceDriveGains,
  spaceImpulseChannel,
  type SpaceColour,
  type SpaceOptions,
} from './core/tracks/space'
export {
  MIN_SPACE_TILT,
  SPACE_TILT_RETURN_DB_PER_SECOND,
  SpaceRoom,
  type SpaceRoomHost,
  type SpaceRoomSettings,
} from './core/tracks/SpaceRoom'
export {
  SharedSpaces,
  SpaceFeed,
  stripOnlySetsLevel,
  type SharedSpacesOptions,
} from './core/tracks/SharedSpace'
export * from './core/transport'
export {
  DEFAULT_BEATS_PER_BAR,
  DEFAULT_BPM,
  TempoMap,
  type BarBeat,
  type QuantizeGrid,
  type TempoSegment,
} from './core/time/TempoMap'
export {
  camelotCompatible,
  camelotDistance,
  camelotNumber,
  compatibleCamelotNumbers,
  formatCamelot,
  parseCamelot,
  semitonesBetween,
  transposeCamelot,
  type CamelotCompatibilityOptions,
  type CamelotKey,
  type CamelotLetter,
} from './core/music/camelot'
export {
  DEFAULT_MAX_SEMITONES,
  keyMatch,
  rankByKeyMatch,
  type KeyMatch,
  type KeyMatchOptions,
} from './core/music/keyMatch'
export {
  INTENSITY_LABELS,
  INTENSITY_LADDER,
  MAX_INTENSITY,
  MIN_INTENSITY,
  STEER_DIRECTIONS,
  clampIntensity,
  rankTonal,
  resolveReplacementTracks,
  targetIntensity,
  tonalPreference,
  type IntensityDirection,
  type IntensityTrack,
  type ResolveReplacementsOptions,
  type SteerDirection,
  type TonalDirection,
} from './core/music/intensity'
export {
  StretchSource,
  semitonesToRate,
  warpRateAt,
  warpSegments,
  warpSourceSecAt,
  type StretchNode,
  type StretchNodeFactory,
  type StretchPlayOptions,
  type StretchScheduleChange,
  type StretchSourceOptions,
  type WarpMarker,
  type WarpOptions,
  type WarpSegment,
} from './core/sources/StretchSource'
export {
  DEFAULT_STRETCH_PRELOAD_SECONDS,
  StretchTrack,
  entryOffset,
  segmentsFrom,
  warpClipSecAt,
  wrapIntoLoop,
  type StretchTrackOptions,
  type StretchVoice,
} from './core/tracks/StretchTrack'
export {
  audioBufferToWav,
  decodeWav,
  deinterleave,
  encodeWav,
  interleave,
  planarFromAudioBuffer,
  readWavInfo,
  wavBlob,
  type PlanarAudio,
  type WavBitDepth,
  type WavEncodeOptions,
  type WavInfo,
} from './core/render/encode'
export {
  maxAbsDifference,
  renderOffline,
  renderStems,
  scheduleAhead,
  type OfflineContextFactory,
  type OfflineContextLike,
  type RenderBuild,
  type RenderBuildInfo,
  type RenderOptions,
  type RenderResult,
  type ScheduleAheadOptions,
  type StemsOptions,
} from './core/render/OfflineRenderer'
export {
  RENDER_QUANTUM_FRAMES,
  canHoldRender,
  holdFrame,
  holdRenderAt,
  type HoldableContext,
} from './core/render/hold'
export {
  MediaStreamRecorder,
  Recorder,
  WorkletRecorder,
  createRecorder,
  defaultRecorderProcessorUrl,
  type MediaRecorderLike,
  type MediaRecorderOptions,
  type MediaRecording,
  type RecordSource,
  type Recording,
  type RecorderNodeFactory,
  type RecorderOptions,
  type WorkletRecorderOptions,
  type WorkletRecording,
} from './core/render/Recorder'
export {
  DEFAULT_RECORDER_CHUNK_FRAMES,
  RECORDER_PROCESSOR_NAME,
  type RecorderHostMessage,
  type RecorderMessage,
  type RecorderProcessorOptions,
} from './core/render/recorder-protocol'
export {
  // Node devices
  COMPRESSOR_DESCRIPTOR,
  COMPRESSOR_DEVICE,
  COMPRESSOR_LOOKAHEAD_SECONDS,
  COMPRESSOR_PARAMS,
  Compressor,
  DELAY_DESCRIPTOR,
  DELAY_DEVICE,
  DELAY_MAX_SECONDS,
  DELAY_PARAMS,
  EQ3_DESCRIPTOR,
  EQ3_DEVICE,
  EQ3_PARAMS,
  FILTER_DESCRIPTOR,
  FILTER_DEVICE,
  FILTER_PARAMS,
  FILTER_TYPES,
  FLAT_CUT_Q_DB,
  NODE_DEVICES,
  NODE_DEVICE_RAMP_SECONDS,
  NodeDevice,
  PARAMETRIC_EQ_BANDS,
  PARAMETRIC_EQ_DESCRIPTOR,
  PARAMETRIC_EQ_DEVICE,
  PARAMETRIC_EQ_PARAMS,
  UTILITY_DESCRIPTOR,
  UTILITY_DEVICE,
  UTILITY_PARAMS,
  compressorLookaheadSamples,
  compressorNodeCurve,
  compressorNodeMakeupDb,
  createCompressor,
  createDelay,
  createEq3,
  createFilter,
  createParametricEq,
  createUtility,
  cutQDb,
  dbToGain,
  defineNodeDevice,
  filterTypeAt,
  filterTypeIndex,
  gainToDb,
  isCutFilter,
  isUtility,
  utilityGain,
  utilityIsLevelOnly,
  type CompressorParamName,
  type Delay,
  type DelayParamName,
  type Eq3,
  type Eq3ParamName,
  type Filter,
  type FilterParamName,
  type FilterType,
  type NodeDeviceDefinition,
  type NodeDeviceGraph,
  type NodeDeviceOptions,
  type ParamApplier,
  type ParamRamp,
  type ParamScale,
  type ParametricEq,
  type ParametricEqParamName,
  type Utility,
  type UtilityParamName,
  // Registry and presets
  DEVICE_CATEGORIES,
  DeviceRegistry,
  PRESET_FORMAT_VERSION,
  applyPreset,
  capturePreset,
  defaultPreset,
  hasPreset,
  devices,
  isPreset,
  listPresets,
  parsePreset,
  presetParams,
  resolvePreset,
  serializePreset,
  validateDescriptor,
  CONVOLVER_REVERB_DESCRIPTOR,
  CONVOLVER_REVERB_PARAMS,
  ConvolverReverb,
  REVERB_DECAY_SECONDS,
  REVERB_WET_LEVEL,
  createConvolverReverb,
  generateHallImpulse,
  type ConvolverReverbOptions,
  type ApplyPresetResult,
  type DeviceCategory,
  type DeviceCreateOptions,
  type DeviceCreateRequest,
  type DeviceDescriptor,
  type DeviceFactory,
  type DeviceFilter,
  type DeviceKind,
  type DeviceRegistryEvent,
  type DeviceRegistryListener,
  type Preset,
  type PresetSource,
  type PresetTable,
  type RegisterOptions,
  type SerializedPreset,
  // Racks, macros and delay compensation (U34)
  ALIGNMENT_DELAY_ID,
  AlignmentDelay,
  Chain,
  DEFAULT_MACRO_COUNT,
  MACRO_CURVES,
  MAX_MACRO_COUNT,
  PDC_MAX_DELAY_SECONDS,
  RACK_DESCRIPTOR,
  RACK_ID,
  RACK_MIX_PARAM,
  RACK_PARAMS,
  RACK_PRESET_FORMAT_VERSION,
  RACK_VERSION,
  Rack,
  RackMacro,
  buildLatencyReport,
  captureRackPreset,
  chainCompensationSamples,
  chainLatencySamples,
  createMacroMapping,
  createRack,
  createRackFromPreset,
  definitionLatencySamples,
  deviceLatencySamples,
  isAlignmentDelay,
  isRackPreset,
  macroCurve,
  macroCurveInverse,
  macroIndexOf,
  macroMappedValue,
  macroParamName,
  macroPositionFor,
  parseRackPreset,
  rackParams,
  rampParamTo,
  secondsToSamples,
  serializeRackPreset,
  taperPosition,
  taperValue,
  type AlignmentDelayOptions,
  type CaptureRackPresetOptions,
  type ChainOptions,
  type CreateRackFromPresetOptions,
  type DeviceLatency,
  type LatencyPathInput,
  type LatencyPathKind,
  type LatencyReport,
  type LatencySource,
  type MacroCurve,
  type MacroMapping,
  type MacroMappingOptions,
  type MacroMappingShape,
  type MapMacroOptions,
  type PathLatency,
  type RackChainPreset,
  type RackCreateOptions,
  type RackDevicePreset,
  type RackMacroMappingPreset,
  type RackMacroPreset,
  type RackOptions,
  type RackPreset,
  type RemoveChainOptions,
  type SerializedRackPreset,
  type ZoneRange,
} from './core/devices'
// Patches: an instrument with its effects, or an effect chain
export {
  capturePatch,
  capturePatchDevice,
  createPatchDevice,
  createPatchEffects,
  isInstrumentPatch,
  isPatch,
  patchDeviceParams,
  patchDevices,
  replaceInserts,
  validatePatch,
  type CapturePatchOptions,
  type Patch,
  type PatchCategory,
  type PatchCreateOptions,
  type PatchDevice,
  type PatchInsertHost,
  type PatchIssue,
  type ReplaceInsertsOptions,
} from './core/devices'
export {
  ABSOLUTE_GATE_LUFS,
  Biquad,
  GATING_HOP_SECONDS,
  LOUDNESS_OFFSET_LU,
  LoudnessAnalyzer,
  MOMENTARY_WINDOW_SECONDS,
  RELATIVE_GATE_LU,
  SHORT_TERM_WINDOW_SECONDS,
  TRUE_PEAK_FIR_PHASES,
  TRUE_PEAK_FIR_TAPS,
  TruePeakDetector,
  kWeightingCoefficients,
  loudnessFromMeanSquare,
  silentReading,
  truePeakOversampling,
  type BiquadCoefficients,
  type KWeighting,
  type MeterReading,
} from './core/analysis/loudness'
export {
  DEFAULT_ONSET_HOP_SECONDS,
  DEFAULT_ONSET_MIN_GAP_SECONDS,
  MAX_TEMPO_BPM,
  MIN_TEMPO_BPM,
  MIN_TEMPO_ONSETS,
  detectOnsets,
  estimateTempo,
  type OnsetOptions,
  type TempoEstimate,
} from './core/analysis/onsets'
export { analyzeSound, type SoundAnalysis, type SoundKind } from './core/analysis/sound-kind'
export {
  DEFAULT_METER_INTERVAL_MS,
  MAX_METER_INTERVAL_MS,
  METER_PROCESSOR_NAME,
  MIN_METER_INTERVAL_MS,
  clampMeterInterval,
  type MeterHostMessage,
  type MeterMessage,
  type MeterProcessorOptions,
} from './core/analysis/meter-protocol'
export {
  LufsMeter,
  defaultMeterProcessorUrl,
  type LufsMeterOptions,
  type MeterListener,
  type MeterNodeFactory,
} from './core/analysis/LufsMeter'
export { MasterLimiter } from './core/buses/MasterLimiter'
export { type LimiterFactory } from './core/buses/MasterBus'
export {
  EngineStats,
  type EngineGlitchSource,
  type EngineLoadSource,
  type EngineStatsListener,
  type EngineStatsOptions,
  type EngineStatsSnapshot,
  type RenderCapacityLike,
  type RenderCapacityUpdate,
} from './core/stats'
export {
  LOAD_CELL_BUSY,
  LoadProbe,
  defaultLoadSamplerUrl,
  loadCells,
  wasmMemoryBytes,
  type DeviceLoad,
  type LoadClaim,
  type LoadProbeOptions,
  type LoadReading,
  type LoadSampler,
  type LoadSamplerFactory,
  type LoadSamplerInit,
  type LoadSamplerReport,
  type LoadSlot,
} from './core/load'
export * from './score'
export * from './core/session'
export * from './core/perform'
export * from './core/control'
export * from './agent'
export {
  DEFAULT_ARBITRATION_POLICY,
  DEFAULT_DEFER_TTL_MS,
  DEFAULT_HOLD_MS,
  HoldTable,
  WRITER_KINDS,
  decide,
  formatPolicyTable,
  policyTable,
  resolvePolicy,
  sameOwner,
  type ArbitrationDecision,
  type ArbitrationPolicy,
  type ArbitrationPolicyOptions,
  type Hold,
  type HoldOwner,
  type HoldTableOptions,
  type Lock,
  type PolicyRow,
  type WriterKind,
} from './core/params/arbitration'
