// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Acid Bass, shared with
// src/dsp/devices/acid-bass.gen.ts:
//    0  wave: 0 Saw, 1 Square, default 0
//    1  cutoff: 40..5000 Hz, default 280
//    2  resonance: 0..1, default 0.7
//    3  envMod: 0..1, default 0.55
//    4  decay: 0.05..10 s, default 0.35
//    5  accent: 0..1, default 0.6
//    6  slide: 0.01..1 s, default 0.12
//    7  sustain: 0.1..20 s, default 3
//    8  drive: 0..1, default 0.134
//    9  volume: -48..6 dB, default -9

#pragma once

namespace livemix {
namespace acid_bass {

enum Param : int {
  kWave = 0,
  kCutoff = 1,
  kResonance = 2,
  kEnvMod = 3,
  kDecay = 4,
  kAccent = 5,
  kSlide = 6,
  kSustain = 7,
  kDrive = 8,
  kVolume = 9,
  kNumParams = 10,
};

inline constexpr float kParamMin[kNumParams] = {0.0f, 40.0f, 0.0f, 0.0f, 0.05f, 0.0f, 0.01f, 0.1f, 0.0f, -48.0f};
inline constexpr float kParamMax[kNumParams] = {1.0f, 5000.0f, 1.0f, 1.0f, 10.0f, 1.0f, 1.0f, 20.0f, 1.0f, 6.0f};
inline constexpr float kParamDefault[kNumParams] = {0.0f, 280.0f, 0.7f, 0.55f, 0.35f, 0.6f, 0.12f, 3.0f, 0.134f, -9.0f};

}  // namespace acid_bass
}  // namespace livemix
