// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Ladder Bass, shared with
// src/dsp/devices/ladder-bass.gen.ts:
//    0  wave: 0..1, default 0
//    1  beat: 0..25 ct, default 6
//    2  sub: 0..1, default 0.3
//    3  cutoff: 30..12000 Hz, default 500
//    4  emphasis: 0..1, default 0.3
//    5  contour: 0..1, default 0.6
//    6  decay: 0.03..10 s, default 0.6
//    7  drive: 0..1, default 0.3
//    8  glide: 0..1 s, default 0.08
//    9  volume: -48..6 dB, default -9

#pragma once

namespace livemix {
namespace ladder_bass {

enum Param : int {
  kWave = 0,
  kBeat = 1,
  kSub = 2,
  kCutoff = 3,
  kEmphasis = 4,
  kContour = 5,
  kDecay = 6,
  kDrive = 7,
  kGlide = 8,
  kVolume = 9,
  kNumParams = 10,
};

inline constexpr float kParamMin[kNumParams] = {0.0f, 0.0f, 0.0f, 30.0f, 0.0f, 0.0f, 0.03f, 0.0f, 0.0f, -48.0f};
inline constexpr float kParamMax[kNumParams] = {1.0f, 25.0f, 1.0f, 12000.0f, 1.0f, 1.0f, 10.0f, 1.0f, 1.0f, 6.0f};
inline constexpr float kParamDefault[kNumParams] = {0.0f, 6.0f, 0.3f, 500.0f, 0.3f, 0.6f, 0.6f, 0.3f, 0.08f, -9.0f};

}  // namespace ladder_bass
}  // namespace livemix
