// Ashram Harp and Organ: an organ pushed through a turning speaker, a harp
// over strings that ring on a drone, a string section that swells and sways,
// voices in a prayer hall. Its chains turn, ring and sing; they are warm and
// on a plate more often than not; nothing is cold, broken or digital.

import { type PackPalette } from './types'

// The turning speaker as it turns: slow or fast, never parked.
const ROTOR = [
  'rotary:Chorale',
  'rotary:Tremolo',
  'rotary:Growl',
  'rotary:Across the room',
  'rotary:Heavy rotors',
  'rotary:Guitar swirl',
  'rotary:Faint motion',
  'rotary:Soft blend',
  'rotary:Mono cabinet',
  'rotary:Dark drum',
  'rotary:Bright horn',
  'rotary:Far shimmer',
  'rotary:Close pulse',
  'rotary:Slow burn',
] as const

export const PALETTE: PackPalette = {
  pack: 'ashram',
  groups: { space: 28, echo: 10, tape: 9, motion: 24, texture: 14, pitch: 9, master: 6 },
  traits: {
    warm: 1.8,
    wide: 1.25,
    long: 1.2,
    cold: 0.25,
    strange: 0.25,
    worn: 0.5,
    noisy: 0.4,
    narrow: 0.6,
    backwards: 0.2,
    heavy: 0.7,
    frozen: 0.7,
  },
  devices: {
    rotary: 3.2,
    sympathetic: 2.6,
    'plate-reverb': 4.5,
    'vowel-reverb': 2,
    'pad-follower': 2,
    phaser: 2.4,
    octaves: 1.6,
    'analog-drive': 1.6,
    'hall-reverb': 1.8,
    swell: 1.1,
    're-amp': 1.3,
    'tape-echo': 2.4,
    'analog-delay': 1.2,
    sustainer: 2,
    chorus: 1.2,
    tremolo: 1.2,
    lattice: 0.5,
    'pitch-shifter': 1.2,
    'shaped-reverb': 0.5,
    'spectral-blur': 1.3,
    expanse: 0.8,
    'tape-loop': 0.45,
    shimmer: 0.6,
    cascade: 0.15,
    flanger: 0.05,
    'auto-filter': 0.5,
    'echo-memory': 0.3,
    vinyl: 0.6,
    'swarm-reverb': 0.04,
    'grain-cloud': 0.25,
    'grain-delay': 0.15,
    'spectral-drifter': 0.25,
    'micro-looper': 0.25,
    'noise-floor': 0.5,
    'half-speed': 0.03,
    'reverse-delay': 0.03,
    'freq-shifter': 0.03,
    'vintage-digital': 0,
    radio: 0,
    glitch: 0,
    'low-bitrate': 0,
  },
  voices: {
    // A flanger in all but its device: weighed as this pack weighs flangers.
    'tremolo:Drifting comb': 0.05,
    'rotary:Chorale': 1.6,
    'rotary:Slow burn': 1.8,
    'rotary:Growl': 1.5,
    'sympathetic:Sitar drone': 2,
    'sympathetic:Centre drone': 1.6,
    'sympathetic:Glass harp': 1.4,
    'lattice:Pentatonic harp': 3,
    'lattice:Two note drone': 3,
    'octaves:Organ': 1.6,
    'octaves:Cathedral': 1.4,
    'vowel-reverb:Humming': 1.5,
    'plate-reverb:Long plate': 1.4,
    'rotary:Stopped horn': 0,
    'rotary:Parked growl': 0.2,
    're-amp:Bedside radio': 0.2,
    'pitch-shifter:Rising steps': 0.4,
    'pitch-shifter:Falling steps': 0.4,
    'pitch-shifter:Slow cloud': 0.3,
    'pitch-shifter:High sparks': 0.3,
    'pitch-shifter:Shimmer': 0.4,
    'phaser:Saw riser': 0.5,
    'lattice:Rough high splinters': 0,
    'micro-looper:Sampler grit': 0.2,
    'micro-looper:Lo-fi quarter': 0.2,
    'expanse:Thin air': 0.3,
    'expanse:Narrow tunnel': 0.3,
    'stereo-widener:Mono': 0,
    'fdn-reverb:Pulsing gate': 0.05,
    'shaped-reverb:Gated': 0.1,
    'shaped-reverb:Gate steps': 0.1,
    'shaped-reverb:Late wall': 0.1,
    'ambient-eq:Thin': 0.2,
    'auto-filter:Glacial low-pass': 0.3,
    'patina:Muffled sampler': 0.1,
    'patina:Early sampler': 0.1,
    'lattice:Crystal cascade': 0.4,
    'lattice:Sinking cascade': 0.4,
    'noise-floor:Wall of hiss': 0.2,
    'noise-floor:Radio static': 0.1,
    'noise-floor:Static notes': 0.1,
    'noise-floor:Old record': 2,
    'noise-floor:Amp left on': 1.5,
    'stereo-widener:Narrow': 0.3,
    'fet-limiter:Flattened': 0,
    'fet-limiter:Squash': 0,
    'tremolo:Chopper': 0,
    'tremolo:On and off': 0,
    'phaser:Random steps': 0,
    'ambient-comp:Pump': 0,
  },
  recipes: {
    'drive-motion': 2,
    'drive-motion-hall': 2,
    'motion-hall': 1.5,
    'motion-halo': 1.5,
    'pulse-hall': 1.3,
    'hold-motion': 1.5,
    'hold-motion-hall': 1.5,
    'halo-hall': 1.6,
    'swell-halo': 1.3,
    'tone-halo': 1.3,
    'room-halo': 1.3,
    'swell-hall': 1.3,
    'drive-hall': 1.4,
    'hold-hall': 1.4,
    'hold-halo': 1.4,
    'swell-hold': 1.5,
    'pitch-motion': 1.6,
    'pitch-hall': 1.3,
    'pitch-halo': 1.2,
    'motion-echo': 1.4,
    'drive-echo': 1.3,
    'echo-hall': 1.2,
    'pulse-echo': 0.7,
    'hall-tone': 0.6,
    'tone-hall': 0.7,
    'motion-tone': 0.6,
    'echo-tone': 0.6,
    'tone-wear': 0.7,
    'wear-tone': 0.7,
    'echo-echo': 0.5,
    'loop-hall': 0.3,
    'loop-room': 0.15,
    'tone-loop': 0.5,
    'loop-echo': 0.15,
    'loop-tone-hall': 0.3,
    'loop-wear': 0.2,
    'loop-wear-hall': 0.2,
    'wear-hiss': 0.2,
    'wear-hiss-hall': 0.4,
    'drive-hiss': 0.3,
    'grain-hall': 0.2,
    'grain-room': 0.15,
    'grain-echo': 0.2,
    'grain-wear': 0.1,
    'grain-tone': 0.1,
    'drive-grain': 0.2,
    'swell-grain-hall': 0.15,
    'pitch-grain': 0.4,
    'pitch-wear': 0.6,
  },
  own: [
    {
      // The organ: an amplifier pushed warm, the speaker turning, a plate behind it.
      id: 'ashram-driven-rotor-plate',
      category: 'motion',
      lead: 1,
      count: 6,
      slots: [
        {
          role: 'drive',
          devices: ['analog-drive', 'saturator', 'patina', 're-amp'],
          any: ['warm'],
          not: ['worn', 'strange', 'far'],
        },
        { presets: ROTOR },
        {
          role: 'hall',
          devices: ['plate-reverb', 'hall-reverb', 'spring-reverb'],
          not: ['heavy', 'strange', 'cold'],
        },
      ],
    },
    {
      // The harp: strings that ring on in sympathy with what is played, in a hall.
      id: 'ashram-harp-over-strings',
      category: 'space',
      lead: 0,
      count: 5,
      slots: [
        { role: 'halo', devices: ['sympathetic'], not: ['heavy'] },
        {
          role: 'hall',
          devices: ['plate-reverb', 'hall-reverb', 'fdn-reverb', 'ether-reverb', 'expanse'],
          not: ['heavy', 'cold', 'strange', 'unsteady'],
        },
      ],
    },
    {
      // The drone: ringing strings sent round slowly, so the buzz circles the room.
      id: 'ashram-drone-sent-round',
      category: 'motion',
      lead: 0,
      count: 4,
      slots: [
        { role: 'halo', devices: ['sympathetic'], not: ['heavy', 'short'] },
        { role: 'motion', devices: ['rotary', 'phaser', 'chorus'], not: ['strange', 'cold'] },
      ],
    },
    {
      // The string section: bowed in, held behind the playing, left in a long plate.
      id: 'ashram-bowed-section',
      category: 'texture',
      lead: 1,
      count: 5,
      slots: [
        { role: 'swell', devices: ['swell', 'ambient-comp', 'tremolo'] },
        { role: 'hold', devices: ['pad-follower'], not: ['heavy', 'cold'] },
        {
          role: 'hall',
          devices: ['plate-reverb', 'hall-reverb', 'fdn-reverb'],
          not: ['heavy', 'cold'],
        },
      ],
    },
    {
      // The organ's stops: octaves pulled out over each note, then the speaker turning.
      id: 'ashram-stops-in-the-rotor',
      category: 'pitch',
      lead: 0,
      count: 4,
      slots: [
        { role: 'pitch', devices: ['octaves'], not: ['cold', 'strange', 'heavy'] },
        { presets: ROTOR },
      ],
    },
    {
      // The evening's singing as it was kept: a warm home tape, voices in the room's tail.
      id: 'ashram-voices-on-home-tape',
      category: 'tape',
      lead: 1,
      count: 4,
      slots: [
        {
          role: 'wear',
          devices: ['tape', 'patina', 'vinyl'],
          any: ['warm'],
          not: ['strange'],
        },
        { role: 'halo', devices: ['vowel-reverb'], not: ['heavy'] },
      ],
    },
  ],
  heads: [
    'Saffron',
    'Marigold',
    'Incense',
    'Sandalwood',
    'Canyon-road',
    'Veranda',
    'Prayer-hour',
    'Lamp-lit',
    'Brass-lamp',
    'Barefoot',
    'Devotional',
    'Sunday',
    'Dusk',
    'Daybreak',
    'Hillside',
    'Chaparral',
    'Sagebrush',
    'Jasmine',
    'Lotus-pond',
    'Garland',
    'Camphor',
    'Doorstep',
    'Courtyard',
    'Rosewood',
    'Gourd',
    'Sundown',
    'Evening',
    'After-hours',
    'Last-set',
    'Back-room',
    'Late-set',
    'Foothill',
    'Live-oak',
    'Dry-creek',
    'Coastal',
    'Orange-grove',
    'Sycamore',
    'Shrine',
    'Altar',
    'Bare-floor',
    'Cross-legged',
    'Satsang',
    'Ochre',
    'Turmeric',
    'Hilltop',
    'Silk',
    'Teak',
    'Rose-petal',
    'Ghee-lamp',
    'Up-canyon',
    'Wood-smoke',
    'Stone-step',
    'Rose-water',
    'Kneeling',
    'Pilgrim',
    'Oil-lamp',
    'Dry-season',
    'Bluff-top',
    'Twilight',
    'Evening-raga',
    { word: 'Swaying', for: ['unsteady'] },
    { word: 'Unhurried', for: ['slow'] },
    { word: 'Sun-warmed', for: ['warm'] },
    { word: 'Dim-lamp', for: ['dark'] },
    { word: 'Noon-bright', for: ['bright'] },
    { word: 'Open-air', for: ['wide'] },
    { word: 'Deep-pedal', for: ['low'] },
    { word: 'Top-octave', for: ['high'] },
    { word: 'Far-ridge', for: ['far'] },
    { word: 'Half-heard', for: ['far'] },
    { word: 'Home-taped', for: ['worn', 'noisy'] },
    { word: 'Unbroken', for: ['frozen'] },
  ],
  tails: [
    'up the canyon',
    'by the lamp',
    'in saffron',
    'after prayers',
    'at the shrine',
    'before dawn',
    'at sundown',
    'in incense',
    'for the altar',
    'in marigolds',
    'under oaks',
    'in dry hills',
    'by the creek',
    'on the hill',
    'for evening',
    'between sets',
    'in the grove',
    'with garlands',
    'in sandalwood',
    'in sage',
    'at the gate',
    { word: 'in no hurry', for: ['slow'] },
    { word: 'till daybreak', for: ['long', 'frozen'] },
    { word: 'pitched low', for: ['low'] },
    { word: 'on home tape', for: ['worn', 'noisy'] },
  ],
}
