// Old Broadcast Hall: a damped upright, a chorus polysynth and tines, close
// to the microphone, through a tape echo, a reel and real rooms: a speaker in
// a bare chamber, a plate, a spring. Its chains are warm, close and handmade:
// repeats off tape heads, a slow chorus, a little valve and console, wooden
// rooms. Nothing is glassy, broken or digital, and the grain is left alone.

import { type PackPalette } from './types'

export const PALETTE: PackPalette = {
  pack: 'broadcast-hall',
  groups: { space: 22, echo: 24, tape: 21, motion: 13, texture: 6, pitch: 8, master: 6 },
  traits: {
    warm: 1.7,
    dark: 1.25,
    short: 1.2,
    faint: 1.1,
    bright: 0.75,
    cold: 0.3,
    strange: 0.08,
    heavy: 0.5,
    high: 0.6,
    frozen: 0.5,
    far: 0.85,
    worn: 0.6,
    backwards: 0.5,
  },
  devices: {
    'tape-echo': 3,
    chorus: 3,
    're-amp': 2.2,
    tape: 2.2,
    'plate-reverb': 2,
    'spring-reverb': 2,
    'hall-reverb': 1.6,
    'tape-loop': 1.6,
    'analog-drive': 1.5,
    sympathetic: 2.2,
    'analog-delay': 1.3,
    tremolo: 1.3,
    'noise-floor': 1.5,
    octaves: 1.4,
    'half-speed': 1.2,
    'ambient-comp': 1.2,
    rotary: 1.1,
    patina: 1.1,
    saturator: 1.1,
    'pad-follower': 0.9,
    'ether-reverb': 0.8,
    sustainer: 0.8,
    'auto-filter': 0.7,
    'echo-memory': 0.6,
    'micro-looper': 0.6,
    'reverse-delay': 0.2,
    'shaped-reverb': 0.25,
    expanse: 0.5,
    'pitch-shifter': 0.2,
    'spectral-blur': 0.5,
    swell: 0.2,
    flanger: 0.12,
    'vowel-reverb': 0.1,
    radio: 0.03,
    'grain-cloud': 0.03,
    'bloom-reverb': 0.05,
    'grain-delay': 0.04,
    shimmer: 0.03,
    'swarm-reverb': 0.02,
    cascade: 0.05,
    'spectral-drifter': 0.05,
    vinyl: 0,
    'freq-shifter': 0,
    'vintage-digital': 0,
    lattice: 0,
    glitch: 0,
    'low-bitrate': 0,
  },
  voices: {
    'tape-echo:Three heads': 2,
    'tape-echo:Dotted bounce': 2,
    'tape-echo:Warm repeats': 1.5,
    'chorus:Classic chorus': 1.5,
    'chorus:Lush ensemble': 1.5,
    're-amp:Just the room': 1.6,
    're-amp:Far end of the hall': 1.6,
    'tape:Quarter inch': 1.3,
    'patina:Quarter inch reel': 1.2,
    'tape-loop:Two decks': 2,
    'sympathetic:Piano pedal': 2,
    'noise-floor:Close mic': 2.5,
    'noise-floor:Empty room': 2,
    'noise-floor:Amp left on': 2,
    'noise-floor:Mains hum': 1.5,
    'noise-floor:Wall of hiss': 0.3,
    'noise-floor:Old record': 0.3,
    'noise-floor:Gap crackle': 0.3,
    'noise-floor:Static notes': 0.4,
    'noise-floor:Radio static': 0.5,
    'analog-drive:Console': 1.5,
    'analog-drive:Hot channel': 1.4,
    'patina:Eight bit': 0,
    'patina:Early sampler': 0,
    'patina:Muffled sampler': 0,
    'patina:Falling apart': 0.1,
    'tape:Chewed cassette': 0.1,
    'tape:Cassette four-track': 0.02,
    'tape:Old dictation': 0.02,
    'tape:Warm thump': 0.03,
    'tape:Under a blanket': 0.03,
    'tape:Crumbling oxide': 0.15,
    'tape:Worn thin': 0.4,
    'tape-loop:Worn out': 0.4,
    'tape-echo:Worn tape': 0.35,
    'patina:Worn cassette': 0.03,
    'patina:Dusty record': 0,
    'patina:Scratched record': 0,
    'patina:Distant station': 0.15,
    'patina:Shortwave': 0.15,
    'patina:Valve fuzz': 0.1,
    're-amp:Stack flat out': 0.25,
    're-amp:Warm stack': 0.25,
    're-amp:Dark and woolly': 0.25,
    're-amp:Speaker on the edge': 0.5,
    'analog-drive:Dark fuzz': 0.1,
    'analog-drive:Iron melt': 0.1,
    'phaser:Still formant': 0.4,
    'auto-filter:Soft bloom': 0.6,
    'auto-filter:Phone line': 0.3,
    'fet-limiter:Drive': 0.5,
    'ambient-limiter:Pinned': 0.4,
    'phaser:Glacial sweep': 0.3,
    'pad-follower:Glassy': 0.2,
    'pad-follower:High mist': 0.2,
    'spring-reverb:Single slack coil': 0.2,
    'spring-reverb:Slack and strange': 0.2,
    'ambient-comp:Pump': 0.2,
    'ambient-comp:Dense pad': 0.4,
    'analog-drive:Crushed': 0.7,
    'saturator:Sustain bed': 0.4,
    'saturator:Lo-fi': 0.1,
    'shaped-reverb:Gated': 0.3,
    'shaped-reverb:Gate steps': 0.2,
    'radio:Clean transistor': 0.3,
    'expanse:Event horizon': 0.2,
    'tremolo:Chopper': 0.1,
    'tremolo:On and off': 0.1,
    'fet-limiter:Squash': 0.1,
    'fet-limiter:Flattened': 0.1,
    'micro-looper:Lo-fi quarter': 0,
    'micro-looper:Sampler grit': 0,
    'saturator:Fuzz pedal': 0.1,
    'saturator:Wavefold lead': 0.1,
    'saturator:Folded glass': 0.15,
    'saturator:Blown speaker': 0,
    'stereo-detune:Seasick': 0,
  },
  recipes: {
    'drive-room': 1.6,
    'room-hall': 1.5,
    'drive-hall': 1.4,
    'tone-room-hall': 1.3,
    'swell-hall': 0.3,
    'swell-halo': 0.3,
    'swell-halo-hall': 0.05,
    'room-halo': 1.3,
    'tone-halo': 1.2,
    'echo-room': 1.5,
    'drive-echo': 1.5,
    'motion-echo': 1.5,
    'drive-echo-hall': 1.5,
    'echo-hall': 1.2,
    'echo-halo': 0.3,
    'swell-echo': 0.15,
    'wear-room': 1.5,
    'drive-wear-room': 1.6,
    'wear-echo': 1.5,
    'drive-wear': 1.4,
    'tone-wear-echo': 1.3,
    'drive-hiss': 0.3,
    'wear-hiss': 1.2,
    'wear-hiss-hall': 1.2,
    'motion-room': 1.5,
    'motion-echo-hall': 1.6,
    'drive-motion': 1.3,
    'pulse-echo': 0.9,
    'pulse-hall': 0.4,
    'motion-halo': 0.5,
    'swell-motion': 0.2,
    'hold-hall': 1.3,
    'hold-motion': 1.3,
    'grain-hall': 0.25,
    'grain-room': 0.25,
    'grain-echo': 0.2,
    'grain-wear': 0.25,
    'grain-tone': 0.2,
    'drive-grain': 0.2,
    'swell-grain-hall': 0.1,
    'pitch-room': 1.5,
    'pitch-wear': 1.5,
    'pitch-echo': 1.3,
    'pitch-halo': 0.5,
    'swell-pitch': 0.15,
    'swell-pitch-hall': 0.1,
    'pitch-grain': 0.3,
    'pitch-width': 0.5,
  },
  own: [
    {
      // The echo machine as it comes: repeats off the tape heads, then its own spring, or a plate.
      id: 'broadcast-hall-heads-and-spring',
      category: 'echo',
      lead: 0,
      count: 6,
      slots: [
        { role: 'echo', devices: ['tape-echo'], not: ['strange'] },
        { devices: ['spring-reverb', 'plate-reverb'], not: ['strange', 'heavy'] },
      ],
    },
    {
      // The polysynth with its chorus in, played as a broken chord into an echo until the pattern blurs, in the hall.
      id: 'broadcast-hall-chorus-into-echo',
      category: 'motion',
      lead: 0,
      count: 5,
      slots: [
        { role: 'motion', devices: ['chorus'], not: ['strange', 'worn'] },
        { role: 'echo', devices: ['tape-echo', 'analog-delay'], not: ['strange', 'fast'] },
        { role: 'hall', devices: ['hall-reverb', 'plate-reverb'], not: ['heavy'] },
      ],
    },
    {
      // A little valve or desk, then out of a loudspeaker in a bare room and recorded back.
      id: 'broadcast-hall-speaker-in-a-room',
      category: 'space',
      lead: 1,
      count: 5,
      slots: [
        {
          role: 'drive',
          devices: ['analog-drive', 'saturator', 'tape'],
          any: ['warm', 'faint'],
          not: ['strange', 'worn', 'cold'],
        },
        { role: 'room', devices: ['re-amp'] },
      ],
    },
    {
      // A quiet instrument miked close: levelled so the mechanism comes up, onto a reel, in a small room.
      id: 'broadcast-hall-close-on-a-reel',
      category: 'tape',
      lead: 1,
      count: 5,
      slots: [
        { role: 'glue', devices: ['ambient-comp'], not: ['fast'] },
        { role: 'wear', devices: ['tape', 'patina'], not: ['worn', 'cold', 'strange'] },
        { role: 'room', any: ['short', 'faint'], not: ['strange', 'cold', 'backwards'] },
      ],
    },
    {
      // A few seconds of tape between two machines, each pass a little duller, left in the hall.
      id: 'broadcast-hall-two-machines',
      category: 'echo',
      lead: 0,
      count: 4,
      slots: [
        { role: 'loop', devices: ['tape-loop'], not: ['strange', 'bright', 'frozen', 'cold'] },
        {
          role: 'hall',
          devices: ['hall-reverb', 'plate-reverb', 'spring-reverb'],
          not: ['strange', 'heavy'],
        },
      ],
    },
    {
      // The phrase again under itself, slowed on tape to an octave or so down, with a small plate or a room.
      id: 'broadcast-hall-slowed-overdub',
      category: 'pitch',
      lead: 0,
      count: 4,
      slots: [
        {
          role: 'pitch',
          devices: ['half-speed', 'tape-loop'],
          want: ['low'],
          not: ['heavy', 'strange', 'cold'],
        },
        {
          devices: ['plate-reverb', 'hall-reverb', 'spring-reverb', 'ether-reverb'],
          not: ['heavy', 'strange', 'bright'],
        },
      ],
    },
  ],
  heads: [
    'Broadcast',
    'On-air',
    'Off-air',
    'Sign-off',
    'Closedown',
    'Interval',
    'Parquet',
    'Panelled',
    'Oak-panel',
    'Red-brick',
    'Riverside',
    'Quayside',
    'Embankment',
    'Upriver',
    'Courtyard',
    'Stairwell',
    'Skylight',
    'Foyer',
    'Cloakroom',
    'Canteen',
    'Gallery',
    'Tenth-row',
    'Back-row',
    'Control-room',
    'Machine-room',
    'Live-room',
    'Patchbay',
    'Talkback',
    'Red-light',
    'Soundcheck',
    'Rehearsal',
    'Session',
    'Overdub',
    'Run-through',
    'After-hours',
    'Small-hours',
    'Tea-break',
    'Workshop',
    'Hand-built',
    'Moderator',
    'Piano-lid',
    'Piano-top',
    'Lid-open',
    'Dust-cover',
    'Double-door',
    { word: 'Damped', for: ['dark'] },
    { word: 'Curtained', for: ['dark', 'short'] },
    { word: 'Tiptoe', for: ['faint'] },
    { word: 'Floorboard', for: ['low'] },
    { word: 'Under-stage', for: ['low'] },
    { word: 'Next-studio', for: ['far'] },
    { word: 'Ribbon-mic', for: ['narrow'] },
    { word: 'Slipping', for: ['unsteady'] },
    { word: 'Spooled-back', for: ['backwards'] },
    { word: 'Blank-reel', for: ['noisy'] },
    { word: 'Unhurried', for: ['long', 'slow'] },
  ],
  tails: [
    'on parquet',
    'by the river',
    'off the floor',
    'after hours',
    'at soundcheck',
    'on the stage',
    'under the lid',
    'past the weir',
    'on the stairs',
    'in one pass',
    'at sign-off',
    'at closedown',
    'by lamplight',
    'under glass',
    'in oak panels',
    'by the window',
    'in the yard',
    'on the quay',
    'on air',
    'sent out live',
    { word: 'a room away', for: ['far'] },
    { word: 'from row ten', for: ['far'] },
    { word: 'underfoot', for: ['low'] },
    { word: 'wound back', for: ['backwards'] },
    { word: 'left running', for: ['long', 'frozen'] },
    { word: 'half asleep', for: ['slow'] },
    { word: 'and room tone', for: ['noisy'] },
  ],
  avoid: [
    'felt',
    'space',
    'solo',
    'night',
    'wall',
    'chant',
    'bells',
    'bell',
    'rain',
    'sheet',
    'takes',
    'shimmer',
  ],
}
