// Empty Concourse: a few notes on loops of unequal length that never meet the
// same way twice, a long delay between two machines, slowed tape, held vowels
// and a halo an octave above. Its chains are loops, long repeats and singing
// tails, calm and clear; nothing is quick, broken or dirty.

import { type PackPalette } from './types'

export const PALETTE: PackPalette = {
  pack: 'concourse',
  groups: { space: 25, echo: 27, tape: 10, motion: 8, texture: 10, pitch: 14, master: 6 },
  traits: {
    long: 1.5,
    slow: 1.5,
    clean: 1.3,
    warm: 1.3,
    high: 1.3,
    low: 1.2,
    far: 1.2,
    wide: 1.1,
    faint: 1.1,
    backwards: 1.1,
    unsteady: 0.85,
    frozen: 0.8,
    cold: 0.7,
    narrow: 0.7,
    heavy: 0.6,
    short: 0.55,
    worn: 0.45,
    noisy: 0.45,
    fast: 0.15,
    strange: 0.08,
  },
  devices: {
    'tape-loop': 5,
    shimmer: 4,
    'echo-memory': 3.5,
    'vowel-reverb': 3,
    'tape-echo': 3,
    tape: 2.6,
    sympathetic: 2.2,
    'half-speed': 2,
    'plate-reverb': 2,
    'hall-reverb': 2,
    'bloom-reverb': 1.6,
    chorus: 1.6,
    swell: 1.6,
    'stereo-detune': 1.6,
    'micro-looper': 1.4,
    rotary: 1.3,
    sustainer: 1.3,
    expanse: 1.3,
    'fdn-reverb': 1.2,
    'ether-reverb': 1.2,
    'pitch-shifter': 0.8,
    'reverse-delay': 0.8,
    'shaped-reverb': 0.8,
    'spectral-blur': 0.8,
    octaves: 0.7,
    'pad-follower': 0.7,
    phaser: 0.5,
    'noise-floor': 0.5,
    'spectral-drifter': 0.4,
    tremolo: 0.3,
    'freq-shifter': 0.3,
    'grain-cloud': 0.3,
    flanger: 0.25,
    'auto-filter': 0.25,
    saturator: 0.2,
    'analog-drive': 0.2,
    'grain-delay': 0.2,
    cascade: 0.15,
    'analog-delay': 0.12,
    'swarm-reverb': 0.12,
    're-amp': 0.08,
    lattice: 0.06,
    patina: 0.05,
    radio: 0.03,
    'vintage-digital': 0.02,
    'spring-reverb': 0,
    vinyl: 0,
    glitch: 0,
    'low-bitrate': 0,
  },
  voices: {
    // The pack's own: two decks, a late return, the octave above, a held vowel, a held pedal.
    'tape-loop:Two decks': 2,
    'tape-loop:Clean layers': 1.5,
    'tape-loop:Slowed down': 1.5,
    'echo-memory:Late return': 1.6,
    'echo-memory:Recalling': 1.5,
    'shimmer:Rising choir': 1.5,
    'shimmer:Faint glimmer': 1.5,
    'vowel-reverb:Choir of ah': 1.5,
    'vowel-reverb:Oo behind': 1.4,
    'sympathetic:Piano pedal': 1.6,
    'stereo-detune:Piano haze': 1.5,
    'swell:Piano to pad': 1.6,
    'rotary:Chorale': 1.4,
    'octaves:Slow halo': 2,
    'octaves:Faint octave': 1.6,
    'pitch-shifter:Faint air': 1.6,
    // What the effects it mostly leaves alone still have for it: a reel, a far speaker, room tone.
    'patina:Quarter inch reel': 14,
    'patina:New tape': 14,
    'patina:Reel pushed hard': 8,
    'vintage-digital:Glaze': 8,
    'vintage-digital:Sampler': 8,
    'auto-filter:Glacial low-pass': 3,
    're-amp:Far end of the hall': 14,
    're-amp:Down the hall': 12,
    're-amp:Station platform': 10,
    're-amp:Just the room': 8,
    're-amp:Room underneath': 8,
    'noise-floor:Empty room': 2.5,
    'noise-floor:Close mic': 1.6,
    'noise-floor:Mains hum': 1.5,
    'freq-shifter:Still water': 3,
    'freq-shifter:Slow drift': 3,
    'tremolo:Slow pan': 2.5,
    'tremolo:Gentle breath': 2.5,
    // Too rough, too quick, the wrong medium, or so little that it is used up fast.
    'tape:Needles pinned': 0.15,
    'tape:Cassette four-track': 0.4,
    'tape:Old dictation': 0.3,
    'tape:Crumbling oxide': 0.2,
    'micro-looper:Sampler grit': 0.15,
    'micro-looper:Lo-fi quarter': 0.15,
    'micro-looper:Octave up': 0.5,
    'half-speed:Slow chops': 0.3,
    'shaped-reverb:Gated': 0.2,
    'auto-filter:Dub sweep': 0.2,
    'auto-filter:Phone line': 0.2,
    'saturator:Lo-fi': 0.2,
    'rotary:Parked growl': 0.2,
    'rotary:Slow burn': 0.4,
    'ambient-limiter:Pinned': 0.3,
    'ambient-comp:Dense pad': 0.2,
    'ambient-comp:Pump': 0,
    'noise-floor:Old record': 0,
    'noise-floor:Gap crackle': 0,
  },
  recipes: {
    // Space.
    'halo-hall': 2,
    'width-hall': 1.6,
    'swell-hall': 1.5,
    'swell-halo': 1.5,
    'swell-halo-hall': 1.3,
    'tone-halo': 0.7,
    'tone-hall': 0.5,
    'hall-tone': 0.6,
    'tone-room-hall': 0.7,
    'room-halo': 1.2,
    'width-room': 0.6,
    'drive-hall': 0.2,
    'drive-room': 0.2,
    // Echo.
    'loop-hall': 2.5,
    'loop-echo': 2,
    'loop-tone-hall': 1.6,
    'tone-loop': 1.2,
    'echo-tone': 0.6,
    'echo-hall': 1.5,
    'echo-halo': 1.6,
    'echo-echo': 1.3,
    'swell-echo': 1.3,
    'echo-room': 0.8,
    'drive-echo': 0.3,
    'drive-echo-hall': 0.3,
    // Tape.
    'loop-wear': 2.5,
    'loop-wear-hall': 2.5,
    'wear-hall': 2,
    'wear-echo': 1.5,
    'tone-wear-echo': 0.8,
    'tone-wear': 0.6,
    'wear-tone': 0.5,
    'motion-wear': 0.8,
    'wear-hiss-hall': 0.5,
    'wear-hiss': 0.4,
    'drive-wear': 0.3,
    'drive-tone': 0.2,
    'drive-wear-room': 0.2,
    'drive-hiss': 0,
    // Motion.
    'motion-hall': 2,
    'motion-halo': 1.6,
    'motion-echo-hall': 1.3,
    'width-motion': 1.2,
    'swell-motion': 1.2,
    'motion-tone': 0.5,
    'drive-motion': 0.15,
    'drive-motion-hall': 0.15,
    'pulse-echo': 0,
    'pulse-hall': 0,
    'pulse-room': 0,
    'tone-pulse': 0,
    // Texture.
    'hold-hall': 1.6,
    'hold-halo': 1.6,
    'swell-hold': 1.5,
    'hold-motion': 1.2,
    'hold-motion-hall': 1.2,
    'hold-tone': 0.5,
    'grain-hall': 0.8,
    'swell-grain-hall': 0.8,
    'grain-echo': 0.6,
    'grain-room': 0.4,
    'grain-tone': 0.4,
    'grain-wear': 0.3,
    'drive-grain': 0,
    // Pitch.
    'pitch-halo': 1.6,
    'pitch-hall': 1.5,
    'pitch-wear': 1.3,
    'swell-pitch-hall': 1.3,
    'pitch-echo': 1.2,
    'pitch-tone': 0.5,
    'pitch-grain': 0.4,
    'drive-pitch': 0.1,
    // Master.
    'drive-ceiling': 0.3,
    'drive-tone-ceiling': 0.15,
    'drive-glue-ceiling': 0.15,
  },
  own: [
    {
      // The pack in one chain: two loops of unequal length that never meet the same way twice.
      id: 'concourse-unequal-loops',
      category: 'echo',
      lead: 0,
      count: 7,
      slots: [
        { role: 'loop', devices: ['tape-loop'], not: ['fast', 'strange', 'high'] },
        {
          role: 'loop',
          devices: ['echo-memory', 'micro-looper'],
          not: ['fast', 'strange', 'high', 'worn'],
        },
        { role: 'hall', not: ['heavy', 'strange'] },
      ],
    },
    {
      // A plain tone shaped, sent round the long delay between two machines, onto tape.
      id: 'concourse-two-machines',
      category: 'echo',
      lead: 1,
      count: 4,
      slots: [
        {
          role: 'tone',
          devices: ['ambient-eq', 'auto-filter', 'phaser'],
          not: ['worn', 'cold', 'bright'],
        },
        {
          presets: [
            'tape-loop:Two decks',
            'tape-loop:Slow fade',
            'tape-loop:Clean layers',
            'tape-loop:Crossing sides',
            'tape-echo:Long dark trail',
            'tape-echo:Dub wash',
            'tape-echo:Hovering wash',
            'echo-memory:Late return',
            'echo-memory:Dark trail',
            'echo-memory:Recalling',
          ],
        },
        { role: 'wear', devices: ['tape'], any: ['faint', 'clean'] },
      ],
    },
    {
      // Notes with the strike faded off, under a tail that climbs an octave above them.
      id: 'concourse-octave-halo',
      category: 'space',
      lead: 1,
      count: 5,
      slots: [
        { role: 'swell', devices: ['swell'], not: ['fast'] },
        { role: 'halo', devices: ['shimmer', 'bloom-reverb'], any: ['high'] },
        { role: 'hall', not: ['heavy', 'strange', 'unsteady'] },
      ],
    },
    {
      // A hall that sings a held vowel back, laid again on a loop a little longer than the chord.
      id: 'concourse-vowel-on-a-loop',
      category: 'space',
      lead: 0,
      count: 4,
      slots: [
        { role: 'halo', devices: ['vowel-reverb'] },
        {
          role: 'loop',
          devices: ['tape-loop', 'echo-memory', 'micro-looper'],
          not: ['fast', 'strange', 'high', 'worn'],
        },
      ],
    },
    {
      // Slowed to half speed on tape, an octave down and soft-edged, in a long plate or hall.
      id: 'concourse-slowed-on-tape',
      category: 'pitch',
      lead: 0,
      count: 4,
      slots: [
        { role: 'pitch', devices: ['half-speed', 'tape-loop', 'micro-looper'], any: ['low'] },
        { role: 'wear', devices: ['tape'], not: ['strange', 'noisy'] },
        { role: 'hall', devices: ['plate-reverb', 'hall-reverb'] },
      ],
    },
    {
      // A piano with its pedal held: open strings that ring on in sympathy, in a long dark room.
      id: 'concourse-pedal-held',
      category: 'space',
      lead: 0,
      count: 4,
      slots: [
        { role: 'halo', devices: ['sympathetic'], not: ['heavy'] },
        {
          role: 'hall',
          devices: [
            'plate-reverb',
            'hall-reverb',
            'ether-reverb',
            'fdn-reverb',
            'expanse',
            'shaped-reverb',
          ],
          any: ['long', 'dark', 'warm'],
          not: ['heavy', 'strange', 'unsteady'],
        },
      ],
    },
  ],
  heads: [
    'Concourse',
    'Departure',
    'Terminal',
    'Transit',
    'Layover',
    'Stopover',
    'Standby',
    'Boarding',
    'Gate-side',
    'Runway',
    'Tarmac',
    'Atrium',
    'Skylight',
    'Walkway',
    'Escalator',
    'Carousel',
    'Lounge',
    'Check-in',
    'Last-call',
    'Red-eye',
    'Night-shift',
    'Small-hours',
    'Pre-dawn',
    'Overnight',
    'Unattended',
    'Connecting',
    'Inbound',
    'Outbound',
    'Terrazzo',
    'Tube-lit',
    'Sodium',
    'Unclaimed',
    'Shuttered',
    'Vacant',
    'Window-seat',
    'Hangar',
    'Taxiway',
    'Windsock',
    'Split-flap',
    'Gate-change',
    'Freight',
    'Ground-crew',
    'Touchdown',
    'Cruising',
    'Contrail',
    'Crosswind',
    'Drizzle',
    'Midweek',
    'Off-peak',
    'Empty-row',
    'Kerbside',
    'Air-bridge',
    'Baggage',
    'Timetable',
    'Transfer',
    'Paging',
    { word: 'Overhead', for: ['high'] },
    { word: 'Descending', for: ['low'] },
    { word: 'Taxiing', for: ['slow'] },
    { word: 'Long-haul', for: ['long'] },
    { word: 'Far-gate', for: ['far'] },
    { word: 'Turned-round', for: ['backwards'] },
    { word: 'Jet-lagged', for: ['unsteady'] },
    { word: 'Lights-down', for: ['dark'] },
    { word: 'Snowed-in', for: ['frozen'] },
    { word: 'Ventilated', for: ['noisy'] },
    { word: 'Half-heard', for: ['faint'] },
  ],
  tails: [
    'in transit',
    'on standby',
    'after hours',
    'at the desk',
    'on a layover',
    'before dawn',
    'on the apron',
    'on the tarmac',
    'past customs',
    'at last call',
    'left running',
    'for nobody',
    'at arrivals',
    'on level two',
    'by the window',
    'between gates',
    'in low cloud',
    'at the pier',
    'through glass',
    'on the hour',
    'till morning',
    'at the kerb',
    { word: 'gates away', for: ['far'] },
    { word: 'from above', for: ['high'] },
    { word: 'from below', for: ['low'] },
    { word: 'run backwards', for: ['backwards'] },
    { word: 'all night', for: ['long'] },
    { word: 'after dark', for: ['dark'] },
    { word: 'with vent air', for: ['noisy'] },
    { word: 'taken slowly', for: ['slow'] },
  ],
  // Nouns this pack's names leave alone.
  avoid: ['ascent', 'bloom', 'drift', 'shadow'],
}
