// Far North Bowed Guitar: a bow drawn over electric strings, a hot amplifier
// and a hall seconds across, with a high voice, a pump organ and strings that
// rise behind. Its chains swell in, overdrive warmly and open into very large
// spaces whose tails climb or turn backwards; little is quick, broken or worn.

import { type PackPalette } from './types'

export const PALETTE: PackPalette = {
  pack: 'far-north',
  groups: { space: 34, echo: 13, tape: 10, motion: 7, texture: 16, pitch: 14, master: 6 },
  traits: {
    long: 1.6,
    slow: 1.5,
    warm: 1.4,
    high: 1.4,
    backwards: 1.5,
    wide: 1.3,
    bright: 1.3,
    far: 1.2,
    dark: 0.85,
    low: 0.8,
    unsteady: 0.7,
    short: 0.6,
    narrow: 0.6,
    noisy: 0.2,
    worn: 0.15,
    fast: 0.35,
    strange: 0.05,
  },
  devices: {
    'analog-drive': 2.6,
    're-amp': 2.4,
    'hall-reverb': 4,
    expanse: 2.4,
    'fdn-reverb': 2.6,
    'reverse-delay': 2.6,
    shimmer: 2.4,
    swell: 2.6,
    'plate-reverb': 1.8,
    'shaped-reverb': 1.6,
    'ether-reverb': 1.5,
    'bloom-reverb': 1.5,
    'vowel-reverb': 1.6,
    'pad-follower': 1.8,
    sustainer: 1.4,
    'spring-reverb': 0.9,
    octaves: 1.3,
    rotary: 1.6,
    chorus: 1.2,
    'tape-echo': 1.1,
    cascade: 1.1,
    saturator: 0.8,
    'tape-loop': 0.5,
    'micro-looper': 0.4,
    'echo-memory': 0.6,
    patina: 0.6,
    tape: 1,
    'swarm-reverb': 0.7,
    'ambient-eq': 0.7,
    'noise-floor': 0.4,
    'half-speed': 0.3,
    'auto-filter': 0.4,
    phaser: 0.05,
    flanger: 0.05,
    lattice: 0.4,
    vinyl: 0.05,
    radio: 0.05,
    'freq-shifter': 0.1,
    glitch: 0,
    'low-bitrate': 0,
    'vintage-digital': 0,
  },
  voices: {
    'swell:Bowed': 2,
    'swell:Slow bow': 2,
    'swell:String section': 1.6,
    'shimmer:Rising choir': 1.6,
    'hall-reverb:Vast nave': 1.5,
    'reverse-delay:Slow swells': 1.6,
    'analog-drive:Torn cone': 0.2,
    'patina:Valve fuzz': 0.2,
    'saturator:Blown speaker': 0.1,
    'saturator:Wavefold lead': 0.2,
    'saturator:Lo-fi': 0.2,
    'auto-filter:Dub sweep': 0,
    'auto-filter:Low-pass gate': 0.1,
    'auto-filter:Touch wah': 0,
    'phaser:Stereo scatter': 0,
    'phaser:Still formant': 8,
    'tremolo:Wandering pan': 0.3,
    'micro-looper:Lo-fi quarter': 0.2,
    'micro-looper:Sampler grit': 0.2,
    'tape:Needles pinned': 2,
    'tape:Mastering deck': 1.5,
    'patina:Reel pushed hard': 2,
    'patina:New tape': 1.5,
    'noise-floor:Amp left on': 4,
    're-amp:Noisy valves': 1.5,
    'saturator:Fuzz pedal': 0.4,
    'patina:Early sampler': 0,
    'patina:Eight bit': 0,
    'patina:Muffled sampler': 0,
    'patina:Scratched record': 0,
    'patina:Dusty record': 0,
    'cascade:Dropped marbles': 0.2,
    'fet-limiter:Flattened': 0,
    'fet-limiter:Squash': 0,
    'ambient-comp:Pump': 0,
    'ambient-comp:Dense pad': 0.1,
  },
  recipes: {
    'drive-hall': 2.2,
    'swell-hall': 2,
    'swell-halo-hall': 1.8,
    'swell-halo': 1.6,
    'halo-hall': 1.5,
    'room-hall': 1.2,
    'width-hall': 0.7,
    'tone-hall': 0.6,
    'hall-tone': 0.6,
    'tone-halo': 0.6,
    'tone-room-hall': 0.5,
    'width-room': 0.5,
    'swell-echo': 1.6,
    'echo-hall': 1.6,
    'echo-halo': 1.5,
    'drive-echo': 1.4,
    'drive-echo-hall': 1.6,
    'echo-echo': 0.5,
    'echo-tone': 0.4,
    'loop-hall': 0.5,
    'loop-room': 0.4,
    'tone-loop': 0.4,
    'loop-echo': 0.4,
    'loop-tone-hall': 0.3,
    'drive-tone': 1,
    'drive-wear-room': 1.3,
    'wear-hall': 1.4,
    'drive-wear': 0.8,
    'tone-wear': 0.6,
    'wear-tone': 0.6,
    'motion-wear': 0.3,
    'tone-wear-echo': 0.5,
    'wear-hiss': 0.3,
    'loop-wear': 0.2,
    'loop-wear-hall': 0.5,
    'motion-hall': 1.5,
    'motion-motion': 0.4,
    'swell-motion': 1.5,
    'motion-halo': 1.3,
    'drive-motion-hall': 1.4,
    'pulse-echo': 0.3,
    'pulse-hall': 0.4,
    'pulse-room': 0.3,
    'tone-pulse': 0.3,
    'motion-tone': 0.5,
    'swell-hold': 2,
    'hold-hall': 1.8,
    'hold-halo': 1.5,
    'swell-grain-hall': 1.4,
    'swell-room': 1.2,
    'grain-wear': 0.4,
    'hold-wear': 0.4,
    'hold-tone': 0.5,
    'pitch-hall': 1.6,
    'swell-pitch': 1.5,
    'swell-pitch-hall': 1.6,
    'pitch-halo': 1.4,
    'drive-pitch': 1.3,
    'pitch-wear': 0.4,
    'wear-ceiling': 0.5,
    'wear-glue-ceiling': 0.5,
  },
  own: [
    {
      // The pack in one chain: every note bowed in, a hot amplifier, a hall seconds across.
      id: 'far-north-bow-amp-hall',
      category: 'space',
      lead: 2,
      count: 6,
      slots: [
        { role: 'swell', devices: ['swell'], not: ['fast'] },
        {
          role: 'drive',
          devices: ['analog-drive', 're-amp', 'saturator', 'patina'],
          not: ['strange', 'cold'],
        },
        {
          role: 'hall',
          devices: ['hall-reverb', 'fdn-reverb', 'expanse', 'ether-reverb', 'plate-reverb'],
          any: ['long', 'wide'],
        },
      ],
    },
    {
      // Each stroke swells up to where it began and stops, on a long plate or in a hall.
      id: 'far-north-backwards-on-a-plate',
      category: 'echo',
      lead: 0,
      count: 5,
      slots: [
        { role: 'echo', want: ['backwards'], not: ['fast', 'strange'] },
        { role: 'hall', devices: ['plate-reverb', 'hall-reverb', 'fdn-reverb', 'ether-reverb'] },
      ],
    },
    {
      // A valve stage into a speaker near its limit, with a spring behind it.
      id: 'far-north-valve-speaker-spring',
      category: 'tape',
      lead: 1,
      count: 4,
      slots: [
        { role: 'drive', devices: ['analog-drive', 'saturator', 'patina'], not: ['strange'] },
        { role: 'drive', devices: ['re-amp'], not: ['cold'] },
        { devices: ['spring-reverb'], not: ['strange', 'heavy'] },
      ],
    },
    {
      // A string section that swells up behind whatever is played, in a large space.
      id: 'far-north-strings-rising-behind',
      category: 'texture',
      lead: 0,
      count: 5,
      slots: [
        { role: 'hold', devices: ['pad-follower', 'sustainer'], not: ['fast', 'frozen'] },
        { role: 'hall', any: ['long', 'wide', 'warm'], not: ['strange', 'narrow'] },
      ],
    },
    {
      // The amplifier begins to sing: an overdriven stage whose tail climbs to the octave.
      id: 'far-north-drive-into-rising-tail',
      category: 'pitch',
      lead: 1,
      count: 4,
      slots: [
        { role: 'drive', devices: ['analog-drive', 're-amp', 'saturator'], not: ['strange'] },
        { role: 'halo', any: ['high'], not: ['strange'] },
      ],
    },
    {
      // A pump organ: ranks of octaves drawn, a slow rotor or the bellows breathing, a room.
      id: 'far-north-ranks-and-bellows',
      category: 'pitch',
      lead: 0,
      count: 4,
      slots: [
        { role: 'pitch', devices: ['octaves'], not: ['strange'] },
        {
          role: 'motion',
          devices: ['rotary', 'tremolo', 'chorus'],
          not: ['fast', 'strange', 'worn'],
        },
        { role: 'room', not: ['backwards', 'narrow', 'fast'] },
      ],
    },
  ],
  heads: [
    'Lava-field',
    'Mossy',
    'Basalt',
    'Fjord',
    'Turf-roof',
    'Boathouse',
    'Midnight-sun',
    'Blue-hour',
    'Whiteout',
    'Meltwater',
    'Black-sand',
    'Lichen',
    'Tundra',
    'Northern',
    'Far-shore',
    'Harbour',
    'Lighthouse',
    'Pumice',
    'Ashfall',
    'Scree',
    'Driftwood',
    'Trawler',
    'Seabird',
    'Skerry',
    'Kelp',
    'Birchwood',
    'Crowberry',
    'Geothermal',
    'Solstice',
    'Snowmelt',
    'Pack-ice',
    'Northerly',
    'Low-cloud',
    'Parish',
    'Schoolhouse',
    'Slipway',
    'Quayside',
    'Thawing',
    'Highland',
    'Headland',
    'Sheepfold',
    'Hoarfrost',
    'Nightless',
    'Treeless',
    'Tin-roof',
    'Glacier-fed',
    'Sea-fog',
    'Smokehouse',
    { word: 'Glacial', for: ['slow'] },
    { word: 'Frosted', for: ['cold', 'bright'] },
    { word: 'Mirrored', for: ['backwards'] },
    { word: 'Across-water', for: ['far'] },
    { word: 'Under-ice', for: ['low'] },
    { word: 'Steaming', for: ['noisy'] },
    { word: 'Snowbound', for: ['dark'] },
    { word: 'Never-setting', for: ['frozen', 'long'] },
    { word: 'Windblown', for: ['unsteady'] },
  ],
  tails: [
    'over lava',
    'on the moss',
    'at midsummer',
    'by the fjord',
    'in sea fog',
    'off the ice',
    'in whiteout',
    'on black sand',
    'at blue hour',
    'up north',
    'on the fell',
    'at low sun',
    'over the bay',
    'by the boats',
    'before thaw',
    'in long light',
    'after snow',
    'in hoarfrost',
    'under cloud',
    'in the lee',
    'off the pier',
    { word: 'from afar', for: ['far'] },
    { word: 'turned round', for: ['backwards'] },
    { word: 'in slow waves', for: ['slow'] },
    { word: 'under ice', for: ['low', 'dark'] },
  ],
}
