// Pulse under the Forest: old orchestral records looped, played at the wrong
// speed, shut under a lid and smeared into fog between the trees, with a
// heartbeat somewhere far below. Its chains slow things down, blur them and
// put them in a large dark space; nothing is bright, clean, quick or thin.

import { type PackPalette } from './types'

export const PALETTE: PackPalette = {
  pack: 'forest-pulse',
  groups: { space: 14, echo: 13, tape: 14, motion: 12, texture: 23, pitch: 18, master: 6 },
  traits: {
    dark: 2,
    low: 1.5,
    warm: 1.3,
    slow: 1.4,
    far: 1.4,
    long: 1.3,
    wide: 1.2,
    heavy: 1.2,
    worn: 1.2,
    noisy: 1.2,
    unsteady: 1.1,
    bright: 0.12,
    high: 0.1,
    cold: 0.2,
    clean: 0.5,
    fast: 0.25,
    short: 0.7,
    strange: 0.08,
    faint: 0.8,
  },
  devices: {
    'spectral-blur': 4,
    'half-speed': 2.2,
    vinyl: 3,
    'micro-looper': 2.4,
    'auto-filter': 1.8,
    'grain-cloud': 1.8,
    'tape-loop': 2,
    phaser: 1.3,
    'pad-follower': 1.5,
    expanse: 1.2,
    'hall-reverb': 1.4,
    sustainer: 1.3,
    'ambient-eq': 0.8,
    'fdn-reverb': 1.2,
    'echo-memory': 1.2,
    'noise-floor': 1.2,
    patina: 0.7,
    tape: 0.6,
    'tape-echo': 0.6,
    'analog-delay': 0.6,
    'reverse-delay': 0.6,
    'pitch-shifter': 0.6,
    'spectral-drifter': 0.3,
    'vintage-digital': 0.5,
    tremolo: 0.7,
    flanger: 0.2,
    cascade: 0.3,
    sympathetic: 0.2,
    shimmer: 0.3,
    're-amp': 0.1,
    'freq-shifter': 0.1,
    'shaped-reverb': 0.8,
    glitch: 0.25,
    // No place under these trees: a rotating speaker, dripping springs, a radio,
    // a starved stream, a harmoniser in a fixed key.
    rotary: 0,
    'spring-reverb': 0,
    radio: 0,
    'low-bitrate': 0,
    lattice: 0,
  },
  voices: {
    // The record, its surface, and the fog.
    'vinyl:Warped': 1.5,
    'vinyl:Dust and scratches': 2,
    'vinyl:Crackle bed': 2,
    'vinyl:Surface and rumble': 1.5,
    'vinyl:Dull stylus': 0.7,
    'patina:Dusty record': 2.5,
    'patina:Scratched record': 2,
    'glitch:Skipping disc': 6,
    'noise-floor:Old record': 1.8,
    'noise-floor:Gap crackle': 1.8,
    'spectral-blur:Slow dissolve': 1.5,
    'spectral-blur:Hanging mist': 2,
    'spectral-blur:Band of fog': 2,
    'grain-cloud:Thick fog': 1.5,
    'auto-filter:Glacial low-pass': 2,
    'expanse:Small dark room': 2,
    'bloom-reverb:Narrow cellar': 2,
    'plate-reverb:Small plate': 1.5,
    // The heartbeat: what beats about twice a second.
    'freq-shifter:Moving beat': 24,
    'freq-shifter:Still water': 4,
    'tremolo:Amp tremolo': 6,
    'tremolo:On and off': 4,
    'flanger:Tremolo saw': 6,
    'flanger:Square chop': 10,
    'fdn-reverb:Pulsing gate': 4,
    'shaped-reverb:Ripples': 4,
    // Quicker than a heartbeat.
    'half-speed:Short stutter': 0.3,
    'auto-filter:Tremolo filter': 0.5,
    'auto-filter:Touch wah': 0.1,
    'auto-filter:Falling high-pass': 0.3,
    'tremolo:Harmonic shimmer': 0.4,
    'tremolo:Wide shimmer': 0.4,
    'tremolo:Fast shudder': 0.4,
    'chorus:Fast flutter': 0.3,
    'chorus:Vibrato': 0.3,
    'echo-memory:Swarm': 0.2,
    // Undamped, thin or high on top, though their traits do not all say so.
    'hall-reverb:Bright hall': 0.2,
    'fdn-reverb:Bright air': 0.2,
    'fdn-reverb:Small bright tank': 0.2,
    'ether-reverb:Shining tail': 0.1,
    'ether-reverb:Bright chamber': 0.3,
    'ether-reverb:Ether': 0.3,
    'swarm-reverb:Glass rain': 0.1,
    'swarm-reverb:Metal pipe': 0.2,
    'vowel-reverb:High ee': 0.2,
    'vowel-reverb:High choir': 0.1,
    'bloom-reverb:Quick sparkle': 0.1,
    'bloom-reverb:Glass scatter': 0.2,
    'bloom-reverb:Endless rise': 0.2,
    'auto-filter:Resonant peak': 0.2,
    'grain-delay:Rising fifths': 0.3,
    'vinyl:Jukebox single': 0.2,
    // Too far from an orchestra in a wood.
    'sympathetic:Glass harp': 0.3,
    'sympathetic:Sitar drone': 0.2,
    'analog-delay:Octave hop': 0.08,
    'analog-delay:Fifth hop': 0.08,
    'analog-drive:Iron melt': 0.3,
    'vintage-digital:Toy': 0.3,
    'vinyl:Ruined record': 0.4,
    // A record, not a cassette, a radio, a telephone or an amplifier left on.
    'tape:Cassette four-track': 0,
    'tape:Old dictation': 0,
    'tape:Chewed cassette': 0,
    'tape:Warm thump': 0,
    'tape:Under a blanket': 0,
    'patina:Worn cassette': 0,
    'patina:Falling apart': 0,
    'patina:Kitchen radio': 0,
    'patina:Shortwave': 0,
    'patina:Distant station': 0,
    'noise-floor:Radio static': 0,
    'noise-floor:Static notes': 0,
    'noise-floor:Mains hum': 0,
    'noise-floor:Amp left on': 0,
    'auto-filter:Phone line': 0,
    'vintage-digital:Phone': 0,
    're-amp:In the cupboard': 0,
    // Bright, out of tune, splintered, chopped or squelching: no place here.
    'ambient-eq:Bright': 0,
    'grain-delay:Scattered pitches': 0,
    'spectral-drifter:Splintered': 0,
    'spectral-drifter:Scatter': 0,
    'tremolo:Chopper': 0,
    'auto-filter:Squelch': 0,
    'auto-filter:Stepped': 0,
    'auto-filter:Screaming': 0,
  },
  recipes: {
    'tone-hall': 2,
    'hall-tone': 2,
    'tone-room-hall': 1.6,
    'room-hall': 1.3,
    'loop-hall': 2,
    'loop-tone-hall': 2.5,
    'tone-loop': 2,
    'loop-wear': 2,
    'loop-wear-hall': 2,
    'wear-tone': 2,
    'tone-wear': 1.6,
    'wear-hall': 1.6,
    'wear-hiss': 1.4,
    'wear-hiss-hall': 1.6,
    'pulse-hall': 2,
    'pulse-room': 1.6,
    'tone-pulse': 2,
    'motion-hall': 1.4,
    'grain-hall': 2,
    'hold-hall': 2,
    'hold-motion-hall': 1.6,
    'swell-grain-hall': 1.5,
    'grain-wear': 1.6,
    'hold-wear': 1.4,
    'pitch-hall': 2,
    'pitch-grain': 2.5,
    'pitch-wear': 2,
    'pitch-hold': 1.6,
    'pitch-tone': 1.6,
    'swell-pitch-hall': 1.5,
    'glue-ceiling': 3,
    'tone-glue-ceiling': 2,
    'drive-glue-ceiling': 2,
    'tone-ceiling': 0.5,
    'drive-tone-ceiling': 0.5,
    'tone-width-ceiling': 0.3,
    'echo-echo': 0.2,
    'echo-width': 0.3,
    'drive-echo': 0.3,
    'drive-echo-hall': 0.3,
    'drive-motion': 0.3,
    'drive-motion-hall': 0.4,
    'drive-hall': 0.5,
    'drive-room': 0.3,
    'drive-grain': 0.4,
    'drive-pitch': 0.4,
    'drive-wear': 0.4,
    'drive-wear-room': 0.3,
    'drive-tone': 0.4,
    'pulse-echo': 0.5,
    'pitch-halo': 0.4,
    'pitch-width': 0.4,
    'hall-width': 0.5,
    'room-halo': 0.4,
    'width-room': 0.5,
    'swell-width': 0.2,
    'wear-ceiling': 0.5,
    'width-ceiling': 0.5,
    'drive-ceiling': 0.6,
  },
  own: [
    {
      // The pack in one chain: an octave down at half speed, smeared until no edge is left, in a very large dark space.
      id: 'forest-pulse-slowed-into-fog',
      category: 'pitch',
      lead: 0,
      count: 5,
      slots: [
        {
          role: 'pitch',
          devices: ['half-speed', 'micro-looper', 'tape-loop', 'octaves'],
          any: ['low'],
          not: ['high', 'strange', 'fast'],
        },
        {
          role: 'grain',
          devices: ['spectral-blur', 'grain-cloud', 'grain-delay'],
          not: ['bright', 'high', 'strange', 'fast', 'cold'],
        },
        { role: 'hall', any: ['dark', 'long', 'far'], not: ['bright', 'cold', 'strange'] },
      ],
    },
    {
      // An old record played at the wrong speed, an octave down, crackle and all, in a stone hall.
      id: 'forest-pulse-record-at-wrong-speed',
      category: 'tape',
      lead: 0,
      count: 5,
      slots: [
        {
          role: 'wear',
          devices: ['vinyl', 'patina'],
          any: ['worn', 'dark', 'noisy'],
          not: ['bright', 'cold', 'strange', 'narrow'],
        },
        {
          role: 'pitch',
          devices: ['half-speed', 'micro-looper', 'tape-loop'],
          any: ['low'],
          not: ['high', 'strange', 'fast'],
        },
        { role: 'hall', any: ['dark', 'long', 'far'], not: ['bright', 'cold', 'strange'] },
      ],
    },
    {
      // The heartbeat: a steady pulse, closed off above the bass, heard through the floor of a large room.
      id: 'forest-pulse-beat-below',
      category: 'motion',
      lead: 0,
      count: 5,
      slots: [
        {
          role: 'pulse',
          presets: [
            'freq-shifter:Moving beat',
            'half-speed:Slow chops',
            'flanger:Square chop',
            'flanger:Tremolo saw',
            'shaped-reverb:Ripples',
            'tremolo:Amp tremolo',
            'tremolo:On and off',
            'grain-delay:Pulsing repeat',
            'phaser:Two-tone flip',
          ],
        },
        { role: 'tone', any: ['dark'], not: ['cold'] },
        { role: 'hall', any: ['dark', 'long', 'far'], not: ['bright', 'cold', 'strange'] },
      ],
    },
    {
      // A section held as one even bed, phased slowly, in a long dark space.
      id: 'forest-pulse-strings-in-fog',
      category: 'texture',
      lead: 0,
      count: 5,
      slots: [
        {
          role: 'hold',
          devices: ['pad-follower', 'sustainer', 'spectral-blur'],
          not: ['bright', 'high', 'cold', 'fast'],
        },
        { role: 'motion', devices: ['phaser', 'chorus', 'tape', 'vinyl'], any: ['slow'] },
        { role: 'hall', any: ['dark', 'long', 'far'], not: ['bright', 'cold', 'strange'] },
      ],
    },
    {
      // Fog with the surface of the record still under it: a smear, and crackle or rumble.
      id: 'forest-pulse-fog-and-crackle',
      category: 'texture',
      lead: 0,
      count: 4,
      slots: [
        {
          role: 'grain',
          devices: ['spectral-blur', 'grain-cloud', 'grain-delay'],
          not: ['bright', 'high', 'strange', 'fast', 'cold'],
        },
        { role: 'hiss', not: ['bright', 'strange', 'narrow'] },
      ],
    },
    {
      // A loop under a filter that opens and closes over many bars, in a hall.
      id: 'forest-pulse-lidded-loop',
      category: 'echo',
      lead: 0,
      count: 5,
      slots: [
        {
          role: 'loop',
          devices: ['micro-looper', 'tape-loop', 'echo-memory'],
          not: ['bright', 'high', 'fast'],
        },
        {
          presets: [
            'auto-filter:Glacial low-pass',
            'auto-filter:Dub sweep',
            'auto-filter:Low-pass gate',
            'auto-filter:Soft bloom',
            'auto-filter:Slow notch',
            'ambient-eq:Muffled',
            'ambient-eq:Shaded',
            'phaser:Bass safe',
          ],
        },
        { role: 'hall', any: ['dark', 'long', 'far'], not: ['bright', 'cold', 'strange'] },
      ],
    },
  ],
  heads: [
    'Mossy',
    'Fir-wood',
    'Under-canopy',
    'Forest-floor',
    'Leaf-mould',
    'Leaf-litter',
    'Pinewood',
    'Beechwood',
    'Undergrowth',
    'Bracken',
    'Lichen',
    'Windfall',
    'Deadfall',
    'Woodsmoke',
    'Resin',
    'Treeline',
    'Old-growth',
    'Evergreen',
    'Spruce',
    'Larch',
    'Alder',
    'Bramble',
    'Hemlock',
    'Thicket',
    'Trunk-side',
    'Root-tangle',
    'Bark-brown',
    'Needle-bed',
    'Fogbound',
    'Drizzle',
    'Overcast',
    'Dew-wet',
    'Half-lit',
    'Dusk-wood',
    'First-light',
    'Woodland',
    'Deepwood',
    'Rhineland',
    'Logging-road',
    'Flea-market',
    'Second-hand',
    'Salon',
    'Late-romantic',
    'Underfoot',
    'Under-moss',
    'Rain-soaked',
    'Mycelium',
    'Ivy-grown',
    'Birchbark',
    'Wood-path',
    'Hollow-trunk',
    'Owl-hour',
    'Grey-dawn',
    'Late-autumn',
    'Leafless',
    'Damp-bark',
    { word: 'Slowed', for: ['low'] },
    { word: 'Wrong-speed', for: ['low'] },
    { word: 'Unhurried', for: ['slow'] },
    { word: 'Lidded', for: ['dark'] },
    { word: 'Muffled', for: ['dark'] },
    { word: 'Buried', for: ['dark', 'low'] },
    { word: 'Far-off', for: ['far'] },
    { word: 'Scuffed', for: ['noisy'] },
    { word: 'Swallowed', for: ['heavy'] },
    { word: 'Turned-back', for: ['backwards'] },
    { word: 'Unending', for: ['frozen'] },
    { word: 'Warped', for: ['unsteady'] },
  ],
  tails: [
    'under moss',
    'under leaves',
    'between firs',
    'in the firs',
    'under canopy',
    'past a ridge',
    'in a thicket',
    'at treeline',
    'among trunks',
    'off the path',
    'in wet bark',
    'in leaf mould',
    'before dawn',
    'by the stream',
    'after rain',
    'in drizzle',
    'under bracken',
    'in a clearing',
    'in woodsmoke',
    'in the fog',
    { word: 'from far off', for: ['far'] },
    { word: 'far below', for: ['low'] },
    { word: 'under a lid', for: ['dark'] },
    { word: 'played slow', for: ['low'] },
    { word: 'run backwards', for: ['backwards'] },
  ],
}
