// Coast Fog Four-Track: a voice, a guitar and an old electric piano on a
// cassette four-track on the coast, with the reverb up until the words are
// gone. Its chains are a plate or a hall first and the cassette and its hiss
// second; everything is dull on top, far back and a little unsteady, and
// nothing is bright, clean, quick or digital.

import { type PackPalette } from './types'

export const PALETTE: PackPalette = {
  pack: 'four-track',
  groups: { space: 27, echo: 15, tape: 27, motion: 7, texture: 9, pitch: 9, master: 6 },
  traits: {
    dark: 2,
    far: 1.8,
    warm: 1.5,
    worn: 1.5,
    noisy: 1.4,
    long: 1.4,
    unsteady: 1.3,
    low: 1.3,
    slow: 1.2,
    heavy: 1.2,
    narrow: 1.2,
    faint: 0.8,
    short: 0.7,
    clean: 0.6,
    fast: 0.5,
    bright: 0.25,
    cold: 0.3,
    high: 0.3,
    strange: 0.15,
  },
  devices: {
    tape: 1.8,
    'plate-reverb': 5,
    'hall-reverb': 4,
    'noise-floor': 2.5,
    patina: 2.2,
    'fdn-reverb': 1.4,
    'vowel-reverb': 1.5,
    'tape-echo': 1.6,
    'analog-delay': 1.4,
    'tape-loop': 1.5,
    'half-speed': 1.5,
    're-amp': 1.5,
    'analog-drive': 1.3,
    'spring-reverb': 1.3,
    expanse: 0.8,
    'stereo-detune': 1.4,
    tremolo: 1.6,
    swell: 1.2,
    sympathetic: 1.2,
    'spectral-blur': 1.1,
    'reverse-delay': 0.9,
    chorus: 0.6,
    sustainer: 0.8,
    'pad-follower': 0.7,
    'echo-memory': 0.7,
    'bloom-reverb': 0.7,
    'ether-reverb': 0.8,
    'shaped-reverb': 0.6,
    'auto-filter': 0.5,
    rotary: 0.7,
    'stereo-widener': 0.7,
    'micro-looper': 0.6,
    'swarm-reverb': 0.3,
    'grain-cloud': 0.5,
    phaser: 0.12,
    octaves: 0.4,
    'pitch-shifter': 0.4,
    shimmer: 0.3,
    'grain-delay': 0.3,
    'spectral-drifter': 0.3,
    flanger: 0.1,
    cascade: 0.05,
    'freq-shifter': 0.15,
    lattice: 0.1,
    // A record, a radio and anything digital have no place on a cassette by the sea.
    vinyl: 0,
    radio: 0,
    'vintage-digital': 0,
    'low-bitrate': 0,
    glitch: 0,
  },
  voices: {
    'tape:Cassette four-track': 2.2,
    'tape:Under a blanket': 2,
    'tape:Warm thump': 2,
    'tape:Hiss and air': 3,
    'patina:Worn cassette': 1.8,
    // Tape hiss is bright by its nature: held up against the pack's lean away from bright.
    'noise-floor:Tape floor': 10,
    'noise-floor:Breathing tape': 8,
    'noise-floor:Riding hiss': 12,
    'noise-floor:Wall of hiss': 4,
    'noise-floor:Muffled hiss': 2,
    'noise-floor:Faint hiss': 2,
    'noise-floor:Distant rumble': 0.5,
    'noise-floor:Empty room': 0.6,
    'noise-floor:Mains hum': 0.5,
    'plate-reverb:Distant haze': 2,
    'plate-reverb:Dark plate': 1.2,
    'plate-reverb:Long plate': 1.5,
    'noise-floor:Old record': 0,
    'noise-floor:Gap crackle': 0,
    'noise-floor:Radio static': 0,
    'noise-floor:Static notes': 0,
    'patina:Dusty record': 0,
    'patina:Scratched record': 0,
    'patina:Shortwave': 0,
    'patina:Distant station': 0,
    'patina:Kitchen radio': 0,
    'patina:Early sampler': 0,
    'patina:Eight bit': 0,
    'patina:Muffled sampler': 0,
    'micro-looper:Sampler grit': 0,
    'micro-looper:Lo-fi quarter': 0,
    'saturator:Lo-fi': 0,
    'ether-reverb:Cathedral': 0.3,
    're-amp:Bedside radio': 0.3,
    'auto-filter:Phone line': 0.1,
    'auto-filter:Falling high-pass': 0.3,
    'auto-filter:Dub sweep': 0.3,
    'auto-filter:Touch wah': 0.2,
    'ambient-eq:Bright': 0.1,
    'ambient-eq:Thin': 0.3,
    'ambient-eq:Hollow': 0.3,
    'analog-delay:Fifth hop': 0.1,
    'analog-delay:Octave hop': 0.1,
    'analog-delay:Slow lurch': 0.3,
    'spring-reverb:Dub send': 0.3,
    'spring-reverb:Surf drip': 0.3,
    'auto-filter:Resonant peak': 0.2,
    'shaped-reverb:Gated': 0.1,
    'shaped-reverb:Gate steps': 0.1,
    'shaped-reverb:Late wall': 0.3,
    'shaped-reverb:Ghost': 0.5,
    'hall-reverb:Bright hall': 0.4,
    'fdn-reverb:Bright air': 0.4,
    'vowel-reverb:High ee': 0.4,
    'vowel-reverb:High choir': 0.3,
  },
  recipes: {
    'wear-hall': 1.8,
    'wear-hiss-hall': 3,
    'wear-hiss': 2.5,
    'drive-hiss': 2,
    'wear-room': 1.3,
    'drive-wear-room': 1.3,
    'loop-wear-hall': 1.4,
    'motion-wear': 1.3,
    'tone-hall': 1.2,
    'drive-hall': 2.5,
    'drive-room': 1.5,
    'width-hall': 1.5,
    'room-hall': 1.2,
    'echo-hall': 1.6,
    'drive-echo-hall': 1.5,
    'loop-hall': 1.3,
    'pitch-wear': 1.6,
    'pitch-hall': 1.4,
    'hold-wear': 1.3,
    'hold-hall': 1.3,
    'swell-room': 1.2,
    'pulse-hall': 1.2,
    'wear-ceiling': 1.5,
    'wear-glue-ceiling': 1.5,
    'echo-echo': 0.5,
    'pulse-echo': 0.5,
    'motion-motion': 0.4,
    'tone-pulse': 0.5,
    'pitch-grain': 0.3,
    'pitch-width': 0.5,
    'drive-grain': 0.4,
    'grain-tone': 0.5,
    'grain-echo': 0.6,
    'tone-wear': 0.7,
    'wear-tone': 0.6,
    'drive-tone': 0.5,
    'echo-tone': 0.6,
    'pitch-tone': 0.6,
  },
  own: [
    {
      // The pack in one chain: the reverb turned well up, and all of it recorded to cassette.
      id: 'four-track-plate-then-cassette',
      category: 'space',
      lead: 0,
      count: 6,
      slots: [
        {
          role: 'hall',
          devices: ['plate-reverb', 'hall-reverb', 'fdn-reverb', 'expanse', 'ether-reverb'],
          not: ['bright', 'cold', 'strange'],
        },
        {
          role: 'wear',
          devices: ['tape', 'patina'],
          any: ['worn', 'dark', 'warm'],
          not: ['bright', 'cold', 'strange'],
        },
      ],
    },
    {
      // A cassette with its hiss left in and turned up, and the plate behind it.
      id: 'four-track-hiss-left-in',
      category: 'tape',
      lead: 1,
      count: 6,
      slots: [
        {
          role: 'wear',
          devices: ['tape', 'patina'],
          any: ['worn', 'dark', 'warm'],
          not: ['bright', 'cold', 'strange'],
        },
        {
          presets: [
            'noise-floor:Tape floor',
            'noise-floor:Breathing tape',
            'noise-floor:Riding hiss',
            'noise-floor:Faint hiss',
            'noise-floor:Muffled hiss',
            'noise-floor:Wall of hiss',
            'noise-floor:Close mic',
            'noise-floor:Thin bright air',
            'tape:Hiss and air',
          ],
        },
        { role: 'hall', any: ['dark', 'far', 'long'], not: ['bright', 'cold', 'strange'] },
      ],
    },
    {
      // The same line sung twice, a little apart, onto cassette and into the room.
      id: 'four-track-two-takes',
      category: 'tape',
      lead: 0,
      count: 4,
      slots: [
        {
          role: 'width',
          devices: ['stereo-detune', 'chorus', 'tape-echo', 'analog-delay', 'pitch-shifter'],
          not: ['strange', 'narrow'],
        },
        { role: 'wear', any: ['worn', 'dark', 'warm'], not: ['bright', 'cold', 'strange'] },
        { role: 'hall', any: ['dark', 'far', 'long'], not: ['bright', 'cold', 'strange'] },
      ],
    },
    {
      // A sung line on a loop of tape, each pass laid over the last, in a hall that sings back.
      id: 'four-track-sung-in-rounds',
      category: 'echo',
      lead: 0,
      count: 4,
      slots: [
        {
          role: 'loop',
          devices: ['tape-loop', 'echo-memory', 'micro-looper'],
          not: ['bright', 'cold', 'fast', 'strange'],
        },
        { role: 'halo', devices: ['vowel-reverb'], not: ['bright'] },
      ],
    },
    {
      // An electric piano's tremolo into a spring or a plate.
      id: 'four-track-tremolo-and-spring',
      category: 'motion',
      lead: 0,
      count: 4,
      slots: [
        { devices: ['tremolo'], not: ['strange'] },
        {
          role: 'hall',
          devices: ['spring-reverb', 'plate-reverb', 'hall-reverb', 'fdn-reverb'],
          not: ['bright', 'cold', 'strange'],
        },
      ],
    },
    {
      // The machine run at half speed: an octave down, dull, on cassette, far off.
      id: 'four-track-run-slow',
      category: 'pitch',
      lead: 0,
      count: 4,
      slots: [
        {
          role: 'pitch',
          devices: ['half-speed', 'tape-loop', 'micro-looper', 'analog-delay'],
          any: ['low'],
          not: ['strange', 'fast', 'cold', 'frozen'],
        },
        { role: 'wear', any: ['worn', 'dark', 'warm'], not: ['bright', 'cold', 'strange'] },
        { role: 'hall', any: ['dark', 'far', 'long'], not: ['bright', 'cold', 'strange'] },
      ],
    },
  ],
  heads: [
    'Fogbound',
    'Overcast',
    'Porch',
    'Back-porch',
    'Small-hours',
    'Bedroom',
    'Fogbank',
    'Salt-air',
    'Driftwood',
    'Low-cloud',
    'Rain-day',
    'Woodstove',
    'Damp',
    'Harbour',
    'Cannery',
    'Tide-flat',
    'Sandbar',
    'Estuary',
    'Rivermouth',
    'Oilskin',
    'Quilt',
    'Mudroom',
    'One-take',
    'Bounced',
    'Track-four',
    'Homemade',
    'Overdubbed',
    'Ninety-minute',
    'Off-season',
    'November',
    'Grey',
    'Wet-road',
    'Shore-road',
    'Last-ferry',
    'Slack-tide',
    'Unheated',
    'Borrowed',
    'Hand-labelled',
    'Pencilled',
    'Second-hand',
    'Tidewater',
    'Lean-to',
    'Rain-gutter',
    'Net-shed',
    'Marsh',
    'Dune-grass',
    'Rented',
    'Sunday',
    'Headphone',
    'Closed-door',
    'Hemlock',
    'Alder',
    'Mudflat',
    'River-bar',
    'Spare-room',
    'Punched-in',
    'Mix-down',
    'Pause-button',
    'Trestle',
    'Shingle',
    'Tarpaper',
    'Kerosene',
    'Raincoat',
    'Mill-town',
    'Space-heater',
    { word: 'Blanketed', for: ['dark'] },
    { word: 'Lid-shut', for: ['dark'] },
    { word: 'Hiss-deep', for: ['noisy'] },
    { word: 'Far-shore', for: ['far'] },
    { word: 'Next-room', for: ['far'] },
    { word: 'Slowed', for: ['low'] },
    { word: 'Backwards', for: ['backwards'] },
    { word: 'Slack-belt', for: ['unsteady'] },
    { word: 'Wavering', for: ['unsteady'] },
    { word: 'Buried', for: ['heavy'] },
    { word: 'Played-out', for: ['worn'] },
  ],
  tails: [
    'in coast fog',
    'in fog',
    'at low tide',
    'till morning',
    'in the rain',
    'under cloud',
    'through fog',
    'in wet wool',
    'on side b',
    'in salt air',
    'in november',
    'out of season',
    'on the ebb',
    'in one take',
    'under eaves',
    'in fine rain',
    'under wool',
    'by the stove',
    'on track four',
    'still rolling',
    'kept indoors',
    'off the jetty',
    'up the stairs',
    'by one lamp',
    'between takes',
    'at slack tide',
    'by the shore',
    { word: 'one room over', for: ['far'] },
    { word: 'far back', for: ['far'] },
    { word: 'in the dark', for: ['dark'] },
    { word: 'under hiss', for: ['noisy'] },
    { word: 'run slow', for: ['low'] },
    { word: 'flipped over', for: ['backwards'] },
  ],
  avoid: ['shade', 'gate'],
}
