// Sunburnt Laptop Guitar: a guitar fed through a patch on a laptop until
// the chords are a bright fizzing haze with the tune still in it. Its chains
// are gain first, then grains, skips and a starved stream; the room is a
// plate or the amp's own; nothing turns slowly, nothing is on old tape.

import { type PackPalette } from './types'

export const PALETTE: PackPalette = {
  pack: 'laptop-guitar',
  groups: { space: 11, echo: 13, tape: 24, motion: 6, texture: 27, pitch: 13, master: 6 },
  traits: {
    bright: 1.6,
    high: 1.3,
    cold: 1.2,
    wide: 1.2,
    backwards: 1.3,
    fast: 1.1,
    dark: 0.6,
    low: 0.55,
    far: 0.7,
    slow: 0.7,
    clean: 0.6,
    narrow: 0.5,
    frozen: 0.7,
    unsteady: 0.7,
  },
  devices: {
    glitch: 4,
    'grain-cloud': 4.5,
    'spectral-blur': 3.2,
    saturator: 2.4,
    'low-bitrate': 2,
    'analog-drive': 2,
    'vintage-digital': 2,
    'grain-delay': 2,
    'plate-reverb': 2.6,
    'freq-shifter': 2,
    're-amp': 1.7,
    'spectral-drifter': 1.5,
    'reverse-delay': 1.4,
    'micro-looper': 1.3,
    cascade: 1.2,
    'pitch-shifter': 0.8,
    'shaped-reverb': 0.8,
    patina: 0.7,
    expanse: 0.7,
    'echo-memory': 0.7,
    sustainer: 0.6,
    shimmer: 0.25,
    'bloom-reverb': 0.6,
    'analog-delay': 0.5,
    'tape-echo': 0.4,
    chorus: 0.3,
    octaves: 0.4,
    flanger: 0.05,
    tremolo: 0.6,
    radio: 0.25,
    phaser: 0.12,
    'swarm-reverb': 0.3,
    'half-speed': 0.25,
    'tape-loop': 0.15,
    sympathetic: 0.12,
    tape: 0.2,
    'vowel-reverb': 0.1,
    lattice: 0.2,
    'pad-follower': 0,
    vinyl: 0.05,
    rotary: 0,
  },
  voices: {
    'grain-cloud:Soft cloud': 1.6,
    'grain-cloud:Octave rain': 1.5,
    'glitch:Gentle stumble': 1.5,
    'glitch:Skipping disc': 1.6,
    'saturator:Fuzz pedal': 1.6,
    'analog-drive:Bite': 1.5,
    'low-bitrate:Fizzing phases': 1.6,
    'spectral-blur:Hanging mist': 1.5,
    'grain-delay:High glitter': 1.5,
    'patina:Early sampler': 3,
    'patina:Eight bit': 3,
    'patina:Valve fuzz': 3,
    'patina:Hot valve': 2,
    'patina:Worn cassette': 0.2,
    'patina:Falling apart': 0.2,
    'patina:Dusty record': 0.2,
    'patina:Scratched record': 0.2,
    'patina:Kitchen radio': 0.2,
    'patina:Quarter inch reel': 0.3,
    'patina:New tape': 0.4,
    'stereo-widener:Mono': 0.1,
    'auto-filter:Low-pass gate': 0,
    'ambient-eq:Muffled': 0,
    'ambient-eq:Bright': 2,
    'ambient-eq:Hollow': 1.5,
  },
  recipes: {
    'drive-grain': 3,
    'grain-wear': 3,
    'grain-hall': 2.5,
    'grain-room': 2.5,
    'grain-echo': 2,
    'swell-grain-hall': 2,
    'grain-tone': 1.5,
    'drive-wear': 2,
    'drive-wear-room': 1.8,
    'drive-tone': 1.3,
    'wear-wear': 1.4,
    'drive-hall': 3,
    'drive-room': 3,
    'drive-echo': 1.6,
    'drive-echo-hall': 1.4,
    'drive-pitch': 1.8,
    'pitch-grain': 1.8,
    'pitch-wear': 1.4,
    'drive-motion': 3,
    'drive-motion-hall': 2,
    'drive-ceiling': 1.5,
    'drive-glue-ceiling': 1.5,
    'drive-tone-ceiling': 1.5,
    'swell-hall': 0.7,
    'loop-wear': 0.6,
    'loop-wear-hall': 0.6,
    'motion-wear': 0.5,
    'room-hall': 0.5,
    'room-halo': 0.5,
    'halo-hall': 0.3,
    'width-motion': 0.4,
    'motion-motion': 0.3,
    'swell-halo': 0.5,
    'swell-halo-hall': 0.5,
    'pulse-echo': 0.5,
    'echo-echo': 0.5,
    'hold-hall': 0.5,
    'hold-wear': 0.5,
    'hold-tone': 0.4,
    'hold-motion': 0.4,
    'hold-motion-hall': 0.4,
    'swell-hold': 0.4,
    'swell-room': 0.4,
    'hold-halo': 0.3,
    'pitch-hold': 0.5,
    'swell-width': 0.3,
  },
  own: [
    {
      // The pack in one chain: a chord pushed into fuzz, torn into a cloud of grains, hung in a plate or a hall.
      id: 'laptop-guitar-fuzz-into-grains',
      category: 'texture',
      lead: 1,
      count: 6,
      slots: [
        {
          role: 'drive',
          devices: ['saturator', 'analog-drive', 're-amp', 'patina'],
          not: ['faint'],
        },
        {
          role: 'grain',
          devices: ['grain-cloud', 'glitch', 'grain-delay', 'spectral-blur', 'cascade'],
        },
        {
          role: 'hall',
          devices: ['plate-reverb', 'hall-reverb', 'fdn-reverb', 'ether-reverb', 'spring-reverb'],
          not: ['dark', 'heavy'],
        },
      ],
    },
    {
      // A buffer that skips and sticks, then sent down a line that starves it.
      id: 'laptop-guitar-skipping-buffer',
      category: 'texture',
      lead: 0,
      count: 5,
      slots: [
        { role: 'grain', devices: ['glitch'] },
        { role: 'wear', devices: ['low-bitrate', 'vintage-digital', 'patina'], not: ['noisy'] },
      ],
    },
    {
      // Gain first, then the whole spectrum blurred until the chord hangs as a haze.
      id: 'laptop-guitar-gain-then-haze',
      category: 'tape',
      lead: 0,
      count: 5,
      slots: [
        { role: 'drive', devices: ['saturator', 'analog-drive', 'patina'], not: ['dark'] },
        { role: 'grain', devices: ['spectral-blur', 'low-bitrate', 'grain-cloud'] },
      ],
    },
    {
      // Old converters, then out of the machine and into a small amplifier in a room.
      id: 'laptop-guitar-bits-through-amp',
      category: 'tape',
      lead: 0,
      count: 4,
      slots: [
        { role: 'wear', devices: ['vintage-digital', 'low-bitrate', 'patina'], not: ['noisy'] },
        { role: 'drive', devices: ['re-amp', 'analog-drive'] },
      ],
    },
    {
      // Grains thrown an octave up that fall back over the chord as glitter, in a plate.
      id: 'laptop-guitar-glitter',
      category: 'pitch',
      lead: 0,
      count: 4,
      slots: [
        {
          role: 'pitch',
          devices: ['grain-cloud', 'grain-delay', 'cascade', 'spectral-blur', 'pitch-shifter'],
          any: ['high'],
          not: ['strange'],
        },
        { role: 'hall', devices: ['plate-reverb', 'hall-reverb', 'fdn-reverb', 'ether-reverb'] },
      ],
    },
    {
      // Each phrase handed back in reverse, then cut up or scattered.
      id: 'laptop-guitar-reversed-and-cut',
      category: 'echo',
      lead: 0,
      count: 4,
      slots: [
        { role: 'echo', want: ['backwards'] },
        { role: 'grain', devices: ['grain-cloud', 'glitch', 'spectral-blur', 'low-bitrate'] },
      ],
    },
  ],
  heads: [
    'Sunburnt',
    'Boardwalk',
    'Deckchair',
    'Pier-end',
    'Postcard',
    'Overexposed',
    'Bleached',
    'Salted',
    'Heat-haze',
    'Noon',
    'Midday',
    'Poolside',
    'Promenade',
    'Parasol',
    'Sunstruck',
    'Sun-faded',
    'Peeling',
    'Blistered',
    'Kiosk',
    'Jetty',
    'Dune',
    'Driftwood',
    'Tideline',
    'Low-season',
    'August',
    'Heatwave',
    'Balcony',
    'Rooftop',
    'Tramline',
    'Courtyard',
    'Laptop',
    'Desktop',
    'Screen-lit',
    'Low-battery',
    'Borrowed',
    'Bedroom',
    'Rendered',
    'Bounced',
    'Unsaved',
    'Overheated',
    'Souvenir',
    'Holiday',
    'Remembered',
    'Patched',
    'Buffered',
    'Pixel',
    'Arcade',
    'Quayside',
    'Windbreak',
    'Siesta',
    'Soundcard',
    'Line-in',
    'Snapshot',
    'Autosave',
    'Trackpad',
    'Terrace',
    'Awning',
    'Breakwater',
    'Lifeguard',
    'Esplanade',
    'Mixdown',
    { word: 'Glittering', for: ['bright', 'high'] },
    { word: 'Blinding', for: ['bright'] },
    { word: 'Reversed', for: ['backwards'] },
    { word: 'Corrupted', for: ['worn'] },
    { word: 'Pixelated', for: ['cold'] },
    { word: 'Crackling', for: ['noisy'] },
    { word: 'Far-pier', for: ['far'] },
    { word: 'Octave-up', for: ['high'] },
    { word: 'Paused', for: ['frozen'] },
    { word: 'Melting', for: ['unsteady'] },
    { word: 'Jittery', for: ['fast'] },
    { word: 'After-dark', for: ['dark'] },
  ],
  tails: [
    'on the pier',
    'at noon',
    'in the patch',
    'in the buffer',
    'on shingle',
    'by the kiosk',
    'off the lid',
    'in heat haze',
    'in salt air',
    'out of season',
    'on a postcard',
    'gone pink',
    'bleached out',
    'in august',
    'on hot tiles',
    'in deckchairs',
    'on a balcony',
    'down the line',
    'on battery',
    'in the glare',
    'from memory',
    'by the water',
    { word: 'in reverse', for: ['backwards'] },
    { word: 'an octave up', for: ['high'] },
    { word: 'over the bay', for: ['far'] },
    { word: 'in glitter', for: ['high'] },
    { word: 'in crackle', for: ['noisy'] },
    { word: 'breaking up', for: ['worn'] },
  ],
}
