// Cornish Lucid Dreams: pads and bells remembered from sleep on a far
// south-west coast. Its chains are a detuned double or a dull bucket-brigade
// echo left in a long dark plate, heard through old converters and tape that
// wows; a slow shifter turns under the reverb and some of it goes sour.
// Nothing is bright, clean or quick, and nothing is in tune for long.

import { type PackPalette } from './types'

export const PALETTE: PackPalette = {
  pack: 'lucid',
  groups: { space: 26, echo: 20, tape: 16, motion: 12, texture: 9, pitch: 11, master: 6 },
  traits: {
    dark: 2,
    unsteady: 1.8,
    low: 1.4,
    worn: 1.3,
    warm: 1.3,
    far: 1.3,
    long: 1.3,
    slow: 1.3,
    wide: 1.1,
    strange: 0.85,
    backwards: 0.8,
    short: 0.7,
    noisy: 0.6,
    frozen: 0.6,
    clean: 0.6,
    high: 0.3,
    fast: 0.3,
    bright: 0.25,
  },
  devices: {
    'plate-reverb': 5,
    'analog-delay': 3,
    tape: 3,
    chorus: 3,
    'vintage-digital': 2.4,
    'stereo-detune': 2.2,
    'freq-shifter': 1.8,
    'ether-reverb': 1.6,
    'half-speed': 1.5,
    'fdn-reverb': 1.4,
    'hall-reverb': 1.3,
    patina: 1.3,
    expanse: 1.2,
    'vowel-reverb': 1.2,
    'bloom-reverb': 1.1,
    'shaped-reverb': 0.8,
    'ambient-eq': 0.6,
    'reverse-delay': 0.7,
    'echo-memory': 0.7,
    'noise-floor': 0.7,
    sustainer: 0.7,
    'tape-loop': 0.6,
    'micro-looper': 0.6,
    'spectral-drifter': 0.6,
    'analog-drive': 0.6,
    sympathetic: 0.4,
    phaser: 0.5,
    'tape-echo': 0.5,
    'low-bitrate': 0.4,
    saturator: 0.5,
    'pad-follower': 0.5,
    'grain-cloud': 0.5,
    'grain-delay': 0.5,
    flanger: 0.4,
    'pitch-shifter': 0.4,
    radio: 0.3,
    tremolo: 0.3,
    cascade: 0.2,
    rotary: 0.2,
    shimmer: 0.25,
    octaves: 0.2,
    vinyl: 0.2,
    're-amp': 0.2,
    glitch: 0.05,
    lattice: 0,
  },
  voices: {
    'plate-reverb:Dark plate': 1.6,
    'plate-reverb:Long plate': 1.4,
    'plate-reverb:Medium plate': 1.6,
    'plate-reverb:Faint sheen': 1.5,
    'analog-delay:Falling tape': 0.35,
    'freq-shifter:Slow drift': 1.5,
    'tape:Seasick': 1.4,
    'chorus:Metallic comb': 1.4,
    'flanger:Metal resonator': 8,
    'freq-shifter:Sunken bell': 2.5,
    'freq-shifter:Bell metal': 3,
    'freq-shifter:Radio ring': 1.8,
    'plate-reverb:Bright plate': 0.3,
    'analog-delay:Clean echo': 0.3,
    'plate-reverb:Full wet send': 0.08,
    'hall-reverb:Full wet send': 0.2,
    'fdn-reverb:Full wet send': 0.2,
    'vowel-reverb:High ee': 0.3,
    'vowel-reverb:High choir': 0.3,
    'saturator:Blown speaker': 0.2,
    'analog-drive:Torn cone': 0.2,
    'analog-drive:Iron melt': 0.2,
    'ether-reverb:Cathedral': 0.4,
    'echo-memory:Swarm': 0.2,
    'tape-echo:Hovering wash': 0.6,
    'auto-filter:Screaming': 0,
    'flanger:Classic jet': 0.3,
    'low-bitrate:Stuck stream': 0.3,
    'low-bitrate:Bad connection': 0.3,
    'low-bitrate:Fizzing phases': 0.3,
    'patina:Scratched record': 0.4,
    'patina:Dusty record': 0.4,
    'ambient-comp:Dense pad': 0.3,
    'ambient-comp:Pump': 0.2,
    'auto-filter:Low-pass gate': 0.6,
    'spring-reverb:Surf drip': 0.4,
    'fet-limiter:Squash': 0.05,
    'fet-limiter:Tucked under': 0.3,
    'fet-limiter:Flattened': 0.05,
    'ambient-limiter:Pinned': 0.1,
    'fet-limiter:Drive': 0.4,
    'low-bitrate:Ghost': 0.3,
    'low-bitrate:Thin air': 0.3,
    'saturator:Parallel shine': 0.3,
    'ambient-limiter:Loud': 0.5,
    'reverse-delay:Rising glass': 0.3,
    'ambient-eq:Bright': 0.2,
    'hall-reverb:Bright hall': 0.3,
    // Presets whose own nouns would give this pack a name it must not have.
    'half-speed:Blurred half': 0,
    'stereo-detune:Cloud': 0,
    'spectral-blur:Softened attacks': 0,
    'spectral-drifter:Reversed smear': 0,
    'grain-cloud:Detuned double': 0,
    'glitch:Smears underneath': 0,
    'glitch:Total collapse': 0,
    'glitch:Bouncing': 0,
  },
  recipes: {
    'width-hall': 3,
    'tone-hall': 1.5,
    'width-room': 1.5,
    'room-hall': 1.3,
    'hall-tone': 1.2,
    'halo-hall': 0.8,
    'room-halo': 0.6,
    'swell-halo-hall': 0.6,
    'drive-hall': 0.4,
    'drive-room': 0.4,
    'echo-hall': 3.5,
    'echo-room': 2.5,
    'motion-echo': 2.5,
    'echo-width': 1.5,
    'echo-echo': 0.5,
    'drive-echo': 0.1,
    'drive-echo-hall': 0.4,
    'loop-hall': 0.25,
    'loop-room': 0.25,
    'loop-echo': 0.25,
    'tone-loop': 0.25,
    'loop-tone-hall': 0.25,
    'wear-hall': 3,
    'wear-echo': 3,
    'wear-room': 2.5,
    'motion-wear': 2.5,
    'tone-wear-echo': 2,
    'tone-wear': 1.2,
    'wear-hiss': 0.4,
    'wear-hiss-hall': 0.3,
    'loop-wear': 0.4,
    'loop-wear-hall': 0.4,
    'drive-wear': 0.3,
    'drive-wear-room': 0.3,
    'drive-tone': 0.1,
    'drive-hiss': 0.1,
    'motion-hall': 3,
    'motion-room': 2,
    'motion-echo-hall': 2.5,
    'width-motion': 2,
    'motion-halo': 1.2,
    'motion-tone': 0.1,
    'drive-motion': 0.1,
    'drive-motion-hall': 0.2,
    'pulse-echo': 0,
    'pulse-hall': 0,
    'pulse-room': 0,
    'tone-pulse': 0,
    'hold-hall': 1.6,
    'hold-wear': 1.6,
    'hold-motion': 1.5,
    'grain-wear': 1.2,
    'swell-room': 0.5,
    'swell-hold': 0.7,
    'swell-grain-hall': 0.6,
    'drive-grain': 0.4,
    'pitch-wear': 3,
    'pitch-hall': 2.5,
    'pitch-room': 2,
    'pitch-width': 1.5,
    'pitch-echo': 1.3,
    'pitch-motion': 1.3,
    'pitch-grain': 0.5,
    'pitch-hold': 0.3,
    'drive-pitch': 0.1,
    'wear-ceiling': 2,
    'wear-glue-ceiling': 1.6,
    'width-ceiling': 1.4,
    'tone-width-ceiling': 1.4,
    'tone-ceiling': 1.2,
    'drive-ceiling': 0.4,
    'drive-glue-ceiling': 0.4,
    'drive-tone-ceiling': 0.4,
  },
  own: [
    {
      // The pack in one chain: a pad pulled a little out of tune with itself, left in a long dull plate.
      id: 'lucid-detuned-in-plate',
      category: 'space',
      lead: 1,
      count: 6,
      slots: [
        { devices: ['stereo-detune', 'chorus'], not: ['fast', 'strange'] },
        {
          role: 'hall',
          devices: ['plate-reverb', 'ether-reverb', 'fdn-reverb', 'hall-reverb'],
          not: ['bright', 'heavy'],
        },
      ],
    },
    {
      // A dull bucket-brigade echo that sways, and the plate it dies in.
      id: 'lucid-dull-echo-in-plate',
      category: 'echo',
      lead: 0,
      count: 6,
      slots: [
        { role: 'echo', devices: ['analog-delay'], not: ['fast', 'clean'] },
        {
          role: 'hall',
          devices: ['plate-reverb', 'ether-reverb', 'fdn-reverb', 'expanse'],
          any: ['dark', 'long', 'far', 'warm'],
        },
      ],
    },
    {
      // Everything sampled first: old converters, then a dull echo, then a small plate or room.
      id: 'lucid-old-converters',
      category: 'tape',
      lead: 0,
      count: 5,
      slots: [
        { role: 'wear', devices: ['vintage-digital', 'patina'], any: ['cold', 'dark'] },
        { role: 'echo', devices: ['analog-delay', 'tape-echo'], not: ['bright', 'fast', 'clean'] },
        { role: 'room', not: ['bright'] },
      ],
    },
    {
      // Something turning slowly out of true under a reverb: two tones that beat.
      id: 'lucid-shifter-under-plate',
      category: 'motion',
      lead: 0,
      count: 4,
      slots: [
        { devices: ['freq-shifter'], not: ['fast', 'strange'] },
        { role: 'hall', not: ['bright', 'heavy'] },
      ],
    },
    {
      // The last seconds again at half speed, an octave under, on a cassette in a small room.
      id: 'lucid-half-speed-cassette',
      category: 'pitch',
      lead: 0,
      count: 4,
      slots: [
        { role: 'pitch', devices: ['half-speed', 'micro-looper', 'tape-loop'], any: ['low'] },
        { role: 'wear', devices: ['tape', 'patina'], not: ['bright', 'clean'] },
        { role: 'room', not: ['bright'] },
      ],
    },
    {
      // Voices from the other side of a wall: the top shut off, then a hall that hums along.
      id: 'lucid-sung-through-walls',
      category: 'space',
      lead: 1,
      count: 4,
      slots: [
        { role: 'tone', any: ['dark', 'far'] },
        { role: 'halo', devices: ['vowel-reverb', 'bloom-reverb'], not: ['bright', 'high'] },
      ],
    },
  ],
  heads: [
    'Half-asleep',
    'Bedside',
    'Night-light',
    'Landing-light',
    'Small-hours',
    'Before-dawn',
    'Moorland',
    'Tin-mine',
    'Adit',
    'Engine-house',
    'Mineshaft',
    'Sea-fret',
    'Cove',
    'Slate-roof',
    'Granite',
    'Hedgerow',
    'Lane-end',
    'Pylon',
    'Fuse-box',
    'Fence-wire',
    'Shed',
    'Yard',
    'Floorboard',
    'Upstairs',
    'Next-door',
    'Lullaby',
    'Dreamt',
    'Sleepwalk',
    'Half-dreamt',
    'Eyes-shut',
    'Peninsula',
    'Far-west',
    'Headland',
    'Foghorn',
    'Lighthouse',
    'Wheal',
    'Tin-roof',
    'Village-hall',
    'Box-room',
    'Bunk-bed',
    'Eiderdown',
    'Mizzle',
    'Gorse',
    'Bracken',
    'Creek',
    'Low-water',
    'Inland',
    'Midwinter',
    'Bedtime',
    'Back-lane',
    'Copper',
    'China-clay',
    'Remembered',
    'Misheard',
    'Half-lit',
    'Hymnbook',
    'Last-bus',
    { word: 'Wonky', for: ['unsteady'] },
    { word: 'Seasick', for: ['unsteady'] },
    { word: 'Unlit', for: ['dark'] },
    { word: 'Lights-out', for: ['dark'] },
    { word: 'Down-the-lane', for: ['far'] },
    { word: 'Under-floor', for: ['low'] },
    { word: 'Drowsy', for: ['slow'] },
    { word: 'Threadbare', for: ['worn'] },
    { word: 'Tinny', for: ['cold'] },
    { word: 'Uneasy', for: ['strange'] },
    { word: 'Back-to-front', for: ['backwards'] },
    { word: 'Half-heard', for: ['faint'] },
  ],
  tails: [
    'in the lane',
    'on the moor',
    'in sea fret',
    'half asleep',
    'before dawn',
    'at lights out',
    'under the bed',
    'from upstairs',
    'in the adit',
    'by nightlight',
    'heard asleep',
    'in a dream',
    'off the coast',
    'past the shed',
    'in the yard',
    'after rain',
    'at low water',
    'down the mine',
    'under slates',
    'barely awake',
    'by the hedge',
    'from the cove',
    'on the stairs',
    { word: 'through walls', for: ['dark', 'far'] },
    { word: 'gone sour', for: ['strange'] },
    { word: 'out of tune', for: ['unsteady'] },
    { word: 'in reverse', for: ['backwards'] },
    { word: 'from far off', for: ['far'] },
    { word: 'sunk low', for: ['low'] },
    { word: 'still ringing', for: ['long'] },
    { word: 'never fading', for: ['frozen'] },
  ],
  avoid: ['metal'],
}
