// Faded Nature Film: detuned synthesizers copied to a reel that wobbles, as
// heard under a schools programme with the blinds down. Its chains are tape
// that sways, a slow phaser, a chorus, the grit of an old sampler and dark
// repeats; a room is a small plate; nothing is clean, bright or vast.

import { type PackPalette } from './types'

export const PALETTE: PackPalette = {
  pack: 'nature-film',
  groups: { space: 11, echo: 16, tape: 28, motion: 19, texture: 9, pitch: 10, master: 7 },
  traits: {
    unsteady: 2.2,
    warm: 1.6,
    worn: 1.5,
    dark: 1.4,
    narrow: 1.2,
    noisy: 1.1,
    low: 1.1,
    slow: 1.1,
    fast: 0.9,
    far: 0.9,
    cold: 0.8,
    long: 0.5,
    heavy: 0.5,
    bright: 0.5,
    clean: 0.5,
    strange: 0.3,
    high: 0.2,
    frozen: 0.3,
  },
  devices: {
    tape: 2.4,
    phaser: 2.6,
    chorus: 2.2,
    'vintage-digital': 1.9,
    patina: 2.2,
    'stereo-detune': 2.6,
    'tape-echo': 1.8,
    'analog-delay': 1.8,
    'plate-reverb': 2.5,
    'half-speed': 1.3,
    'auto-filter': 1.3,
    'analog-drive': 1.3,
    'micro-looper': 1.2,
    'noise-floor': 1.2,
    vinyl: 0.8,
    tremolo: 1.1,
    saturator: 0.9,
    flanger: 0.45,
    radio: 0.8,
    'spring-reverb': 0.8,
    'hall-reverb': 0.7,
    'ether-reverb': 0.7,
    'fdn-reverb': 0.7,
    'tape-loop': 0.7,
    swell: 0.7,
    'shaped-reverb': 0.6,
    'pad-follower': 0.8,
    'echo-memory': 0.5,
    'freq-shifter': 0.5,
    'low-bitrate': 0.5,
    'spectral-blur': 0.8,
    'pitch-shifter': 0.5,
    sustainer: 0.5,
    're-amp': 0.5,
    expanse: 0.3,
    'grain-cloud': 0.4,
    'grain-delay': 0.4,
    'spectral-drifter': 0.4,
    rotary: 0.06,
    octaves: 0.3,
    'vowel-reverb': 0.08,
    'bloom-reverb': 0.45,
    glitch: 0.3,
    cascade: 0.04,
    lattice: 0.05,
    'swarm-reverb': 0.04,
    sympathetic: 0.03,
    shimmer: 0.03,
  },
  voices: {
    // A flanger in all but its device: weighed as this pack weighs flangers.
    'tremolo:Drifting comb': 0.45,
    'tape:Seasick': 1.8,
    'chorus:Warped tape': 1.8,
    'phaser:Warm six-stage': 1.5,
    'patina:Early sampler': 2.5,
    'patina:Muffled sampler': 1.8,
    'micro-looper:Sampler grit': 2,
    'micro-looper:Lo-fi quarter': 2,
    'vintage-digital:Sampler': 1.5,
    'tremolo:Pitch wobble': 1.5,
    'auto-filter:Screaming': 0.1,
    'auto-filter:Squelch': 0.3,
    'saturator:Fuzz pedal': 0,
    'patina:Valve fuzz': 0,
    'analog-drive:Dark fuzz': 0,
    'analog-drive:Iron melt': 0,
    'analog-drive:Torn cone': 0,
    'glitch:Total collapse': 0.1,
    'ambient-eq:Bright': 0.3,
    'analog-delay:Octave hop': 0.15,
    'analog-delay:Fifth hop': 0.15,
    'fet-limiter:Flattened': 0.5,
    'vinyl:Ballroom 78': 0.1,
    'vinyl:Parlour 78': 0.1,
    'grain-cloud:Rising shimmer': 0,
    'fdn-reverb:Pulsing gate': 0.4,
    'expanse:Low cathedral': 0.3,
    'expanse:Event horizon': 0.2,
    'hall-reverb:Cathedral': 0.2,
    'hall-reverb:Vast nave': 0.2,
    'fdn-reverb:Open valley': 0.5,
    'fdn-reverb:Endless tail': 0.4,
    'ether-reverb:Dark infinite': 0.5,
    'plate-reverb:Full wet send': 0.5,
    'tremolo:Wandering pan': 0.5,
  },
  recipes: {
    'motion-wear': 2,
    'pitch-wear': 1.8,
    'wear-echo': 1.5,
    'wear-room': 1.4,
    'tone-wear': 1.3,
    'drive-wear': 1.2,
    'grain-wear': 2,
    'hold-wear': 2.2,
    'hold-tone': 1.3,
    'tone-room-hall': 1.4,
    'motion-echo': 1.5,
    'echo-room': 1.3,
    'drive-echo': 1.3,
    'motion-room': 1.4,
    'width-motion': 1.5,
    'motion-motion': 1.2,
    'pitch-motion': 1.3,
    'pitch-width': 1.2,
    'drive-room': 1.5,
    'width-room': 1.5,
    'loop-hall': 0.7,
    'loop-tone-hall': 0.7,
    'swell-hall': 0.6,
    'pulse-echo': 0.6,
    'pulse-hall': 0.6,
    'pulse-room': 0.6,
    'hall-glue': 0.5,
    'wear-ceiling': 0.7,
    'room-halo': 0.15,
    'tone-halo': 0.3,
    'echo-halo': 0.4,
    'motion-halo': 0.15,
    'halo-hall': 0.1,
    'swell-halo': 0.3,
    'swell-halo-hall': 0.05,
    'pitch-halo': 0.3,
    'hold-halo': 0.1,
  },
  own: [
    {
      // The pack in one chain: a detuned double, copied to a reel that wobbles, in a small room.
      id: 'nature-film-detuned-off-the-reel',
      category: 'tape',
      lead: 1,
      count: 5,
      slots: [
        { role: 'width', devices: ['stereo-detune', 'chorus', 'analog-delay', 'tape-echo'] },
        {
          role: 'wear',
          devices: ['tape', 'patina'],
          any: ['unsteady', 'warm'],
          not: ['strange', 'clean'],
        },
        { role: 'room', not: ['bright', 'far'] },
      ],
    },
    {
      // A string machine's slow phaser, then onto tape that wows a little.
      id: 'nature-film-phased-then-taped',
      category: 'motion',
      lead: 0,
      count: 5,
      slots: [
        { role: 'motion', devices: ['phaser'] },
        { role: 'wear', devices: ['tape', 'patina'], not: ['strange', 'clean'] },
      ],
    },
    {
      // Played back by an old sampler, copied to tape, with dark repeats behind it.
      id: 'nature-film-sampled-then-taped',
      category: 'tape',
      lead: 0,
      count: 5,
      slots: [
        { role: 'wear', devices: ['vintage-digital', 'micro-looper'], not: ['strange'] },
        { role: 'wear', devices: ['tape', 'patina', 'chorus'], any: ['unsteady', 'warm'] },
        {
          role: 'echo',
          devices: ['tape-echo', 'analog-delay'],
          not: ['clean', 'strange', 'cold'],
        },
      ],
    },
    {
      // A simple lead: vibrato or chorus, then repeats that dull as they go.
      id: 'nature-film-lead-in-dark-repeats',
      category: 'echo',
      lead: 1,
      count: 4,
      slots: [
        { devices: ['chorus', 'tremolo'], any: ['unsteady', 'slow'], not: ['strange', 'clean'] },
        {
          role: 'echo',
          devices: ['analog-delay', 'tape-echo'],
          any: ['warm', 'dark', 'worn', 'unsteady'],
        },
      ],
    },
    {
      // A sample slowed to half speed, on a reel or a record that sways.
      id: 'nature-film-slowed-sample',
      category: 'pitch',
      lead: 0,
      count: 4,
      slots: [
        { role: 'pitch', devices: ['half-speed', 'micro-looper', 'tape-loop'], any: ['low'] },
        { role: 'wear', devices: ['tape', 'patina', 'vinyl', 'chorus'], any: ['unsteady'] },
      ],
    },
    {
      // A phrase run backwards, as when the reel is wound back, and dulled by the tape.
      id: 'nature-film-wound-back',
      category: 'echo',
      lead: 0,
      count: 3,
      slots: [
        { devices: ['reverse-delay', 'tape-loop', 'micro-looper'], want: ['backwards'] },
        { role: 'wear', devices: ['tape', 'patina'], not: ['strange', 'clean'] },
      ],
    },
  ],
  heads: [
    'Classroom',
    'Projector',
    'Schools',
    'Closedown',
    'Test-card',
    'Half-term',
    'Last-period',
    'Mid-morning',
    'Autumn-term',
    'Blinds-down',
    'Wheeled-in',
    'Blackboard',
    'Chalk-dust',
    'Jotter',
    'Nature-table',
    'Frogspawn',
    'Field-trip',
    'Duffel-coat',
    'Corduroy',
    'Parquet',
    'Seventies',
    'Narrated',
    'Voice-over',
    'Interlude',
    'Regional',
    'Film-strip',
    'Sprocket',
    'Take-up',
    'Changeover',
    'Sixteen-mil',
    'Magenta',
    'Film-can',
    'Hired-print',
    'Heather',
    'Moorland',
    'Lochside',
    'Peat-water',
    'Glen',
    'Bothy',
    'Tin-roof',
    'Hillside',
    'Estuary',
    'Rock-pool',
    'Tideline',
    'Hedgerow',
    'Bracken',
    'Bog-cotton',
    'Gorse',
    'Drizzle',
    'Overcast',
    'Haar',
    'Curlew',
    'Otter',
    'Kestrel',
    'Osprey',
    'Lapwing',
    'Red-deer',
    'Salmon-run',
    'Caravan',
    { word: 'Faded', for: ['worn', 'dark'] },
    { word: 'Worn-print', for: ['worn'] },
    { word: 'Buckled', for: ['unsteady'] },
    { word: 'Wobbling', for: ['unsteady'] },
    { word: 'Off-speed', for: ['unsteady'] },
    { word: 'Slowed-down', for: ['low'] },
    { word: 'Wound-back', for: ['backwards'] },
    { word: 'Lights-off', for: ['dark'] },
    { word: 'Crackling', for: ['noisy'] },
    { word: 'Long-lens', for: ['far'] },
    { word: 'One-speaker', for: ['narrow'] },
  ],
  tails: [
    'in the glen',
    'by the loch',
    'on the moor',
    'in heather',
    'at half-term',
    'in class',
    'after lunch',
    'at closedown',
    'on film',
    'in corduroy',
    'for schools',
    'from a hide',
    'in drizzle',
    'under haar',
    'in a bothy',
    'in the rushes',
    'in the can',
    'gone magenta',
    'over credits',
    'on a wet day',
    { word: 'in long shot', for: ['far'] },
    { word: 'run slow', for: ['low'] },
    { word: 'spooled back', for: ['backwards'] },
    { word: 'on a lean', for: ['unsteady'] },
    { word: 'on pause', for: ['frozen'] },
  ],
  avoid: ['warp'],
}
