// Neon Rain, 2019: a wet city at night as the early eighties imagined it.
// Its chains are a chorus, dark repeats and a digital hall the size of the
// city, heard through early converters: slow swells that open into the hall,
// glitter runs of rising octaves, a doubled lead with repeats behind it,
// strings in slow motion. Everything is wide and long; nothing is worn out,
// noisy, narrow or broken.

import { type PackPalette } from './types'

export const PALETTE: PackPalette = {
  pack: 'neon-rain',
  groups: { space: 30, echo: 17, tape: 8, motion: 16, texture: 9, pitch: 14, master: 6 },
  traits: {
    long: 1.6,
    wide: 1.5,
    slow: 1.3,
    far: 1.2,
    clean: 1.2,
    high: 1.15,
    cold: 1.1,
    warm: 1.1,
    heavy: 0.6,
    unsteady: 0.6,
    frozen: 0.5,
    short: 0.5,
    fast: 0.4,
    worn: 0.5,
    narrow: 0.1,
    noisy: 0.3,
    backwards: 0.2,
    strange: 0.02,
  },
  devices: {
    'hall-reverb': 3.5,
    chorus: 3,
    'analog-delay': 3,
    'vintage-digital': 2.6,
    expanse: 2.2,
    phaser: 2.2,
    'plate-reverb': 2.4,
    'fdn-reverb': 1.7,
    'ether-reverb': 1.3,
    swell: 1.6,
    'stereo-detune': 1.5,
    'tape-echo': 1,
    cascade: 1.3,
    flanger: 1.3,
    'ambient-comp': 1.3,
    shimmer: 1.2,
    'pad-follower': 1.2,
    'stereo-widener': 1.2,
    'pitch-shifter': 1.1,
    'vowel-reverb': 0.9,
    'bloom-reverb': 0.8,
    'grain-delay': 0.8,
    sustainer: 0.8,
    tremolo: 0.8,
    'half-speed': 0.7,
    'shaped-reverb': 0.7,
    'spectral-blur': 0.7,
    saturator: 0.5,
    'analog-drive': 0.4,
    lattice: 0.6,
    'echo-memory': 0.5,
    'grain-cloud': 0.5,
    rotary: 0.5,
    sympathetic: 0.5,
    tape: 0.2,
    patina: 0.4,
    'micro-looper': 0.4,
    'swarm-reverb': 0.15,
    'tape-loop': 0.12,
    'freq-shifter': 0.3,
    'noise-floor': 0.15,
    're-amp': 0.06,
    'reverse-delay': 0.12,
    'spectral-drifter': 0.3,
    'low-bitrate': 0.04,
    'spring-reverb': 0.03,
    radio: 0.03,
    glitch: 0.02,
    vinyl: 0.02,
  },
  voices: {
    'hall-reverb:Cathedral': 3,
    'hall-reverb:Hall': 1.8,
    'hall-reverb:Vast nave': 2,
    'hall-reverb:Dark hall': 1.5,
    'hall-reverb:Bright hall': 1.5,
    'hall-reverb:Warm undertow': 1.3,
    'fdn-reverb:Hall': 2,
    'plate-reverb:Long plate': 1.6,
    'shimmer:Plain hall': 1.5,
    'ether-reverb:Cathedral': 1.8,
    'expanse:Open space': 1.8,
    'expanse:Bloom': 1.4,
    'fdn-reverb:Slow swell': 1.4,
    'chorus:Slow drift': 1.6,
    'chorus:Classic chorus': 1.6,
    'chorus:Lush ensemble': 1.5,
    'analog-delay:Dark echo': 2,
    'analog-delay:Chorused': 1.5,
    'tape-echo:Long dark trail': 1.4,
    'tape-echo:Three heads': 1.4,
    'phaser:Slow swirl': 1.6,
    'flanger:Slow sweep': 1.5,
    'half-speed:Under the mix': 2,
    'tape:Quarter inch': 2,
    'tape:Mastering deck': 2,
    'vintage-digital:Glaze': 2.5,
    'vintage-digital:Sampler': 1.6,
    'vintage-digital:Glassy': 1.4,
    'vintage-digital:Worn': 2,
    'vintage-digital:Dusty': 1.5,
    'vintage-digital:Jittery': 1.2,
    'vintage-digital:Metallic': 1.2,
    'vintage-digital:Sunken': 1.2,
    're-amp:Station platform': 8,
    're-amp:Far end of the hall': 5,
    're-amp:Just the room': 4,
    're-amp:Room underneath': 4,
    're-amp:Down the hall': 3,
    'radio:Clean transistor': 10,
    'patina:Early sampler': 3,
    'auto-filter:Soft bloom': 2.5,
    'auto-filter:Glacial low-pass': 2,
    'ambient-comp:Hold swells': 1.6,
    'tremolo:Pitch wobble': 3,
    'tremolo:Slow chorus': 1.5,
    'cascade:Glass rain': 3,
    'cascade:Rising steps': 2.5,
    'cascade:Sparkle bed': 1.5,
    'grain-delay:Crystals': 1.6,
    'grain-delay:High glitter': 1.6,
    'lattice:Crystal cascade': 2,
    'lattice:Pentatonic harp': 2,
    'pitch-shifter:Rising steps': 1.6,
    'pitch-shifter:High sparks': 1.6,
    'stereo-detune:Classic': 1.4,
    'stereo-detune:Doubled': 1.4,
    'vintage-digital:Rasp': 0.2,
    'vintage-digital:Crushed': 0.3,
    'vintage-digital:Toy': 0.15,
    'vintage-digital:Coarse': 0.4,
    'chorus:Warped tape': 0.2,
    'vintage-digital:Phone': 0.3,
    'analog-delay:Seasick': 0,
    'analog-delay:Falling tape': 0.3,
    'analog-delay:Noisy clock': 0.4,
    'analog-delay:Slow lurch': 0.3,
    'analog-delay:Fluttering': 0.3,
    'tape-echo:Worn tape': 0.3,
    'expanse:Fast flutter': 0.3,
    'auto-filter:Phone line': 0.3,
    'auto-filter:Low-pass gate': 0.03,
    'shaped-reverb:Gated': 0.3,
    'expanse:Small box': 0.3,
    'expanse:Narrow tunnel': 0,
    'flanger:Tremolo saw': 0,
    'analog-delay:Slapback': 0.5,
    'fdn-reverb:Pulsing gate': 0.2,
    'cascade:Undertow': 0.4,
    'expanse:Seasick choir': 0.5,
    'analog-drive:Crushed': 0.2,
    'analog-drive:Dark fuzz': 0,
    'analog-drive:Iron melt': 0,
    'analog-drive:Worn tape': 0.2,
    'saturator:Fuzz pedal': 0,
    'saturator:Wavefold lead': 0.2,
    'saturator:Sustain bed': 0.3,
    'patina:Hot valve': 0.3,
    'saturator:Lo-fi': 0.2,
    'tape:Warm thump': 0.3,
    'tape:Under a blanket': 0.3,
    'tape:Cassette four-track': 0.2,
    'stereo-widener:Narrow': 0.3,
    'stereo-widener:Mono': 0,
    'grain-cloud:Sinking spiral': 0,
    'fet-limiter:Flattened': 0.1,
    'fet-limiter:Squash': 0.1,
    'ambient-limiter:Pinned': 0.3,
    'ambient-comp:Pump': 0,
  },
  recipes: {
    // Space.
    'swell-hall': 1.8,
    'width-hall': 1.5,
    'hall-glue': 1.2,
    'hall-width': 1,
    'halo-hall': 0.9,
    'hall-tone': 0.6,
    'swell-halo': 0.8,
    'swell-halo-hall': 0.8,
    'tone-hall': 0.6,
    'room-hall': 0.6,
    'tone-halo': 0.6,
    'drive-hall': 0.3,
    'room-halo': 0.5,
    'tone-room-hall': 0.5,
    'width-room': 0.4,
    'drive-room': 0.3,
    // Echo.
    'echo-hall': 2,
    'motion-echo': 1.8,
    'swell-echo': 1.2,
    'echo-width': 1,
    'echo-halo': 0.8,
    'drive-echo-hall': 0.6,
    'echo-room': 0.5,
    'drive-echo': 0.3,
    'echo-echo': 0.5,
    'loop-hall': 0.08,
    'loop-room': 0.05,
    'tone-loop': 0.05,
    'loop-echo': 0.05,
    'loop-tone-hall': 0.05,
    // Tape: here the medium is the early converters.
    'wear-hall': 2,
    'motion-wear': 1.2,
    'wear-echo': 1.3,
    'tone-wear-echo': 1,
    'wear-tone': 0.8,
    'wear-room': 0.6,
    'drive-wear': 0.5,
    'drive-tone': 0.5,
    'wear-hiss': 0.15,
    'loop-wear': 0.15,
    'loop-wear-hall': 0.15,
    'drive-wear-room': 0.3,
    'wear-hiss-hall': 0.15,
    'drive-hiss': 0.05,
    // Motion.
    'motion-hall': 2.2,
    'motion-echo-hall': 2,
    'swell-motion': 1.4,
    'motion-motion': 1,
    'width-motion': 1,
    'motion-halo': 0.8,
    'motion-tone': 0.7,
    'motion-room': 0.4,
    'drive-motion-hall': 0.25,
    'drive-motion': 0.15,
    'pulse-echo': 0.03,
    'pulse-hall': 0.03,
    'pulse-room': 0.03,
    'tone-pulse': 0.03,
    // Texture.
    'hold-hall': 1.6,
    'hold-motion': 1.5,
    'hold-motion-hall': 1.5,
    'swell-hold': 1.4,
    'swell-grain-hall': 1,
    'swell-width': 1,
    'hold-wear': 0.6,
    'grain-echo': 0.6,
    'swell-room': 0.5,
    'grain-wear': 0.15,
    'grain-room': 0.4,
    'drive-grain': 0.1,
    // Pitch.
    'pitch-hall': 2,
    'pitch-echo-hall': 1.5,
    'swell-pitch-hall': 1.3,
    'pitch-echo': 1.2,
    'pitch-width': 0.8,
    'pitch-wear': 0.6,
    'pitch-room': 0.5,
    'pitch-grain': 0.4,
    'drive-pitch': 0.3,
    // Master.
    'wear-ceiling': 1.3,
    'width-ceiling': 1.2,
    'drive-ceiling': 0.6,
    'drive-tone-ceiling': 0.6,
    'drive-glue-ceiling': 0.6,
  },
  own: [
    {
      // The pack in one chain: a chorus, repeats that dull as they fall away, and the very large hall.
      id: 'neon-rain-chorus-repeats-hall',
      category: 'space',
      lead: 2,
      count: 6,
      slots: [
        { role: 'motion', devices: ['chorus'], not: ['fast', 'strange', 'worn'] },
        {
          role: 'echo',
          devices: ['analog-delay', 'tape-echo'],
          not: ['unsteady', 'strange', 'worn', 'short'],
        },
        {
          role: 'hall',
          devices: ['hall-reverb', 'expanse', 'ether-reverb', 'fdn-reverb'],
          any: ['long', 'wide'],
          not: ['heavy', 'narrow', 'unsteady'],
        },
      ],
    },
    {
      // A chord that opens slowly into the hall, the whole of it heard through early converters.
      id: 'neon-rain-slow-swell-glazed',
      category: 'space',
      lead: 1,
      count: 5,
      slots: [
        { role: 'swell', devices: ['swell', 'auto-filter', 'ambient-comp'], not: ['fast'] },
        {
          role: 'hall',
          devices: ['hall-reverb', 'expanse', 'ether-reverb', 'fdn-reverb', 'plate-reverb'],
          not: ['heavy', 'narrow', 'unsteady'],
        },
        {
          presets: [
            'vintage-digital:Glaze',
            'vintage-digital:Sampler',
            'vintage-digital:Glassy',
            'vintage-digital:Grit bed',
            'vintage-digital:Dusty',
            'vintage-digital:Worn',
            'patina:Early sampler',
            'patina:Muffled sampler',
          ],
        },
      ],
    },
    {
      // A run of bells: every note comes back as quick rising octaves, a glitter in a cathedral.
      id: 'neon-rain-glitter-run',
      category: 'pitch',
      lead: 0,
      count: 5,
      slots: [
        {
          presets: [
            'cascade:Glass rain',
            'cascade:Rising steps',
            'cascade:Sparkle bed',
            'cascade:Octave stack',
            'grain-delay:Crystals',
            'grain-delay:High glitter',
            'grain-delay:Faint glints',
            'pitch-shifter:Rising steps',
            'pitch-shifter:High sparks',
            'lattice:Crystal cascade',
            'lattice:Pentatonic harp',
          ],
        },
        {
          role: 'hall',
          devices: ['hall-reverb', 'expanse', 'ether-reverb', 'fdn-reverb', 'plate-reverb'],
          any: ['long', 'wide', 'bright'],
          not: ['heavy', 'narrow', 'unsteady'],
        },
      ],
    },
    {
      // One line doubled a few cents apart, with repeats behind it.
      id: 'neon-rain-doubled-lead',
      category: 'echo',
      lead: 1,
      count: 4,
      slots: [
        {
          role: 'width',
          devices: ['stereo-detune', 'pitch-shifter', 'grain-delay', 'grain-cloud', 'lattice'],
          not: ['strange', 'worn', 'narrow'],
        },
        { role: 'echo', devices: ['tape-echo', 'analog-delay'], not: ['strange', 'worn', 'fast'] },
      ],
    },
    {
      // A string section that follows the playing, turned slowly and left in the hall.
      id: 'neon-rain-strings-in-motion',
      category: 'texture',
      lead: 0,
      count: 4,
      slots: [
        { role: 'hold', devices: ['pad-follower'], not: ['heavy', 'narrow'] },
        { role: 'motion', devices: ['phaser', 'chorus', 'flanger'], not: ['fast', 'strange'] },
        { role: 'hall', not: ['heavy', 'narrow', 'strange'] },
      ],
    },
    {
      // The big hall played back through twelve bits: the grain of the pack.
      id: 'neon-rain-hall-through-bits',
      category: 'tape',
      lead: 1,
      count: 4,
      slots: [
        {
          role: 'hall',
          devices: ['hall-reverb', 'expanse', 'ether-reverb', 'fdn-reverb'],
          any: ['long', 'wide'],
          not: ['heavy', 'narrow', 'unsteady'],
        },
        { role: 'wear', devices: ['vintage-digital'], not: ['strange'] },
      ],
    },
  ],
  heads: [
    'Neon',
    'Rain-wet',
    'Rooftop',
    'Skyline',
    'Smog',
    'Sodium',
    'Tenth-floor',
    'Night-market',
    'Basin',
    'Billboard',
    'Overpass',
    'Atrium',
    'Elevator',
    'Noodle-bar',
    'Small-hours',
    'Midnight',
    'After-hours',
    'Late-shift',
    'Arcade',
    'Signboard',
    'Storm-drain',
    'Gutter',
    'Girder',
    'Foundry',
    'Refinery',
    'Rain-streak',
    'Streetlamp',
    'Dashboard',
    'Searchlight',
    'Downtown',
    'Freeway',
    'Fire-escape',
    'Walkway',
    'Balcony',
    'Shopfront',
    'Airship',
    'Kiosk',
    'Back-alley',
    'Pylon',
    'Overcast',
    'Halogen',
    'Tube-lit',
    'Wet-neon',
    'Smokestack',
    'Gantry',
    'Awning',
    'Lantern',
    'Windscreen',
    'Tail-light',
    'Flare-stack',
    'Steam-grate',
    'Precinct',
    'Curfew',
    'Last-train',
    { word: 'Flare-lit', for: ['bright'] },
    { word: 'Cross-town', for: ['far'] },
    { word: 'Sub-level', for: ['low'] },
    { word: 'High-rise', for: ['high'] },
    { word: 'Smog-dimmed', for: ['dark'] },
    { word: 'All-night', for: ['long', 'frozen'] },
    { word: 'Slow-lane', for: ['slow'] },
    { word: 'Sprawling', for: ['wide'] },
    { word: 'Ten-lane', for: ['wide'] },
    { word: 'Rush-hour', for: ['noisy'] },
    { word: 'Chromed', for: ['cold'] },
  ],
  tails: [
    'under neon',
    'in wet neon',
    'in steam',
    'in the smog',
    'at the kerb',
    'in light rain',
    'after rain',
    'at curfew',
    'by the sign',
    'past midnight',
    'at shift end',
    'by the vents',
    'in the atrium',
    'at the market',
    'behind blinds',
    'in headlights',
    'below towers',
    'in the basin',
    'on wet glass',
    'in the alley',
    { word: 'across town', for: ['far'] },
    { word: 'storeys up', for: ['high'] },
    { word: 'below ground', for: ['low'] },
    { word: 'in blackout', for: ['dark'] },
    { word: 'in low light', for: ['dark'] },
    { word: 'till morning', for: ['long', 'frozen'] },
    { word: 'in the flare', for: ['bright'] },
    { word: 'at a crawl', for: ['slow'] },
    { word: 'in rear view', for: ['backwards'] },
    { word: 'over traffic', for: ['noisy'] },
  ],
  // Plain nouns that in this pack would read as the title of a record or a piece.
  avoid: ['spiral', 'voices', 'memories', 'memory'],
}
