// Steel in Slow Orbit: a steel guitar that slides and swells and never
// twangs, sent up to circle the moon. Its chains take the pick off with a
// pedal, put one slap behind the note, throb in a small amplifier's tremolo
// and ring in a spring, a plate or a very long hall. Nothing is broken,
// digital or harsh.

import { type PackPalette } from './types'

export const PALETTE: PackPalette = {
  pack: 'orbit-steel',
  groups: { space: 26, echo: 18, tape: 8, motion: 18, texture: 14, pitch: 10, master: 6 },
  traits: {
    warm: 1.5,
    long: 1.4,
    wide: 1.3,
    slow: 1.3,
    clean: 1.2,
    far: 1.2,
    unsteady: 0.7,
    heavy: 0.6,
    narrow: 0.7,
    cold: 0.4,
    worn: 0.35,
    noisy: 0.4,
    frozen: 0.6,
    strange: 0.03,
  },
  devices: {
    tremolo: 4.5,
    'plate-reverb': 3.4,
    'tape-echo': 2.6,
    'spring-reverb': 2.4,
    'hall-reverb': 2.4,
    're-amp': 2,
    'stereo-detune': 2,
    shimmer: 1.6,
    swell: 2,
    rotary: 1.2,
    'ether-reverb': 1.1,
    'pad-follower': 1.4,
    'half-speed': 1.3,
    sustainer: 1.3,
    tape: 2,
    'analog-delay': 1.2,
    'bloom-reverb': 1.2,
    sympathetic: 1.2,
    phaser: 0.8,
    'shaped-reverb': 0.8,
    'reverse-delay': 0.8,
    'tape-loop': 0.8,
    octaves: 0.8,
    saturator: 0.8,
    patina: 0.7,
    'echo-memory': 0.7,
    'spectral-blur': 0.7,
    'micro-looper': 0.6,
    lattice: 0.4,
    'swarm-reverb': 0.35,
    'auto-filter': 0.5,
    'grain-delay': 0.4,
    flanger: 0.3,
    'noise-floor': 0.4,
    'grain-cloud': 0.4,
    cascade: 0.3,
    'spectral-drifter': 0.4,
    vinyl: 0.12,
    'freq-shifter': 0.1,
    radio: 0.03,
    'vintage-digital': 0,
    'low-bitrate': 0,
    glitch: 0,
  },
  voices: {
    'swell:Volume pedal': 2.5,
    'swell:Loud notes only': 0.05,
    'tremolo:Amp tremolo': 2,
    'tremolo:Harmonic shimmer': 1.8,
    'tremolo:Chopper': 0,
    'tremolo:On and off': 0,
    'tremolo:Side to side': 0.4,
    'tape-echo:Single slap': 2.5,
    'tape-echo:Short and soft': 1.8,
    'analog-delay:Slapback': 2,
    'plate-reverb:Long plate': 1.8,
    'spring-reverb:Long three spring': 1.6,
    'spring-reverb:Quick twang': 0,
    'spring-reverb:Surf drip': 0.1,
    'spring-reverb:Dub send': 0.4,
    'stereo-detune:Classic': 1.5,
    're-amp:Combo in a room': 1.8,
    're-amp:Stack flat out': 0.3,
    'rotary:Chorale': 1.5,
    'half-speed:Under the mix': 1.6,
    'shimmer:Rising choir': 1.5,
    'saturator:Fuzz pedal': 0.1,
    'saturator:Wavefold lead': 0.2,
    'saturator:Lo-fi': 0.05,
    'saturator:Folded glass': 0.2,
    'saturator:Sustain bed': 0.3,
    'patina:Valve fuzz': 0.1,
    'patina:Quarter inch reel': 1.6,
    'patina:New tape': 1.6,
    'patina:Muffled sampler': 0,
    'patina:Early sampler': 0,
    'patina:Eight bit': 0,
    'patina:Shortwave': 0,
    'patina:Distant station': 0,
    'patina:Kitchen radio': 0.05,
    'micro-looper:Sampler grit': 0.05,
    'micro-looper:Lo-fi quarter': 0.05,
    'micro-looper:Fast reverse': 0.1,
    'tape-loop:Octave up ghosts': 0.3,
    'half-speed:Slow chops': 0.05,
    'shaped-reverb:Gate steps': 0.15,
    'shaped-reverb:Gated': 0.4,
    'analog-drive:Dark fuzz': 0.2,
    'analog-drive:Parallel grit': 0.05,
    'analog-drive:Bite': 0.05,
    'analog-drive:Sheen': 0.2,
    'flanger:Square chop': 0.1,
    'phaser:Two-tone flip': 0.3,
    'noise-floor:Amp left on': 2,
    'noise-floor:Mains hum': 1.5,
    'noise-floor:Static notes': 0,
    'noise-floor:Radio static': 0,
    'noise-floor:Old record': 0.3,
    'noise-floor:Gap crackle': 0.3,
    'freq-shifter:Moving beat': 0.2,
    'saturator:Drum bus crunch': 0.4,
    'octaves:Nasal reed': 0.2,
    'auto-filter:Dub sweep': 0.2,
    'auto-filter:Touch wah': 0.2,
    'phaser:Saw riser': 0.3,
    'reverse-delay:Tight stutter': 0.2,
    'ambient-comp:Dense pad': 0.2,
    'ambient-comp:Pump': 0.05,
    'ambient-limiter:Pinned': 0.2,
    'ambient-limiter:Loud': 0.4,
    'fet-limiter:Squash': 0.1,
    'fet-limiter:Flattened': 0.05,
    'fet-limiter:Tucked under': 0.3,
  },
  recipes: {
    'swell-hall': 1.5,
    'width-hall': 2,
    'drive-hall': 1.6,
    'drive-room': 1.3,
    'room-hall': 1.2,
    'tone-halo': 0.7,
    'echo-hall': 2,
    'echo-room': 1.5,
    'swell-echo': 1.5,
    'drive-echo': 1.5,
    'drive-echo-hall': 2,
    'echo-echo': 0.6,
    'loop-echo': 0.7,
    'loop-tone-hall': 0.7,
    'wear-hall': 1.6,
    'wear-room': 1.4,
    'wear-echo': 1.3,
    'drive-wear-room': 1.6,
    'wear-hiss': 0.3,
    'wear-hiss-hall': 0.3,
    'drive-hiss': 0.3,
    'pulse-hall': 4,
    'pulse-room': 3.5,
    'pulse-echo': 2,
    'tone-pulse': 2,
    'drive-motion': 1.5,
    'drive-motion-hall': 2,
    'motion-motion': 0.5,
    'motion-tone': 0.6,
    'swell-hold': 1.5,
    'hold-hall': 2,
    'hold-motion': 1.5,
    'hold-motion-hall': 1.5,
    'grain-wear': 0.4,
    'grain-tone': 0.5,
    'grain-echo': 0.5,
    'grain-room': 0.6,
    'drive-grain': 0.5,
    'pitch-hall': 1.5,
    'swell-pitch-hall': 1.6,
    'pitch-wear': 1.2,
    'pitch-grain': 0.4,
  },
  own: [
    {
      // The pack in one chain: a chord raised on the pedal, one slap behind it, a long hall.
      id: 'orbit-steel-pedal-slap-hall',
      category: 'space',
      lead: 2,
      count: 6,
      slots: [
        { role: 'swell', devices: ['swell'], not: ['fast'] },
        {
          presets: [
            'tape-echo:Single slap',
            'tape-echo:Short and soft',
            'tape-echo:Tiny room cluster',
            'analog-delay:Slapback',
            'ether-reverb:Slap room',
            'shaped-reverb:Mono slap',
            'stereo-detune:Late copy',
          ],
        },
        {
          role: 'hall',
          devices: ['plate-reverb', 'hall-reverb', 'ether-reverb', 'fdn-reverb', 'expanse'],
          any: ['long', 'wide', 'warm'],
          not: ['heavy'],
        },
      ],
    },
    {
      // A small amplifier with its tremolo turned up deep and its spring on.
      id: 'orbit-steel-amp-tremolo-spring',
      category: 'motion',
      lead: 1,
      count: 5,
      slots: [
        {
          role: 'drive',
          presets: [
            're-amp:Combo in a room',
            're-amp:Warm stack',
            're-amp:Speaker on the edge',
            're-amp:Just the valves',
            're-amp:Clean and bright',
            're-amp:Dark and woolly',
            're-amp:In the cupboard',
            're-amp:Noisy valves',
            'analog-drive:Triode glow',
            'patina:Hot valve',
            'patina:Valve bloom',
            'saturator:Tube preamp',
          ],
        },
        {
          presets: [
            'tremolo:Amp tremolo',
            'tremolo:Harmonic shimmer',
            'tremolo:Wide shimmer',
            'tremolo:Fast shudder',
            'tremolo:Sea swell',
            'tremolo:Gentle breath',
            'tremolo:Tilting tone',
            'tremolo:Pitch wobble',
            'rotary:Tremolo',
            'rotary:Chorale',
            'rotary:Heavy rotors',
            'rotary:Close pulse',
          ],
        },
        { devices: ['spring-reverb'], not: ['strange', 'heavy'] },
      ],
    },
    {
      // Every pick taken off, the note doubled a few cents wide, in a long plate.
      id: 'orbit-steel-no-pick-doubled',
      category: 'texture',
      lead: 0,
      count: 5,
      slots: [
        { role: 'swell', devices: ['swell', 'tremolo'], not: ['fast'] },
        {
          role: 'width',
          devices: ['stereo-detune', 'pitch-shifter', 'chorus', 'analog-delay'],
          not: ['strange'],
        },
        {
          role: 'hall',
          devices: ['plate-reverb', 'hall-reverb', 'ether-reverb'],
          not: ['heavy'],
        },
      ],
    },
    {
      // A faded-in note under a reverb that climbs an octave on every pass.
      id: 'orbit-steel-rising-halo',
      category: 'space',
      lead: 1,
      count: 4,
      slots: [
        { role: 'swell', devices: ['swell', 'tremolo', 'ambient-comp'] },
        { role: 'halo', devices: ['shimmer', 'bloom-reverb'], any: ['high'], not: ['cold'] },
      ],
    },
    {
      // The playing with itself at half speed under it, on clean tape in a hall.
      id: 'orbit-steel-half-speed-under',
      category: 'pitch',
      lead: 0,
      count: 4,
      slots: [
        {
          role: 'pitch',
          devices: ['half-speed', 'tape-loop', 'micro-looper'],
          want: ['low'],
          not: ['strange', 'frozen', 'backwards', 'heavy'],
        },
        { role: 'wear', devices: ['tape', 'patina'], not: ['worn', 'noisy', 'cold', 'unsteady'] },
        { role: 'hall', not: ['heavy', 'strange', 'cold'] },
      ],
    },
    {
      // One slap behind each note, through a small amplifier, with a little spring or a plate.
      id: 'orbit-steel-slap-amp-spring',
      category: 'echo',
      lead: 0,
      count: 4,
      slots: [
        {
          presets: [
            'tape-echo:Single slap',
            'tape-echo:Short and soft',
            'tape-echo:Faint trace',
            'analog-delay:Slapback',
            'ether-reverb:Slap room',
            'shaped-reverb:Mono slap',
            'stereo-detune:Late copy',
          ],
        },
        { role: 'drive', devices: ['re-amp'], not: ['far', 'worn', 'noisy'] },
        { role: 'room', devices: ['spring-reverb', 'plate-reverb'], not: ['strange'] },
      ],
    },
  ],
  heads: [
    'Earthrise',
    'Lunar',
    'Orbiting',
    'Moonlit',
    'Moonrise',
    'Tranquility',
    'Lander',
    'Splashdown',
    'Liftoff',
    'Re-entry',
    'Buoyant',
    'Floating',
    'Tethered',
    'Hovering',
    'Translunar',
    'Cislunar',
    'Perigee',
    'Crater',
    'Regolith',
    'Moondust',
    'Dawn-line',
    'Outbound',
    'Homeward',
    'Gibbous',
    'Crescent',
    'Porthole',
    'Airlock',
    'Heat-shield',
    'Parachute',
    'Gantry',
    'Countdown',
    'Porch',
    'Prairie',
    'Cabin',
    'Ridge',
    'Front-room',
    'Dance-hall',
    'Tin-roof',
    'Screen-door',
    'Stock-pond',
    'Creekside',
    'Campfire',
    'Bunkhouse',
    'County-fair',
    'Two-lane',
    'Truck-stop',
    'Pearl-snap',
    'Lonesome',
    'Homesick',
    'Sagebrush',
    'Night-field',
    'Nickel',
    'Chrome',
    { word: 'Far-side', for: ['far'] },
    { word: 'Slow-orbit', for: ['slow'] },
    { word: 'Adrift', for: ['unsteady'] },
    { word: 'Night-side', for: ['dark'] },
    { word: 'Day-side', for: ['bright'] },
    { word: 'Long-haul', for: ['long'] },
    { word: 'Octave-strung', for: ['high'] },
    { word: 'Baritone', for: ['low'] },
    { word: 'Turned-back', for: ['backwards'] },
    { word: 'Held-aloft', for: ['frozen'] },
    { word: 'Stove-warm', for: ['warm'] },
    { word: 'Throbbing', for: ['fast'] },
  ],
  tails: [
    'past the moon',
    'at earthrise',
    'at moonrise',
    'by moonlight',
    'from orbit',
    'in free fall',
    'headed home',
    'miles up',
    'above it all',
    'after liftoff',
    'at splashdown',
    'at the window',
    'on the porch',
    'off the ridge',
    'over prairie',
    'at the dance',
    'at last call',
    'on a tin roof',
    'by the creek',
    'in the cabin',
    'under the bar',
    'in earthshine',
    { word: 'in slow orbit', for: ['slow'] },
    { word: 'from far off', for: ['far'] },
    { word: 'in harmonics', for: ['high'] },
    { word: 'turned around', for: ['backwards'] },
    { word: 'in the shadow', for: ['dark'] },
  ],
  avoid: ['ascent', 'drift'],
}
