// Shedding Oxide: short loops on tape so old it sheds a little more each
// time round. Its chains are loops, wear and hiss before anything else; a
// room when there is one is dark and far; nothing is bright, clean or quick.

import { type PackPalette } from './types'

export const PALETTE: PackPalette = {
  pack: 'oxide',
  groups: { space: 10, echo: 18, tape: 30, motion: 9, texture: 13, pitch: 14, master: 6 },
  traits: {
    worn: 2.4,
    dark: 1.8,
    warm: 1.5,
    unsteady: 1.8,
    slow: 1.5,
    long: 1.4,
    noisy: 1.4,
    low: 1.5,
    far: 1.4,
    backwards: 1.2,
    bright: 0.3,
    cold: 0.5,
    clean: 0.35,
    fast: 0.3,
    high: 0.3,
    strange: 0.5,
  },
  devices: {
    'tape-loop': 3,
    tape: 3,
    'noise-floor': 2,
    'half-speed': 2.2,
    patina: 1.8,
    'micro-looper': 1.6,
    'tape-echo': 1.6,
    'echo-memory': 1.4,
    'reverse-delay': 1.2,
    'plate-reverb': 1.3,
    'hall-reverb': 1.3,
    'analog-delay': 0.8,
    'vintage-digital': 0.15,
    'low-bitrate': 0.1,
    glitch: 0.1,
    lattice: 0.15,
    shimmer: 0.2,
    'freq-shifter': 0.3,
    flanger: 0.3,
    'grain-delay': 0.5,
    octaves: 0.4,
    'pitch-shifter': 0.4,
    cascade: 0.3,
  },
  recipes: {
    'loop-wear': 2,
    'loop-wear-hall': 2,
    'wear-hiss': 1.6,
    'wear-hiss-hall': 1.6,
    'loop-hall': 1.6,
    'tone-loop': 1.3,
    'pitch-wear': 2,
    'hold-wear': 1.6,
    'grain-wear': 1.4,
    'motion-wear': 1.4,
    'echo-echo': 0.4,
    'pulse-echo': 0.4,
    'pulse-hall': 0.5,
    'pulse-room': 0.4,
  },
  own: [
    {
      // The pack in one chain: a loop that comes round, the tape it is on, the room it is heard in.
      id: 'oxide-loop-on-old-tape',
      category: 'tape',
      lead: 0,
      count: 6,
      slots: [
        { role: 'loop', devices: ['tape-loop'], not: ['bright', 'fast', 'clean'] },
        { role: 'wear', devices: ['tape', 'patina'], any: ['worn', 'dark'] },
        { role: 'hall', any: ['dark', 'far', 'long'] },
      ],
    },
    {
      // The same tune a little lower and slower each year.
      id: 'oxide-slowed-and-worn',
      category: 'pitch',
      lead: 0,
      count: 5,
      slots: [
        { role: 'pitch', devices: ['half-speed', 'tape-loop'], any: ['low'] },
        { role: 'wear', devices: ['tape', 'patina', 'vinyl'], not: ['bright'] },
      ],
    },
    {
      // What is left when the tune has gone: hiss, and a room.
      id: 'oxide-mostly-hiss',
      category: 'tape',
      lead: 1,
      count: 4,
      slots: [
        { role: 'wear', devices: ['tape'], any: ['worn', 'dark'] },
        { role: 'hiss', devices: ['noise-floor'] },
        { role: 'room' },
      ],
    },
    {
      id: 'oxide-loop-under-loop',
      category: 'echo',
      lead: 0,
      count: 4,
      slots: [
        { role: 'loop', devices: ['tape-loop', 'micro-looper'] },
        { role: 'echo', devices: ['tape-echo', 'echo-memory'], not: ['bright', 'fast'] },
      ],
    },
  ],
  heads: [
    'Shedding',
    'Flaking',
    'Brittle',
    'Dusty',
    'Fortieth-pass',
    'Late-summer',
    'Archive',
    'Attic',
    'Thinning',
    'Fading',
    'Last-pass',
    'Rusting',
    'Crumbling',
    'Powdered',
    'Sunlit',
    'Afternoon',
    'Unmarked',
    'Shelved',
    'Spliced',
    'Slow-spool',
    'Tired',
    'Yellowed',
    'Stretched',
    'Baked',
    'Forgotten',
    'Half-erased',
    'Print-through',
    'Twice-played',
    'Motor-down',
    'Lobby',
    'Bandstand',
    'Far-dial',
    'Boxed',
    'Leader',
    'Run-out',
    'Old-stock',
    'Ferric',
    'Brown',
    'Rust-red',
    'Seventh-year',
    { word: 'Muffled', for: ['dark'] },
    { word: 'Sagging', for: ['unsteady', 'low'] },
    { word: 'Wavering', for: ['unsteady'] },
    { word: 'Hissing', for: ['noisy'] },
    { word: 'Distant', for: ['far'] },
    { word: 'Rewound', for: ['backwards'] },
    { word: 'Slowed', for: ['low', 'slow'] },
    { word: 'Endless', for: ['frozen'] },
  ],
  tails: [
    'on old stock',
    'left in sun',
    'in the attic',
    'nearly gone',
    'losing flakes',
    'off the shelf',
    'on pass forty',
    'in a shoebox',
    'unlabelled',
    'under dust',
    'played thin',
    'in late light',
    'thinning out',
    'next door',
    'on the shelf',
    'kept too long',
  ],
  avoid: ['cascade', 'shortwave', 'loops', 'tiles'],
}
