// Park Bench Zither: open strings under light hammers and a brush, through
// three pedals on the grass: a phaser, an echo and a reverb. Its chains turn
// before anything else, then repeat, then ring; they are bright, wide and
// glad. A home cassette is as worn as it gets; nothing is sunk or broken.

import { type PackPalette } from './types'

export const PALETTE: PackPalette = {
  pack: 'park-zither',
  groups: { space: 18, echo: 20, tape: 7, motion: 28, texture: 10, pitch: 10, master: 7 },
  traits: {
    bright: 1.8,
    wide: 1.4,
    high: 1.3,
    clean: 1.2,
    warm: 1.1,
    cold: 0.8,
    far: 0.8,
    unsteady: 0.6,
    heavy: 0.4,
    narrow: 0.4,
    backwards: 0.2,
    frozen: 0.4,
    worn: 0.3,
    noisy: 0.3,
    low: 0.2,
    dark: 0.12,
    strange: 0.12,
  },
  devices: {
    phaser: 2.5,
    sympathetic: 2.4,
    'tape-echo': 2.2,
    'analog-delay': 2.2,
    'spring-reverb': 1.8,
    'hall-reverb': 2.2,
    'plate-reverb': 1.6,
    'ether-reverb': 1.5,
    'fdn-reverb': 1.3,
    flanger: 1.4,
    tape: 1.3,
    cascade: 1.2,
    shimmer: 1.2,
    octaves: 1.2,
    chorus: 1,
    lattice: 1.1,
    'echo-memory': 0.8,
    'vowel-reverb': 0.8,
    'bloom-reverb': 0.8,
    tremolo: 0.6,
    'pad-follower': 0.5,
    saturator: 0.6,
    'shaped-reverb': 0.7,
    'spectral-blur': 0.6,
    'grain-cloud': 0.4,
    'micro-looper': 0.5,
    'tape-loop': 0.5,
    'freq-shifter': 0.5,
    rotary: 0.3,
    'auto-filter': 0.005,
    'analog-drive': 0.4,
    'spectral-drifter': 0.15,
    'swarm-reverb': 0.3,
    'noise-floor': 0.3,
    'reverse-delay': 0.05,
    vinyl: 0.02,
    glitch: 0.05,
    'half-speed': 0.03,
    'vintage-digital': 0,
    radio: 0,
    'low-bitrate': 0,
  },
  voices: {
    'phaser:Warm six-stage': 1.5,
    'sympathetic:Hammered': 2.5,
    'sympathetic:Glass harp': 1.5,
    'octaves:Twelve string': 2.5,
    'lattice:Pentatonic harp': 3,
    'freq-shifter:Barber pole': 4,
    'tape-echo:Three heads': 1.5,
    'tape-echo:Dotted bounce': 1.5,
    'cascade:Restruck': 2,
    'cascade:Sparkle bed': 1.6,
    're-amp:Clean and bright': 1.6,
    're-amp:Combo in a room': 1.6,
    'patina:Worn cassette': 12,
    'tape:Cassette four-track': 20,
    're-amp:Station platform': 0.2,
    'patina:Early sampler': 0,
    'patina:Eight bit': 0,
    'patina:Muffled sampler': 0,
    'patina:Shortwave': 0,
    'patina:Distant station': 0,
    'patina:Kitchen radio': 0,
    'patina:Dusty record': 0,
    'patina:Scratched record': 0,
    'swarm-reverb:Mine shaft': 0.1,
    're-amp:Bedside radio': 0.1,
    're-amp:Pillow speaker': 0.2,
    'rotary:Stopped horn': 0.2,
    'rotary:Parked growl': 0.1,
    'rotary:Slow burn': 0.3,
    'rotary:Growl': 0.2,
    'chorus:Metallic comb': 0.2,
    'pad-follower:Pad alone': 0.3,
    'ambient-eq:Thin': 0.2,
    'spring-reverb:Slack and strange': 0,
    'spring-reverb:Single slack coil': 0.3,
    're-amp:Stack flat out': 0,
    're-amp:Speaker on the edge': 0.2,
    're-amp:Just the valves': 0.4,
    're-amp:Noisy valves': 0.3,
    'auto-filter:Phone line': 0.05,
    'saturator:Fuzz pedal': 0,
    'saturator:Blown speaker': 0,
    'analog-drive:Iron melt': 0,
    'analog-drive:Crushed': 0,
    'analog-drive:Dark fuzz': 0,
    'analog-drive:Torn cone': 0,
    'patina:Valve fuzz': 0,
    'analog-drive:Parallel grit': 0.3,
    'analog-drive:Bite': 0.3,
    'saturator:Wavefold lead': 0.15,
    'fet-limiter:Squash': 0,
    'fet-limiter:Flattened': 0,
    'fet-limiter:Tucked under': 0,
    'ambient-limiter:Pinned': 0.1,
    'ambient-eq:Muffled': 0.1,
    'auto-filter:Init': 0.2,
    'ambient-comp:Dense pad': 0.03,
    'ambient-comp:Pump': 0.1,
    'stereo-widener:Mono': 0,
    'stereo-widener:Narrow': 0,
    'tape:Needles pinned': 0.2,
    'tape:Hiss and air': 0.05,
    'analog-delay:Murky': 0,
    'tape-loop:Backwards layers': 0.1,
    'spring-reverb:Dark amp spring': 0,
    'analog-delay:Noisy clock': 0,
    'grain-delay:Backwards shards': 0,
    'fdn-reverb:Endless tail': 0.2,
  },
  recipes: {
    'motion-echo-hall': 4,
    'motion-hall': 2,
    'motion-halo': 2.5,
    'motion-room': 1.5,
    'motion-tone': 0.6,
    'drive-motion': 0.4,
    'drive-motion-hall': 0.4,
    'pulse-echo': 0.4,
    'pulse-hall': 0.4,
    'pulse-room': 0.4,
    'tone-pulse': 0.15,
    'motion-echo': 3,
    'echo-hall': 1.5,
    'echo-halo': 1.6,
    'echo-room': 1.2,
    'echo-width': 0.6,
    'drive-echo': 0.4,
    'drive-echo-hall': 0.4,
    'loop-hall': 0.15,
    'loop-room': 0.15,
    'tone-loop': 0.15,
    'loop-echo': 0.15,
    'loop-tone-hall': 0.15,
    'halo-hall': 1.4,
    'room-halo': 1.4,
    'tone-halo': 1.2,
    'drive-hall': 0.4,
    'motion-wear': 3,
    'wear-echo': 1.4,
    'wear-hall': 1.2,
    'wear-hiss': 0.15,
    'wear-hiss-hall': 0.15,
    'wear-wear': 0.2,
    'loop-wear': 0.1,
    'loop-wear-hall': 0.1,
    'drive-hiss': 0.1,
    'drive-wear': 0.4,
    'drive-tone': 0.2,
    'drive-wear-room': 0.4,
    'hold-motion': 1.6,
    'hold-motion-hall': 1.5,
    'hold-halo': 1.3,
    'swell-hold': 1.2,
    'drive-grain': 0.3,
    'grain-wear': 0.2,
    'hold-wear': 0.2,
    'pitch-motion': 2,
    'pitch-echo': 1.4,
    'pitch-wear': 0.2,
    'drive-pitch': 0.4,
    'width-ceiling': 0.5,
    'tone-width-ceiling': 0.5,
    'glue-width-ceiling': 0.5,
  },
  own: [
    {
      // The pack in one chain: the phaser, then the soft echo, then the hall.
      id: 'park-zither-three-pedals',
      category: 'motion',
      lead: 0,
      count: 6,
      slots: [
        { role: 'motion', devices: ['phaser'] },
        {
          role: 'echo',
          devices: ['tape-echo', 'analog-delay', 'echo-memory'],
          not: ['dark', 'worn', 'unsteady', 'strange', 'long'],
        },
        {
          role: 'hall',
          devices: ['hall-reverb', 'plate-reverb', 'ether-reverb', 'fdn-reverb'],
          not: ['dark', 'heavy', 'far'],
        },
      ],
    },
    {
      // A strum turned once by a pedal and left in the springs of a small amplifier.
      id: 'park-zither-amp-spring',
      category: 'space',
      lead: 1,
      count: 4,
      slots: [
        { role: 'motion', devices: ['phaser', 'flanger', 'chorus'], not: ['strange'] },
        { devices: ['spring-reverb'], not: ['strange', 'heavy'] },
      ],
    },
    {
      // Open strings left to ring behind what is played, turning, in a hall.
      id: 'park-zither-open-strings',
      category: 'space',
      lead: 0,
      count: 5,
      slots: [
        { role: 'halo', devices: ['sympathetic'], not: ['heavy', 'narrow'] },
        { role: 'motion', devices: ['phaser', 'flanger', 'chorus'], not: ['strange'] },
        { role: 'hall', not: ['dark', 'heavy', 'far', 'strange', 'unsteady'] },
      ],
    },
    {
      // A dry thumb piano through the same pedals: it turns, then an echo keeps a pattern going.
      id: 'park-zither-thumb-pattern',
      category: 'echo',
      lead: 1,
      count: 5,
      slots: [
        { role: 'motion', devices: ['phaser'] },
        {
          presets: [
            'tape-echo:Three heads',
            'tape-echo:Dotted bounce',
            'tape-echo:Two head gallop',
            'tape-echo:Warm repeats',
            'tape-echo:Clean and steady',
            'analog-delay:Octave hop',
            'analog-delay:Fifth hop',
            'analog-delay:Clean echo',
            'analog-delay:Chorused',
            'echo-memory:Side to side',
            'echo-memory:Plain echo',
            'lattice:Pentatonic harp',
            'lattice:Crystal cascade',
            'shaped-reverb:Scattered',
            'expanse:Hard echoes',
            'cascade:Restruck',
            'grain-delay:Plain repeat',
          ],
        },
      ],
    },
    {
      // A gong kept sounding with soft beaters, swept by a slow flanger in a very large room.
      id: 'park-zither-bronze-sweep',
      category: 'motion',
      lead: 0,
      count: 4,
      slots: [
        { role: 'motion', devices: ['flanger'], want: ['slow'], not: ['strange', 'cold'] },
        { role: 'hall', any: ['long'], not: ['dark', 'heavy', 'far', 'strange', 'unsteady'] },
      ],
    },
    {
      // Strings rolled in octaves: the octave above each note, then the pedal that turns it.
      id: 'park-zither-rolled-octaves',
      category: 'pitch',
      lead: 0,
      count: 4,
      slots: [
        {
          role: 'pitch',
          devices: ['octaves', 'pitch-shifter', 'lattice', 'cascade', 'grain-delay'],
          any: ['high'],
          not: ['strange', 'heavy', 'cold', 'low', 'backwards'],
        },
        { role: 'motion', devices: ['phaser', 'chorus'], not: ['strange'] },
      ],
    },
  ],
  heads: [
    'Park',
    'Park-bench',
    'Busking',
    'Noon',
    'Midday',
    'Lunch-hour',
    'Open-tuned',
    'Chopstick',
    'Brushed',
    'Wire-brush',
    'Marigold',
    'Fountain',
    'Stone-arch',
    'Plane-tree',
    'Lawn',
    'Sprinkler',
    'Pavement',
    'Brownstone',
    'Stoop',
    'Pawn-shop',
    'Open-case',
    'Pocket',
    'Kite-flying',
    'Picnic',
    'Hopscotch',
    'Railing',
    'Weekend',
    'Saturday',
    'Shirtsleeve',
    'Barefoot',
    'Dappled',
    'Battery-amp',
    'Thumb-piano',
    'Bronze',
    'Chord-bar',
    'Zither',
    'Open-air',
    'Downtown',
    'Dandelion',
    'Clover',
    'Heat-haze',
    'Cloudless',
    'Bandshell',
    'Boat-pond',
    'Footpath',
    'Chess-table',
    'Tip-jar',
    'Glad',
    'Lemonade',
    'Straw-hat',
    'Flagstone',
    'Cut-grass',
    'Soap-bubble',
    'Pinwheel',
    'Eyes-closed',
    { word: 'Glittering', for: ['bright', 'high'] },
    { word: 'Noon-bright', for: ['bright'] },
    { word: 'Wide-open', for: ['wide'] },
    { word: 'Unhurried', for: ['slow'] },
    { word: 'High-wire', for: ['high'] },
    { word: 'Low-tuned', for: ['low'] },
    { word: 'Skipping', for: ['fast'] },
    { word: 'Far-bench', for: ['far'] },
    { word: 'Half-heard', for: ['faint', 'far'] },
    { word: 'Tree-shaded', for: ['dark'] },
    { word: 'Wind-bent', for: ['unsteady'] },
    { word: 'Home-dubbed', for: ['worn', 'noisy'] },
  ],
  tails: [
    'at noon',
    'in the park',
    'by the arch',
    'on a bench',
    'on the lawn',
    'for coins',
    'under leaves',
    'fountainside',
    'on a blanket',
    'by hand',
    'in july',
    'in daylight',
    'cross-legged',
    'under trees',
    'by the pond',
    'on brick',
    'under hammers',
    'in the grass',
    'outdoors',
    'for pigeons',
    'on the path',
    'after lunch',
    'in the open',
    'by the gate',
    'in june',
    { word: 'aglitter', for: ['bright'] },
    { word: 'an octave up', for: ['high'] },
    { word: 'for hours', for: ['long'] },
    { word: 'at a stroll', for: ['slow'] },
    { word: 'a bench away', for: ['far'] },
    { word: 'over the lawn', for: ['far'] },
    { word: 'in the shade', for: ['dark'] },
    { word: 'in a breeze', for: ['unsteady'] },
  ],
}
