// Island Patch Cables: a patched synthesizer with no keyboard habits, on an
// island of cedar and rain. Its chains are quick and bright: echoes that hop
// by fifths and octaves, a line given harmony voices from the scale, filters
// that jump to random steps, notes struck again until they bubble, a folded
// edge, and a spring tank or a small plate behind them. Nothing is worn,
// hissing, slowed or far away.

import { type PackPalette } from './types'

export const PALETTE: PackPalette = {
  pack: 'patch-cables',
  groups: { space: 13, echo: 20, tape: 6, motion: 18, texture: 15, pitch: 22, master: 6 },
  traits: {
    bright: 1.6,
    high: 1.4,
    fast: 1.4,
    short: 1.3,
    clean: 1.2,
    wide: 1.1,
    dark: 0.12,
    worn: 0,
    noisy: 0,
    low: 0.6,
    slow: 0.65,
    long: 0.4,
    far: 0.3,
    heavy: 0.3,
    frozen: 0.4,
    unsteady: 0.6,
    backwards: 0.7,
    strange: 0.8,
    narrow: 0.7,
  },
  devices: {
    lattice: 3,
    'analog-delay': 2.8,
    cascade: 2.2,
    'spring-reverb': 2.4,
    'pitch-shifter': 2.6,
    'auto-filter': 2,
    saturator: 1.6,
    'plate-reverb': 1.5,
    chorus: 1.5,
    phaser: 1.5,
    'grain-delay': 1.5,
    tremolo: 1.4,
    'fdn-reverb': 1.3,
    shimmer: 1.2,
    'vowel-reverb': 1.2,
    octaves: 1.2,
    'tape-echo': 1.2,
    sympathetic: 1.1,
    expanse: 0.7,
    'bloom-reverb': 0.8,
    'freq-shifter': 0.8,
    swell: 0.7,
    glitch: 0.6,
    'micro-looper': 0.6,
    'echo-memory': 0.6,
    'reverse-delay': 0.6,
    'spectral-blur': 0.6,
    'spectral-drifter': 0.6,
    'analog-drive': 0.6,
    're-amp': 0.3,
    rotary: 0.4,
    sustainer: 0.4,
    'pad-follower': 0.3,
    'tape-loop': 0.15,
    'vintage-digital': 0.1,
    'half-speed': 0.1,
    tape: 0.1,
    patina: 0.1,
    vinyl: 0,
    radio: 0,
    'noise-floor': 0,
    'low-bitrate': 0,
  },
  voices: {
    'analog-delay:Fifth hop': 2,
    'analog-delay:Octave hop': 3,
    'lattice:Thesis voicing': 2.5,
    'lattice:Diatonic thirds': 2.5,
    'lattice:Seventh chord stack': 2,
    'lattice:Pentatonic harp': 2,
    'auto-filter:Stepped': 3,
    'auto-filter:Touch wah': 1.4,
    'auto-filter:Resonant peak': 1.5,
    'auto-filter:Tremolo filter': 2,
    'phaser:Random steps': 3,
    'flanger:Stepped random': 2.5,
    'saturator:Wavefold lead': 3,
    'saturator:Folded glass': 3,
    'cascade:Restruck': 2.5,
    'cascade:Dropped marbles': 2,
    'glitch:Bouncing': 3,
    'spring-reverb:Two spring tank': 2,
    'micro-looper:Octave up': 3,
    'micro-looper:Quick loop': 2,
    'auto-filter:Low-pass gate': 0.5,
    'swarm-reverb:Endless': 0.2,
    'plate-reverb:Endless wash': 0.3,
    'vowel-reverb:Endless oo': 0.15,
    'analog-drive:Dark fuzz': 0,
    'reverse-delay:Backwards only': 0,
    'ether-reverb:Cathedral': 0.1,
    'ether-reverb:Dark hall': 0.2,
    'plate-reverb:Full wet send': 0.2,
    'fdn-reverb:Full wet send': 0.2,
    'hall-reverb:Full wet send': 0.2,
    'phaser:Glacial sweep': 0.3,
    'flanger:Glacial drift': 0.3,
    'lattice:Two note drone': 0.5,
    'auto-filter:Glacial low-pass': 0.3,
    'ambient-eq:Muffled': 0,
    'ambient-eq:Distant': 0,
    'pad-follower:Pad alone': 0,
    'sustainer:Held sound alone': 0,
    'sympathetic:Sitar drone': 0.3,
    'ambient-comp:Pump': 0.3,
    'fet-limiter:Flattened': 0.3,
    'fet-limiter:Squash': 0.3,
    'saturator:Blown speaker': 0.1,
    'analog-drive:Torn cone': 0.1,
    'glitch:Total collapse': 0.1,
    'freq-shifter:Low growl': 0.2,
    'auto-filter:Screaming': 0.2,
  },
  recipes: {
    'tone-hall': 0.6,
    'hall-tone': 0.6,
    'drive-room': 2,
    'width-room': 2,
    'room-halo': 1.5,
    'swell-hall': 0.5,
    'swell-halo': 0.5,
    'swell-halo-hall': 0.4,
    'swell-echo': 0.5,
    'swell-motion': 0.5,
    'swell-room': 0.5,
    'swell-width': 0.4,
    'swell-grain-hall': 0.5,
    'swell-pitch': 0.5,
    'swell-pitch-hall': 0.5,
    'echo-room': 1.5,
    'drive-echo': 1.3,
    'motion-echo': 1.3,
    'echo-echo': 1.2,
    'loop-hall': 0.4,
    'loop-room': 0.5,
    'tone-loop': 0.4,
    'loop-echo': 0.5,
    'loop-tone-hall': 0.3,
    'drive-tone': 4,
    'wear-room': 0.15,
    'wear-hall': 0.15,
    'drive-wear': 0.15,
    'tone-wear': 0.15,
    'wear-echo': 0.15,
    'motion-wear': 0.15,
    'wear-tone': 0.15,
    'drive-wear-room': 0.15,
    'tone-wear-echo': 0.15,
    'wear-hiss': 0,
    'wear-hiss-hall': 0,
    'drive-hiss': 0,
    'loop-wear': 0.3,
    'loop-wear-hall': 0.2,
    'pulse-echo': 1.8,
    'pulse-room': 1.6,
    'pulse-hall': 1.2,
    'tone-pulse': 1.4,
    'motion-room': 1.3,
    'grain-room': 1.6,
    'grain-echo': 1.5,
    'drive-grain': 1.3,
    'hold-hall': 0.15,
    'swell-hold': 0.1,
    'hold-motion': 0.15,
    'hold-wear': 0,
    'hold-halo': 0.15,
    'hold-tone': 0.15,
    'hold-motion-hall': 0.1,
    'grain-wear': 0,
    'grain-tone': 0.5,
    'pitch-tone': 0.6,
    'pitch-room': 1.6,
    'pitch-echo': 1.5,
    'pitch-motion': 1.3,
    'drive-pitch': 1.3,
    'pitch-width': 1.3,
    'pitch-wear': 0,
    'pitch-hold': 0.15,
    'wear-ceiling': 0.1,
    'wear-glue-ceiling': 0.1,
  },
  own: [
    {
      // An echo whose repeats hop to another pitch each time, in a spring tank or a small plate.
      id: 'patch-cables-hopping-echo',
      category: 'echo',
      lead: 0,
      count: 6,
      slots: [
        {
          presets: [
            'analog-delay:Fifth hop',
            'analog-delay:Octave hop',
            'lattice:Crystal cascade',
            'lattice:Pentatonic harp',
            'lattice:Sinking cascade',
            'pitch-shifter:Rising steps',
            'pitch-shifter:Falling steps',
            'grain-delay:Crystals',
            'grain-delay:Rising fifths',
            'grain-delay:Falling fourths',
            'cascade:Rising steps',
            'cascade:Slow staircase',
          ],
        },
        {
          role: 'room',
          devices: ['spring-reverb', 'plate-reverb', 'swarm-reverb', 'fdn-reverb', 'shimmer'],
          not: ['dark', 'far'],
        },
      ],
    },
    {
      // One line given harmony voices from the steps of the scale, doubled a little, in a plate or a small hall.
      id: 'patch-cables-line-in-harmony',
      category: 'pitch',
      lead: 0,
      count: 6,
      slots: [
        { role: 'pitch', devices: ['lattice'], not: ['strange'] },
        { role: 'width', devices: ['chorus', 'stereo-detune'], not: ['strange', 'dark'] },
        {
          devices: ['plate-reverb', 'spring-reverb', 'hall-reverb', 'fdn-reverb'],
          not: ['heavy', 'far', 'long', 'dark', 'strange'],
        },
      ],
    },
    {
      // A filter, a phaser or a level that jumps or chops several times a second, thrown about by an echo.
      id: 'patch-cables-stepped-voltage',
      category: 'motion',
      lead: 0,
      count: 5,
      slots: [
        { role: 'pulse', devices: ['auto-filter', 'phaser', 'flanger', 'tremolo'] },
        {
          role: 'echo',
          devices: ['analog-delay', 'tape-echo', 'echo-memory', 'expanse', 'shaped-reverb'],
          not: ['dark', 'worn', 'long', 'backwards'],
        },
      ],
    },
    {
      // Each note struck again in quick small copies until it bubbles, widened, in a small room.
      id: 'patch-cables-bubbles',
      category: 'texture',
      lead: 0,
      count: 5,
      slots: [
        {
          role: 'grain',
          devices: ['cascade', 'glitch', 'grain-cloud', 'grain-delay'],
          any: ['fast', 'high', 'bright'],
          not: ['strange', 'backwards', 'heavy'],
        },
        { role: 'width', devices: ['chorus', 'stereo-detune', 'phaser'], not: ['strange', 'dark'] },
        { role: 'room', not: ['dark', 'far', 'narrow'] },
      ],
    },
    {
      // A folded or driven edge, then a filter that opens on each note or stands part shut, in a spring tank or a small room.
      id: 'patch-cables-fold-and-gate',
      category: 'tape',
      lead: 0,
      count: 5,
      slots: [
        { role: 'drive', devices: ['saturator', 'analog-drive'], any: ['bright'] },
        { devices: ['auto-filter'], not: ['slow', 'dark'] },
        { role: 'room', devices: ['spring-reverb', 'plate-reverb', 'fdn-reverb', 'ether-reverb'] },
      ],
    },
  ],
  heads: [
    'Cedar',
    'Fern',
    'Kelp',
    'Rockpool',
    'Greenhouse',
    'Garden',
    'Island',
    'Ferry',
    'Dockside',
    'Morning',
    'Dew',
    'Sapling',
    'Sprouting',
    'Seedling',
    'Tendril',
    'Salal',
    'Hemlock',
    'Inlet',
    'Cove',
    'Saltwater',
    'Patched',
    'Voltage',
    'Hand-wired',
    'Cabled',
    'Re-patched',
    'Plugged-in',
    'Clover',
    'Foxglove',
    'Trillium',
    'Lupine',
    'Heron',
    'Wren',
    'Kingfisher',
    'Tree-frog',
    'Bumblebee',
    'Otter',
    'Pollen',
    'Sapwood',
    'Canopy',
    'Porch',
    'Woodshed',
    'Rain-barrel',
    'Wharf',
    'Shingle',
    'Windowsill',
    'Trellis',
    'Seed-tray',
    'Orchard',
    'Eelgrass',
    'Barnacle',
    'Starfish',
    'Pebble',
    'Loam',
    'Green',
    'Huckleberry',
    'Salmonberry',
    'Frog-pond',
    'Rowboat',
    'Mooring',
    { word: 'Bubbling', for: ['fast'] },
    { word: 'Darting', for: ['fast', 'short'] },
    { word: 'Dappled', for: ['bright'] },
    { word: 'Sunbreak', for: ['bright'] },
    { word: 'Top-octave', for: ['high'] },
    { word: 'Treetop', for: ['high'] },
    { word: 'Taproot', for: ['low'] },
    { word: 'Shaded', for: ['dark'] },
    { word: 'Next-island', for: ['far'] },
    { word: 'Inhaled', for: ['backwards'] },
    { word: 'Perennial', for: ['frozen', 'long'] },
    { word: 'Slow-growing', for: ['slow'] },
  ],
  tails: [
    'in the ferns',
    'under cedar',
    'on the island',
    'in the garden',
    'by the dock',
    'on the ferry',
    'in the kelp',
    'patched in',
    'in leaf',
    'on the porch',
    'by the cove',
    'in a hothouse',
    'in dew',
    'in clover',
    'on wet cedar',
    'off the cable',
    'by the pond',
    'with the bees',
    'at the inlet',
    'from seed',
    'in new leaf',
    'in shallows',
    'in green',
    'on the sill',
    { word: 'in full sun', for: ['bright'] },
    { word: 'in the shade', for: ['dark'] },
    { word: 'at the roots', for: ['low'] },
    { word: 'in the crown', for: ['high'] },
    { word: 'in a hurry', for: ['fast'] },
    { word: 'one cove over', for: ['far'] },
    { word: 'still growing', for: ['long'] },
    { word: 'breathed in', for: ['backwards'] },
  ],
  avoid: ['tide'],
}
