// Polar Night Signal: short loops in a cold space, a radio a long way off,
// static, and a sub under it all. Its chains are loops through old
// converters, far stations and crackle before anything else; the space is
// large, cold and dull; nothing is warm, quick or sweet.

import { type PackPalette } from './types'

export const PALETTE: PackPalette = {
  pack: 'polar-signal',
  groups: { space: 20, echo: 20, tape: 26, motion: 6, texture: 11, pitch: 11, master: 6 },
  traits: {
    cold: 2.2,
    far: 2.2,
    dark: 1.5,
    low: 1.6,
    narrow: 1.4,
    noisy: 1.4,
    slow: 1.4,
    long: 1.3,
    worn: 1.3,
    frozen: 1.2,
    unsteady: 0.9,
    short: 0.8,
    bright: 0.6,
    strange: 0.5,
    warm: 0.55,
    high: 0.3,
    fast: 0.15,
  },
  devices: {
    radio: 4.5,
    'noise-floor': 4,
    'micro-looper': 3,
    'vintage-digital': 2.6,
    'half-speed': 2.6,
    'tape-loop': 2.4,
    expanse: 1.8,
    vinyl: 1.6,
    'auto-filter': 1.5,
    'hall-reverb': 1.5,
    patina: 1.5,
    'spectral-blur': 1.4,
    'echo-memory': 1.3,
    'low-bitrate': 1.3,
    'grain-cloud': 1.3,
    'ambient-eq': 1.1,
    'fdn-reverb': 1,
    'shaped-reverb': 0.8,
    tape: 0.7,
    'vowel-reverb': 0.7,
    'plate-reverb': 0.7,
    sustainer: 0.7,
    'freq-shifter': 0.6,
    'grain-delay': 0.6,
    'spectral-drifter': 0.6,
    'analog-drive': 0.5,
    'stereo-detune': 0.5,
    'pad-follower': 0.5,
    'pitch-shifter': 0.5,
    'swarm-reverb': 0.4,
    tremolo: 0.4,
    saturator: 0.3,
    glitch: 0.3,
    're-amp': 0.25,
    sympathetic: 0.1,
    shimmer: 0.1,
    phaser: 0.08,
    chorus: 0.08,
    cascade: 0.06,
    // Nothing here is a jet, a harmoniser, a spinning horn or a spring.
    flanger: 0,
    lattice: 0,
    rotary: 0,
    'spring-reverb': 0,
  },
  voices: {
    // A flanger in all but its device: weighed as this pack weighs flangers.
    'tremolo:Drifting comb': 0,
    // The far station, the static and the horn across the water.
    'radio:Night shortwave': 1.6,
    'radio:Far station': 1.6,
    'patina:Shortwave': 2,
    'patina:Distant station': 2,
    'patina:Early sampler': 1.8,
    'noise-floor:Radio static': 2,
    'noise-floor:Distant rumble': 1.6,
    'freq-shifter:Radio ring': 2,
    'freq-shifter:Sunken bell': 2,
    // Of the loudspeakers, only the far ones and the small ones.
    're-amp:Down the hall': 8,
    're-amp:Far end of the hall': 8,
    're-amp:Station platform': 6,
    're-amp:Bedside radio': 6,
    're-amp:Just the room': 5,
    're-amp:Room underneath': 4,
    're-amp:Pillow speaker': 4,
    // The cold space: dulled, far, its tail falling flat.
    'ambient-eq:Distant': 1.3,
    'auto-filter:Glacial low-pass': 2,
    'bloom-reverb:Winter drift': 2,
    'bloom-reverb:Long dark': 1.6,
    'expanse:Thin air': 1.5,
    'expanse:Wash alone': 0.6,
    // What moves here moves like breath, surf or still water.
    'tremolo:Gentle breath': 5,
    'tremolo:Sea swell': 5,
    'freq-shifter:Still water': 4,
    'freq-shifter:Slow drift': 4,
    // The few that belong among effects the pack otherwise leaves alone.
    'cascade:Deep drone': 10,
    'glitch:Skipping disc': 3,
    'glitch:Phrase repeats': 2.5,
    'analog-drive:Tape weight': 2.5,
    'analog-drive:Iron lows': 2.5,
    'analog-drive:Low warmth': 2.5,
    // Too bright, too warm or too sweet for the place.
    'ambient-eq:Warm': 0.4,
    'ambient-eq:Bright': 0.15,
    'analog-drive:Sheen': 0.1,
    'analog-drive:Parallel grit': 0.1,
    'analog-drive:Bite': 0.1,
    'saturator:Folded glass': 0.3,
    'saturator:Drum bus crunch': 0.3,
    'glitch:Shards': 0.2,
    'phaser:Still formant': 0.3,
    'micro-looper:Octave up': 0.3,
    // No summer, no sunrise and nothing that glitters upwards in two months of dark.
    'bloom-reverb:Wide summer': 0,
    'bloom-reverb:Endless rise': 0,
    'swell:Sunrise': 0,
    'cascade:Glass rain': 0,
    'grain-cloud:Rising shimmer': 0,
  },
  recipes: {
    'loop-hall': 1.8,
    'loop-room': 1.3,
    'tone-loop': 1.5,
    'loop-tone-hall': 1.6,
    'wear-hall': 1.8,
    'wear-hiss': 2.5,
    'wear-hiss-hall': 2.5,
    'tone-wear': 1.4,
    'loop-wear': 1.6,
    'loop-wear-hall': 1.6,
    'tone-hall': 1.5,
    'hall-tone': 1.4,
    'tone-room-hall': 1.4,
    'pitch-hall': 1.5,
    'pitch-tone': 1.4,
    'pitch-wear': 1.5,
    'grain-hall': 1.4,
    'hold-hall': 1.4,
    'grain-wear': 1.3,
    'hold-wear': 1.3,
    'motion-hall': 1.3,
    'motion-wear': 1.3,
    'motion-tone': 1.3,
    'wear-ceiling': 1.6,
    'wear-glue-ceiling': 1.6,
    'tone-glue-ceiling': 1.4,
    'width-ceiling': 0.6,
    'glue-width-ceiling': 0.6,
    'drive-hall': 0.4,
    'drive-room': 0.3,
    'drive-echo': 0.3,
    'drive-echo-hall': 0.3,
    'drive-wear': 0.4,
    'drive-tone': 0.4,
    'drive-wear-room': 0.3,
    'drive-motion': 0.3,
    'drive-motion-hall': 0.3,
    'drive-grain': 0.3,
    'drive-pitch': 0.4,
    'drive-hiss': 0.3,
    'width-hall': 0.6,
    'pitch-motion': 0.3,
    'halo-hall': 0.6,
    'echo-echo': 0.5,
    'width-room': 0.4,
    'width-motion': 0.15,
    'hold-motion': 0.5,
    'motion-motion': 0.4,
    'pulse-echo': 0.03,
    'pulse-hall': 0.03,
    'pulse-room': 0.03,
    'tone-pulse': 0.03,
    'room-halo': 0.6,
    'tone-halo': 0.6,
    'swell-halo': 0.6,
    'echo-halo': 0.6,
    'hold-halo': 0.6,
    'pitch-halo': 0.6,
    'motion-halo': 0.6,
  },
  own: [
    {
      // The pack in one chain: a short sampled loop, through early converters, round again in a cold space.
      id: 'polar-loop-in-cold-space',
      category: 'echo',
      lead: 0,
      count: 6,
      slots: [
        { role: 'loop', devices: ['micro-looper', 'tape-loop'], not: ['bright', 'fast', 'high'] },
        {
          role: 'wear',
          devices: ['vintage-digital', 'patina', 'low-bitrate'],
          any: ['cold', 'dark'],
          not: ['bright', 'strange'],
        },
        { role: 'hall', any: ['cold', 'far', 'dark', 'long'], not: ['bright'] },
      ],
    },
    {
      // A station a long way off, sinking under its static, heard in a large empty place.
      id: 'polar-far-station',
      category: 'tape',
      lead: 0,
      count: 6,
      slots: [
        { role: 'wear', devices: ['radio', 'patina'], any: ['far', 'narrow'] },
        { role: 'hall', any: ['far', 'dark', 'long', 'cold'] },
      ],
    },
    {
      // A bar lifted from a record, crackle and all, caught in a loop that keeps coming round.
      id: 'polar-record-in-a-loop',
      category: 'tape',
      lead: 0,
      count: 4,
      slots: [
        { role: 'wear', devices: ['vinyl'] },
        {
          role: 'loop',
          devices: ['micro-looper', 'tape-loop', 'echo-memory'],
          not: ['bright', 'fast'],
        },
        { role: 'hall', any: ['dark', 'far', 'long', 'cold'] },
      ],
    },
    {
      // What the dial gives between stations: the sound dulled, static or rumble laid under it, a far space.
      id: 'polar-static-under',
      category: 'tape',
      lead: 1,
      count: 5,
      slots: [
        {
          role: 'tone',
          devices: ['auto-filter', 'ambient-eq'],
          any: ['dark', 'far', 'cold', 'slow'],
        },
        { role: 'hiss', devices: ['noise-floor', 'radio'] },
        { role: 'hall', any: ['far', 'dark', 'long', 'cold'], not: ['bright'] },
      ],
    },
    {
      // The octave below at half speed with the top taken off: more felt than heard.
      id: 'polar-sub-under',
      category: 'pitch',
      lead: 0,
      count: 5,
      slots: [
        {
          role: 'pitch',
          devices: ['half-speed', 'octaves', 'pitch-shifter', 'grain-delay'],
          any: ['low'],
          not: ['high', 'fast', 'strange'],
        },
        {
          role: 'tone',
          devices: ['auto-filter', 'ambient-eq'],
          any: ['dark', 'far', 'cold', 'slow'],
        },
        { role: 'hall', any: ['dark', 'long', 'far'], not: ['bright'] },
      ],
    },
    {
      // A horn across open water: the sound set far off first, then thrown into a long cold space.
      id: 'polar-across-the-water',
      category: 'space',
      lead: 1,
      count: 4,
      slots: [
        {
          devices: ['re-amp', 'ambient-eq', 'low-bitrate', 'ether-reverb', 'tape-loop'],
          want: ['far'],
          not: ['heavy'],
        },
        { role: 'hall', any: ['far', 'long', 'cold'], not: ['bright'] },
      ],
    },
  ],
  heads: [
    'Harbour',
    'Quayside',
    'Midwinter',
    'Snowbound',
    'Icebound',
    'Northern',
    'Arctic',
    'Fjord',
    'Lighthouse',
    'Coastguard',
    'Trawler',
    'Ferry',
    'Breakwater',
    'Pier-end',
    'Sodium-lit',
    'Lamp-lit',
    'Tundra',
    'Treeline',
    'Headland',
    'Island',
    'Jetty',
    'Slipway',
    'Mooring',
    'Boathouse',
    'Net-loft',
    'Transmitter',
    'Relay',
    'Weather-hut',
    'Lightship',
    'Pack-ice',
    'Sea-ice',
    'Snowfield',
    'Snowline',
    'Hoarfrost',
    'Moonlit',
    'Starlit',
    'Blue-hour',
    'January',
    'December',
    'Solstice',
    'Small-hours',
    'Night-watch',
    'Leeward',
    'Windward',
    'Coastal',
    'Skerry',
    'Tideline',
    'Cabin',
    'Generator',
    'Snowplough',
    'Streetlamp',
    'Shuttered',
    'Tin-roof',
    'Night-band',
    'Coast-station',
    'Callsign',
    'Forecast',
    'Bell-buoy',
    'Wheelhouse',
    'Mast-light',
    { word: 'Far-shore', for: ['far'] },
    { word: 'Fogbound', for: ['far', 'dark'] },
    { word: 'Snow-muffled', for: ['dark'] },
    { word: 'Sleet-blown', for: ['noisy'] },
    { word: 'Frostbitten', for: ['cold'] },
    { word: 'Below-deck', for: ['low'] },
    { word: 'Ice-locked', for: ['frozen'] },
    { word: 'Narrow-band', for: ['narrow'] },
    { word: 'Off-station', for: ['strange'] },
    { word: 'Slow-thaw', for: ['slow'] },
    { word: 'Wind-bent', for: ['unsteady'] },
  ],
  tails: [
    'under snow',
    'at the quay',
    'off the pier',
    'in midwinter',
    'by lamplight',
    'over the town',
    'on the ferry',
    'at the mast',
    'off the coast',
    'in january',
    'at the pass',
    'in the lee',
    'before thaw',
    'out at anchor',
    'on the fjord',
    'in harbour',
    'on the floe',
    'up the coast',
    'at the light',
    'past the buoy',
    { word: 'in the dark', for: ['dark'] },
    { word: 'far offshore', for: ['far'] },
    { word: 'across water', for: ['far'] },
    { word: 'below deck', for: ['low'] },
    { word: 'under the ice', for: ['low', 'dark'] },
    { word: 'iced over', for: ['frozen', 'cold'] },
    { word: 'blown back', for: ['backwards'] },
    { word: 'through sleet', for: ['noisy'] },
    { word: 'between bands', for: ['strange', 'noisy'] },
  ],
  avoid: ['wireless', 'horizon', 'memories', 'shortwave', 'shaft'],
}
