// Indiana Reel Room: slow orchestral swells run through tape until they blur,
// over a drone low enough to feel. Its chains are a reel and its hiss first, a
// steep filter and a slowed copy second, and a long dark room behind; every
// attack is taken away and every fade is long. Nothing is bright, quick,
// clean-edged or digital.

import { type PackPalette } from './types'

export const PALETTE: PackPalette = {
  pack: 'reel-room',
  groups: { space: 17, echo: 14, tape: 22, motion: 6, texture: 18, pitch: 17, master: 6 },
  traits: {
    dark: 2,
    low: 1.6,
    slow: 1.6,
    long: 1.5,
    warm: 1.6,
    worn: 1.5,
    noisy: 1.4,
    far: 1.3,
    unsteady: 1.2,
    bright: 0.2,
    high: 0.12,
    cold: 0.25,
    fast: 0.08,
    strange: 0.15,
    short: 0.5,
    clean: 0.7,
    narrow: 0.8,
  },
  devices: {
    tape: 1.5,
    'noise-floor': 3,
    'half-speed': 2.6,
    'tape-loop': 2.2,
    swell: 2.2,
    'ambient-eq': 1.6,
    'auto-filter': 1.4,
    'ambient-comp': 1.4,
    'pad-follower': 1.5,
    sustainer: 1.4,
    patina: 2,
    'analog-drive': 1.3,
    'plate-reverb': 1.7,
    'hall-reverb': 1.7,
    'fdn-reverb': 1.2,
    expanse: 1.1,
    'spectral-blur': 1.4,
    'micro-looper': 1.3,
    'tape-echo': 1.3,
    octaves: 1.1,
    'reverse-delay': 1.2,
    'echo-memory': 1,
    saturator: 0.8,
    'shaped-reverb': 0.7,
    'ether-reverb': 0.7,
    'bloom-reverb': 0.6,
    'analog-delay': 0.35,
    'stereo-detune': 0.3,
    'pitch-shifter': 0.6,
    'vowel-reverb': 0.5,
    'swarm-reverb': 0.5,
    'grain-cloud': 0.7,
    'grain-delay': 0.5,
    chorus: 0.5,
    're-amp': 0.4,
    tremolo: 0.5,
    sympathetic: 0.2,
    cascade: 0.2,
    shimmer: 0.15,
    'spring-reverb': 0.1,
    glitch: 0.03,
    'freq-shifter': 0.03,
    rotary: 0.02,
    vinyl: 0.01,
    // No place here at all: nothing in this room is digital, comes off the air or sweeps like a jet.
    flanger: 0,
    phaser: 0,
    lattice: 0,
    radio: 0,
    'low-bitrate': 0,
    'vintage-digital': 0,
  },
  voices: {
    // The recorder's own hiss, which the lexicon hears as bright, ahead of rumble and hum.
    'noise-floor:Tape floor': 8,
    'noise-floor:Breathing tape': 8,
    'noise-floor:Riding hiss': 8,
    'noise-floor:Wall of hiss': 4,
    'noise-floor:Faint hiss': 4,
    'noise-floor:Muffled hiss': 3,
    'noise-floor:Distant rumble': 0.5,
    'noise-floor:Mains hum': 0.5,
    'noise-floor:Empty room': 0.6,
    'tape:Hiss and air': 3,
    'patina:Quarter inch reel': 1.2,
    'patina:Falling apart': 0.3,
    'tape:Chewed cassette': 0.3,
    'patina:Worn cassette': 1.5,
    'patina:Reel pushed hard': 1.5,
    // Records, radio and samplers are another pack's dirt.
    'noise-floor:Old record': 0.005,
    'noise-floor:Gap crackle': 0.005,
    'noise-floor:Radio static': 0.005,
    'noise-floor:Static notes': 0.005,
    'patina:Dusty record': 0.01,
    'patina:Scratched record': 0.01,
    'patina:Shortwave': 0.01,
    'patina:Distant station': 0.01,
    'patina:Kitchen radio': 0.01,
    'patina:Muffled sampler': 0.01,
    'micro-looper:Sampler grit': 0.01,
    'micro-looper:Lo-fi quarter': 0.01,
    'auto-filter:Phone line': 0.05,
    'saturator:Lo-fi': 0.03,
    'saturator:Sustain bed': 0.05,
    // The steep filter, the slow hand on the fader, the transformer.
    'auto-filter:Low-pass gate': 1.8,
    'auto-filter:Glacial low-pass': 3,
    'ambient-eq:Muffled': 1.5,
    'ambient-eq:Thin': 0.1,
    'ambient-eq:Hollow': 0.1,
    'ambient-eq:Bright': 0.05,
    'ambient-eq:Texture': 0.4,
    'ambient-eq:Voice': 0.4,
    'auto-filter:Falling high-pass': 0,
    'auto-filter:Dub sweep': 0,
    'auto-filter:Touch wah': 0,
    'auto-filter:Slow notch': 0.4,
    'ambient-comp:Slow fader': 2,
    'analog-drive:Iron lows': 1.8,
    'analog-drive:Low warmth': 1.5,
    'analog-drive:Dark fuzz': 0.02,
    'analog-drive:Crushed': 0.05,
    'analog-drive:Iron melt': 0.05,
    'analog-drive:Console': 0.3,
    'hall-reverb:Vast nave': 1.5,
    'plate-reverb:Dark plate': 1.5,
    // Undamped rooms the lexicon does not call bright.
    'hall-reverb:Bright hall': 0.2,
    'fdn-reverb:Bright air': 0.2,
    'fdn-reverb:Small bright tank': 0.3,
    'ether-reverb:Shining tail': 0.4,
    'bloom-reverb:Endless rise': 0.1,
    // What moves here is the reel and the fader, nothing that turns or bounces.
    'tremolo:Sea swell': 2,
    'tremolo:Gentle breath': 2,
    'tape:Drifting chorus': 1,
    'chorus:Warped tape': 2,
    'glitch:Winding down': 3,
    'half-speed:Slow chops': 0.01,
    'tape-echo:Dotted bounce': 0.04,
    'tape-echo:Two head gallop': 0.04,
    'tape-echo:Three heads': 0.5,
    'analog-delay:Fifth hop': 0.1,
    'analog-delay:Octave hop': 0.1,
    'stereo-detune:Spiral': 0.1,
    'stereo-detune:Melting': 0.5,
    'grain-cloud:Choir of fifths': 0.1,
    'shaped-reverb:Late wall': 0.1,
    'expanse:Hard echoes': 0.1,
    'phaser:Still formant': 0.2,
    // A whole mix here is quiet: nothing is pressed against the ceiling.
    'ambient-limiter:Pinned': 0.05,
    'ambient-limiter:Loud': 0.05,
    'fet-limiter:Squash': 0.05,
    'fet-limiter:Flattened': 0.05,
  },
  recipes: {
    'swell-hall': 1.8,
    'tone-hall': 1.6,
    'hall-tone': 1.6,
    'hall-glue': 1.3,
    'room-hall': 0.6,
    'halo-hall': 0.3,
    'room-halo': 0.1,
    'tone-halo': 0.4,
    'swell-halo': 0.4,
    'swell-halo-hall': 0.4,
    'tone-room-hall': 0.6,
    'drive-room': 0.5,
    'width-room': 0.3,
    'width-hall': 0.3,
    'hall-width': 0.2,
    'loop-hall': 2,
    'loop-tone-hall': 2,
    'tone-loop': 1.6,
    'swell-echo': 1.4,
    'echo-tone': 1.2,
    'echo-echo': 0.3,
    'echo-width': 0.3,
    'echo-room': 0.5,
    'motion-echo': 0.5,
    'drive-echo': 0.5,
    'drive-echo-hall': 0.6,
    'wear-hiss': 2.4,
    'wear-hiss-hall': 2.6,
    'drive-hiss': 0.8,
    'wear-hall': 1.6,
    'wear-wear': 1.6,
    'loop-wear': 1.6,
    'loop-wear-hall': 1.8,
    'tone-wear': 1.6,
    'wear-tone': 1.6,
    'wear-echo': 0.6,
    'wear-room': 0.6,
    'motion-wear': 0.6,
    'motion-hall': 2,
    'motion-tone': 1.8,
    'swell-motion': 1.8,
    'motion-room': 0.6,
    'motion-motion': 0.15,
    'width-motion': 0.4,
    'motion-halo': 0.3,
    'motion-echo-hall': 0.3,
    'drive-motion': 0.6,
    // Nothing here has a beat.
    'pulse-echo': 0,
    'pulse-hall': 0,
    'pulse-room': 0,
    'tone-pulse': 0,
    'hold-wear': 1.8,
    'swell-hold': 1.8,
    'hold-hall': 1.6,
    'hold-tone': 1.5,
    'grain-room': 0.25,
    'hold-motion': 0.5,
    'grain-echo': 0.4,
    'drive-grain': 0.3,
    'swell-width': 0.4,
    'hold-halo': 0.5,
    'pitch-wear': 2,
    'pitch-tone': 1.8,
    'pitch-hall': 1.5,
    'swell-pitch': 1.5,
    'swell-pitch-hall': 1.5,
    'pitch-hold': 1.2,
    'pitch-echo': 0.6,
    'pitch-motion': 0.3,
    'pitch-grain': 0.4,
    'pitch-halo': 0.4,
    'pitch-width': 0.3,
    'pitch-room': 0.5,
    'wear-ceiling': 1.5,
    'wear-glue-ceiling': 1.5,
    'width-ceiling': 0.4,
    'tone-width-ceiling': 0.4,
    'glue-width-ceiling': 0.4,
  },
  own: [
    {
      // The pack in one chain: a section that takes seconds to arrive, on a tired reel, far down a long dark room.
      id: 'reel-room-swell-to-reel',
      category: 'tape',
      lead: 1,
      count: 5,
      slots: [
        { role: 'swell', devices: ['swell'], not: ['fast'] },
        {
          role: 'wear',
          devices: ['tape', 'patina'],
          any: ['worn', 'dark', 'warm'],
          not: ['strange'],
        },
        { role: 'hall', any: ['dark', 'long', 'far'], not: ['bright', 'strange', 'high'] },
      ],
    },
    {
      // A recorder whose hiss comes up in every gap, into a long dark plate or hall.
      id: 'reel-room-hiss-in-the-gaps',
      category: 'tape',
      lead: 1,
      count: 5,
      slots: [
        {
          role: 'wear',
          devices: ['tape', 'patina'],
          any: ['worn', 'dark', 'warm'],
          not: ['strange'],
        },
        { role: 'hiss', devices: ['noise-floor'], not: ['worn'] },
        {
          role: 'hall',
          devices: ['plate-reverb', 'hall-reverb', 'fdn-reverb', 'expanse', 'ether-reverb'],
          any: ['dark', 'long', 'far', 'warm'],
          not: ['bright', 'cold'],
        },
      ],
    },
    {
      // A slowed copy bounced to tape, each pass duller, behind a steep filter.
      id: 'reel-room-slowed-copy',
      category: 'pitch',
      lead: 0,
      count: 5,
      slots: [
        {
          role: 'pitch',
          devices: ['half-speed', 'tape-loop', 'micro-looper'],
          want: ['low'],
          not: ['strange', 'fast'],
        },
        {
          role: 'wear',
          devices: ['tape', 'patina', 'analog-drive', 'tape-echo', 'chorus'],
          not: ['strange', 'bright', 'cold'],
        },
        { role: 'tone', devices: ['ambient-eq', 'auto-filter'], want: ['dark'] },
      ],
    },
    {
      // The drone under everything: the octave below, a filter set low, then a transformer or a tape stage.
      id: 'reel-room-sub-under',
      category: 'pitch',
      lead: 0,
      count: 4,
      slots: [
        {
          role: 'pitch',
          devices: ['octaves', 'pitch-shifter', 'pad-follower', 'grain-delay'],
          want: ['low'],
          not: ['high', 'strange'],
        },
        { role: 'tone', devices: ['ambient-eq', 'auto-filter'], want: ['dark'] },
        {
          role: 'drive',
          devices: ['analog-drive', 'saturator', 'patina'],
          any: ['warm', 'dark'],
          not: ['bright', 'strange'],
        },
      ],
    },
    {
      // A phrase fed to a long loop that plays backwards, so each chord returns as a swell with no start.
      id: 'reel-room-played-from-the-end',
      category: 'echo',
      lead: 0,
      count: 5,
      slots: [
        {
          devices: ['tape-loop', 'reverse-delay', 'micro-looper', 'echo-memory'],
          want: ['backwards'],
          not: ['fast', 'bright', 'high', 'cold'],
        },
        {
          role: 'wear',
          devices: ['tape', 'patina', 'analog-drive', 'tape-echo', 'chorus'],
          not: ['strange', 'bright', 'cold'],
        },
        { role: 'hall', any: ['dark', 'long', 'far'], not: ['bright', 'strange', 'high'] },
      ],
    },
    {
      // A bed held under the playing, behind the filter, with a hand on the fader that takes minutes.
      id: 'reel-room-long-fade',
      category: 'texture',
      lead: 0,
      count: 4,
      slots: [
        {
          role: 'hold',
          devices: ['pad-follower', 'sustainer', 'spectral-blur'],
          any: ['dark', 'low', 'slow'],
          not: ['bright', 'high', 'cold'],
        },
        { role: 'tone', devices: ['ambient-eq', 'auto-filter'], any: ['dark', 'slow'] },
        { role: 'glue', devices: ['ambient-comp'], want: ['slow'] },
      ],
    },
  ],
  heads: [
    'Reel-room',
    'Joist',
    'Crawl-space',
    'Lath',
    'Subfloor',
    'Ductwork',
    'Flat-roof',
    'Stovepipe',
    'Root-cellar',
    'Furnace-room',
    'Coal-chute',
    'Linoleum',
    'Wainscot',
    'Radiator',
    'Storm-window',
    'Band-room',
    'Bleacher',
    'Folding-chair',
    'Music-stand',
    'Stand-light',
    'Back-desk',
    'Bow-hair',
    'Cork-grease',
    'Tuning-note',
    'County-line',
    'Stubble',
    'Fencerow',
    'Haymow',
    'Seed-corn',
    'Feed-mill',
    'Section-line',
    'Gravel-road',
    'Township',
    'Bottomland',
    'Fallow',
    'Furrow',
    'Corncrib',
    'Pole-barn',
    'Rail-spur',
    'Flatland',
    'Ploughed',
    'Chaff',
    'Winter-wheat',
    'Ground-fog',
    'First-frost',
    'Killing-frost',
    'Late-harvest',
    'Heat-lightning',
    'Snow-fence',
    'Mud-season',
    'February',
    'Yard-light',
    'Barn-light',
    'Lake-effect',
    'Second-copy',
    'Splice-block',
    'Grease-pencil',
    'Razor-cut',
    'Bounce-down',
    'Head-gap',
    'Pinch-roller',
    'Capstan',
    'Half-track',
    'Erase-head',
    'Supply-reel',
    'Line-up',
    'Seven-inch',
    { word: 'Third-copy', for: ['worn'] },
    { word: 'Slack-spool', for: ['unsteady'] },
    { word: 'Tails-out', for: ['backwards'] },
    { word: 'Low-speed', for: ['low'] },
    { word: 'Subsoil', for: ['low'] },
    { word: 'Motor-on', for: ['noisy'] },
    { word: 'Next-county', for: ['far'] },
    { word: 'Rolled-off', for: ['dark'] },
    { word: 'Con-sordino', for: ['dark'] },
    { word: 'Minutes-long', for: ['long'] },
    { word: 'Never-stopped', for: ['frozen'] },
    { word: 'Slow-arriving', for: ['slow'] },
  ],
  tails: [
    'by the deck',
    'on take-up',
    'by the silo',
    'in stubble',
    'behind lath',
    'down a duct',
    'off a spool',
    'at harvest',
    'in low fog',
    'by one bulb',
    'in february',
    'on the flat',
    'down a row',
    'by the barn',
    'in plaster',
    'out back',
    'by the boiler',
    'before snow',
    'all winter',
    'at a splice',
    'at the mill',
    'under tin',
    'in the gym',
    'on risers',
    'on a siding',
    { word: 'in the hiss', for: ['noisy'] },
    { word: 'a county off', for: ['far'] },
    { word: 'tail first', for: ['backwards'] },
    { word: 'in the joists', for: ['low'] },
    { word: 'on third copy', for: ['worn'] },
    { word: 'run slack', for: ['unsteady'] },
    { word: 'slow to go', for: ['long'] },
    { word: 'still going', for: ['frozen'] },
    { word: 'into murk', for: ['dark'] },
  ],
  // "Erase-head heads": the noun reads badly after this pack's own tape words.
  avoid: ['heads'],
}
