// Rosewood Circles: wooden bars under soft mallets, patterns that turn round
// each other, gongs and bowls between, all of it in real rooms. Its chains
// are echoes set a fraction of a beat behind, short rooms and plates, tuned
// strings that ring on after a stroke, and a little clean tape; nothing is
// washed out, worn or broken, and every attack stays clear.

import { type PackPalette } from './types'

export const PALETTE: PackPalette = {
  pack: 'rosewood',
  groups: { space: 25, echo: 30, tape: 9, motion: 8, texture: 10, pitch: 11, master: 7 },
  traits: {
    clean: 1.6,
    short: 1.6,
    warm: 1.3,
    faint: 1.15,
    fast: 1.1,
    dark: 0.8,
    cold: 0.7,
    slow: 0.75,
    low: 0.55,
    narrow: 0.6,
    far: 0.55,
    long: 0.3,
    backwards: 0.12,
    unsteady: 0.25,
    worn: 0.15,
    noisy: 0.15,
    heavy: 0.08,
    strange: 0.05,
    frozen: 0.1,
  },
  devices: {
    'tape-echo': 2.4,
    sympathetic: 2.8,
    'hall-reverb': 1.8,
    'fdn-reverb': 1.6,
    'plate-reverb': 1.6,
    tremolo: 2.4,
    'analog-delay': 1.8,
    'echo-memory': 1.5,
    cascade: 1.6,
    lattice: 1.5,
    swell: 1.5,
    'ether-reverb': 1.3,
    'swarm-reverb': 1,
    tape: 1.3,
    'pitch-shifter': 1.2,
    'tape-loop': 1.1,
    'shaped-reverb': 1,
    expanse: 0.55,
    octaves: 0.8,
    'micro-looper': 0.7,
    chorus: 0.8,
    'stereo-detune': 0.5,
    'vowel-reverb': 0.45,
    saturator: 0.7,
    patina: 0.7,
    'analog-drive': 0.6,
    'spring-reverb': 0.12,
    'pad-follower': 0.6,
    sustainer: 0.6,
    'auto-filter': 0.6,
    're-amp': 0.03,
    'grain-delay': 0.5,
    'bloom-reverb': 0.3,
    'grain-cloud': 0.3,
    'spectral-blur': 0.4,
    rotary: 0.04,
    phaser: 0.03,
    'reverse-delay': 0.08,
    shimmer: 0.08,
    flanger: 0.1,
    'half-speed': 0.1,
    'spectral-drifter': 0.3,
    'freq-shifter': 0.08,
    'noise-floor': 0.2,
    // No place here at all: records, radios, starved streams, old converters, glitches.
    vinyl: 0,
    'vintage-digital': 0,
    glitch: 0,
    radio: 0,
    'low-bitrate': 0,
  },
  voices: {
    // A flanger in all but its device: weighed as this pack weighs flangers.
    'tremolo:Drifting comb': 0.1,
    'tape-echo:Dotted bounce': 1.4,
    'tape-echo:Two head gallop': 2,
    'tape-echo:Three heads': 1.8,
    'analog-delay:Clean echo': 2,
    'echo-memory:Plain echo': 1.6,
    'echo-memory:Side to side': 1.6,
    'expanse:Hard echoes': 2.5,
    'shaped-reverb:Scattered': 2,
    'swarm-reverb:Pattering': 2.5,
    'cascade:Restruck': 2.5,
    'lattice:Pentatonic harp': 2,
    'sympathetic:Hammered': 1.5,
    'sympathetic:Follow the tune': 1.5,
    'vowel-reverb:Chapel': 1.6,
    'swell:Bowed': 1.5,
    'analog-delay:Seasick': 0.1,
    'tape-echo:Worn tape': 0.2,
    'tape-echo:Dub wash': 0.4,
    'tape-echo:Hovering wash': 0.3,
    'tape-echo:Wobbly double': 0.4,
    'swarm-reverb:Mine shaft': 0.1,
    'swarm-reverb:Cavern': 0.5,
    'ether-reverb:Dark infinite': 0.1,
    'spring-reverb:Tight long tank': 0.3,
    'analog-drive:Worn tape': 0.3,
    'stereo-widener:Narrow': 0.1,
    'grain-delay:Backwards shards': 0.2,
    'lattice:Rough high splinters': 0.2,
    'spectral-blur:Band of fog': 0.3,
    'patina:Muffled sampler': 0.02,
    'patina:Kitchen radio': 0.1,
    'phaser:Still formant': 0.1,
    'vowel-reverb:Choir alone': 0.1,
    'patina:Early sampler': 0.05,
    'patina:Eight bit': 0.05,
    'auto-filter:Falling high-pass': 0.05,
    'auto-filter:Dub sweep': 0.05,
    'auto-filter:Touch wah': 0.05,
    'auto-filter:Resonant peak': 0.3,
    'auto-filter:Glacial low-pass': 0.1,
    'vowel-reverb:High choir': 0.05,
    'vowel-reverb:Endless oo': 0.03,
    'vowel-reverb:Cathedral': 0.5,
    'fdn-reverb:Dark cave': 0.03,
    'fdn-reverb:Open valley': 0.15,
    'expanse:Open space': 0.5,
    'analog-delay:Fluttering': 0.3,
    'fdn-reverb:Endless tail': 0.3,
    'fdn-reverb:Slow swell': 0.3,
    'tape:Hiss and air': 0.2,
    'analog-delay:Noisy clock': 0.2,
    // Of the re-amped speakers only the rooms: the amplifiers stay out.
    're-amp:Room underneath': 20,
    're-amp:Just the room': 20,
    're-amp:Far end of the hall': 15,
    'cascade:Backwards stack': 0.3,
    // No place here at all: amplifier stacks, fuzz, a mix flattened or folded to mono.
    're-amp:Warm stack': 0,
    're-amp:Dark and woolly': 0,
    're-amp:Stack flat out': 0,
    're-amp:Speaker on the edge': 0,
    're-amp:Station platform': 0,
    're-amp:Combo in a room': 0,
    're-amp:In the cupboard': 0,
    're-amp:Just the valves': 0,
    're-amp:Clean and bright': 0,
    're-amp:Noisy valves': 0,
    're-amp:Bedside radio': 0,
    're-amp:Pillow speaker': 0,
    'saturator:Fuzz pedal': 0,
    'saturator:Wavefold lead': 0,
    'saturator:Blown speaker': 0,
    'patina:Valve fuzz': 0,
    'analog-drive:Torn cone': 0,
    'analog-drive:Iron melt': 0,
    'saturator:Sustain bed': 0.2,
    'analog-drive:Dark fuzz': 0,
    // Nor a wash with no end, a tunnel, a tail that will not hold its pitch, or a sampler's grit.
    'expanse:Event horizon': 0,
    'expanse:Wash alone': 0,
    'expanse:Seasick choir': 0,
    'expanse:Narrow tunnel': 0,
    'expanse:Fast flutter': 0,
    'swarm-reverb:Intervals': 0,
    'swarm-reverb:Endless': 0,
    'swarm-reverb:Vast hollow': 0,
    'micro-looper:Sampler grit': 0,
    'micro-looper:Lo-fi quarter': 0,
    'tape:Seasick': 0,
    'tape:Old dictation': 0,
    'tape:Chewed cassette': 0,
    'tape:Crumbling oxide': 0,
    'tape:Worn thin': 0,
    'tape:Cassette four-track': 0,
    'tape:Flutter shimmer': 0.2,
    'spring-reverb:Dub send': 0,
    'spring-reverb:Tank alone': 0,
    'spring-reverb:Slack and strange': 0,
    'spring-reverb:Single slack coil': 0,
    'analog-drive:Bite': 0.3,
    'analog-drive:Parallel grit': 0.3,
    'auto-filter:Low-pass gate': 0.02,
    'ambient-eq:Muffled': 0.2,
    'ambient-comp:Long sustain': 0.3,
    'stereo-widener:Mono': 0,
    'fet-limiter:Flattened': 0,
    'fet-limiter:Squash': 0,
    'ambient-limiter:Pinned': 0.05,
    'ambient-comp:Dense pad': 0.1,
    'ambient-comp:Pump': 0.1,
  },
  recipes: {
    'room-hall': 1.5,
    'room-halo': 1.6,
    'halo-hall': 1.3,
    'swell-hall': 1.4,
    'swell-halo': 1.5,
    'tone-room-hall': 1.3,
    'width-room': 1.3,
    'drive-room': 0.8,
    'drive-hall': 0.7,
    'echo-room': 2,
    'echo-echo': 1.7,
    'echo-halo': 1.5,
    'drive-echo': 0.8,
    'drive-echo-hall': 0.7,
    'motion-echo': 0.3,
    'motion-echo-hall': 0.3,
    'loop-hall': 0.7,
    'loop-tone-hall': 0.6,
    'tone-loop': 0.6,
    'echo-tone': 0.6,
    'hall-tone': 0.6,
    'tone-hall': 0.7,
    'wear-room': 2,
    'wear-echo': 2,
    'drive-wear-room': 1.5,
    'tone-wear-echo': 1.5,
    'wear-hiss': 0.15,
    'drive-hiss': 0.1,
    'wear-hiss-hall': 0.15,
    'wear-ceiling': 0.7,
    'wear-glue-ceiling': 0.7,
    'drive-tone': 0.4,
    'loop-wear-hall': 0.4,
    'pulse-room': 1.8,
    'pulse-echo': 1.6,
    'pulse-hall': 1.3,
    'tone-pulse': 1.2,
    'motion-room': 1.2,
    'motion-motion': 0.05,
    'motion-tone': 0.5,
    'drive-motion': 0.3,
    'drive-motion-hall': 0.4,
    'swell-motion': 0.6,
    'width-motion': 0.6,
    'swell-room': 1.8,
    'grain-room': 1.3,
    'grain-echo': 1.2,
    'grain-wear': 0.4,
    'hold-wear': 0.4,
    'drive-grain': 0.5,
    'hold-motion': 0.5,
    'hold-tone': 0.5,
    'grain-tone': 0.5,
    'hold-motion-hall': 0.4,
    'pitch-room': 1.8,
    'pitch-echo': 1.6,
    'pitch-halo': 1.3,
    'pitch-hall': 0.7,
    'pitch-wear': 0.4,
    'pitch-grain': 0.5,
    'pitch-motion': 0.5,
    'pitch-hold': 0.5,
  },
  own: [
    {
      // The pack in one chain: a pattern and its copy a fraction of a beat behind, in a short room.
      id: 'rosewood-pattern-in-a-room',
      category: 'echo',
      lead: 0,
      count: 6,
      slots: [
        {
          role: 'echo',
          devices: [
            'tape-echo',
            'analog-delay',
            'echo-memory',
            'expanse',
            'shaped-reverb',
            'grain-delay',
          ],
          not: ['unsteady', 'strange', 'worn', 'long', 'backwards', 'far'],
        },
        { role: 'room', not: ['far', 'backwards', 'narrow'] },
      ],
    },
    {
      // A stroke, then the strings nobody played ringing on after it, in a plain room or hall.
      id: 'rosewood-strings-ring-on',
      category: 'space',
      lead: 0,
      count: 5,
      slots: [
        { role: 'halo', devices: ['sympathetic'], not: ['heavy'] },
        {
          devices: ['hall-reverb', 'fdn-reverb', 'plate-reverb', 'ether-reverb'],
          not: ['long', 'heavy', 'far'],
        },
      ],
    },
    {
      // The fans of a metal-barred instrument turning: a steady pulse into a short plate or room.
      id: 'rosewood-fans-turning',
      category: 'motion',
      lead: 0,
      count: 4,
      slots: [
        { devices: ['tremolo'], not: ['strange', 'unsteady'] },
        {
          devices: ['plate-reverb', 'hall-reverb', 'fdn-reverb', 'ether-reverb'],
          not: ['long', 'heavy', 'far'],
        },
      ],
    },
    {
      // A small canon: each note answered a moment later at another pitch, in a room.
      id: 'rosewood-small-canon',
      category: 'pitch',
      lead: 0,
      count: 5,
      slots: [
        {
          role: 'pitch',
          devices: ['lattice', 'pitch-shifter', 'analog-delay', 'grain-delay', 'cascade'],
          not: ['strange', 'heavy', 'backwards', 'unsteady'],
        },
        { role: 'room', not: ['far', 'backwards'] },
      ],
    },
    {
      // One stroke struck again in a run of quieter ones, with strings or a room behind.
      id: 'rosewood-restruck',
      category: 'texture',
      lead: 0,
      count: 4,
      slots: [
        { devices: ['cascade'], not: ['heavy', 'long', 'backwards', 'low'] },
        {
          devices: ['sympathetic', 'hall-reverb', 'plate-reverb', 'fdn-reverb', 'swarm-reverb'],
          not: ['long', 'heavy', 'far'],
        },
      ],
    },
    {
      // Plucked firmly onto hot tape, with an echo weaving a second line behind.
      id: 'rosewood-hot-tape-pattern',
      category: 'tape',
      lead: 0,
      count: 4,
      slots: [
        {
          role: 'drive',
          devices: ['tape', 'patina', 'analog-drive', 'saturator'],
          any: ['warm'],
          not: ['worn', 'strange', 'dark'],
        },
        { role: 'echo', not: ['unsteady', 'strange', 'worn', 'long', 'backwards', 'far'] },
      ],
    },
  ],
  heads: [
    'Rosewood',
    'Hardwood',
    'Heartwood',
    'Padauk',
    'Paulownia',
    'Bamboo',
    'Cedar',
    'Hinoki',
    'Cut-cane',
    'Oiled-wood',
    'Unvarnished',
    'Lacquered',
    'Sawn-plank',
    'Bronze',
    'Gourd',
    'Silk-string',
    'Rawhide',
    'Goatskin',
    'Yarn-wound',
    'Cord-wound',
    'Rattan',
    'Birch-shaft',
    'Soft-mallet',
    'Four-mallet',
    'Two-player',
    'Four-hand',
    'Barefoot',
    'Kneeling',
    'Counted',
    'Unconducted',
    'Rehearsal',
    'Practice',
    'Recital',
    'Conservatory',
    'Backstage',
    'Workshop',
    'Tuning-bench',
    'Rainy-season',
    'Plum-rain',
    'Roof-tile',
    'Broad-leaf',
    'Charcoal',
    'Brazier',
    'Grove-wind',
    'Streamside',
    'Hill-thunder',
    'Cicada-noon',
    'Humid',
    'Midsummer',
    { word: 'Hand-damped', for: ['short'] },
    { word: 'Ringing', for: ['long'] },
    { word: 'Far-wall', for: ['far'] },
    { word: 'Rolled', for: ['fast'] },
    { word: 'Low-bar', for: ['low'] },
    { word: 'High-bar', for: ['high'] },
    { word: 'Unhurried', for: ['slow'] },
    { word: 'Hard-stick', for: ['bright'] },
    { word: 'Felt-beater', for: ['dark'] },
    { word: 'Wide-set', for: ['wide'] },
  ],
  tails: [
    'in rosewood',
    'on soft yarn',
    'in circles',
    'round again',
    'at rehearsal',
    'for two hands',
    'after rain',
    'under tiles',
    'by the stream',
    'on bare wood',
    'in the grove',
    'over gourds',
    'in bronze',
    'on the count',
    'in the wings',
    'before dusk',
    'off the hills',
    'at the bridge',
    'among gongs',
    'between bowls',
    'in the round',
    { word: 'left ringing', for: ['long'] },
    { word: 'a room away', for: ['far'] },
    { word: 'on low bars', for: ['low'] },
    { word: 'on small bars', for: ['high'] },
    { word: 'in no hurry', for: ['slow'] },
  ],
  avoid: ['glass', 'mirror'],
}
