// Berlin Sequencer, 1974: a bass sequence running all night under tape-replay
// flutes and choirs, a phased string ensemble and an organ. Its chains are a
// slow phaser, the heads of a tape echo, and a plate or a spring to end in;
// the medium is a studio reel, never a cassette, a record or a converter.

import { type PackPalette } from './types'

export const PALETTE: PackPalette = {
  pack: 'sequencer-1974',
  groups: { space: 17, echo: 23, tape: 12, motion: 23, texture: 8, pitch: 10, master: 7 },
  traits: {
    warm: 1.6,
    slow: 1.4,
    wide: 1.2,
    dark: 1.2,
    long: 1.15,
    cold: 0.6,
    high: 0.6,
    bright: 0.8,
    noisy: 0.6,
    worn: 0.7,
    strange: 0.35,
    backwards: 0.25,
    frozen: 0.5,
  },
  devices: {
    phaser: 3.5,
    'tape-echo': 3.5,
    'plate-reverb': 3.5,
    'spring-reverb': 2.6,
    flanger: 2,
    tape: 1.8,
    rotary: 1.6,
    'auto-filter': 1.6,
    'vowel-reverb': 1.5,
    'pad-follower': 1.5,
    octaves: 1.5,
    'analog-drive': 1.3,
    'half-speed': 1.2,
    'hall-reverb': 1.2,
    'tape-loop': 1.6,
    'fdn-reverb': 0.6,
    'ether-reverb': 0.5,
    expanse: 0.45,
    'shaped-reverb': 0.15,
    'swarm-reverb': 0.2,
    'bloom-reverb': 0.35,
    sympathetic: 0.5,
    'noise-floor': 0.7,
    patina: 0.9,
    'freq-shifter': 0.55,
    'reverse-delay': 0.15,
    'echo-memory': 0.08,
    'pitch-shifter': 0.3,
    lattice: 0.15,
    'spectral-blur': 0.15,
    radio: 0.03,
    shimmer: 0.2,
    'micro-looper': 0.2,
    cascade: 0.1,
    'grain-cloud': 0.2,
    'grain-delay': 0.1,
    vinyl: 0,
    'spectral-drifter': 0.08,
    tremolo: 0.8,
    glitch: 0,
    'low-bitrate': 0,
    'vintage-digital': 0,
  },
  voices: {
    'phaser:Warm six-stage': 2,
    'tape-echo:Three heads': 2,
    'tape-echo:Two head gallop': 2,
    'tape:Cassette four-track': 0,
    'tape:Old dictation': 0,
    'tape:Chewed cassette': 0,
    'tape:Warm thump': 0,
    'tape:Under a blanket': 0,
    'patina:Worn cassette': 0,
    'patina:Falling apart': 0,
    'patina:Dusty record': 0,
    'patina:Scratched record': 0,
    'patina:Shortwave': 0.1,
    'patina:Distant station': 0.1,
    'patina:Kitchen radio': 0.1,
    'patina:Early sampler': 0,
    'patina:Eight bit': 0,
    'patina:Muffled sampler': 0,
    'ambient-comp:Pump': 0.05,
    'saturator:Lo-fi': 0,
    'micro-looper:Lo-fi quarter': 0,
    'micro-looper:Sampler grit': 0,
    'stereo-widener:Narrow': 0.4,
    'stereo-widener:Mono': 0.3,
    're-amp:Bedside radio': 0.1,
    'fdn-reverb:Pulsing gate': 0.2,
    'tape:Crumbling oxide': 0.3,
    'tape:Worn thin': 0.3,
    'auto-filter:Phone line': 0.03,
    'auto-filter:Low-pass gate': 0.4,
    'shaped-reverb:Gated': 0.1,
    'shaped-reverb:Gate steps': 0.1,
  },
  recipes: {
    'motion-hall': 1.8,
    'motion-echo': 1.8,
    'motion-echo-hall': 1.6,
    'drive-motion': 1.3,
    'drive-motion-hall': 1.4,
    'pulse-echo': 1.3,
    'echo-hall': 1.5,
    'echo-room': 1.4,
    'drive-echo': 1.4,
    'drive-echo-hall': 1.5,
    'wear-echo': 1.5,
    'tone-wear-echo': 1.3,
    'motion-wear': 1.4,
    'hold-motion': 1.8,
    'hold-motion-hall': 1.8,
    'hold-hall': 1.4,
    'pitch-motion': 1.6,
    'pitch-echo': 1.3,
    'halo-hall': 1.3,
    'loop-hall': 0.4,
    'loop-room': 0.4,
    'tone-loop': 0.4,
    'loop-echo': 0.4,
    'loop-tone-hall': 0.4,
    'loop-wear': 0.4,
    'loop-wear-hall': 0.4,
    'wear-hiss': 0.6,
    'wear-hiss-hall': 0.6,
    'drive-hiss': 0.6,
    'grain-hall': 0.1,
    'grain-room': 0.1,
    'grain-echo': 0.1,
    'grain-wear': 0.1,
    'grain-tone': 0.1,
    'drive-grain': 0.05,
    'swell-grain-hall': 0.1,
    'pitch-grain': 0.1,
  },
  own: [
    {
      // The string ensemble's chain: a slow phaser or flanger across the chord, left in a plate or a spring.
      id: 'sequencer-phased-into-plate',
      category: 'motion',
      lead: 0,
      count: 5,
      slots: [
        { role: 'motion', devices: ['phaser', 'flanger'], not: ['strange'] },
        { role: 'hall', devices: ['plate-reverb', 'spring-reverb'], not: ['strange'] },
      ],
    },
    {
      // Each step of the sequence answered by tape heads, in a plate or a spring.
      id: 'sequencer-heads-answer',
      category: 'echo',
      lead: 0,
      count: 5,
      slots: [
        { role: 'echo', devices: ['tape-echo'] },
        { devices: ['plate-reverb', 'spring-reverb'], not: ['strange', 'heavy'] },
      ],
    },
    {
      // The sequence run hot into tape first, then the echo, then the tank.
      id: 'sequencer-hot-step-echo',
      category: 'echo',
      lead: 1,
      count: 4,
      slots: [
        {
          role: 'drive',
          devices: ['saturator', 'analog-drive', 'tape'],
          any: ['warm'],
          not: ['worn', 'strange'],
        },
        { role: 'echo', devices: ['tape-echo', 'analog-delay'], not: ['strange', 'unsteady'] },
        { devices: ['spring-reverb', 'plate-reverb'], not: ['strange', 'heavy'] },
      ],
    },
    {
      // A filter swept by hand over the running line, its repeats behind it.
      id: 'sequencer-swept-filter',
      category: 'motion',
      lead: 0,
      count: 4,
      slots: [
        { role: 'motion', devices: ['auto-filter'] },
        { role: 'echo', devices: ['tape-echo', 'analog-delay'], not: ['strange'] },
      ],
    },
    {
      // The tape-replay keyboard: a reel under every key, phased, in a long room.
      id: 'sequencer-replay-reel',
      category: 'tape',
      lead: 0,
      count: 5,
      slots: [
        { role: 'wear', devices: ['tape', 'patina'], not: ['strange', 'noisy', 'cold'] },
        { role: 'motion', devices: ['phaser', 'flanger', 'chorus'], not: ['strange'] },
        {
          role: 'hall',
          devices: ['plate-reverb', 'hall-reverb', 'spring-reverb'],
          not: ['strange'],
        },
      ],
    },
    {
      // The organ: stops drawn in octaves, then a rotor or a phaser turning.
      id: 'sequencer-organ-turning',
      category: 'pitch',
      lead: 0,
      count: 4,
      slots: [
        { role: 'pitch', devices: ['octaves'], not: ['strange'] },
        { role: 'motion', devices: ['rotary', 'phaser', 'flanger'], not: ['strange'] },
      ],
    },
  ],
  heads: [
    'Night-run',
    'Small-hours',
    'All-night',
    'Overnight',
    'Midnight',
    'Four-a-m',
    'First-light',
    'November',
    'Winter-night',
    'Snowbound',
    'Courtyard',
    'Back-room',
    'Coal-cellar',
    'Tenement',
    'Tower-block',
    'Rooftop',
    'Canal-side',
    'Wall-side',
    'Island-city',
    'Divided-city',
    'S-bahn',
    'Last-tram',
    'Wet-street',
    'Empty-street',
    'Sodium-lit',
    'Lamp-lit',
    'Dial-lit',
    'Scope-lit',
    'Half-lit',
    'Candlelit',
    'Control-room',
    'Rehearsal',
    'Late-session',
    'Patch-cord',
    'Patchbay',
    'Hand-patched',
    'Improvised',
    'Free-running',
    'Clock-driven',
    'Sixteen-step',
    'Eight-step',
    'Second-row',
    'Third-reel',
    'Flight-case',
    'Dry-ice',
    'Incense',
    'Chancel',
    'Transept',
    'Cloister',
    'Planetarium',
    'Black-knob',
    'Walnut',
    { word: 'Far-off', for: ['far'] },
    { word: 'Slow-turning', for: ['slow'] },
    { word: 'Side-long', for: ['long'] },
    { word: 'Underfloor', for: ['low'] },
    { word: 'Unshielded', for: ['noisy'] },
    { word: 'Untuned', for: ['unsteady'] },
    { word: 'Valve-warm', for: ['warm'] },
    { word: 'Shuttered', for: ['dark'] },
    { word: 'Frosted', for: ['cold'] },
    { word: 'Spooled-back', for: ['backwards'] },
    { word: 'Held-key', for: ['frozen'] },
  ],
  tails: [
    'past midnight',
    'before dawn',
    'near dawn',
    'all night',
    'till morning',
    'after hours',
    'on the hour',
    'by lamplight',
    'in dry ice',
    'in the yard',
    'in the rack',
    'by patch cord',
    'on row two',
    'on step eight',
    'over the city',
    'by the wall',
    'under sodium',
    'in november',
    'in the snow',
    'on the clock',
    { word: 'heard far off', for: ['far'] },
    { word: 'from below', for: ['low'] },
    { word: 'run backwards', for: ['backwards'] },
    { word: 'through hum', for: ['noisy'] },
    { word: 'out of tune', for: ['unsteady'] },
    { word: 'turning slow', for: ['slow'] },
    { word: 'left running', for: ['long'] },
  ],
}
