// Six Squared: short sad loops layered until they glow, pressed hard into
// saturation, compression and hiss and left in a long dark reverb with a
// filter that moves slowly. Its chains are drive, glue and hiss before
// anything else, then a loop and a dark hall; nothing is quick, thin or odd.

import { type PackPalette } from './types'

export const PALETTE: PackPalette = {
  pack: 'six-squared',
  groups: { space: 24, echo: 16, tape: 26, motion: 12, texture: 9, pitch: 5, master: 8 },
  traits: {
    dark: 1.9,
    warm: 1.8,
    long: 1.5,
    slow: 1.5,
    noisy: 1.3,
    wide: 1.2,
    far: 1.2,
    worn: 1.1,
    clean: 0.6,
    short: 0.5,
    narrow: 0.6,
    backwards: 0.6,
    unsteady: 0.7,
    bright: 0.4,
    cold: 0.4,
    high: 0.3,
    fast: 0.15,
    strange: 0.05,
  },
  devices: {
    saturator: 2.6,
    'analog-drive': 2,
    'ambient-comp': 1.6,
    'noise-floor': 2.6,
    'tape-loop': 2.2,
    'auto-filter': 2.4,
    'hall-reverb': 1.8,
    'fdn-reverb': 1.6,
    'plate-reverb': 1.5,
    'micro-looper': 1.5,
    chorus: 1.6,
    tape: 1.4,
    'ether-reverb': 1.3,
    expanse: 1.2,
    patina: 1.1,
    phaser: 1.1,
    sustainer: 1.1,
    'vintage-digital': 0.8,
    'half-speed': 0.45,
    'tape-echo': 0.8,
    'analog-delay': 0.8,
    'pad-follower': 0.8,
    'vowel-reverb': 0.6,
    'reverse-delay': 0.35,
    'grain-cloud': 0.35,
    'bloom-reverb': 0.5,
    flanger: 0.3,
    tremolo: 0.5,
    vinyl: 0.4,
    octaves: 0.8,
    'pitch-shifter': 0.6,
    'grain-delay': 0.25,
    'swarm-reverb': 0.2,
    rotary: 0.1,
    radio: 0.08,
    're-amp': 0.05,
    shimmer: 0.3,
    cascade: 0.3,
    'spectral-drifter': 0.3,
    'spring-reverb': 0.03,
    sympathetic: 0.05,
    'freq-shifter': 0.15,
    'low-bitrate': 0.2,
    lattice: 0.1,
    glitch: 0.1,
  },
  voices: {
    'auto-filter:Glacial low-pass': 2,
    'auto-filter:Dub sweep': 1.5,
    'hall-reverb:Warm undertow': 1.5,
    'fdn-reverb:Endless tail': 1.5,
    'ether-reverb:Dark infinite': 1.5,
    'chorus:Lush ensemble': 1.5,
    'noise-floor:Tape floor': 1.5,
    'ambient-comp:Pump': 0.1,
    'grain-delay:Falling fourths': 0.2,
    'grain-delay:Rising fifths': 0.2,
    'analog-delay:Octave hop': 0.3,
    'analog-delay:Fifth hop': 0.3,
    'shaped-reverb:Gated': 0.2,
    'shaped-reverb:Late wall': 0.2,
    'analog-delay:Slow lurch': 0,
    'swarm-reverb:Intervals': 0,
    'radio:Sour sideband': 0,
    'radio:Sideband voices': 0,
    'saturator:Fuzz pedal': 0.1,
    'auto-filter:Screaming': 0,
    'saturator:Blown speaker': 0,
    'analog-drive:Torn cone': 0,
    'patina:Valve fuzz': 0,
  },
  recipes: {
    'hall-glue': 2.5,
    'drive-hall': 2.2,
    'tone-hall': 1.3,
    'hall-tone': 1.3,
    'room-hall': 0.5,
    'halo-hall': 0.5,
    'room-halo': 0.4,
    'tone-halo': 0.5,
    'swell-halo': 0.5,
    'swell-halo-hall': 0.5,
    'drive-room': 0.6,
    'width-room': 0.4,
    'loop-hall': 2.2,
    'loop-tone-hall': 2,
    'tone-loop': 1.6,
    'drive-echo': 1.3,
    'drive-echo-hall': 1.5,
    'echo-echo': 0.4,
    'echo-halo': 0.5,
    'drive-hiss': 3,
    'wear-hiss': 1.8,
    'wear-hiss-hall': 2,
    'drive-wear': 1.6,
    'drive-tone': 1.5,
    'loop-wear': 1.8,
    'loop-wear-hall': 2,
    'wear-hall': 1.4,
    'motion-hall': 1.8,
    'drive-motion': 1.8,
    'drive-motion-hall': 2.2,
    'motion-tone': 1.2,
    'motion-halo': 0.5,
    'motion-motion': 0.5,
    'motion-room': 0.5,
    'pulse-echo': 0.2,
    'pulse-hall': 0.2,
    'pulse-room': 0.2,
    'tone-pulse': 0.2,
    'hold-hall': 1.6,
    'hold-wear': 1.4,
    'hold-tone': 1.3,
    'hold-motion': 1.4,
    'hold-motion-hall': 1.6,
    'grain-room': 0.5,
    'grain-echo': 0.6,
    'grain-tone': 0.6,
    'pitch-hall': 1.4,
    'pitch-wear': 1.4,
    'drive-pitch': 1.5,
    'pitch-echo-hall': 0.4,
    'pitch-grain': 0.4,
    'drive-glue-ceiling': 6,
    'wear-glue-ceiling': 3,
    'glue-width-ceiling': 0.4,
    'tone-glue-ceiling': 2,
    'drive-tone-ceiling': 1.5,
    'glue-ceiling': 1.5,
    'tone-ceiling': 0.6,
    'width-ceiling': 0.4,
    'tone-width-ceiling': 0.5,
  },
  own: [
    {
      // The pack in one chain: driven until it glows, pressed level, hiss underneath.
      id: 'six-squared-pressed-into-hiss',
      category: 'tape',
      lead: 0,
      count: 6,
      slots: [
        {
          role: 'drive',
          devices: ['saturator', 'analog-drive', 'tape', 'patina'],
          not: ['bright', 'cold', 'strange'],
        },
        { role: 'glue', devices: ['ambient-comp'] },
        { role: 'hiss', devices: ['noise-floor'] },
      ],
    },
    {
      // A short phrase going round, layer on layer, driven warm and left in a long dark hall.
      id: 'six-squared-loop-until-it-glows',
      category: 'echo',
      lead: 0,
      count: 6,
      slots: [
        {
          role: 'loop',
          devices: ['tape-loop', 'micro-looper', 'echo-memory'],
          not: ['bright', 'fast', 'strange', 'backwards'],
        },
        {
          role: 'drive',
          devices: ['saturator', 'analog-drive', 'tape', 'patina'],
          not: ['bright', 'cold', 'strange'],
        },
        { role: 'hall', any: ['dark', 'long', 'far'], not: ['high', 'strange'] },
      ],
    },
    {
      // Driven chords behind a filter that is shut or opens slowly, in a dark hall.
      id: 'six-squared-slow-filter',
      category: 'motion',
      lead: 1,
      count: 5,
      slots: [
        {
          role: 'drive',
          devices: ['saturator', 'analog-drive'],
          not: ['bright', 'cold', 'strange', 'heavy'],
        },
        { devices: ['auto-filter'], not: ['fast', 'bright', 'cold', 'strange'] },
        { role: 'hall', any: ['dark', 'long'], not: ['bright', 'cold', 'high', 'strange'] },
      ],
    },
    {
      // A big chorused synth, driven, over hiss, in a long dark hall.
      id: 'six-squared-chorus-over-hiss',
      category: 'motion',
      lead: 0,
      count: 4,
      slots: [
        { role: 'motion', devices: ['chorus'], not: ['strange', 'fast', 'worn'] },
        { role: 'drive', devices: ['saturator', 'analog-drive'], not: ['cold', 'strange'] },
        { role: 'hiss', devices: ['noise-floor'], not: ['heavy'] },
        { role: 'hall', any: ['dark', 'long'], not: ['bright', 'cold', 'high', 'heavy'] },
      ],
    },
    {
      // A chord sampled coarse and left going round on a loop, far off.
      id: 'six-squared-sampled-and-looped',
      category: 'tape',
      lead: 0,
      count: 4,
      slots: [
        { role: 'wear', devices: ['vintage-digital'], not: ['bright', 'strange'] },
        {
          role: 'loop',
          devices: ['tape-loop', 'micro-looper'],
          not: ['bright', 'fast', 'strange'],
        },
        { role: 'hall', any: ['dark', 'long', 'far'], not: ['high', 'strange'] },
      ],
    },
    {
      // The long dark reverb itself, fed warm and then pressed so its tail comes up.
      id: 'six-squared-hall-pressed',
      category: 'space',
      lead: 1,
      count: 5,
      slots: [
        {
          role: 'drive',
          devices: ['saturator', 'analog-drive', 'tape', 'patina'],
          not: ['bright', 'cold', 'strange', 'heavy'],
        },
        { role: 'hall', any: ['dark', 'long'], not: ['bright', 'cold', 'high', 'strange'] },
        { role: 'glue', devices: ['ambient-comp'] },
      ],
    },
  ],
  heads: [
    'Ring-road',
    'Estate',
    'Flyover',
    'Bypass',
    'Car-park',
    'Substation',
    'Warehouse',
    'Comedown',
    'Bus-shelter',
    'Motorway',
    'Top-deck',
    'Closing-time',
    'Lock-up',
    'Precinct',
    'Gasworks',
    'Viaduct',
    'Lay-by',
    'Slip-road',
    'Amber',
    'Sodium',
    'Milk-float',
    'First-bus',
    'Morning-after',
    'Back-seat',
    'Cooling-tower',
    'Bedsit',
    'Roundabout',
    'Outskirts',
    'Redbrick',
    'Old-flyer',
    'Cul-de-sac',
    'High-rise',
    'Ginnel',
    'Cobbled',
    'Multi-storey',
    'Windscreen',
    'Towpath',
    'Allotment',
    'Pebble-dash',
    'Bay-window',
    'Fog-lamp',
    'Dancefloor',
    'Forecourt',
    'Fire-exit',
    'Ticket-stub',
    'Convoy',
    'Depot',
    'Shopfront',
    'Rain-slick',
    'Hard-shoulder',
    'Net-curtain',
    'Paper-round',
    'Remembered',
    { word: 'Glowing', for: ['warm'] },
    { word: 'Left-on', for: ['noisy'] },
    { word: 'Power-cut', for: ['dark'] },
    { word: 'Steamed-up', for: ['dark', 'far'] },
    { word: 'Low-slung', for: ['low'] },
    { word: 'Rewound', for: ['backwards'] },
    { word: 'Night-long', for: ['long', 'frozen'] },
    { word: 'Idling', for: ['slow'] },
    { word: 'Photocopied', for: ['worn'] },
    { word: 'Flickering', for: ['unsteady'] },
    { word: 'Floodlit', for: ['bright'] },
  ],
  tails: [
    'at half four',
    'on the estate',
    'by the canal',
    'on wet tarmac',
    'before buses',
    'in lamplight',
    'walking home',
    'by the pylons',
    'over rooftops',
    'in a car park',
    'from a taxi',
    'from the bus',
    'out of town',
    'in a lock-up',
    'gone midnight',
    'under amber',
    'by the bypass',
    'at the depot',
    'in a ginnel',
    'in a lay-by',
    'in fine rain',
    'in sleet',
    'at a bus stop',
    { word: 'streets away', for: ['far'] },
    { word: 'in no light', for: ['dark'] },
    { word: 'never silent', for: ['noisy'] },
    { word: 'wound back', for: ['backwards'] },
    { word: 'till daylight', for: ['long', 'frozen'] },
  ],
  avoid: ['hollow', 'void', 'box', 'bloom', 'shadow', 'pulse', 'dust', 'waves', 'memories'],
}
