// Austin Slow Brass: horns, strings and guitars with the entry taken off
// every note, held on one chord and left to go out through a very large
// hall. Its chains are a fade-in, something that holds, and a long dark
// space; a little tape and the hum of an amplifier left on underneath;
// nothing is quick, bright or broken.

import { type PackPalette } from './types'

export const PALETTE: PackPalette = {
  pack: 'slow-brass',
  groups: { space: 28, echo: 8, tape: 12, motion: 7, texture: 27, pitch: 12, master: 6 },
  traits: {
    slow: 1.8,
    long: 1.6,
    dark: 1.6,
    warm: 1.5,
    far: 1.3,
    low: 1.2,
    wide: 1.1,
    unsteady: 0.7,
    narrow: 0.7,
    noisy: 0.6,
    worn: 0.4,
    short: 0.7,
    cold: 0.25,
    high: 0.15,
    bright: 0.15,
    strange: 0,
    fast: 0,
  },
  devices: {
    swell: 1.8,
    'hall-reverb': 3.2,
    expanse: 1.6,
    'fdn-reverb': 2,
    'plate-reverb': 2.4,
    'spectral-blur': 2.6,
    sustainer: 3,
    'pad-follower': 1.8,
    tape: 1.6,
    'half-speed': 1.5,
    'ether-reverb': 1.4,
    'ambient-eq': 1.3,
    'stereo-detune': 1.6,
    'analog-drive': 1.6,
    'shaped-reverb': 1,
    'ambient-comp': 1.2,
    're-amp': 0.9,
    'noise-floor': 0.8,
    'micro-looper': 0.8,
    'reverse-delay': 0.7,
    octaves: 0.7,
    'echo-memory': 0.7,
    saturator: 0.5,
    'swarm-reverb': 0.35,
    'vowel-reverb': 0.35,
    'bloom-reverb': 0.6,
    'grain-cloud': 0.6,
    chorus: 0.8,
    tremolo: 1,
    'tape-echo': 0.6,
    shimmer: 0.5,
    sympathetic: 0.35,
    'pitch-shifter': 0.5,
    'analog-delay': 0.2,
    'spectral-drifter': 0.4,
    patina: 0.4,
    'auto-filter': 0.4,
    'grain-delay': 0.3,
    'freq-shifter': 0.3,
    cascade: 0.3,
    lattice: 0.05,
    'spring-reverb': 0,
    rotary: 0,
    vinyl: 0,
    phaser: 0,
    flanger: 0,
    radio: 0,
    'low-bitrate': 0,
    'vintage-digital': 0,
    glitch: 0,
  },
  voices: {
    // A flanger in all but its device: weighed as this pack weighs flangers.
    'tremolo:Drifting comb': 0,
    'swell:Glacier': 1.6,
    'swell:Tide': 1.5,
    'swell:String section': 1.5,
    'hall-reverb:Cathedral': 1.5,
    'hall-reverb:Vast nave': 1.5,
    'expanse:Low cathedral': 1.4,
    'expanse:Wash alone': 0.6,
    'noise-floor:Amp left on': 2.5,
    'noise-floor:Mains hum': 2,
    'noise-floor:Empty room': 2,
    're-amp:Down the hall': 1.6,
    're-amp:Far end of the hall': 1.6,
    'auto-filter:Glacial low-pass': 2.5,
    'tape:Drifting chorus': 1.5,
    'grain-delay:Dark slow smear': 0.4,
    'analog-drive:Iron melt': 0.3,
    'analog-drive:Crushed': 0.3,
    're-amp:Stack flat out': 0.3,
    'fdn-reverb:Small bright tank': 0.3,
    'cascade:Slow staircase': 0.3,
    'expanse:Hard echoes': 0.3,
    'ambient-comp:Pluck tamer': 0.3,
    'chorus:Warped tape': 0.3,
    'sustainer:Shimmer cloud': 0.3,
    'vowel-reverb:High choir': 0.3,
    'sustainer:High frost': 0.2,
    'sustainer:Glass organ': 0.2,
    'auto-filter:Falling high-pass': 0.2,
    'auto-filter:Dub sweep': 0.2,
    'ambient-eq:Bright': 0.1,
    'shaped-reverb:Late wall': 0.1,
    'analog-drive:Dark fuzz': 0,
    'pitch-shifter:Broken choir': 0,
    'tape:Crumbling oxide': 0,
    'tape:Worn thin': 0,
    'tape-loop:Worn out': 0,
    'tape-echo:Worn tape': 0,
    'noise-floor:Old record': 0,
    'noise-floor:Gap crackle': 0,
    'auto-filter:Low-pass gate': 0,
    'auto-filter:Resonant peak': 0,
    'auto-filter:Phone line': 0,
    'shaped-reverb:Gated': 0,
    'tape-echo:Dotted bounce': 0,
    'tape-echo:Two head gallop': 0,
    'tape-echo:Three heads': 0,
    'freq-shifter:Moving beat': 0,
    'freq-shifter:Barber pole': 0,
    'sympathetic:Brief pluck': 0,
    'sympathetic:Hammered': 0,
    'sympathetic:Glass harp': 0,
    'ambient-comp:Dense pad': 0,
    'shimmer:Endless ascent': 0,
    'shimmer:Rising choir': 0,
    'shimmer:Rising tail alone': 0,
    'micro-looper:Sampler grit': 0,
    'micro-looper:Lo-fi quarter': 0,
    'patina:Worn cassette': 0,
    'tape:Old dictation': 0,
    'stereo-widener:Narrow': 0,
    'bloom-reverb:Quick sparkle': 0,
    'saturator:Parallel shine': 0,
    'saturator:Drum bus crunch': 0,
    'reverse-delay:Hard splices': 0,
    'vowel-reverb:High ee': 0,
    'stereo-widener:Mono': 0,
    'ambient-limiter:Pinned': 0,
    'shimmer:Sparkle room': 0,
    'swarm-reverb:Metal pipe': 0,
    'swarm-reverb:Glass rain': 0,
    'analog-delay:Octave hop': 0,
    'analog-delay:Fifth hop': 0,
    'saturator:Lo-fi': 0,
    'patina:Muffled sampler': 0,
    'patina:Early sampler': 0,
    'patina:Eight bit': 0,
    'patina:Kitchen radio': 0,
    'patina:Shortwave': 0,
    'patina:Distant station': 0,
    'patina:Dusty record': 0,
    'patina:Scratched record': 0,
    're-amp:Bedside radio': 0,
    're-amp:Station platform': 0,
    'ambient-comp:Pump': 0,
    'fet-limiter:Flattened': 0,
    'fet-limiter:Squash': 0,
  },
  recipes: {
    'swell-hall': 2,
    'tone-hall': 1.5,
    'width-hall': 1.4,
    'room-hall': 1.3,
    'hall-tone': 1.3,
    'swell-halo-hall': 1.2,
    'halo-hall': 0.4,
    'swell-halo': 0.5,
    'room-halo': 0.1,
    'tone-halo': 0.25,
    'drive-room': 0.15,
    'width-room': 0.15,
    'loop-hall': 2,
    'loop-tone-hall': 1.6,
    'swell-echo': 1.5,
    'tone-loop': 1.3,
    'echo-hall': 1.2,
    'echo-echo': 0.2,
    'echo-room': 0.08,
    'drive-echo': 0.5,
    'motion-echo': 0.5,
    'echo-halo': 0.5,
    'wear-hall': 2,
    'loop-wear-hall': 1.4,
    'wear-hiss-hall': 1.4,
    'tone-wear': 1.2,
    'wear-echo': 0.5,
    'motion-wear': 0.6,
    'motion-hall': 2,
    'swell-motion': 1.6,
    'pulse-echo': 0,
    'pulse-hall': 0,
    'pulse-room': 0,
    'tone-pulse': 0,
    'motion-motion': 0.4,
    'motion-room': 0.4,
    'motion-halo': 0.3,
    'drive-motion': 0.3,
    'hold-hall': 2.2,
    'swell-hold': 1.6,
    'swell-grain-hall': 1.6,
    'grain-hall': 1.4,
    'hold-tone': 1.2,
    'hold-wear': 0.8,
    'hold-halo': 0.4,
    'grain-echo': 0.2,
    'grain-room': 0.5,
    'grain-wear': 0.4,
    'drive-grain': 0.6,
    'pitch-hall': 2,
    'swell-pitch-hall': 2,
    'swell-pitch': 1.5,
    'pitch-hold': 1.3,
    'pitch-echo': 0.2,
    'pitch-echo-hall': 0.4,
    'pitch-grain': 0.5,
    'pitch-halo': 0.5,
    'pitch-motion': 0.6,
    'pitch-room': 0.6,
  },
  own: [
    {
      // The pack in one chain: the entry faded off every note, the top shaded, and out through a very large hall.
      id: 'slow-brass-no-entry-long-hall',
      category: 'space',
      lead: 2,
      count: 6,
      slots: [
        { role: 'swell', devices: ['swell'], not: ['fast'] },
        { role: 'tone', devices: ['ambient-eq', 'auto-filter'], any: ['dark'] },
        {
          role: 'hall',
          devices: ['hall-reverb', 'expanse', 'fdn-reverb', 'plate-reverb', 'ether-reverb'],
          any: ['long', 'dark', 'far'],
          not: ['bright', 'cold', 'unsteady'],
        },
      ],
    },
    {
      // A note that fades in, is caught and held as a bed, and leaves through a hall.
      id: 'slow-brass-faded-in-and-held',
      category: 'texture',
      lead: 1,
      count: 6,
      slots: [
        { role: 'swell', not: ['fast', 'backwards', 'heavy'] },
        {
          role: 'hold',
          devices: ['sustainer', 'pad-follower', 'spectral-blur'],
          not: ['bright', 'cold', 'fast', 'high', 'unsteady'],
        },
        { role: 'hall', any: ['long', 'dark', 'far'], not: ['bright', 'cold', 'strange'] },
      ],
    },
    {
      // Two guitars through an amplifier, printed to tape, heard from the other end of the building.
      id: 'slow-brass-amplifier-to-tape',
      category: 'tape',
      lead: 1,
      count: 5,
      slots: [
        {
          role: 'drive',
          devices: ['re-amp', 'analog-drive', 'saturator', 'patina'],
          any: ['warm', 'dark'],
          not: ['strange', 'bright', 'worn'],
        },
        {
          role: 'wear',
          devices: ['tape', 'patina'],
          any: ['warm', 'dark', 'faint'],
          not: ['strange', 'cold', 'bright'],
        },
        {
          role: 'hall',
          devices: [
            'hall-reverb',
            'plate-reverb',
            'fdn-reverb',
            'expanse',
            'ether-reverb',
            'shaped-reverb',
          ],
          any: ['long', 'dark', 'far'],
          not: ['bright', 'cold', 'strange', 'unsteady'],
        },
      ],
    },
    {
      // The hum of an amplifier left on, under whatever is held, in a big room.
      id: 'slow-brass-hum-left-on',
      category: 'tape',
      lead: 1,
      count: 4,
      slots: [
        { role: 'hold', not: ['bright', 'cold', 'fast', 'high', 'strange', 'heavy'] },
        {
          role: 'hiss',
          presets: [
            'noise-floor:Amp left on',
            'noise-floor:Mains hum',
            'noise-floor:Empty room',
            'noise-floor:Distant rumble',
            'noise-floor:Close mic',
            'noise-floor:Faint hiss',
            'noise-floor:Muffled hiss',
            're-amp:Noisy valves',
          ],
        },
        {
          role: 'hall',
          devices: [
            'hall-reverb',
            'plate-reverb',
            'fdn-reverb',
            'expanse',
            'ether-reverb',
            'shaped-reverb',
          ],
          any: ['long', 'dark', 'far'],
          not: ['bright', 'cold', 'strange', 'heavy', 'unsteady'],
        },
      ],
    },
    {
      // The section an octave under itself, with no entry, in the hall.
      id: 'slow-brass-section-below',
      category: 'pitch',
      lead: 1,
      count: 5,
      slots: [
        { role: 'swell', not: ['fast', 'backwards', 'heavy', 'high'] },
        { role: 'pitch', want: ['low'], not: ['high', 'strange', 'fast', 'backwards', 'worn'] },
        { role: 'hall', any: ['long', 'dark', 'far'], not: ['bright', 'cold', 'strange', 'heavy'] },
      ],
    },
  ],
  heads: [
    'Stage-door',
    'Back-row',
    'Foyer',
    'Night-ward',
    'Next-room',
    'Screen-door',
    'August',
    'After-hours',
    'Lights-off',
    'Empty-house',
    'Rehearsal',
    'Two-guitar',
    'Patient',
    'One-chord',
    'Hot-night',
    'Hill-country',
    'Limestone',
    'Cedar',
    'Heat-haze',
    'Dog-days',
    'Thunderhead',
    'Creek-bed',
    'Balcony',
    'Velvet',
    'Rosin',
    'Half-asleep',
    'Small-hours',
    'Backstage',
    'Cloakroom',
    'Green-room',
    'Fire-door',
    'Exit-sign',
    'House-lights',
    'Second-desk',
    'Waiting-room',
    'Sleepless',
    'Drowsy',
    'Water-tower',
    'County-road',
    'Proscenium',
    'Upper-circle',
    'Night-shift',
    'Floorboard',
    'Vestry',
    'Borrowed',
    { word: 'Unhurried', for: ['slow'] },
    { word: 'Largo', for: ['slow'] },
    { word: 'Fermata', for: ['long', 'frozen'] },
    { word: 'Slow-leaving', for: ['long'] },
    { word: 'Unlit', for: ['dark'] },
    { word: 'Muted', for: ['dark'] },
    { word: 'Far-end', for: ['far'] },
    { word: 'Bass-clef', for: ['low'] },
    { word: 'End-first', for: ['backwards'] },
    { word: 'Left-on', for: ['noisy'] },
    { word: 'Lamp-warm', for: ['warm'] },
    { word: 'Unsettled', for: ['unsteady'] },
  ],
  tails: [
    'at the door',
    'in the pit',
    'at the back',
    'after closing',
    'on the porch',
    'before rain',
    'in the eaves',
    'nodding off',
    'on the ward',
    'for two',
    'all evening',
    'till morning',
    'past midnight',
    'in the wings',
    'by the exit',
    'between sets',
    'in still air',
    'by lamplight',
    'in the heat',
    { word: 'in no hurry', for: ['slow', 'long'] },
    { word: 'from the end', for: ['backwards'] },
    { word: 'from below', for: ['low'] },
    { word: 'two rooms off', for: ['far'] },
    { word: 'left running', for: ['noisy', 'frozen'] },
    { word: 'held over', for: ['long', 'frozen'] },
  ],
  avoid: ['oxide', 'dust', 'lid'],
}
