// Soft Pedal: a piano with the soft pedal down, a copy a few cents sharp on
// one side and flat on the other, left to hang in a room that takes most of
// a minute to empty. Its chains are a detuned double and a very long dark
// room before anything else; a slow chorus, a swell that takes the hammers
// away, dull repeats; no grit, no wear to speak of, nothing quick or bright.

import { type PackPalette } from './types'

// The rooms the pack is heard in: plain halls and plates, nothing that chirps, sings or splashes.
const ROOMS = [
  'hall-reverb',
  'expanse',
  'fdn-reverb',
  'plate-reverb',
  'ether-reverb',
  'bloom-reverb',
] as const

export const PALETTE: PackPalette = {
  pack: 'soft-pedal',
  groups: { space: 38, echo: 12, tape: 6, motion: 14, texture: 14, pitch: 9, master: 7 },
  traits: {
    dark: 1.4,
    long: 1.4,
    slow: 1.3,
    wide: 1.2,
    warm: 1.2,
    far: 1.2,
    clean: 1.1,
    heavy: 0.7,
    unsteady: 0.7,
    high: 0.6,
    backwards: 0.6,
    frozen: 0.6,
    short: 0.5,
    narrow: 0.3,
    cold: 0.3,
    bright: 0.15,
    noisy: 0.2,
    worn: 0.1,
    fast: 0.05,
    strange: 0,
  },
  devices: {
    'hall-reverb': 3.5,
    'stereo-detune': 2.4,
    expanse: 2,
    chorus: 1.7,
    'fdn-reverb': 1.7,
    'plate-reverb': 1.6,
    sympathetic: 1.4,
    'bloom-reverb': 1.3,
    'tape-echo': 1.3,
    'ambient-limiter': 1.3,
    swell: 1.2,
    'ether-reverb': 1.2,
    'ambient-comp': 1.2,
    'spectral-blur': 1.1,
    sustainer: 1.1,
    'half-speed': 0.8,
    shimmer: 0.8,
    'echo-memory': 0.8,
    'ambient-eq': 0.7,
    phaser: 0.55,
    rotary: 0.7,
    tremolo: 0.6,
    'stereo-widener': 0.6,
    octaves: 0.6,
    'pitch-shifter': 0.6,
    'grain-cloud': 0.5,
    'micro-looper': 0.5,
    saturator: 0.5,
    'auto-filter': 0.4,
    'reverse-delay': 0.4,
    'spectral-drifter': 0.4,
    patina: 0.4,
    'grain-delay': 0.35,
    'vowel-reverb': 0.25,
    'freq-shifter': 0.15,
    'tape-loop': 0.3,
    'noise-floor': 0.3,
    'fet-limiter': 0.25,
    'analog-drive': 0.15,
    'swarm-reverb': 0.1,
    cascade: 0.05,
    // No amplifier, no record, no sampler, no spring, no harmoniser, nothing broken.
    're-amp': 0,
    vinyl: 0,
    'vintage-digital': 0,
    'spring-reverb': 0,
    lattice: 0,
    glitch: 0,
    flanger: 0,
    'low-bitrate': 0,
    radio: 0,
  },
  voices: {
    // The pack's own: the detuned double in each of its forms, the long dark room, the strings that ring on under the pedal.
    'stereo-detune:Piano haze': 1.4,
    'stereo-detune:Classic': 1.3,
    'freq-shifter:Detuned': 8,
    'pitch-shifter:Doubler': 2.5,
    'hall-reverb:Cathedral': 1.3,
    'expanse:Open space': 1.5,
    'bloom-reverb:Long dark': 1.5,
    'sympathetic:Piano pedal': 2,
    'half-speed:Under the mix': 1.5,
    // Echoes and loops that jump in pitch, or are a sampler's.
    'analog-delay:Octave hop': 0,
    'analog-delay:Fifth hop': 0,
    'pitch-shifter:Falling steps': 0.1,
    'pitch-shifter:Rising steps': 0.1,
    'grain-delay:Falling embers': 0,
    'micro-looper:Lo-fi quarter': 0,
    'micro-looper:Sampler grit': 0,
    'micro-looper:Octave up': 0.1,
    'patina:Muffled sampler': 0,
    'tape-echo:Two head gallop': 0.3,
    'octaves:Organ': 0.15,
    'octaves:Cathedral': 0.1,
    'reverse-delay:Descending steps': 0.2,
    // Anything driven hard.
    'tape:Needles pinned': 0,
    'tape:Hot glue': 0.2,
    'saturator:Sustain bed': 0,
    'analog-drive:Dark fuzz': 0,
    'patina:Hot valve': 0,
    'patina:Reel pushed hard': 0,
    'rotary:Slow burn': 0,
    'rotary:Parked growl': 0,
    'rotary:Stopped horn': 0.2,
    // Movement that chops, snaps back or lurches.
    'half-speed:Slow chops': 0,
    'phaser:Two-tone flip': 0.2,
    'phaser:Saw riser': 0.1,
    'phaser:Endless fall': 0.3,
    'auto-filter:Falling high-pass': 0.1,
    'auto-filter:Dub sweep': 0,
    'tremolo:Wandering pan': 0.3,
    // Rooms that are gated, bright, boxy or thin.
    'shaped-reverb:Late wall': 0,
    'shaped-reverb:Gated': 0,
    'hall-reverb:Bright hall': 0,
    'hall-reverb:Airy tail': 0.3,
    'fdn-reverb:Bright air': 0,
    'fdn-reverb:Small bright tank': 0.1,
    'fdn-reverb:Dark cave': 0.6,
    'expanse:Narrow tunnel': 0.3,
    'bloom-reverb:Quick sparkle': 0.1,
    'ambient-eq:Thin': 0.3,
    'ambient-eq:Hollow': 0.3,
    'ambient-eq:Bright': 0,
    'ether-reverb:Shining tail': 0.3,
    // Tails that climb, repeats that bounce or patter.
    'bloom-reverb:Endless rise': 0,
    'bloom-reverb:Octave halo': 0.5,
    'bloom-reverb:Rising fifths': 0.5,
    'pad-follower:High mist': 0.5,
    'tape-echo:Dotted bounce': 0.2,
    'swarm-reverb:Pattering': 0,
    'echo-memory:Side to side': 0.3,
    'reverse-delay:Hard splices': 0,
    'shaped-reverb:Reverse': 0.2,
    'ether-reverb:Small booth': 0.3,
    'ether-reverb:Bright chamber': 0,
    'expanse:Bright chamber': 0,
    'plate-reverb:Bright plate': 0,
    'sympathetic:Sitar drone': 0,
    'freq-shifter:Barber pole': 0,
    'chorus:Warped tape': 0.3,
    'octaves:Bass alone': 0.2,
    'saturator:Bass grit': 0,
    'auto-filter:Low-pass gate': 0.4,
    // A wide, quiet pack is not folded to the middle, pumped or pressed flat.
    'stereo-widener:Mono': 0,
    'stereo-widener:Narrow': 0,
    'ambient-comp:Pump': 0,
    'ambient-comp:Dense pad': 0.2,
    'ambient-limiter:Pinned': 0,
    'fet-limiter:Drive': 0.2,
    'fet-limiter:Squash': 0,
    'fet-limiter:Flattened': 0,
  },
  recipes: {
    // Space.
    'hall-width': 1.5,
    'halo-hall': 1.4,
    'width-hall': 1.3,
    'swell-hall': 1.1,
    'tone-hall': 0.8,
    'room-hall': 0.8,
    'swell-halo-hall': 0.8,
    'hall-tone': 0.6,
    'tone-halo': 0.5,
    'tone-room-hall': 0.5,
    'swell-halo': 0.5,
    'width-room': 0.4,
    'drive-hall': 0,
    'drive-room': 0,
    // Echo.
    'echo-hall': 1.8,
    'echo-width': 1.3,
    'echo-halo': 1.2,
    'motion-echo': 1.2,
    'swell-echo': 0.8,
    'loop-tone-hall': 0.6,
    'echo-tone': 0.5,
    'echo-echo': 0.4,
    'loop-room': 0.4,
    'loop-echo': 0.4,
    'tone-loop': 0.4,
    'drive-echo': 0,
    'drive-echo-hall': 0,
    // Tape.
    'wear-hall': 1.5,
    'tone-wear': 1.2,
    'motion-wear': 1.2,
    'loop-wear': 0.4,
    'loop-wear-hall': 0.4,
    'drive-tone': 0,
    'drive-wear': 0,
    'wear-hiss-hall': 0.2,
    'wear-hiss': 0.15,
    'drive-wear-room': 0,
    'drive-hiss': 0,
    // Motion.
    'motion-hall': 2,
    'width-motion': 1.5,
    'motion-halo': 1.2,
    'motion-echo-hall': 1.2,
    'swell-motion': 0.9,
    'motion-tone': 0.4,
    'pulse-hall': 0,
    'pulse-echo': 0,
    'pulse-room': 0,
    'tone-pulse': 0,
    'drive-motion': 0,
    'drive-motion-hall': 0,
    // Texture.
    'hold-hall': 1.6,
    'hold-halo': 1.2,
    'swell-width': 1,
    'swell-hold': 1,
    'swell-grain-hall': 0.8,
    'swell-room': 0.6,
    'grain-echo': 0.6,
    'grain-tone': 0.4,
    'hold-tone': 0.4,
    'hold-wear': 0.4,
    'grain-wear': 0.3,
    'drive-grain': 0,
    // Pitch.
    'pitch-hall': 1.8,
    'pitch-width': 1.3,
    'swell-pitch-hall': 1,
    'swell-pitch': 0.6,
    'pitch-grain': 0.4,
    'pitch-room': 0.4,
    'pitch-tone': 0.4,
    'pitch-wear': 0.3,
    'drive-pitch': 0,
    // Master.
    'tone-ceiling': 1.2,
    'tone-glue-ceiling': 1.2,
    'width-ceiling': 0.8,
    'tone-width-ceiling': 0.8,
    'glue-width-ceiling': 0.7,
    'wear-ceiling': 0.4,
    'wear-glue-ceiling': 0.4,
    'drive-ceiling': 0.3,
    'drive-tone-ceiling': 0.3,
    'drive-glue-ceiling': 0.3,
  },
  own: [
    {
      // The pack in one chain: a copy a few cents sharp on one side and flat on the other, then the very long room.
      id: 'soft-pedal-few-cents-long-room',
      category: 'space',
      lead: 1,
      count: 7,
      slots: [
        {
          role: 'width',
          devices: ['stereo-detune', 'pitch-shifter', 'freq-shifter'],
          not: ['worn', 'unsteady'],
        },
        { role: 'hall', devices: ROOMS, not: ['bright', 'narrow', 'cold', 'faint'] },
      ],
    },
    {
      // The other way round: the room first, and then the whole room tipped a few cents out of tune.
      id: 'soft-pedal-room-tipped',
      category: 'space',
      lead: 0,
      count: 4,
      slots: [
        {
          role: 'hall',
          devices: [...ROOMS, 'shaped-reverb'],
          not: ['bright', 'narrow', 'cold', 'heavy'],
        },
        { role: 'width', devices: ['stereo-detune', 'chorus'], not: ['worn'] },
      ],
    },
    {
      // The piano without hammers: the strike faded out of every note, the after-ring doubled and left in the room.
      id: 'soft-pedal-no-hammers',
      category: 'texture',
      lead: 0,
      count: 5,
      slots: [
        { role: 'swell', devices: ['swell'], not: ['fast'] },
        {
          role: 'width',
          devices: ['stereo-detune', 'pitch-shifter', 'freq-shifter'],
          not: ['worn', 'unsteady'],
        },
        {
          role: 'hall',
          devices: [...ROOMS, 'shaped-reverb'],
          not: ['bright', 'narrow', 'cold', 'faint'],
        },
      ],
    },
    {
      // Lid nearly closed: the top rolled off, a chorus or a phaser that takes seconds to turn, a long room.
      id: 'soft-pedal-lid-down-chorus',
      category: 'motion',
      lead: 1,
      count: 5,
      slots: [
        { role: 'tone', devices: ['ambient-eq', 'auto-filter'], want: ['dark'] },
        {
          role: 'motion',
          devices: ['chorus', 'phaser', 'rotary', 'tremolo'],
          any: ['slow', 'faint', 'wide'],
          not: ['fast', 'cold'],
        },
        { role: 'hall', devices: [...ROOMS, 'shaped-reverb'], not: ['bright', 'narrow', 'cold'] },
      ],
    },
    {
      // A few slow dull repeats that blur into the dark room behind them.
      id: 'soft-pedal-dull-repeats',
      category: 'echo',
      lead: 0,
      count: 4,
      slots: [
        {
          role: 'echo',
          devices: ['tape-echo', 'analog-delay', 'echo-memory'],
          any: ['dark', 'warm', 'faint'],
          not: ['fast', 'bright', 'worn'],
        },
        { role: 'hall', devices: ROOMS, not: ['bright', 'narrow', 'cold', 'faint'] },
      ],
    },
    {
      // The keys and their room recorded together to slow tape, so the room wavers along with the notes.
      id: 'soft-pedal-room-on-slow-tape',
      category: 'tape',
      lead: 1,
      count: 3,
      slots: [
        {
          role: 'hall',
          devices: ['plate-reverb', 'hall-reverb', 'fdn-reverb', 'expanse'],
          not: ['bright', 'heavy', 'narrow', 'cold'],
        },
        { role: 'wear', devices: ['tape', 'patina'], not: ['noisy', 'narrow', 'cold', 'fast'] },
      ],
    },
  ],
  heads: [
    'Dusk',
    'Evening',
    'Twilit',
    'Lamplit',
    'Unlit',
    'After-hours',
    'Back-row',
    'Balcony',
    'Alcove',
    'Foyer',
    'Doorway',
    'Stage-door',
    'Recital',
    'Rehearsal',
    'Salon',
    'Upright',
    'Treated',
    'Draped',
    'Shuttered',
    'Panelled',
    'Parquet',
    'Plaster',
    'Walnut',
    'Spruce',
    'Ebony',
    'Draughty',
    'Overcast',
    'Half-stick',
    'Overstrung',
    'Stove-side',
    'Rained-in',
    'Empty-stage',
    'Stacked-chair',
    'Lid-down',
    'Pedal-down',
    'Upstairs',
    'Midweek',
    'Fermata',
    'Brushed',
    'Aisle',
    'Rafter',
    'Floorboard',
    'Annexe',
    'Vestibule',
    { word: 'Felted', for: ['dark'] },
    { word: 'Pianissimo', for: ['faint'] },
    { word: 'Lento', for: ['slow'] },
    { word: 'Undamped', for: ['long'] },
    { word: 'Never-damped', for: ['frozen'] },
    { word: 'Offstage', for: ['far'] },
    { word: 'Detuned', for: ['unsteady'] },
    { word: 'Wall-to-wall', for: ['wide'] },
    { word: 'Retrograde', for: ['backwards'] },
    { word: 'Left-hand', for: ['low'] },
    { word: 'Right-hand', for: ['high'] },
    { word: 'Left-on', for: ['noisy'] },
  ],
  tails: [
    'at dusk',
    'under the lid',
    'on soft pedal',
    'after hours',
    'by one lamp',
    'by the stove',
    'as it rains',
    'past the door',
    'in the stalls',
    'at half stick',
    'under drapes',
    'on parquet',
    'one floor up',
    'on a weekday',
    'in a draught',
    'at closing',
    'to empty rows',
    { word: 'from the back', for: ['far'] },
    { word: 'in felt', for: ['dark'] },
    { word: 'half heard', for: ['faint'] },
    { word: 'on the quiet', for: ['faint'] },
    { word: 'few and slow', for: ['slow'] },
    { word: 'left to hang', for: ['long'] },
    { word: 'slow to empty', for: ['long'] },
    { word: 'a shade flat', for: ['unsteady'] },
    { word: 'either side', for: ['wide'] },
    { word: 'in the bass', for: ['low'] },
    { word: 'back to front', for: ['backwards'] },
  ],
  // Nouns that in this pack would sit too close to a title.
  avoid: [
    'mirror',
    'crystals',
    'sky',
    'memories',
    'mist',
    'stairs',
    'drift',
    'ball',
    'glances',
    'stream',
    'night',
    'pulse',
    'breath',
    'shadow',
    'ice',
    'harmony',
    'return',
    'returns',
  ],
}
