// Sonoran Night Air: analogue pads that breathe as slowly as a sleeper, over
// the desert after dark. Its chains are the largest halls there are, and what
// stands in front of them moves over seconds: a filter that opens and shuts,
// an ensemble, a slow phaser, an analogue echo that fills the gaps of a
// pattern. Deep, wide and without an edge; nothing is quick, broken or worn.

import { type PackPalette } from './types'

export const PALETTE: PackPalette = {
  pack: 'sonoran',
  groups: { space: 30, echo: 17, tape: 5, motion: 18, texture: 15, pitch: 9, master: 6 },
  traits: {
    long: 1.7,
    slow: 1.7,
    wide: 1.4,
    warm: 1.5,
    low: 1.4,
    far: 1.4,
    dark: 1.3,
    heavy: 0.8,
    faint: 0.7,
    high: 0.6,
    unsteady: 0.6,
    backwards: 0.6,
    bright: 0.4,
    cold: 0.3,
    short: 0.3,
    noisy: 0.25,
    narrow: 0.15,
    worn: 0.15,
    fast: 0.1,
    strange: 0.1,
  },
  devices: {
    expanse: 3.5,
    'analog-delay': 4,
    'hall-reverb': 3,
    chorus: 2.2,
    'fdn-reverb': 2,
    phaser: 2,
    'auto-filter': 2,
    swell: 1.2,
    'half-speed': 1.6,
    'ether-reverb': 1.5,
    sustainer: 1.5,
    'plate-reverb': 1.4,
    'shaped-reverb': 1,
    tape: 1.5,
    'pad-follower': 1.3,
    'spectral-blur': 1.3,
    'vowel-reverb': 1.2,
    'swarm-reverb': 1.2,
    'tape-echo': 1,
    flanger: 0.9,
    'ambient-eq': 0.8,
    patina: 0.8,
    'bloom-reverb': 0.8,
    'grain-cloud': 0.8,
    rotary: 0.5,
    saturator: 0.6,
    'micro-looper': 0.6,
    'tape-loop': 0.6,
    'pitch-shifter': 0.6,
    sympathetic: 0.35,
    'grain-delay': 0.5,
    'reverse-delay': 0.2,
    'spectral-drifter': 0.5,
    'noise-floor': 0.4,
    'freq-shifter': 0.1,
    cascade: 0.3,
    'spring-reverb': 0.05,
    lattice: 0.15,
    'vintage-digital': 0.05,
    're-amp': 0,
    glitch: 0,
    'low-bitrate': 0,
    vinyl: 0,
    radio: 0,
  },
  voices: {
    'expanse:Open space': 2,
    'expanse:Low cathedral': 0.6,
    'expanse:Bloom': 0.8,
    'expanse:Event horizon': 0.8,
    'fdn-reverb:Breathing': 1.5,
    'fdn-reverb:Open valley': 1.5,
    'hall-reverb:Vast nave': 1.5,
    'hall-reverb:Cathedral': 1.5,
    'shaped-reverb:Breathing': 1.5,
    'auto-filter:Glacial low-pass': 3,
    'auto-filter:Dub sweep': 1.5,
    'tremolo:Gentle breath': 2.5,
    'tremolo:Sea swell': 1.5,
    'chorus:Slow drift': 2,
    'chorus:Lush ensemble': 2,
    'phaser:Slow swirl': 2,
    'phaser:Glacial sweep': 2,
    'analog-delay:Dark echo': 1.3,
    'analog-delay:Clean echo': 1.3,
    'tape:Mastering deck': 1.5,
    'tape:Quarter inch': 2,
    'patina:Quarter inch reel': 2,
    'patina:New tape': 2,
    'swell:Glacier': 0.6,
    'noise-floor:Distant rumble': 2,
    'noise-floor:Close mic': 2,
    'auto-filter:Squelch': 0,
    'auto-filter:Stepped': 0,
    'auto-filter:Screaming': 0,
    'tremolo:Chopper': 0,
    'tremolo:On and off': 0,
    'flanger:Stepped random': 0,
    'phaser:Random steps': 0,
    'analog-delay:Slow lurch': 0.05,
    'auto-filter:Touch wah': 0.1,
    'auto-filter:Resonant peak': 0.05,
    'expanse:Wash alone': 0.5,
    'fdn-reverb:Small bright tank': 0.1,
    'tape:Seasick': 0.2,
    'rotary:Stopped horn': 0.2,
    'swarm-reverb:Metal pipe': 0.2,
    'reverse-delay:Hard splices': 0.2,
    'analog-drive:Dark fuzz': 0,
    'analog-drive:Torn cone': 0,
    'analog-drive:Crushed': 0,
    'saturator:Fuzz pedal': 0,
    'saturator:Wavefold lead': 0,
    'saturator:Blown speaker': 0,
    'patina:Valve fuzz': 0,
    'patina:Early sampler': 0,
    'patina:Eight bit': 0,
    'auto-filter:Phone line': 0,
    'analog-drive:Iron melt': 0.4,
    'ambient-comp:Dense pad': 0.1,
    'ambient-comp:Pump': 0.1,
    'fet-limiter:Squash': 0,
    'fet-limiter:Flattened': 0,
    'analog-delay:Fluttering': 0.05,
    'analog-delay:Seasick': 0.05,
    'analog-delay:Slapback': 0.2,
    'analog-delay:Noisy clock': 0.4,
    'analog-delay:Murky': 0.6,
    'tremolo:Pitch wobble': 0.3,
    'tape-loop:Worn out': 0.2,
    'tape:Needles pinned': 0,
    'tremolo:Harmonic shimmer': 0.3,
    'flanger:Tremolo saw': 0.2,
    'flanger:Classic jet': 0,
    'patina:Reel pushed hard': 0.05,
    'ambient-limiter:Pinned': 0.3,
    'ambient-limiter:Slow tide': 2,
    'ambient-limiter:Late night': 1.5,
    'noise-floor:Radio static': 0.1,
    'noise-floor:Static notes': 0.1,
    'noise-floor:Old record': 0.1,
    'noise-floor:Gap crackle': 0.1,
    'patina:Muffled sampler': 0.05,
    'tape:Flutter shimmer': 0.3,
    'saturator:Drum bus crunch': 0.05,
    'stereo-widener:Narrow': 0,
    'stereo-widener:Mono': 0,
    'analog-delay:Octave hop': 0.5,
    'analog-delay:Fifth hop': 0.5,
    'plate-reverb:Bright plate': 0.25,
    'rotary:Mono cabinet': 0.3,
    'freq-shifter:Seasick': 0.2,
    'ambient-eq:Bright': 0.3,
    'ambient-eq:Thin': 0,
    'ambient-eq:Hollow': 0.5,
    'shaped-reverb:Late wall': 0.3,
    'shaped-reverb:Gated': 0.2,
    'half-speed:Slow chops': 0.5,
    'fdn-reverb:Full wet send': 0.5,
    'hall-reverb:Full wet send': 0.5,
    'plate-reverb:Full wet send': 0.5,
    'ether-reverb:Shining tail': 0.4,
    'ether-reverb:Cathedral': 0.4,
    'auto-filter:Falling high-pass': 0.4,
    'tape-echo:Two head gallop': 0,
    'tape-echo:Single slap': 0.2,
    'tape:Hot glue': 0.3,
    'analog-drive:Bite': 0.2,
    'chorus:Warped tape': 0.2,
    'swarm-reverb:Pattering': 0.3,
    'ether-reverb:Bright chamber': 0.3,
    'analog-delay:Falling tape': 0.1,
    'shaped-reverb:Scattered': 0.4,
    'expanse:Hard echoes': 0.05,
    'bloom-reverb:Narrow cellar': 0,
    'expanse:Narrow tunnel': 0.1,
    'expanse:Fast flutter': 0.2,
    'expanse:Thin air': 0.4,
    'expanse:Small box': 0.1,
    'expanse:Bright chamber': 0.5,
    'expanse:Seasick choir': 0.05,
    'fdn-reverb:Bright air': 0.1,
    'hall-reverb:Bright hall': 0.1,
    'hall-reverb:Airy tail': 0.3,
    'phaser:Saw riser': 0.3,
    'analog-drive:Sheen': 0.3,
    'patina:Hot valve': 0.2,
    'saturator:Sustain bed': 0.5,
    'rotary:Slow burn': 0.1,
    'rotary:Growl': 0,
    'rotary:Parked growl': 0,
    'micro-looper:Lo-fi quarter': 0,
    'micro-looper:Sampler grit': 0,
    'grain-cloud:Sinking spiral': 0.3,
    'tape:Crumbling oxide': 0.1,
    'tape-echo:Worn tape': 0.2,
  },
  recipes: {
    'swell-hall': 1.3,
    'width-hall': 1.4,
    'room-hall': 1.3,
    'hall-tone': 0.8,
    'drive-room': 0.1,
    'width-room': 0.2,
    'echo-hall': 1.8,
    'motion-echo': 1.6,
    'drive-echo-hall': 1.4,
    'echo-room': 0.5,
    'echo-width': 0.5,
    'echo-echo': 0.4,
    'loop-room': 0.4,
    'wear-hall': 1.6,
    'drive-tone': 1.4,
    'wear-hiss': 0.05,
    'drive-hiss': 0.05,
    'wear-echo': 0.6,
    'wear-hiss-hall': 0.1,
    'drive-wear': 1.3,
    'drive-wear-room': 1.2,
    'loop-wear': 0.15,
    'loop-wear-hall': 0.3,
    'motion-hall': 2,
    'drive-motion-hall': 1.4,
    'swell-motion': 1,
    'motion-echo-hall': 1.4,
    'pulse-echo': 0,
    'pulse-hall': 0,
    'pulse-room': 0,
    'tone-pulse': 0,
    'motion-room': 0.2,
    'hold-hall': 2,
    'swell-hold': 1.2,
    'hold-motion': 1.5,
    'hold-motion-hall': 1.5,
    'grain-room': 0.3,
    'grain-wear': 0.3,
    'grain-tone': 0.3,
    'drive-grain': 0.3,
    'hold-wear': 0.4,
    'pitch-hall': 2,
    'swell-pitch-hall': 1.5,
    'pitch-wear': 0.1,
    'swell-room': 0.3,
    'tone-room-hall': 0.5,
    'drive-pitch': 0.3,
    'pitch-room': 0.4,
    'pitch-grain': 0.4,
    'width-ceiling': 0.5,
    'tone-width-ceiling': 0.5,
    'glue-width-ceiling': 0.5,
    'wear-ceiling': 0.5,
    'wear-glue-ceiling': 0.5,
  },
  own: [
    {
      // The pack in one chain: a filter or a level that opens and shuts over seconds, an ensemble, the largest hall.
      id: 'sonoran-breath-ensemble-hall',
      category: 'motion',
      lead: 0,
      count: 6,
      slots: [
        { role: 'motion', devices: ['auto-filter', 'tremolo'], want: ['slow'] },
        { devices: ['chorus'], not: ['fast', 'strange', 'worn'] },
        { role: 'hall', any: ['long', 'wide'], not: ['bright', 'cold', 'narrow'] },
      ],
    },
    {
      // A pattern softened: an analogue echo that fills the gaps between short notes, left in a long hall.
      id: 'sonoran-pattern-softened',
      category: 'echo',
      lead: 0,
      count: 6,
      slots: [
        {
          role: 'echo',
          devices: ['analog-delay', 'tape-echo'],
          not: ['fast', 'strange', 'worn', 'short'],
        },
        { role: 'hall', any: ['long', 'wide', 'dark'], not: ['bright', 'cold', 'narrow'] },
      ],
    },
    {
      // Night insects at half speed: an octave down, each chirp a slow soft pulse in a huge space.
      id: 'sonoran-half-speed-night',
      category: 'pitch',
      lead: 0,
      count: 4,
      slots: [
        { role: 'pitch', devices: ['half-speed'], want: ['low'], not: ['strange', 'fast'] },
        { role: 'hall', any: ['long', 'far'], not: ['bright', 'cold', 'narrow'] },
      ],
    },
    {
      // A drone on the valley floor: a held bed under a low filter, hanging in a space that lasts.
      id: 'sonoran-drone-under-filter',
      category: 'texture',
      lead: 0,
      count: 5,
      slots: [
        {
          role: 'hold',
          devices: ['sustainer', 'pad-follower', 'spectral-blur'],
          not: ['bright', 'cold', 'fast', 'short'],
        },
        { role: 'tone', devices: ['ambient-eq', 'auto-filter'], any: ['dark', 'warm'] },
        { role: 'hall', want: ['long'], not: ['bright', 'cold', 'narrow'] },
      ],
    },
    {
      // Printed to clean tape, or through a warm preamp, and set far back in a long hall.
      id: 'sonoran-printed-and-set-back',
      category: 'tape',
      lead: 0,
      count: 3,
      slots: [
        {
          devices: ['tape', 'patina', 'analog-drive', 'saturator'],
          any: ['clean', 'warm'],
          not: ['worn', 'noisy', 'unsteady', 'bright', 'cold'],
        },
        { role: 'hall', any: ['long', 'far'], not: ['bright', 'cold', 'narrow'] },
      ],
    },
    {
      // Two seconds to speak: the attack taken away, a slow turning thickness, then a hall with no end in sight.
      id: 'sonoran-slow-to-speak',
      category: 'space',
      lead: 2,
      count: 5,
      slots: [
        { role: 'swell', devices: ['swell'], not: ['fast'] },
        { role: 'motion', devices: ['chorus', 'phaser', 'flanger'], want: ['slow'], not: ['cold'] },
        { role: 'hall', any: ['long', 'wide'], not: ['bright', 'cold', 'narrow'] },
      ],
    },
  ],
  heads: [
    'Sonoran',
    'High-desert',
    'Saguaro',
    'Ocotillo',
    'Cereus',
    'Mesquite',
    'Yucca',
    'Palo-verde',
    'Ironwood',
    'Cholla',
    'Agave',
    'Arroyo',
    'Bajada',
    'Playa',
    'Rimrock',
    'Basin',
    'Caliche',
    'Mud-brick',
    'Granite',
    'Dry-lake',
    'Ridgeline',
    'Foothill',
    'Open-range',
    'Moonrise',
    'Moonlit',
    'Starlit',
    'Starfield',
    'Blue-hour',
    'Small-hours',
    'Sundown',
    'Satellite',
    'Porch',
    'Two-lane',
    'Tail-light',
    'Headlight',
    'Power-line',
    'Windmill',
    'Stock-tank',
    'Cattle-guard',
    'Mission',
    'Observatory',
    'Coyote',
    'Katydid',
    'Kit-fox',
    'Elf-owl',
    'Poorwill',
    'Moth-wing',
    'Monsoon',
    'Firelight',
    'Windless',
    'Unfenced',
    'Lamp-lit',
    'Screen-door',
    'Tinaja',
    'Bosque',
    'Cienega',
    'Thunderhead',
    { word: 'Moonless', for: ['dark'] },
    { word: 'Dark-sky', for: ['dark'] },
    { word: 'Far-ridge', for: ['far'] },
    { word: 'Mile-off', for: ['far'] },
    { word: 'All-night', for: ['long'] },
    { word: 'Slow-breath', for: ['slow'] },
    { word: 'Edgeless', for: ['slow'] },
    { word: 'Open-sky', for: ['wide'] },
    { word: 'Sun-warmed', for: ['warm'] },
    { word: 'Deep-basin', for: ['low'] },
    { word: 'High-cirrus', for: ['high'] },
    { word: 'Wind-bent', for: ['unsteady'] },
  ],
  tails: [
    'after dark',
    'at moonset',
    'under stars',
    'in night air',
    'on hardpan',
    'down the wash',
    'off the rim',
    'among cactus',
    'at last light',
    'after rain',
    'on bare rock',
    'in the open',
    'under cirrus',
    'by the road',
    'in the scrub',
    'overhead',
    'in still air',
    'out past town',
    'half asleep',
    'before sunup',
    'by the fire',
    { word: 'under no moon', for: ['dark'] },
    { word: 'miles off', for: ['far'] },
    { word: 'a valley over', for: ['far'] },
    { word: 'till morning', for: ['long'] },
    { word: 'slow as sleep', for: ['slow'] },
    { word: 'rim to rim', for: ['wide'] },
    { word: 'below ground', for: ['low'] },
    { word: 'on warm rock', for: ['warm'] },
  ],
  // Words a title is made of, and the sea and ice words that are not this desert's.
  avoid: [
    'void',
    'spiral',
    'memories',
    'memory',
    'canyon',
    'dust',
    'surge',
    'sunrise',
    'solo',
    'surf',
    'glacier',
    'ice',
    'frost',
  ],
}
