// Stairwell Choir of One: one voice sung into a looper again and again until
// it is a choir, in the reverb a stairwell or a church gives for nothing. Its
// chains are a clean loop, a double or a harmony laid over it, and a very
// large bright room, often one that sings back; little is worn, driven,
// dark or quick, and nothing is broken.

import { type PackPalette } from './types'

export const PALETTE: PackPalette = {
  pack: 'stairwell-choir',
  groups: { space: 27, echo: 26, tape: 6, motion: 7, texture: 12, pitch: 16, master: 6 },
  traits: {
    bright: 1.5,
    long: 1.5,
    wide: 1.4,
    high: 1.4,
    clean: 1.3,
    far: 1.2,
    slow: 1.1,
    frozen: 1.1,
    faint: 0.9,
    heavy: 0.9,
    backwards: 0.9,
    cold: 0.8,
    dark: 0.4,
    low: 0.6,
    unsteady: 0.6,
    short: 0.6,
    narrow: 0.5,
    fast: 0.35,
    worn: 0.2,
    noisy: 0.2,
    strange: 0.15,
  },
  devices: {
    'vowel-reverb': 3.2,
    'micro-looper': 3,
    'hall-reverb': 2.8,
    'echo-memory': 2,
    'ether-reverb': 1.8,
    shimmer: 1.8,
    'stereo-detune': 1.6,
    'pitch-shifter': 1.6,
    lattice: 1.5,
    'tape-loop': 1.4,
    'plate-reverb': 1.4,
    'fdn-reverb': 1.4,
    sustainer: 1.4,
    expanse: 1.1,
    'bloom-reverb': 1.3,
    octaves: 1.2,
    swell: 1,
    chorus: 1.1,
    'ambient-eq': 0.8,
    'reverse-delay': 1,
    cascade: 0.9,
    sympathetic: 0.6,
    'spectral-blur': 0.9,
    'spectral-drifter': 0.8,
    'shaped-reverb': 0.8,
    'pad-follower': 0.7,
    'grain-cloud': 0.7,
    'grain-delay': 0.7,
    rotary: 1.2,
    tape: 1,
    'tape-echo': 0.4,
    'swarm-reverb': 0.3,
    'analog-delay': 0.5,
    'half-speed': 0.5,
    patina: 0.5,
    tremolo: 0.5,
    saturator: 0.4,
    'auto-filter': 0.05,
    'noise-floor': 0.3,
    'analog-drive': 0.25,
    're-amp': 0.15,
    'freq-shifter': 0.1,
    phaser: 0.03,
    flanger: 0.02,
    'spring-reverb': 0,
    glitch: 0.1,
    vinyl: 0,
    'vintage-digital': 0.03,
    'low-bitrate': 0,
    radio: 0,
  },
  voices: {
    'vowel-reverb:Choir of ah': 1.6,
    'vowel-reverb:Cathedral': 1.6,
    'vowel-reverb:High choir': 1.5,
    'vowel-reverb:Low monks': 0.5,
    'hall-reverb:Vast nave': 1.8,
    'hall-reverb:Cathedral': 1.6,
    'ether-reverb:Cathedral': 1.8,
    'ether-reverb:Shining tail': 1.5,
    'micro-looper:Soft bed': 1.5,
    'micro-looper:Clean hold': 1.3,
    'micro-looper:Sampler grit': 0.3,
    'micro-looper:Lo-fi quarter': 0.3,
    'echo-memory:Gathering': 1.8,
    'tape-loop:Clean layers': 2,
    'tape-loop:Two decks': 1.5,
    'sustainer:Stacked harmony': 2,
    'sustainer:Wavering choir': 2.2,
    'shimmer:Rising choir': 1.6,
    'shimmer:Organ loft': 1.4,
    'pitch-shifter:Fifth above': 1.6,
    'pitch-shifter:Octave up': 1.3,
    'pitch-shifter:Rising steps': 1.4,
    'pitch-shifter:Broken choir': 0.3,
    'lattice:Diatonic thirds': 1.5,
    'lattice:Quiet fifth halo': 1.5,
    'lattice:Tuned double': 1.5,
    'chorus:Vocal thickener': 2.5,
    'ambient-eq:Voice': 2,
    'ambient-eq:Bright': 1.5,
    'octaves:Cathedral': 1.5,
    'octaves:Organ': 1.3,
    'grain-cloud:Choir of fifths': 1.5,
    'rotary:Chorale': 2,
    'cascade:Slow staircase': 2.5,
    'stereo-widener:Mono': 0,
    'stereo-widener:Narrow': 0,
    'patina:Eight bit': 0,
    'patina:Shortwave': 0,
    'patina:Kitchen radio': 0,
    'patina:Distant station': 0,
    'patina:Early sampler': 0,
    'noise-floor:Close mic': 2,
    'patina:Muffled sampler': 0.1,
    'patina:Reel pushed hard': 0.1,
    'saturator:Bass grit': 0.2,
    'saturator:Drum bus crunch': 0.2,
    'tape:Needles pinned': 0.2,
    'tape:Crumbling oxide': 0.3,
    'tape:Seasick': 0.3,
    'lattice:Rough high splinters': 0.2,
    'lattice:Minor mirror and drone': 0.3,
    'lattice:Whole tone haze': 0.3,
    'expanse:Fast flutter': 0.3,
    'expanse:Narrow tunnel': 0.3,
    'spectral-drifter:Winter drift': 0.2,
    'spectral-drifter:Splintered': 0.2,
    'spectral-drifter:Scatter': 0.3,
    'tape-echo:Dub wash': 0.3,
    'ambient-eq:Thin': 0.5,
    'ambient-eq:Muffled': 0.4,
    'ambient-limiter:Pinned': 0.3,
    'bloom-reverb:Narrow cellar': 0.2,
    'spectral-blur:Sub bed': 0.3,
    'sympathetic:Sitar drone': 0,
    'rotary:Mono cabinet': 0.3,
    'rotary:Slow burn': 0.3,
    'rotary:Stopped horn': 0.2,
    'rotary:Growl': 0,
    'rotary:Parked growl': 0,
    'grain-cloud:Glass shards': 0.2,
    're-amp:Station platform': 0,
    're-amp:In the cupboard': 0,
    're-amp:Down the hall': 0.3,
    'noise-floor:Old record': 0,
    'noise-floor:Gap crackle': 0,
    'noise-floor:Radio static': 0,
    'noise-floor:Static notes': 0,
    'noise-floor:Amp left on': 0,
    'noise-floor:Mains hum': 0,
    'swell:Loud notes only': 0,
  },
  recipes: {
    'width-hall': 1.8,
    'halo-hall': 1.3,
    'tone-halo': 0.8,
    'swell-halo': 1,
    'swell-hall': 0.8,
    'swell-halo-hall': 1,
    'hall-width': 1.2,
    'tone-hall': 0.8,
    'hall-tone': 0.6,
    'tone-room-hall': 0.8,
    'drive-hall': 0,
    'drive-room': 0,
    'loop-hall': 2.2,
    'loop-tone-hall': 1,
    'tone-loop': 0.8,
    'swell-echo': 0.6,
    'loop-echo': 1.3,
    'echo-halo': 1.3,
    'loop-room': 1.2,
    'echo-hall': 1.2,
    'echo-echo': 0.2,
    'echo-tone': 0.3,
    'motion-echo': 0.3,
    'drive-echo': 0,
    'drive-echo-hall': 0,
    'wear-hall': 2,
    'loop-wear-hall': 2,
    'loop-wear': 1.5,
    'wear-echo': 0.8,
    'tone-wear': 0.6,
    'wear-tone': 0.5,
    'motion-wear': 0.3,
    'wear-hiss': 0,
    'wear-hiss-hall': 0.3,
    'drive-wear': 0,
    'drive-wear-room': 0,
    'drive-tone': 0,
    'drive-hiss': 0,
    'motion-hall': 2,
    'motion-halo': 2,
    'width-motion': 1.3,
    'swell-motion': 0.8,
    'motion-tone': 0.1,
    'pulse-echo': 0,
    'pulse-hall': 0.1,
    'pulse-room': 0,
    'tone-pulse': 0,
    'drive-motion': 0,
    'drive-motion-hall': 0,
    'hold-hall': 2,
    'hold-halo': 2,
    'grain-hall': 1.3,
    'swell-hold': 1,
    'hold-motion-hall': 1.2,
    'swell-room': 0.6,
    'hold-tone': 0.5,
    'grain-tone': 0.5,
    'hold-wear': 0,
    'grain-wear': 0,
    'drive-grain': 0,
    'pitch-hall': 1.8,
    'pitch-halo': 1.5,
    'swell-pitch-hall': 1,
    'pitch-echo-hall': 1.2,
    'pitch-width': 1.2,
    'pitch-hold': 1.2,
    'pitch-tone': 0.5,
    'pitch-grain': 0.5,
    'pitch-wear': 0.3,
    'drive-pitch': 0,
    'tone-ceiling': 1.5,
    'tone-glue-ceiling': 1.2,
    'glue-ceiling': 1.2,
    'width-ceiling': 0.5,
    'tone-width-ceiling': 0.6,
    'glue-width-ceiling': 0.5,
    'drive-ceiling': 0.2,
    'drive-tone-ceiling': 0.2,
    'drive-glue-ceiling': 0.2,
    'wear-ceiling': 0.3,
    'wear-glue-ceiling': 0.3,
  },
  own: [
    {
      // The pack in one chain: a phrase that comes round and is sung over, in a very large bright room.
      id: 'stairwell-choir-round-in-a-tall-room',
      category: 'echo',
      lead: 0,
      count: 6,
      slots: [
        {
          role: 'loop',
          devices: ['micro-looper', 'echo-memory', 'tape-loop'],
          not: ['worn', 'strange', 'fast', 'dark'],
        },
        { role: 'hall', any: ['long', 'wide', 'bright'], not: ['dark', 'strange', 'narrow'] },
      ],
    },
    {
      // The same round in a room whose tail is itself a voice, so that the reverb joins the choir.
      id: 'stairwell-choir-room-sings-back',
      category: 'echo',
      lead: 1,
      count: 5,
      slots: [
        {
          role: 'loop',
          devices: ['micro-looper', 'echo-memory', 'tape-loop'],
          not: ['worn', 'strange', 'fast', 'dark'],
        },
        {
          role: 'halo',
          devices: ['vowel-reverb', 'shimmer'],
          not: ['dark', 'strange', 'narrow', 'low'],
        },
      ],
    },
    {
      // A second part laid above the line before it is looped: a descant over the round, then the room.
      id: 'stairwell-choir-descant-over-the-round',
      category: 'pitch',
      lead: 0,
      count: 5,
      slots: [
        {
          role: 'pitch',
          devices: ['pitch-shifter', 'lattice', 'octaves'],
          any: ['high'],
          not: ['strange', 'cold', 'heavy', 'fast'],
        },
        {
          role: 'loop',
          devices: ['micro-looper', 'echo-memory', 'tape-loop'],
          not: ['worn', 'strange', 'fast', 'dark'],
        },
        { role: 'hall', any: ['long', 'wide', 'bright'], not: ['dark', 'strange', 'narrow'] },
      ],
    },
    {
      // One voice doubled to either side and gathered in a room that sings back.
      id: 'stairwell-choir-doubled-either-side',
      category: 'space',
      lead: 1,
      count: 5,
      slots: [
        {
          role: 'width',
          devices: [
            'stereo-detune',
            'chorus',
            'lattice',
            'pitch-shifter',
            'grain-cloud',
            'grain-delay',
            'pad-follower',
          ],
          not: ['strange', 'unsteady', 'narrow', 'dark', 'worn'],
        },
        {
          role: 'halo',
          devices: ['vowel-reverb', 'shimmer', 'bloom-reverb'],
          not: ['dark', 'strange', 'narrow', 'low'],
        },
      ],
    },
    {
      // A syllable with its start taken off, held as a bed and let go into the big room.
      id: 'stairwell-choir-held-syllable',
      category: 'texture',
      lead: 1,
      count: 4,
      slots: [
        { role: 'swell', devices: ['swell', 'ambient-comp'], not: ['fast'] },
        {
          role: 'hold',
          devices: ['sustainer', 'pad-follower', 'micro-looper', 'spectral-blur'],
          not: ['dark', 'strange', 'low', 'fast'],
        },
        { role: 'hall', any: ['long', 'wide', 'bright'], not: ['dark', 'strange', 'narrow'] },
      ],
    },
    {
      // The little organ beside the voice: octaves drawn like stops, an uneven wind or a slow rotor, the room.
      id: 'stairwell-choir-organ-on-slow-wind',
      category: 'motion',
      lead: 0,
      count: 3,
      slots: [
        {
          presets: [
            'octaves:Organ',
            'octaves:Cathedral',
            'octaves:Late bloom',
            'octaves:Slow halo',
            'octaves:Faint octave',
            'octaves:Slow pedals',
            'pad-follower:Still pipes',
          ],
        },
        {
          role: 'motion',
          devices: ['rotary', 'tremolo'],
          not: ['fast', 'strange', 'narrow'],
        },
        { role: 'hall', not: ['dark', 'strange', 'narrow', 'heavy'] },
      ],
    },
  ],
  heads: [
    'Stairwell',
    'Landing',
    'Banister',
    'Top-landing',
    'Stair-foot',
    'Third-floor',
    'Handrail',
    'Newel-post',
    'Spiral-stair',
    'Three-flight',
    'Top-step',
    'Mid-flight',
    'Fire-stair',
    'Ground-floor',
    'Marble',
    'Tiled',
    'Concrete',
    'Lightwell',
    'Skylit',
    'Tall-window',
    'East-window',
    'Rose-window',
    'Sunbeam',
    'Dust-mote',
    'Daybreak',
    'Empty-pool',
    'Gymnasium',
    'Rotunda',
    'Cupola',
    'Silo',
    'Clapboard',
    'Back-pew',
    'Steeple',
    'Wordless',
    'Sung-over',
    'Hummed',
    'One-voice',
    'Lone',
    'A-cappella',
    'Unaccompanied',
    'Held-breath',
    'Balustrade',
    'Hymn',
    'Psalm',
    'Canon',
    'Motet',
    'Melisma',
    'Antiphon',
    'Plainsong',
    'Vespers',
    'Introit',
    'Offertory',
    'Processional',
    { word: 'Echoing', for: ['long'] },
    { word: 'Long-breath', for: ['slow', 'long'] },
    { word: 'Far-landing', for: ['far'] },
    { word: 'Descant', for: ['high'] },
    { word: 'Soprano', for: ['high'] },
    { word: 'Contralto', for: ['low'] },
    { word: 'Luminous', for: ['bright'] },
    { word: 'Clear-voiced', for: ['clean'] },
    { word: 'Sotto-voce', for: ['faint'] },
    { word: 'Breathless', for: ['frozen'] },
    { word: 'Sung-backward', for: ['backwards'] },
    { word: 'Quavering', for: ['unsteady'] },
  ],
  tails: [
    'up the stairs',
    'on the stairs',
    'on a landing',
    'two floors up',
    'a flight up',
    'by the rail',
    'at stair foot',
    'in bare tile',
    'off the tiles',
    'off concrete',
    'in a dry pool',
    'under a dome',
    'in empty pews',
    'from the pews',
    'after vespers',
    'before mass',
    'on sunday',
    'in low sun',
    'in dust motes',
    'sung alone',
    'sung twice',
    'for one voice',
    'without words',
    'on one breath',
    { word: 'left to ring', for: ['long'] },
    { word: 'a floor away', for: ['far'] },
    { word: 'sung high', for: ['high'] },
    { word: 'sung low', for: ['low'] },
    { word: 'sung backward', for: ['backwards'] },
    { word: 'never let go', for: ['frozen'] },
    { word: 'under breath', for: ['faint'] },
    { word: 'in a sunbeam', for: ['bright'] },
    { word: 'either side', for: ['wide'] },
  ],
  avoid: ['night'],
}
