// Static Cathedral: organ, piano and guitar pushed through broken digital
// gear, a driven stage and a far loudspeaker until the church fills with
// warm static. Its chains are drive, starved streams, old converters and
// smear before anything else, and nearly all of them end in a big stone
// room heard from the far end; little is clean, quick or close.

import { type PackPalette } from './types'

export const PALETTE: PackPalette = {
  pack: 'static-cathedral',
  groups: { space: 16, echo: 8, tape: 28, motion: 7, texture: 22, pitch: 12, master: 7 },
  traits: {
    worn: 1.6,
    noisy: 1.5,
    far: 1.6,
    wide: 1.3,
    heavy: 1.3,
    long: 1.3,
    warm: 1.2,
    unsteady: 1.2,
    strange: 1.1,
    dark: 1.1,
    bright: 0.9,
    backwards: 0.9,
    narrow: 0.9,
    high: 0.5,
    faint: 0.6,
    short: 0.6,
    fast: 0.5,
    clean: 0.45,
  },
  devices: {
    'low-bitrate': 3,
    're-amp': 2.8,
    'analog-drive': 2.5,
    'vintage-digital': 4.5,
    'spectral-blur': 3.5,
    saturator: 1.8,
    radio: 1,
    'grain-cloud': 2.2,
    'noise-floor': 1.6,
    'hall-reverb': 2,
    glitch: 2,
    'ether-reverb': 1.3,
    expanse: 1.3,
    'vowel-reverb': 1.2,
    octaves: 1.2,
    'freq-shifter': 1.5,
    'grain-delay': 0.9,
    'echo-memory': 0.8,
    'micro-looper': 0.8,
    'bloom-reverb': 0.8,
    'shaped-reverb': 0.8,
    'stereo-detune': 0.8,
    swell: 0.8,
    'plate-reverb': 0.7,
    'reverse-delay': 0.7,
    shimmer: 0.6,
    sustainer: 0.7,
    'pad-follower': 0.5,
    tape: 0.3,
    sympathetic: 0.3,
    'tape-loop': 0.25,
    cascade: 0.25,
    tremolo: 0.08,
    chorus: 0.05,
    rotary: 0.05,
    flanger: 0.04,
    phaser: 0.04,
    'tape-echo': 0.1,
    'analog-delay': 0.1,
    lattice: 0.08,
    vinyl: 0,
    'spring-reverb': 0,
  },
  voices: {
    'hall-reverb:Vast nave': 2.5,
    'hall-reverb:Cathedral': 2,
    'expanse:Low cathedral': 1.8,
    'ether-reverb:Cathedral': 1.5,
    'vowel-reverb:Cathedral': 1.5,
    'shimmer:Organ loft': 2.5,
    'octaves:Cathedral': 1.5,
    'analog-drive:Bite': 2,
    'analog-drive:Dark fuzz': 1.6,
    'analog-drive:Torn cone': 1.6,
    're-amp:Far end of the hall': 2,
    're-amp:Down the hall': 2,
    're-amp:Warm stack': 1.5,
    're-amp:Stack flat out': 1.5,
    'low-bitrate:Smeared haze': 2,
    'low-bitrate:Fizzing phases': 1.5,
    'low-bitrate:Frozen stream': 1.5,
    'vintage-digital:Crushed': 1.6,
    'vintage-digital:Rasp': 1.5,
    'pitch-shifter:Broken choir': 2.5,
    'noise-floor:Wall of hiss': 1.8,
    'noise-floor:Radio static': 1.8,
    'radio:Between stations': 1.5,
    'radio:Static wash': 1.5,
    'spectral-blur:Slow dissolve': 1.5,
    'grain-cloud:Thick fog': 1.5,
    'glitch:Skipping disc': 2,
    'glitch:Stuck': 2,
    'glitch:Smears underneath': 1.5,
    'tape:Seasick': 3,
    'chorus:Warped tape': 10,
    'freq-shifter:Seasick': 1.5,
    'freq-shifter:Slow drift': 1.5,
    'auto-filter:Glacial low-pass': 2,
    'sustainer:Wavering choir': 1.5,
    'vowel-reverb:Vowel drift': 1.5,
    'noise-floor:Old record': 0.1,
    'noise-floor:Gap crackle': 0.1,
    'patina:Dusty record': 0.05,
    'patina:Scratched record': 0.05,
    'patina:Worn cassette': 0.2,
    'patina:Falling apart': 0.3,
    'grain-delay:Shimmer wash': 0.2,
    'pitch-shifter:Rising steps': 0.3,
    'shimmer:Sparkle room': 0.2,
    'auto-filter:Touch wah': 0,
    'auto-filter:Squelch': 0,
    'auto-filter:Dub sweep': 0.2,
    'cascade:Rising steps': 0.2,
    'tape-echo:Hovering wash': 0.3,
    'stereo-widener:Mono': 0.2,
    'stereo-widener:Narrow': 0.3,
  },
  recipes: {
    'drive-hall': 2,
    'drive-room': 1.5,
    'tone-hall': 0.8,
    'swell-hall': 0.7,
    'swell-halo': 0.7,
    'drive-echo': 2.5,
    'drive-echo-hall': 3,
    'echo-hall': 1.2,
    'loop-hall': 1.5,
    'echo-echo': 0.4,
    'echo-width': 0.3,
    'echo-halo': 0.3,
    'echo-tone': 0.5,
    'echo-room': 0.6,
    'motion-echo': 0.5,
    'swell-echo': 0.6,
    'tone-loop': 0.5,
    'wear-hall': 2,
    'drive-wear': 2,
    'drive-wear-room': 2,
    'wear-hiss-hall': 1.6,
    'drive-hiss': 1.5,
    'wear-wear': 1.4,
    'wear-hiss': 1.3,
    'loop-wear-hall': 0.6,
    'loop-wear': 0.5,
    'drive-motion': 2,
    'drive-motion-hall': 2.5,
    'motion-hall': 1.5,
    'pulse-echo': 0,
    'pulse-hall': 0.2,
    'pulse-room': 0,
    'tone-pulse': 0,
    'motion-motion': 0.2,
    'width-motion': 0.2,
    'grain-wear': 2,
    'drive-grain': 2,
    'grain-hall': 1.5,
    'hold-wear': 1.6,
    'swell-width': 0.5,
    'pitch-wear': 2,
    'drive-pitch': 1.6,
    'pitch-grain': 1.5,
    'pitch-motion': 0.5,
    'pitch-halo': 0.5,
    'pitch-hall': 1.3,
    'drive-ceiling': 1.5,
    'wear-ceiling': 1.5,
    'drive-tone-ceiling': 1.4,
    'drive-glue-ceiling': 1.4,
  },
  own: [
    {
      // The pack in one chain: a stage driven hard, played through a loudspeaker and heard again from the far end of a stone room.
      id: 'static-cathedral-speaker-in-the-nave',
      category: 'tape',
      lead: 1,
      count: 5,
      slots: [
        {
          role: 'drive',
          devices: ['analog-drive', 'saturator', 'patina'],
          not: ['faint', 'clean'],
        },
        { devices: ['re-amp'], not: ['clean'] },
        { role: 'hall', any: ['long', 'far', 'dark'] },
      ],
    },
    {
      // Too few bits, then smeared until the attacks are gone and only the chord is left, in a hall.
      id: 'static-cathedral-bits-dissolved',
      category: 'texture',
      lead: 1,
      count: 5,
      slots: [
        { role: 'wear', devices: ['vintage-digital', 'low-bitrate'] },
        {
          role: 'grain',
          devices: ['spectral-blur', 'grain-cloud', 'grain-delay'],
          not: ['high', 'fast'],
        },
        { role: 'hall' },
      ],
    },
    {
      // Copies set off their pitch, their phases scattered by failing digital gear, far back in the room.
      id: 'static-cathedral-wavering-copies',
      category: 'pitch',
      lead: 0,
      count: 5,
      slots: [
        {
          role: 'pitch',
          devices: ['pitch-shifter', 'freq-shifter', 'half-speed', 'octaves', 'radio'],
          any: ['unsteady', 'strange', 'low', 'worn'],
        },
        { role: 'wear', devices: ['low-bitrate', 'vintage-digital', 'radio'] },
        { role: 'hall', any: ['far', 'long', 'dark', 'wide'] },
      ],
    },
    {
      // The room first and the fuzz after it, so that the tail itself breaks up.
      id: 'static-cathedral-tail-through-fuzz',
      category: 'space',
      lead: 0,
      count: 5,
      slots: [
        { role: 'hall', any: ['long', 'wide', 'dark'], not: ['faint'] },
        {
          role: 'drive',
          devices: ['analog-drive', 'saturator', 're-amp', 'patina'],
          not: ['faint', 'clean'],
        },
      ],
    },
    {
      // A chord held as a wall, with static standing over it.
      id: 'static-cathedral-held-under-static',
      category: 'texture',
      lead: 0,
      count: 4,
      slots: [
        { role: 'hold', not: ['clean', 'short'] },
        { role: 'hiss', devices: ['noise-floor', 'radio', 're-amp'] },
      ],
    },
    {
      // A loop of the last phrase, bitten by a driven stage and left ringing in the far hall.
      id: 'static-cathedral-loop-in-the-far-hall',
      category: 'echo',
      lead: 0,
      count: 3,
      slots: [
        { role: 'loop', not: ['clean', 'faint'] },
        {
          role: 'drive',
          devices: ['analog-drive', 'saturator', 're-amp'],
          not: ['faint', 'clean'],
        },
        { role: 'hall', any: ['far', 'long'] },
      ],
    },
    {
      // A driven sound whose whole mass sways out of tune or breathes over seconds, in a hall.
      id: 'static-cathedral-swaying-wall',
      category: 'motion',
      lead: 1,
      count: 3,
      slots: [
        {
          role: 'drive',
          devices: ['analog-drive', 'saturator', 're-amp', 'patina'],
          not: ['faint', 'clean'],
        },
        {
          role: 'motion',
          devices: [
            'freq-shifter',
            'tape',
            'expanse',
            'shaped-reverb',
            'sustainer',
            'vowel-reverb',
            'auto-filter',
            'stereo-detune',
          ],
          any: ['unsteady', 'slow'],
          not: ['fast'],
        },
        { role: 'hall', any: ['far', 'long', 'dark', 'wide'] },
      ],
    },
  ],
  heads: [
    'Stone',
    'Nave-end',
    'Transept',
    'Vestry',
    'Rafter',
    'Clerestory',
    'Chancel',
    'Apse',
    'Side-aisle',
    'Belfry',
    'Cloister',
    'Flagstone',
    'Buttress',
    'Lead-roof',
    'Tallow',
    'Soot',
    'Midwinter',
    'Snowbound',
    'Sleet',
    'Thaw',
    'Evensong',
    'Compline',
    'Matins',
    'Advent',
    'Lenten',
    'Unheated',
    'Padlocked',
    'Empty-pew',
    'Draughty',
    'Leaded',
    'Mullion',
    'Boarded-up',
    'Roofless',
    'Derelict',
    'Pillar',
    'Gargoyle',
    'Bell-rope',
    'Bellows',
    'Candle-end',
    'Guttering',
    'Slate',
    'Limestone',
    'Mortar',
    'Whitewashed',
    'North-door',
    'Lychgate',
    'Churchyard',
    'Overcast',
    'Short-day',
    'Blown-fuse',
    'Bad-cable',
    'Scorched',
    'Verdigris',
    'Censer',
    'Brownout',
    'Burnt-out',
    'Loose-wire',
    'Solder',
    'Fuse-wire',
    'Dead-channel',
    'Snow-light',
    'Whiteout',
    'Grey-noon',
    { word: 'Far-end', for: ['far'] },
    { word: 'Snowed-under', for: ['noisy'] },
    { word: 'Crackling', for: ['noisy'] },
    { word: 'Failing', for: ['worn'] },
    { word: 'Cracked', for: ['worn'] },
    { word: 'Buried', for: ['heavy'] },
    { word: 'Sunken', for: ['low'] },
    { word: 'Warped', for: ['unsteady'] },
    { word: 'Lingering', for: ['long'] },
    { word: 'Turned-back', for: ['backwards'] },
    { word: 'Frostbitten', for: ['cold'] },
    { word: 'Unlit', for: ['dark'] },
  ],
  tails: [
    'in the nave',
    'under snow',
    'in stone',
    'through stone',
    'in the loft',
    'at evensong',
    'in the tower',
    'off the walls',
    'in the vestry',
    'past the pews',
    'in midwinter',
    'by candle',
    'under slates',
    'in the crypt',
    'in the roof',
    'after mass',
    'by the font',
    'in the apse',
    'with no heat',
    { word: 'down the nave', for: ['far'] },
    { word: 'in static', for: ['noisy'] },
    { word: 'breaking up', for: ['worn'] },
    { word: 'held for good', for: ['frozen'] },
    { word: 'run backwards', for: ['backwards'] },
    { word: 'wall to wall', for: ['wide'] },
    { word: 'ringing on', for: ['long'] },
    { word: 'in cold stone', for: ['cold'] },
  ],
}
