// Museum Window Garden: a few clear notes in a room that looks out on a
// pond. Its chains are a light chorus, one or two plain repeats and a small
// room or plate; old converters and fresh tape when there is a medium at
// all; nothing is drowned, worn, held for ever or made strange.

import { type PackPalette } from './types'

export const PALETTE: PackPalette = {
  pack: 'window-garden',
  groups: { space: 26, echo: 22, tape: 9, motion: 20, texture: 8, pitch: 8, master: 7 },
  traits: {
    clean: 1.35,
    short: 1.2,
    faint: 1.1,
    bright: 1.15,
    warm: 1.05,
    cold: 0.8,
    narrow: 0.6,
    fast: 0.4,
    dark: 0.45,
    low: 0.25,
    backwards: 0.15,
    far: 0.12,
    noisy: 0.2,
    unsteady: 0.1,
    long: 0.04,
    worn: 0.03,
    heavy: 0,
    strange: 0,
    frozen: 0,
  },
  devices: {
    chorus: 2.1,
    'plate-reverb': 1.7,
    'tape-echo': 1.8,
    'fdn-reverb': 1.4,
    'hall-reverb': 1.5,
    'analog-delay': 1.8,
    'stereo-detune': 1.5,
    'vintage-digital': 1.5,
    tremolo: 1.3,
    phaser: 0.8,
    'ambient-eq': 0.8,
    'ether-reverb': 1.1,
    'micro-looper': 0.8,
    sympathetic: 0.8,
    'echo-memory': 0.7,
    'bloom-reverb': 0.9,
    'swarm-reverb': 0.7,
    'shaped-reverb': 0.7,
    flanger: 0.5,
    octaves: 0.7,
    'pitch-shifter': 0.7,
    lattice: 0.6,
    rotary: 0.6,
    sustainer: 0.6,
    'vowel-reverb': 0.4,
    swell: 0.5,
    'spring-reverb': 0.04,
    'spectral-blur': 0.5,
    patina: 0.5,
    'grain-delay': 0.5,
    expanse: 0.45,
    'analog-drive': 0.8,
    saturator: 0.8,
    shimmer: 0.25,
    cascade: 0.4,
    're-amp': 0.5,
    vinyl: 0.35,
    'reverse-delay': 0.35,
    'auto-filter': 0.2,
    'grain-cloud': 0.3,
    'noise-floor': 0.3,
    'spectral-drifter': 0.25,
    'freq-shifter': 0.2,
    radio: 0.15,
    'half-speed': 0.15,
    'low-bitrate': 0.1,
    glitch: 0.08,
  },
  voices: {
    // The pack's own: a light chorus, a small plate, one repeat, clean tape, old converters.
    'chorus:Classic chorus': 1.5,
    'chorus:Subtle widener': 1.5,
    'plate-reverb:Small plate': 1.3,
    'plate-reverb:Medium plate': 1.1,
    'tremolo:Slow pan': 2,
    'tremolo:Amp tremolo': 3,
    'analog-delay:Dark echo': 1.5,
    'tape-echo:Short and soft': 1.2,
    'swarm-reverb:Pattering': 3,
    'swarm-reverb:Glass rain': 2,
    'freq-shifter:Still water': 6,
    'radio:Clean transistor': 4,
    'vinyl:New pressing': 3,
    'noise-floor:Faint hiss': 3,
    'patina:New tape': 2,
    'vintage-digital:Sampler': 2,
    'vintage-digital:Glaze': 2,
    'lattice:Diatonic thirds': 2.5,
    'octaves:Faint octave': 2,
    'vowel-reverb:Whispering': 2.5,
    'vowel-reverb:Chapel': 2,
    'vowel-reverb:Plain hall': 2,
    'shimmer:Plain hall': 2,
    'shimmer:Sparkle room': 2,
    're-amp:Room underneath': 2,
    're-amp:Just the room': 4,
    'tape-loop:Two decks': 25,
    'tape-loop:Clean layers': 15,
    'tape-loop:Slow fade': 15,
    // Not the pack: fuzz and twang, a squashed mix, notes that take seconds to arrive.
    'saturator:Wavefold lead': 0.03,
    'saturator:Fuzz pedal': 0.03,
    'saturator:Sustain bed': 0.1,
    'saturator:Bass grit': 0.1,
    'saturator:Drum bus crunch': 0.2,
    'rotary:Heavy rotors': 0.1,
    'spectral-blur:Dark water': 0.1,
    'shaped-reverb:Ripples': 0.2,
    'fet-limiter:Drive': 0.2,
    'swell:Backwards': 0.1,
    'flanger:Classic jet': 0.2,
    'flanger:Rising comb': 0.2,
    'shaped-reverb:Gate steps': 0.05,
    'analog-drive:Bite': 0.15,
    'analog-drive:Dark fuzz': 0.05,
    're-amp:Warm stack': 0.1,
    're-amp:Dark and woolly': 0.1,
    're-amp:Stack flat out': 0.05,
    're-amp:Speaker on the edge': 0.1,
    're-amp:In the cupboard': 0.15,
    'rotary:Slow burn': 0.15,
    'tape:Needles pinned': 0.05,
    'tape:Hot glue': 0.15,
    'tape:Hiss and air': 0.3,
    'vintage-digital:Flat tops': 0.05,
    'tremolo:Wide wobble': 0.1,
    'patina:Reel pushed hard': 0.15,
    'patina:Hot valve': 0.15,
    'auto-filter:Touch wah': 0.1,
    'tremolo:Fast shudder': 0.1,
    'tremolo:Side to side': 0.2,
    'flanger:Square chop': 0.1,
    'flanger:Deep dive': 0.2,
    'vinyl:Parlour 78': 0.1,
    'cascade:Drone of fifths': 0.15,
    'freq-shifter:Moving beat': 0.3,
    'freq-shifter:Barber pole': 0.1,
    're-amp:Just the valves': 0.15,
    'auto-filter:Tremolo filter': 0.3,
    'phaser:Two-tone flip': 0.1,
    'shaped-reverb:Gated': 0.02,
    'shaped-reverb:Late wall': 0.05,
    'fet-limiter:Squash': 0.1,
    'fet-limiter:Flattened': 0.05,
    'ambient-limiter:Pinned': 0.03,
    'ambient-comp:Pump': 0.1,
    'ambient-comp:Dense pad': 0.1,
    'ambient-eq:Muffled': 0.2,
    'ambient-eq:Deep': 0.2,
    'spectral-blur:Sub bed': 0.2,
    'vintage-digital:Phone': 0.3,
    'swell:Glacier': 0.05,
    'swell:Sunrise': 0.05,
    'swell:Tide': 0.05,
    'swell:Piano to pad': 0.2,
    // Nor these: caves and naves on the pack's own reverbs, and repeats that hop, climb or flutter.
    'hall-reverb:Cathedral': 0.05,
    'hall-reverb:Vast nave': 0.1,
    'hall-reverb:Far away': 0.1,
    'hall-reverb:Warm undertow': 0.5,
    'fdn-reverb:Dark cave': 0.05,
    'fdn-reverb:Slow swell': 0.1,
    'fdn-reverb:Breathing': 0.2,
    'fdn-reverb:Small bright tank': 0.05,
    'fdn-reverb:Pulsing gate': 0.1,
    'plate-reverb:Long plate': 0.3,
    'expanse:Open space': 0.1,
    'expanse:Thin air': 0.15,
    'fdn-reverb:Open valley': 0.1,
    'shimmer:Rising choir': 0.05,
    'shimmer:Endless ascent': 0.02,
    'shimmer:Fifths': 0.1,
    'shimmer:Late answer': 0.1,
    'sympathetic:Sitar drone': 0.1,
    'bloom-reverb:Wide summer': 0.2,
    'bloom-reverb:Octave halo': 0.2,
    'vowel-reverb:Choir of ah': 0.2,
    'vowel-reverb:Cathedral': 0.1,
    'swarm-reverb:Cavern': 0.1,
    'swarm-reverb:Mine shaft': 0.05,
    'swarm-reverb:Metal pipe': 0.05,
    'ether-reverb:Distant': 0.15,
    'shaped-reverb:Sparkles': 0.15,
    'analog-delay:Octave hop': 0.02,
    'analog-delay:Fifth hop': 0.02,
    'analog-delay:Fluttering': 0.03,
    'lattice:Crystal cascade': 0.1,
    'lattice:Two note drone': 0.3,
    'grain-delay:Crystals': 0.1,
    'grain-delay:Rising fifths': 0.1,
    'pitch-shifter:Rising steps': 0.05,
    'cascade:Slow staircase': 0.1,
    'cascade:Octave stack': 0.2,
    'grain-delay:Falling fourths': 0.1,
    'lattice:Sinking cascade': 0.1,
    'phaser:Endless fall': 0.05,
    'phaser:Saw riser': 0.03,
    'pitch-shifter:Falling steps': 0.05,
    'micro-looper:Fast reverse': 0.2,
  },
  recipes: {
    'width-room': 4,
    'drive-room': 1.5,
    'room-halo': 0.25,
    'hall-width': 0.5,
    'hall-glue': 0.3,
    'room-hall': 1.2,
    'tone-room-hall': 1.6,
    'width-hall': 1.2,
    'tone-hall': 0.7,
    'hall-tone': 0.6,
    'tone-halo': 0.25,
    'drive-hall': 0.5,
    'swell-hall': 0.15,
    'swell-halo': 0.05,
    'halo-hall': 0.03,
    'swell-halo-hall': 0.05,
    'echo-room': 2.5,
    'motion-echo': 2,
    'echo-width': 2,
    'echo-tone': 1.3,
    'loop-room': 0.6,
    'drive-echo': 0.4,
    'echo-halo': 0.15,
    'echo-hall': 0.5,
    'echo-echo': 0.6,
    'tone-loop': 0.4,
    'swell-echo': 0.2,
    'drive-echo-hall': 0.6,
    'loop-hall': 0.3,
    'loop-echo': 0.3,
    'loop-tone-hall': 0.5,
    'wear-room': 2.5,
    'tone-wear': 1.5,
    'motion-wear': 1.5,
    'wear-tone': 1.5,
    'wear-echo': 1.2,
    'wear-hall': 0.6,
    'tone-wear-echo': 0.9,
    'loop-wear': 0.6,
    'drive-wear-room': 0.8,
    'drive-tone': 0.4,
    'loop-wear-hall': 0.4,
    'drive-wear': 0.3,
    'wear-hiss': 0.15,
    'drive-hiss': 0.1,
    'wear-hiss-hall': 0.1,
    'motion-room': 2.5,
    'width-motion': 2,
    'motion-tone': 1.3,
    'motion-hall': 0.6,
    'motion-echo-hall': 1.4,
    'motion-motion': 0.6,
    'motion-halo': 0.05,
    'drive-motion': 0.5,
    'swell-motion': 0.2,
    'pulse-room': 0.15,
    'drive-motion-hall': 0.15,
    'tone-pulse': 0.03,
    'pulse-echo': 0.08,
    'pulse-hall': 0.05,
    'swell-room': 0.5,
    'hold-motion': 1.3,
    'hold-tone': 1.2,
    'swell-width': 0.6,
    'hold-hall': 0.8,
    'grain-tone': 0.7,
    'hold-halo': 0.3,
    'grain-echo': 0.6,
    'grain-room': 0.6,
    'swell-hold': 0.15,
    'hold-motion-hall': 0.9,
    'grain-hall': 0.5,
    'hold-wear': 0.5,
    'grain-wear': 0.4,
    'drive-grain': 0.03,
    'swell-grain-hall': 0.15,
    'pitch-room': 2.5,
    'pitch-width': 1.5,
    'pitch-motion': 1.3,
    'pitch-tone': 1.2,
    'pitch-hall': 0.8,
    'pitch-halo': 0.25,
    'pitch-echo': 0.6,
    'pitch-wear': 0.5,
    'pitch-hold': 0.5,
    'swell-pitch': 0.2,
    'pitch-echo-hall': 0.9,
    'drive-pitch': 0.3,
    'swell-pitch-hall': 0.15,
    'pitch-grain': 0.15,
    'tone-glue-ceiling': 1.3,
    'width-ceiling': 1.2,
    'wear-ceiling': 0.6,
    'wear-glue-ceiling': 0.6,
    'drive-ceiling': 0.5,
    'drive-tone-ceiling': 0.5,
    'drive-glue-ceiling': 0.5,
  },
  own: [
    {
      // The pack in one chain: a light chorus on clear keys, in a small room.
      id: 'window-garden-chorus-in-a-small-room',
      category: 'motion',
      lead: 0,
      count: 6,
      slots: [
        { role: 'motion', devices: ['chorus'], not: ['strange', 'unsteady'] },
        {
          role: 'room',
          devices: ['fdn-reverb', 'hall-reverb', 'plate-reverb', 'ether-reverb', 'bloom-reverb'],
          not: ['dark', 'far', 'narrow', 'fast'],
        },
      ],
    },
    {
      // An early digital keyboard: old converters, doubled a little wide, in a small room.
      id: 'window-garden-early-digital-keys',
      category: 'tape',
      lead: 0,
      count: 4,
      slots: [
        {
          presets: [
            'vintage-digital:Sampler',
            'vintage-digital:Glaze',
            'vintage-digital:Glassy',
            'vintage-digital:Grit bed',
            'patina:Early sampler',
          ],
        },
        { role: 'width', devices: ['chorus', 'stereo-detune'], not: ['strange', 'unsteady'] },
        {
          role: 'room',
          devices: ['fdn-reverb', 'hall-reverb', 'plate-reverb', 'ether-reverb', 'bloom-reverb'],
          not: ['dark', 'far', 'narrow', 'fast'],
        },
      ],
    },
    {
      // One or two plain repeats behind each note, and a small room or plate after them.
      id: 'window-garden-one-repeat-and-a-room',
      category: 'echo',
      lead: 0,
      count: 5,
      slots: [
        {
          role: 'echo',
          devices: ['tape-echo', 'analog-delay'],
          not: ['long', 'unsteady', 'worn', 'strange', 'low'],
        },
        {
          role: 'room',
          devices: ['plate-reverb', 'fdn-reverb', 'hall-reverb', 'ether-reverb', 'bloom-reverb'],
          not: ['dark', 'far', 'fast'],
        },
      ],
    },
    {
      // Drops in a jar under the garden: a patter of short echoes, with a plain short hall behind it.
      id: 'window-garden-patter-of-drops',
      category: 'space',
      lead: 0,
      count: 4,
      slots: [
        {
          presets: [
            'swarm-reverb:Pattering',
            'swarm-reverb:Tight swarm',
            'swarm-reverb:Long scatter',
            'swarm-reverb:Faint scatter',
            'swarm-reverb:Glass rain',
            'shaped-reverb:Scattered',
            'expanse:Hard echoes',
            'spring-reverb:Late splash',
          ],
        },
        { role: 'hall', any: ['clean', 'faint'], not: ['long', 'far', 'heavy', 'dark'] },
      ],
    },
    {
      // A faint pad that grows behind held notes and stops with them, in a small room.
      id: 'window-garden-pad-behind-held-notes',
      category: 'texture',
      lead: 0,
      count: 3,
      slots: [
        {
          role: 'hold',
          devices: ['pad-follower', 'sustainer', 'spectral-blur'],
          not: ['heavy', 'long', 'frozen', 'dark', 'far', 'unsteady'],
        },
        {
          role: 'room',
          devices: ['fdn-reverb', 'hall-reverb', 'plate-reverb', 'ether-reverb', 'bloom-reverb'],
          not: ['dark', 'far', 'narrow', 'fast'],
        },
      ],
    },
    {
      // A soft tone with its own octave, fifth or third faintly above it, in a small room or plate.
      id: 'window-garden-a-little-above-itself',
      category: 'pitch',
      lead: 0,
      count: 4,
      slots: [
        {
          presets: [
            'octaves:Faint octave',
            'octaves:Slow halo',
            'octaves:Twelve string',
            'pitch-shifter:Faint air',
            'pitch-shifter:Octave up',
            'pitch-shifter:Fifth above',
            'lattice:Quiet fifth halo',
            'lattice:Diatonic thirds',
            'lattice:Just intonation triad',
            'grain-delay:Faint glints',
          ],
        },
        {
          role: 'room',
          devices: ['plate-reverb', 'fdn-reverb', 'hall-reverb', 'ether-reverb'],
          not: ['dark', 'far', 'fast'],
        },
      ],
    },
  ],
  heads: [
    'Vitrine',
    'Gallery',
    'Foyer',
    'Courtyard',
    'Veranda',
    'Skylight',
    'Daylight',
    'Forenoon',
    'Midday',
    'Weekday',
    'Museum',
    'Garden',
    'Pondside',
    'Bamboo',
    'Cypress',
    'Pine-shade',
    'Paper-screen',
    'Sliding-door',
    'Tea-room',
    'Porcelain',
    'Celadon',
    'Stone-basin',
    'Stone-path',
    'Raked-gravel',
    'Lantern',
    'Under-eaves',
    'Sill',
    'Pond-skater',
    'Koi-pond',
    'Heron',
    'Sparrow',
    'Wagtail',
    'Camellia',
    'Azalea',
    'Fern',
    'Ginkgo',
    'White-wall',
    'Atrium',
    'Opening-hour',
    'Morning',
    'Early-light',
    'Closed-day',
    'Tatami',
    'Shoji',
    'Overcast',
    'Windless',
    'Drizzle',
    'East-wing',
    'Guest-book',
    'Tea-bowl',
    'Pebble',
    'Brookside',
    'Footbridge',
    'Stoneware',
    'Reading-room',
    'Cloakroom',
    { word: 'Hushed', for: ['faint'] },
    { word: 'Close-walled', for: ['short'] },
    { word: 'Glinting', for: ['bright', 'high'] },
    { word: 'Frosted', for: ['cold'] },
    { word: 'Sun-warmed', for: ['warm'] },
    { word: 'Unhurried', for: ['slow'] },
    { word: 'Wall-to-wall', for: ['wide'] },
    { word: 'Shaded', for: ['dark'] },
    { word: 'Upstairs', for: ['far'] },
    { word: 'Mirrored', for: ['backwards'] },
  ],
  tails: [
    'by the pond',
    'on the sill',
    'at opening',
    'before noon',
    'in the foyer',
    'in a vitrine',
    'under eaves',
    'over moss',
    'on gravel',
    'by the basin',
    'in daylight',
    'on a weekday',
    'among ferns',
    'after drizzle',
    'in the garden',
    'from indoors',
    'at ten',
    'on tatami',
    'by the shoji',
    'in pine shade',
    'by the hedge',
    'on a bench',
    'by the door',
    'for one room',
    { word: 'left plain', for: ['clean'] },
    { word: 'kept small', for: ['short'] },
    { word: 'in no hurry', for: ['slow'] },
    { word: 'in the shade', for: ['dark'] },
    { word: 'past the pane', for: ['far'] },
  ],
  // Nouns that after this pack's words would read as a title, and two that read badly beside a bird or a paper screen.
  avoid: [
    'air',
    'box',
    'cloud',
    'copy',
    'heads',
    'horizon',
    'ice',
    'loft',
    'rain',
    'shards',
    'signal',
    'static',
    'water',
    'waves',
  ],
}
