// GENERATED by scripts/gen-devices.mjs from device.json. Do not edit.
//
// Parameter ids and ranges of Ring, shared with
// src/dsp/devices/ring.gen.ts:
//    0  root: 0 C, 1 C#, 2 D, 3 D#, 4 E, 5 F, 6 F#, 7 G, 8 G#, 9 A, 10 A#, 11 B, default 0
//    1  octave: 0..7, default 4
//    2  fine: -100..100 ct, default 0
//    3  tune: 0 Note, 1 Free, default 0
//    4  frequency: 0.5..4000 Hz, default 6
//    5  wave: 0 Sine, 1 Triangle, 2 Soft square, 3 Diode, default 0
//    6  second: 0 Off, 1 Fifth, 2 Octave, 3 Octave below, default 0
//    7  drift: 0..1, default 0.25
//    8  lowCut: 20..2000 Hz, default 150
//    9  tone: 300..16000 Hz, default 7000
//   10  width: 0..1, default 0.5
//   11  mix: 0..1, default 0.4

#pragma once

namespace livemix {
namespace ring {

enum Param : int {
  kRoot = 0,
  kOctave = 1,
  kFine = 2,
  kTune = 3,
  kFrequency = 4,
  kWave = 5,
  kSecond = 6,
  kDrift = 7,
  kLowCut = 8,
  kTone = 9,
  kWidth = 10,
  kMix = 11,
  kNumParams = 12,
};

inline constexpr float kParamMin[kNumParams] = {0.0f, 0.0f, -100.0f, 0.0f, 0.5f, 0.0f, 0.0f, 0.0f, 20.0f, 300.0f, 0.0f, 0.0f};
inline constexpr float kParamMax[kNumParams] = {11.0f, 7.0f, 100.0f, 1.0f, 4000.0f, 3.0f, 3.0f, 1.0f, 2000.0f, 16000.0f, 1.0f, 1.0f};
inline constexpr float kParamDefault[kNumParams] = {0.0f, 4.0f, 0.0f, 0.0f, 6.0f, 0.0f, 0.0f, 0.25f, 150.0f, 7000.0f, 0.5f, 0.4f};

}  // namespace ring
}  // namespace livemix
